### ISSUE TITLE
tags are only processed in posts, not in pages

### ISSUE THREAD

**Issue by damiencourousse** [getnikola/nikola#1014]
hello !

I am a new user of Nikola v6.2.

I cannot have tags generated for pages (aka stories), but the tags are correctly processed for posts.
How to configure the build so that tags are not only searched in posts ?

For example with this configuration :
(nikola init --demo)

```python
POSTS = (
    ("posts/*.rst", "posts", "post.tmpl"),
    ("posts/*.txt", "posts", "post.tmpl"),
)
PAGES = (
    ("stories/*.rst", "stories", "story.tmpl"),
    ("stories/*.txt", "stories", "story.tmpl"),
)

NAVIGATION_LINKS = {
    DEFAULT_LANG: (
        ('/stories/news.html', 'News'),
        ('/categories/index.html', 'Tags'),
        ('/rss.xml', 'RSS'),
    ),
}
```

The generated file categories/index.html does only show the tags contained in the posts, but not in the pages.

Is it a problem of configuration, or a bug ?

regards,
Damien

**Comment by ralsina** [comment]
I say a).
