### ISSUE TITLE
[idea] redesign for bootstrap via the BS3.1.0 new blog example

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1018]
Look at this gem: http://getbootstrap.com/examples/blog/

Maybe we could make our bootstrap theme(s) look more like this (not a 1:1 copy though), making Nikola a bit nicer and giving it a more professional feeling?  Or, alternatively, re-implement it as a theme in the themes repo?  Any opinions?

**Comment by Kwpolska** [comment]
Nobody cares.

**Comment by ralsina** [comment]
I do care, I just forgot about this one.

**Comment by Kwpolska** [comment]
Awesome!

(It should not be hard to do, most of this theme is [applying some CSS](http://getbootstrap.com/examples/blog/blog.css))

**Comment by Kwpolska** [comment]
taking this.

**Comment by Kwpolska** [comment]
Done: getnikola/nikola-themes#46
