### ISSUE TITLE
write our own reST stylesheets

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1150]
The default ones are straight out of 1999 with their `border: medium outset`.

**Comment by ralsina** [comment]
Took a look at this, feels moumentally boring, need a brave volunteer :-)

**Comment by ralsina** [comment]
I am just removing the most nutzo bits of rst.css: d3fd6708766224cf43b003f4ae21903107d2014b 0e2b91697511e530be228d5a7805a562bb919a7d defa4e4afb41d3cdb8d543b99e616686790cc6ed

**Comment by ralsina** [comment]
Closing, marked as http://giphy.com/gifs/3b1JW7LxfsAKs

**Comment by Kwpolska** [comment]
I’m bored, so I just did this.  PR upcoming.
