### ISSUE TITLE
Octopress Importer

### ISSUE THREAD

**Issue by michaeljoseph** [getnikola/nikola#1165]

**Comment by ralsina** [comment]
There's a bunch of these. I think "someone" should review them and bless one by stealing it. 

https://github.com/mikemccracken/nikola-octopress-import is another one.

**Comment by ralsina** [comment]
@magmax want to turn this into a plugin? I can guide you, that way it will be easily available to users.

**Comment by magmax** [comment]
Yes. Indeed... I already did it :D

The plugin: https://github.com/getnikola/plugins/tree/master/v7/import_jekyll
The nikola page about the plugin: http://plugins.getnikola.com/#import_jekyll

**Comment by ralsina** [comment]
@magmax Closing then :)
