### ISSUE TITLE
Existence of Markdown post in Wordpress imported site prevents math from working

### ISSUE THREAD

**Issue by asmeurer** [getnikola/nikola#1185]
From the mailing list. Steps to reproduce:

- Go to https://github.com/asmeurer/blog.  I am on 6bdc97fa556b34a80601ac84dd4dd714f1db6b53.
- `nikola build`
- Notice the math in output/posts/2013/03/03/when-does-xlogy-ylogx.html
- `rm posts/moving-to-github-pages-with-nikola.m*`
- `nikola build`
- Notice the math in the same page

**Comment by ralsina** [comment]
Putting those two posts in an empty site with default config + your mathjax config works.
Adding your conf, it breaks.

So, it's something in the configuration!

Careful experimentation shows this to be the guilty piece. This line renders differently with the default configuration and yours:

Default config:
```
'<p>A discussion on a\xc2\xa0<a href="https://github.com/sympy/sympy/pull/1845">pull request</a>\xc2\xa0got me thinking about this question: what are the solutions to the complex equation $latex x^{\\log{(y)}} = y^{\\log(x)}$? \xc2\xa0At the outset, they look like different expressions. \xc2\xa0But clearly there some solutions. For example, if $latex x = y$, then obviously the two expressions will be the same. \xc2\xa0We probably should exclude $latex x = y = 0$, though note that even if $latex 0^{\\log(0)}$ is well-defined (probably if it is it is either 0 or complex $latex \\infty$), it will be the same well-defined value. But for the remainder of this blog post, I\'ll assume that $latex x$ and $latex y$ are nonzero.</p>'
```

Your config:
```
'<p>A dis\xc2\xadcus\xc2\xadsion on a\xc2\xa0 <a href="https://github.com/sympy/sympy/pull/1845">pull re\xc2\xadquest</a> \xc2\xa0got me think\xc2\xading about this ques\xc2\xadtion: what are the so\xc2\xadlu\xc2\xadtions to the com\xc2\xadplex equa\xc2\xadtion $la\xc2\xadtex x^{\\log{(y)}} = y^{\\log(x)}$? \xc2\xa0At the out\xc2\xadset, they look like dif\xc2\xadfer\xc2\xadent ex\xc2\xadpres\xc2\xadsion\xc2\xads. \xc2\xa0But clear\xc2\xadly there some so\xc2\xadlu\xc2\xadtion\xc2\xads. For ex\xc2\xadam\xc2\xadple, if $la\xc2\xadtex x = y$, then ob\xc2\xadvi\xc2\xadous\xc2\xadly the two ex\xc2\xadpres\xc2\xadsions will be the same. \xc2\xa0We prob\xc2\xada\xc2\xadbly should ex\xc2\xadclude $la\xc2\xadtex x = y = 0$, though note that even if $la\xc2\xadtex 0^{\\log(0)}$ is well-de\xc2\xadfined (prob\xc2\xada\xc2\xadbly if it is it is ei\xc2\xadther 0 or com\xc2\xadplex $la\xc2\xadtex \\in\xc2\xadfty$), it will be the same well-de\xc2\xadfined val\xc2\xadue. But for the re\xc2\xadmain\xc2\xadder of this blog post, I\'ll as\xc2\xadsume that $la\xc2\xadtex x$ and $la\xc2\xadtex y$ are nonze\xc2\xadro.</p> '
```

Further research needed :-P

**Comment by Kwpolska** [comment]
For reST-based blogs, we could probably add an exception for hyphenating (`.math`), if anyone cares.

**Comment by ralsina** [comment]
I hope noone ever does. Debugging this killed me a little.

**Comment by asmeurer** [comment]
Thanks for debugging this. Hyphenation probably isn't worth it for me if it will break math.

**Comment by ralsina** [comment]
Agreed. Sorry it took me a year and a half to do it :-(

**Comment by entron** [comment]
I maybe have a similar problem and the math is not rendering even I used the default HYPHENATE settings. Here is [the post](http://entron.github.io/boke/posts/2014/08/31/li-jie-hong-lou-meng-yao-yong-yin-xing-ma-er-ke-fu-mo-xing.html), and here is the [blog repo](https://github.com/entron/boke/tree/master).

**Comment by Kwpolska** [comment]
Markdown uses backslashes for certain escapes and thus requires `\\[double backslashes\\]` for math.

**Comment by entron** [comment]
This means the handbook is wrong because the example is:

```
\[\int \frac{dx}{1+ax}=\frac{1}{a}\ln(1+ax)+C\]
```

**Comment by Kwpolska** [comment]
It isn’t *wrong*. It is how the output HTML should look like, and how input HTML looks like. Markdown, however, does backslash escapes for some characters, and thus requires double backslashes. I added a note to the handbook (on master).
