### ISSUE TITLE
Find a way to access templates from posts

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1227]
This is a similar idea to pelican's [liquid tags plugin](https://github.com/getpelican/pelican-plugins/tree/master/liquid_tags) but let's do it better.

The idea would be a block in the post content where you can use template markup. In reSt this could be done using a directive (ignore the name):

```
.. templated::

   This post is tagged 
   %for tag in post.tags():
       ${tag} 

```

While not terribly useful by itself, it would allow things like the series plugin to work in a very seamless way that integrates nicely with the post's text flow.

Also, it doesn't look horribly hard to do in reSt and in markdown it could be as simple as a fenced section.

**Comment by Kwpolska** [comment]
(1) yes (2) have fun rewriting all posts (3) whatever is required to be compatible with everyone — probably a rest directive also available as a shortcode

**Comment by ralsina** [comment]
Indeed a shortcode/directive for this is stupid simple to write!

After @kwpolska added the global context to shortcodes, and since shortcode arguments are passed to templates ... this is really really easy.
