### ISSUE TITLE
Need help installing Nikola

### ISSUE THREAD

**Issue by esc** [getnikola/nikola#1240]
Hi,

I tried installing Nikola from PyPi today and can't get it to run.

I am using Debian stable and Anaconda 1.9.2.

I tried installing from PyPi using `pip install nikola`. I couldn't compile `pillow` due to missing X11 headers, so I did a `sudo aptitude install xorg-dev` and then the pip install ran through.

Next trouble I encountered:

```
zsh» nikola post
Scanning posts....done!
[2014-04-14T19:55:18Z] ERROR: Nikola: In order to render galleries, you must install the "pillow" Python package.
[2014-04-14T19:55:18Z] ERROR: Nikola: Exiting due to missing dependencies.
```

I then tried installing current master from git (a082ca3fbfcc27c34948178a8dab1a920f796e11) but that didn't solve my Problem.

I then tracked it down to:

```
In [1]: from PIL import  Image
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-206fa461ef2c> in <module>()
----> 1 from PIL import  Image

/home/esc/anaconda/lib/python2.7/site-packages/PIL/Image.py in <module>()
     51     # them.  Note that other modules should not refer to _imaging
     52     # directly; import Image and use the Image.core variable instead.
---> 53     from PIL import _imaging as core
     54     if PILLOW_VERSION != getattr(core, 'PILLOW_VERSION', None):
     55          raise ImportError("The _imaging extension was built for another "

ImportError: libjpeg.so.62: cannot open shared object file: No such file or directory

```

Which is unfortunately masqueraded by the line:

```
        if Image is None:
            req_missing(['pillow'], 'render galleries')
```

in `nikola/plugins/task/galleries.py`

Anyay, I guess there are two issues here, the first is that the Import error is masqueraded and Nikola incorrectly reports that `pillow` is not installed and the second is the issue with pillow itself.

Help? Is there anyway to disable using galleries? I just want to try some RST blog posts.

**Comment by muxuezi** [comment]
Maybe pillow had broken when `pip install pillow` and gcc compile it, you cat install pillow again.
```
pip uninstall pillow
pip install pillow
```
I fix it :-)
