### ISSUE TITLE
mathjax always comes from a CDN

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1259]
We use mathjax from their CDN.  Some people might not like that, we should let them use their own servers.

**Comment by ralsina** [comment]
So, any ideas how to do this? :-)

**Comment by Kwpolska** [comment]
I recommend *not at all* — it’s a waste of resources and time, and if someone has unlimited bandwidth, disk space and a tin foil hat, they can just figure out how to set it up themselves.

You see, we would need to shove MathJax down everyone’s throat, unless we developed some system to download and include MathJax only when the user asks us to.  And nobody will, especially if we were to provide some helpful stats alongside the option.

If we were to include mathjax from bower, the uncompressed size of our git repo/tarballs would grow by **176 megabytes**, and our sites would grow by **155 megabytes** (and an empty site is 2.5 MB right now — in other words, that’s a **62× increase**).  Nikola would take forever to download and install (and people would just kill `pip` and never come back), sites would take forever to build for the first time, and people might even have to pay a lot of real money for this misfeature.

*Close at will, unless someone really wants to implement this (as a plugin or an option buried in the config with some download command).  Also, the numbers changed quite dramatically in the past 364.75 days…*

**Comment by ralsina** [comment]
Closing. Happy birthday Issue #1259 !

**Comment by damianavila** [comment]
:birthday:
