### ISSUE TITLE
Refactor metadata extraction

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1278]
Parts of it can be refactored into format-specific extractors (in the compiler plugins) which would get it from places like the docutils document metadata.

**Comment by ralsina** [comment]
One concern is that to get the metadata we need to parse the thing. So, we may need to cache the intermediate representation (like the doctree in rst)

**Comment by Kwpolska** [comment]
We already have `read_metadata()` (#1603), used by eg. `ipynb`: https://github.com/getnikola/nikola/blob/master/nikola/plugins/compile/ipynb.py#L125

Its performance is not perfect (we read files twice), but that’s fixable too if it’s a concern.

**Comment by ralsina** [comment]
Ok, so if I implemented read_metadata in, say, the reSt compiler, that would do things. I may take a shot at it.

**Comment by Kwpolska** [comment]
For #1923, perhaps? (feel free to take it over, I didn’t get much stuff done for that)

**Comment by ralsina** [comment]
Yes, that too. We could even use yaml metadata or whatever.

**Comment by ralsina** [comment]
There are now metadata extractors in the reSt, markdown and ipynb compilers. I say, let's close.
