### ISSUE TITLE
Image metadata support

### ISSUE THREAD

**Issue by devurandom** [getnikola/nikola#1286]
It would be great if metadata could be added to images. This could then be displayed in the galleries, e.g. as a caption below the image.

Process could be as follows:
1. Extract metadata from `image.jpg`, i.e. EXIF
2. Add/replace with data from `image.jpg.meta`, e.g. `.. caption: …` or `.. date: …`
3. Generate captions, etc.

Step 1 is just mentioned for completeness and describes only a minor and distant wish. This request is primarily about steps 2 and 3.

**Comment by devurandom** [comment]
Related to #786?

**Comment by guyou** [comment]
I started a feature branch on this topic:
https://github.com/guyou/nikola/tree/feature-images-metadata

It is quite functionnal and expect your review.

**Comment by BryanQuigley** [comment]
Would this let me do something like https://irongiantdesign.com ?

IN this case it's implemented in Wordpress posts and just displays the first picture in the post.  Thanks!

**Comment by Kwpolska** [comment]
@BryanQuigley No, but you can just use the existing `previewimage` meta field on posts and create custom templates that make use of it.
