### ISSUE TITLE
Language links should point to the same page in the other language and not the index

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1287]
This would be a nice thing to have — our language links (in the menu) are quite misleading, and make the user search further.  (if we don’t have this page in $CHOSEN_LANGUAGE, fallback to index, of course)

It looks like we'd need:

- [ ] A function that given a URL (the current page's permalink) tells you the equivalente URL in other languages (sort of the reverse of Nikola.path)
- [ ] A way to tell if those pages actually exist or if they don't because of missing translations?

hecking the code ... well, we have some problems :-)

The main problem is that we don't have a generic way to get either:

1. internal object + lang -> path

nor

2. path -> internal object + lang

For 1. we are rather close, with Nikola.path but not really (for example, post paths are not obtained that way). For 2. not even close.

One way to do this would be:

- [ ] Add the missing path registrations
- [ ] Add a method to plugins where they would record ALL their paths, based on timeline, internal data of the Nikola object, etc.
- [ ] Use that to "record" to go back & forth, so we can do
- [ ] Have some debugging mode that lets us see unregistered paths so we can make sure we register them

path -> internal object + lang -> change lang -> new path

It's a large branch, but the good news is: it's not incompatible! So I can attack it slowly.

**Comment by e2jk** [comment]
In https://github.com/getnikola/nikola/issues/1008#issuecomment-69285656 I argue about reopening this issue, as these are not true duplicates. Correct, fixing this issue #1287 would indeed fix #1008, but this is *an enhancement* which requires a bit more complex logic (to handle non-translated pages) while #1008 is *actually a bug* which prevents accessing the index page of a non-blog site in another language without manually fiddling with the URL in the browser.

Please reopen this issue, so that #1008 can be fixed easily, and we work later on this enhancement #1287.

By the way, regarding non-translated posts, can

**Comment by e2jk** [comment]
Thanks for reopening.
Maybe a minor question, but should this be labeled as bug (as just set) or as enhancement (as used to be the case prior to closing as duplicate)?

**Comment by Kwpolska** [comment]
The links are not intuitive — especially because the language links in posts already do the right thing.  I’d call this a bug.

Here’s a design idea for this: objects should provide arguments for `site.linkas part of the context.

**Comment by ralsina** [comment]
So, what we would need to fix this is:

- [ ] A function that given a URL (the current page's permalink) tells you the equivalente URL in other languages
- [ ] A way to tell if those pages actually exist or if they don't because of missing translations?

**Comment by Aeyoun** [comment]
UI wise, its common to only display the language the current page is available in. Untranslated means it doesn’t exist so the link makes no sense.

**Comment by ralsina** [comment]
Checking the code ... well, we have some problems :-)

The main problem is that we don't have a generic way to get either:

1. internal object + lang -> path

nor

2. path -> internal object + lang

For 1. we are rather close, with Nikola.path but not really (for example, post paths are not obtained that way). For 2. not even close.

One way to do this would be:

- [ ] Add the missing path registrations
- [ ] Add a method to plugins where they would record ALL their paths, based on timeline, internal data of the Nikola object, etc.
- [ ] Use that to "record" to go back & forth, so we can do

path -> internal object + lang -> change lang -> new path

It's a large branch, but the good news is: it's not incompatible! So I can attack it slowly.

**Comment by ralsina** [comment]
Closing as wontfix.

Rationale:

1. Doing "the right thing" is very hard
2. Doing "the right thing" is not necessary in the important cases! For posts and pages, we already can provide those links.

**Comment by Kwpolska** [comment]
I have some sort of simple idea for doing this, and if I get lazy one day, I might implement it.  Long story short: provide URLs for the picker from within the context in `render_template`.  For example, `GLOBAL_CONTEXT['language_links']` would contain links to `root` and `context['language_links']` in a post would overwrite that with translations for the post.

But for now, let’s leave it closed.  (hopefully I will get lazy before v8 gets released…)
