### ISSUE TITLE
Disabling plugin "generate_rss" precludes generating a RSS via a personal plugin

### ISSUE THREAD

**Issue by jcea** [getnikola/nikola#1307]
In Nikola 6.4 I disabled stock "generate_rss" and provided a new personal plugin to generate RSS in a different way.

That trick is not working anymore in Nikola 7.0: when adding "generate_rss" to "DISABLED_PLUGINS" in "conf.py", Nikola AUTOMATICALLY sets "GENERATE_RSS=False" and it is not generating RSS links neither running my custom RSS plugin.

For me would be enough if I could override/extend the Nikola RSS machinery without disabling stock "generate_rss" plugin.

Ideas welcomed.

**Comment by jcea** [comment]
Kwpolska, I only need this change in Nikola to enable my own RSS generator:

```
--- nikola.py   2015-01-17 21:39:50.000000000 +0100
+++ /home/jcea/hg/virtualenv-nikola/lib/python2.7/site-packages/nikola/nikola.py2014-06-09 14:24:36.701459964 +0200
@@ -453,11 +453,13 @@

         # Disable RSS.  For a successful disable, we must have both the option
         # false and the plugin disabled through the official means.
-        if 'generate_rss' in self.config['DISABLED_PLUGINS']:
-            self.config['GENERATE_RSS'] = False

-        if not self.config['GENERATE_RSS'] and 'generate_rss' not in self.config['DISABLED_PLUGINS']:
-            self.config['DISABLED_PLUGINS'].append('generate_rss')
+        # JCEA: ver bug https://github.com/getnikola/nikola/issues/1307
+        #if 'generate_rss' in self.config['DISABLED_PLUGINS']:
+        #    self.config['GENERATE_RSS'] = False
+
+        #if not self.config['GENERATE_RSS'] and 'generate_rss' not in self.config['DISABLED_PLUGINS']:
+        #    self.config['DISABLED_PLUGINS'].append('generate_rss')

         # PRETTY_URLS defaults to enabling STRIP_INDEXES unless explicitly disabled
         if self.config.get('PRETTY_URLS') and 'STRIP_INDEXES' not in config:
```

The problem is that I can not replace the Nikola stock RSS generator with my own version. Give me back that option! :).

**Comment by Kwpolska** [comment]
What do you need to do to make the replacement, exactly?  Would you mind providing some details on how your replacement worked before, how it looks, how it integrates with Nikola?

**Comment by jcea** [comment]
I explained my personalized RSS plugin previously in this thread, but I think that it mudded the waters.

Simple explanation:

1. Currently Nikola doesn't allow you to personalize RSS in any way.

2. Before Nikola 7.0, you could disable internal Nikola RSS plugin and use your own personalized plugin.

3. Since Nikola 7.0, disabling the internal Nikola RSS (via conf.py) will disable RSS generation altogether. personalized RSS plugin will be ignored, since RSS is disabled.

I have patched this myself:

```
--- nikola.py   2015-01-17 21:39:50.000000000 +0100
+++ /home/jcea/hg/virtualenv-nikola/lib/python2.7/site-packages/nikola/nikola.py2014-06-09 14:24:36.701459964 +0200
@@ -453,11 +453,13 @@

         # Disable RSS.  For a successful disable, we must have both the option
         # false and the plugin disabled through the official means.
-        if 'generate_rss' in self.config['DISABLED_PLUGINS']:
-            self.config['GENERATE_RSS'] = False

-        if not self.config['GENERATE_RSS'] and 'generate_rss' not in self.config['DISABLED_PLUGINS']:
-            self.config['DISABLED_PLUGINS'].append('generate_rss')
+        # JCEA: ver bug https://github.com/getnikola/nikola/issues/1307
+        #if 'generate_rss' in self.config['DISABLED_PLUGINS']:
+        #    self.config['GENERATE_RSS'] = False
+
+        #if not self.config['GENERATE_RSS'] and 'generate_rss' not in self.config['DISABLED_PLUGINS']:
+        #    self.config['DISABLED_PLUGINS'].append('generate_rss')

         # PRETTY_URLS defaults to enabling STRIP_INDEXES unless explicitly disabled
         if self.config.get('PRETTY_URLS') and 'STRIP_INDEXES' not in config:
```

**Comment by Kwpolska** [comment]
Wait, you are actually running outdated code.

In 8999de0d100d99027bdb7386eec7f0e9e9cefdf1, which made it into Nikola v7.0.1, in **May 2014**, I added a kludge for your use case.  It was also [explained](https://github.com/getnikola/nikola/commit/8999de0d100d99027bdb7386eec7f0e9e9cefdf1#commitcomment-6498655) there, on your request.

If you were to upgrade to v7.3.0, the hack described in the commit should work fine.
