### ISSUE TITLE
new_page [path] relative to conf.py not $PWD

### ISSUE THREAD

**Issue by tritium21** [getnikola/nikola#1325]
Steps to replicate:

    (site)tritium@gesa:~$ nikola init -q foo
    [2014-06-12T10:37:00Z] INFO: init: Created empty site at foo.
    (site)tritium@gesa:~$ cd foo
    (site)tritium@gesa:~/foo$ cd stories
    (site)tritium@gesa:~/foo/stories$ mkdir bar
    (site)tritium@gesa:~/foo/stories$ cd bar
    (site)tritium@gesa:~/foo/stories/bar$ nikola new_page -t 'Spam' ./spam.txt
    Creating New Page
    -----------------
    
    Title: Spam
    Scanning posts....done!
    [2014-06-12T10:37:46Z] INFO: new_page: Your page's text is at: ./spam.txt
    (site)tritium@gesa:~/foo/stories/bar$ tree ~/foo
    /home/tritium/foo
    ├── conf.py
    ├── conf.pyc
    ├── files
    ├── galleries
    ├── listings
    ├── posts
    ├── spam.txt
    └── stories
        └── bar
    
    6 directories, 3 files
    (site)tritium@gesa:~/foo/stories/bar$

This struck me as entirely counter-intuitive, as traditionally, command line applications specify paths relative to $PWD, not an arbitrary file (conf.py).  In attempting to work around #1326, this was discovered.

A proposed new semantics for the command is to assume that all paths giving in to the ``new_page`` and ``new_post`` commands be relative to $PWD.

* This matches the expectation of users familiar with command line tools (very few tools that accept relative paths will treat them as anything but relative to $PWD)
* This should not greatly affect users familiar with the current semantics; the current semantics would still be valid if the user is currently in the root (conf.py) directory of the project.

**Comment by ralsina** [comment]
I don't understand what new behaviour this change allows. If it doesn't let you do anything new, then what does it fix?

Maybe we should close this issue and replace it with a proposed feature one instead?

**Comment by tritium21** [comment]
Note to future viewers: the original bug report was updated at this point.
