### ISSUE TITLE
Ambiguities in testing

### ISSUE THREAD

**Issue by ccanepa** [getnikola/nikola#1339]
### Testing Use Cases

1 Test the correctness of the WC
2 Test the correctness of the installed Nikola
3 CI tests
#### The tests always ends importing nikola from the WC or unzipped download
- This precludes the use case 2.
- Makes windows testing confusing, like 'pip install . && test' -> failures while 'setup.py install &&  test' -> success (this related to symlinks and implementation details in pip vs setuptools)
#### But some tests always ends using the installed nikola package

This harms the use case 1 because
- if dev forgets to install before testing, it will be testing a mix of two nikola versions
- if never installed some tests will fail with misleading messages  
#### inconditionally importing nikola from the WC
- When py.test sees an `__init__.py` in tests/ it inserts the WC dir as the first entry in sys.path, so python will find nikola at that directory. That init is needed for the relative imports in tests, aka `from .base import ...`
- Additionally, theres a common paragraph at the beginning of each test doing the `__file__ bla bla sys.path` trick, which I think comes from the nosetest era or before

**Preventing this hardcoding**
- move test/ -> test/test_crypt fixes 1st problem
-  remove (or augment with some environ conditional) the common paragraph

**Serving all the use cases**
The test runner can't guess if use 1 or 2 is wanted, an explicit setting is needed.

Most discoverable would be a parameter to the test runner. ( Don't know what the standard way to do this with py.test is, is anyone know please post ) 

Clunky but feasible: set an environ variable, make the common paragraph respect the selection
#### mixed nikola versions in testing

This is caused by calls of the form `os.system("nikola bla bla")` in test code 

**fix**
`os.system(python -c "import sys; from nikola.__main__ import main; main(sys.argv[])` ?

ugh. needs work about which python, quoting for win/linux.

suggestions ?
### What about CI ?

I think we want CI runs go as a case 2, test installed nikola.

When we can select between case 1 and case 2 it is a matter of setting the correct test parameter for the CI run.

With current test code, we can rename nikola/ ->  blalz/ after installation but before running tests to fall in a clean case 2.

Edited: added to problems by 'tests always importing nikola from WC

**Comment by ralsina** [comment]
Clearly noone cares enough to do this, and/or current tests do work reliably enough.
