### ISSUE TITLE
SHOW_UNTRANSLATED_POSTS=False leads to 404s in archives

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1360]
Even though SHOW_UNTRANSLATED_POSTS=False, archives still display posts that do not exist, leading to 404s everywhere.

**Comment by ralsina** [comment]
So, is this fixed @Kwpolska ?

**Comment by Kwpolska** [comment]
No, and I don’t know why.

**Comment by Kwpolska** [comment]
It assigned to `archdata[year]` instead of `posts`, so the change wasn’t picked up.  Works correctly now.
