### ISSUE TITLE
Make it possible to use SASS/LESS with bundles

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1370]
via @padelt on IRC.

This could require magic, as we need to have a way to link the .less/sass/scss file with the resulting .css file.  [file_dep](https://github.com/getnikola/nikola/blob/master/nikola/plugins/task/bundles.py#L92) works on input files, while [build_bundle](https://github.com/getnikola/nikola/blob/master/nikola/plugins/task/bundles.py#L68) works on output files.

**Comment by ralsina** [comment]
Reading this ... I vaguely remember we used to depend on output files and we changed it to input files for what, at the time, seemed very good reasons.

**Comment by ralsina** [comment]
Bundles already depend on output files:

````python
                file_dep = [os.path.join(kw['output_folder'], fname)
                            for fname in files if
                            utils.get_asset_path(fname, self.site.THEMES, self.site.config['FILES_FOLDERS'])
                            or fname == 'assets/css/code.css']
````

**Comment by ralsina** [comment]
So, I think this is not a real bug: You can use sass/less and then bundle the output files.

Has anyone ever *tried* this? If yes, what failed? Is it just that the order of tasks is wrong? In that case it's trivial to fix using dependency injection now.

**Comment by bcarlin** [comment]
I'm affraid it is not working...
The culprit is the filter `utils.get_asset_path(fname, self.site.THEMES, self.site.config['FILES_FOLDERS'])` that looks for files on the disk in the "input" folders (THEMES and FILE_FOLDERS). The files generated by sass, however, only exists in the output folder.

**Comment by ralsina** [comment]
ok.

**Comment by bcarlin** [comment]
I can't see any obvious error.

Here is the layout of my theme (full repo: https://github.com/bcarlin/bcarlin.net/tree/nikola7) :
```
themes/bcarlin
...
├── bundles
├── parent
├── sass
│   ├── bcarlin.scss
│   └── targets
└── templates
    ├── base.tmpl
    ├── index.tmpl
    ├── list_post.tmpl
    ├── post.tmpl
    └── tag.tmpl
```

I've added the line `assets/css/foo.css=bcarlin.css` to my bundles file.

Here is the ouput of "nikola build" ([full output](https://gist.github.com/bcarlin/e24ed9e7610e3681c8d7#file-build_output-txt)) :
```
[18:18:43] Progs/bcarlin/bcarlin.net [.venv]±(nikola7|…) ➜  nikola build -a
Scanning posts..done!
[...]
.  prepare_sass_sources:cache/sass/targets
.  prepare_sass_sources:cache/sass/bcarlin.scss
.  build_sass:output/assets/css/bcarlin.css
.  create_bundles:output/assets/css/foo.css
.  create_bundles:output/assets/js/all-nocdn.js
.  create_bundles:output/assets/js/all.js
.  create_bundles:output/assets/css/all-nocdn.css
.  create_bundles:output/assets/css/all.css
.  sitemap:output/sitemap.xml
.  sitemap:output/sitemapindex.xml
.  robots_file:output/robots.txt
```

So the scss sources are compiled, the bundle "foo.css" is generated, but it is empty (whereas bcarlin.scss and output/assets/css/bcarlin.css have content).

When I add a print after file_dep is computed for each bundle :
```python
file_dep = [os.path.join(kw['output_folder'], fname)
                            for fname in files if
                            utils.get_asset_path(fname, self.site.THEMES, self.site.config['FILES_FOLDERS'])
                            or fname == 'assets/css/code.css']
print("file_dep for bundle ", name, ": ", file_dep)
```

Here is what I get :
```
$ nikola build   
Scanning posts..done!
file_dep for bundle  assets/css/all-nocdn.css :  ['output/assets/css/bootstrap.css', 'output/assets/css/rst.css', 'output/assets/css/code.css', 'output/assets/css/colorbox.css', 'output/assets/css/theme.css']
file_dep for bundle  assets/js/all-nocdn.js :  ['output/assets/js/jquery.min.js', 'output/assets/js/bootstrap.min.js', 'output/assets/js/jquery.colorbox-min.js', 'output/assets/js/moment-with-locales.min.js', 'output/assets/js/fancydates.js']
file_dep for bundle  assets/css/all.css :  ['output/assets/css/rst.css', 'output/assets/css/code.css', 'output/assets/css/colorbox.css', 'output/assets/css/theme.css']
file_dep for bundle  assets/js/all.js :  ['output/assets/js/jquery.colorbox-min.js', 'output/assets/js/moment-with-locales.min.js', 'output/assets/js/fancydates.js']
file_dep for bundle  assets/css/foo.css :  []
.  render_archive:output/blog/index.html
[...]
.  render_tags:output/blog/tag/debian.xml
.  prepare_sass_sources:cache/sass/targets
.  prepare_sass_sources:cache/sass/bcarlin.scss
.  build_sass:output/assets/css/bcarlin.css
.  create_bundles:output/assets/css/all-nocdn.css
.  create_bundles:output/assets/css/all.css
.  create_bundles:output/assets/js/all-nocdn.js
.  create_bundles:output/assets/css/foo.css
.  create_bundles:output/assets/js/all.js
.  sitemap:output/sitemap.xml
.  sitemap:output/sitemapindex.xml
.  robots_file:output/robots.txt
```

Tell me if you need more information.
