### ISSUE TITLE
Add mathjax automatically when needed instead of using a flag in tags

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1393]
Math support usually produces a clearly visible thing in the output. For example:

```
.. math:: 2+2
```

produces:

```
<div class="formula">
2 + 2
</div>
```

So, a Post object could examine its text and figure out if it contains math, which would then be used by the templates to determine if the mathjax inclusion is needed.

**Comment by ralsina** [comment]
@klingtnet I had never heard of KaTeX before!

It looks very interesting, and I may even want to switch to it instead of mathjax if it's:

1) Actually faster
2) Possible to bundle without it using 150MB

**Comment by Kwpolska** [comment]
3) uses a nicely anti-aliased version of Computer Modern via webfonts instead of Times New Roman (ugh) or a bad-looking SVG

:+1: for switching to KaTeX.  We could even investigate if we could just run it all the time and eliminate the need for a special tag/meta option (which would need a rename either way).  Do many people use `\[x]\`, `\(x)\` or `$$x$$` for things that are not TeX math?  (we could disable the double-dollars which are deprecated in LaTeX)

**Comment by ralsina** [comment]
Right, we could make it a global flag if it's reasonably fast

**Comment by klingtnet** [comment]
@Kwpolska Currently KaTeX doesn't support environments, which means it can't render matrices and so on.  But this is the only big downside, besides that it's [a hell lot faster](http://jsperf.com/katex-vs-mathjax)  than MathJax.

**Comment by Kwpolska** [comment]
Sheesh… Possible resolutions:

(a) wait until environment support is added, which can take forever;
(b) ignore this, hoping our users don’t need to write out matrices etc. in TeX;
(c) switch to KaTeX but still allow MathJax for people who really want it.

(we are actually pretending `\begin{equation*}` is a display math delimiter right now)

**Comment by klingtnet** [comment]
It looks like environment support will not come in the near future: [KaTeX issue 206](https://github.com/Khan/KaTeX/issues/206)

**Comment by damianavila** [comment]
I think option c (switch to KaTeX but still allow MathJax for people who really want it) is the way to go...

**Comment by ralsina** [comment]
Looks like KaTeX support \begin \end now?

**Comment by Kwpolska** [comment]
It does, but it might not support all blocks people are using.

**Comment by ralsina** [comment]
About KaTeX https://github.com/getnikola/nikola/pull/2045

**Comment by ralsina** [comment]
I am closing this issue.
