### ISSUE TITLE
Stop rebuilding RSS files for tags that don’t need it

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1410]
1. Add a few posts with some tags
2. nikola build
3. Edit any one of the posts and add a new tag
4. nikola build

All tags’ RSS files are rebuilt to facilitate adding one new tag. Even when not all of them have changing content. They get new `<lastBuildDate>` which causes utilities like rsync and git to treat them as new files.

We should be more selective about what feeds need rebuilding.

**Comment by felixfontein** [comment]
Actually, adding a new tag (or category) will not only trigger a rebuild of all tag RSS files, but also of all tag pages. The reason for this is that in the ```tags.py``` plugin, one of the first functions when creating tasks which is called is ```RenderTags.list_tags_page```, which inserts a list of *all tags and categories* into ```kw``` (as ```kw['tags']``` and ```kw['categories']```). This affects all later tasks created by that plugin, including all tag/category page tasks and all tag/category RSS tasks.

Does any of these tasks *needs* this information in ```kw```? I think not. If you all agree, I'd like to change ```RenderTags._create_tags_page``` to add the list of tags and categories to only a  copy of ```kw```.
