### ISSUE TITLE
Apply XSL to RSS to make it user/web-browser friendly

### ISSUE THREAD

**Issue by da2x** [getnikola/nikola#1411]
Branch: xsl-rssexy

Todo left on this in utils.py:
- href should be absolute path.
- check that path exists before including the PI

Todo in future iteration:
- localization

**Comment by sjehuda** [comment]
May this ticket be reopened?

I have made an XSLT stylesheet which handles Atom and RSS filetypes and is well constructed; it also has RTL support (page direction switches in case a language code of an RTL language is set).

It would be nice to enhance the CSS stylesheet, nevertheless it is good.

You can find it at https://gitgud.io/sjehuda/streamburner

Of note:
* I have made it one file so it would not be believed to be complex to apply.
* Originally, it was splitted into several files and all were compiled together using `<include>`.

**Comment by sjehuda** [comment]
You can see a preview at https://github.com/QupZilla/qupzilla/issues/1361#issuecomment-262802841

**Comment by Kwpolska** [comment]
Our current layout is a preview, and it includes an explanation of RSS. Your example is very complex, 1068 lines of XSLT (ours is 28 lines, although it uses tighter formatting), and it could pass as a full blog page.

I think our layout is fine. If there are RTL bugs, or if there are some issues with our XSLT, please open a bug for those specifically — but I would not want to make the XSLT more complex or a replacement for web pages.

**Comment by sjehuda** [comment]
I can make it even smaller and use the CSS provided by Nikola and Nikola Themes.

If you would want any help on this matter, I am available, even though it has been a while since I have coded in XSLT.

**Comment by Kwpolska** [comment]
The XSLT file should be self-contained, standalone, and compatible with any theme. We can’t use CSS from Nikola themes, because some stylesheets may have specific expectations (e.g. about containers, alignment, flexbox) that would not be handled by the global XSLT stylesheet.

**Comment by sjehuda** [comment]
I have slightly updated my previous comment.

> The XSLT file should be self-contained, standalone, and compatible with any theme.

I _think_ I can do something like this.

> We can’t use CSS from Nikola themes, because some stylesheets may have specific expectations.

I understand. Hence the structure would have to be as common as possible with most common elements, that is, if we would use CSS of Nikola themes.

---

Please know that I am here and know that I am willing to contribute to XSLT matters whenever you wish, as Nikola is one of the fewer CMS software that uses XSLT.

**Comment by Kwpolska** [comment]
I understand, but I still think that our XSLT things are fine as-is, and don’t need a redesign or new features.
