### ISSUE TITLE
Keep closely-related static files in the same directory as their posts / pages

### ISSUE THREAD

**Issue by foresto** [getnikola/nikola#1427]
Rather than putting inline images and other static files in a separate directory, my sites keep them as siblings of their closely-related content files. When I try using nokola to build such a site, the markdown files get processed, but the jpegs & zip files don't get copied. Adding support for this would make nikola useful to folks like me who have sites organized this way.

**Comment by e2jk** [comment]
The way it currently works (separating textual contents and "other files") makes sense to me.
@foresto where you able to find a solution to your issue with Pelican?

In any case, can we close this issue as I don't see this getting changed anytime soon/ever?

**Comment by foresto** [comment]
As it turns out, this was a frequently requested feature in Pelican's issue tracker and IRC channel, and the maintainers were quite supportive of it, so I implemented it.

Pelican now allows storing static files in the same directory as content source files, without causing the raw content sources to be published. The files can be kept together when published either by replicating the source tree structure in the output, or by using a special link syntax that causes static files to follow their linking documents.

These features make Pelican useful to a much larger audience, since it can now support nearly arbitrary site layouts and source trees. This makes it a good candidate for migrating existing sites away from legacy tools, and for developing new sites where the URL hierarchy must represent the information hierarchy (instead of being a slave to MIME types).

Since I now have a tool that does what I need, closing this issue won't bother me much. (I may never understand the compulsion to close legitimate bug reports & feature requests just because they seem unlikely to be addressed quickly, though. I guess maybe some folks feel better when their issue list is short. Personally, I find that leaving wish-list items open and easily visible makes them more likely to be addressed by someone eventually, like I did with Pelican.)

**Comment by Kwpolska** [comment]
You can EASILY recreate the structure in files/ and have an arbitrary
output tree. Source tree layout should not be important.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by foresto** [comment]
> You can EASILY recreate the structure in files/ and have an arbitrary output tree.

That's nice, but having the ability to create directory structures as we like does some of us no good at all without the ability to store in them whatever files we like. The two go hand in hand. (And yes, I understand that it can be done with Nikola; the point is that it can't be done cleanly.) Pelican had a similar problem until recently.

> Source tree layout should not be important.

Source tree layout is only unimportant to people who are willing and able to change their layout and workflow to suit the limitations of a single tool. Some of us have existing sites with existing source layouts, and either can't justify the time it would take to rearrange them and reconfigure the other tools involved, or can't/won't force their site collaborators to adapt to such changes. Even among those who have the luxury to change, some of us will choose not to do it, because scattering interdependent files across different directory subtrees makes it harder to understand the relations and manage the information. I ran into quite a few people with the same complaint when I was working on Pelican, so I know it's not just me. :)

**Comment by ralsina** [comment]
I clearly don't understand the issue here:

    Pelican now allows storing static files in the same directory as content source files, without causing the 
    raw content sources to be published. The files can be kept together when published either by 
    replicating the source tree structure in the output, or by using a special link syntax that causes static 
    files to follow their linking documents (like attachments).

You can do *exactly* that in Nikola. Keep the files along with the post sources in posts/ and replicate the same tree structure (sans the post sources) in files and voilá, it just works.

**Comment by ralsina** [comment]
Oops, closed by mistake.

**Comment by felixfontein** [comment]
If I understand this correctly, not having to replicate/dupliate files is the main point of this issue.

A simple version of this could be done by modifying the file copying plugin ```nikola/plugins/task/copy_files.py``` (or creating a new plugin doing something similar) which copies everything but ```.meta``` files and files specified in the ```COMPILERS``` section.

**Comment by ralsina** [comment]
If you don't want to duplicate the source files, just set posts/ and stories/ in your FILES_FOLDERS and set COPY_SOURCES to False to avoid conflicts like Kw said. Have not tried it but it *should* work.

Of course this will install every random file you forget in there, backups, etc but hey, it does what is requested.

I will close the issue. If there is anything I am missing, that this doesn't do, I'll reopen, of course :-)

**Comment by ralsina** [comment]
Oops, forgot: to avoid the last described problem of source files appearing in the output: delete them as part of the deploy process, or on the server after deployment, or blacklist them from syncing to the server.

**Comment by meshlogic** [comment]
I also think it's redundant work to maintain two folder trees just because of images that are always post/page related. Not mentioning the complicated urls when you have images in separate folder tree.

So I added posts and pages to FILES_FOLDERS. Setting COPY_SOURCES to False didn't work since CopyFiles copies everything. Thus, to avoid copying source files I went to `copy_files.py` and added few lines to skip files based on extension...

            ...
            for task in utils.copy_tree(src, real_dst, link_cutoff=dst):
                
                # Skip source files from copying !!
                targets = task.get('targets')
                if targets is not None:
                    ext = os.path.splitext(targets[0])[-1].lower()
                    if ext in ['.html', '.rst', '.md', '.ipynb']:
                        continue

                task['basename'] = self.name
                ...

Of course it would be nice, if the list of extensions to skip were included in the site config file `conf.py`.
