### ISSUE TITLE
Fix docs on sub-menus in conf.py

### ISSUE THREAD

**Issue by dr-leo** [getnikola/nikola#1430]
Look at the boiler-plate code from conf.py:

``` py
#     ('http://example.com/', 'Text')
#
# For submenus:
#     ((
#         ('Sub 1', 'http://example.com/'),
#         ('Sub 2', 'http://example.org/'),
#     ), 'Top')
#
```

This suggests that for sub menue entries the 2-tuple is ('name', 'url') whereas for menue entries it is vice versa. Reality is more consistent: sub-menue entries are the same as menue entries. 

Also, I would suggest to give "Top" a more meaningful name such as "Grapes" and name submenu entries "oranges" etc. For non-techies all these (()) can be confusing. So a more natural hierarchy would ease readability.

On a separate note, Nikola is awesom, as you know.

**Comment by undertherain** [comment]
Could you please document submenus in case the links are not to external urls, but to the folders within a site? 
for instance, 
```
    (
        (
            ('/fruits/apple', 'Apple'),
            ('/fruits/orange', 'Orange'),
        ),
        'Fruits'
    )
``` 
it is rendering correctly from the index page, but when I go to /fruits/apple, the prefix from the links mysteriously dissipates
