### ISSUE TITLE
Let's support commonmarkdown?

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1431]
https://pypi.python.org/pypi/CommonMark

**Comment by asmeurer** [comment]
FYI [highlight.js](https://highlightjs.org/usage/) works well with commonmark (commonmark generates the code needed for it automatically, so I was able to get it to work with just 

```py
BODY_END += """
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.5/styles/default.min.css">
<script
src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.5/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
"""
```

**Comment by ralsina** [comment]
@asmeurer thanks, added it to the plugin's README
