### ISSUE TITLE
github_deploy broken if no remote `gh-pages` branch

### ISSUE THREAD

**Issue by talos** [getnikola/nikola#1464]
If you just started out with Nikola and your remote doesn't have a `gh-pages` branch yet (which will be the case for most people), then `github_deploy` crashes with:

```
ERROR: github_deploy: Failed GitHub deployment — command ['git', 'pull', 'origin', 'gh-pages:gh-pages'] returned 1
```

Since `git pull origin gh-pages:gh-pages` won't work if there's no remote `gh-pages` branch.  This is a big problem, because creating and pushing the blank branch is possible but nontrivial, and is one of the main automation "bonuses" of having a `nikola github_deploy` in the first place.

**Comment by jean** [comment]
I encountered the missing remote branch issue too, and wrote a [Hello World](http://jean.github.io/posts/hello-world/) which details the steps I followed to get started.
