### ISSUE TITLE
Minfy_lines filter removes indentation from code blocks

### ISSUE THREAD

**Issue by KLINGTdotNET** [getnikola/nikola#1497]
Like the title says, if you activate the `minfy_lines` filter for html files, the identation of code-blocks will be lost. The filter should avoid running on `<pre>` blocks. I am using nikola 7.20.

**Comment by ralsina** [comment]
Let's make it into a no-op filter and emit a warning. We can't have a filter that breaks things so easily.

**Comment by Kwpolska** [comment]
s/warning/critical error/
