### ISSUE TITLE
Add category support to the WordPress importer

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1519]
hat tip @jjconti on IRC.

I might find time to do it this weekend.

**Comment by felixfontein** [comment]
I think this is already (mostly?) implemented: https://github.com/getnikola/nikola/blob/master/nikola/plugins/command/import_wordpress.py#L160
Besides that, since we get rid of categories, I don't think there's need to keep this open. So can we close this?

**Comment by Kwpolska** [comment]
Let’s assume this works.

**Comment by felixfontein** [comment]
It did for me. So I'm happy ;)
