### ISSUE TITLE
Extending categories?

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#1520]
Hi,
two things I'm missing in Nikola are the possibility to have more than one category per post, and to have a hierarchy of categories (where posts in child categories automatically belong to parent categories when browsing through the list of posts per category).
(Thruth is, I've been heavily relying on these two features in WordPress and don't like the idea of just mixing the small amount of structured categories into the huge tag mess.)
Parts of this can be done without modifying Nikola -- that is, adding categories (just add ``categories: A, B, C`` to ``.meta`` files) and displaying them (use ``[ x.strip() for x in post.meta('categories').split(',') ]`` for the list of categories per post; won't have a nice automatic order, though).
Other parts can be done by duplicating a lot of code from Nikola into plugins -- such as showing posts per category.
But I don't like unecessary code duplication, so here's my question: what about adding that natively to Nikola? With some automatic defaults -- like automatically setting ``category`` resp. ``categories`` when only the other is set (if it makes sense) -- it should be mostly backwards compatible (in particular if you don't use more than one category per post in your blog).
What do you all think?
All the best,
Felix

**Comment by Kwpolska** [comment]
It would be nice if nested categories appeared in the core — the implementation would be cleaner, and everyone would be able to benefit.  @felixfontein, would you mind working on this?

cc @immanetize @ralsina (via IRC)

**Comment by felixfontein** [comment]
Yeah, I can work on that. Shall it still be restricted to one category per post? :)

Ok, so here are some basic thoughts:
   - A hierarchy of categories could be specified in the configuration file. All categories not appearing in this hierarchy are added as additional top-level categories.
   - The hierarchy mostly plays a role when determining the list of posts for a category: a post is added to the list of its category, the parent of the category, its parent, etc. The post itself has only this one category assigned, and a post's page usually has no information on the parents of the category.
   - The categories overview page (generated by the tags plugin) shows a category tree instead of a (linear) category list. The rendering of the tree shall be done by the theme; the tags plugin will provide enough information on how to render the tree.
Is this more or less what you guys are interested in?

(Regarding the rendering/handling, I'll probably borrow code from my wordpress_categories plugin: https://github.com/felixfontein/nikola-wordpress/blob/master/plugins/wordpress_categories.py. It essentially provides a category hierarchy as described above as well as the possibility of having more than one category per post to current Nikola.)

**Comment by immanetize** [comment]
I'm most interested in a category hierarchy, and resulting category overview pages.  Ultimately, it would be ideal to build a site with a view offering a list of top level categories with stub descriptions of those categories, then each top level category showing their child categories with stub descriptions, and so on.  Where a category contains pages instead of other categories, you would see titles and teasers for the pages.

Something to help a reader looking for posts/pages on a specific topic browse through a huge volume of content in an organized matter, basically.  I'll try to keep up, but I'm coding at the 'reheated copypasta' level at this point :P

**Comment by immanetize** [comment]
Oh, and on your second point - if the post doesn't know about parent categories, wouldn't that require all categories be globally unique? ie you couldn't have both "work/photos" and "personal/photos" ?  Instead, the post could do something like:

```yaml
category:
   scope: work
   theme: photos
   subject: holiday parties
```
The parser could know that subjects are a subset of themes, and themes are a subset of scopes.  You wouldn't have to maintain a value-specific hierarchy for the parser to know that 'holiday parties' are a subset of 'photos' which is a subset of 'work' - much more manageable and flexible, imo.

**Comment by Aeyoun** [comment]
I've kind of hacked tags to work in this way. See my [tag index](https://www.aeyoun.com/tag/) and a sample [tag index](https://www.aeyoun.com/tag/web-browsers.html) and an [older index of that tag](https://www.aeyoun.com/tag/web-browsers-1.html). Sounds like what you guys want, right? So there is more interest for something like this without all the customization needed,

**Comment by felixfontein** [comment]
> I'm most interested in a category hierarchy, and resulting category overview pages. Ultimately, it would be ideal to build a site with a view offering a list of top level categories with stub descriptions of those categories, then each top level category showing their child categories with stub descriptions, and so on. Where a category contains pages instead of other categories, you would see titles and teasers for the pages.

A category should also have both sub-categories _and_ posts.

> Oh, and on your second point - if the post doesn't know about parent categories, wouldn't that require all categories be globally unique? ie you couldn't have both "work/photos" and "personal/photos" ?

Well, that depends on how you want it. There are two ways to work with hierarchies:

  (i) either you specify the whole path for every post (like "work/photos");

  (ii) or you just specify the leaf ("photos") and let the system figure out the parents.

In case of (i), "work/photos" would be different than "personal/photos". In that case, the post would know the whole path, and the template could display it in some way (like "category: work >> photos"). In case of (ii), "photos" should be a subcategory of either "work" or of "personal" (otherwise, you don't get a tree, but a [DAG](https://en.wikipedia.org/wiki/Directed_acyclic_graph)); here, the post stores 'category: photos', and the template can either just print "category: photos", or walk the tree to get "category: work >> photos" (or for which category "photos" is a subcategory). In case of (ii), categories would be "globally unique" (if I understand the term as you mean it).

In case of WordPress categories (where you have a tree-like hierarchy), you have case (ii), so "photos" can be a subcategory of either "work" or "personal", but not of both. You could for example have seven categories "photos", "work", "talks", "showcase", "personal", "programming", "travelling" organized as follows:

  * photos
  * work
     * talks
     * showcase
  * personal
     * programming
     * travelling

Every post which has category "programming" also shows up in the list for the category "personal", but not vice versa.

> Instead, the post could do something like:
> 
> category:
>    scope: work
>    theme: photos
>    subject: holiday parties
> 
> The parser could know that subjects are a subset of themes, and themes are a subset of scopes. You wouldn't have to maintain a value-specific hierarchy for the parser to know that 'holiday parties' are a subset of 'photos' which is a subset of 'work' - much more manageable and flexible, imo.

How precisely should this work? What does "scope", "theme" and "subject" mean in this model? Can you combine these freely?

**Comment by felixfontein** [comment]
@Aeyoun: in which sense is your tag index different from using an unmodified Nikola with a custom theme and with ```TAG_PAGES_ARE_INDEXES = True```? I couldn't find a hierarchy of tags/categories in your index.

**Comment by immanetize** [comment]
@felixfontein In the heirarchy, scope > theme > subject.  If you'll indulge some pseudocode, I can maybe explain better.  When assembling the metadata, you might end up with:

```python
post_metadata = {
   'widget_one': {
        'title':  'Widget improves lives!',
        category: {
            'scope': 'work',
            'theme': 'products',
            'subject': 'widget'
            }
     'widget_two': {
        #fill in many more posts
        }
}

all_scopes = _mythical_class.get_scopes(post_metadata)
# real code would iterate over the post metadata without these demonstrative 
# variable names being used along the way
all_scopes = ['work', 'play', 'tutorials', 'news', 'politics']
work_themes = _mythical_class.get_themes(post_metadata, scope='work')
work_themes = ['events', 'meetings', 'products', 'projects']
work_project_subjects = _mythical_class.get_subjects(
    post_metadata, 
    scope='work',
    theme='products'
    )
work_project_subjects = ['widget', 'gadget', 'toy']
project_posts = _mythical_class.get_posts(
    post_metadata,
    scope='work',
    theme='products',
    subject='widget'
    )
project_posts = ['widget_one', 'widget_two', 'widget_three']
```

The top level category page gets built from *all_scopes*.  Iterating over *all_scopes* gives you the themes in each scope.  The theme list is used to build the second level category page, one for each parent scope.  Iterating over the theme gives you the next category down in the heirarchy, which we're calling 'subject', so the subject list is used to build the theme's category page.  Finally, the subject category view shows posts within that subject (or a post could show in the 'scope' or 'theme' level, depending on the depth of categorization declared in the post)

Then there's... something to supply a description for each named category.  The top category view, for example, would read something like this instead of a list of category names:

```
Work
    Posts about things going on at my day job.

Play
    Recreation is fun! Here is how I do it.

News
    I have opinions on current events!
```

Hopefully this gives a decent idea of what I'm looking for.  I need to block off some time to read the existing code more...

**Comment by felixfontein** [comment]
@immanetize So basically you want a hierarchical category system with three levels, where category names can be re-used in different sub-categories.

Instead of fixing the number of levels to three, it would be better to specify each category as a path, like 'work/products/widget' as the category for 'widget_one'. I'm not sure whether the use of '/' is a good idea here, maybe we should use ',' instead. So your 'widget_one' post could have
```
category: work, products, widget
```
in its metadata. Nikola would then assume that `work` is a top-level category, with sub-category `products`, and sub-sub-category `widget`. By collecting all these information from all posts, it could build a tree of categories, which would be accessible in some way for the categories overview page(s).

There are at least two different ways to present this tree: first, to show the top-level categories and allow to go to a sub-category by clicking it. Next, to show a tree representing the available categories, and allowing to click one category in the tree to get a list of posts for this category.

Also, for listing posts for a category, one could either list the posts for precisely this category, or list all posts for this category and its sub(sub)categories.

The main question for me is what's the best way to specify the category path. @ralsina, @KWpolska: any suggestions here? Is comma a good separator, or should we use a forward slash or something like that (even though it could already appear in existing category names)? Or use a Python-similar list instead, like `[work, products, widget]`?

**Comment by ralsina** [comment]
On 16/04/15 16:27, felixfontein wrote:
> The main question for me is what's the best way to specify the 
> category path. @ralsina <https://github.com/ralsina>, @KWpolska 
> <https://github.com/KWpolska>: any suggestions here? Is comma a good 
> separator, or should we use a forward slash or something like that 
> (even though it could already appear in existing category names)? Or 
> use a Python-similar list instead, like |[work, products, widget]|?
If it's a hierarchy, use a path. If someone has / in the name of a 
category, it can be worked around, I guess.

You could even use other separators, like C++'s :: ... I won't intrude 
in the design since I have no idea what this is good for.

**Comment by Kwpolska** [comment]
I would use forward slashes. If there is any configuration of possible
structures, we could just intelligently decide if it's a structure or not.
Otherwise, we might even have to delay until v8…

**Comment by felixfontein** [comment]
I've thought a bit more about this. Being forced to always specify the whole path seems somewhat annoying to me, especially since it is not compatible with what I'm using at the moment :)

So what do you think about the following:

 - If you want hierarchies of categories, you have to specify the hierarchy completely in the ```conf.py``` file. (If you use a category outside this hierarchy, you'll get a warning and it will be assumed that it is a top-level category.)

 - Given a category string, Nikola will find for the shortest path beginning at the bottom of the hierarchy which, joined with forward slashes, matches the given string. If it is not unique, you will get an error. (This means that it is possible to use slashes in category names, and it is possible to construct hierarchies where some paths cannot be specified because they will never be unique. While the first part is nice for backwards compatibility, the second part is your own fault if you create such crazy category trees.)

 - In case no hierarchy is given in ```conf.py```, all category names used are top-level categories, you don't need to specify them in advance, and slashes are treated as parts of category names. So this is completely backwards compatible and no existing Nikola-based blog must be changed.

For example, assume you have the following hierarchy:

 - "work"
    - "photos"
    - "thoughts"
 - "private"
    - "photos"
    - "books"
 - "work/books"
    - "funny books"

The following are valid category strings:
  - "work" (top-level category "work")
  - "work/thoughts" (subcategory "thoughts" of "work")
  - "work/photos" (subcategory "photos" of "work")
  - "thoughts" (subcategory "thoughts" of "work")
  - "books" (subcategory "books" of "private")
  - "work/books" (top-level category "work/books")
  - "work/books/funny books" (subcategory "funny books" of top-level category "work/books")
  - "funny books" (subcategory "funny books" of top-level category "work/books")

On the other hand, "photos" is an invalid category string since it could both be completed to "work/photos" and "private/photos". Also, if you would have a subcategory called "books" of "work", the string "work/books" would match both this subcategory and the top-level category. Since the path to the top-level category is shorter, "work/books" will refer to it. If you write "books", though, you could mean both the subcategory "books" of "work" and of "private". You can still write "private/books" to get the subcategory "books" of "private", but there's no way to reach the subcategory "books" of "work". (Nikola could detect this and print a warning.)

**Comment by Kwpolska** [comment]
Wouldn’t it be easier to just have users write out the full category at all times without guessing and, more importantly, configuring it in config?

If you really hate typing, buy a good keyboard that makes you *want* to type or consider copy-pasting them from a listing file you created.  Adding things to the config file while creating new posts is very **user-unfriendly**. In an ideal world, you should be able to write a config file once and never change it (unless we add some backwards-incompatible config changes, but that’s a rare case).  There can also be sites where there are editors who do not have access to the config file/cannot write Python code (like in the Coil CMS project), which will basically make it impossible to use nested categories for them without talking to the administrator (*if* the administrator has time to play with a crazy setting every time the category hierarchy needs to be extended).

**Comment by felixfontein** [comment]
Well, if we're allowed to break backwards compatibility (different interpretation of category names with a forward slash in them), that's fine. (And I'd have to go through all posts of my blogs and adjust the categories, since at the moment I'm using a hierarchy without the need to specify the complete path, but I can live with that.)

To still allow category names containing a forward slash, I'm suggesting to use // as an escape. This is not perfect as it doesn't allow to distinguish between a slash at the end of a higher-level category name from a slash at the beginning of its children, but that's acceptable from my point of view. Or would you prefer '\/' as an escape for '/', and '\\' as an escape for '\'? This breaks a bit more backwards compatibility, but makes everything unique.

**Comment by felixfontein** [comment]
(If nobody minds this backwards-incompatibility, I'll start actually writing code :) )

**Comment by ralsina** [comment]
@felixfontein you can auto-edit your tags to avoid effort using https://plugins.getnikola.com/#tags 

Also, I don't see an incompatibility... at some point in the code, we will split tags by separator. We add an option not to do it, and then they stay flat.

That option is set to flat by default. In version 8 we set it to True for new sites.

**Comment by felixfontein** [comment]
Sounds good. That setting will also enable `\` as an escape character (to escape `\` and `/`), then.

**Comment by felixfontein** [comment]
@immanetize: with the implementation from the branch, you should be able to do what you want to do. Instead of
```
category:
   scope: work
   theme: photos
   subject: holiday parties
```
you must write
```
category: work/photos/holiday parties
```
though. But you can have both ```work/photos``` and ```personal/photos``` :-)
