### ISSUE TITLE
reST titles broken?

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1539]
Input:

```rest
=====
hello
=====

some text
```

Output completely ignores the `hello` title.  It should be handled by _get_metadata_from_file and made the document title, but it gets ignored for some reason…  I don’t understand what the regexp is supposed to do though.

It does not appear in the final HTML, because we don’t use `pub.writer.parts['body_pre_docinfo']`.

cc @ralsina

**Comment by ralsina** [comment]
Basically, the regexp there matches things like 

```
Foobar
======
```

Not 

```
========
Foobar
========
```

I will try to expand it, or else document it.
