### ISSUE TITLE
Add something like Sphinx's ifconfig directive

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1566]
It lets you omit content based on configuration options, which sure sounds handy.

Usually I'd do it in the sphinx compatibility plugin, but maybe it should go in core.

**Comment by Kwpolska** [comment]
This may not be easy.  We would probably need to figure out everything before compiling (search by regexp?) so we can feed it to `register_extra_dependencies()`.

**Comment by Kwpolska** [comment]
Wait, no, I was reading old code.

Post-#1587 version: `self.config_dependencies` should be enough.  It looks like we won’t even get a race condition anywhere, because it’s checked in the `generic_*_renderer`s, so after post compiling.

**Comment by ralsina** [comment]
In fact, it's a pain in the ass with the new dependency stuff and I have no idea how to get the right information from one place to another.

I need to access config in a rest extension: sure, use self.site.config
I need to tell the Post object which variables I used: there is no way to do that

I could do some sort of rickety contraption that passes things to the compiler which then in turn passes them to the Post object but it's not worth it. Marking as wontfix.
