### ISSUE TITLE
TEASER_END unexpected behaviour

### ISSUE THREAD

**Issue by sableloki** [getnikola/nikola#1567]
for my blog posts im adding `.. TEASER_END` to keep the homepage cleaner however when i run `nikola serve` it just renders the whole post on the page. is there a setting i've glanced over?

__FYI__
- (python 2.7.9)
- (virtualenv 1.11.6)

__pip packages__

- blinker (1.3)
- docutils (0.12)
- doit (0.26.0)
- gnureadline (6.3.3)
- ipython (2.3.1)
- Logbook (0.8.1)
- lxml (3.4.1)
- MacFSEvents (0.4)
- Mako (1.0.0)
- MarkupSafe (0.23)
- natsort (3.5.1)
- Nikola (7.2.0)
- Pillow (2.7.0)
- pip (1.5.6)
- Pygments (2.0.1)
- PyRSS2Gen (1.1)
- python-dateutil (2.4.0)
- requests (2.5.1)
- setuptools (11.3)
- six (1.9.0)
- Unidecode (0.04.17)
- webassets (0.10.1)
- wsgiref (0.1.2)
- Yapsy (1.10.423)

**Comment by Kwpolska** [comment]
By default, TEASER_END is used only for RSS feeds, not for indexes.  If you want your to use it for indexes, you need to set `INDEX_TEASERS = True`.  

```py
# Show only teasers in the index pages? Defaults to False.
# INDEX_TEASERS = False
```

This is also documented in the handbook, in the [Teasers](http://getnikola.com/handbook.html#teasers) section:

> By default all your RSS feeds will be shortened (they'll contain only teasers) whereas your index page will still show complete posts. You can change this behaviour with your `conf.py`: `INDEX_TEASERS` defines whether index page should display the whole contents or only teasers. `RSS_TEASERS` works the same way for your RSS feeds.

**Comment by sableloki** [comment]
ok thanks :smile_cat:
