### ISSUE TITLE
Installation: /usr/bin/ld: cannot find -lz

### ISSUE THREAD

**Issue by e2jk** [getnikola/nikola#1569]
On Ubuntu 14.04 (32 bit), running `sudo pip install nikola` after having installed the libxml and libxslt libraries (as explained in the handbook), I do get the following error when the `lxml` module is being compiled:

    /usr/bin/ld: cannot find -lz

I've tried to install a couple of packages (`liblz-dev`, `liblz4-dev`) to no avail. Installing the following did the trick though:

    sudo apt-get install zlib1g-dev

Should this be included in the Handbook? I don't know how this package would be known for Red Hat and similar, and I don't know if it would apply, so I haven't yet made a pull request for this change.

**Comment by Kwpolska** [comment]
It’s `zlib-devel` for RPM-based.  I fixed this in 7b24dc7 with your name as the commit author.

**Comment by e2jk** [comment]
Thanks.
