### ISSUE TITLE
Custom template for tags' index pages?

### ISSUE THREAD

**Issue by dang2327** [getnikola/nikola#1570]
Hi, from reading the manual I understand that Nikola allows custom template for blog posts through the "template" metadata. 

I would like to see if it makes sense to add an option in `conf.py` that allows for custom templating of tag's index page, when we already have `TAG_PAGES_ARE_INDEXES` option turned on. When this "custom tag  index templating" option is true, users can add custom templates for each tag page using `<tag_name>-tag.tmpl`. If no such file is found for a tag, it will be default to `tagindex.tmpl`. 

A useful scenario for this feature would be the case where I want to use the tag's index page as "generic page" of a site that is simply a list of similarly formatted entries. For example, a "research areas" page of my lab site would consists of a detailed list of research topics. We can also have a "facilities" page to display the list of equipment and its information. All item pieces are simply posts with the appropriate tags to be included in the listing page. 

Thanks and regards,
Danh

**Comment by Kwpolska** [comment]
You can accomplish what you want much more easily.  Just use `TAG_PAGES_DESCRIPTIONS` (see tag.tmpl for an example).  If that is not enough, an `if` in tagindex.tmpl ought to do it.  Another alternative could be `post_list` in reST.
