### ISSUE TITLE
i18n: Link behind site name/logo is not aware of the current language

### ISSUE THREAD

**Issue by e2jk** [getnikola/nikola#1573]
The upper-left link always redirect to the “site-wide index” a.k.a. `SITE_URL` (regardless if the site is a blog of a non-blog using a custom index.html and non-null `INDEX_PATH`).

This means that if you are browsing the site in a non-default language, clicking on that link will send you to the home page (that's correct) but will switch you back to the default language (not correct).

That link should send to the "localized index":
* `SITE_URL` for the default language
* `SITE_URL + "/es/"` for non-default language (here with Spanish as an example)

**Comment by e2jk** [comment]
Looking at the templates, the link is generated by the `abs_link` function defined in `nikola/nikola.py`. That function takes `self.config['BASE_URL']`, and optionally appends the content of `dst`
How about adding an extra 2 lines at the beginning of that function that would do (pseudo-code, as I don't know how to determine that the current page is in a non-standard language, assuming here that there would be a `lang_code` variable set with e.g. "/es/"):

```
if lang_code:   # Make the URL aware of the current language
    url = self.config['BASE_URL'] + lang_code
```

And then use the `url` variable instead of `self.config['BASE_URL']` in that first if/else block?

**Comment by ralsina** [comment]
LGTM
