### ISSUE TITLE
"Not a blog" documentation points to non-existent website

### ISSUE THREAD

**Issue by e2jk** [getnikola/nikola#1574]
The [Creating a Site (Not a Blog) with Nikola](http://getnikola.com/creating-a-site-not-a-blog-with-nikola.html) documentation page/`docs/creating-a-site.txt` file mentions twice the site http://notablog.ralsina.com.ar/ which is not active anymore.
The first mention (in the `conf.py` file) is not a problem (it's just an example), but the second link at the bottom of the page is more problematic, as it actively encourages the reader to access the site:
> You can see the finished site in http://notablog.ralsina.com.ar

Should we just remove that second reference (and leave the link to the full configuration which is still a valid URL), or is there another example site that could be used instead?

**Comment by Kwpolska** [comment]
We should just recreate the site and put it up under a new URL.

Or just say that the Nikola website is a prime example of a site where a
blog is not the most important thing.

cc @ralsina

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by ralsina** [comment]
+1 to linking to the nikola site. In the meantime I brought back the site as http://notablog.ralsina.me

**Comment by Kwpolska** [comment]
There, updated.

**Comment by Kwpolska** [comment]
There, files updated.  Docs on the website will get updated along with v7.3.0 (which will hopefully come out soon).
