### ISSUE TITLE
`nikola build` succeeds in building a site without a config file

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1575]
cc @felixfontein

**Comment by felixfontein** [comment]
If I understand the old code correctly (https://github.com/getnikola/nikola/blob/007a0e7cf611ef9e377644fca8600ff2b258d8df/nikola/__main__.py), that has already been the situation before adding the switch to specify the configuration file's location. Now it outputs a warning, though.

**Comment by felixfontein** [comment]
If we want this not to work, I'd suggest to supply the ```Nikola``` object with information whether the config file was there, and let it decide (based on the command to run) whether it should bail out or not. The ```Nikola``` object should ask the command object whether it needs a config file or not, so that it is possible to write command plugins which don't need a config file (if we hard-code the commands which don't need one, as it is at the moment for commands where the warning isn't printed, that's not possible).

**Comment by Kwpolska** [comment]
Actually, no.  This **is** caused by b985b2f3922e67e642922419f3d589c6d00182a7.

Before this commit, `nikola build` did this if there was no config:

```log
[2015-01-10T10:11:14Z] ERROR: Nikola: This command needs to run inside an existing Nikola site.
```

The culprit:

```py
    config['__configuration_filename__'] = conf_filename
```

What is wrong with this?  You see, we determine whether or not a site is configured by `site.configured = bool(config)`.  Before we do that, we [remove the variables added in `__main__.py`](https://github.com/getnikola/nikola/blob/7a2e236d111fef773c795abf9cf621d45bac6a5d/nikola/nikola.py#L255) and make them attributes of the site object.

In order to fix this error and restore the old behavior (coming from [`__main__.py` for doit commands (incl. `nikola build`)](https://github.com/getnikola/nikola/blob/7a2e236d111fef773c795abf9cf621d45bac6a5d/nikola/__main__.py#L308)  or [`execute()` in nikola-specific `Command`s](https://github.com/getnikola/nikola/blob/7a2e236d111fef773c795abf9cf621d45bac6a5d/nikola/plugin_categories.py#L102)), we need to also remove `__configuration_filename__` from the config dict before attempting to check whether or not the site is configured.

Another change I made, trying to use a different config file that does not exist is now an error that leads to `sys.exit(1)`.

**Comment by felixfontein** [comment]
Ah, ok, that's one way to do it. But your change now breaks ```nikola/plugins/check.py```, because that looks for ```site.config['__configuration_filename__']```. I'll fix that.

**Comment by felixfontein** [comment]
Ah, you already changed that. Sorry, didn't see that...
