### ISSUE TITLE
failed to create process. on Windows

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1586]
AppVeyor fails with

    failed to create process.

when trying to use `nikola help`.  (using Python 2.7.9 on Windows Server 2012 R2)

A similar bug was just fixed by altering `subprocess.call` to use `shell=True` in `nikola check` on Windows. (cc @felixfontein)

**Comment by felixfontein** [comment]
First, regarding ```nikola check```: shouldn't the ```command = command.join(' ')``` in there actually be a ```command = ' '.join(command)```?

**Comment by felixfontein** [comment]
And then: why is ```nikola help``` trying to create a process? And what did change so that this suddenly starts failing?

**Comment by Kwpolska** [comment]
(1) it probably should be, mind fixing this?  
(2) no idea, will check around

**Comment by Kwpolska** [comment]
This may also be AppVeyor’s fault, I tweeted at them, maybe they can help.  If they can’t, I’ll probably toy around a Windows VM.

**Comment by Kwpolska** [comment]
Oh: and the `check` fix is back to being broken.  I don’t think we are at fault here.

**Comment by Kwpolska** [comment]
:exclamation: This is interesting: `nikola.exe` IS butchered, `python -m nikola` works.

Tell you what: I’d prefer to nuke the subprocess in `nikola check`. @felixfontein?

**Comment by felixfontein** [comment]
Sorry for not reacting faster, was offline...

What do you mean by nuking? Replacing it with what was there before? Or directly calling ```__main__.main()```?

**Comment by felixfontein** [comment]
Who's creating ```nikola.exe```, btw? pip?

**Comment by Kwpolska** [comment]
1. call __main__.main() and redirect stdout/stderr
2. setuptools creates `nikola.exe`

**Comment by felixfontein** [comment]
Ok, I tried to implement 1. here: https://github.com/getnikola/nikola/tree/check-nuke-subprocess
Haven't checked it with Python 2, though, but according to stackoverflow (http://stackoverflow.com/questions/1218933/can-i-redirect-the-stdout-in-python-into-some-sort-of-string-buffer/19345047#19345047) the grabbing should work both under Python 2 and 3.

**Comment by felixfontein** [comment]
At least AppVeyor and Travis don't complain. Doesn't change anything about Nikola.exe, though.

**Comment by felixfontein** [comment]
Maybe the ```nikola.exe``` problem is related to this one? https://bitbucket.org/pypa/setuptools/issue/331/windows-launchers-broken-in-120

**Comment by Kwpolska** [comment]
Looks like that’s it.  It was fixed overnight and released as 12.0.3.  If this manages to build, merging and closing this issue.  If not, we’ll look further.
