### ISSUE TITLE
Not able to compile ipynb after migrating to a new distro (Missing IPython error)

### ISSUE THREAD

**Issue by shankarmsy** [getnikola/nikola#1588]
Hi Guys,

I've been using nikola and ipython for a while now and it's a match made in heaven!

Currently I am trying to migrate my laptop to a different Linux distro on an SSD.  I've managed to get nikola installed as well as all the dependencies. But when I try to build, it throws an error that IPython is not installed. 

    [2015-01-18T01:05:48Z] ERROR: Nikola: In order to build this site (compile ipynb), you must  install the "ipython>=1.1.0" Python package.
    [2015-01-18T01:05:48Z] ERROR: Nikola: Exiting due to missing dependencies.

But I do have IPython 2.2 installed:

    Python 2.7.9 |Anaconda 2.1.0 (64-bit)| (default, Dec 15 2014, 10:33:51) 
    Type "copyright", "credits" or "license" for more information.
    IPython 2.2.0 -- An enhanced Interactive Python.

I am trying to work out of a virtual env and I can create notebooks okay in the environment. Why is it not finding IPython?

Nikola version is 7.3.0.

UPDATE: I removed Anaconda and installed IPython through pypi, now it started working. How do I get this to work with Anaconda?

**Comment by punchagan** [comment]
@shankarmsy It should work if you have Nikola and IPython installed in the same virtual env.

**Comment by Kwpolska** [comment]
Install Nikola inside Anaconda, by explicitly using `pip` from the Anaconda binary directory.  Nikola and IPython must live in the same environment to work properly.
