### ISSUE TITLE
Tag sorting

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#1590]
If I have two tags in a post, say ```a``` and ```B```, Nikola (using ```natsort```) sorts them as ```['B', 'a']``` and thus displays them in the "wrong" order.

How about if we use ```natsort.humansorted``` (http://pythonhosted.org//natsort/humansorted.html) instead of ```natsort.natsorted```? Or is there a reason why tags are sorted this way?

**Comment by Kwpolska** [comment]
There is no real reason.  Probably we were unaware of humansort.  We’d probably need `alg=ns.FLOAT | ns.LOCALE` anyway.

Suggestion 1: all tags in one case.

**Comment by Kwpolska** [comment]
Suggestion 2: we could also just use `ns.IGNORECASE`.

I’ll try to investigate.

**Comment by Kwpolska** [comment]
We must use IGNORECASE, because LOCALE is flaky: it may or may not need PyICU, which does not work with Windows.

**Comment by felixfontein** [comment]
Thanks for investigating and fixing! :)
