### ISSUE TITLE
archive for 2015

### ISSUE THREAD

**Issue by bhanuvrat** [getnikola/nikola#1592]
Hi

`nikola build`  is unable to create archive links and folders for posts in 2015 ... which is why posts I write don't even show up on the main page of my blog. Is it a bug?

Regards

**Comment by Kwpolska** [comment]
1. Do you actually **have** any 2015 posts?
2. Does Nikola pick up the posts?  (check by running `site.timeline` in `nikola console` and reading the output)
3. What does `nikola build -a` output?  It may just tell you what you’re doing wrong…

I was able to create 2015 posts and a 2015 archive just fine.

**Comment by bhanuvrat** [comment]
@Kwpolska  thanks. `-a` was something I didn't know.

**Comment by Kwpolska** [comment]
:question: 

`-a` rebuilds everything.

What did you do?  What happened?  What did it “fix”?

**Comment by bhanuvrat** [comment]
I was unaware of  `-a`. 
without `-a` too, the page wasgenerated ... I could access `http://localhost:8000/<the-slug>.html` but the post was not visible on the front page.

with `-a`, the post became visible on the front page.

**Comment by Kwpolska** [comment]
My **guess** is that the date of this post was in the future, which means it did not get rendered.

Please read the output of `nikola build` more carefully.  Also, `nikola build -a` should NOT be used on a daily basis.
