### ISSUE TITLE
Typo in generated tabcompletion script

### ISSUE THREAD

**Issue by e2jk** [getnikola/nikola#1596]
On v7.3.0, the output of `$ nikola tabcompletion` has a typo on the second line:

> auto-generate by 'nikola tabcomple**n**tion'

I couldn't find a reference to that mistyped word **tabcomplention** using Github's search function though.

**Comment by Kwpolska** [comment]
tabcompletion is provided by `doit`.

And this is a duplicate of #1408, by you.  It was already fixed in pydoit/doit@b72ba0c9d6d89dbcc0aa070f414f5137dfe49e59, but it didn’t get released yet.

**Comment by e2jk** [comment]
Indeed ;)
