### ISSUE TITLE
Plugin and extract metadata.

### ISSUE THREAD

**Issue by Carreau** [getnikola/nikola#1602]
Hi there ! 

Is there a way for plugin to define a way to extract metadata from file ? 
In particular with ipynb plugin as the fileformat is json, it would be relatively easy,
but I don't find information about that. 

I've looked at BasePlugin and PageCompiler (that get a class default_metadata).

Would adding an (optional) `extract_metadata(...)` to `PageCompiler` and call it in the right place(s) be accepted ? The good way to do it?

Could someone give me some pointers on where that should be? 

Ping @damianavila

**Comment by ralsina** [comment]
Currently the data extraction is in the Post class, but it would make tons of sense to refactor it into the compiler plugins.

**Comment by Carreau** [comment]
> Currently the data extraction is in the Post class, but it would make tons of sense to refactor it into the compiler plugins.

Thanks for the quick answer.

With backward compatibility I guess, so 
 - default_metadata
 - if availlable, merge with : from plugin
 - if availlable, merge with : .meta file ?

I'll try to take a stab at it.

**Comment by ralsina** [comment]
Right, more or less that, I think :-)

**Comment by ralsina** [comment]
This was fixed by #1603
