### ISSUE TITLE
Is it possible to have more than one blog?

### ISSUE THREAD

**Issue by vivekiitkgp** [getnikola/nikola#1604]
I was wondering if it is possible to have more than one blog under the same website. For example, say `/technical`, `/personal`

**Comment by ralsina** [comment]
You can do that in different ways.

1) Use categories. Then you have separate indexes and separate feeds.

2) Use two blogs and deploy them to the same server

Surely there's others :-)

**Comment by Kwpolska** [comment]
Not quite.  Best you could do is, make them categories and use `CATEGORY_PAGES_ARE_INDEXES`, along with multiple POSTS inputs/outputs (or just a good directory structure under posts/).  But Nikola will still think of them as one large blog — that is, there will still be places in which all of your posts will display as one big blog — specifically, the main `index.html`, the main RSS feed, tag pages and archives.
