### ISSUE TITLE
SVG images in galleries don't work

### ISSUE THREAD

**Issue by pellenilsson** [getnikola/nikola#1605]
Galleries plugin (and scale_images plugin) explicitly claims to support SVG:

    image_ext_list_builtin = ['.jpg', '.png', '.jpeg', '.gif', '.svg', '.bmp', '.tiff']

But it fails:

    .  render_galleries:output/galleries/test/normal_vectors.thumbnail.svg
    ########################################
    TaskError - taskid:render_galleries:output/galleries/test/normal_vectors.thumbnail.svg
    PythonAction Error
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/doit/action.py", line 360, in execute
        returned_value = self.py_callable(*self.args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/Nikola-7.3.0-py2.7.egg/nikola/image_processing.py", line 55, in resize_image
        im = Image.open(src)
      File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2288, in open
        % (filename if filename else fp))
    IOError: cannot identify image file u'galleries/test/normal_vectors.svg'

Should probably be handled by simply copying the SVG and setting desired size in HTML code instead.

**Comment by Kwpolska** [comment]
We would still need to figure out the SVG size to get the proper aspect ratio.

PS. 

>   File "/usr/local/lib/python2.7/dist-packages/Nikola-7.3.0-py2.7.egg/

Don’t use `easy_install`.
