### ISSUE TITLE
Installation instructions should use pip3 instead of pip

### ISSUE THREAD

**Issue by facundobatista** [getnikola/nikola#1614]
This way, the default usage would be of python 3....

**Comment by Kwpolska** [comment]
big :-1:

Use a virtualenv created with Python 3 and use `pip`, or switch to Arch Linux or Fedora 22.  EVERYONE in the world just says `pip` and has users figure it out themselves, or just makes them use the system Python.  Besides: not everyone has `pip3` (or even Python 3) on their system, and we’d probably have Python 2 die-hard fans or people with no `pip3` in their Python 2 virtualenv complaining or even requesting `pip2`.
