### ISSUE TITLE
Cannot deploy after removing cache

### ISSUE THREAD

**Issue by kayhayen** [getnikola/nikola#1615]
Hello,

the deploy command crashes like this:

IOError: [Errno 2] No such file or directory: 'cache/lastdeploy'

Why, yes, of course, I can remove "cache", can't I? Seems I have to "mkdir" it. Also I would like to disable its usage, as the point is unclear to my, using rsync does the trick to me.

**Comment by Kwpolska** [comment]
`rsync` is *recommended* by Nikola, but we use this worthless thing for deploy signals (so that they can know what was changed).  An easy fix.

**Comment by pellenilsson** [comment]
Now deployment is only possible if there *isn't* a cache directory. :smile:
