### ISSUE TITLE
github_deploy does not push src

### ISSUE THREAD

**Issue by dacoex** [getnikola/nikola#1620]
in conf.py

GITHUB_SOURCE_BRANCH = 'src'

the stuff get's not pushed.

What can I do to correct?

**Comment by Kwpolska** [comment]
What are you doing, how are you deploying, **what is the output of `nikola github_deploy`?**

**Comment by ralsina** [comment]
2 months, no reply, closing

**Comment by punchagan** [comment]
For the record, `github_deploy` only pushes the `output` to the `GITHUB_DEPLOY_BRANCH`. The sources are not pushed. The `GITHUB_SOURCE_BRANCH` is only used to keep track of the commit from which we are deploying.
