### ISSUE TITLE
i18n: Boilerplate for new post/page should use the default language

### ISSUE THREAD

**Issue by e2jk** [getnikola/nikola#1621]
With this new project, I have only one non-English language defined for the website. In conf.py:

```
# What is the default language?
DEFAULT_LANG = "nl"

# What other languages do you have?
# The format is {"translationcode" : "path/to/translation" }
# the path will be used as a prefix for the generated pages location
TRANSLATIONS = {
    DEFAULT_LANG: "",
    # Example for another language:
    # "es": "./es",
}
```

When creating a new page or post, the English string `Write your page here.` should be replaced by its translation in the `DEFAULT_LANG` language.

I am creating this website for someone who doesn't speak English, and would like him to be able to understand by himself what this means.

**Comment by Kwpolska** [comment]
Nikola requires knowledge of some basic English phrases — the post metadata must be in English, for example, and `new_post`/`new_page` are English.  Just tell them what *Write your post/page here.* means.

You could also monkey-patch the strings; they are in each compiler and new_post.py if I am not mistaken.

Not sure if we should proceed with that.  Comments welcome.

**Comment by e2jk** [comment]
True, the metadata is in English, as well as the prompt of the command line utility.
But these users are not even going to look at the metadata. They create a new post, know they need to enter the title of their post, then start typing below.

It's obviously not a huge deal, but as an enhancement I think it would make sense to speak the user's language, i.e. the primary language defined in conf.py.

I know the tool is somewhat directed towards tech savy/geeky/English speaking folks, but I don't think it would hurt to be a tiny bit more user-friendly in speaking the user's language.

**Comment by Kwpolska** [comment]
That would require a lot of restructuring.

```py
            # ipynb's create_post depends on this exact string, take care
            # if you're changing it
            content = "Write your {0} here.".format('page' if is_page else 'post')
```

That comment is making everything harder; we would have to devise something else to tell ipynb if a post is imported (and has some valid ipynb json as content) or not, without breaking existing plugins (we cannot really add metadata) — for example, check if `content` starts with `{`…

And we have one more problem: people with more than one locale.  You see, Nikola is completely unaware of the language of the post. We *could* try parsing the translation filename formats, assuming they are provided by the user.  People may be confused if they see a different language than they want to write in.  By using English, which is also the language of everything Nikola (except the name, that’s Serbian), we work around this.

Actually, there might be a way to fix this without breaking everything in one go.  You see, we have this nice thing called `ADDITIONAL_METADATA`.  We could alter it so it was accepting `content` and you would set it to the Dutch phrase “Write your post or page here”.  This would still make some refactoring in ipynb necessary, but it would be easier to work around.

I’ll try doing something this weekend.

**Comment by e2jk** [comment]
Don't spend too much time on this, I'm sure there are other issues that have a higher importance.

That being said, if Nikola was to be made aware of the language, I'd say we should use whatever is set in `DEFAULT_LANG`. Assuming that is the primary language of the website author/its readership, and that any additional languages defined in `TRANSLATIONS` are secondary languages.

**Comment by TheHellstorm** [comment]
I also think that this is not a high priority, but it certainly would be nice if Nikola would be localized. Well Python offers good support of localization, with the built in Gettext or with PyBabel. This could be used.

Many strings just need to be marked with the _() function so that Gettext can extract the strings. This is a rather stupid work and I would volunteer for it :-D

There are of course some issues which would require more work, for example the conf.py template or like your mentioned posts, but I guess it wouldn't hurt to at least translate the easy ones at first.
