### ISSUE TITLE
Refactor gallery into a JSON+JS implementation

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1623]
The current solution has a bunch of problems:

1) It's JQuery-dependent
2) It uses a largely abandoned library
3) It's complex code
4) It doesn't even work in the base theme

So, how to make this easier:

1) Simplify the plugin to make it just generate a json file with the correct image data.
2) Write, in the base theme, a _very_ simplistic loader of that data that lists the images
3) Write in the bootstrap theme (which guarantees JQuery) something nicer, based on whatever JQuery gallery thing we find

This plan would move the complexity out of core and into the templates, which is where we probably want it since:

1) The gallery display code is JS anyway
2) The theme authors are the ones who may want to hack that
3) Makes the gallery directive a much simpler thing

Plan:
- [x] Generate JSON file with gallery image info
- [x] Create by hand HTML file that can display said thing 
- [x] Templatize
- [x] Remove useless template inputs
- [x] Remove code that generates removed inputs

**Comment by Kwpolska** [comment]
Let’s not use fancy schmancy *experiments*.  That’s what happened with this one.  Let’s look for something **tried and true**; hell, we could even make something ourselves with Bootstrap’s `<img class="img-thumbnail">` and [the tooltip JS](http://getbootstrap.com/javascript/#tooltips).

Oh, this one is also abandoned: https://github.com/codrops/GammaGallery (last commit December **2012**)

**Comment by devurandom** [comment]
I'll vote for anything that stabilises the gallery_directive, so you can remove the "horrible, horrible hack" note from the plugin. :)

**Comment by StyXman** [comment]
Could you include #2146 in this?

**Comment by ralsina** [comment]
This is actually done!
