### ISSUE TITLE
post_list should depend on the deps of the post

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1624]
This way, templates can use `${post.text()}`.

**Comment by Kwpolska** [comment]
There is a fix on the `post_list-deps` branch.  It doesn’t really work, though: this requires a double-rebuild and making sure the files exist.  In other words, it seems impossible to use `${post.text()}` with `post_list` at all…

@ralsina, any ideas?

**Comment by Kwpolska** [comment]
In the meantime, a hack: https://gist.github.com/Kwpolska/3b20af944126182e447d

**Comment by felixfontein** [comment]
If a post_list can access the post object, then what's the difference between a post list and an index?

**Comment by Kwpolska** [comment]
As said on IRC: you may want to add some extra text that may change
often/want to write rest)
-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by Kwpolska** [comment]
Sort of fixed in df2eb6a… should be acceptable for some basic use cases.
