### ISSUE TITLE
Meta extraction error: incorrect parsing clobbers title from meta file

### ISSUE THREAD

**Issue by mforbes** [getnikola/nikola#1625]
I recently ran into a problem with metadata extraction.  I had an ipython notebook and a meta file specifying the title.  The correct title was extracted from the meta file on [line 926 of post.py](https://github.com/getnikola/nikola/blob/master/nikola/post.py#L926), but this was then clobbered by [line 936 of post.py](https://github.com/getnikola/nikola/blob/master/nikola/post.py#L936) with tried to parse the ``.ipynb`` file as an ``.rst`` file.

It seems that the metadata expressed in the ``.meta`` file should have precedence.

Here is the failing notebook.  The ``rst`` parser picks up on the ``"... it is in the data directory:"`` somehow and things that the title is ``"source": [``.  In any case, I would expect that either having a ``.meta`` file or having valid metadata extracted from [ipynb/__init__py](https://github.com/getnikola/nikola/blob/23426460b43973ce91a8696c5047098a2f611006/nikola/plugins/compile/ipynb/__init__.py) would tell ``post.py`` *not* to process the file (or at least the file should be processes *before* this other data is added.

```
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "... it is in the data directory:"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
```

**Comment by Kwpolska** [comment]
In addition to not honoring metadata from files if .meta exists, we could also limit metadata detection so that sequences like `...` would not be caught.

**Comment by Kwpolska** [comment]
@mforbes, @Carreau: does 41356a1 fix this?

**Comment by mforbes** [comment]
Yes, that seems to work for my use case.
