### ISSUE TITLE
Non-traditional links not being updated during rewrite_links

### ISSUE THREAD

**Issue by infowantstobeseen** [getnikola/nikola#1626]
doc.rewrite_links is used to make links relative to the document actually being written (so /assets/etc might become ../assets/etc if we are in a subdir of root). This works well on img:src, a:href, etc, but not for things like srcset (a way to specify responsive images on images); they are not processed at all. I'm dealing w/ this right now by using abs_link in my mako, but it might be nice for this do handled in the code (or have a mako function that does the same functionality; I might be missing it).

**Comment by Kwpolska** [comment]
We can’t do it easily.  We can’t just change everything that looks like a link, because we’d break text and other things that rely on full links.  We can’t also look for each and every thing that is a link, because we might just not manage to catch every instance.

Please raise this with the lxml folks instead.

**Comment by infowantstobeseen** [comment]
I'll ping lxml.

However, the ability to find out the relative url while in a template would be useful (so I could fix this w/o having to use abs_link). I may not be using rel_link link correctly, but couldn't find a means to replicate the behavior that is done in the Python processing w/o the template engine (mako).

**Comment by Kwpolska** [comment]
We use the replacer in our own templates for the HTML 5 shim, look at that.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by Kwpolska** [comment]
Closing as *wontfix* because it’s impossible (or at least very, VERY hard to do).
