### ISSUE TITLE
Get metadata from file extract random part of post as title.

### ISSUE THREAD

**Issue by Carreau** [getnikola/nikola#1627]
[This line](https://github.com/getnikola/nikola/blob/master/nikola/post.py#L936) seem to return some part of my post as metadata tile like: 
   `"source": [`,  `"\n"` and other. 

Is there a way to deactivate extracting metadata from the files themselves if metadata are in companion files, or already extracted by the compiler ?

**Comment by Kwpolska** [comment]
What post format is it?  Mind pasting full lines?  We certainly should make some changes there…

Also, this is a possible duplicate of #1625.

**Comment by Carreau** [comment]
Oh gosh, yes it is the same issue, and .ipynb too. I'm not sure how I missed it. sorry.
