### ISSUE TITLE
We should be able to add an image to RSS posts

### ISSUE THREAD

**Issue by jcea** [getnikola/nikola#1628]
Ideally RSS should be a template too, to be able to personalize. In the meantime I miss a lot being able to include an image per post in the RSS. It could be a metadata line per post, optional. I need it to feed some RSS consumers, including a RSS->Twitter gateway.

**Comment by Aeyoun** [comment]
Reuse the `thumbnail` metafield.

**Comment by jcea** [comment]
I don't see any reference to "thumbnail" in the rss.py file.

**Comment by Kwpolska** [comment]
I believe @Aeyoun meant `previewimage`.

**Comment by jcea** [comment]
I don't see any reference to `previewimage` in `rss.py` either. Remember that current Nikola DOES NOT use templates for RSS generation, it is hardcoded.

**Comment by Kwpolska** [comment]
It looks like it’s not implemented for RSS files, but we could easily change that.  Also, note that the actual RSS generation happens in `nikola.py` in `generic_rss_renderer`.

But we do have another feature for you that *will* work: the `enclosure` meta tag.  It’s not documented anywhere, but it should work (nikola.py lines 234-241; 1095-1100)

**Comment by ralsina** [comment]
Actually, previewimage is mentioned in he docs, and it does seem fit if it would be used for that purpose.

**Comment by ralsina** [comment]
@jcea how would that image thing look in a RSS feed? If you give me a link I *may* give it a shot :-)

**Comment by jcea** [comment]
I have solved my problem writing some code of my own. Thanks.

**Comment by ralsina** [comment]
@jcea I am still interested in working on "this", whenever "this" is explained :-)

Closing for now, but anyone feel free to reopen.
