### ISSUE TITLE
Unclear how to enable thumbnails

### ISSUE THREAD

**Issue by bobismijnnaam** [getnikola/nikola#1630]
From the documentation it is unclear how you make thumbnails work. Just adding images to the folder "images" and using the .. thumbnail directive is not enough. In your conf.py you also have to add a line saying something like `IMAGE_FOLDERS = {'images': 'posts'}` to make sure all the images are copied, or at least, that's what I had to do to get it to work (if I'm not forgetting anything else I added to my conf.py). This information is as far as I can tell not in the documentation, nor in (commented) sections of my conf.py.

I don't mind spicing up the docs with this information if I can find the time but I just wanted to check if I maybe missed/misinterpreted parts of the documentation. Can somebody shed some light on this for me, and if this is indeed missing in the docs, point me in the right direction of updating the docs with this information?

**Comment by ralsina** [comment]
On 02/03/15 12:49, Bob Rubbens wrote:
>
> From the documentation it is unclear how you make thumbnails work. 
> Just adding images to the folder "images" and using the .. thumbnail 
> directive is not enough. In your conf.py you also have to add a line 
> saying something like |IMAGE_FOLDERS = {'images': 'posts'}| to make 
> sure all the images are copied, or at least, that's what I had to do 
> to get it to work (if I'm not forgetting anything else I added to my 
> conf.py). This information is as far as I can tell not in the 
> documentation, nor in (commented) sections of my conf.py.
>
> I don't mind spicing up the docs with this information if I can find 
> the time but I just wanted to check if I maybe missed/misinterpreted 
> parts of the documentation. Can somebody shed some light on this for 
> me, and if this is indeed missing in the docs, point me in the right 
> direction of updating the docs with this information?
>

I'd say if that's needed and these thumbnails are not a plugin, that 
config should be added to the default config at least.

**Comment by bobismijnnaam** [comment]
Doesn't seem to be a plugin to me, I can't find it in the pugin listing on the site.

**Comment by Kwpolska** [comment]
It’s already nicely documented: http://getnikola.com/handbook.html#thumbnails

**Comment by ralsina** [comment]
On 02/03/15 12:58, Chris Warrick wrote:
>
> It’s already nicely documented: 
> http://getnikola.com/handbook.html#thumbnails
>
And IMAGE_FOLDERS defaults to {'images': ''} so there shouldn't need to 
be any
config tweaks in most cases.

**Comment by bobismijnnaam** [comment]
@Kwpolska: The code in the handbook doesn't work for me. When I do `.. thumbnail:: tesla.jpg` it doesn't work; I have to change it to `.. thumbnail:: ../tesla.jpg` otherwise the image doesn't show up on the generated page (or I'm missing something - but you should only have to put the images in the images/ folder to get it to work, right?). This behaviours is fine I guess but then there should be a little bit more clarification about IMAGE_FOLDERS.

Either that or my directory structure is just plain wrong

**Comment by Kwpolska** [comment]
The example working depends solely on your site configuration and directory layout.  Make sure to check paths before blindly copy-pasting examples.

**Comment by bobismijnnaam** [comment]
Sorry if this sounds like whining to you, I'm really just trying to understand Nikola better here. @ralsina says there is a default configuration and that there are no config tweaks needed in most cases. Shouldn't the example from the handbook then work without any changes (given the basic blog generated by Nikola, or is that too much to assume)? Because right now you need to change the IMAGE_FOLDERS variable in conf.py, or the line in the handbook has to be changed to `.. thumbnail: ../tesla.jpg`. It might seem really obvious to you that it depends a lot on your directory structure (to me it's now obvious also), but for a Python/Nikola noob like me (who perceives Nikola like magic) it's scary to perform the steps in the documentation and get missing file errors.

In any case, thanks for responding so quickly to my github issues! You guys kick ass for maintaining Nikola so well

**Comment by Kwpolska** [comment]
9b40483 just to make things clearer

**Comment by ralsina** [comment]
I have never looked at this... is the path to be used here relative to images/ or relative from the location of the post to the URL of images/ in the server or ... ?

**Comment by Kwpolska** [comment]
On Mon, Mar 2, 2015 at 5:41 PM, Roberto Alsina <notifications@github.com>
wrote:

> I have never looked at this... is the path to be used here relative to
> images/ or relative from the location of the post to the URL of images/ in
> the server or ... ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getnikola/nikola/issues/1630#issuecomment-76747134>.
>

relative to the post, IIRC

-- 
Chris Warrick <https://chriswarrick.com/>
PGP: 5EAAEA16

**Comment by ralsina** [comment]
On 02/03/15 13:43, Chris Warrick wrote:
> On Mon, Mar 2, 2015 at 5:41 PM, Roberto Alsina <notifications@github.com>
> wrote:
>
> > I have never looked at this... is the path to be used here relative to
> > images/ or relative from the location of the post to the URL of 
> images/ in
> > the server or ... ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/getnikola/nikola/issues/1630#issuecomment-76747134>.
> >
>
> relative to the post, IIRC
>

That may be the problem. I expected this to be relative to images/
