### ISSUE TITLE
Error using listings

### ISSUE THREAD

**Issue by bobismijnnaam** [getnikola/nikola#1631]
Hi everyone,

While trying to use listings I got the following error while rendering the post: <string>:1: (ERROR/3) Unknown target name: "prog.cpp <link://listing/listingsprog.cpp>". Also, the site in question looks like this:

![](http://i.imgur.com/8EoWu92.png)

What I did:

0. Setup a virtualenv (python 2.7.9)
1. pip install nikola
2. initialize new nikola site (with the -q option)
3. add a new post
4. add ".. listing:: prog.cpp c++" to the post
5. add prog.cpp to listings/
6. nikola build
7. nikola serve

For reference, prog.cpp contains the following:
    
    #include <iostream>
    
    int main() {
    	std::cout << "Hello world!";
    
    	return 0;
    }

I have no clue what I did wrong. Been prodding around in the Nikola internals today and it was a lot of fun founding out how it's structured but I didn't find anything useful. There also doesn't seem to be anything about this in the docs, altough it's 100% possible I missed something (if so, sorry for wasting your time and please point me in the right direction!). It seems to have something to do with the docutils Publisher class, altough that's probably really obvious (took me a while to figure out).

Hope someone can help me out with this, thanks in advance!

**Comment by Kwpolska** [comment]
I cannot reproduce, at least on Linux in a clean virtualenv.  This might be a Windows-specific issue… What Python version are you running?

**Comment by Kwpolska** [comment]
Ah, I think I see it.  You are using backslashes (the Windows way).  Please try using / (forward slash) instead and report if it works out.  (It 99% should, but you never know)

**Comment by bobismijnnaam** [comment]
In the given example there is no way for me to use forwardslashes anywhere. However if I change `.. listing:: prog.cpp c++` to `.. listings:: listings/prog.cpp c++` it says:

    [2015-03-08T16:47:23Z] ERROR: Nikola: Unknown listing name listings/prog.cpp!

Not sure where else I can substitute backslashes to frontslashes, unless you mean the nikola internals (earlier I tried it in the compiler/rest/listing.py file, replacing backslashes with frontslashes, and it gave me the same error). And yes I'm on windows so that's very likely the problem. Maybe the implementation #1505 does not support windows?

If supporting windows is not too big of a priority, I don't really need this feature any time soon, I can just use the code-block directive.

**Comment by Kwpolska** [comment]
Windows is a priority, but we can’t always test everything.

I should come up with a fix soon.

**Comment by bobismijnnaam** [comment]
Thanks for looking at it. I'll try to take a look at it but my Nikola
knowledge is still far below useful levels. For now I'll just not use it
then.
Op 8 mrt. 2015 18:01 schreef "Chris Warrick" <notifications@github.com>:

**Comment by Kwpolska** [comment]
That should fix it.  Make sure it works.  You can also test all three scenarios (`prog.cpp`; `listings/prog.cpp`; `listings\prog.cpp`) just to be extra sure.

**Comment by bobismijnnaam** [comment]
I'm gonna try it tonight, thanks!
Op 8 mrt. 2015 18:17 schreef "Chris Warrick" <notifications@github.com>:

**Comment by bobismijnnaam** [comment]
Works almost flawlessly (good enough for me, actually)! There's only one escaping thingy going on:

![](https://dl.dropboxusercontent.com/u/65227065/Screenshot%202015-03-09%2016.41.06.png)

I fixed this by changing

    [core.publish_doctree('`{0} <{1}>`_'.format(_fname, target))[0]])

to

    [core.publish_doctree('`{0} <{1}>`_'.format(_fname.replace('\\', '\\\\'), target))[0]])

in plugins/compile/rest/listing.py. Thanks for responding so quickly!
