### ISSUE TITLE
Better syntax for images linked to external URLs

### ISSUE THREAD

**Issue by jcea** [getnikola/nikola#1638]
After using #1536 I noticed something ugly.

#1536 allows me to translate:

```
|logo|_

.. |logo| image:: logo.png
    :alt: Logo de la Asociación Python España
    :height: 250

.. _logo: http://www.es.python.org/
```

To something more intuitive:

```
.. class:: islink

.. image:: logo.png
   :alt: Logo de la Asociación Python España
   :height: 250
   :target: PythonES_

.. _PythonES: http://www.es.python.org/
```

That is a nice improvement.

But I would love to move the class statement inside the image details. Something like:

```
.. image:: logo.png
   :class: islink
   :alt: Logo de la Asociación Python España
   :height: 250
   :target: PythonES_

.. _PythonES: http://www.es.python.org/
```

**Comment by ralsina** [comment]
Sadly the image directive doesn't seem to support a class option:

http://docutils.sourceforge.net/docs/ref/rst/directives.html#image

We *could* monkeypatch this, but it would make our restructured text gratuitously incompatible with docutils...

**Comment by ralsina** [comment]
There you go: https://github.com/getnikola/plugins/commit/ff854c83e7b9366d08735c907dbe7fca01fc331b
