### ISSUE TITLE
Archives should allow moving to next and previous.

### ISSUE THREAD

**Issue by magmax** [getnikola/nikola#1639]
Context variables injected in archives doesn't allow to manage "next page" or "previous page" links.

It would be great to allow it.

**Comment by Kwpolska** [comment]
What do you mean, exactly?  What should be changed?

**Comment by magmax** [comment]
The same way index.tmpl can manage `${prevlink}` and `${nextlink}` (file data/themes/base/templates/index_helper.tmpl), the template list_posts.tmpl should receive the link for the next and previous pages.

For example, in an environment with archives per year, it could be possible to add a link for "next year" and "previous year" in each of the archive pages. In an environment with `CREATE_MONTHLY_ARCHIVE=True`, it should have a "next month" and "previous month" buttons.

**Comment by magmax** [comment]
An example taken from one of the blogs in the "users" section:

the archive has these years: http://www.curiousefficiency.org/archive.html

So it would be great to be able to move from http://www.curiousefficiency.org/2011/index.html to the previous/next years without having to press on the archive index again.

Thank you!

**Comment by Kwpolska** [comment]
This certainly makes sense.  It could be done, I’ll try to look into it when I have some time.

**Comment by jjconti** [comment]
Can I work on this or is someone already on it?

**Comment by ralsina** [comment]
@jjconti feel free!

**Comment by Aeyoun** [comment]
Should look into including them in the Atom feeds too (for when archives are indexes).

**Comment by Kwpolska** [comment]
Fixed ni #2599.
