### ISSUE TITLE
Implement tag hiding

### ISSUE THREAD

**Issue by hiliev** [getnikola/nikola#1640]
Hi there, this is a suggestion for improvement. The main incentive behind it is to enable hiding of the `mathjax` tag, whose sole purpose (at least in my case) is to enable support for MathJax in a set of articles. Therefore, I would like to be able to hide the tag from the list of article tags, the tag cloud, the tag index, and so on. In any case, it might be useful to have the option to hide a certain list of tags that could be passed e.g. in the configuration file:

    HIDE_TAGS = [ 'mathjax', 'tag1', 'tag2' ]

**Comment by Kwpolska** [comment]
:+1:

We should also work on #1393 one day.

**Comment by Kwpolska** [comment]
There, all done.  New sites hide `mathjax` by default; we don’t do it in existing sites not to break things (maybe someone uses the tag to show off their maths/TeX skills?)
