### ISSUE TITLE
Link checker broken for absolute and full-path URL types

### ISSUE THREAD

**Issue by hiliev** [getnikola/nikola#1650]
It seems that the link checker (`nikola check -l`) doesn't work properly when `URL_TYPE` is set to `absolute` or `full_path`:

    $ nikola init --demo demo; cd demo
    ... change URL_TYPE to "full_path" or "absolute"
    $ nikola build
    $ nikola check -l
    Scanning posts....done!
    [2015-04-05T01:11:42Z] ERROR: check: Error with: output/2012/index.html 'str' object has no attribute 'path'
    [2015-04-05T01:11:42Z] ERROR: check: Error with: output/archive.html 'str' object has no attribute 'path'
    [2015-04-05T01:11:42Z] ERROR: check: Error with: output/galleries/demo/index.html 'str' object has no attribute 'path'
    ...

Nikola is vanilla `7.3.1` from `pip`, but `check.py` is the same in HEAD. I have a working patch in my forked repository that fixes it but being new to GitHub (and Git as a whole) I have a bit of trouble following the process outlined in `CONTRIBUTING`. Now that the issue is documented and open, shall I create pull request?

**Comment by Kwpolska** [comment]
Yes, you should create a PR if you have a patch.  Also, make sure it works with every configuration, as per #1649.

**Comment by hiliev** [comment]
I did check with most configurations imaginable. That's how #1651 turned up.

**Comment by ralsina** [comment]
So, closing because it's fixed by #1652
