### ISSUE TITLE
Misleading warning when BASE_URL does not end with slash

### ISSUE THREAD

**Issue by hiliev** [getnikola/nikola#1651]
Whenever `BASE_URL` does not end with slash, e.g. `http://getnikola.com/foo`, the following **warning** is issued:

    [2015-04-05T01:11:40Z] WARNING: Nikola: Your BASE_URL doesn't end in / -- adding it, but please fix it in your config file!

The message is misleading since no `/` is actually appended and the link paths in the final output end up being wrong.

**Comment by Kwpolska** [comment]
It would be so nice if computers could understand English and fill in for the developers sometimes… fixed, thanks.

(please really do fix your config file.)
