### ISSUE TITLE
Latex Equation Rendering in Ipython Notebooks

### ISSUE THREAD

**Issue by roblem** [getnikola/nikola#1653]
$ and $$ latex delimiters from Ipython notebooks (markdown cells) not rendering correctly after nikola build.   Rendered as raw markdown latex text ($e = mc^2$) rather than mathjax equation.

Ipython version: 3.1.0
Ipython Notebook format: v 4
Nikola version: 7.3.1

**Comment by Kwpolska** [comment]
You must use the `ipython` theme (which forces mathjax everywhere), or manually add `mathjax` tags to post requiring mathjax.  We don’t support the TeX-style single-dollar format for inline math — use LaTeX-style `\(e = mc^2\)` instead.

**Comment by Kwpolska** [comment]
PS. The `ipython` theme must be first installed via `nikola install_theme ipython` and set in your config file.

**Comment by roblem** [comment]
Thanks for the quick reply.

FYI: 
1. Using Ipython theme
2. Before upgrading to Ipython 3, the $ and $$ delimiters inside markdown cells worked perfectly.   Now the same notebooks (but saved as newer notebook version) have issues.

**Comment by Kwpolska** [comment]
Please post a link to a page that shows this issue and the `.ipynb` file.

**Comment by roblem** [comment]
[Here is the page](http://rlhick.people.wm.edu/test/posts/debug-latex-in-ipython-notebooks.html)  and the ipynb can be grabbed from the source link.  I also include a link to the nbconvert to html output which renders correctly.  This is using zen-ipython theme, but the same thing happens with the ipython theme.

**Comment by Kwpolska** [comment]
By default, Nikola ignores the `$x$` delimiters to prevent collisions with people talking about money.  You can enable support by setting `MATHJAX_CONFIG` in conf.py appropriately; there is a code snippet that will activate dollars for you that you can uncomment.

**Comment by roblem** [comment]
Yes, that did it.  Sorry for the bother.
