### ISSUE TITLE
Support mediawiki markup

### ISSUE THREAD

**Issue by djbclark** [getnikola/nikola#1654]
Not sure if this would be considered a dupe of #197 or not, if so, sorry.

For those of us who do a lot of editing on sites like wikipedia, support for mediawiki markup syntax in addition to markdown et al would be welcome.

This is, I think, the current best mediawiki to *ml converter library: https://github.com/lambdafu/smc.mw/

Ditto for parsing library: https://github.com/earwig/mwparserfromhell

**Comment by ralsina** [comment]
If it has a tool that generates HTML when called from the command line, then implementing it is pretty much a search/replace from the asciidoc plugin: 

http://plugins.getnikola.com/#asciidoc
https://github.com/getnikola/plugins/tree/master/v7/asciidoc

**Comment by Kwpolska** [comment]
@djbclark, would you mind providing some example on how to take a MediaWiki string with and convert it to HTML with `smc.mw`?  With that, writing a plugin would be quite easy (it would land in getnikola/plugins and not here though)

**Comment by ralsina** [comment]
smc.mw has not made a pypi release since 2013, even though it has commits in 2014 ... I'll do a quick plugin based on GH code, let's see how it goes.

**Comment by ralsina** [comment]
Also, release 0.3 fails with a syntax error in setup.py (!!!)

**Comment by ralsina** [comment]
So, after 15 minutes looking at the only usage example I can find (tool.py) I hate smc.mw with the intensity of 300, 400 suns.

**Comment by ralsina** [comment]
There you go: https://github.com/getnikola/plugins/commit/34e88237ea4a619f2b0c2d5e0cc719d8c64dc06d
