### ISSUE TITLE
CDN handling is not very smart

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1676]
Currently, we have a USE_CDN flag and we do things like:

```
        %if use_cdn:
            <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
            <script src="//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
            <script src="/assets/js/all.js"></script>
        %else:
            <script src="/assets/js/all-nocdn.js"></script>
        %endif
```

That's why bundles looks like this. Things we want bundled when we don't use a CDN:

```
assets/js/all-nocdn.js=jquery.min.js,bootstrap.min.js,jquery.colorbox-min.js,moment-with-locales.min.js,fancydates.js
```

Things we want bundled when we _do_ use a CDN, because jquery and others are handled in the template:

```
assets/js/all.js=jquery.colorbox-min.js,moment-with-locales.min.js,fancydates.js
```

This is very fragile!

One possible improvement is that we only keep all.js and then, IF the USE_CDN flag is set, we smartly remove from  all.js the ones that are available in the CDN and we update a global context variable (say, CDN_JS_URLS) to contain them.

So the template would look like this:

```
        %if use_cdn:
               ${CDN_JS_URLS}
        %endif
            <script src="/assets/js/all-nocdn.js"></script>
```

This could be a problem if the ORDER of JS loading matters but that problem already exists :-)

---

All of the above is when we are using bundles. When not using bundles, use_cdn implies the template author has to do all the work again:

```
        %if use_cdn:
            <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
            <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
        %else:
            <script src="/assets/js/jquery.min.js"></script>
            <script src="/assets/js/bootstrap.min.js"></script>
            <script src="/assets/js/moment-with-locales.min.js"></script>
            <script src="/assets/js/fancydates.js"></script>
        %endif
```

Here we could have a helper that takes a JS or CSS name as specified in the WIP branch and returns a local or CDN URL depending on use_cdn, so that the template, again, is simpler.

**Comment by Kwpolska** [comment]
:-1: from me.  All those URLs are **theme**–specific, we can’t just put them in the global context.

**Comment by ralsina** [comment]
Indeed they are theme-specific:

The theme is the one that has the bundles file. So, if it says we should bundle "flowtype.js" and it comes with a "flowtype.js".

If we are set to use CDN:

* Lookup "flowtype.js" in a table like https://cdnjs.com/
* Add https://cdnjs.cloudflare.com/ajax/libs/Flowtype.js/1.1.0/flowtype.min.js to that list of URLs
* Get it from there.
* Do not bundle the included "flowtype.js"

If we are set NOT to use CDN:

* bundle the included "flowtype.js"

The theme can even choose not to support this at all by not doing anything with that variable.

**Comment by ralsina** [comment]
Sadly, this gets complicated rather fast.

If you see the https://github.com/getnikola/nikola/tree/smarter-CDN branch it shows an idea of a notation that allows to automatically filter CDN-able assets.

However! There's no way to guarantee that said lists will be available when the pages are rendered, and since we do need that, then this will be racy.

A solution is to inject a dependency for the ``pages`` task so this plugin runs first, but at that point, is it worth it?

**Comment by ralsina** [comment]
Now that we have dependency injection for plugins, I will continue to explore in the smarter-CDN branch.

**Comment by ralsina** [comment]
Current idea is to have a sort of DSL in the theme's "bundles" file that makes all this work.
BUT that probably means it's not backwards-compatible, so marking as such.

**Comment by ralsina** [comment]
Did not get anywhere. Closing, will reopen if someone ever complains about it.
