### ISSUE TITLE
Something like #noqa for links for use with `nikola check -l`

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1681]
Need a way to tell `nikola check -l` not to fail on a given link (or possibly all links found in a given document). Something like flake’s `# noqa`.

Use cases:

* Forcing caching refreshes

    /assets/css/all-nocdn.css?updated
* Redirected URLs (RSS_LINK)

   /feed # with server-side rewrite to /index.atom
* Showing off errors because design blog

    /beautiful-error-page-404-preview

**Comment by ralsina** [comment]
LINK_CHECK_WHITELIST in conf.py :-)

**Comment by ralsina** [comment]
Maybe that could be a list of regexes instead of a list of links, I guess.

**Comment by Aeyoun** [comment]
Yeah, … user error. Sorry about not checking the code before bugging.
