### ISSUE TITLE
Max 49 998 files per sitemap file

### ISSUE THREAD

**Issue by da2x** [getnikola/nikola#1683]
Theoretical issue, but at some point in time someone will run into this much sooner because of issue #1610. Sitemaps should include no more than 50 000\* URLs**.

Luckily, we already have a sitemapindex so we can just create more sitemaps.

The problem right now is that we don’t know how many URLs will be included in the sitemap. So we don’t know how many sitemaps/tasks should be created. The `urlset` is only available to the sitemap plug-in after the `_scan_locs` task has run, but this is too late for task creation.

\* In practice it’s 49 998. Don’t ask.
** Not `<url>` elements, but any kind of URL. Including schema, or localized link alternative, etc. Really should keep a running count  `://` in the sitemaps as they’re created to get it right.

**Comment by ralsina** [comment]
Ugh. We can work around that by using a calculated dependency: 

http://pydoit.org/dependencies.html#calculated-dependencies

**Comment by ralsina** [comment]
Aeyoun: would it be good enough to parse the sitemap using lxml, count the links and just warn people that Nikola's sitemap support is limited to 49998 links?

**Comment by Kwpolska** [comment]
Wouldn’t it be good enough to just count links when we add them in `sitemap.py`?

**Comment by ralsina** [comment]
Noone is going to fix this until someone actually runs into it, and then pays someone to fix it or does it himself:

* It's difficult
* It's a theoretical problem so far
