### ISSUE TITLE
Some features should be moved to plugins

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1696]
Specially features that are not widely used, or "bad" for some reason. Feel free to add more ;-)
- [x] Annotations via annotateit.org (removed)
- [x] Post password-protection (removed)
- [ ] Tag cloud
- [x] Slides

**Comment by Kwpolska** [comment]
:+1:

**Comment by felixfontein** [comment]
The tag cloud JSON file is now written by a dedicated plugin `render_tag_cloud` (since PR #2535). Moving to to https://github.com/getnikola/plugins should be straightforward.

**Comment by felixfontein** [comment]
Moving the post encryption feature into a plugin should be no problem by adding a signal handler for the `compiled` signal emitted by `Post.compile`.

**Comment by gwax** [comment]
The commenting systems could probably be carved out as plugins as well. That way you could install the one you want and never consider the rest.

**Comment by Kwpolska** [comment]
You don’t need to care about other comment systems. Those templates will simply be ignored, and won’t ever appear in output (plus making them plugins would be hard).

**Comment by gwax** [comment]
I care about the commenting systems less from the perspective of using nikola and more from the perspective of theme development; they are annoyingly entangled with the rest of the base templates. Though, maybe that can be better solved by rearranging the base templates slightly.

**Comment by tritium21** [comment]
It is a major refactor to move comments into their own plugins (its been requested before)
