### ISSUE TITLE
Make scan_posts a plugin with a defined API

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1700]
Yes, I know, big refactor. But it could make for a much cleaner internal structure.

- [x] Move Nikola.scan_posts into a plugin
- [x] Create a ScanPost type of plugin that can be used to add more post sources
- [x] Clean up scan_posts code, removing unused options
- [x] Refactor code that puts posts in buckets (posts_per_year, etc) back into Nikola class
- [x] General code cleanup
- [x] Do we really need global_data? [No we don't, nothing in core or plugins uses it!]

Ohhhh crap, I had a bunch of stuff written down here and it's all lost now :-P

**Comment by felixfontein** [comment]
Part of that was already implemented in earlytask_impl branch. There, the functionality of scan_posts is still where it used to be, but it is called from precisely one place, namely a plugin of the same name. Moving the other code there as well shouldn't be a problem.

**Comment by ralsina** [comment]
Ok, since I did not follow that branch's progress, did not check that. Anyway, this would be the other half of that work, and it can be done independently.

I am also doing some cleanup (scan_posts had two arguments that it was never called with, for example)

**Comment by ralsina** [comment]
Also, since I want to make it possible that there be more than one post scanning mechanism (so someone can use this to aggregate data, fetch from databases, etc) I am creating a specific plugin category so we can call them all.

**Comment by felixfontein** [comment]
Yes, that sounds like a good idea. It would also be nice if the code which reads a post is separated from the code which processes the post (like the one which looks at its tags and categories). Then you don't have to copy too much code when creating such a plugin.

**Comment by ralsina** [comment]
Yes, all that code is going back into Nikola.scan_posts :-)

**Comment by felixfontein** [comment]
Is the general idea that such a plugin returns a list of Post objects (or something similar), and then the post-processing (adding the post to the tags/category maps etc.) is done by scan_posts (or whatever asks the plugins to return a list of posts)?

**Comment by ralsina** [comment]
I think so, yes.

**Comment by felixfontein** [comment]
Sounds great, then :)

**Comment by Kwpolska** [comment]
Why is that not closed yet if all the checkboxes are checked?  Are there more things to do?

**Comment by ralsina** [comment]
Good point, let's close it.
