### ISSUE TITLE
Configurable theming

### ISSUE THREAD

**Issue by da2x** [getnikola/nikola#1701]
OK, it’s late so thinking may not be 100% but here we go.
1. Theme author provides `configurable.css` with a few mako-variables or something
2. Theme author provides default values for variables in `configurable.css`.
3. User overrides these variables through options in `conf.py`
4. Nikola generates `assets/css/configurable.css`, filling in the user’s option values or the theme author’s fallback values
- CSS_COLOR_PRIMARY
- CSS_COLOR_SECONDARY
- CSS_COLOR_TEXT
- CSS_PAGE_COLOR_BACKGROUND
- CSS_PAGE_IMAGE_BACKGROUND
- CSS_FONT
- CSS_CUSTOM – just inserted as-is at the end of `configurable.css`

We’d get prospecting users going much quicker if themes were tweakable. It’s easier to grow attached to something you’ve painted bright pink yourself and lovingly can call “home.”

**Comment by davidak** [comment]
one of the first things i changed in wordpress was the header image. it was really nice to have a self taken photo there.

the options should be easy to understand and it should be hard to make a nasty looking site. advanced users can still customize the themes CSS.

the [lanyon theme](https://themes.getnikola.com/#lanyon) has already color variants and [material-theme](https://themes.getnikola.com/#material-theme) has also links and author's biography.

we can suggest theme developers a good workflow and some standard variables so it's more consistent for users.

**Comment by ralsina** [comment]
So ... this has been open for 5 years. The themes that need this sort of thing just documented it and suggest the user should use some GLOBAL_CONTEXT.

So ... let's close it. Leaving wishes open for years is not useful for anyone :-(

**Comment by Kwpolska** [comment]
Well, `THEME_CONFIG` is a thing since v8.
