### ISSUE TITLE
Related posts as JSON

### ISSUE THREAD

**Issue by da2x** [getnikola/nikola#1702]
/posts/post-slug.html should optionally have an accompanying /posts/post-slug.json (link and title only?) that contains related posts.

Simple logic for “related”:
- other  posts with similar tags
- other  posts with similar title keywords
- other posts with similar body keywords

Need to assign scores to each of these signals.

Ideally, only the JSON should need to be rebuilt and not the page. Plug-in material, maybe?

**Comment by ralsina** [comment]
Tool that could make this feasible: https://github.com/piskvorky/gensim

**Comment by Aeyoun** [comment]
We should keep this in sync with the format used in the recent post JSON plug-in.
https://github.com/getnikola/plugins/tree/master/v7/recent_posts_json

**Comment by Aeyoun** [comment]
I expanded the https://github.com/getnikola/plugins/tree/master/v7/recent_posts_json plugin to create individual JSON files for each section. For sectioned sites, this will at least improve relevance.

**Comment by Aeyoun** [comment]
@ralsina, any progress? I’m considering moving to WordPress and this feature right here is at the top of the list of reasons to go with WordPress.

**Comment by ralsina** [comment]
Amazing what things I have marked as in progress through the years.

**Comment by ralsina** [comment]
Done as a plugin.
