### ISSUE TITLE
support for shortcodes

### ISSUE THREAD

**Issue by gour** [getnikola/nikola#1707]
In order that Nikola's features could be as markup-independent as possible, iow. having no features depending on usage of reST, it would be nice to have feature similar to Hugo's [shortcodes](http://gohugo.io/extras/shortcodes/).

Several things need to happen here:
- [x] Support for registering and using shortcodes (merged)
- [x] Support for template-based shortcodes (merged)
- [x] Support for converting template-based shortcodes in jinjify (in #2195)
- [x] Load shortcodes from a folder shipped with Nikola (template system dependent) (in #2195)
- [ ] Provide the same built-in filters as Hugo does (not many, not hard!)
- [ ] Using the shortcodes from each compiler (because of backwards compat, I can't do it in all at once)
  - [x] Done as an example in markdown
- [ ] Convert some interesting features, like post-list into shortcodes
  - [x] Done for post-list
- [x] Document it from the user's POV
- [x] Document it from the developers POV

I am starting a PR for this, will check progress here

**Comment by Kwpolska** [comment]
An implementation requires:
* a syntax that will not collide with other things (eg. `\[math\]`),
* a syntax that will be easily parseable with regular expressions,
* a syntax that does not involve characters like `<>&\` and other things that might result in weird output by markup languages,
* a syntax that can be inserted inline (HTML comments won’t do it in most markups),
* being implemented somewhere in the post.text pipeline.

**Comment by gour** [comment]
Hugo use syntax like:

```
{{< figure src="/media/spf13.jpg" title="Steve Francia" >}}
```

What about that?

**Comment by Kwpolska** [comment]
> a syntax that does not involve characters like <>&\ and other things that might result in weird output by markup languages,

The other Hugo syntax, `{{% foo %}}`, should be fine

**Comment by gour** [comment]
> The other Hugo syntax, {{% foo %}}, should be fine

Considering that *foo* is supposed to do a lot, it's quite good. ;)

**Comment by konilabs** [comment]
Hi, I agree this would be a great feature. :+1: 

In my case when using Nikola 
- I use Rest for simple pages like Articles and Documents. I like a lot extensions like post-list.
- When doing complicated pages (lot of content in multiple columns, with lot of bootstrap containers) I prefer to go with HTML, but I cannot use anymore post-list or do file includes.

Short code would be nice, or something to add a little bit of rest inside HTML/PHP, or maybe some kind of standard interface to pass parameters to extensions.

Thanks a lot !

**Comment by ralsina** [comment]
I have started exploratory work on this.

**Comment by gour** [comment]
:thumbsup:

**Comment by ralsina** [comment]
This is now in master for markdown, read the docs for details on how to start using it. Still more work to be done, though.

**Comment by ralsina** [comment]
This was open long enough. Let's open new issues for specific things.
