### ISSUE TITLE
Refactor the Post object

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1709]
The Post object is way too complex at this point.

1) post.py is over 1000 LOC
2) `Post.__init__` is over 150 LOC
3) The `Post` class has 36 methods
4) We have 5 (five!) different ways to extract metadata

So, proposed solutions:
- [ ] Create an abstract Post class
- [ ] Move some things into plugins [1]
- [x] Deprecate stuff (example: old-old metadata!)
- [x] Move some things out of core directly (encryption)
- [x] Maybe refactor metadata extraction into compiler plugins? (Get docinfo from docutils, etc) (~~This is #618~~ no it's not)

[1] For example, estimated read time could be implemented as metadata. We could create a mechanism for adding metadata to posts. Could be separated into plugins. Those will use the Post class to add data to it.  Makes for a very simple way to extend the Post class, without commiting to core.

**Comment by felixfontein** [comment]
How about two new plugin classes for points 2 and 4:
 - post preprocessing:
   - they get the `Post` object and `lang` and can add additional metadata or dependencies
 - post postprocessing:
   - receives the compiler's output (or the previous postprocessor's output), the `Post` object and `lang`
   - the encryption plugin is a natural candidate for this

Perhaps in the following form:
``` .py
class PostPreprocessor(BasePlugin):
    """Preprocess a Post object before compiling."""

    name = "dummy_post_preprocessor"

    def preprocess(self, post, lang):
        """Preprocess the Post object before compiling."""
        raise NotImplementedError()

class PostPostprocessor(BasePlugin):
    """Postprocesses a compiled Post."""

    name = "dummy_post_postprocessor"

    def postprocess(self, data, post, lang):
        """Postprocess the compiled post.

        Obtains the compiled post ``post`` in language ``lang`` as ``data``
        as a decoded string. Must return the new post contents as a string.
        """
        raise NotImplementedError()
```
What is to be decided is whether the postprocessing will be done before or after the `compiled` signal. (Obviously, one could implement postprocessing also a `SignalHandler` listening to the `compiled` signal. It doesn't receive `lang`, though. And I think having an own plugin category is cleaner.)

**Comment by felixfontein** [comment]
The post postprocessing plugin type isn't really needed, this can be handled by a signal handler listening for `compiled` (emitted by `Post.compile`).

**Comment by gwax** [comment]
This situation seems like it might be a better case for encapsulation than for abstraction. What I hear (and read in the code) is that metadata processing is complex and gums up the `Post` object. That seems to argue for carving out metadata processing to another class (or maybe just some functions in a separate module) so as to allow `Post` to focus on posts.

**Comment by Kwpolska** [comment]
We aren’t doing this in version 8, although some of these things are more-or-less done.

**Comment by ralsina** [comment]
The valid part of this ticket is that ``Post.__init__`` is ridiculous (250 LOC right now) so I will try to refactor that a bit and then we can close it.

**Comment by ralsina** [comment]
Done and closing. Further refactors and cleanups are possible, of course.

**Comment by remram44** [comment]
Does this solve #2659?

**Comment by ralsina** [comment]
@remram44 not at all.

I am about to start taking a look at it, tho :-)

**Comment by remram44** [comment]
Oh no! Haha.

Thanks for looking into it!
