### ISSUE TITLE
submenu: click on the parent item, then clicking elsewhere makes the whole menu item gone

### ISSUE THREAD

**Issue by xuhdev** [getnikola/nikola#1714]
You can reproduce the bug on [my website](http://www.topbug.net).

1. Click on the "About" menu,
2. then click elsewhere on the webpage (any blank space),
3. see the "About" menu gone.

I can reproduce this bug on bootstrap3 and bootstrap3-gradient theme.

I'm using nikola 7.4.1

**Comment by ralsina** [comment]
Hmmm looks like clicking outside the menu is setting ``display: none`` on the ``li`` ... maybe we are not generating exactly correct HTML for the menu.

**Comment by Kwpolska** [comment]
I cannot reproduce with a clean site.  Maybe you have some fancy JS that conflicts with Bootstrap’s?

Normal (clean) site:

```html
<li class="dropdown">
↓  open ↓
<li class="dropdown open">
↓ close ↓
<li class="dropdown">
```

Your site:

```html
<li class="dropdown">
↓  open ↓
<li class="dropdown open" style="display: block;">
↓ close ↓                 ^^^^^^^^^^^^^^^^^^^^^^^
<li class="dropdown" style="display: none;">
                     ^^^^^^^^^^^^^^^^^^^^^^

**Comment by Kwpolska** [comment]
https://comments.topbug.net/js/count.min.js seems to be at fault, according to Chrome’s Web Inspector (with *Break on attributes modifications*)

**Comment by Kwpolska** [comment]
https://comments.topbug.net/js/count.min.js seems to be at fault, according to Chrome’s Web Inspector (with *Break on attributes modifications*)

**Comment by Kwpolska** [comment]
This is isso’s fault.  It looks like it’s a bit too greedy when it comes to registering its handlers — and it seems to mess with Bootstrap’s own dropdown code.

cc @posativ (isso dev) — please investigate.

**Comment by posativ** [comment]
Played around a bit with Chrome's Devtools and I have no idea why this might happen. @Kwpolska I do not register any handlers (except dom ready boilerplate), maybe a dependency interferes here.

**Comment by xuhdev** [comment]
@posativ Thanks for investigation. Let me know if you need any help
