### ISSUE TITLE
Restructure demo/template site a bit

### ISSUE THREAD

**Issue by da2x** [getnikola/nikola#1721]
The demo site includes this configuration:

```
POSTS = ( ("posts/*.html", "posts", "post.tmpl") )
```

I’m suggesting we move the posts directory into a new content directory, like this:

```
POSTS = ( ("content/posts/*.html", "posts", "post.tmpl") )
```

It better illustrate how output URLs can be customized and encourages all “source content” be kept together in one directory rather than spreading it in multiple directories directly  under the site root. It help illustrate that Nikola is not “just a blog  software” by better conveying how to customize it.

An extra comment would probably also be beneficial here:

```
POSTS = (
    # (source-directory, destination-path/url, template )
```

   … )

What do you guys think? @Kwpolska @ralsina

**Comment by Kwpolska** [comment]
:-1: from me. This will:

* invalidate **all** existing documentation, tutorials, etc. — including those written by the community
* bring little benefit to the user while hiding all the directories away (making it harder to discover)
* lead to some (slightly controversial) decisions: are themes and files content or not?  For some people they are, for some they are not.  `files` can contain both “content” (various media relating to blog posts) but also assets (JS, CSS, whatever)

People should just read the comment above `POSTS` and `PAGES`, which will explain everything.  We could also add some docs to the handbook.
