### ISSUE TITLE
Guessable URLs and posts directory indexes

### ISSUE THREAD

**Issue by da2x** [getnikola/nikola#1722]
The demo site suggests putting content into a posts/ directory. If a visitor where to guess that there are more posts by going directly to that folder (eg. stripping "content.html" from the URL "/posts/content.html", they’ll more than likely get a 403 Forbidden or possibly an nginx or Apache directory index.

Nikola should build indexes for post directories if there are more than one post directory (eg. "posts" and "reviews") _OR_ redirect to the front-page if there is only one such directory (avoiding identical content duplication).

A more complex example:

```
POSTS = (
    ("content/posts/*.html", "posts", "post.tmpl"),
    ("content/review/apps/*.html", "review/apps", "post.tmpl"),
    ("content/review/books/*.html", review/books", "post.tmpl"),
)
```

I’ve solved this on my own sites by redirecting `posts/index.html` to `archive.html`.

**Comment by Kwpolska** [comment]
So basically, like STORY_INDEXES, just for posts?

**Comment by Kwpolska** [comment]
> I’ve solved this on my own sites by redirecting `posts/index.html` to `archive.html`.

You can get rid of `archive.html` and use `posts/index.html` for all your archiving needs:

```py
ARCHIVE_PATH = "posts"
ARCHIVE_FILENAME = "index.html"
```

**Comment by Aeyoun** [comment]
> So basically, like STORY_INDEXES, just for posts?

Yep. Although that seems to be hardcoded to use the list template and not index.

> You can get rid of archive.html and use posts/index.html for all your archiving needs:

That will only work when you have one output directory for all posts.

**Comment by felixfontein** [comment]
Isn't this kind of covered by sections and their indexes?

**Comment by Kwpolska** [comment]
It sounds like it.
