### ISSUE TITLE
Support for bitballoon

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1724]
Bitballoon has a cool thing, which is static hosting that supports forms (automatically stored in DBs).

So, I will (when I have a free day or two) implement the following:
- [x] A rst plugin to create forms
- [ ] A nikola plugin to deploy to bitballoon
- [ ] A document explaining how it all works

**Comment by Kwpolska** [comment]
> A rst plugin to create forms

This is a ton of work, especially if you want it too look nice.  IMO forcing `.. raw:: html` will work out much better for everyone.

**Comment by znmeb** [comment]
My Nikola blog is on bitballoon so any code will be appreciated

**Comment by ralsina** [comment]
One way to do this is to bridge a python forms library like [WTForms](https://wtforms.readthedocs.org/en/latest/forms.html) to directive syntax, a bit like we do for pygal and charts.

Another is to use a JS forms library like [Alpaca](http://www.alpacajs.org/) and just pass along the data it uses to build the forms as directive content. That one is probably less than one hour of work.

**Comment by ralsina** [comment]
Implemented a forms plugin as https://github.com/getnikola/plugins/commit/49ebb6838a7eafb53406c6fce110711897422df1

**Comment by ralsina** [comment]
Just use netlify.
