### ISSUE TITLE
auto doesn't rebuild in some situations

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1729]
- [ ] When there's a tag collision
- [ ] When adding a new post via command line

**Comment by ralsina** [comment]
In fact, It doesn't rebuild for me in a number of circunstances, like "adding a new post"

**Comment by Aeyoun** [comment]
Oh, I knew about that one too. Don’t know why I didn’t consider *that* a bug. Probably because this took me longer to figure out. ;)

**Comment by ralsina** [comment]
Strangely, it seems to work for adding posts when I use ``nikola auto -b``!

**Comment by ralsina** [comment]
Reported this as https://github.com/lepture/python-livereload/issues/109

**Comment by ralsina** [comment]
"This is intentional". Asking if livereload author accepts patches to make this an option. If not, I'll just rewrite the thing.

**Comment by Kwpolska** [comment]
How will you “rewrite it”?

**Comment by ralsina** [comment]
livereload.js is from another project (the original livereload). I could do a simple wsgi app (no tornado) and use inotify directly. It's probably 200 LOC in all.

**Comment by Kwpolska** [comment]
Or you could hook into `doit auto` (aka `nikola doit_auto`).

**Comment by ralsina** [comment]
Good point.

**Comment by lepture** [comment]
FYI.  https://github.com/lepture/python-livereload/issues/109 is solved.
