### ISSUE TITLE
Less aggressive rebuild triggers when changing POSTS

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1735]
1. Set conf.py to:  `POSTS = (("some-post-here/*.html", "some-posts-here", "post.tmpl"))`
2. build
3. Set conf.py to: `POSTS = (
        ("some-post-here/*.html", "some-posts-here", "post.tmpl"),
        ("others-go-here/*.html", "others-go-here", "post.tmpl")
    )`
4. build

Shouldn’t have to rebuild "some-posts-here" posts because "others-go-here" were added. (Indexes and other resources need rebuilding, sure. Maybe if you retroactively change some posts and mess up the timeline it also need to rebuild. adding an empty category (or a new post in new location) shouldn’t force rebuild of everything.)

**Comment by ralsina** [comment]
Nikola currently errs in the side of caution. If you can make it be more refined, by all means go ahead :-)

**Comment by ralsina** [comment]
If the 3rd location you add inserts posts in the timeline, then the posts before/after those it adds need rebuilding, which is a bit tricky to detect, but I think we do that already.

**Comment by Kwpolska** [comment]
This would require a lot of effort for not much gain. Perhaps we could close this?

**Comment by ralsina** [comment]
Yes, closing.
