### ISSUE TITLE
`nikola status`

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1740]
Just thinking out loud here …

    $ nikola status
    The last build succeeded.
    2 days and 6 hours since last deployment.
    48 files have changed (including 1 new post) since then.
    2 scheduled post (next in 58 hours), and 2 drafts.
    You’re running the latest version of Nikola.

Any interest? (I keep mistyping “git status” and though “Hey, Nikola could do something useful here.”)

**Comment by ralsina** [comment]
Sounds interesting.

**Comment by duck** [comment]
+1
