### ISSUE TITLE
No useful error when two posts have same slug

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#1749]
As noticed in #1748, if two posts (or pages) in the same output directory have the same slug, no good error message is given. (Usually doit will emit an error since two tasks generate the same target.)

I think it would be a good idea if after scanning all posts, a check for duplicate slugs in the same directory is performed and warnings are emitted if such situations occurr. (I'm hesitant to make this an error since depending on where -- and by whom -- things are written to in the output, the tags might not collide in the end.) What do you think about that?

**Comment by ralsina** [comment]
Checking if two posts have the same output file is very easy, just look at them after the timeline is built :-)

**Comment by felixfontein** [comment]
Assuming that the posts plugin isn't disabled for some reason, that makes sense. I can add it, though probably neither today nor tomorrow. So if you want to do it before that, feel free :)

**Comment by ralsina** [comment]
I got it then
