### ISSUE TITLE
build and deploy when schedule time is past

### ISSUE THREAD

**Issue by da2x** [getnikola/nikola#1752]
Optionally add build and deploy on schedule time is reached. Maybe using `atq`.

**Comment by ralsina** [comment]
Something like:

``nikola schedule_next_post``

Which would do:

```
echo 'nikola build && nikola deploy' | at datetime-of-next-post + 5 sec
```

And maybe a ``--all`` which would do that for **all** the pending posts.

**Comment by Aeyoun** [comment]
This should work for Mac, Linux, and BSD. Windows’ MS-Schedule requires user to be an administrator and is generally unpleasant to work with.

`nikola build --on-schedule` ?

**Comment by ralsina** [comment]
Adding extra options to build is complicated. Deploy is more doable.

**Comment by SpotlightKid** [comment]
Please don't add a scheduler to Nikola. That's what OSes are for.

**Comment by felixfontein** [comment]
I agree. Why not add this as a plugin to the plugins repository?

**Comment by tritium21** [comment]
This should be handled with documentation, instead of code.

**Comment by ralsina** [comment]
So, let's not do this.
