### ISSUE TITLE
nikola status: show list of scheduled posts, or at least next scheduled post

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#1753]
What what you think about `nikola status` also showing a list of scheduled posts (with time until they are scheduled, ordered by that), or at least the next scheduled post's source path / title?

If nobody minds, I'll implement that.

**Comment by felixfontein** [comment]
And possibly also a list of drafts.

And maybe let's make displaying the lists depend on command line arguments.

**Comment by Aeyoun** [comment]
It already does some of this. It will show how long into the future the next scheduled post is due. It does not check if there is a post newer than the deployment date, though. It probably should.

I also thought about `nikola diff`. Possible git integration point?

**Comment by Aeyoun** [comment]
I’m all for more features in status. Give me an overview of what my site is up to so I don’t have to track it in my mind. My mind is better suited to other tasks.

**Comment by felixfontein** [comment]
Yes, that was my motivation to actually show *which* posts are scheduled to be shown when that time elapses. Or even better, all scheduled and draft posts, so you can see what you were working on (some people like me tend to forget or have drafts open for years). :)

What precisely should `nikola diff` do? Everything I can think of is quite hard to implement and requires either caching all source files somewhere (or let git/svn/... do that for your), or running nikola to another subdirectory and diffing that one with `output`.

**Comment by Aeyoun** [comment]
I was thinking that diff would show which files are new and what change have happen in output since last deployment to now.

**Comment by felixfontein** [comment]
Ah. That's actually a good idea (and isn't as hard to implement as I was afraid of :) ).

Anyway, I'll start implementing the other `nikola status` features mentioned so far (probably tomorrow or Friday).

**Comment by felixfontein** [comment]
@Aeyoun: do you want this issue to be left open for your `nikola diff` ideas, or should that go into a new issue?
