### ISSUE TITLE
Inject and remove for `serve` and `auto`

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1755]
Settings for removing and injecting things into auto and serve. Similar to how the browser reloading script is injected when using auto.

I’m confusing some third-party scripts when viewing my pages from 0.0.0.0. Would like to strip them out when serving locally.

**Comment by ralsina** [comment]
It's injected in a rather naïve way....

**Comment by Aeyoun** [comment]
This is quite impossible with the new livereload implementation. I solved my usecase with a [JavaScript domain blacklisting extension](https://addons.mozilla.org/firefox/addon/yesscript/) instead.

**Comment by Aeyoun** [comment]
Well, by blocking all JavaScript on the local domains, I also kill off the autoreload feature. So … kind of solved my usecase.

**Comment by ralsina** [comment]
Why is it impossible?

We could:

1) Support user-defined functions that process the file before sending to the browser
2) Inject using a less naïve mechanism, like lxml node injection
