### ISSUE TITLE
`nikola auto -b -a ::` crashes Firefox

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1756]
Scanning posts........done!
    Serving on http://:::8000

Firefox launches with two windows and crashes. Seems to be triggered by broken address http://:::8000. Should be http://[::]:8000 which does not crash.

**Comment by Kwpolska** [comment]
this is not a problem in `nikola serve` which correctly formats the URLs

**Comment by ralsina** [comment]
``-b -a :: -6`` works and binds to :::8000 (-b doesn't work for me but maybe I am ipv4 only)

``-b -a [::]`` works and binds to :::8000 (-b doesn't work for me but maybe I am ipv4 only)

Maybe we don't really need -6?

I'll leave it to more informed people.

**Comment by Aeyoun** [comment]
@ralsina, the reason -b doesn’t work for you must be the broken addresses your browser are told to open.

**Comment by Kwpolska** [comment]
`-6` is not strictly needed to use IPv6, as it is basically `-a ::`.  To fix `-b`, it needs some change in URL formatting, see `serve.py` for an example

**Comment by ralsina** [comment]
I am not fixing this one. Volunteers much appreciated.

**Comment by Kwpolska** [comment]
fixed in 5133ac3208f24893d9bb4b5e106356c5483bece2 (on new-auto)

**Comment by ralsina** [comment]
Thanks @Kwpolska !
