### ISSUE TITLE
serve and auto anti-robotism

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1757]
Googlebot started indexing my auto instance. No idea how it found the URL. Had shared it with a friend to discuss. Anyway, this should be blocked.

Special-handle /robots.txt when using serve and auto to return:

    User-Agent: *
    Disallow: /

**Comment by ralsina** [comment]
Fixed in https://github.com/getnikola/nikola/commit/972d67d44d80e48f549169d95cd9e76327031a1f

**Comment by Kwpolska** [comment]
PS. Not sure if we should do it in `nikola serve`, some people might abuse it as an Internet-facing thing, or notice the bad file and complain.

**Comment by ralsina** [comment]
I disagree with doing it in ``nikola serve``. It may be lame, but it's a normal server which should act like a normal server.
