### ISSUE TITLE
Add --list-available or --list-installed to nikola plugin

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1761]
Since there is no obvious way to know what plugins are installed in a site.

**Comment by ralsina** [comment]
This already exists :-)

**Comment by Aeyoun** [comment]
You’re so smart you reached into the past to implement it for when you needed it now. Sure sign of a great developer.

**Comment by ralsina** [comment]
Either that, or early(ish) onset Alzheimer.
