### ISSUE TITLE
Nikola makes HTML5 video source tags invalid

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#1768]
If you use a `<video>` element with a `<source>` tag in a post, theme, ..., Nikola generates a `</source>` for every `<source ...>`, which is not valid HTML5.

This happens in the last few lines of `Nikola.render_template()` in `nikola/nikola.py`:
```
parser = lxml.html.HTMLParser(remove_blank_text=True)
doc = lxml.html.document_fromstring(data, parser)
doc.rewrite_links(lambda dst: self.url_replacer(src, dst, context['lang']))
data = b'<!DOCTYPE html>\n' + lxml.html.tostring(doc, encoding='utf8', method='html', pretty_print=True)
```
This is a problem of lxml.html (or maybe of something they use), so nothing we can easily fix.

I'll try to investigate more when I'm more motivated and have some more time... (For my blog, I can "fix" this by replacing "</source>" with "" in all .html files... That's no good solution in general, though...)

**Comment by felixfontein** [comment]
Minimal example to reproduce (with lxml directly):
```
import lxml.html

data = """<!DOCTYPE html>
<html>
  <head>
    <title>1</title>
  </head>
  <body>
    <video>
      <source src="1.ogv" type="video/ogg">
    </video>
  </body>
</html>"""

parser = lxml.html.HTMLParser()
doc = lxml.html.document_fromstring(data, parser)
data = b'<!DOCTYPE html>\n' + lxml.html.tostring(doc)
result = data.decode('utf-8')

assert result == """<!DOCTYPE html>
<html>
  <head>
    <title>1</title>
  </head>
  <body>
    <video>
      <source src="1.ogv" type="video/ogg">
    </source></video>
  </body>
</html>"""
```

**Comment by Aeyoun** [comment]
tidy5 fixes this.

The source element is also used with the audio and picture elements.

**Comment by felixfontein** [comment]
The problem seems to be that the HTML tag list of libxml2, which is used by lxml, is stuck to HTML 4.

**Comment by ralsina** [comment]
Looks like lxml devs are aware of this:

https://github.com/lxml/lxml/blob/f8bdb7d48b5cf4403aa6bbbf10f5f8da6a4a510e/src/lxml/tests/test_incremental_xmlfile.py#L342

**Comment by Kwpolska** [comment]
maybe we could ask for help on their mailing list?

**Comment by ralsina** [comment]
@Kwpolska looks like @felixfontein already asked :-)

https://mailman-mail5.webfaction.com/pipermail/lxml/2015-May/007524.html

**Comment by ralsina** [comment]
Found a way!

```
>>> import html5lib
>>> lxml_etree_document = html5lib.parse("""<!DOCTYPE html>,
... <html>
...   <head>
...     <title>1</title>
...   </head>
...   <body>
...     <video>
...       <source src="1.ogv" type="video/ogg">
...     </video>
...   </body>
... </html>""", treebuilder="lxml")
>>> import html5lib.serializer
>>> print html5lib.serializer.serialize(lxml_etree_document,tree="lxml")
<!DOCTYPE html>,

  
    <title>1</title>
  
  
    <video>
      <source type=video/ogg src=1.ogv>
    </video>
```

**Comment by ralsina** [comment]
A little more research and it does a nice job:

```
>>> print html5lib.serializer.serialize(doc, tree="lxml", format="html", omit_optional_tags=False)
<!DOCTYPE html><html><head>
    <title>1</title>
  </head>
  <body>
    <video>
      <source type=video/ogg src=1.ogv>
    </video>
  
</body></html>
```

**Comment by felixfontein** [comment]
@ralsina: looks good, at least the try with `omit_optional_tags=False`. Interestingly, both W3C validators accept the shorter fragments without `<body>`, `</body>` and `</html>` as valid. Apparently, the closing tags have already been optional for some time (http://stackoverflow.com/questions/3008593/html-include-or-exclude-optional-closing-tags). Also, here: http://www.w3schools.com/htmL/html5_syntax.asp it is written that `<body>` and `<html>` can be omitted as well. Interesting; I really didn't knew that.

**Comment by felixfontein** [comment]
In case anyone cares, the detailed rules for HTML5 in which precise cases something can be omitted are here: http://www.w3.org/TR/html5/syntax.html#optional-tags

**Comment by Aeyoun** [comment]
You loose XML parsability by dropping those tags. (Only doctype and the title element are strictly required by the spec.)

**Comment by felixfontein** [comment]
You already lose XML parsability by using HTML5, since closing some tags (such as `<source>`) is illegal. Anyway, I'd prefer to have as many closing tags as possible (i.e. allowed).

**Comment by ralsina** [comment]
We can trivially make this configurable if you guys tell me this serializer is worth using (I defer because I am no expert in this)

**Comment by Kwpolska** [comment]
```html
<!DOCTYPE html><html><head>
    <title>1</title>
  </head>
  <body>
    <video>
      <source type=video/ogg src=1.ogv>
    </video>

</body></html>
```

Are there really no quotes around `video/ogg` and `1.ogv`?  That’s ugly.

**Comment by ralsina** [comment]
Well, that's legal as long as the attribute value has no " ' ` = <  > or space...

**Comment by Kwpolska** [comment]
It is legal, but it just looks bad.  Besides, I’m not sure if we should change the entire rendering pipeline just to address one minor tag…

**Comment by Aeyoun** [comment]
I’ve bashed html5lib over the head with the troublesome areas I know about (was a browser tester for five years, after all) and can’t immediately find anything wrong with it. I’d say it’s better† than the current solution and recommend that we proceed with html5lib.

I suggest providing two presets in an option (`HTML_OUTPUT = "minified" | "xml-like"`) to make everyone stylistically happy. The two main choices boils down to minified versus XML(-like).  Defaulting to "xml-like" will produce output similar to what Nikola does today.

Minified:
* `quote_attr_values=False`
* `omit_optional_tags=True`
* `minimize_boolean_attributes=True` (can break stringmatched JS/CSS, but nothing by default uses it)
* `strip_whitespace=True`
* `alphabetical_attributes=True`

XML-like:
* `quote_attr_values=True`
* `use_trailing_solidus=True`
* `alphabetical_attributes=True`
* `strip_whitespace=False` (because no understanding of xml:space nor CDATA)

 † From glancing over their code, they seem to know what a bastard HTML (authors) can be and know how to deal with it. Solves problems I’ve worked around using the tidy5 filters (which is much slower than html5lib). Produces output that should yield better compression.

**Comment by felixfontein** [comment]
I like Aeyoun's proposal a lot. XML-like should be the default, since it is closest to what lxml outputs (if I'm not mistaken).

**Comment by Aeyoun** [comment]
The main differences with "XML-like" from today’s output is attribute sorting and consistent trailing solidus. I also agree that XML-like should be default, even though I’m likely to opt for minified myself. (Got to save those bytes.)

**Comment by ralsina** [comment]
If we refactor "write this tree to a file" into a separate function (which we should anyway, because it's duplicated) we can make this all work easy and improve the code quality and test coverage at the same time.

**Comment by ralsina** [comment]
I have not tried it but we may want to keep using lxml's parser and just use html5lib's serializer.

**Comment by Kwpolska** [comment]
If I were to make the final decision, I would not give users a choice (since less than 10 people are going to be aware of the option’s existence, let alone know the difference and actually care about that) and instead pick a good compromise of the options.  I would personally opt for minified + `quote_attr_values=True`, but that’s only my opinion.

**Comment by ralsina** [comment]
Blah, html5lib crashes if the LXML tree contains a ProcessingInstruction node :-(

It looks like a bug (or rather a missing case) in their ``lxmltree.TreeWalker.getNodeDetails``

I am so not going to shave that yak...

For an example failure, check the enter-html5lib branch with the demo site's ``charts`` story.

**Comment by Aeyoun** [comment]
Added two new filters so anyone can quickly test this against their sites: html5lib_minify and html5lib_xmllike.

**Comment by ralsina** [comment]
Since this doesn't get rid of LXML, A filter is a very good idea, I say that's it.
