### ISSUE TITLE
error when running command 'nikola'

### ISSUE THREAD

**Issue by riovan** [getnikola/nikola#1769]
I get an error when running nikola. I installed nikola[extras] through pip. I'm running python 2.7 on windows 7. Traceback below.

```pytb
D:\>nikola
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\nikola.exe\__main__.py", line 9, in <module>
  File "C:\Python27\lib\site-packages\nikola\__main__.py", line 150, in main
    DN = DoitNikola(site, quiet)
  File "C:\Python27\lib\site-packages\nikola\__main__.py", line 268, in __init__

    super(DoitNikola, self).__init__()
  File "C:\Python27\lib\site-packages\doit\doit_cmd.py", line 58, in __init__
    ini_config = self.load_config_ini(config_filenames)
  File "C:\Python27\lib\site-packages\doit\doit_cmd.py", line 71, in load_config
_ini
    cfg_parser = ConfigParser(allow_no_value=True, delimiters=('=',))
TypeError: __init__() got an unexpected keyword argument 'delimiters'

D:\>
```

**Comment by felixfontein** [comment]
That looks like a problem of doit; it needs configparser with Python 2. Maybe your installed version of configparser is too old?

Can you show us your output of `pip show configparser`?

**Comment by Kwpolska** [comment]
Are you sure you have the `configparser` module from PyPI installed (which should be a dependency)?  It looks as if you were running with Python 2’s old `ConfigParser` and not the backport.  The import statement in doit seems to be correct (`from configparser import ConfigParser`).

I’m going to try and reproduce myself.

cc @schettino72

**Comment by riovan** [comment]
D:\repositories>pip show configparser
---
Metadata-Version: 2.0
Name: configparser
Version: 3.3.0.post2
Summary: This library brings the updated configparser from Python 3.2+ to Python
 2.6-2.7.
Home-page: http://docs.python.org/3/library/configparser.html
Author: ┼üukasz Langa
Author-email: lukasz@langa.pl
License: MIT
Location: c:\python27\lib\site-packages
Requires:

D:\repositories>

**Comment by Kwpolska** [comment]
Run `pip install --upgrade configparser`.  Then check `python -c 'import configparser; print configparser.__file__'` and post the output here; also try running `nikola` again.

**Comment by riovan** [comment]
Ah, well. I did an uninstall/install, but it didn't work. Then I saw that it wasn't deleting the directory fully when uninstalling. I deleted the configparser dir manually and reinstalled; it works now. Thanks!
