### ISSUE TITLE
Drop lxml?

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1770]
We have had a bunch of issues with it:

1) It breaks video/audio tags
2) It doesn't replace srcset URLs
3) It's a bit complicated to build (requires unusual -dev packages)
4) Pretty-printed output (at least prettier)

Probably others I don't recall.

So, what could we use instead? A quick pypi search shows

https://pypi.python.org/pypi/html5lib/0.99999

When used along with lxml, html5lib does nice things! See #1768 comments.
Sadly, it explodes with things like the charts post in the demo.

https://pypi.python.org/pypi/AdvancedHTMLParser/3.1.2  -- Feels immature

https://pypi.python.org/pypi/gumbo/0.10.0  -- Painful to install, not packaged anywhere

I am not an expert in these things. Any thoughts?

**Comment by Kwpolska** [comment]
For starters, we need something that can parse and *write* HTML and *XML*.

This could be a little help (though it’s doubtful): http://lxml.de/html5parser.html

**Comment by Aeyoun** [comment]
Added pretty-print.

**Comment by ralsina** [comment]
Apparently gumbo can be used as a parser replacement for lxml, which would make the writing problem a non-issue.

**Comment by felixfontein** [comment]
Using html5lib via lxml seems to be somewhat broken. The sample code there outputs for me:
```
b'<html:table xmlns:html="http://www.w3.org/1999/xhtml"><html:tbody><html:tr><html:td>foo</html:td></html:tr></html:tbody></html:table>'
```
This bug has already been reported two years ago (see here: https://bugs.launchpad.net/lxml/+bug/1191545), but apparently nothing changed.

Maybe using html5lib directly yields better results, but we should first do some extensive tests.

(Also, lxml + html5lib also inserts `</source>`, or more precisely `</html:source>`, since the serialization is done by lxml and not html5lib.)

**Comment by ralsina** [comment]
@felixfontein you can use the html5lib serializer with good results! See #1768

**Comment by ralsina** [comment]
No, we are not getting rid of LXML yet. Let's talk about this again next year, I guess.

**Comment by kata198** [comment]
Hey, I updated AdvancedHTMLParser fixing the instability issues. Sorry about that, the code had split into two divergent copies and I merged them into what was version 3, but apparently did it too quickly and without enough testing.

Latest version https://pypi.python.org/pypi/AdvancedHTMLParser/5.0.1 is able to accurately reconstruct any pages I've tested (github, JIRA, etc) by parsing then using getHTML to return the HTML. Version 3 was really for supporting XHTML, and didn't so much like SGML implicitly-closed elements (like meta tags). This has been fixed. Also utf-8/other encoding support.

Version 5.0.1 also supports auto formatting (getFormattedHTML on AdvancedHTMLParser class, and AdvancedHTMLFormatter class itself, as well as a script "formatHTML" which will do the same).

It's been well tested now with a lot of HTML documents, various scraping, 

Maybe you can give it another chance. Maybe it's still not what you're looking for, I don't really know the context I just found this thread while searching if anyone was using it.

**Comment by ralsina** [comment]
@kata198 cool, I'll give it another spin :-)
