### ISSUE TITLE
`check -l` can’t stomach REDIRECTIONS pages

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1776]
REDIRECTIONS = [ ( "test.html", "/index.html" ) ]

    WARNING: check: Broken link in output/test.html: 0; url=/index.html
    WARNING: check: Broken link in output/test.html: /index.html

**Comment by ralsina** [comment]
For the second warning, problem is this:

```
target = '/index.html'
```

We create the filename that we check for existence like this:

```
os.path.join(os.path.dirname(filename), target)
```

Since target is an absolute path, this returns ``/index.html`` instead of ``output/index.html``.

**Comment by ralsina** [comment]
For the 1st line ... looks like lxml has no idea how to parse that, workaround coming up.

**Comment by Aeyoun** [comment]
Still seeing both warnings.

**Comment by ralsina** [comment]
Hey, does output/index.html exist?

**Comment by Aeyoun** [comment]
It does indeed.

**Comment by ralsina** [comment]
Then I can't reproduce.

**Comment by Aeyoun** [comment]
I haven’t got time right now to verify this, but what about REDIRECTIONS = [ ( "folder1/test.html", "folder2/test.html" ) ]
@ralsina, you just removed the leading slash, right? so it’s looking for folder1/folder2/test.html and not  folder2/test.html relative to root.

**Comment by ralsina** [comment]
If you do a redirect from folder1/test.html to folder2/test.html it *will* point to folder1/folder2/test.html right?

**Comment by Aeyoun** [comment]
Yes, but the link pointed to /folder2/test.html before you `target.lstrip('/')` on line 241. I think that is what happens. So by lstripping you change it to /folder1/folder2/test.html

**Comment by ralsina** [comment]
But then the redirection would be ``[("folder1/test.html", "/folder2/test.html")], right?

**Comment by Aeyoun** [comment]
Right, which it was supposed to be. Typing out examples from memory on a mobile while on the go was probably a bad idea. Sorry about the added confusion from me not checking my typing whilst not contributing anything but complaints. ;)

**Comment by Aeyoun** [comment]
File "/usr/local/lib/python3.4/dist-packages/nikola/plugins/command/check.py", line 242
        else:  # Relative path
           ^
    SyntaxError: invalid syntax

**Comment by ralsina** [comment]
And I should not try to code without even running the code before pushing ;-)

**Comment by Aeyoun** [comment]
REDIRECTS = [ ("posts/review-the-martian.html", "/book-review/the-martian.html"), ]

Produced: [/posts/review-the-martian.html](https://www.aeyoun.com/posts/review-the-martian.html) which successfully redirects to [/book-review/the-martian.html](https://www.aeyoun.com/book-review/the-martian.html) (which also exists).

check -l still disagrees:

[2015-06-01T20:01:24Z] WARNING: check: Broken link in output/posts/review-the-martian.html: /book-review/the-martian.html
[2015-06-01T20:01:24Z] WARNING: check: Broken link in output/posts/review-the-martian.html: /book-review/the-martian.html

**Comment by ralsina** [comment]
Ok, so this will need actual work. Sorry for wasting time with halff-assed work :-(

**Comment by ralsina** [comment]
@Aeyoun I started a PR with a test case.

Basically, let's put there as many situations as we want to check, and it will run check against them:

https://github.com/getnikola/nikola/pull/1780

So if check doesn't work correctly, we should know.

**Comment by Aeyoun** [comment]
Work around! Kind of. Make the redirect links absolute URIs. As per RFC 2616, the Location header (our friend in the redirect meta header) must be an absolute URI. So we should be producing absolute URIs for redirects and not relative URIs.

**Comment by ralsina** [comment]
Absolute as in "https://foo.com/bar/baz.html"? That means not even "//foo.com/bar/baz.html"?

**Comment by Aeyoun** [comment]
Absolute includes protocol scheme, yes.

**Comment by ralsina** [comment]
On 01/06/15 17:42, Daniel Aleksandersen wrote:
>
> Absolute includes protocol scheme, yes.
>

That sucks SO much, I would rather not implement it :-(

**Comment by Kwpolska** [comment]
> As per RFC 2616, the Location header (our friend in the redirect meta header) must be an absolute URI.

It’s actually `Refresh`, which is:

* not part of the HTTP standard
* [deprecated in the eyes of the W3C for a11y reasons](http://www.w3.org/TR/WCAG10-HTML-TECHS/#meta-element)
* [uses a relative URL in the WHATWG HTML spec example](https://html.spec.whatwg.org/#attr-meta-http-equiv-refresh)
