### ISSUE TITLE
Multilanguage post

### ISSUE THREAD

**Issue by humitos** [getnikola/nikola#1786]
Hi,

When I have a multilanguage post (English and Spanish) it says:

* In the Spanish version:  `También disponible en: English` which is written in Spanish
* In the English version:  `Also available in: Español`

Don't you think it should be the other way around? If I'm an English speaker and I'm reading a Spanish post I would like to read in my nature language that there is another version in my mother tongue.

**Comment by immanetize** [comment]
On Jun 5, 2015 7:20 AM, "Manuel Kaufmann" <notifications@github.com> wrote:
>
> Hi,
>
> When I have a multilanguage post (English and Spanish) it says:
>
> In the Spanish version: También disponible en: English which is written
in Spanish
> In the English version: Also available in: Español
>
> Don't you think it should be the other way around? If I'm an English
speaker and I'm reading a Spanish post I would like to read in my nature
language that there is another version in my mother tongue.
>
> —
> Reply to this email directly or view it on GitHub.

If I were an English only speaker, or a Spanish only speaker, and I
encountered a post that was written in a language I did not know, I would
like to read the post in my native language and those strings would help me
do it.

--Pete

**Comment by ralsina** [comment]
If the post is translated to N languages, where N > 2, translating the whole phrase gets clunkier.

**Comment by Kwpolska** [comment]
We used to say “Read in English”/“Leer en español” before the v7 themes revamp.  The current version is IMO cleaner.  The word “Español” is a landmark, and if that is not enough, you can always edit your own templates (even adding a little flag there).
