### ISSUE TITLE
"English" / "Spanish" link from navbar

### ISSUE THREAD

**Issue by humitos** [getnikola/nikola#1787]
How NIkola determinate which is the URL for the link "English" / "Spanish" / etc from navbar when you have a multi language site?

In my site is pointing to `/en/blog/` and I want to change it to just `/en/`

http://argentinaenpython.com.ar/

I couldn't find it in the docs...

**Comment by ralsina** [comment]
It seems to be something like this:

```
<%def name="html_translations()">
    <ul class="translations">
    %for langname in translations.keys():
        %if langname != lang:
            <li><a href="${abs_link(_link("root", None, langname))}" rel="alternate" hreflang="${langname}">${messages("LANGUAGE", langname)}</a></li>
        %endif
    %endfor
    </ul>
</%def>
```

**Comment by ralsina** [comment]
The "root" path used in that template is calculated like this:

```
    def root_path(self, name, lang):
        """root_path path handler"""
        d = self.config['TRANSLATIONS'][lang]
        if d:
            return [d, '']
        else:
            return []
```

**Comment by Kwpolska** [comment]
Your theme is probably outdated and using the old `index` handler for this link, which was used in Nikola v7.3.0 and older.  On a demo site with Nikola v7.4.1 with Spanish added and `INDEX_PATH='blog'`, I get links pointing to `https://example.com/` and `https://example.com/es/`.

See #1008.
