### ISSUE TITLE
Small issue with new html-tidy filter defaults

### ISSUE THREAD

**Issue by randomhammer** [getnikola/nikola#1795]
Love the html-tidy filter! One issue: by default the option **drop-empty-elements** is set to **yes**. This has the effect of stripping things that look like this out of HTML:

```<i class="fa fa-bomb"></i>```

This should show a bomb from Font Awesome, but it is stripped out by html-tidy5. I added the option
 ```--drop-empty-elements no``` 
in filters.py and it fixed it right away. I believe that this should be the default going forward.

**Comment by Aeyoun** [comment]
Use an `<ins>` element for placeholders for insertions. Add a space to make the element non-empty.

**Comment by ralsina** [comment]
@Aeyoun that won't do. According to the bootstrap doc:

Only for use on empty elements
Icon classes should only be used on elements that contain no text content and have no child elements.

http://getbootstrap.com/components/

**Comment by randomhammer** [comment]
It's quite an easy fix to add the parameter to filters.py, and it seems to work just fine afterward. Alternate methods would be to create a tidy5 configuration file, or change the makefile to make keeping empty elements the default, but I found it much easier to just modify the last of defaults Nikola sends.

Date: Mon, 8 Jun 2015 05:53:16 -0700

**Comment by Kwpolska** [comment]
:+1: for adding configuration file support.

**Comment by ralsina** [comment]
Any suggestions on how this could look?

**Comment by Kwpolska** [comment]
We could add a `conf.py` setting to run `tidy5` with a desired config file, and if it’s set, just use that.

(also, adding `--drop-empty-elements no` by default is a good idea IMO)

**Comment by Aeyoun** [comment]
I was actually thinking of deprecating tidy5 in favor of html5lib (much better performance and serves the same purpose).

**Comment by felixfontein** [comment]
How about not adding a new config, but a new meta-filter like:
``` .py
def create_custom_html_tidy(options):
    return lambda infile: _html_tidy_runner(r'-quiet --show-info no --show-warnings no -utf8 ' + infile + r' -modify %1', options)
```
then one can write
```
FILTERS = {
    '.html': [filters.create_custom_html_tidy('-indent --indent-attributes no --sort-attributes alpha --wrap 0 --wrap-sections no --tidy-mark no --drop-empty-elements no')]
}
```

**Comment by Kwpolska** [comment]
Huge :-1:.

It's cleaner and nicer to use a config file instead of messing with command
line arguments. It also has the added bonus of being usable outside of
Nikola.

We value simplicity over ugly hacks.

-- 
Chris Warrick <https://chriswarrick.com>
