### ISSUE TITLE
Logging handlers are useless

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1797]
Only a few things request `self.site.loghandlers` explicitly, which is crucial for them to work (and we probably can’t do anything else). Moreover, it’s not really used.

(We might as well drop them, I wouldn’t be amazed if we found out nobody even touched the setting, buried on line 934 of the default config file)

Comments?

**Comment by Kwpolska** [comment]
Done on `logging` branch, which also includes using our own handlers for all old-style `logging` loggers.

**Comment by felixfontein** [comment]
Why not fixing all `get_logger` calls to use `self.site.loghandlers` instead? :)

**Comment by Kwpolska** [comment]
Because we can’t always get it, we have some out-of-site loggers.

Still: it’s probably not a popular feature, and I’d love a diet for Nikola.

**Comment by ralsina** [comment]
I agree about killing it. I would not even wait for v8, we can replace it with a noop+warning or something.

**Comment by Kwpolska** [comment]
We can’t easily tell if someone has actually configured their handlers; the only way would involve comparing `len()` ≠ 1 or individual elements.
