### ISSUE TITLE
Apple News Format (probably as a plugin)

### ISSUE THREAD

**Issue by da2x** [getnikola/nikola#1798]
Whenever it’s announced, I’ll add support to Nikola for Apple’s new [news format](https://developer.apple.com/news-publisher/).

**Comment by amunozf** [comment]
Do we really need Apple News, Google AMP and Facebook instant articles? Why not real HTML5 with inline CSS styles and Javascript? There should be only one and open web standard for everyone.

I don't think this should be a priority.

**Comment by Kwpolska** [comment]
This has the *Whenever* milestone. Many of our *Whenever* issues are just cool ideas someone might implement, or that might never happen.

This wouldn’t get into Nikola core either way.

**Comment by Kwpolska** [comment]
> google: "Apple News Format"
> About 10,100 results (0.49 seconds) 

Not very important. The AMP issue was killed, so this one goes down too.
