### ISSUE TITLE
Missing jinja2 strftime filter

### ISSUE THREAD

**Issue by randomhammer** [getnikola/nikola#1800]
Jinja2 has a built-in filter called ```strftime``` that acts like the internal Python function of the same name. It is not working in Nikola 7.5.0. I enter the following macro on my template:
```
{% macro inject_post_dateline() %}
	<p>Broken: {{ post.date|strftime("%m") }}</p>
{% endmacro %}
```
And I get the following stack trace:
```
Scanning posts......done!
.  render_pages:output/pages/about.html
########################################
TaskError - taskid:render_pages:output/pages/about.html
PythonAction Error
Traceback (most recent call last):
  File "/Users/chris/anaconda/lib/python2.7/site-packages/doit/action.py", line 372, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/Users/chris/anaconda/lib/python2.7/site-packages/nikola/nikola.py", line 950, in render_template
    template_name, None, local_context)
  File "/Users/chris/anaconda/lib/python2.7/site-packages/nikola/plugins/template/jinja.py", line 90, in render_template
    output = template.render(**context)
  File "/Users/chris/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/chris/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "themes/deuces/templates/post_helper.tmpl", line 13, in <module>
    <p>Broken: {{ post.date|strftime("%m") }}</p>
TemplateAssertionError: no filter named 'strftime'
```
Some other built-in filters are working fine. There is a dictionary in ```config.py``` for enabling custom template filters, but that does not apply here because this function is built in. Is there any way to make the build-in strftime template function work?

**Comment by ralsina** [comment]
A quick look at the jinja code doesn't show a strftime filter:

https://github.com/mitsuhiko/jinja2/blob/master/jinja2/filters.py

**Comment by randomhammer** [comment]
Fascinating...  It is in the documentation, and I used it in Pelican before I moved my blog to Nikola. Not sure why it's not here, but thanks for taking the time to help. I'll roll a custom filter and add it. 
Thanks again!

Date: Mon, 8 Jun 2015 14:49:43 -0700

**Comment by ralsina** [comment]
I don't see it in the jinja documentation either. Maybe it's added by Pelican?

**Comment by Kwpolska** [comment]
@ralsina so, do we add it here or leave it to the users?

**Comment by ralsina** [comment]
I think I'll add it globally so it works for both mako and jinja.
