### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-4: ord inal not in range(256)

### ISSUE THREAD

**Issue by xh84** [getnikola/nikola#1806]
i use win7 with python 2.7.9
when i installed nikola and use "nikola help" command, cmd.exe tells:

Traceback (most recent call last):
  File "D:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Python27\Scripts\nikola.exe\__main__.py", line 9, in <module>
  File "D:\Python27\lib\site-packages\nikola\__main__.py", line 158, in main
    site = Nikola(**config)
  File "D:\Python27\lib\site-packages\nikola\nikola.py", line 658, in __init__
    self.tzinfo = dateutil.tz.gettz(self.config['TIMEZONE'])
  File "D:\Python27\lib\site-packages\dateutil\tz.py", line 964, in gettz
    tz = tzwin(name)
  File "D:\Python27\lib\site-packages\dateutil\tzwin.py", line 92, in __init__
    self._stdname = keydict["Std"].encode("iso-8859-1")
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-4: ord
inal not in range(256)

**Comment by ralsina** [comment]
What is the value you set in TIMEZONE?

**Comment by xh84** [comment]
you mean the TIMEZONE of my operation system (win7)?

**Comment by ralsina** [comment]
In your conf.py

**Comment by xh84** [comment]
i does not set the conf.py
i just want to test that nikola is installed successfully
do i have to set the conf.py first?

**Comment by Kwpolska** [comment]
On Wed, Jun 10, 2015 at 6:21 PM, xh84 <notifications@github.com> wrote:

> i does not set the conf.py
> i just want to test that nikola is installed successfully
> do i have to set the conf.py first?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getnikola/nikola/issues/1806#issuecomment-110820674>.
>
That won’t help.

What timezone is Windows set to?  Please type out the exact name as
displayed in the Date/Time Settings, in your language, including
diacritical marks.

-- 
Chris Warrick <https://chriswarrick.com/>
PGP: 5EAAEA16

**Comment by xh84** [comment]
C:\Users\Administrator>tzutil /g
China Standard Time

**Comment by xh84** [comment]
UTC

**Comment by ralsina** [comment]
What happens if you type

```
python -c "import dateutil.tz; print dateutil.tz.gettz('UTC')"
```

**Comment by xh84** [comment]
File "<string>", line 1, in <module>
  File "D:\Python27\lib\site-packages\dateutil\tz.py", line 964, in gettz
    tz = tzwin(name)
  File "D:\Python27\lib\site-packages\dateutil\tzwin.py", line 92, in __init__
    self._stdname = keydict["Std"].encode("iso-8859-1")
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-4: ord
inal not in range(256)

**Comment by xh84** [comment]
File "<string>", line 1, in <module>
  File "D:\Python27\lib\site-packages\dateutil\tz.py", line 964, in gettz
    tz = tzwin(name)
  File "D:\Python27\lib\site-packages\dateutil\tzwin.py", line 92, in __init__
    self._stdname = keydict["Std"].encode("iso-8859-1")
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-4: ord
inal not in range(256)

**Comment by ralsina** [comment]
Ok, so that looks like a bug in dateutils. I'll file it and try to do a workaround so you can at least see "nikola help" working :-P

**Comment by xh84** [comment]
thank you!!!

**Comment by ralsina** [comment]
Reported here: https://github.com/dateutil/dateutil/issues/92

**Comment by ralsina** [comment]
@xh84 can you try nikola from master now? I added a workaround but can't test it because I can't reproduce it :-)

**Comment by xh84** [comment]
how to try nikola from master now?
just download nikola from github and put it under Python27\Lib\site-packages?

**Comment by punchagan** [comment]
Or just `pip install https://github.com/getnikola/nikola/archive/master.zip`

**Comment by xh84** [comment]
E:\python\nikola>pip install nikola-master.zip
Unpacking e:\python\nikola\nikola-master.zip
  Running setup.py (path:c:\users\admini~1\appdata\local\temp\pip-ytqysx-build\s
etup.py) egg_info for package from file:///E:/python/nikola/nikola-master.zip

  Requirement already satisfied (use --upgrade to upgrade): Nikola==7.5.0 from f
ile:///E:/python/nikola/nikola-master.zip in d:\python27\lib\site-packages
Cleaning up...

E:\python\nikola>nikola help
Traceback (most recent call last):
  File "D:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Python27\Scripts\nikola.exe\__main__.py", line 9, in <module>
  File "D:\Python27\lib\site-packages\nikola\__main__.py", line 158, in main
    site = Nikola(**config)
  File "D:\Python27\lib\site-packages\nikola\nikola.py", line 658, in __init__
    self.tzinfo = dateutil.tz.gettz(self.config['TIMEZONE'])
  File "D:\Python27\lib\site-packages\dateutil\tz.py", line 964, in gettz
    tz = tzwin(name)
  File "D:\Python27\lib\site-packages\dateutil\tzwin.py", line 92, in __init__
    self._stdname = keydict["Std"].encode("iso-8859-1")
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-4: ord
inal not in range(256)

**Comment by ralsina** [comment]
I don't get it. That code is not in that line aymore, that looks like the old version.

**Comment by xh84** [comment]
[C:\Users\Administrator]$ nikola version
[2015-06-11T10:30:49Z] WARNING: Nikola: Error getting TZ: 'latin-1' codec can't encode characters in position 0-4: ordinal not in range(256)
ERROR:yapsy:Unable to import plugin: D:\Python27\lib\site-packages\nikola\plugins\command\auto
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\yapsy\PluginManager.py", line 484, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,None,candidate_filepath,("py","r",imp.PKG_DIRECTORY))
  File "D:\Python27\lib\site-packages\nikola\plugins\command\auto\__init__.py", line 60, in <module>
    MASK = pyinotify.IN_DELETE | pyinotify.IN_CREATE | pyinotify.IN_MODIFY
AttributeError: 'NoneType' object has no attribute 'IN_DELETE'
Nikola v7.5.0

**Comment by ralsina** [comment]
``nikola auto`` doesn't work on windows (but I need to fix that error message), opened #1809

**Comment by ralsina** [comment]
@xh84 this is how nikola.py looks now where you get the latin-1 error:

https://github.com/getnikola/nikola/blob/master/nikola/nikola.py#L658

You could change it to be like that manually, but it does look like you are still using the old version somehow.

Try 

```
pip install https://github.com/getnikola/nikola/archive/master.zip --upgrade --force-reinstall
```

**Comment by xh84** [comment]
[C:\Users\Administrator]$ pip install https://github.com/getnikola/nikola/archive/master.zip --upgrade --force-reinstall
Downloading/unpacking https://github.com/getnikola/nikola/archive/master.zip
  Running setup.py (path:c:\users\admini~1\appdata\local\temp\pip-mc9a8n-build\setup.py) egg_info for package from https://github.com/getnikola/nikola/archive/master.zip
    
Downloading/unpacking doit==0.28.0 (from Nikola==7.5.0)
  Running setup.py (path:c:\users\admini~1\appdata\local\temp\pip_build_Administrator\doit\setup.py) egg_info for package doit
    
Downloading/unpacking Pygments>=1.6 (from Nikola==7.5.0)
Downloading/unpacking Pillow>=2.4.0 (from Nikola==7.5.0)
Downloading/unpacking python-dateutil==2.4.2 (from Nikola==7.5.0)
Downloading/unpacking docutils>=0.12 (from Nikola==7.5.0)
  Running setup.py (path:c:\users\admini~1\appdata\local\temp\pip_build_Administrator\docutils\setup.py) egg_info for package docutils
    
    warning: no files found matching 'MANIFEST'
    warning: no files found matching '*' under directory 'extras'
    warning: no previously-included files matching '.cvsignore' found under directory '*'
    warning: no previously-included files matching '*.pyc' found under directory '*'
    warning: no previously-included files matching '*~' found under directory '*'
    warning: no previously-included files matching '.DS_Store' found under directory '*'
Downloading/unpacking mako>=1.0.0 (from Nikola==7.5.0)
  Running setup.py (path:c:\users\admini~1\appdata\local\temp\pip_build_Administrator\mako\setup.py) egg_info for package mako
    
    warning: no files found matching '*.xml' under directory 'examples'
    warning: no files found matching '*.mako' under directory 'examples'
    warning: no files found matching 'ez_setup.py'
    no previously-included directories found matching 'doc\build\output'
Downloading/unpacking unidecode>=0.04.16 (from Nikola==7.5.0)
  Running setup.py (path:c:\users\admini~1\appdata\local\temp\pip_build_Administrator\unidecode\setup.py) egg_info for package unidecode
    D:\Python27\lib\site-packages\setuptools\dist.py:285: UserWarning: Normalizing '0.04.17' to '0.4.17'
      normalized_version,
    
Downloading/unpacking lxml>=3.3.5 (from Nikola==7.5.0)
Downloading/unpacking yapsy==1.10.423 (from Nikola==7.5.0)
  Running setup.py (path:c:\users\admini~1\appdata\local\temp\pip_build_Administrator\yapsy\setup.py) egg_info for package yapsy
    
    no previously-included directories found matching 'src2\package\doc\_build'
    no previously-included directories found matching 'src3\package\doc\_build'
Downloading/unpacking PyRSS2Gen>=1.1 (from Nikola==7.5.0)
  Downloading PyRSS2Gen-1.1.tar.gz
  Running setup.py (path:c:\users\admini~1\appdata\local\temp\pip_build_Administrator\PyRSS2Gen\setup.py) egg_info for package PyRSS2Gen
    
Downloading/unpacking logbook>=0.7.0 (from Nikola==7.5.0)
  Running setup.py (path:c:\users\admini~1\appdata\local\temp\pip_build_Administrator\logbook\setup.py) egg_info for package logbook
    
Downloading/unpacking blinker>=1.3 (from Nikola==7.5.0)
  Running setup.py (path:c:\users\admini~1\appdata\local\temp\pip_build_Administrator\blinker\setup.py) egg_info for package blinker
    
Downloading/unpacking setuptools>=5.4.1 (from Nikola==7.5.0)
Downloading/unpacking natsort>=3.5.2 (from Nikola==7.5.0)
  Downloading natsort-4.0.1-py2.py3-none-any.whl
Downloading/unpacking requests>=2.2.0 (from Nikola==7.5.0)
Downloading/unpacking six (from doit==0.28.0->Nikola==7.5.0)
  Downloading six-1.9.0-py2.py3-none-any.whl
Downloading/unpacking configparser (from doit==0.28.0->Nikola==7.5.0)
  Downloading configparser-3.3.0r2.tar.gz
  Running setup.py (path:c:\users\admini~1\appdata\local\temp\pip_build_Administrator\configparser\setup.py) egg_info for package configparser
    D:\Python27\lib\site-packages\setuptools\dist.py:285: UserWarning: Normalizing '3.3.0r2' to '3.3.0.post2'
      normalized_version,
    
Downloading/unpacking MarkupSafe>=0.9.2 (from mako>=1.0.0->Nikola==7.5.0)
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py (path:c:\users\admini~1\appdata\local\temp\pip_build_Administrator\MarkupSafe\setup.py) egg_info for package MarkupSafe
    
Installing collected packages: doit, Pygments, Pillow, python-dateutil, docutils, mako, unidecode, lxml, yapsy, PyRSS2Gen, logbook, blinker, setuptools, natsort, requests, Nikola, six, configparser, MarkupSafe
  Found existing installation: doit 0.28.0
    Uninstalling doit:
      Successfully uninstalled doit
  Running setup.py install for doit
    
    Installing doit-script.py script to D:\Python27\Scripts
    Installing doit.exe script to D:\Python27\Scripts
    Installing doit.exe.manifest script to D:\Python27\Scripts
  Found existing installation: Pygments 2.0.2
    Uninstalling Pygments:
      Successfully uninstalled Pygments
  Found existing installation: Pillow 2.8.2
    Uninstalling Pillow:
      Successfully uninstalled Pillow
  Found existing installation: python-dateutil 2.4.2
    Uninstalling python-dateutil:
      Successfully uninstalled python-dateutil
  Found existing installation: docutils 0.12
    Uninstalling docutils:
      Successfully uninstalled docutils
  Running setup.py install for docutils
    
    warning: no files found matching 'MANIFEST'
    warning: no files found matching '*' under directory 'extras'
    warning: no previously-included files matching '.cvsignore' found under directory '*'
    warning: no previously-included files matching '*.pyc' found under directory '*'
    warning: no previously-included files matching '*~' found under directory '*'
    warning: no previously-included files matching '.DS_Store' found under directory '*'
  Found existing installation: Mako 1.0.1
    Uninstalling Mako:
      Successfully uninstalled Mako
  Running setup.py install for mako
    
    warning: no files found matching '*.xml' under directory 'examples'
    warning: no files found matching '*.mako' under directory 'examples'
    warning: no files found matching 'ez_setup.py'
    no previously-included directories found matching 'doc\build\output'
    Installing mako-render-script.py script to D:\Python27\Scripts
    Installing mako-render.exe script to D:\Python27\Scripts
    Installing mako-render.exe.manifest script to D:\Python27\Scripts
  Found existing installation: Unidecode 0.04.17
    Uninstalling Unidecode:
      Successfully uninstalled Unidecode
  Running setup.py install for unidecode
    D:\Python27\lib\site-packages\setuptools\dist.py:285: UserWarning: Normalizing '0.04.17' to '0.4.17'
      normalized_version,
    
  Found existing installation: lxml 3.4.4
    Uninstalling lxml:
      Successfully uninstalled lxml
  Found existing installation: Yapsy 1.10.423
    Uninstalling Yapsy:
      Successfully uninstalled Yapsy
  Running setup.py install for yapsy
    
    no previously-included directories found matching 'src2\package\doc\_build'
    no previously-included directories found matching 'src3\package\doc\_build'
  Found existing installation: PyRSS2Gen 1.1
    Uninstalling PyRSS2Gen:
      Successfully uninstalled PyRSS2Gen
  Running setup.py install for PyRSS2Gen
    
  Found existing installation: Logbook 0.9.1
    Uninstalling Logbook:
      Successfully uninstalled Logbook
  Running setup.py install for logbook
    building 'logbook._speedups' extension
    ==========================================================================
    WARNING: The C extension could not be compiled, speedups are not enabled.
    Failure information, if any, is above.
    Retrying the build without the C extension now.
    
    
    ==========================================================================
    WARNING: The C extension could not be compiled, speedups are not enabled.
    Plain-Python installation succeeded.
    ==========================================================================
  Found existing installation: blinker 1.3
    Uninstalling blinker:
      Successfully uninstalled blinker
  Running setup.py install for blinker
    
  Found existing installation: setuptools 17.1.1
    Uninstalling setuptools:
      Successfully uninstalled setuptools
  Found existing installation: natsort 4.0.1
    Uninstalling natsort:
      Successfully uninstalled natsort
  Found existing installation: requests 2.7.0
    Uninstalling requests:
      Successfully uninstalled requests
  Found existing installation: Nikola 7.5.0
    Uninstalling Nikola:
      Successfully uninstalled Nikola
  Running setup.py install for Nikola
    WARNING: your working copy is now dirty by changes in samplesite, sphinx and themes
    
    Installing nikola-script.py script to D:\Python27\Scripts
    Installing nikola.exe script to D:\Python27\Scripts
    Installing nikola.exe.manifest script to D:\Python27\Scripts
  Found existing installation: six 1.9.0
    Uninstalling six:
      Successfully uninstalled six
  Found existing installation: configparser 3.3.0r2
    Uninstalling configparser:
      Successfully uninstalled configparser
  Running setup.py install for configparser
    deleting configparser.egg-info\requires.txt
    D:\Python27\lib\site-packages\setuptools\dist.py:285: UserWarning: Normalizing '3.3.0r2' to '3.3.0.post2'
      normalized_version,
    
  Found existing installation: MarkupSafe 0.23
    Uninstalling MarkupSafe:
      Successfully uninstalled MarkupSafe
  Running setup.py install for MarkupSafe
    
    building 'markupsafe._speedups' extension
    ==========================================================================
    WARNING: The C extension could not be compiled, speedups are not enabled.
    Failure information, if any, is above.
    Retrying the build without the C extension now.
    
    
    ==========================================================================
    WARNING: The C extension could not be compiled, speedups are not enabled.
    Plain-Python installation succeeded.
    ==========================================================================
Successfully installed doit Pygments Pillow python-dateutil docutils mako unidecode lxml yapsy PyRSS2Gen logbook blinker setuptools natsort requests Nikola six configparser MarkupSafe
Cleaning up...

[C:\Users\Administrator]$ nikola version
[2015-06-11T10:55:10Z] WARNING: Nikola: Error getting TZ: 'latin-1' codec can't encode characters in position 0-4: ordinal not in range(256)
ERROR:yapsy:Unable to import plugin: D:\Python27\lib\site-packages\nikola\plugins\command\auto
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\yapsy\PluginManager.py", line 484, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,None,candidate_filepath,("py","r",imp.PKG_DIRECTORY))
  File "D:\Python27\lib\site-packages\nikola\plugins\command\auto\__init__.py", line 60, in <module>
    MASK = pyinotify.IN_DELETE | pyinotify.IN_CREATE | pyinotify.IN_MODIFY
AttributeError: 'NoneType' object has no attribute 'IN_DELETE'
Nikola v7.5.0

**Comment by xh84** [comment]
do i use the newest nikola?

![Uploading 222.png…]()

**Comment by xh84** [comment]
![222](https://cloud.githubusercontent.com/assets/12828733/8105561/dd66119c-106c-11e5-91f4-67f5826def05.png)

**Comment by ralsina** [comment]
Ok, yes, that's the latest. Still have that error on ``nikola help``?

**Comment by xh84** [comment]
yes, cmd.exe first show errors but then can show the result of the command


[C:\Users\Administrator]$ nikola help
[2015-06-11T12:37:21Z] WARNING: Nikola: Error getting TZ: 'latin-1' codec can't encode characters in position 0-4: ordinal not in range(256)
ERROR:yapsy:Unable to import plugin: D:\Python27\lib\site-packages\nikola\plugins\command\auto
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\yapsy\PluginManager.py", line 484, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,None,candidate_filepath,("py","r",imp.PKG_DIRECTORY))
  File "D:\Python27\lib\site-packages\nikola\plugins\command\auto\__init__.py", line 60, in <module>
    MASK = pyinotify.IN_DELETE | pyinotify.IN_CREATE | pyinotify.IN_MODIFY
AttributeError: 'NoneType' object has no attribute 'IN_DELETE'
Nikola is a tool to create static websites and blogs. For full documentation and more information, please visit https://getnikola.com/


Available commands:
  nikola bootswatch_theme     given a swatch name from bootswatch.com and a parent theme, creates a custom theme
  nikola build                run tasks
  nikola check                check links and files in the generated site
  nikola clean                clean action / remove targets
  nikola console              start an interactive Python console with access to your site
  nikola deploy               deploy the site
  nikola doit_auto            automatically execute tasks when a dependency changes
.........

**Comment by ralsina** [comment]
Ok, so the workaround for this issue worked (you will still get an error until dateutil fixes their problem). The other error is that the ``auto`` command is failing to load, but it would not work for you anyway. I have a separate issue for it.

Thanks for the report, and I hope Nikola works for you and you like it!

**Comment by xh84** [comment]
thank you for your reply!!!

**Comment by twz915** [comment]
fuck !!!, I've tested for 30 minutes and see the answer here. 
on windows 7, when I upgrade my `dateutils` the problem was solved.
