### ISSUE TITLE
`nikola auto` does not track default themes

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1821]

**Comment by ralsina** [comment]
We would have to watch the whole theme chain, not too complicated.

It also doesn't watch ``templates/`` in the site's directory.

**Comment by Kwpolska** [comment]
> It also doesn't watch `templates/` in the site's directory.

[The source code claims otherwise.](https://github.com/getnikola/nikola/blob/watchdog/nikola/plugins/command/auto/__init__.py#L146)

**Comment by Kwpolska** [comment]
Fixed on `watchdog` branch.
