### ISSUE TITLE
nikola help auto, UnicodeEncodeError

### ISSUE THREAD

**Issue by shmilee** [getnikola/nikola#1826]
Archlinux, python 3.4.3, python-six 1.9.0,  python-doit 0.28.0, python-unidecode 0.04.17, nikola 7.5.1

When running `nikola help auto`, I  get an error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/doit/doit_cmd.py", line 165, in run
    return command.parse_execute(args)
  File "/usr/lib/python3.4/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/usr/lib/python3.4/site-packages/doit/cmd_help.py", line 155, in execute
    six.print_(cmd.help())
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 269: ordinal not in range(128)
```

**Comment by ralsina** [comment]
That's unusual. I can't reproduce that myself yet.

**Comment by Kwpolska** [comment]
You probably need to [configure your locale](https://wiki.archlinux.org/index.php/Locale) properly: make sure you use an `.utf8` locale.

What does `python -c "import sys; print(sys.getdefaultencoding(), sys.getfilesystemencoding())"` say?

**Comment by shmilee** [comment]
Thanks. Problem solved.

I run the command `nikola help auto` in a docker container, and the locale is forgotten to configure.

And,
```
$ python -c "import sys; print(sys.getdefaultencoding(), sys.getfilesystemencoding())"
utf-8 ascii
```

**Comment by Kwpolska** [comment]
Your locale might still be misconfigured then, they should both say utf-8.  Make sure `locale` outputs sane UTF-8 values for everything (other than `LC_ALL` which cannot be set)

**Comment by sukiletxe** [comment]
The same thing happens here, in a Windows 10 machine, both in cmd and Powershell. It complains whenever an en-dash (u2013) is used, refusing to print any help. This happens in at least auto and serve.
After running the command suggested above, I get:
utf-8 mbcs

**Comment by Kwpolska** [comment]
Full traceback?

**Comment by sukiletxe** [comment]
Oops, so sorry, I was going to add that when you replied. With nikola auto:
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\doit\doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "c:\python35\lib\site-packages\doit\cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "c:\python35\lib\site-packages\doit\cmd_help.py", line 157, in execute
    six.print_(cmd.help())
  File "c:\python35\lib\encodings\cp850.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2013' in position 274: character maps to <undefined>

**Comment by Kwpolska** [comment]
So basically, en-dashes we use somewhere trip up Windows, which does **not** speak Unicode and blatantly lies about locales. Fixed in master.

**Comment by sukiletxe** [comment]
Thank you very much!
