### ISSUE TITLE
Man page improvement

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1827]
The current man page is the barely necessary to say "we have a man page".

It could be improved by showing the help of each subcommand. Maybe a ``--help --long`` that expands each one?

**Comment by ralsina** [comment]
@schettino72 maybe this would be good for doit, too, want me to try doing a PR there?

**Comment by schettino72** [comment]
The debian package provides a man page for `doit`. I actually dont care at all about man pages for doit. No user ever complained about that. And I guess it would just be an extra hassle to deal with it in setuptools. 

Said that, I would be ok to add a man page as long as its creation is completely automated.

Thanks!

**Comment by Kwpolska** [comment]
IMO automated man pages are not a good idea. A man page that shows the help of each subcommand is going to help no-one.  I would personally have a human-written man page that is a short introduction to Nikola, along with descriptions of commands.  We could start by taking the handbook and editing it down.

**Comment by ralsina** [comment]
I have no intention to ever learn how to write man pages. So it's either going to be something using rst2man or help2man.

We have at least one user for whom running nikola itself is too slow to use the help command :-P

```
<polyzen> :p nikola help bootswatch_theme  22.98s user 0.88s system 90% cpu 26.281 total
```

But I agree that's totally a corner case.

**Comment by schettino72** [comment]
`bootswatch_theme` is a command or a task? Yes, 20 seconds is not acceptable. Why it takes that long? This should be fixed...

**Comment by ralsina** [comment]
It's a command. It only takes that long for him because he's trying to run this in a Rpi, where disk access uses CPU :-P

**Comment by schettino72** [comment]
OK. I see #1825. I will comment there :)
