### ISSUE TITLE
Index view: the second index page always get the smallest number of posts

### ISSUE THREAD

**Issue by xuhdev** [getnikola/nikola#1829]
The index page lists posts (by default 10 per page), from the latest post to the earliest one. The last page should have the smallest number of posts. However, I found that the second page always has the smallest number of posts.

e.g. we have 21 posts and 10 posts per index page. We should have 10 and 10 in the first and second page, then the earliest one in the last page. But nikola puts 10, 1, 10 in the 1st, 2nd and 3rd page.

[This is an example](https://www.dropbox.com/s/y7i2xo6sz70r10s/nikola-index-2-only-1-post.tar.bz2?dl=0) which can reproduce the bug. It uses the demo website, and add 20 more posts to it.

Another example is [this webpage](https://www.topbug.net/index-3.html) on my blog, which should have 10 posts displayed.

**Comment by felixfontein** [comment]
It's not a bug, but a feature. It makes sure that most of the index pages never change (only the first and second page). You can disable this and get the behaviour you want by setting
```
INDEXES_STATIC = False
```
This will make sure all pages have the maximum number of posts (except the last one), but will also rebuild all index pages everytime you add a new post at the beginning.

**Comment by ralsina** [comment]
And the reason for having the index pages not change is that the usual behaviour (newest page is index, second newest is index-1, etc) means all links to indexes get stale after a few posts.

**Comment by Aeyoun** [comment]
This is kind of hard to understand and should probably be better communicated through docs.

**Comment by Kwpolska** [comment]
Let’s make this a documentation issue and handle it soonish.
