### ISSUE TITLE
Checking links after checking files during deploy output errors about drafts

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1831]
nikola deploy
    Scanning posts...........done!
    INFO: deploy: ==> nikola check -f
    Scanning posts...........done!
    WARNING: check: Files not generated:
    WARNING: check: output/posts/draft.html
    WARNING: check: output/posts/draft2.html
    INFO: deploy: ==> nikola check -l
    Scanning posts...........done!
    ERROR: check: Error with: output/posts/draft.html [Errno 2] No such file or directory: 'output/posts/draft.html'
    ERROR: check: Error with: output/posts/draft2.html [Errno 2] No such file or directory: 'output/posts/draft2.html'

**Comment by Kwpolska** [comment]
These two commands run independently.  A better way to phrase this would be “`nikola check -l` tries to check files that don’t exist”.

I guess I’ll fix it.
