### ISSUE TITLE
Auto should `except KeyboardInterrupt` for shutting down server

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1832]
Like [serve does](https://github.com/getnikola/nikola/blob/master/nikola/plugins/command/serve.py#L120-L124) and auto used to do.

**Comment by Kwpolska** [comment]
https://github.com/getnikola/nikola/blob/master/nikola/plugins/command/auto/__init__.py#L213

**Comment by ralsina** [comment]
It does. But it locks. So it does, and then kills itself hard :-)

So, what's the bug?

**Comment by Kwpolska** [comment]
Also, it looks like it can exit cleanly now, probably thanks to Watchdog.  I’m removing the hack and adding `observer.stop(); observer.join()` just in case.

**Comment by ralsina** [comment]
@Kwpolska ok then :-)

**Comment by Kwpolska** [comment]
Yeah, can’t reproduce the ^C issue (#1811) anymore, tried 5 times.

**Comment by Aeyoun** [comment]
The issues I’m seeing are with Python 3 where auto doensn’t really  work anyways, issue #1830.

**Comment by ralsina** [comment]
Yes, auto in python3 is a mess.
