### ISSUE TITLE
Archive listing pages rebuilt on every build

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1833]
d@Yogapants:~/blog$ nikola build
    Scanning posts...........done!
    .  render_archive:output/2015/index.html
    .  render_archive:output/2013/index.html
    .  render_archive:output/2014/index.html
    .  render_archive:output/archive.html
    d@Yogapants:~/blog$ nikola build
    Scanning posts...........done!
    .  render_archive:output/2014/index.html
    .  render_archive:output/2013/index.html
    .  render_archive:output/2015/index.html
    .  render_archive:output/archive.html

**Comment by ralsina** [comment]
Is this master? Is this 7.5.1? Is this your own site? Any hints on how to reproduce?

**Comment by Kwpolska** [comment]
Can you reproduce with a demo site?  A demo site with your posts added?

**Comment by Aeyoun** [comment]
(Sorry crappy bugs, short on time and just wanted to get it down before I forgot.)

This is Python 3, today’s master, on my own site, started happening this week. Archive pages use default settings. Can’t reproduce on the demo site.

**Comment by Kwpolska** [comment]
Would you mind `git bisect`ing yourself?

**Comment by Aeyoun** [comment]
Stupid. F*ing. Bug.

Fix coming up.

**Comment by felixfontein** [comment]
Hmm, do you have any idea where this bug comes from? I mean, the lines you changed have been there for a long time (more than half a year), and 30 lines down is essentially the same thing (with months) which is still the same as before.

My first guess would be that this is somewhat triggered by changing `kw` in the loop. By fixing the loop order, you would just fix the symptom, but not the cause. What precisely are your settings for your blog? What are the values of `ARCHIVES_ARE_INDEXES`, `CREATE_MONTHLY_ARCHIVE` and `CREATE_FULL_ARCHIVES`?

In case `not CREATE_MONTHLY_ARCHIVE and CREATE_FULL_ARCHIVES` is `False` or `ARCHIVES_ARE_INDEXES` is `False`, a task is created whose `uptodate` depends on `kw` directly and not on a copy of `kw`. This *could* cause the problem. (If in line 75, we would use `copy(kw)` instead of `kw`, that should be fixed.)

**Comment by ralsina** [comment]
I expect if you have monthly archives this same bug may pop up for monthly pages, too.

**Comment by Aeyoun** [comment]
(See notes on IRC logs from now.)

**Comment by Aeyoun** [comment]
Settings are,

    ARCHIVE_PATH = ""
    ARCHIVE_FILENAME = "archive.html"
    ARCHIVES_ARE_INDEXES = False

Only happens in Python 3. No idea why it started happening only now.

**Comment by felixfontein** [comment]
@ralsina: I looked again, if this is the cause it might not appear for months because there, `kw` is not changed.

**Comment by felixfontein** [comment]
@Aeyoun: could you undo your change temporarily and change line 75 by using a copy of `kw` instead of `kw` directly, and check if the bug still appears?

**Comment by felixfontein** [comment]
It's not very surprising that this happens with Python 3 only and not with Python 2: if you run
```
a = { "2013": 1, "2014": 2, "2015": 3 }
for i, _ in a.items(): print(i)
```
in Python 2, I always get the same order, while in Python 3, the order changes.

**Comment by Aeyoun** [comment]
@felixfontein, reverting my changes and making a copy at line 75 change the problem a bit:

    d@Yogapants:~/blog$ nikola build
    Scanning posts...........done!
    .  render_archive:output/2015/index.html
    .  render_archive:output/2013/index.html
    .  render_archive:output/2014/index.html
    .  render_archive:output/archive.html
    d@Yogapants:~/blog$ nikola build
    Scanning posts...........done!
    d@Yogapants:~/blog$ nikola build
    Scanning posts...........done!
    d@Yogapants:~/blog$ nikola build
    Scanning posts...........done!
    .  render_archive:output/2014/index.html
    .  render_archive:output/2013/index.html
    .  render_archive:output/2015/index.html
   .  render_archive:output/archive.html
    d@Yogapants:~/blog$ nikola build
    Scanning posts...........done!
    d@Yogapants:~/blog$ nikola build
    Scanning posts...........done!
    .  render_archive:output/archive.html
    d@Yogapants:~/blog$ nikola build
    Scanning posts...........done!
    d@Yogapants:~/blog$ nikola build
    Scanning posts...........done!
   .  render_archive:output/archive.html
    d@Yogapants:~/blog$ nikola build
    Scanning posts...........done!

**Comment by felixfontein** [comment]
I can reproduce the bug by taking the demo site, and replicating the one post three times, in years 2013, 2014, 2015. (And of course, undoing your fix :) )

**Comment by felixfontein** [comment]
I also get the problem you have now. Let me debug it a bit...

**Comment by felixfontein** [comment]
Ok, got it. The problem is that `kw["is_feed_stale"]` isn't changed for the main page (line 210 in `archive.py`), so it takes the value it had last. Which was randomly assigned (because the loop order is random) in the yearly loop.

I'll fix it.
