### ISSUE TITLE
Use PRETTY_URLS by default

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1838]
Operation plan:
- [x] ~~v7.5.2~~v7.6.0: Add question to wizard, defaulting to yes
- [x] v8.0.0: default to PRETTY_URLS also in `-q` sites and probably in imports

Comments?

**Comment by ralsina** [comment]
+1

**Comment by Aeyoun** [comment]
-1

Requires server work and not everyone is able to change it depending on their hosting and knowledge. Raises the barrier to entry.

**Comment by duck** [comment]
I am good with adding the option, but as @Aeyoun pointed out, having it as default would make things harder.

My US$0.02....

**Comment by Kwpolska** [comment]
@Aeyoun I’m not sure you understand how `PRETTY_URLS` work.  Exactly **zero** web server configuration is required.  With `PRETTY_URLS` on, Nikola creates a `slug` directory and writes to `slug/index.html` instead of just using `slug.html`. See [input](https://github.com/Kwpolska/kwpolska.github.io/tree/master/contact) vs [output](https://kwpolska.github.io/contact/), and you can’t have rewrites on GitHub Pages.

@duck The option already *exists*, see above for an explanation.

**Comment by felixfontein** [comment]
@Aeyoun: which web servers are problematic here?

The only instance I know of is Amazon S3, where you explicitly have to tell it to use `index.html` instead of returning a directory listing (see http://docs.aws.amazon.com/AmazonS3/latest/dev/IndexDocumentSupport.html). But then, that already is true for the root of the page, so it's something which has to be enabled anyway to make the page work as expected, even without `PRETTY_URLS = True`.

If there's no good example of a standard webserver having problems with `index.html`, I'm for setting `PRETTY_URLS = True` as default.

**Comment by ralsina** [comment]
If the web server doesn't use index.html for directory indexes, Nikola will not work anyway since it uses that by default.

Unless of course the server uses something else, in which case, you'd tweak INDEX_FILE

**Comment by felixfontein** [comment]
If that's the case, you'll notice quite directly when you try to access your site at `http://your-domain/blog/` the first time. So in this case, you'll have to modify `INDEX_FILE` anyway, and after that `PRETTY_URLS` will also work.

**Comment by xuhdev** [comment]
I'm also against this decision as on a shared webhosting service you may not able to change the relevant web server options.

**Comment by Kwpolska** [comment]
How hard is it to read?

# YOU DO NOT HAVE TO CHANGE ANY WEB SERVER CONFIG AT ALL TO USE THIS OPTION

**Comment by xuhdev** [comment]
While it is the default for most servers, but a web server can also make index.html nondefault. See [this Apache option](http://httpd.apache.org/docs/2.4/mod/mod_dir.html#directoryindex), it's not impossible, and it's not strange someone may put a `disabled` there. e.g. a university web space may want staff to use dir browsing feature, thus the pretty url won't work there.

If you insist, At least a warning message is helpful.

**Comment by Kwpolska** [comment]
Then how do you get your index at `index.html` to work? Makes web sites much harder.

And we do **ask** about it in the init wizard, which every casual user should run to get a new site.

**Comment by xuhdev** [comment]
Alright, I see that people configure dir view only when `index.html` does not exist in the directory. I think it makes sense. Sorry for the noise.
