### ISSUE TITLE
Get rid of sys.exit() calls

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1839]
We should return error codes from functions and use `sys.exit()` preferably only in `__main__.py`.

**Comment by felixfontein** [comment]
Why not raise (a specific kind of) exceptions?

**Comment by ffdybuster** [comment]
What about all the `sys.exit()` calls which are left, like in `nikola.Nikola.__init__()` or in the task plugins?

**Comment by felixfontein** [comment]
What about all the `sys.exit()` calls which are left, like in `nikola.Nikola.__init__()` or in the task plugins?

**Comment by Kwpolska** [comment]
These are hard to get rid of without some restructuring.
