### ISSUE TITLE
UnicodeDecodeError in sitemap plugin (again)

### ISSUE THREAD

**Issue by CarstenGrohmann** [getnikola/nikola#1842]
Hi Nikola Developers,

The sitemap pluging raises a UnicodeDecodeError sometimes if it reads old HTML files.

The triggered traceback:
```python
########################################
TaskError - taskid:_scan_locs:sitemap
PythonAction Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/doit/action.py", line 372, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/usr/lib/python2.7/site-packages/nikola/plugins/task/sitemap/__init__.py", line 249, in scan_locs_task
    scan_locs()
  File "/usr/lib/python2.7/site-packages/nikola/plugins/task/sitemap/__init__.py", line 167, in scan_locs
    filehead = io.open(real_path, 'r', encoding='utf8').read(1024)
  File "/usr/lib/python2.7/codecs.py", line 302, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 877: invalid start byte
```

Initially this bug has been fixed in #1308, but it occurred again. Unfortunately I neither can't remove nor recreate this ancient files.

May you can extend the try/except statement introduced in dbf417fadd3f7be328d611c0df83a959fd2daade to include the `io.open()` statement.

Regards,
Carsten

**Comment by Kwpolska** [comment]
Can’t you convert your files to UTF-8 and change their `<meta>` fields?

Sheesh, I’ll fix it (I guess we can just work on bytes here).  But please remember it’s 2015 and you should switch everything in your life to UTF-8.
