### ISSUE TITLE
Promote Coil CMS for Nikola users

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1843]
- [x] set up demo site (@ralsina and his VPS)
- [x] blog post (@Kwpolska)
- [x] link ~~in handbook?~~on features page (redesign 2015)

**Comment by ralsina** [comment]
I just spent 90 minutes trying to make coil work in limited mode with uwsgi+rq+redis with no luck whatsoever.

I have redis and rq running, I have everything installed but uwsgi does nothing, and  nothing works.
I give up.

@Kwpolska I think you have an account on the VPS, you can use it to get it started. If you prefer not to do that, I will happily pay for a separate droplet we can use for this.

**Comment by Kwpolska** [comment]
I could try, but I would need an account with root access on that VPS (the getnikola user doesn’t, and/or I don’t know the password).

uWSGI should not be that hard to set up; you just need to get the configuration right (the example in coil docs should work, sometimes with small modifications.  uWSGI is supposed to run as a daemon in its custom protocol, and nginx has to connect to that port/socket and talk to it.

In case I fail on that machine, I can always just set it up on my own VPS (DigitalOcean $5, Fedora 22, LON1), which runs [two](https://users.getnikola.com/) uwsgi+nginx [apps](https://go.chriswarrick.com/) already.  If you would prefer to have complete control and less money, I could also work on the separate droplet of yours… (should run ubuntu 15.04 or fedora 22 with systemd if that’s the case). You could also get access to the files of that Coil CMS instance through an account on my droplet.

In any case: /msg me on IRC (or e-mail me) with the password to an account on your VPS, that is in sudoers.
