### ISSUE TITLE
pip install nikola misses some dependencies

### ISSUE THREAD

**Issue by cbrown1** [getnikola/nikola#1851]
I am on Scientific Linux 7 (a RHEL derivative). I do `sudo pip install nikola` and it installs OK. But if I try to initialize a project, I get errors indicating that required python packages are not found. I manually installed the following packages via pip:

> yapsy
> configParser
> requests
> mako

And then nikola worked fine. Just wanted to report this.

**Comment by Kwpolska** [comment]
This should not happen, we always list them out… Could you please:

* remove the listed 4 packages and Nikola the same way you installed them
* try installing Nikola again and post the install log?

**Comment by ralsina** [comment]
I don't know how that happened to you, but I can't reproduce it here at all:

```
ralsina@yoga:/tmp$ mkvirtualenv -q test
(test)ralsina@yoga:/tmp$ pip install nikola
Downloading/unpacking nikola
  Downloading Nikola-7.5.1-py2.py3-none-any.whl (2.6MB): 2.3MB downloaded
Cleaning up...
Operation cancelled by user
Storing debug log for failure in /home/ralsina/.pip/pip.log
(test)ralsina@yoga:/tmp$ pip -q install nikola
(test)ralsina@yoga:/tmp$ pip freeze
Logbook==0.9.1
Mako==1.0.1
MarkupSafe==0.23
Nikola==7.5.1
Pillow==2.8.2
PyRSS2Gen==1.1
Pygments==2.0.2
Unidecode==0.4.18
Yapsy==1.10.423
argparse==1.2.1
blinker==1.3
configparser==3.3.0.post2
docutils==0.12
doit==0.28.0
lxml==3.4.4
natsort==4.0.3
pyinotify==0.9.6
python-dateutil==2.4.2
requests==2.7.0
six==1.9.0
wsgiref==0.1.2
(test)ralsina@yoga:/tmp$ nikola init -q foo
[2015-07-01T17:06:08Z] WARNING: Nikola: In order to USE_BUNDLES, you must install the "webassets" Python package.
[2015-07-01T17:06:08Z] WARNING: bundles: Setting USE_BUNDLES to False.
[2015-07-01T17:06:08Z] INFO: init: Created empty site at foo.
```

There you can see that on a clean virtualenv installing nikola via pip does setup all the dependencies you mentioned.

I also tried it on python 3 with the same results:

```
(test3)ralsina@yoga:/tmp$ pip -q install nikola
(test3)ralsina@yoga:/tmp$ pip freeze
Logbook==0.9.1
Mako==1.0.1
MarkupSafe==0.23
Nikola==7.5.1
Pillow==2.8.2
PyRSS2Gen==1.1
Pygments==2.0.2
Unidecode==0.4.18
Yapsy==1.10.423
blinker==1.3
docutils==0.12
doit==0.28.0
lxml==3.4.4
natsort==4.0.3
pyinotify==0.9.6
python-dateutil==2.4.2
requests==2.7.0
six==1.9.0
(test3)ralsina@yoga:/tmp$ nikola init -q foo3
[2015-07-01T17:10:27Z] WARNING: Nikola: In order to USE_BUNDLES, you must install the "webassets" Python package.
[2015-07-01T17:10:27Z] WARNING: bundles: Setting USE_BUNDLES to False.
[2015-07-01T17:10:27Z] INFO: init: Created empty site at foo3.
```

**Comment by Kwpolska** [comment]
PS. `sudo pip install` can be harmful and may lead to system breakage (especially on Python-heavy distros such as RHEL/Fedora/derivatives) — please use virtualenvs instead.

**Comment by cbrown1** [comment]
I now see that on installing nikola, there is an error (I didn't catch it previously). It turns out that this is because I didn't have the libxml2-devel and libxslt-devel packages installed. I installed those two packages via yum, and now nikola and the other mentioned packages install without error. 

I am pasting the requested logs (with the error) here for completeness. 

[code-breaker@workstation1 Projects]$ sudo pip install nikola
Downloading/unpacking nikola
  Downloading Nikola-7.5.1-py2.py3-none-any.whl (2.6MB): 2.6MB downloaded
Requirement already satisfied (use --upgrade to upgrade): docutils>=0.12 in /usr/lib/python2.7/site-packages (from nikola)
Requirement already satisfied (use --upgrade to upgrade): PyRSS2Gen>=1.1 in /usr/lib/python2.7/site-packages (from nikola)
Requirement already satisfied (use --upgrade to upgrade): doit==0.28.0 in /usr/lib/python2.7/site-packages (from nikola)
Requirement already satisfied (use --upgrade to upgrade): natsort>=3.5.2 in /usr/lib/python2.7/site-packages (from nikola)
Requirement already satisfied (use --upgrade to upgrade): blinker>=1.3 in /usr/lib/python2.7/site-packages (from nikola)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil==2.4.2 in /usr/lib/python2.7/site-packages (from nikola)
Requirement already satisfied (use --upgrade to upgrade): unidecode>=0.04.16 in /usr/lib/python2.7/site-packages (from nikola)
Requirement already satisfied (use --upgrade to upgrade): logbook>=0.7.0 in /usr/lib64/python2.7/site-packages (from nikola)
Downloading/unpacking lxml>=3.3.5 (from nikola)
  Downloading lxml-3.4.4.tar.gz (3.5MB): 3.5MB downloaded
  Running setup.py (path:/tmp/pip-build-bcyHK2/lxml/setup.py) egg_info for package lxml
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Building lxml version 3.4.4.
    Building without Cython.
    ERROR: /bin/sh: xslt-config: command not found
    
    ** make sure the development packages of libxml2 and libxslt are installed **
    
    Using build configuration of libxslt
    
    warning: no previously-included files found matching '*.py'
Downloading/unpacking yapsy==1.10.423 (from nikola)
  Downloading Yapsy-1.10.423.tar.gz (152kB): 152kB downloaded
  Running setup.py (path:/tmp/pip-build-bcyHK2/yapsy/setup.py) egg_info for package yapsy
    
    no previously-included directories found matching 'src2/package/doc/_build'
    no previously-included directories found matching 'src3/package/doc/_build'
Downloading/unpacking mako>=1.0.0 (from nikola)
  Downloading Mako-1.0.1.tar.gz (473kB): 473kB downloaded
  Running setup.py (path:/tmp/pip-build-bcyHK2/mako/setup.py) egg_info for package mako
    
    warning: no files found matching '*.xml' under directory 'examples'
    warning: no files found matching '*.mako' under directory 'examples'
    warning: no files found matching 'ez_setup.py'
    no previously-included directories found matching 'doc/build/output'
Downloading/unpacking requests>=2.2.0 (from nikola)
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB): 470kB downloaded
Downloading/unpacking setuptools>=5.4.1 (from nikola)
  Downloading setuptools-18.0.1-py2.py3-none-any.whl (461kB): 461kB downloaded
Requirement already satisfied (use --upgrade to upgrade): Pygments>=1.6 in /usr/lib/python2.7/site-packages (from nikola)
Requirement already satisfied (use --upgrade to upgrade): Pillow>=2.4.0 in /usr/lib64/python2.7/site-packages (from nikola)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/site-packages (from doit==0.28.0->nikola)
Requirement already satisfied (use --upgrade to upgrade): pyinotify in /usr/lib/python2.7/site-packages (from doit==0.28.0->nikola)
Downloading/unpacking configparser (from doit==0.28.0->nikola)
  Downloading configparser-3.3.0r2.tar.gz
  Running setup.py (path:/tmp/pip-build-bcyHK2/configparser/setup.py) egg_info for package configparser
    
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe>=0.9.2 in /usr/lib64/python2.7/site-packages (from mako>=1.0.0->nikola)
Installing collected packages: nikola, lxml, yapsy, mako, requests, setuptools, configparser
  Found existing installation: lxml 3.2.1
    Uninstalling lxml:
      Successfully uninstalled lxml
  Running setup.py install for lxml
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Building lxml version 3.4.4.
    Building without Cython.
    ERROR: /bin/sh: xslt-config: command not found
    
    ** make sure the development packages of libxml2 and libxslt are installed **
    
    Using build configuration of libxslt
    building 'lxml.etree' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/tmp/pip-build-bcyHK2/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
    In file included from src/lxml/lxml.etree.c:239:0:
    /tmp/pip-build-bcyHK2/lxml/src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory
     #include "libxml/xmlversion.h"
                                   ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-bcyHK2/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-w6wvKY-record/install-record.txt --single-version-externally-managed --compile:
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'

  warnings.warn(msg)

Building lxml version 3.4.4.

Building without Cython.

ERROR: /bin/sh: xslt-config: command not found



** make sure the development packages of libxml2 and libxslt are installed **



Using build configuration of libxslt

running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/lxml

copying src/lxml/builder.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/cssselect.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/sax.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/__init__.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-2.7/lxml

creating build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/__init__.py -> build/lib.linux-x86_64-2.7/lxml/includes

creating build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/builder.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/clean.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/__init__.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/defs.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/diff.py -> build/lib.linux-x86_64-2.7/lxml/html

creating build/lib.linux-x86_64-2.7/lxml/isoschematron

copying src/lxml/isoschematron/__init__.py -> build/lib.linux-x86_64-2.7/lxml/isoschematron

copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-2.7/lxml/includes

creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources

creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/rng

copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/rng

creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl

copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl

copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl

creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

running build_ext

building 'lxml.etree' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/src

creating build/temp.linux-x86_64-2.7/src/lxml

gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/tmp/pip-build-bcyHK2/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w

In file included from src/lxml/lxml.etree.c:239:0:

/tmp/pip-build-bcyHK2/lxml/src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory

 #include "libxml/xmlversion.h"

                               ^

compilation terminated.

error: command 'gcc' failed with exit status 1

----------------------------------------
  Rolling back uninstall of lxml
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-bcyHK2/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-w6wvKY-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-bcyHK2/lxml
Storing debug log for failure in /root/.pip/pip.log
[code-breaker@workstation1 Projects]$ nikola init test
Traceback (most recent call last):
  File "/usr/bin/nikola", line 7, in <module>
    from nikola.__main__ import main
  File "/usr/lib64/python2.7/site-packages/nikola/__init__.py", line 33, in <module>
    from .nikola import Nikola  # NOQA
  File "/usr/lib64/python2.7/site-packages/nikola/nikola.py", line 54, in <module>
    from yapsy.PluginManager import PluginManager
ImportError: No module named yapsy.PluginManager
[code-breaker@workstation1 Projects]$ sudo pip install yapsy
Downloading/unpacking yapsy
  Downloading Yapsy-1.11.223.tar.gz (80kB): 80kB downloaded
  Running setup.py (path:/tmp/pip-build-BA6UUe/yapsy/setup.py) egg_info for package yapsy
    
    no previously-included directories found matching 'doc/_build'
Installing collected packages: yapsy
  Running setup.py install for yapsy
    
    no previously-included directories found matching 'doc/_build'
Successfully installed yapsy
Cleaning up...
[code-breaker@workstation1 Projects]$ nikola init test
Traceback (most recent call last):
  File "/usr/bin/nikola", line 7, in <module>
    from nikola.__main__ import main
  File "/usr/lib64/python2.7/site-packages/nikola/__init__.py", line 33, in <module>
    from .nikola import Nikola  # NOQA
  File "/usr/lib64/python2.7/site-packages/nikola/nikola.py", line 57, in <module>
    from .post import Post  # NOQA
  File "/usr/lib64/python2.7/site-packages/nikola/post.py", line 42, in <module>
    from . import utils
  File "/usr/lib64/python2.7/site-packages/nikola/utils.py", line 53, in <module>
    from doit import tools
  File "/usr/lib/python2.7/site-packages/doit/__init__.py", line 33, in <module>
    from doit.doit_cmd import get_var
  File "/usr/lib/python2.7/site-packages/doit/doit_cmd.py", line 8, in <module>
    from configparser import ConfigParser
ImportError: No module named configparser
[code-breaker@workstation1 Projects]$ sudo pip install configParser
Downloading/unpacking configParser
  Downloading configparser-3.3.0r2.tar.gz
  Running setup.py (path:/tmp/pip-build-l5ndoL/configParser/setup.py) egg_info for package configParser
    
Installing collected packages: configParser
  Running setup.py install for configParser
    deleting configparser.egg-info/requires.txt
    
Successfully installed configParser
Cleaning up...
[code-breaker@workstation1 Projects]$ nikola init test
ERROR:yapsy:Unable to import plugin: /usr/lib64/python2.7/site-packages/nikola/plugins/command/github_deploy
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/command/github_deploy.py", line 36, in <module>
    from nikola.plugins.command.check import real_scan_files
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/command/check.py", line 40, in <module>
    import requests
ImportError: No module named requests
ERROR:yapsy:Unable to import plugin: /usr/lib64/python2.7/site-packages/nikola/plugins/command/check
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/command/check.py", line 40, in <module>
    import requests
ImportError: No module named requests
ERROR:yapsy:Unable to import plugin: /usr/lib64/python2.7/site-packages/nikola/plugins/command/orphans
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/command/orphans.py", line 31, in <module>
    from nikola.plugins.command.check import real_scan_files
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/command/check.py", line 40, in <module>
    import requests
ImportError: No module named requests
ERROR:yapsy:Unable to import plugin: /usr/lib64/python2.7/site-packages/nikola/plugins/command/init
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/command/init.py", line 37, in <module>
    from mako.template import Template
ImportError: No module named mako.template
ERROR:yapsy:Unable to import plugin: /usr/lib64/python2.7/site-packages/nikola/plugins/command/rst2html
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/yapsy/PluginManager.py", line 485, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,None,candidate_filepath,("py","r",imp.PKG_DIRECTORY))
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/command/rst2html/__init__.py", line 32, in <module>
    from mako.template import Template
ImportError: No module named mako.template
ERROR:yapsy:Unable to import plugin: /usr/lib64/python2.7/site-packages/nikola/plugins/command/plugin
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/command/plugin.py", line 33, in <module>
    import requests
ImportError: No module named requests
ERROR:yapsy:Unable to import plugin: /usr/lib64/python2.7/site-packages/nikola/plugins/command/bootswatch_theme
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/command/bootswatch_theme.py", line 30, in <module>
    import requests
ImportError: No module named requests
ERROR:yapsy:Unable to import plugin: /usr/lib64/python2.7/site-packages/nikola/plugins/command/install_theme
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/command/install_theme.py", line 31, in <module>
    import requests
ImportError: No module named requests
ERROR:yapsy:Unable to import plugin: /usr/lib64/python2.7/site-packages/nikola/plugins/command/version
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/command/version.py", line 30, in <module>
    import requests
ImportError: No module named requests
ERROR:yapsy:Unable to import plugin: /usr/lib64/python2.7/site-packages/nikola/plugins/command/import_wordpress
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/command/import_wordpress.py", line 32, in <module>
    import requests
ImportError: No module named requests
ERROR:yapsy:Unable to import plugin: /usr/lib64/python2.7/site-packages/nikola/plugins/template/mako
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/template/mako.py", line 34, in <module>
    from mako import util, lexer
ImportError: No module named mako
ERROR:yapsy:Unable to import plugin: /usr/lib64/python2.7/site-packages/nikola/plugins/compile/markdown/mdx_gist
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/compile/markdown/mdx_gist.py", line 208, in <module>
    import requests
ImportError: No module named requests
ERROR:yapsy:Unable to import plugin: /usr/lib64/python2.7/site-packages/nikola/plugins/compile/rest/vimeo
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/compile/rest/vimeo.py", line 31, in <module>
    import requests
ImportError: No module named requests
ERROR:yapsy:Unable to import plugin: /usr/lib64/python2.7/site-packages/nikola/plugins/compile/rest/gist
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/compile/rest/gist.py", line 4, in <module>
    import requests
ImportError: No module named requests
Error loading mako template system plugin
[code-breaker@workstation1 Projects]$ sudo pip install mako
Downloading/unpacking mako
  Downloading Mako-1.0.1.tar.gz (473kB): 473kB downloaded
  Running setup.py (path:/tmp/pip-build-9hZPFG/mako/setup.py) egg_info for package mako
    
    warning: no files found matching '*.xml' under directory 'examples'
    warning: no files found matching '*.mako' under directory 'examples'
    warning: no files found matching 'ez_setup.py'
    no previously-included directories found matching 'doc/build/output'
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe>=0.9.2 in /usr/lib64/python2.7/site-packages (from mako)
Installing collected packages: mako
  Running setup.py install for mako
    
    warning: no files found matching '*.xml' under directory 'examples'
    warning: no files found matching '*.mako' under directory 'examples'
    warning: no files found matching 'ez_setup.py'
    no previously-included directories found matching 'doc/build/output'
    Installing mako-render script to /usr/bin
Successfully installed mako
Cleaning up...
[code-breaker@workstation1 Projects]$ sudo pip install requests
Downloading/unpacking requests
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB): 470kB downloaded
Installing collected packages: requests
Successfully installed requests
Cleaning up...
[code-breaker@workstation1 Projects]$ nikola init test
ERROR:yapsy:Unable to import plugin: /usr/lib64/python2.7/site-packages/nikola/plugins/command/import_wordpress
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/command/import_wordpress.py", line 56, in <module>
    class CommandImportWordpress(Command, ImportMixin):
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/command/import_wordpress.py", line 329, in CommandImportWordpress
    code_re1 = re.compile(r'\[code.* lang.*?="(.*?)?".*\](.*?)\[/code\]', re.DOTALL | re.MULTILINE)
  File "/usr/lib64/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
error: nothing to repeat
[2015-07-01T17:41:52Z] WARNING: Nikola: In order to USE_BUNDLES, you must install the "webassets" Python package.
[2015-07-01T17:41:52Z] WARNING: bundles: Setting USE_BUNDLES to False.
Creating Nikola Site
====================

This is Nikola v7.5.1.  We will now ask you a few easy questions about your new site.
If you do not want to answer and want to go with the defaults instead, simply restart with the `-q` parameter.
--- Questions about the site ---
Site title [My Nikola Site]: test title
Site author [Nikola Tesla]: test author
Site author's e-mail [n.tesla@example.com]: test email
Site description [This is a demo site for Nikola.]: test description
Site URL [https://example.com/]: test url
    ERROR: You must specify a protocol (http or https).
Site URL [https://example.com/]: http://test.com
    The URL does not end in '/' -- adding it.
--- Questions about languages and locales ---
We will now ask you to provide the list of languages you want to use.
Please list all the desired languages, comma-separated, using ISO 639-1 codes.  The first language will be used as the default.
Type '?' (a question mark, sans quotes) to list available languages.
Language(s) to use [en]: 

Please choose the correct time zone for your blog. Nikola uses the tz database.
You can find your time zone here:
http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

Time zone [America/New_York]: 
    Current time in America/New_York: 13:42:29
Use this time zone? [Y/n] 
--- Questions about comments ---
You can configure comments now.  Type '?' (a question mark, sans quotes) to list available comment systems.  If you do not want any comments, just leave the field blank.
Comment system: 

That's it, Nikola is now configured.  Make sure to edit conf.py to your liking.
If you are looking for themes and addons, check out https://themes.getnikola.com/ and https://plugins.getnikola.com/.
Have fun!
[2015-07-01T17:42:31Z] INFO: init: Created empty site at test.
[code-breaker@workstation1 Projects]$
