### ISSUE TITLE
Arbitrary rst substitutions

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1854]
Since we have transforms now, it should be easy to do something generic, like this:

```|bzr-revno|``` that would be replaced by the output of ```bzr revno``` using a configuration like

```py
def bzr_revno():
    return subprocess.check_output(["bzr", "revno"])

RST_SUBSTITUTIONS = {
    'bzr_revno': bzr_revno
}
```

**Comment by ralsina** [comment]
Now I don't remember how this would have worked anymore :-D

**Comment by Kwpolska** [comment]
just a random guess based on the original post and the rest plugin: http://docutils.sourceforge.net/docs/ref/transforms.html + self.site.rst_transforms?

**Comment by Kwpolska** [comment]
Let’s scrap this and use shortcodes instead.

**Comment by ralsina** [comment]
Shortcodes are horrible in rst because of quoting and random replacements
docutils does.

For example, anything that looks like a URL will become a link before
shortcodes get to it.

**Comment by Kwpolska** [comment]
Well then, I’ll reopen and you might implement it if you ever feel like it.

**Comment by ralsina** [comment]
Maybe a middle ground is a role that passes things through so you can use shortcodes without breaking stuff.
