### ISSUE TITLE
Nikola + Pandoc + Mathjax : Some Maths not displayed properly

### ISSUE THREAD

**Issue by ddmmcjmm** [getnikola/nikola#1862]
I have a static site with Nikola in which `.md` are turned into `.html` with `pandoc`.

Part of my `conf.py` looks like:
    
    COMPILERS = {
        # "markdown": ('.md', '.mdown', '.markdown'),
        "pandoc": ('.md', '.mdown', '.markdown')
    }

I generate posts using `nikola new_post -f pandoc`.

My question is about generating Maths. I have a `.md` file like this:

    

    $\beta_i=2$
    $k_i=2$
    $\hat{\beta_i}=2$

I build my site with `nikola build` and host it locally with `nikola serve`. And here's a screenshot of the browser: http://s9.postimg.org/70t4j7k6l/Screen_Shot_2015_07_04_at_11_48_40_pm.png

The first two math equations are displayed properly. But the last one is not.
    
Can anyone help? Thanks.

**Comment by Kwpolska** [comment]
How does the HTML source look?  (also, since when does MathJax use sans-serif fonts?)

**Comment by ddmmcjmm** [comment]
Thanks for your reply. This makes me doubt whether I am using MathJax in Nikola. I have pasted my html code here https://gist.github.com/ddmmcjmm/52c469c47e6ab3429597

Thanks for having a look at that.

**Comment by Kwpolska** [comment]
You’re not, Pandoc is parsing that and failing miserably.  Please figure out how to disable that in `PANDOC_OPTIONS`, or just use the sane `markdown` compiler.

Besides, you’re going to need to alter `MATHJAX_CONFIG` to use `$` for input, or use `\(2 + 2 = 4\)`.
