### ISSUE TITLE
Bootstrap3 theme needs aria-expanded on the navigation toggle button

### ISSUE THREAD

**Issue by tspivey** [getnikola/nikola#1863]
When the Toggle navigation button is pressed, the screen reader doesn't know that a new list appeared under it.
To fix this, I think you can add aria-expanded="false" or aria-expanded="true" to indicate the current status.

**Comment by Kwpolska** [comment]
Fixed, thanks!

I just deployed this to [our website](https://getnikola.com/). Would you please mind testing if it works properly?  And while you’re at it, do the navigation bar dropdown menus (Documentation/Support & Contact; also changed) work for you?

**Comment by tspivey** [comment]
I tested the site, with the following results:
1. Pressing the Toggle navigation button fails to change the 
expanded/collapsed status, it's always reported as collapsed.
2. Once expanded, the documentation and contact links do report 
expanded/collapsed.
I tested with NVDA and Firefox.

**Comment by Kwpolska** [comment]
I think I got it to work now, would you mind [testing again](https://getnikola.com/)?

**Comment by tspivey** [comment]
Thanks, works now.
