### ISSUE TITLE
Images not being copied to output

### ISSUE THREAD

**Issue by notfoss** [getnikola/nikola#1872]
Hi guys, long time no see.

So, I decided to give the latest Nikola a try and have encountered a problem. Using `nikola build` I get this error:

    Scanning posts....done!
    ERROR: Two different tasks can't have a common target.'output/images/digitalocean-logo.png' is a target for copy_files:output/images/digitaloce
    an-logo.png and scale_images:output/images/digitalocean-logo.png.

But, I found that no image under the images directory is being copied to the output. Here's the structure of my images directory (the root has a few images, rest all are under the month directories).
```
.
├── 2013
│   ├── 05
│   ├── 06
│   └── 10
└── 2014
    ├── 03
    └── 04
```

The interesting thing is that the directory structure *is* being copied to the output directory, but not the files.

Using Nikola 7.6.0 with Python 3.4.3

**Comment by Kwpolska** [comment]
Please show your config and full directory structure.

**Comment by ralsina** [comment]
The important part would be FILES_FOLDERS and IMAGES_FOLDERS, probably.

It looks like you have either the same folder in both or the same file in two folders which are one on each list.

**Comment by notfoss** [comment]
Here's FILES_FOLDERS
 
    FILES_FOLDERS = {'files': 'files', 'images': 'images'}
I don't have any IMAGES_FOLDERS option.

@Kwpolska, are you asking for the full directory structure of the images directory?

**Comment by Kwpolska** [comment]
`IMAGES_FOLDERS` defaults to `{'images': 'images'}`.  You basically have two options:

(a) remove images from `FILES_FOLDERS` and use `IMAGES_FOLDERS` instead (it will add thumbnails for you); or  
(b) set `IMAGES_FOLDERS` to an empty dict and leave it the way it is.

(I don’t need the directory structure anymore.)

**Comment by notfoss** [comment]
Setting IMAGES_FOLDERS to an empty dict didn't fix the problem. Also, I cannot find any reference to this option either in conf.py or in the whole repository instead. Where is it being referenced from?

**Comment by Kwpolska** [comment]
It’s actually `IMAGE_FOLDERS`, sorry.

**Comment by notfoss** [comment]
Still getting the same error with `IMAGE_FOLDERS`. Just to be clear, I am setting it as following:
    
     IMAGE_FOLDERS = {}

**Comment by ralsina** [comment]
On 08/07/15 09:28, notfoss wrote:
>
> Here's FILES_FOLDERS
>
> |FILES_FOLDERS = {'files': 'files', 'images': 'images'}
> |
>
> I don't have any IMAGES_FOLDERS option.
>
> @Kwpolska <https://github.com/Kwpolska>, are you asking for the full 
> directory structure of the images directory?
>

Ok, set IMAGES_FOLDERS = {}

please :-)

OR,  remove images from FILES_FOLDERS, and get image thumbnails for free.

**Comment by Kwpolska** [comment]
> Edit: Nevermind, this happened due to the IMAGES / IMAGE confusion. I didn't search for IMAGE_FOLDERS in conf.py. It was being used later in the file. Now everything builds fine. Thanks!

This was caused by us changing the default after this feature was first introduced, which led to this setting being uncommented. Wouldn’t happen in normal circumstances. Sorry!
