### ISSUE TITLE
Add type of page to template context

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1877]
I started hacking around this quite some time ago by conditionally finding unique keys available only in the contexts of some page tasks and not other. It’s starting to become hairy and unmaintainable, but there is clearly a need to identify page kind. I use it to include some special stuff on the front page only, load some stylesheets only on indexes,  some scripts only on posts, and include search fields only on some pages.

* frontpage (work-around: %if permalink == '/' or permalink == '/' + index_file)
* index (work-around: %if index_teasers)
* tag (work-around: %if tag and not post)
* archive ?
* post (work-around: %if post, unreliable)
* story ?
* postlist ?
* listingfolderpage (work-around: % if crumbs)
* galleries
* others?

Suggestions for the best way to do this? Should be some unified thing that it’s easy to write conditionals for in templates.

A page can consist of one or more type of page. For exampe, index and archive, frontpage and index, and list and tag.

**Comment by Kwpolska** [comment]
We could just add a `pagetype` field to every template, and maybe a `pageid` field (that could be used to implement #1287 with `link://`/`url_replacer`)

**Comment by Aeyoun** [comment]
ac9a7bc7c2
