### ISSUE TITLE
Custom INDEX_READ_MORE_LINK not working

### ISSUE THREAD

**Issue by notfoss** [getnikola/nikola#1879]
I am adding an additional class for the "Read more" links using

    INDEX_READ_MORE_LINK = '<p class="more"><a class="label label-primary" href="{link}">{read_more}…</a></p>'

but it is not being applied to the output files. Using Nikola 7.6.0

**Comment by Kwpolska** [comment]
Did you change the setting that already exists?

**Comment by notfoss** [comment]
Yes, in conf.py.

```
$ grep INDEX_READ_MORE_LINK conf.py
# INDEX_READ_MORE_LINK = '<p class="more"><a href="{link}">{read_more}…</a></p>'
INDEX_READ_MORE_LINK = '<p class="more"><a class="label label-primary" href="{link}">{read_more}…</a></p>'
```

**Comment by Kwpolska** [comment]
I’m afraid I cannot reproduce with an almost-clean demo site and Nikola from GitHub master.  Please:

(a) try rebuilding everything with `nikola build -a` (maybe there’s a caching issue?)
(b) post your conf.py file if that does not help

Works for me:
```
$ grep INDEX_READ_MORE_LINK conf.py
# INDEX_READ_MORE_LINK = '<p class="more"><a href="{link}">{read_more}…</a></p>'
INDEX_READ_MORE_LINK = '<p class="more"><a class="label label-primary" href="{link}">{read_more}…</a></p>'
```

Also, do you have an old `READ_MORE_LINK` setting? This could break things, though I’m pretty sure it wouldn’t…

**Comment by notfoss** [comment]
`nikola build -a` didn't work.

Then I tried a new test site with a clean conf.py, but copied over my posts to the new site. Same result. I finally tracked down the problem to custom TEASER_END text. Without custom text, INDEX_READ_MORE_LINK works fine.

I use the following:
      
    .. TEASER_END: Continue Reading...

**Comment by Kwpolska** [comment]
We have some hardcoded HTML for that case.  Opening a PR with a fix.

**Comment by Aeyoun** [comment]
It was done that way to work the same way as the feed variant of that setting.

**Comment by Kwpolska** [comment]
What do you mean?

**Comment by notfoss** [comment]
So, I just checked the fix and now my `Continue Reading...` becomes `Continue Reading... ...`, i.e., `...` is automatically appended after custom text.

**Comment by Kwpolska** [comment]
If your setting is "{read_more}...", this is correct behaviour.

**Comment by notfoss** [comment]
Aah, yes. The wonders of trying out software after two major version bumps :P.

Thanks!
