### ISSUE TITLE
utils.slugify sometimes returns a str, sometimes a unicode

### ISSUE THREAD

**Issue by evgeni** [getnikola/nikola#1885]
Debian Sid, Python 2.7.10.

    >>> import nikola.utils
    >>> a = nikola.utils.slugify(u'aaaaa')
    >>> type(a)
    <type 'str'>
    >>> a = nikola.utils.slugify(u'aaa-aa')
    >>> type(a)
    <type 'unicode'>

It seems, that if `slugify` does not replace anything, it will return a `str` instead of an `unicode`. This breaks the wordpress import because it calls `slugify` twice:

            for tag in self.all_tags:
                try:
                    tag_str = tag.decode('utf8')
                except AttributeError:
                    tag_str = tag
                tag = utils.slugify(tag_str)
                src_url = '{}tag/{}'.format(self.context['SITE_URL'], tag)
                dst_url = self.site.link('tag', tag)
                if src_url != dst_url:
                    self.url_map[src_url] = dst_url

(`site.link` calls `slugify` too)

**Comment by Kwpolska** [comment]
`slugify`*.

Please test yourself (with your WordPress dump?), apply changes in commit 50f92ad over your `utils.py`. If it works, I’ll merge it into master.

**Comment by evgeni** [comment]
Yeah, sorry for the typo, no idea why I made it everywhere.

Patch is good, I can import my WP dump just fine now.
