### ISSUE TITLE
Python 3 is BATSHIT INSANE

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1887]
Random rebuilds on [my blog](https://github.com/Kwpolska/chriswarrick.com):

- [x] tag indexes rebuild all the time
- [ ] galleries rebuild at random (`self.kw` changes sometimes)
- blog posts/pages, mainly related to those galleries, rebuild when galleries get rebuilt (sounds sane)

I have no idea where to start debugging this shit. I’m running Nikola from github master.

Database diffs hint at sorting issues: https://gist.github.com/754d0a351618099f7d4c and https://gist.github.com/7611c1fe09ddf9d6680a
Note that dict order is RANDOM in Python 3.

cc @felixfontein (you messed with all this recently, didn’t you?)

**Comment by Kwpolska** [comment]
experiments moved to https://github.com/Kwpolska/chriswarrick.com/tree/py3

**Comment by felixfontein** [comment]
I've debugged similar things since they often happen to me too (since I'm using Python 3). The diffs (or the parts I've looked at) look ok to me; doit stores the dependency set as a list and the order of that one changes a lot.
I'll play around with your blog a bit, maybe I can find out something.

**Comment by felixfontein** [comment]
And the problem is surely not Python 3, but programmers who make assumptions which simply aren't true, and Python 3 is nice enough to make you notice ;-)

**Comment by ralsina** [comment]
Silly idea... how about we always use ordereddicts? They are there since 2.7 and we don't support anything earlier (do we?)

**Comment by felixfontein** [comment]
Why use a less efficient datastructure everywhere just because we're too lazy to find out where it is really needed? :)

**Comment by ralsina** [comment]
Because I am not perfect.

**Comment by felixfontein** [comment]
Actually, the dependencies *can* matter: namely if the set of dependencies changes, doit will recompile (it's just the order which doesn't matter). For one of the tasks I took a closer look at on my machine (`render_tags:output/pl/blog/tags/review/index.html`), the dependency list had 34 entries in the second run, and 92 in the first. All other fields (in particular the ones we compute checksums of) didn't change.

So this is definitely not a set vs. orderedset (or dict vs. ordereddict) problem, but something else.

**Comment by felixfontein** [comment]
If I run `nikola info render_tags:output/pl/blog/tags/review/index.html`, it will print the dependency list in a sorted way. I called it four times, once it had 58 entries, and then three times 98 entries.

**Comment by felixfontein** [comment]
The problem seems to be the call `deps = self.template_system.template_deps(template_name)` in `Nikola.generic_post_list_renderer`. It returns different sized lists for the same call in different instances of `nikola info render_tags:output/pl/blog/tags/review/index.html`.

**Comment by felixfontein** [comment]
Just add
```
if output_name == 'output/blog/tags/review/index.html': print(deps)
``` 
below that line (in line 1585) and you can easily see the differences yourself.

**Comment by felixfontein** [comment]
My conclusion so far: `template_deps` is somewhat broken. The reason why it shows up with Python 3 is probably that the order for which templates/posts `template_deps` is called depends on every run.

**Comment by felixfontein** [comment]
BTW, the template dependency list returned by `JinjaTemplates.template_deps` also contains files like `cache/posts/2015/07/06/upass.html`, `posts/2013/02/09/password-changing-101.rst`. Is it supposed to do that? (I don't think so.)

**Comment by felixfontein** [comment]
All statements above might depend on the specific blog input, in this case Chris' blog.

Since this doesn't happen for my blogs (which use custom themes not inheriting from any theme included with Nikola), this is probably either a problem with the bootstrap3 theme or Chris' theme, or a problem with something else specific to Chris' blog. Anyway, it doesn't seem to have any connection to code I touched. So I'll pass this along to Chris.

**Comment by Kwpolska** [comment]
> BTW, the template dependency list returned by JinjaTemplates.template_deps also contains files like cache/posts/2015/07/06/upass.html, posts/2013/02/09/password-changing-101.rst. Is it supposed to do that? (I don't think so.)

Disabling this makes tags rebuild correctly, i.e. never.

The culprit is **lack of list copying**.  We set `deps` to the template dependencies, and then added in post dependencies.  I can’t reproduce the tags bug anymore. 6d749f4 fixes it.

The galleries-and-friends bug, which might also be something global, still persists.  I’ll look into it. It seems to be caused by the `mkdir` config_changed.

Thanks for the help, @felixfontein!

**Comment by felixfontein** [comment]
Ah, yes, that makes sense. In fact then this was my fault after all, since I added that loop (I think).

With that fix and your blog, I'm also getting some other random rebuilds for `render_pages` targets:
```
Scanning posts.....done!
.  render_galleries:output/galleries
.  render_galleries:output/galleries/upass
.  render_galleries:output/galleries/speeker
.  render_galleries:output/galleries/inbox-by-google
.  render_galleries:output/galleries/index.html
.  render_galleries:output/galleries/rss.xml
.  render_galleries:output/pl/galleries/index.html
.  render_galleries:output/pl/galleries/rss.xml
.  render_galleries:cache/galleries/upass/index.html
.  render_galleries:cache/galleries/upass/index.pl.html
.  render_galleries:output/pl/galleries/upass/index.html
.  render_galleries:output/pl/galleries/upass/rss.xml
.  render_galleries:cache/galleries/speeker/index.html
.  render_galleries:cache/galleries/speeker/index.pl.html
.  render_galleries:output/pl/galleries/speeker/index.html
.  render_galleries:output/pl/galleries/speeker/rss.xml
.  render_galleries:cache/galleries/inbox-by-google/index.html
.  render_galleries:cache/galleries/inbox-by-google/index.pl.html
.  render_galleries:output/pl/galleries/inbox-by-google/index.html
.  render_galleries:output/pl/galleries/inbox-by-google/rss.xml
.  render_galleries:output/galleries/upass/rss.xml
.  render_galleries:output/galleries/upass/index.html
.  render_galleries:output/galleries/speeker/index.html
.  render_galleries:output/galleries/speeker/rss.xml
.  render_galleries:output/galleries/inbox-by-google/rss.xml
.  render_galleries:output/galleries/inbox-by-google/index.html
.  render_pages:output/pl/blog/2015/07/06/upass/index.html
.  render_pages:output/pl/blog/2015/05/30/think/index.html
.  render_pages:output/pl/blog/2014/08/26/speeker/index.html
.  render_pages:output/pl/blog/2014/08/01/series-android-adventure/index.html
.  render_pages:output/pl/search/index.html
.  render_pages:output/pl/cookies/index.html
.  render_pages:output/pl/contact/index.html
.  render_pages:output/blog/2015/07/06/upass/index.html
.  render_pages:output/blog/2015/05/30/think/index.html
.  render_pages:output/blog/2014/08/26/speeker/index.html
.  render_pages:output/blog/2014/08/01/series-android-adventure/index.html
.  render_pages:output/search/index.html
.  render_pages:output/cookies/index.html
.  render_pages:output/contact/index.html
.  sitemap:output/sitemap.xml
```
(`sitemap.xml` is not surprising since other things changed, but neither the `render_pages` nor the `render_galleries` should happen)

**Comment by felixfontein** [comment]
Ok, I think I found the problem. Let me analyze a bit further.

**Comment by felixfontein** [comment]
The problem is that `post_translations` is inserted into `deps_dict` in `Nikola.generic_page_renderer`. `post_translations` is a set of languages, and in the case of some of the above pages, it is `{'en', 'pl'}`. Now `json.dumps(self.config, cls=CustomEncoder, sort_keys=True)` in `utils.config_changed._calc_digest` converts that set to a string -- and sometimes writes `'{'en', 'pl'}'`, and sometimes `'{'pl', 'en'}'`.

The real culprit here is `utils.CustomEncoder.default`, which calls `repr()` of everything `json.JSONEncoder` doesn't like (like sets). And `repr()` of a set depends on the internal ordering. So we should patch `CustomEncoder.default` to detect sets and make sure that their orders stay the same (by converting them to a list and sorting it, for example).

**Comment by felixfontein** [comment]
Little fix which stops all non-gallery pages rebuilding:
```
class CustomEncoder(json.JSONEncoder):
    def default(self, obj):
        try:
            return super(CustomEncoder, self).default(obj)
        except TypeError:
            if isinstance(obj, set):
                return '{' + repr(sorted(list(obj)))[1:-1] + '}'
            else:
                s = repr(obj).split('0x', 1)[0]
            return s
```

**Comment by felixfontein** [comment]
I can fix the galleries from rebuilding by replacing `Galleries.create_galleries` by
```
    def create_galleries(self):
        """Given a list of galleries, create the output folders."""

        # gallery_path is "gallery/foo/name"
        for gallery_path, input_folder, _ in self.gallery_list:
            # have to use dirname because site.path returns .../index.html
            output_gallery = os.path.dirname(
                os.path.join(
                    self.kw["output_folder"],
                    self.site.path("gallery", gallery_path)))
            output_gallery = os.path.normpath(output_gallery)
            # Task to create gallery in output/
            yield {
                'basename': self.name,
                'name': output_gallery,
                'actions': [(utils.makedirs, (output_gallery,))],
                'targets': [output_gallery],
                'clean': True,
                'uptodate': [utils.config_changed(copy.copy(self.kw), 'nikola.plugins.task.galleries:mkdir')],
            }
```
(I added `copy.copy()`, and of course also an `import copy` at the top of the file.)

**Comment by felixfontein** [comment]
There are quite some potential problems in the galleries plugin, `self.kw` is modified all over the place, and used in `config_changed` without creating a copy first.

**Comment by felixfontein** [comment]
(I'm using `self.kw.copy()` now, instead of `copy.copy(self.kw)`.)

**Comment by felixfontein** [comment]
Hmm, ok, that fixes not everything yet. I still get
```
.  render_galleries:output/galleries/index.html
.  render_galleries:output/galleries/rss.xml
.  render_galleries:output/pl/galleries/index.html
.  render_galleries:output/pl/galleries/rss.xml
.  sitemap:output/sitemap.xml
```

**Comment by felixfontein** [comment]
Ok, fixed the galleries for now. Problem was that `'navigation_links|{0}'.format(lang)` was inserted in the languages loop, and since the order of the elements looped over changed, `self.kw` was sometimes different for the same file in different runs.

**Comment by felixfontein** [comment]
(see 90dd7e0359411e2702b3b38b03ed6a2de6bbfeaf)

**Comment by Kwpolska** [comment]
All fixed.  Thanks for the help!

**Comment by felixfontein** [comment]
You're welcome. It's good to know that it's now working again as it was supposed to.

I'm afraid that such bugs will show up here and there again, since they are really easy to introduce.

**Comment by schettino72** [comment]
> I'm afraid that such bugs will show up here and there again, since they are really easy to introduce.

@felixfontein Is there anything `doit` could do to avoid these?

**Comment by felixfontein** [comment]
@schettino72: I don't think so. These are essentially all problems on Nikola's side. By adding automatic (deep) copying of objects when they are passed to tasks or `config_changed` you could try to mitigate _some_ of the problems, but that might introduce new (potential) problems.

**Comment by Kwpolska** [comment]
@schettino72 There could be some help from doit, in the form of detailed debug information (in the form of *why did this task run?*)

**Comment by schettino72** [comment]
> @schettino72 There could be some help from doit, in the form of detailed debug information (in the form of why did this task run?)

@Kwpolska There is an open issue for that already... https://github.com/pydoit/doit/issues/24 it should not be hard to implement.

**Comment by felixfontein** [comment]
Actually that would be really helpful. Debugging this by hand (looking at DB dumps, inserting `print` statements in Nikola and doit code) is not that much fun...

**Comment by felixfontein** [comment]
I started adding such a feature (see pydoit/doit#75)
