### ISSUE TITLE
Augment post-list directive with more filters

### ISSUE THREAD

**Issue by erdgeist** [getnikola/nikola#1889]
Currently, filtering posts that go into post-lists only works with tags or slugs. In the legacy site I currently want to migrate, I have views in the form of /press/releases/<year>/ that would filter by date but could also filter by globbing the path name. I wonder if there is a generic way to filter by multiple meta data entries.

While we're at it: once you add powerful filters to post-lists and get something what is called "the loop" in php sites, i.e. filter/sort/slice/templatize, the currently implemented indexes for posts-by-year, posts-by-author and posts-by-category just become special cases of these posts-lists. You could basically create paginated indexes for all posts-list queries and offer rss feeds for each of them, too.

**Comment by Kwpolska** [comment]
For `date`: https://gist.github.com/Kwpolska/2779f7d1ea006971aad1

(I’ll relicense to MIT if wanted)

**Comment by Kwpolska** [comment]
`categories` added.
