### ISSUE TITLE
auto can’t be keyboard interrupted after rebuilding files

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1893]
py3

1. nikola auto
2. touch any file after Nikola have started serving the files
3. ctrl+c

    INFO: auto: Server is shutting down.

4. ctrl+c again

    ^CException ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
    Traceback (most recent call last):
      File "/usr/lib/python3.4/threading.py", line 1294, in _shutdown
        t.join()
      File "/usr/lib/python3.4/threading.py", line 1060, in join
    self._wait_for_tstate_lock()
      File "/usr/lib/python3.4/threading.py", line 1076, in _wait_for_tstate_lock
        elif lock.acquire(block, timeout):
    KeyboardInterrupt

**Comment by ralsina** [comment]
Can we put back the hack using kill?

**Comment by Aeyoun** [comment]
Surely everyone likes a good process murder.

**Comment by ralsina** [comment]
Something is starting a non-daemon thread and thus, even if Valar Morghulis, proceses do not. Here's the diff https://github.com/getnikola/nikola/commit/a9e09414cdb14128137ac8353ccfa1bfda2c4cf4

**Comment by Kwpolska** [comment]
I undid it in #1832/6f3002acedf9d924c44d1931daeb36b7e3f0d72a, it worked properly for me. Threads are really crazy; we should probably restore this kill…
