### ISSUE TITLE
mock==1.1.4 compatibility

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1894]
testing-cabal/mock#228, anyone has any ideas on how to fix [all our mock_open tests](https://travis-ci.org/getnikola/nikola/jobs/71393137#L648)?

cc @ralsina

**Comment by ralsina** [comment]
I can probably fix it. I'll take  a look.

**Comment by ralsina** [comment]
In the case of the failing tests in test_utils it looks like the tests are just broken but succeeded by accident.
