### ISSUE TITLE
ipynb listings

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1900]
It would be nice if I could throw an `.ipynb` file in the listings directory and have it render.

Issues:
* would anyone ever want to show off the raw (json) file?
* strange behavior, compared to other formats (including html)

**Comment by ralsina** [comment]
Honestly, it would stinkk of special-casing. We could have a task plugin that took /notebooks and rendered it somewhere in the proper way tho

**Comment by damianavila** [comment]
>It would be nice if I could throw an .ipynb file in the listings directory and have it render.

In fact I think it would be nice to have something like:

`listing: foo.ipynb cells[2:5] python`

I mean, some way to read the content from cell 2 to 5 and show that but rendered correctly (as nbconverted html snippet... 

>would anyone ever want to show off the raw (json) file?

Not to much frequently...

>strange behavior, compared to other formats (including html)

What do you mean with strange?

**Comment by ralsina** [comment]
@Kwpolska On second thought ... how does that differ from throwing the notebook in stories/ ?

**Comment by Kwpolska** [comment]
I would have to take care of directory listings myself, create .py code
block stories out of non-ipynb related files, and it won't display in
listings/.

-- 
Chris Warrick <https://chriswarrick.com>

**Comment by ralsina** [comment]
So... currently we just use pygments to highlight stuff in listings. So, to support this usage, we'd need to have a mechanism to support different processors for different extensions. With that, it would not be horribly hard :-)

**Comment by ralsina** [comment]
If anyone can describe how this feature would work, I'm happy to take a shot at it.

One problem is that the listings **directive** has no way to support this, so it will make things more complicated.

Another is that it should be, if it is to be implemented, a reasonably complete thing that provides support for arbitrary renderers, which means it has huge feature overlap with stories. In fact, it looks like "stories organized by folder hierarchy" which is sort of easy?

**Comment by Kwpolska** [comment]
I actually looked into this now and an implementation in the “full” listings is really simple, will have a PR ready in a moment.

As for the directive, would that be useful? If yes, I think it could be implemented with a simple `get_code_from_file` modification that would return raw HTML nodes from that ipynb plugin.

Implementing “listings = stories with folders” could be problematic. You see, the current idea takes ipynb only, because it’s very unlikely someone would actually want to display the raw JSON files (and if they do, they can just change the extension and also get JSON code highlighting), and displaying notebooks sounds like something a scientist might want to do. But, we could get a web developer who wants to showcase some `.html`, `.md`, `.rst`, and this could be a problem, because we would need some setting/magic to tell raw and rendered modes apart.
