### ISSUE TITLE
Tags to ipython notebooks

### ISSUE THREAD

**Issue by Mec-iS** [getnikola/nikola#1903]
Is there any way to add metadata to IPython Notebooks JSONs? 
I.e. how can I add tags to a post generated by a .ipynb file?

**Comment by Kwpolska** [comment]
If you are using 2-file posts (simpler): just edit the `.meta` file.
If you are using 1-file posts:Edit → Edit Notebook Metadata in the Jupyter web app, or edit the `.ipynb` file by hand.

**Comment by Kwpolska** [comment]
On a side note: Issues are not the best place for general usage questions, please try the [mailing list](http://groups.google.com/group/nikola-discuss) or #nikola on freenode instead.
