### ISSUE TITLE
Translatable URL pathnames

### ISSUE THREAD

**Issue by edemalm** [getnikola/nikola#1914]
Would be nice if we could have translatable *_PATH names in config file.
Think of  /en/categories/cars and /es/categorias/automovil on the same site.

https://groups.google.com/forum/#!topic/nikola-discuss/LXuI3c6eq2Q
- [x] TAG_PATH
- [x] CATEGORY_PATH
- [ ] AUTHOR_PATH
- [ ] INDEX_PATH
- [ ] RSS_PATH

**Comment by ralsina** [comment]
We have a number of these, so I will do each on a separate PR. Adding list of them to the issue description.
