### ISSUE TITLE
Implement mechanism to make posts depend on config options

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1919]
Suppose a rest directive can do things differently based on a config option (yes, abstract feature).

Currently, it would need to record a dependency on the conf.py file in order to react to config changes.

This feature would provide the directive developer a mechanism to declare a depedency on specific config key values.

**Comment by Kwpolska** [comment]
Doing #1854, aren’t you now?

Sounds like adding a `####MAGIC####CONFIG:REST_SUBSTITUTIONS` dependency (like it’s done in post lists) and some simple handling would do it.

**Comment by ralsina** [comment]
Actually,no, this was requested by @humitos for his fotorama  stuff, but yes, that would also need it, and yes, that's the plan :-)

**Comment by ralsina** [comment]
@humitos take a look, that implementation is not tested, see the doc diff for how  it's supposed to work ;-)

**Comment by ralsina** [comment]
Done.
