### ISSUE TITLE
"nikola auto" serving implicit index.html with wrong mime type

### ISSUE THREAD

**Issue by MrClever** [getnikola/nikola#1921]
nikola 7.6.2

- requesting http://localhost:8000/ returns an application/octet-stream (**wrong**)
- requesting http://localhost:8000/index.html returns text/html

::

	james@osx-yosemite - ~
	130:>wget --no-proxy --server-response --spider http://127.0.0.1:8000/
	Spider mode enabled. Check if remote file exists.
	--2015-08-01 14:04:33--  http://127.0.0.1:8000/
	Connecting to 127.0.0.1:8000... connected.
	HTTP request sent, awaiting response...
	  HTTP/1.0 200 OK
	  Date: Sat, 01 Aug 2015 04:04:33 GMT
	  Content-type: application/octet-stream
	  Content-Length: 30926
	Length: 30926 (30K) [application/octet-stream]
	Remote file exists.

	james@osx-yosemite - ~
	0:>wget --no-proxy --server-response --spider http://127.0.0.1:8000/index.html
	Spider mode enabled. Check if remote file exists.
	--2015-08-01 14:04:45--  http://127.0.0.1:8000/index.html
	Connecting to 127.0.0.1:8000... connected.
	HTTP request sent, awaiting response...
	  HTTP/1.0 200 OK
	  Date: Sat, 01 Aug 2015 04:04:45 GMT
	  Content-type: text/html
	  Content-Length: 31123
	Length: 31123 (30K) [text/html]
	Remote file exists and could contain further links,
	but recursion is disabled -- not retrieving.

This happens regardless of the path within the site. So requesting
- http://localhost:8000/posts/2015/08/01/Something/   --> [application/octet-stream]
- http://localhost:8000/posts/2015/08/01/Something/index.html   --> [text/html]

Obviously this is painful when testing as the browser refuses to parse an octet-stream (expected behaviour) but the pretty links are all relying on implicit index pages.  So after every link that ends in "/", I need to append "index.html" etc.

Anyone else seeing this?

-- James

**Comment by Aeyoun** [comment]
Fixed yesterday in 5d894a9e.

**Comment by MrClever** [comment]
Missed that - sorry for the duplicate.  Good work :) Thanks.
