### ISSUE TITLE
Support reading pelican posts directly

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1923]
This came up in the podcast I was in along with a pelican guy... why is our post/data/metadata format different?

I know _why_ ours is the way it is, but hey, why not support their version? Most metadata is exactly the same anyway.  This would reduce  vendor lock-in and is The Nice Thing To Do (in general).

- [x] Support markdown metadata
- [x] Support reSt metadata
- [x] Support HTML meta tags

**Comment by Kwpolska** [comment]
:+1: I sort of wanted to create this issue in the past, with a title along the lines of “simplify world domination”.

But please don’t use crazy regexps for that. They use reST `:fields:`, and we can probably talk docutils into giving us that metadata (probably need to look at Pelican code).  Bonus points for implementing that as compiler metadata, and even more bonus points for getting the page title this way (and removing the hacky code).

**Comment by schettino72** [comment]
link to podcast ?

**Comment by ralsina** [comment]
@schettino72 it's not published yet.

**Comment by ralsina** [comment]
@Kwpolska for markdown they use something that looks like ours except not in a comment and without the ".. " (of course).

We'll also need to remove all that stuff from the output to avoid repeating stuff, so ... tricky.

**Comment by Kwpolska** [comment]
Stealing (at least for reST).

**Comment by ralsina** [comment]
@Kwpolska Be my guest, I am not touching this for a few days at least.

**Comment by Kwpolska** [comment]
* need Publisher (and some refactoring around rst2html and friends; cached instance)
* Try to get id for `title` and `docinfo` from `pub.document.first_child_matching_class(docutils.nodes.XXX)`
* **Title**
  1. Get `title` via `pub.document.children[title_id]` (if it is not None)
  2. Use title.astext() to get the title (loses formatting)
* **Metadata**
  1. Get `docinfo` via `pub.document.children[docinfo_id]` (if it is not None)
  2. Iterate over docinfo.children. There are multiple types of field objects. The type of the current field object needs to be checked using `NAME = field.tagname`:
    * authors: `field.child_text_separator = ', '; VALUE = field.astext()`
    * field [reST fallback]: `NAME = field.children[0].astext(); VALUE = field.children[1].astext()`
    * address, author, contact, copyright, date, organization, revision, status, version [or just `else`]: `VALUE = field.children[1].astext()`
* **Post-processing**
  * A mapping needs to be used to translate Pelican/docutils names into Nikola names. Converting names to lowercase might also be useful.
  * The data can be then fed back to `get_meta()`, but it needs to check if further searches should happen. The metadata can be partial (eg. only "Version" in Nikola docs), and the title might also be a random heading. A good solution could just read the comments and use them as overrides.
  * At the same time, docinfo would have to be hidden now, at least for unconsumed entries. Perhaps a better solution would be to generate docinfo by hand.

**Comment by Kwpolska** [comment]
I have an implementation on the `pelican-posts` branch, but it’s currently broken.  I have a problem though: we have to parse the documents twice, as of right now.  And we get a race condition, and a bogus HTTP request:

```
$ nikola console
Scanning posts.[2015-08-23T16:41:37Z] ERROR: compile_rest: [posts/1.rst:20] "handbook" slug doesn't exist.
[2015-08-23T16:41:37Z] ERROR: compile_rest: [posts/1.rst:23] "listings-demo" slug doesn't exist.
[2015-08-23T16:41:37Z] ERROR: compile_rest: [posts/1.rst:24] "slides-demo" slug doesn't exist.
[2015-08-23T16:41:37Z] ERROR: compile_rest: [posts/1.rst:25] "bootstrap-demo" slug doesn't exist.
..[2015-08-23T16:41:37Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): gist.github.com
[2015-08-23T16:41:38Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): gist.githubusercontent.com
[2015-08-23T16:41:39Z] ERROR: compile_rest: [stories/manual.rst:1689] "creating-a-theme" slug doesn't exist.
[2015-08-23T16:41:39Z] ERROR: compile_rest: [stories/manual.rst:1699] "creating-a-theme" slug doesn't exist.
[2015-08-23T16:41:39Z] ERROR: compile_rest: [stories/manual.rst:1913] "extending" slug doesn't exist.
.done!
```

@ralsina, do you have any idea of how we should structure the code to prevent that, and, at the same time, not damage the ipynb plugin?

Or maybe we could use a special publisher for reading metadata that ignores all extensions and errors (still lower performance)?

**Comment by ralsina** [comment]
I can't take a look right now, but tonight, sure.

**Comment by ralsina** [comment]
So I have a branch that does this for markdown and reSt. Yes, it still reads/parses the document twice.
