### ISSUE TITLE
Category in translated posts ignored

### ISSUE THREAD

**Issue by edemalm** [getnikola/nikola#1924]
From https://groups.google.com/forum/#!topic/nikola-discuss/LXuI3c6eq2Q

Nikola is ignoring the translated category from translated posts, the default category is used across all languages.

**Comment by ralsina** [comment]
So the problem (or one of them) is here in the tags plugin:

```
        categories = [cat.category_name for cat in self.site.category_hierarchy]
```

This is completely unaware of locales.

**Comment by edemalm** [comment]
Hi!
I created this issue, but since then I've moved over to use sections instead, which is great. This issue is no longer important to me, but I guess it's none the less a bug and might be important for other users so I leave it open.

**Comment by Kwpolska** [comment]
We’re killing categories soon, so that will probably end up being a *wontfix*.
