### ISSUE TITLE
Should be only one webserver

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1929]
Why do we need to different servers for `serve` and `auto`? Should reuse as much as possible here.

**Comment by ralsina** [comment]
Because auto is part websockets. I have no idea how to do what you want.

**Comment by Aeyoun** [comment]
Well, auto minus rebuild and script injection == web server, right?

**Comment by ralsina** [comment]
Yes, but to handle websockets, auto needs a WSGI server, serve needs only a HTTP server.

**Comment by ralsina** [comment]
So! Yes, I would love to have only one server. No, we can't have only one server.
