### ISSUE TITLE
Yearly archivs not rebuilt when their posts change

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1931]

**Comment by ralsina** [comment]
@Aeyoun 

What I see is that if ARCHIVES_ARE_INDEXES is True, then you change a post content, then the archives are not rebuilt. Is it that one you saw?

**Comment by Aeyoun** [comment]
@ralsina, my archives [are lists](https://www.aeyoun.com/2014/index.html). If I change the slug of one of these, it’s not updated.

Specifically, I moved from one post from one POSTS folder to another but kept the post otherwise unchanged. Everything else rebuilt fine.

**Comment by ralsina** [comment]
Ok, so two related-ish bugs. I'll take a look.

**Comment by ralsina** [comment]
So, _prepare_task in the archive plugin is missing a whole lot of dependencies.
