### ISSUE TITLE
Final slash on urls with "nikola auto"

### ISSUE THREAD

**Issue by humitos** [getnikola/nikola#1933]
Hi, this issues is half "question" and half bug report :)

When I access to `http://localhost:8000/como-colaborar` (note no slash at the end) and I'm running `nikola auto` I get the option to download the file (on Firefox).

On the other hand, if I'm running `nikola serve` and I access the same url I see the proper page. I suppose that this is the proper behaviour, am I right?

I tried this in master.

**Comment by ralsina** [comment]
Yes, looks like a bug.

**Comment by humitos** [comment]
I think it's a good idea to "include" the final slash into the url because if you are using relative path in images, for example, they are not found by the server.

**Comment by Aeyoun** [comment]
#1922 should have worked around the relative path resolution issues here too, by the by.
