### ISSUE TITLE
Work around for installing ghp-import

### ISSUE THREAD

**Issue by disconsented** [getnikola/nikola#1934]
OS: Debian 8.1
Python Version: 3.4.2
https://gist.github.com/disconsented/f0b806ccec1f797ab829
As per the title how would I go about installing ghp-import or even skipping it would work fine
(https://github.com/davisp/ghp-import/issues/28 looks like this is my issue but the PR is open so I don't know what I can do)

**Comment by ralsina** [comment]
Don't install it and then instead of nikola github_deploy create a config that does the thing you needed with nikola deploy
