### ISSUE TITLE
Same images on multilanguage page

### ISSUE THREAD

**Issue by humitos** [getnikola/nikola#1936]
Hi all,

I have some page in Spanish and English and I'd like to use the same images for those pages. For example:

* Spanish: http://argentinaenpython.com.ar/donaciones/
* English: http://argentinaenpython.com.ar/en/donations/

But, in the English one the image is not showing up because it's not found on the server. I used to have this rule in my NGINX configuration:
```
    location / {
        root /home/humitos/apps/argentinaenpython.com.ar/;
        error_page 404 = @english_version;
        expires modified +1m;
        index index.html;
    }

    location @english_version {
        rewrite ^/en(/.*) $1 last;
    }
```

But, then I also translated the URLs so it's not working anymore. Any ideas?

**Comment by ralsina** [comment]
Sorry, I have no idea what that configuration does. If you can reproduce with ``nikola serve`` please rewrite, and provide what the paths and URLs are for the image and the post in bothlanguages.

**Comment by Aeyoun** [comment]
@humitos, append `/`to your your `<img src=/path>` and it will work on both pages.

**Comment by humitos** [comment]
@Aeyoun well, I'm not writing any `<img src="">` in my code. I'm just adding:
```
.. figure:: flyer.thumbnail.png
   :target: flyer.png

   Caption
```

and I have this folder structure:
```
/images/
  donaciones/
    colaboradores/
      flyer.png
```

and it tries to find: `/en/donations/collaborators/flyer.png` which is "correct" in some point because I translated the url to English but I want it to find in the same place that Spanish.

So, I wrote this NGINX rules to "fix" this, but I need one per url :(
```
    location / {
        root /home/humitos/apps/argentinaenpython.com.ar/;
        error_page 404 = @english_version;
        expires modified +1m;
        index index.html;
    }

    location @english_version {
        rewrite ^/en/our-zen/(.*) /nuestro-zen/$1 last;
        rewrite ^/en/donations/collaborators/(.*) /donaciones/colaboradores/$1 last;
        rewrite ^/en/donations/(.*) /donaciones/$1 last;
        rewrite ^/en/events/(.*) /eventos/$1 last;
    }
```

When a 404 occurs it tries the @english_version by rewriting the url. It looks like a mess, do you have any advice about this?

**Comment by ralsina** [comment]
@humitos why not use the whole path like this?

```
.. figure:: /images/foo/bar/whatver.png

```

If you use relative URLs then you get relative URLs and it's  not something we can ever fix because we'd have to be psychics :-)
