### ISSUE TITLE
 The `IPython.nbconvert` package has been deprecated.

### ISSUE THREAD

**Issue by ltiao** [getnikola/nikola#1938]
IPython 4.0 was just released (http://blog.jupyter.org/2015/08/12/first-release-of-jupyter/).  The `IPython.nbconvert` package has been deprecated. The [`nbconvert`-based ipynb compiler](https://github.com/getnikola/nikola/blob/15217bc93f0af0d70ffe33e0ea067d81ddf32403/nikola/plugins/compile/ipynb.py) should be updated where necessary to reflect any API changes in the 4.0 release.

**Comment by damianavila** [comment]
Yep... for now the shims in Jupyter should work OK, but we need to make the update. Thanks for opening the issue!!
