### ISSUE TITLE
srcset not respecting URL_TYPE option

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1939]
1. Set `URL_TYPE = 'rel_path'` (default)
2. Make a post with `<img srcset="/images/test_large.png 200w, /images/test_small.png 100w" src="/images/test_small.png">`

Expected:
`<img srcset="../images/test_large.png 200w, ../images/test_small.png 100w" src="../images/test_small.png">`

Actual:
`<img srcset="/images/test_large.png 200w, /images/test_small.png 100w" src="../images/test_small.png">`

**Comment by ralsina** [comment]
Is this the same as https://github.com/getnikola/nikola/issues/1626 ?

**Comment by ralsina** [comment]
Is srcset only used in img tags? If yes, it may be worthwhile to specialcase it.

**Comment by Aeyoun** [comment]
It can appear on `<img>` and `<source>` elements.
