### ISSUE TITLE
External Links in NAVIGATION_LINKS don't work

### ISSUE THREAD

**Issue by Cutuchiqueno** [getnikola/nikola#1951]
In the handbook it says:
> The NAVIGATION_LINKS option lets you define what links go in a sidebar or menu (depending on your theme) so you can link to important pages, or to other sites.

In my config I use external links in the way it described in the comments like this:

    NAVIGATION_LINKS = {
        DEFAULT_LANG: (
            ("/", "Blog"),
            ("/publications/", "Publications"),
            ("https://bbaw.academia.edu/NielsOliverWalkowski/", "Academia"),
            ("http://www.twitter.com/cutuchiqueno", "Twitter"),
            ("http://www.github.com/cutuchiqueno/", "GitHub"),
            ("/archive.html", "Archive"),
            ("/categories/", "Tags"),
            ("/rss.xml", "RSS feed"),
        ),
    }

However, all links are interpreted as relative links during compilation resulting in links like:

    http://nowalkowski.de/blog/http://www.twitter.com/cutuchiqueno

which of cause don't work.

What is going wrong here?

**Comment by ralsina** [comment]
Just checked, initialized an empty siteset this in conf.py:

```
NAVIGATION_LINKS = {
    DEFAULT_LANG: (
        ("http://twitter.com/ralsina", "Twitter"),
        ("/categories/index.html", "Tags"),
        ("/rss.xml", "RSS feed"),
    ),
}
```

It produces this:

```
<a href="http://twitter.com/ralsina">Twitter</a>
```

Can you tell me your nikola version?

**Comment by Kwpolska** [comment]
Is this visible in the HTML source, or does this happen only when you click
on a link?

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by Cutuchiqueno** [comment]
@ralsina Nikola version 7.6.2

@Kwpolska it is coded like this in the source `<li class="withripple" data-target="http://nowalkowski.de/blog/http://www.twitter.com/cutuchiqueno">Twitter<div class="ripple-wrapper"></div>`

is it possible that this behaviour is produced by the theme? The corresponding template section is:

                <nav  class="col-xs-3 menu">
                <ul>
                    {{ base.html_navigation_links() }}
                    {{ template_hooks['menu']() }}
                </ul>

                <ul class="nav navbar-nav">
                    {% block belowtitle %}
                    {% if translations|length > 1 %}
                        <li>{{ base.html_translations() }}</li>
                    {% endif %}
                    {% endblock %}
                    {{ template_hooks['menu_alt']() }}
                </ul>
            </nav>

**Comment by Kwpolska** [comment]
This is your theme's fault, but you need to show the html_navigation_links
definition in base_helper.tmpl. Your theme breaks all standards by using
some crazy JavaScript-based links (which is an awful thing to do). It also
seems to do something weird with links there, which makes no sense at all
(unless the JS "links" are complete garbage).

What theme is it?

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by Cutuchiqueno** [comment]
it's called "material-theme" and it's enlisted in the nikola theme page:

https://themes.getnikola.com/

thanks for the judgment, I will just change the theme then. I also found it kind of weired but since I am completely new to Nikola and have no experiences with jinja2 I didn't feel enabled to evaluate this.
