### ISSUE TITLE
Themes use blog_title | blog_title as title

### ISSUE THREAD

**Issue by jjconti** [getnikola/nikola#1952]
Themes (at least the 2 I tried) use "blog_title | blog_title" as title instead of (what I think would be better) "blog_title | blog_description".

**Comment by Kwpolska** [comment]
Try another page. To fix this, we would need a special case for index
pages, to display "blog_title", and that's if no special index title exists.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by Aeyoun** [comment]
I use this in my own theme:

    %if title == blog_title:
        <title>${blog_title|h} blog</title>
    %else:
        <title>${title|h} | ${blog_title|h}</title>
    %endif

Resulting in a front page titled “Aeyoun blog” and other pages “$title | Aeyoun”.

**Comment by ralsina** [comment]
Something like

```
%if title == blog_title:
    <title>${blog_title|h}</title>
%else:
    <title>${title|h} | ${blog_title|h}</title>
%endif
```

Should not be controversial.

**Comment by jjconti** [comment]
@humitos you should use it in your theme too!

**Comment by jjconti** [comment]
I'd use something like

    %if title == blog_title:
        <title>${blog_title|h} | ${blog_description|h}</title>
    %else:
        <title>${blog_title|h} | ${title|h}</title>
    %endif

Should it work?

**Comment by ralsina** [comment]
As long as blog_description is not huge, sure.

**Comment by Aeyoun** [comment]
Keep short names for the main title. It’s used for installable webapps and site-name identification by many systems. Long titles is bs, visitors just need something that can be used to identify a page/tab quickly..

**Comment by Aeyoun** [comment]
I’ll put this in the built-in themes.

**Comment by Aeyoun** [comment]
Not sure why I hadn’t upstreamed this already. Must have forgot, sorry about that.

**Comment by Aeyoun** [comment]
Commit 4dbfeae also changes default from stripping HTML tags to escaping them; preventing loss of data in titles and matching title-behaviors from elsewhere in Nikola.

**Comment by humitos** [comment]
@jjconti done! https://github.com/humitos/blog/commit/894a81d32294dfed285819c4ad27971fadd50e1e
