### ISSUE TITLE
Problems with bootstrap3

### ISSUE THREAD

**Issue by quijot** [getnikola/nikola#1953]
**Nikola v7.6.3** recently installed.
Did 

    $ nikola init --demo mysite
    $ cd mysite
    $ nikola auto

with default conf.py (THEME="bootstrap3"), but is not showing styles.
Installed any other theme (material-theme for example) and it worked just fine.
Then I build my old sites based on bootstrap3 and the same problem.
![2015-08-19--1439999977_1366x768_scrot](https://cloud.githubusercontent.com/assets/1616997/9361535/3511ce3c-4672-11e5-835e-824bda441ddd.png)

**Comment by Kwpolska** [comment]
What OS are you on? Is the CSS linked in the source? Do you get any errors
in the web inspector?

Also, could you put up a tarball of your site up somewhere? That would help
us debug.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by Aeyoun** [comment]
Do you open the output/index.html manually? or do you use the -b option with the auto command?

**Comment by quijot** [comment]
My mistake! I found the problem.

Default ``conf.py`` had ``SITE_URL="https://example.com/"`` so stylesheets where linked to https://example.com/assets/...
I edited ``conf.py`` and set ``BASE_URL`` to my output dir and problem solved.

I'm not used to set ``BASE_URL`` different from ``SITE_URL``. Until now, didn't understand well that difference.

Thank you!

**Comment by Aeyoun** [comment]
User error. :)

**Comment by Kwpolska** [comment]
You should just set `SITE_URL`, and leave `BASE_URL` commented out.  (BTW, is there any reason to keep the distinction?)

**Comment by quijot** [comment]
I did just that, which is the default conf that always worked, then opened the output/index.html manually (as I always did) instead of using the ``-b`` option, only this time something changed in Nikola between ``v7.5.1`` and ``v7.6.3``: ``<base href=...>`` tag was added inside the ``<head>`` tag of the bootstrap3 template, so stylesheets are linked in relation to that url.

If I just use the ``-b`` option it works well.

**Comment by ralsina** [comment]
@Aeyoun see previous comment. We forgot about the case of people just opening the files.

**Comment by Aeyoun** [comment]
The user is running a server via Nikola and still opening the files in their browsers manually. Isn’t serve and auto the intended mechanisms for viewing Nikola sites locally? Sites configured to use root-relative or absolute URLs will also fail when opened manually regardless of the base tag or not.

**Comment by ralsina** [comment]
Sure, we just may have to discourage it somehow.
