### ISSUE TITLE
Disable categories, tags, galleries, etc.

### ISSUE THREAD

**Issue by leonardder** [getnikola/nikola#1958]
I'm using Nikola primary for a simple website without a blog. I used the tutorial to create a site, not a blog, but still find it annoying that Nikola still renders posts, tags, categories, listings and galleries, which I don't use. It would be very helpful if we could disable those. Eventhough I don't use them, removing all those stuff from the output folder is slightly annoying. Thanks in advance!

**Comment by ralsina** [comment]
Check the DISABLED_PLUGINS option.

In any case, the gallery and listings plugins will do nothing if you delete galleries/ and listings/
