### ISSUE TITLE
Title overrides for tags and categories

### ISSUE THREAD

**Issue by leonardder** [getnikola/nikola#1962]
We can override the titles of index pages using INDEXES_TITLE. Also, we can set TAG_PAGES_DESCRIPTIONS and CATEGORY_PAGES_DESCRIPTIONS. It would be great if we could override the titles of certain tags and categories in a similar way TAG_PAGES_DESCRIPTIONS and CATEGORY_PAGES_DESCRIPTIONS work. In that way, it is much more easy to create multiple blogs on one site, using one category per blog, for example.

**Comment by Kwpolska** [comment]
Why not just name your tags and categories the way you want?!

Sounds like a feature that would not find a lot of use.  Please present a real use case.

**Comment by leonardder** [comment]
Of course I'd name my categories and tags the way I want, but their title is not just "TAG_Name", but "Posts about TAG_NAME". So, the part I'd like to get rid of is "Posts about "

**Comment by Kwpolska** [comment]
Sheesh, we hardcode that… reopening, I guess?

Then again, you could just use a messages file for an override, but that’s slightly hacky.

**Comment by leonardder** [comment]
That would require a hack for every single Nikola update, indeed. Though, the feature I propose might be somewhat overkill, if we could just change the title prefix, I can also live with that. However, defining the title for separate categories allows you to keep the "Posts about " prefix in tact for second level categories.

**Comment by Kwpolska** [comment]
Messages (translations) can be edited in a custom theme, without patching the Nikola source.  Still, that could be implemented.

**Comment by Kwpolska** [comment]
Done, turned out to be simple enough.
