### ISSUE TITLE
Import arbitrary web pages.

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1964]
There are conventions about where the "main content"of a page is.

A command could be created to use those conventions and get the "important" HTML out of a page and into a HTML input file for Nikola.

Yes, it will never be perfect, but it could work.

(Based on question by @jjconti in twitter)

**Comment by jjconti** [comment]
:+1:

**Comment by ralsina** [comment]
Using this it should be rather simple: https://github.com/datalib/libextract

**Comment by ralsina** [comment]
Implemented as a plugin.
