### ISSUE TITLE
Add AUTHOR_BIOS

### ISSUE THREAD

**Issue by da2x** [getnikola/nikola#1974]
Like TAG_PAGES_DESCRIPTIONS or use at the bottom of entries or on AUTHOR_PAGES.

**Comment by davidak** [comment]
I want my new website to have an authors bio under the articles, so this feature would be really helpful.

theme designers can integrate it like these examples: http://interactiveblend.com/2009/08/about-the-author/

@Aeyoun did you have started to work on this?

**Comment by Aeyoun** [comment]
No, I did not. But the idea was to structure AUTHOR_BIOS like TAG_PAGES_DESCRIPTIONS, but to stick it the global context. Websites would want to put author bios in all sorts of different pages (on author indexes, in posts, on dedicated pages listing each author, etc), so it must go in the global context.

**Comment by Kwpolska** [comment]
In the meantime, you can just add an `author_bios` dict to `GLOBAL_CONTEXT` in your conf.py and use it in your templates.

**Comment by ralsina** [comment]
So... does it make sense to implement this in core? 

It seems it would be, like described above, just a matter of changing templates, since there is nothing preventing anyone from adding things in GLOBAL_CONTEXT anyway.

**Comment by jidn** [comment]
I agree. This is a theme issue. The Jidn template has this feature. Take a look at http://jidn.com/blog/jidn-a-nikola-theme.  The one in the gallery doesn't show it as it needs changes in the default GLOBAL_CONTEXT.

Should we close this issue?

**Comment by Kwpolska** [comment]
Yeah, let’s close it, since nobody feels like doing this. (Implementing this on your own is pretty trivial.)
