### ISSUE TITLE
Nikola import_feed breaks with some URLs

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1976]
For example https://www.youtube.com/feeds/videos.xml\?user=juanjoconti 

It exposes 2 problems:

1) When calling it with that URL it fails to do anything, prints  help and dies
2) When the URL is downloaded and passed as a file, it explodes

Filing this here so I remember to do it soonish.

Things to fix:

- [x] Take URL in a --url=foo option to avoid bad processing of URLs with "=" in them
- [x] Fix usage of -o option (does nothing currently)
- [x] Don't crash on youtube feeds (they have no content)
- [ ] Handle enclosures

**Comment by ralsina** [comment]
This looks like a doit issue.

process_args finds the "=" in the URL and decides it's a ``name=value`` thing 

@schettino72 ?

**Comment by schettino72** [comment]
Yes doit can't handle `=` sign in parameters. Thats stupid... when I added this `doit` didnt support custom commands or positional parameter on tasks.

This `import_feed` is a command plugin, right?

I guess the correct solution (without breaking backward compatibility) would be to escape the `=`, but that would be extremely annoying to your use-case.

So I suggest just remove this feature for commands that do not collect tasks.
Or do you have any other suggestions?

**Comment by ralsina** [comment]
Yes it's a command. I don't understand the "remove this feature" part... which one?

**Comment by schettino72** [comment]
> I don't understand the "remove this feature" part... which one?

Sorry. I mean remove support for [doit.get_var](http://pydoit.org/task_args.html#command-line-variables-doit-get-var) on commands that do not load tasks.

**Comment by ralsina** [comment]
@schettino72 that's one way. Another is that if you only split on the first = I could document this to be url=foobar and then it would work, even if it's a bit unusual.

**Comment by schettino72** [comment]
If it is named parameter (not a positional argument), like `--url=foobar` it should work without any change.

**Comment by ralsina** [comment]
Even better. I'll do that.

**Comment by ralsina** [comment]
Marking this one as closed and opening a separate enhancement proposal for enclosures.
