### ISSUE TITLE
ask for creative commons licence on init

### ISSUE THREAD

**Issue by wcmckee** [getnikola/nikola#1977]
One feature I would like to see would be when you create a new site (nikola init), it asks if you want a creative commons licence and the ability to choose the licence you want (one of the six 4.0 licences).

**Comment by Aeyoun** [comment]
:-1:

All rights reserved is a good default. Teaching every potential new user about rights, licenses, and Creative Commons would be a significant mental overhead.

**Comment by Kwpolska** [comment]
:-1: from me. Especially if we make users make an actual choice, and have to explain the licenses.

There is an example in the config file, and users who want a CC license can always pick one.

**Comment by ralsina** [comment]
Ok, rejecting this idea. Maybe moving the license choice close to the top of conf.py?
