### ISSUE TITLE
Document categories / sections / tags

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1978]
- [x] clarify what the heck is going on and when to use what
- [ ] change tag documentation and conf.py to avoid using “categories”
- [ ] document categories used as site sections, complete with post storage
- [ ] implement overwritable short-names?

**Comment by fuzzy76** [comment]
Or atleast document sections :)

**Comment by ralsina** [comment]
I am not sure I understand sections well enough to document them :-P

**Comment by Kwpolska** [comment]
@Aeyoun, would you mind clarifying your ideas in the original post?

**Comment by Aeyoun** [comment]
I’m sure [this documentation]((https://www.slightfuture.com/devel/nikola-sections)) was copied over to some Nikola property, but I couldn’t find it again now. Does this cover it well enough?

**Comment by Kwpolska** [comment]
[It was](https://getnikola.com/blog/new-feature-in-nikola-sections.html). I wrote my own, building upon this and adding stuff for tags and categories. See PR #2487.
