### ISSUE TITLE
Indexes for POSTS subfolders

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1980]
Generate indexes (default) or lists for subfolders of POSTS. Treat them as categories, deprecate existing categories (which are just tags) in v8/9 timeframe. No additional metadata is needed along with the post, but rather reflect output folder as set in POSTS.

The following options will be introduced:

    POSTS_CATEGORIES = True
    POSTS_CATEGORY_ARE_INDEXES = True
    POSTS_CATEGORY_COLORS = { 'en': { 'pants': '#ff00ff' } }
    POSTS_CATEGORY_DESCRIPTION = { 'en': { 'pants': 'Excellent pant selection' } }
    POSTS_CATEGORY_FROM_META = False
    POSTS_CATEGORY_NAMES = { 'en': { 'pants': 'Pants and Trousers' } }
    POSTS_CATEGORY_TITLES = { 'en': { 'pants': 'Posts about Pants and Trousers' } }

In addition to the new category pages, each posts will be assigned with the following properties to facilitate category-oriented styling and functionality in templates and themes:

 * post.category_color()
 * post.category_link()
 * post.category_name()
 * post.category_slug()

Feature-creep: To facilitate automatic color assignment, an additional option will be added. I’ll also add a `<meta content=#ff00ff name=theme-color>` (consumed by many browsers and other systems). Ideally, this option will also be used to colorize themes based on user preference in the future.

    THEME-COLOR = '#ff00ff'

**Comment by Aeyoun** [comment]
What I’ve actually implemented in pull request #1981 seem to be closer to sections than categories. WordPress calls sections for categories, which was what got me confused. What I wanted were [sections and not categories](http://textpattern.com/faq/112/how-are-sections-and-categories-different). We can keep the old categories (even though they don’t make sense and just duplicates tags), and I could rename this feature SECTIONS.

@Kwpolska, @ralsina: thoughts? I’m fine with calling this feature categories as it does a more useful thing than the existing categories and the naming would be aligned with WordPress. But then we’d have to phase out the other category system sometime (v8). Or rename this section and go with naming comparable to TextPattern, MovableType, and news papers?

**Comment by ralsina** [comment]
I like the name sections. Categories is very poorly defined in general (which is what brought us here into this particular mess :-) so a clean name with a clear meaning is awesome to me.

**Comment by Kwpolska** [comment]
Let’s go with sections then, and categories will die in v8.

**Comment by Aeyoun** [comment]
Sections it is.

**Comment by Aeyoun** [comment]
Leaving the fallback name for sections as “Uncategorized” as “Unsectioned” sounds just silly.

**Comment by ralsina** [comment]
@Aeyoun sections are implemented, right? Is there anything of this Issue left to do?

**Comment by Aeyoun** [comment]
Nope.
