### ISSUE TITLE
New use case: personal feed aggregation + publishing

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1982]
This came to attention because of questions @jjconti was doing.

A user has some other means of creating content. He may review books at GoodReads, or curate tweet collections at Storify, or publish longform in Medium, etc.

OTOH, that user may want a centralized place where he can access all his own content, to share it with others or for archiving purposes.

Proposal:

* Refurbish the planetoid plugin to make it fit this use case
* Allow metadata retouching on importing. Example: all things from goodreads should go in the "Books" category, with "book, review" tags.
* Allow postprocessing of feed input: Maybe Storify should be scraped specially so that if it ever goes away we keep all the content in place.

This is a sort of novel feature AFAIK, and it makes Nikola more interesting as a personal  tool (I would use it!)

**Comment by jjconti** [comment]
Sadly Facebook and Twitter don't publish RSS of a user content, but we'll
find the way to scrap them.

2015-08-28 9:29 GMT-03:00 Roberto Alsina <notifications@github.com>:

> This came to attention because of questions @jjconti
> <https://github.com/jjconti> was doing.
>
> A user has some other means of creating content. He may review books at
> GoodReads, or curate tweet collections at Storify, or publish longform in
> Medium, etc.
>
> OTOH, that user may want a centralized place where he can access all his
> own content, to share it with others or for archiving purposes.
>
> Proposal:
>
>    - Refurbish the planetoid plugin to make it fit this use case
>    - Allow metadata retouching on importing. Example: all things from
>    goodreads should go in the "Books" category, with "book, review" tags.
>    - Allow postprocessing of feed input: Maybe Storify should be scraped
>    specially so that if it ever goes away we keep all the content in place.
>
> This is a sort of novel feature AFAIK, and it makes Nikola more
> interesting as a personal tool (I would use it!)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getnikola/nikola/issues/1982>.
>



-- 
Juanjo Conti
Mi primer novela ya se puede conseguir en:
http://www.juanjoconti.com.ar/xolopes

**Comment by Kwpolska** [comment]
Or make an extensible architecture that would take a Twitter/Facebook API plugin.

Scraping should never happen in this project.

**Comment by ralsina** [comment]
yes, scraping should be its own thing.

**Comment by ralsina** [comment]
@jjconti there's always a thing: https://twitrss.me/twitter_user_to_rss/?user=ralsina

**Comment by Aeyoun** [comment]
This is very interesting. A lot of services generate a RSS feed, but they all generate very different content. I can think of our main types of content:

* text (book reviews, post on other blogs, etc.)
* status updates
* microblogging
* photos/galleries

For microblogging (Weibo, Twitter, etc.) and status updates, they should probably aggregate days/weeks/number per page. Otherwise they’ll be a bit hard to consume, maybe?

**Comment by ralsina** [comment]
@Aeyoun I did not consider aggregation, but ... "maybe?" :-)

**Comment by Aeyoun** [comment]
Example of a blog/tweet/thing hybrid, http://tantek.com/

**Comment by jjconti** [comment]
When I thought in a Twitter import plugin, for importing OLD tweets, I
imagine an interactive console in which each tweet was shown and with a key
stroke I can tell: keep it or discard it.

2015-08-28 18:01 GMT-03:00 Roberto Alsina <notifications@github.com>:

> @Aeyoun <https://github.com/Aeyoun> I did not consider aggregation, but
> ... "maybe?" :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getnikola/nikola/issues/1982#issuecomment-135886870>.
>



-- 
Juanjo Conti
Mi primer novela ya se puede conseguir en:
http://www.juanjoconti.com.ar/xolopes

**Comment by ralsina** [comment]
I am doing something like this in #2229 ... if it looks significantly different, feel free to reopen this one.
