### ISSUE TITLE
nikola tabcompletion should be able to be ran outside a Nikola site

### ISSUE THREAD

**Issue by bricewge** [getnikola/nikola#1983]
Running `nikola tabcompletion --hardcode-tasks -s zsh` or `nikola tabcompletion` give me: `ERROR: Nikola: This command needs to run inside an existing Nikola site.`
I would like it to be run outside a Nikola site, however I'm not sure if it's possible. In my case would like to put the tab-completion files for bash and zsh in a package to avoid every user to do this by hand. Is it possible, or at least only when used with the `--hardcode-tasks` option?

**Comment by Kwpolska** [comment]
In order to support this, we would need to add an exception for this command. The command is provided by doit.

@schettino72, is `tabcompletion` functional without any tasks defined (only commands)?

**Comment by ralsina** [comment]
We can do it by inheriting that command class, probably. I'll take a shot at it now.

**Comment by bricewge** [comment]
Thanks @ralsina!
