### ISSUE TITLE
mathjax not rendering out of box

### ISSUE THREAD

**Issue by orsenthil** [getnikola/nikola#1984]
I setup nikola in a virtual env with python 2.7.9. My nikola version is

```
(nikola)[localhost ml (master)]$ nikola --version
Nikola v7.6.4
```

And if I have a math rendering code in my post (it is a restructured text) post.

```
.. math::

    100 C_{3} = (100 * 99 * 98) / (3 * 2 * 1) =  161700
````

The html output is displayed as 

```
\begin{equation*} 100 C_{3} = (100 * 99 * 98) / (3 * 2 * 1) = 161700 \end{equation*}
```

I expected the math to render it as I see mathjax is supported by default. I even tried adding a tag `%mathjax` to a the post( as suggested in this https://github.com/getnikola/nikola/pull/311), it did not help.

**Comment by Kwpolska** [comment]
There should be no `%` in the tag name, it’s just `mathjax`.

But it looks like something is broken, because our convoluted `mathjax.js` loader does not work.  @ralsina, do we really need this? Why aren’t we just using a normal script tag?

**Comment by ralsina** [comment]
I'm sure we had a good reason but I don't remember it.

**Comment by Kwpolska** [comment]
Let’s get rid of it then. If it breaks, we’ll come up with a solution.

**Comment by ralsina** [comment]
+1

**Comment by Jurramach** [comment]
So It was just the missing 'mathjax' tag what was failing. I thought it was my template.
