### ISSUE TITLE
nikola no longer has all-nocdn.*

### ISSUE THREAD

**Issue by StyXman** [getnikola/nikola#1992]
I started using `nikola` today for a gallery. The generated pages make reference to `all-nocdn.css` and `all-nocdn.js`, but they're not (longer?) part of `nikola`'s code:

```bash
mdione@diablo:~/src/projects/nikola$ git remote show origin
* remote origin
  Fetch URL: https://github.com/getnikola/nikola.git
  Push  URL: https://github.com/getnikola/nikola.git
  HEAD branch: master
mdione@diablo:~/src/projects/nikola$ git branch
* master
mdione@diablo:~/src/projects/nikola$ git pull
Already up-to-date.
mdione@diablo:~/src/projects/nikola$ find . -name all-nocdn.*
mdione@diablo:~/src/projects/nikola$
```

I just copied those files from and old attempt to use `nikola` and the site works. This happens with both versions `7.6.0-3` from Debian and from `master`, as you can see above.

**Comment by Kwpolska** [comment]
Nikola never had those files. They are generated on build, using webassets.
Do you get any errors about USE_BUNDLES and webassets missing?

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by ralsina** [comment]
OTOH, if we don't have webassets installed we should not be referring to those files...
