### ISSUE TITLE
Add support for cssminifier.com and javascript-minifier.com

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1999]
They offer a nice service to minify CSS/JS and it's easy to use.

**Comment by chilts** [comment]
Hey guys, thanks for using cssminifier.com and javascript-minifier.com. There is also jpgoptimiser.com, pngcrush.com and img-resize.com (all with APIs) if you'd like to use those too! :)

Cheers,
Andy (who runs all of the above)

**Comment by ralsina** [comment]
Hi @chilts ! I did not add those because I expect builds would be too slow using pngcrush, and we already have an image resizer :-)

Thanks for the nice service you run!

**Comment by ralsina** [comment]
Seems like this has a small problem with unicode files? When I minified [this file](https://getnikola.com/assets/css/all-nocdn.css) it caused m-dashes to break
