### ISSUE TITLE
Author pages show stories

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2007]
example: https://getnikola.com/authors/roberto-alsina.html → anything between 7.5.0 and 7.6.1 (most of which were written by me, but that’s not important)

cc @jjconti

**Comment by ralsina** [comment]
The wrong author is because I am the default :-) Changing it to "The Nikola Team".

**Comment by ralsina** [comment]
Now, go to https://getnikola.com/authors/the-nikola-team.html to see the bug

**Comment by Kwpolska** [comment]
I’d rather keep the default author as “Roberto Alsina” and overwrite the pages.  Most of the posts are actually written by you, and you should get credit.

**Comment by ralsina** [comment]
Hey, I am part of the team. If I want to keep credit I will add me ;-)

**Comment by Kwpolska** [comment]
You really **should** get credit. I’ll change the default back and fix the pages.

**Comment by ralsina** [comment]
COMMIT WAR! SHINY AND CHROME! My name is already everywhere in the sources even for files I never touched :-D

**Comment by Kwpolska** [comment]
I really believe in credit where it’s due. This project would not exist without you.

(And there are files without your name AFAIK)
