### ISSUE TITLE
Create a central state file

### ISSUE THREAD

**Issue by jjconti** [getnikola/nikola#2009]
Some plugins may want to preserve state from one run to the next. In those cases, we should provide a reliable, standard place to put it.

Format?

Add to Nikola class save_sate, get_state
key (string) / value (jsonable)

Criteria:

- [ ] Produces nice diffs when changed
- [ ] Readable.
- [ ] Not as important: writable
- [ ] Reasonably efficient

**Comment by Kwpolska** [comment]
`cache/my_fancy_plugin.txt` is much easier

**Comment by ralsina** [comment]
But you are supposed to consider caches transient, this is the opposite of transient.

I want this to be a specific, fixed place, so that you can version it, and when you restore your site from the repo in another machine the state is kept.

**Comment by jjconti** [comment]
I vote for Yaml.

**Comment by Kwpolska** [comment]
I vote for no new external dependencies, and that includes yaml.  The format should be computer-readable and not necessarily human-readable — json is enough.

**Comment by Aeyoun** [comment]
Cache should only be recreatable data. Users shouldn’t loose anything by deleting it, and now we’re loosing states. I’ve got lastdeploy, lastping, and lastiarchive which just contains the date of their last execution. Are there other states we need to preserve than timestamps?

**Comment by ralsina** [comment]
@Aeyoun If we provide the feature, we surely will. For example, planetoid would use it.

**Comment by SpotlightKid** [comment]
I think there should be a distinction between saving state and caching things that are costly to obtain, but can be recalculated / retrieved easily.

E.g. the media plugin, AFAICS, uses micawber to retrieve media metadata / embedding code via HTTP requests. A possible optimization would be to save the retrieved data between runs, keyed by media url. That would speed up successive runs, but deleting the cache is ok.

It would be nice to have an API for plugins to make this kind of caching easy. E.g. just two functions, which receive/return a dictionary of values to cache. The internals of where in in which format the cache is stored shouldn't be important to the plugin.

**Comment by ralsina** [comment]
@SpotlightKid ok, adding #2209 for the specific case of data that *can* be deleted and lives in cache/

**Comment by ralsina** [comment]
This is in master.
