### ISSUE TITLE
Wordpress allows case insensitive tags. nikola breaks when it tries to build them

### ISSUE THREAD

**Issue by orsenthil** [getnikola/nikola#2014]
I had `books` as well as `Books` in my tags and nikola frequently kept crashing while building the site.

**Comment by ralsina** [comment]
What version of Nikola?

Was the crash when importing the wordpress data, or when building the site after it was imported?

**Comment by orsenthil** [comment]
7.7.0 and on master.
This was after the import and when building the site.

**Comment by ralsina** [comment]
Can you show me the error? Usually it should not crash but tell you that you have two tags that produce the same slug and ask you to change them :)

**Comment by ralsina** [comment]
@orsenthil this is what I get with two posts where tags differ only in case:

```
$ nikola build
Scanning posts....[2015-09-04T14:40:56Z] ERROR: Nikola: You have tags that are too similar: bar and Bar
[2015-09-04T14:40:56Z] ERROR: Nikola: Tag bar is used in: posts/foo.rst
[2015-09-04T14:40:56Z] ERROR: Nikola: Tag Bar is used in: posts/foo2.rst
done!
```

**Comment by orsenthil** [comment]
Yes, this is the error.

```
(nikola)[localhost new_site (wordpress_import)]$ nikola build
Scanning posts........[2015-09-05T06:03:47Z] ERROR: Nikola: You have tags that are too similar: Books and books
[2015-09-05T06:03:47Z] ERROR: Nikola: Tag Books is used in: posts/2013/03/10/book-review-the-startup-of-you.md
[2015-09-05T06:03:47Z] ERROR: Nikola: Tag books is used in: posts/2007/02/22/recent-books.md, posts/2007/12/31/books-i-could-read-this-year.md, posts/2008/12/13/the-agony-and-the-ecstasy.md, posts/2010/10/09/the-pleasures-and-sorrows-of-work-amazon-book-link.md
[2015-09-05T06:03:47Z] ERROR: Nikola: You have tags that are too similar: incredibles and Incredibles
[2015-09-05T06:03:47Z] ERROR: Nikola: Tag incredibles is used in: posts/2014/06/20/the-incredibles-bill-and-melida-gates-on-humanity.md
[2015-09-05T06:03:47Z] ERROR: Nikola: Tag Incredibles is used in: posts/2013/06/09/the-incredibles-1.md, posts/2014/02/11/codex-leicester.md
[2015-09-05T06:03:47Z] ERROR: Nikola: You have tags that are too similar: Minecraft and minecraft
[2015-09-05T06:03:47Z] ERROR: Nikola: Tag Minecraft is used in: posts/2014/06/23/madurai-meenakshi-temple-in-minecraft-next-step-north-tower.md
[2015-09-05T06:03:47Z] ERROR: Nikola: Tag minecraft is used in: posts/2013/07/08/my-three-wishes-for-minecraft.md, posts/2014/06/23/madurai-meenakshi-temple-in-minecraft-next-step-north-tower.md
done!
(nikola)[localhost new_site (wordpress_import)]$ ls output
assets/
```

**Comment by Kwpolska** [comment]
Then I’m afraid we can’t really help. This is an information for you, the site author, that you should manually clean up your posts to use only one way to capitalize your tags.  We can’t really automate the cleanups, and a wizard would not be of much help.

**Comment by orsenthil** [comment]
I acknowledge your point. Given the friendliness of Nikola,  can't this be handled transparently by nikola? why not go a step beyond and lower case all tags and build? As I stated at the start of my bug, this is from activate wordpress export, which allowed this kind of thing.

**Comment by felixfontein** [comment]
Lower casing all tags sounds like a terrible default choice. I'd rather consider it a bug of WordPress to allow different spellings of the same tags. We could add an option to the WordPress importer to apply such a conversion (everthing to lower case, or ask for a normal form per tag if two different forms are detected), though.

**Comment by orsenthil** [comment]
Asking for normal form if you different cases are detected sounds like a helpful thing to do. I tried to normalize in wordpress and it was not possible for me.  I did a sed and went ahead with the import. Asking a normal form seems like a good idea.

**Comment by ralsina** [comment]
I wonder if the tags plugin would help here:

https://plugins.getnikola.com/#tags

Specifically:

```
--merge=ARG               Merges a list of comma-separated tags, replacing them with the last tag
                           Requires a list of file names to be passed as arguments.
                               $ nikola tags --merge "foo,bar,baz,useless" posts/*.rst
                           The above command will replace foo, bar, and baz with 'useless'
                           in all rst posts.
```

I have not tested it and it's perfectly likely that it will refuse to start because of the tag collision but maybe worth trying and see if we can adapt it to a fix.

**Comment by felixfontein** [comment]
If it doesn't work, one can also do this by hand. Assuming you only use `.meta` files, the following Python code crawls through all posts and stories, reads the `.meta` files, allows to modify the tags, and writes them back:
``` .py
#!/usr/bin/python
import io
import os
import nikola.post
import nikola.utils

folders = ['posts', 'stories']

for folder in folders:
    for root, dirs, files in os.walk(folder):
        for file in files:
            if file.endswith('.meta'):
                fn = os.path.join(root, file)
                data, ok = nikola.post.get_metadata_from_meta_file(fn)
                if ok:
                    tags = [f.strip() for f in data.get('tags', '').split(',') if f.strip()]
                    ...
                    data['tags'] = ','.join(tags)
                    data_str = nikola.utils.write_metadata(data)
                    with io.open(fn, "w+", encoding="utf8") as fd:
                        fd.write(data_str)
                else:
                    print("Loading {0} failed!".format(fn))
```
(Wrote that recently for some other quick hack.)

**Comment by felixfontein** [comment]
Ok, I implemented a basic tag sanitizing option. It simply takes the first case spelling it finds (or optionally converts everything to lowercase).

**Comment by felixfontein** [comment]
(It also handles categories, BTW.)

**Comment by ralsina** [comment]
Fixed by #2034

**Comment by orsenthil** [comment]
@felixfontein thanks for addressing this.
I feel it is worth raising these usability improvements against nikola.

**Comment by ralsina** [comment]
@orsenthil it sure is!
