### ISSUE TITLE
conf.py documentation for LISTINGS_FOLDERS assumes user knows what LISTINGS are

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#2018]
… yeah, what are listings anyway? Read through the section now and thought I’d fix it. But I couldn’t really explain what it was as I don’t know myself.

**Comment by Kwpolska** [comment]
https://en.wikipedia.org/wiki/Listing_(computer)

Listings are also documented [badly](https://getnikola.com/handbook.html#listing) in the handbook.
