### ISSUE TITLE
Overwrite `LocaleBorg.get_month_name` for custom locale?

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#2029]
When trying to use Nikola for a custom locale which Python doesn't know (say, for a phantasy language or for some local dialect), one can fix most translations by translating `messages_en.py`. Unfortunately, fixing the month names for the archives is not possible (AFAIK), because they are generated by `LocaleBorg.get_month_name`, which uses Python functions which don't know about the custom locale.
How should it be possible to fix this? How about being able to specify the month name translations in `messages_XXX.py`? Or is this already somehow possible with some Python magic?

**Comment by Kwpolska** [comment]
You would have to modify the `calendar` module pretty heavily. We rely on the operating system for locales, and I doubt we will be able to/willing to change that.

**Comment by felixfontein** [comment]
How about a possibility to implement some calendar-related functions with a plugin?

**Comment by felixfontein** [comment]
Another somewhat related thing is that I'd like `DATE_FORMAT` to be translatable. I for example use `'%B %d, %Y at %H:%M'` in one blog, which of course only works in english. Also for some languages/locales you want year/month/day in a different order than in others, so being able to specify a different `DATE_FORMAT` per language would be good.

**Comment by Aeyoun** [comment]
IMHO, use ISO‐8601 everywhere [all the time for all locales](https://www.aeyoun.com/webdev/date-formats-web.html). Though of course not everyone agrees in this utilitarian approach, so localizeable DATE_FORMAT is something that should be supported.

**Comment by Kwpolska** [comment]
Open a separate issue for localizing `DATE_FORMAT` (or even implement it yourself, it would take ~5 lines)

**Comment by felixfontein** [comment]
I'll do that.

**Comment by felixfontein** [comment]
Ok, I looked a bit more in detail at what's happening. There are essentially two methods to print date/time related things:
 * calling `post.formatted_date(format)`;
 * asking for a month's name in the archive plugin (via `LocaleBorg`).
(Well, and there's date/time formatting in JavaScript via `JS_DATE_FORMAT`, but that's not in Nikola's hands, so let's ignore it.)

How about:
  1) making `formatted_date` a method of `LocaleBorg`, so that it is responsible for all date/time related formatting;
  2) allowing to add locale date/time handlers to `LocaleBorg` (for example by plugins, they could do that during `set_site()`) which are asked to handle month name resolution or date/time formatting for the languages they advertise (and if they don't want to, ask next handler and finally resolve to Python functions).

This makes it possible to write plugins which improve/handle a certain special locale without introducting too much infrastructure for it. What do you think? Especially @Kwpolska and @ralsina :)

**Comment by ralsina** [comment]
LGTM, should work.
