### ISSUE TITLE
Add a page with import sources

### ISSUE THREAD

**Issue by jjconti** [getnikola/nikola#2035]
Add to the main site a page listing different import sources: wordpress, tumblr, goodreads, etc...

**Comment by Kwpolska** [comment]
An entry in `/features/index.html` should be good enough.

[Suggest a good icon](https://fortawesome.github.io/Font-Awesome/icons/). (`wordpress` is not good.)

**Comment by ralsina** [comment]
http://fortawesome.github.io/Font-Awesome/icon/cart-arrow-down/ for "bring your stuff like a homeless person"?

**Comment by ralsina** [comment]
More seriously: http://fortawesome.github.io/Font-Awesome/icon/cloud-download/

**Comment by Kwpolska** [comment]
https://getnikola.com/features/#importers
