### ISSUE TITLE
Maybe use versioneye to handle both python and JS version checking?

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2038]
https://www.versioneye.com/

**Comment by Kwpolska** [comment]
For Python, requires.io is awesome. (I get the e-mails, you could set it up for yourself too). And for JS, we just run `bower update` on every release, and it works well enough.

**Comment by ralsina** [comment]
Ok, closing. My main concern was precisely that we update via bower when we release, which should lead to us eventually shipping something totally broken because of a new JQuery or whatever.
