### ISSUE TITLE
Improved tag support / refactoring of tag handling and tag plugin.

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#2039]
For my blog, I wanted to add a new kind of tags called places: each post can not just have tags (and a category), but also places. Places are between tags and categories: they have a hierarchy (like switzerland is a subtag of europe, and zürich a subtag of switzerland) similar to categories, and there can be more than one place per post. So I cannot just "solve" this by using existing tags or categories (besides the fact that I want to have them separate from both).

While thinking on how to add this in a good way (in particular: without too much code repetition), I decided to put a system in place where tags and categories are just a special case of. To implement this without modifying current Nikola, I added two plugins and disabled the default `tags` plugin. The first plugin hooks into the post scanning process (with signals) and, similar to the existing tags and category code in `nikola.py`, goes through all posts and sets up some useful data structures (with posts per tag, sorted by language, etc.). This plugin also reads a configuration, which describes the types of tags (by default, "tag" and "category" which behave as before). The second plugin is a direct replacement for the `tags` plugin (and borrows a lot of code from it), it renders the tag indices and the tag overview pages.

The default plugin config looks like this:
``` .py
{
    'tag': {
        'pluralname': 'tags',
        'sources': [{'identifier': 'tags', 'can_specify_multiple': True}],
        'path': self.site.config.get('TAG_PATH', 'categories'),
        'prefix': '',
        'pages_are_indices': self.site.config.get('TAG_PAGES_ARE_INDEXES', False),
        'slug_paths': self.site.config.get('SLUG_TAG_PATH', True),
        'descriptions': self.site.config.get('TAG_PAGES_DESCRIPTIONS', {}),  # translatable
        'titles': self.site.config.get('TAG_PAGES_TITLES', {}),  # translatable
        'ignore': ['draft', 'retired', 'private'],
        'hidden': self.site.config.get('HIDDEN_TAGS', ['mathjax']),
        'list_minimum_posts': self.site.config.get('TAGLIST_MINIMUM_POSTS', 1),
        'has_hierarchy': False,
        'output_flat_hierarchy': False,
        'tag_cloud_path': 'assets/js/tag_cloud_data.json' if self.site.config.get('WRITE_TAG_CLOUD', True) else None,
    },
    'category': {
        'pluralname': 'categories',
        'sources': [{'identifier': 'category', 'can_specify_multiple': False}],
        'path': self.site.config.get('CATEGORY_PATH', 'categories'),
        'prefix': self.site.config.get('CATEGORY_PREFIX', 'cat_'),
        'pages_are_indices': self.site.config.get('CATEGORY_PAGES_ARE_INDEXES', False),
        'slug_paths': self.site.config.get('SLUG_TAG_PATH', True),
        'descriptions': self.site.config.get('CATEGORY_PAGES_DESCRIPTIONS', {}),  # translatable
        'titles': self.site.config.get('CATEGORY_PAGES_TITLES', {}),  # translatable
        'ignore': [],
        'hidden': self.site.config.get('HIDDEN_CATEGORIES', []),
        'list_minimum_posts': 1,
        'has_hierarchy': self.site.config.get('CATEGORY_ALLOW_HIERARCHIES', False),
        'output_flat_hierarchy': self.site.config.get('CATEGORY_OUTPUT_FLAT_HIERARCHY', False),
        'tag_cloud_path': None,
    }
}
```
I added support to my blog for places by adding
```
    'place': {
        'pluralname': 'places',
        'sources': [{'identifier': 'places', 'can_specify_multiple': True}],
        'path': {'en': 'place', 'chde': 'ort'},
        'prefix': '',
        'pages_are_indices': True,
        'slug_paths': True,
        'descriptions': {},  # translatable
        'titles': {},  # translatable
        'ignore': [],
        'hidden': [],
        'list_minimum_posts': 1,
        'has_hierarchy': True,
        'output_flat_hierarchy': False,
        'tag_cloud_path': None,
        'tag_page_list_template': 'place.tmpl',
        'tag_page_index_template': 'placeindex.tmpl',
    },
```
and modifying my theme to display the tags. Now I can write
```
places: europe/switzerland/zürich, north america/canada/toronto
```
in a post `.meta` file, and under the post, something like `places: toronto, zürich` is displayed, and `https://my.blog/place/` yields the hierarchy of places. (Also, I can simply allow multiple categories per post by modifying the category config. That's something I wanted to do for a long time anyway, and also something which will probably never find its way into mainstream Nikola.)

The source code of the plugins can be found here: https://gist.github.com/felixfontein/38468f5d34cedd5148e6

Now: how about including something like this in core Nikola? I.e. making the tags/category handling much more flexible, so that users could easily (well, with some work modifying their themes) add their own types of tags?
This would simplify some code in the sense that the distinction between tags and categories falls away (instead there are tag types, but working with them is spreading the logic of what the difference is to less places). Deprecating categories could also be done more easily with something like this (see #1980), and in particular it will allow some people to continue using categories in the future even when they aren't enabled by default anymore. Also, it would fix #1924 as a side-effect :)

What do you think?

**Comment by Kwpolska** [comment]
Bullshit.

This is utterly complicated, a worthless addition and something a few people would use.  We’re phasing categories out, BTW.

:-1: and voting for *wontfix*

**Comment by ralsina** [comment]
If you want to put this in the plugins repo, sure, but it looks a lot like a feature only you would use, and adding those is a mistake I would want to avoid repeating (I still feel karma-bound to fix bugs on things I added "because they were neat")

**Comment by felixfontein** [comment]
Yes, you are probably right about almost nobody (but me) using it. If I find time I'll polish it to a proper plugin, otherwise it will keep living in my personal plugins folder...
