### ISSUE TITLE
indexes plugin results in exception if index link is created too early.

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#2040]
The `indexes` plugin needs `self.number_of_pages` and `self.number_of_pages_section` to be initialized for its path handlers to work. If some other task plugin tries to create a link to a (section) index before `gen_tasks()` of the `indexes` plugins is called, it will raise an exception.

**Comment by ralsina** [comment]
Can you create steps to reproduce? I can take a look at fixing it.

**Comment by felixfontein** [comment]
It is prominently visible in the `earlytask_impl` branch, as soon as you tell nikola to build only certain tasks (instead of all). Since every plugin's tasks are only generated when they are about to be executed, the `indexes` tasks can easily not be generated when some other tasks are executed.

It is also possible to reproduce this with current, Nikola, though: if you write a task plugin which tries to generate a link during its task creation might or might not work: it depends on whether that plugin is called before or after the `indexes` plugin to generate its tasks.

Actually, changing the `indexes` plugin so that it can generate links to the (section) index at any time, but to specific pages only after its tasks have been generated, is totally fine (since almost nobody outside the `indexes` plugin is using that feature).

**Comment by felixfontein** [comment]
When looking at the code I realized it is quite simple to fix. Just tried it :)
