### ISSUE TITLE
Jinja-based themes missing JavaScript

### ISSUE THREAD

**Issue by samatjain** [getnikola/nikola#2041]
Jinja-based themes are not including JavaScript files (bundled or unbundled) on build.

As per discussion on IRC, in master (as of b0e9b644a981405738ee0dca6b2f04d36cae18db), base.late_load_js() is not called in jinja-based themes (I tested bootstrap3-jinja). Mako-based themes (I tested bootstrap and bootstrap3) work fine.

**Comment by ralsina** [comment]
If USE_BUNDLES is set to False, this shows much more clearly that all the macros in base_helper.tmpl are not working

**Comment by ralsina** [comment]
So, all this was caused by https://github.com/getnikola/nikola/commit/a6cc45c83b8e580e6c513db3552db2fb24d5ba8e ... reverting!

**Comment by ralsina** [comment]
Reverted :-(
