### ISSUE TITLE
post.translated_to is wrong in one corner case

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2042]
While using the upgrade_metadata plugin, noticed this:

If a post has metadata in more than one language, but text in only one language, translated_to only lists the languages for the text.

I'll see if this is a real bug or just doesn't matter.

**Comment by ralsina** [comment]
I worked around it in upgrade_metadata and it doesn't seem to break anything... I'd leave it as is until we have a reason to fix it, because I fear more the side effects of the fix than the bug itself.

**Comment by Kwpolska** [comment]
This sounds like a *user error* type of bug.

**Comment by ralsina** [comment]
@Kwpolska Why? If a post is just a photo with no text, it makes sense to translate only the title.

**Comment by Kwpolska** [comment]
that’s an use case too, you’re right

**Comment by ralsina** [comment]
In any case, if this is a bug it's not causing any harm at this point. Closing.
