### ISSUE TITLE
Assets provided by plugins are ignored by nikola auto

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2044]
For example, localsearch has CSS and JS that is inside the plugin, and are copied by a task. If you edit those, auto rebuild is not triggered.

Possible solutions:

1. Just watch the plugins folder. Also triggers rebuild if the plugin changes but who cares?
2. Have plugins optionally register paths for watching but this gets complicated very fast

I'd say 1?

**Comment by Kwpolska** [comment]
> Just watch the plugins folder. Also triggers rebuild if the plugin changes but who cares?

Don’t/didn’t we rebuild on Nikola code changes before?  Most people would actually consider this a nice touch.

**Comment by ralsina** [comment]
@Kwpolska We used to, when livereload. Wonder if it still happens... no, doesn't happen anymore. I'll make it watch plugins and ~/.nikola/plugins
