### ISSUE TITLE
Problems when using parallel processing with threads and multiple languages

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#2046]
There's a problem with Nikola if your site has more than one language and if you use `nikola run -n4 -P thread` (run four tasks in parallel using threads instead of forking, see here: http://pydoit.org/cmd_run.html#parallel-execution). Namely, when rendering a page/..., `LocaleBorg` is storing the current language in global storage which is then used by `messages("...")` and `formatted_date()` (among others). When two tasks run in parallel for two different languages, one will overwrite the `LocaleBorg` setup of the other, and with high probability one of the output files ends up with wrong strings or wrongly formatted dates.
(When using forking, this should not be a problem, but that doesn't always work -- it might be problematic under Windows, and totally breaks for the `earlytask_impl` branch.)

I don't know how easy/complicated fixing this would be. There are two aspects:

  1. If we store the current language not in a global state, but a thread-local state, at least `messages("...")` will always use the correct language.

  2. This might not help for `formatted_date` and `get_month_name`, since they have to set the correct locale and then call some Python system function -- Python might not store the locale thread-local, but global. (Or does it store it thread-local? If that is guaranteed for both Python 2 and 3, using thread-local storage would be enough.) But this could be solved by using a global lock which avoids that `formatted_date` and `get_month_name` run in parallel.

What do yout think? While standard Nikola not run in parallel mode is totally not affected by this (and after all we don't advertise that you can run several tasks in parallel), I think that making Nikola more thread-safe is always a good idea.

**Comment by Kwpolska** [comment]
3\. drop parallelization

**Comment by ralsina** [comment]
Since it seems to be only localborg-related we could drop parallelization if there's more than 1 language.

**Comment by felixfontein** [comment]
Automatically dropping parallelization or at least printing a strong warning would be good.

**Comment by felixfontein** [comment]
Hmm, how about adding a optional argument `lang` to the `formatted_date`s, which if set changes the locale and later resets it to the previous value?
This would also allow `formatted_date` handlers to get the correct language when it is specified, and not having to rely that `LocaleBorg().current_lang` is correct. I think I could modify my theme to be on the thread-safe side with this change (since all locale-dependent date rendering is done via handlers anyway, in my case). And this is a rather small and simple change, as opposed to adding thread-local storage etc.

**Comment by ralsina** [comment]
@felixfontein there are a lot of things where lang is optional and guessed from LocaleBorg (most templates, for one thing)

**Comment by ralsina** [comment]
@felixfontein just curious, you see this problem both with threads and multiprocessing?

**Comment by felixfontein** [comment]
I now looked at it in more detail. For `tags`, `prev_post`, `next_post` (of `Post`) and `formatted_date` (of `Post` and `LocaleBorg`) it is not possible to provide the current language; for all other calls, one can provide `lang`.
I can modify my templates to provide `lang` whenever needed (I already did so for all `messages()` calls in them), but of course I can only do that if I *can* specify `lang`.

Do you mind if I start a WIP branch where I try to allow specifying `lang` everywhere (mostly for the four above properties/functions) in a backwards-compatible way? Or possibly even modify the default themes to provide `lang` as often as possible, so that the dependency on `LocaleBorg().current_lang` is minimized? Or does this has no chance of being included in Nikola?

**Comment by felixfontein** [comment]
(Rebuilding all `.html` files of my blog single-threaded currently takes almost 12 minutes. I'd be really happy to have some parallelization back, even if I have to invest quite some work to make my theme thread-safe.)

**Comment by ralsina** [comment]
@felixfontein are you using -n N ? In that case those are not threads.

**Comment by felixfontein** [comment]
The `earlytask_impl` branch has to use threads (instead of forking) as pickling the task creation functions fails.

**Comment by ralsina** [comment]
If you try that using master and processes, does it work?

**Comment by felixfontein** [comment]
What do you mean with master and processes?

**Comment by ralsina** [comment]
Using the master branch, not earlytasks, and parallelizing using processes, not threads.

**Comment by felixfontein** [comment]
Hmm, I have to try that another time. It'll take some preparations to be able to efficiently check for failures. (I don't want to check all > 5000 HTML files manually for wrong strings etc.) Maybe I'll manage to do that tomorrow...

**Comment by ralsina** [comment]
Thanks, if you can do that it would really help me a lot :-)

**Comment by felixfontein** [comment]
Ok, I did two runs with master branch and processes instead threads, and it seemed to have worked fine. (Output was binary identical to single threaded.) Takes a bit less than 6 minutes. (I used `-n 4` and `-n 8`, but this laptop only has two cores anyway.) When using the master branch with threads instead of processes, it took a bit longer (roughtly 8 1/2 minutes) and produced incorrect output (461 lines of diff output).

**Comment by ralsina** [comment]
@felixfontein so, it seems to me it's just a matter of making LocaleBorg thread-local. It's a fix in a single place, so it should not be horribly hard to do?

**Comment by felixfontein** [comment]
Yes, using thread-local storage is a good way. But we also need to make sure that the locale is always set before calling date-related functions, and that no other date-related function in executed at the same time. But since they are all in `LocaleBorg` as well (I hope?), this shouldn't be a problem either.

**Comment by ralsina** [comment]
Exactly. Locale is always set, and within a thread everything is sequential, so each task sets the locale, does its thing and dies. So if it's thread-local it *should* work.

**Comment by felixfontein** [comment]
Except that `formatted_date` currently doesn't ensure that the locale is set (again). But that's trivial to change ;-)

Should I start working on that?

**Comment by ralsina** [comment]
By all means! Thanks!

**Comment by felixfontein** [comment]
Works like a charm. (Except the atom feeds, but that's a bug in the atom feed renderer. I'll take care of that later.)
