### ISSUE TITLE
Google + comment support appears to be deprecated.

### ISSUE THREAD

**Issue by stevedrees** [getnikola/nikola#2048]
In https://getnikola.com/handbook.html in the sidebar "COMMENT_SYSTEM_ID" there is a link to "verify your authorship" for the Google + Comment system. That link leads to a page at google that says authorship is no longer supported.

**Comment by ralsina** [comment]
Without the authorship verification, the form appears in localhost, but doesn't work. That may mean it needs to run on a live server.

**Comment by stevedrees** [comment]
After testing on a live server 'googleplus' commenting works as advertised.

**Comment by ralsina** [comment]
Awesome, I'll correct the docs.

**Comment by Kwpolska** [comment]
I can’t find any G+ Comments docs anymore…
