### ISSUE TITLE
Adding some features to right-to-left languages for section-numbering

### ISSUE THREAD

**Issue by yoosofan** [getnikola/nikola#2050]
1- "section-numbering" always produces left to right numbering while in right to left languages like Farsi, Arabic, Urdu, and Hebrew the order of numbers must be reversed. The digits of numbers have the same position as in English. They are left to right. But the order of parts must be reversed  For example:

English: (left to right)
2.4 Chapter two, section four

Farsi: (right to left)
&#x202b;   2.4 chapter four,  section two
&#x202b;   ۲.۴ فصل چهارم  ,  بخش دوم  

English: (left to right)
2.4.12 Chapter two, section four, subsection twelve

Farsi: (right to left)
&#x202b;   2.4.12 chapter twelve,   section four,  subsection two
&#x202b;   ۲.۴.۱۲ فصل دوازدهم  ,  بخش چهارم  , زیربخش دوم  

Section-numbering does their job well when we use only one level numbering:

English: (left to right)
12 Chapter twelve

Farsi: (right to left)
&#x202b;   12 chapter twelve
&#x202b;   ۱۲ فصل دوازدهم     

---

2- Changing prefix and suffix is possible in "section-numbering", but there is no way to change middle character Dot or point ( . ). Adding "middle" tag to change middle character is helpful.

.. section-numbering::  :suffix: -  :middle: -

2-4-1-

**Comment by ralsina** [comment]
I am not at all aware of how to help with this. Are you using reStructured text?

**Comment by yoosofan** [comment]
Yes, I use rst in my website (http://yoosofan.kashanu.ac.ir) but here in github I haven't find a way to write rst in comments. For example see numbers in `<http://yoosofan.kashanu.ac.ir/semester/941.html>`_ . This page is in Farsi but please focus only on numbering from right to left.

**Comment by ralsina** [comment]
I'm afraid I don't know enough farsi to even notice the numbers except by memorizing them :-)

Maybe this will help?

http://docutils.sourceforge.net/FAQ.html#can-i-produce-documents-in-right-to-left-languages

**Comment by yoosofan** [comment]
Thank you for your prompt reply.
Yes, I saw that link before. I think it is hard to deal with this problem with anyone unless who uses right to left languages. It hasn't even solved in OpenOffice yet. I hope, I have had enough time and expertise in Nikola developing to solve this issue.

**Comment by ralsina** [comment]
Awesome, I'm happy to help as far as I can :-)

You may also want to mention this in the mailing list. There are a few RTL sites done using Nikola (I recall a Hebrew one at least and one or more Farsi ones, maybe one was yours)

**Comment by yoosofan** [comment]
An email is sent to mailing list. Thank you.

**Comment by ralsina** [comment]
Just FYI don't feel that the "whenever" milestone decreases the importance of this, it only means I have no clear idea of how long it will take to improve this.

**Comment by Kwpolska** [comment]
Isn’t section numbering provided by reST/docutils, wouldn’t they be responsible?

**Comment by yoosofan** [comment]
Thanks ralsina for your informative comment.
Kwpolska, you are right about the second issue ( :middle: tag) because it depends on standard of reST writing. I sent this issue to Docutils-users mailing list. But they hasn't sent me reply, approval or reject yet. On the other hand, the first issue is more related to application, I think. But I will send to their mailing list too. Thank you by the way.

**Comment by Kwpolska** [comment]
The first issue sounds like something related to reST, too: we do not provide section numbering ourselves, and we do not care.

**Comment by yoosofan** [comment]
So, do you use their code for reST compilation?

**Comment by Kwpolska** [comment]
Yes. Why would we bother re-implementing our own reST parser and writer?!  We do have a couple of plugins and tweaks, but none of them touch section numbering; in fact, I learned about it from your original post.

**Comment by yoosofan** [comment]
Yes it is obvious but I just want to know where is the origin of this issue.

**Comment by ralsina** [comment]
Hmmm maybe we fixed this when we started passing language to docutils a little while ago?

**Comment by yoosofan** [comment]
I download and install the latest package by running the following commnad

           sudo -H pip3 install -e "git+https://github.com/getnikola/nikola#egg=Nikolaextras"

It hasn't been solved yet. You can check the following link you will see the same result for 1.2.
[http://yoosofan.kashanu.ac.ir/semester/941.html](http://yoosofan.kashanu.ac.ir/semester/941.html)
[http://yoosofan.github.io/semester/941.html](http://yoosofan.github.io/semester/941.html)
Thank you for your consideration.

**Comment by tritium21** [comment]
Not related to this issue, but please, please for the love of your system install, never use sudo and pip in the same command line.  Nikola has a *lot* of dependencies, and you just flooded your system wide install with them.  You really should use a virtualenv (or if you really dont want to install virtualenv, [i have a tool for that](https://github.com/tritium21/venvbs))

**Comment by ralsina** [comment]
Since this is a docutils bug and we can do nothing to fix it and it has been open for 4 years, closing.
