### ISSUE TITLE
Replace "Study in Scarlet" with "DR. NIKOLA'S VENDETTA"

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2051]
http://www.gutenberg.org/files/21640/21640-h/21640-h.htm#PROLOGUE

Also, link that and other unlinked parts to the front page of the demo site.

**Comment by Kwpolska** [comment]
https://www.gutenberg.org/ebooks/13476

**Comment by ralsina** [comment]
If it hd math and we could typeset it it would be great. Otherwise... boy is that thing boring :-D

**Comment by Kwpolska** [comment]
The most *mathematical* thing would be `\(T_1\)` and variations of that.

Which isn’t a lot of mathematics, and something that is much better typeset with `<var>T</var><sub>>1</sub>`.
