### ISSUE TITLE
Try to use pageres for the theme screenshots

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2058]
https://github.com/sindresorhus/pageres
- We could automate it for real!
- We could show desk/tablet/mobile screenshots!
- Looks easy to setup

**Comment by Kwpolska** [comment]
(If you do this, throw in a simple webapp that will get push notifications from GitHub and rebuild accordingly.  I could write that part, or you could steal half the logic from [KwBot](https://github.com/Kwpolska/kwbot).)

**Comment by ralsina** [comment]
Good idea.

**Comment by ralsina** [comment]
So, we moved to something else, and the screenshots do look ok to me, so closing.

**Comment by Kwpolska** [comment]
What about automating rebuilds?

**Comment by ralsina** [comment]
There is no reason not to automate as it is now. I'll see if I can rig something up.
