### ISSUE TITLE
Title extracted from content takes over explicit title in metadata

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2059]
A file like this:

```
.. title: A BID FOR FORTUNE OR; DR. NIKOLA'S VENDETTA

By GUY BOOTHBY

Author of "Dr. Nikola," "The Beautiful White Devil," etc., etc.

PART I
======

```

Will be titled "PART I" and it should not.

**Comment by Kwpolska** [comment]
Title extraction magic is garbage, and it should happen only if no better source has anything for it. This might also require a bit of a restructuring, because IIRC there is a check, but it does not have all title data (I worked around this for ipynb before)

**Comment by ralsina** [comment]
Oh yes. I will get it out into a separate function and try really really hard to make it impossible to reach.

**Comment by ralsina** [comment]
FFFFFFFFFFFFFFFFFFFUUUUUUUUUUU

This is caused by the file starting with a BOM.
