### ISSUE TITLE
The "filters" metadata typogrify doesn't work?

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2064]
I tried to apply typogrify that way and could not. Either it doesn't work or it needs better docs.

So, according to the code, this should use the typogrify filter:

```
.. filters: filters.typogrify
```

And ... it does! Sort of.

1) In cache/posts/foo.html -> the post has smart quotes
2) In output/posts/foo/index.html? Nope.
3) site.timeline[0].text()? No quotes

~~Found the guilty party: LXML~~ NOPE

Now for real. This is what happens:

``smartypants('hello "world"')`` works.

But!

``smartypants('hello &quot;world&quot;')`` DOES NOT WORK.

**Comment by Kwpolska** [comment]
What is the problem?  `&quot;` == `"`; does typogrify not understand that, or?

**Comment by ralsina** [comment]
I thought typogrify added those &quot; in the 1st place... didn't it? Hmmmm

**Comment by Kwpolska** [comment]
Typogrify would have added “” or their entity equivalents: `&ldquo;` `&#8220;` / `&rdquo;` `&#8221;`

**Comment by ralsina** [comment]
Ok, then I spent a while chasing the wrong bunny. I'll try again tonight :-)

**Comment by Kwpolska** [comment]
Browsers are not intelligent enough to guess what quote to apply where; and even all the algorithms (be it Microsoft Word, WordPress or Typogrify) can fuck up too.

**Comment by ralsina** [comment]
There still seems to be a corner case, it's working with a simple testcase I had, but not with the actual ebook...

**Comment by ralsina** [comment]
Fixed.
