### ISSUE TITLE
Changing section colors does not rebuild things

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2066]
I want to use section colors in all post headers, and I have to run `nikola build -a` to get the changes to appear everywhere.

**Comment by ralsina** [comment]
We should probably just add POSTS_SECTION_COLORS to the global context, right?

**Comment by Kwpolska** [comment]
We actually need all the `POSTS_SECTION_*` things there, for other things to get rebuilt.  I’ll add them in.
