### ISSUE TITLE
Page with list of sections

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2067]

**Comment by tritium21** [comment]
What is this about?  The title is a little ambiguous.

**Comment by Kwpolska** [comment]
Sections are a replacement for categories, that have a few more features, and are based on the directory hierarchy (by default). However, there is no section index, that lists all sections available on the site.

**Comment by ralsina** [comment]
I can probably try to do this tomorrow.

**Comment by felixfontein** [comment]
This should be now very easy to implement by telling the sections taxonomy to generate an overview page. You need to set `template_for_classification_overview` and define `get_overview_path` and `should_generate_classification_page`.
