### ISSUE TITLE
RSS for sections

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2068]

**Comment by ralsina** [comment]
So, it looks like this should be pretty straightforward as part of the ``indexes`` plugin, giving it a shot.

**Comment by ralsina** [comment]
Looking a bit harder, we are already generating atom feeds if generate_atom is true... so, is this actually useful?

**Comment by ralsina** [comment]
Anyway: https://github.com/getnikola/nikola/pull/2463

**Comment by ralsina** [comment]
Done.
