### ISSUE TITLE
post.section_link ignores languages

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2069]
In [11]: site.timeline[30].section_link('pl')
Out[11]: '/nieskategoryzowane/'

The correct output should be '/pl/nieskategoryzowane/'. I’m using sections from metadata, but I think this is a problem with the path-based implementation, too.  I’ll attempt to fix it by myself.

**Comment by ralsina** [comment]
Since this branch fixes the problem, I say we merge it, and then file a new issue to refactor away the method.
