### ISSUE TITLE
Make the new_post filename template customizable

### ISSUE THREAD

**Issue by koniiiik** [getnikola/nikola#2076]
Currently, new_post always uses `posts/<slug>.<ext>` for the new filename (or whichever directory is the first in `POSTS`). It would be nice to augment this with values like the category, or date, such as `posts/<category>/<slug>.<ext>`, or `posts/<year>/<month>/<day>/<slug>.<ext>`, or some other combinations.

**Comment by Kwpolska** [comment]
`s/<category>/<section>/`

**Comment by ralsina** [comment]
@koniiiik @Kwpolska But how would ```nikola new_post``` know what section your post goes in?

It does look doable for year/month/day at least.

**Comment by Kwpolska** [comment]
`nikola new_post --section=unicorns`

**Comment by PatrickMassot** [comment]
I think ```nikola new_post --section=unicorns``` would be great. It would be even better if one could turn the ```ADDITIONAL_METADATA``` variable of conf.py into a dictionary indexed by sections so that new_post can add metadata fields depending on the value of the --section option.

**Comment by Kwpolska** [comment]
This is already a thing for dates with the `NEW_POST_DATE_PATH = True` option or `nikola init -d`. I’ll close this and consider this done, at least in a good-enough way.
