### ISSUE TITLE
Given a post, it should be possible to get a list of indexes that contains it

### ISSUE THREAD

**Issue by da2x** [getnikola/nikola#2077]
Given a Post object (well, a permalink is a unique enough identifier), it should be possible to get a list of which main, section, tag, or archives indexes pages link to it in HTML or Atom. Say a post is on /2015/index-4.html, /section2/index.html, /index.html. and /tag/cat-porn-2.html. Somehow associate generated paths with a post? Or call on the check-command analyzer to find links pointing to a given post.permalink(); would be kind of useless without knowing the pagekind too. I’ve got exactly three uses for this but no idea how to accomplished it.

**Comment by Kwpolska** [comment]
Bonus question, what use cases do you have?

Note that this is very likely to involve race conditions if this is accessed before index tasks are generated…

**Comment by Aeyoun** [comment]
1. Say you’re on /index-4.html (in this scenario the primary navigation structure of the site) and click in to /post/ninja.html. /post/ninja.html can’t show navigation breadcrumbs linking back to the index page it appeared on.
2. Say you’re in /index.atom, /2015/index-2.atom, or /tag/topic.atom and you see a post. The source for that post could be considered /section/index-3.atom where it originally appeared. The //feed/entry/source element can be used to indicate which feed is the primary source of the information. But it depends on knowing where else the post appears.
3. “Pages that link here:”

**Comment by ralsina** [comment]
@Aeyoun:

1. but then if you get to the post by clicking on a section index the crumbs will lead you to the general index. Crumbs in non-hierarchical sites are bad UI

2. well, the main source of information is already shown as an alternate link, right? We could make that visible somehow.

3. JSON!

**Comment by felixfontein** [comment]
To implement this cleanly, I think one would need some kind of facility where plugins could register a handler which for a post yields a list of URLs where it appears. The big question is how detailled do you want this info; like do you want the page in the index where the post appears? Or only the "main" (first) index URL/page?

If you want the precise location (including page number), this information either needs to be put into every context, which will trigger frequent rebuilds of pretty many pages which are pretty unnecessary (if you don't use this new feature), or you risk this information quickly being out of date. Having this optionally in a JSON file is probably a better idea: this avoids unnecessary rebuilds for people who don't want this feature, and avoids the outdated information trap when this information is not included in the contexts.

**Comment by Aeyoun** [comment]
I’d want the precise page number.

**Comment by felixfontein** [comment]
How can you find out in which indexes a post shows up (without knowing exactly which plugins create which indexes)?

**Comment by ralsina** [comment]
You'd need a sort of registry like we do for paths, where each function takes a post and gives you links to it, maybe?

**Comment by felixfontein** [comment]
That's what I meant yesterday. This is not very hard to implement, the question is whether this should be in Nikola.

**Comment by Aeyoun** [comment]
I’m really just interested in experimenting whether I can use this to “weight” my sitemaps to favor section indexes over the main index by having the main index.atom refer each entry as copied from entry/source/[link]@href=section/index-3.atom.

I then thought of this some more and realized that you can’t even use the link function to get a link to the 205 archive index page number 3 (/2015/index-3.html). You ca only specify name (2015) and get a link to the main index.html, and then diverted down this thought path that given a post object; it should be possible to find which page of a given index it exist on.

**Comment by ralsina** [comment]
Well, of course "can't use it for that now" doesn't mean "can't be used for that as soon as someone does the rather simple patch" :-)

**Comment by Aeyoun** [comment]
Simple patch? Maybe. But the path system is kind of weird the way it works now when you stop to think about it. It magically returns different results when called from inside it’s own plugin.

**Comment by ralsina** [comment]
2 years no code, clearly this was not that important.

**Comment by felixfontein** [comment]
With the new taxonomy system, this is even much easier to implement than before. If someone really wants it, creating a plugin to do so should not be very hard.
