### ISSUE TITLE
listings path handler seems buggy

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2080]
I linked to a listing with ``link://listing/book.tmpl`` and this happened:

```
ERROR: Nikola: Using non-unique listing name 'book.tmpl', which maps to more than one listing name ([u'listings/book.tmpl', u'listings/book.tmpl'])!
```

Somehing is not being very clever there.

**Comment by felixfontein** [comment]
The bug seems not to be in the path handler, but in `set_site` and/or `gen_tasks`, which call `register_output_name` twice for the same listing.

**Comment by ralsina** [comment]
Even then, registering the same name shuld be idempotent.

**Comment by felixfontein** [comment]
In that case, a simple fix to `register_output_name` will do the job. It would be even better though if it wouldn't be called twice for the same post, though.

**Comment by ralsina** [comment]
So, maybe this is 2 bugs. In any case, calling Nikola.path('listing', 'book.tmpl') works, so I need to debug this for real :-)

**Comment by ralsina** [comment]
I fixed the obvious part by making the mapping use sets instead of lists. Still there is surely redundant calls to add things to the mappings.

**Comment by felixfontein** [comment]
LGTM.
I also don't care enough to try to remove redundant calls...
