### ISSUE TITLE
Integrate Documentor

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2085]
https://github.com/diegosarmentero/documentor

**Comment by Kwpolska** [comment]
Nikola-based Sphinx, eh? Looks neat.

We should help the developer out (the project wasn’t updated for 2 years though…) and make it even nicer.

**Comment by ralsina** [comment]
He's a friend of mine and is not really interested in maintaining it, but it's pretty good as it is and it's nice enough code :-)

**Comment by ralsina** [comment]
oops, closed by mistake.

**Comment by Kwpolska** [comment]
I don’t think this is going anywhere.
