### ISSUE TITLE
Using IPython  %%magics breaks syntax highlighting on zen-ipython

### ISSUE THREAD

**Issue by profedrini** [getnikola/nikola#2092]
(euler)drini@hunabku ~/git/euler $ jupyter --version
4.0.4
(euler)drini@hunabku ~/git/euler $ nikola --version
Nikola v7.7.1

Using %%time on a jupyter notebook disables syntax highligting when rendering. Using zen-ipython theme.

With magic:
![With magic, no syntax color](https://cloud.githubusercontent.com/assets/8213196/9924841/1fe3e79e-5cc9-11e5-8654-9724ecbd2b0a.png)

Without magic:
![without magic, syntax coloring](https://cloud.githubusercontent.com/assets/8213196/9924849/2a9afbf0-5cc9-11e5-8e50-958b01badd3b.png)

**Comment by profedrini** [comment]
This behaviour was already present on version 7.6.3 (the  previous version I used)

**Comment by Kwpolska** [comment]
This might be a ipynb/Jupyter bug, since that’s what does our rendering. Does it look good in the Jupyter webapp?

**Comment by profedrini** [comment]
it looks good inside jupyter notebook:
![snap0000](https://cloud.githubusercontent.com/assets/8213196/9944378/88e87e48-5d4c-11e5-8237-ae8285862eca.png)

**Comment by Kwpolska** [comment]
Closing as *someone else’s bug* (jupyter/nbconvert#105)
