### ISSUE TITLE
zen-ipython does not respect CODE_COLOR_SCHEME variable

### ISSUE THREAD

**Issue by profedrini** [getnikola/nikola#2093]
(euler)drini@hunabku ~/git/euler $ jupyter --version
4.0.4
(euler)drini@hunabku ~/git/euler $ nikola --version
Nikola v7.7.1

Setting CODE_COLOR_SCHEME=   on  conf.py has no effect upon  building

For example:

```
# CODE_COLOR_SCHEME = 'default'
CODE_COLOR_SCHEME= 'vim'
```

should render syntax color from notebooks into a dark background scheme,  but it keeps rendering with default color

![snap0002](https://cloud.githubusercontent.com/assets/8213196/9924918/1547b8f0-5cca-11e5-9a6d-0b79f65bff41.png)

**Comment by Kwpolska** [comment]
We use the default syntax highlighting configuration from ipynb, we should probably delete that and change our code.css generation to add whatever class ipynb wants.

**Comment by ralsina** [comment]
I don't think we are going to fix this.

**Comment by Kwpolska** [comment]
I think that we could fix it just by removing [those CSS rules](https://github.com/getnikola/nikola/blob/master/nikola/data/themes/base/assets/css/nikola_ipython.css#L55) and ensuring our code.css has equivalent ones.

**Comment by ralsina** [comment]
code.css does have .hll and all those others, so maybe just removing them so code.css's less-specific one works?
