### ISSUE TITLE
Suggest users visit directory after first deployment

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#2096]
If not `cache/lastdeployment`, print message about adding their site to user directory at `https://users.getnikola.com/add/` during `nikola deploy`. (First deployment.)

**Comment by edemalm** [comment]
FYI, Swedish language option is missing on https://users.getnikola.com/add/ :)

**Comment by Kwpolska** [comment]
Added, along with a few more languages.

**Comment by ralsina** [comment]
Oops, merged directly instead of switching to the feature branch. Should work anyway.
