### ISSUE TITLE
nikola 7.7.1 causes material-theme to not render when there are posts

### ISSUE THREAD

**Issue by kgurnani96** [getnikola/nikola#2097]
While running `nikola build` with nikola on version 7.7.1 with material theme i get this error:

<pre>
(venv)sugarcane:yovoy kunalgurnani$ nikola build
Scanning posts......done!
.  render_listings:output/listings/index.html
.  render_sources:output/posts/about/index.rst
.  render_archive:output/2015/index.html
.  render_archive:output/archive.html
########################################
TaskError - taskid:render_archive:output/archive.html
PythonAction Error
Traceback (most recent call last):
  File "/Users/kunalgurnani/Dev/yovoytaxi/blog/venv/lib/python3.4/site-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/Users/kunalgurnani/Dev/yovoytaxi/blog/venv/lib/python3.4/site-packages/nikola/nikola.py", line 1104, in render_template
    template_name, None, local_context)
  File "/Users/kunalgurnani/Dev/yovoytaxi/blog/venv/lib/python3.4/site-packages/nikola/plugins/template/jinja.py", line 92, in render_template
    output = template.render(**context)
  File "/Users/kunalgurnani/Dev/yovoytaxi/blog/venv/lib/python3.4/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/kunalgurnani/Dev/yovoytaxi/blog/venv/lib/python3.4/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kunalgurnani/Dev/yovoytaxi/blog/venv/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "themes/material-theme/templates/list.tmpl", line 2, in top-level template code
    {% extends 'base.tmpl' %}
  File "themes/material-theme/templates/base.tmpl", line 59, in top-level template code
    {% block content %}{% endblock %}
  File "themes/material-theme/templates/list.tmpl", line 12, in block "content"
    {% for text, link in items %}
ValueError: too many values to unpack (expected 2)
</pre>

**Comment by Kwpolska** [comment]
We changed the `list.tmpl` template upstream.  Fixing.

This is still broken in the `bnw` and `octopress themes. cc @lotabout, @magmax, please fix.

**Comment by ilvidel** [comment]
Hello. I am still getting this error in Nikola 7.7.7
Surely there's some configuration I didn't do properly. Is there anything I'm missing?
`$ pip list`
- blinker (1.4)
- cloudpickle (0.2.1)
- configparser (3.3.0.post2)
- docutils (0.12)
- doit (0.29.0)
- husl (4.0.3)
- Jinja2 (2.8)
- Logbook (0.12.5)
- lxml (3.6.0)
- Mako (1.0.4)
- MarkupSafe (0.23)
- natsort (4.0.4)
- Nikola (7.7.7)
- Pillow (3.2.0)
- pip (8.1.1)
- pkg-resources (0.0.0)
- Pygments (2.1.3)
- pyinotify (0.9.6)
- PyRSS2Gen (1.1)
- python-dateutil (2.5.3)
- requests (2.9.1)
- setuptools (20.9.0)
- six (1.10.0)
- Unidecode (0.4.19)
- wheel (0.29.0)
- Yapsy (1.11.223)

**Comment by Kwpolska** [comment]
Are you running an up-to-date version of the theme?

**Comment by Kwpolska** [comment]
It looks like you aren’t, because I can’t reproduce. Run `nikola install_theme material-theme` and try again.

**Comment by ilvidel** [comment]
Hmm, I was pretty sure I was using the last version of the theme, but perhaps some files were left undeleted. I deleted everything and restarted the whole directory from scratch. Now it works. Thanks, and sorry for the hassle.

**Comment by bretonio** [comment]
« I deleted everything andu00ab restarted the whole directory from scratch». ilvidel, what files did you delete and from where? Did you mean you did a brand-new `nikola init <project>`? I tried that. No joy.  

Let me see if I can install another theme, one not using jinha2.  

Yes I succeed at building planetoid, for example. 

Nikola 7.8.0

**Comment by Kwpolska** [comment]
Please run the following commands and show us the output:

```
nikola init -qd nikolademo
cd nikolademo
nikola theme -i material-theme
nikola build
```

**Comment by bretonio** [comment]
Sorry, I do not know how to output error messages -- traceback -- to a file for debugging.
Let me know how and I will do it!
I received the same error as before while building at any rate.self.lookup.parse
And for some reason specifying `material-theme` in `conf.py` also break the `nikola list` command.

**Comment by Kwpolska** [comment]
Just copy everything that appears in your terminal when running those
commands and paste it here.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by bretonio** [comment]
Academic question now. Theme installed just fine on the Arch Linux half of
my machine! Thx
