### ISSUE TITLE
Incorrect warning about non-existing robots file

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#2098]
> WARNING: Nikola: Did not generate robots.txt as one already exists in FILES_FOLDERS. ROBOTS_EXCLUSIONS will not have any affect on the copied file.

I have no robots in FILES_FOLDERS. I only have one generated by Nikola in output.

**Comment by Aeyoun** [comment]
utils.get_asset_path() includes OUTPUT_FOLDER so this is basically bullshit. A robots.txt can never be generated more than once.

**Comment by ralsina** [comment]
That's a very recent change, maybe it was not a great idea

**Comment by ralsina** [comment]
Or let's make the default NOT check output. It's an easy fix.
