### ISSUE TITLE
Including code using literalinclude directive

### ISSUE THREAD

**Issue by orsenthil** [getnikola/nikola#2099]
Sphinx supports showing code using literalinclude directive. http://sphinx-doc.org/markup/code.html  Nikola does not have it yet.  Creating this ticket as a feature request.

**Comment by ralsina** [comment]
I can add it but you could use the [code option in the include directive](http://docutils.sourceforge.net/docs/ref/rst/directives.html#including-an-external-document-fragment) which is standard in docutils

In any case, added it to the list of sphinx things to implement in #770 and closing this one as duplicate.
Feel free to mention other sphinx bits we may be missing, I'll try to add them when possible.

**Comment by orsenthil** [comment]
Thanks! That works for all my use cases. Honestly, I didn't know about `:code:` option in `.. include::` directive. I had been using `.. literalinclude::` for my needs.

**Comment by ralsina** [comment]
If you want something fancier, we have a ``listing`` directive that is nice :-)

**Comment by orsenthil** [comment]
That is neat, Thank you! :+1:
