### ISSUE TITLE
output/assets/css/code.css is orphaned?

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#2106]
~/blog$ nikola build
    Scanning posts................done!
    copy_assets:output/assets/css/base.css
    Scanning posts................done!
    ~/blog$ 
    ~/blog$ nikola build
    Scanning posts................done!
    ~/blog$ nikola check -f
    Scanning posts................done!
    WARNING: check: Files from unknown origins (orphans):
    WARNING: check: output/assets/css/code.css
    ~/blog$ nikola build
    Scanning posts................done!
    copy_assets:output/assets/css/base.css
    ~/blog$ nikola check -f
    Scanning posts................done!
    WARNING: check: Files from unknown origins (orphans):
    WARNING: check: output/assets/css/code.css

**Comment by Aeyoun** [comment]
It seem to happen at random. It’s either just code.css, or it’s every asset inherited from the base theme. My own assets at themes/mytheme/assets/ and /files/assets/ seem just fine.

.  copy_assets:output/assets/css/theme.css
.  copy_assets:output/assets/css/rst.css
.  copy_assets:output/assets/css/ipython.min.css
.  copy_assets:output/assets/css/nikola_ipython.css
.  copy_assets:output/assets/css/ipython.min.css.map
.  copy_assets:output/assets/js/fancydates.js
.  copy_assets:output/assets/js/moment-with-locales.min.js
.  copy_assets:output/assets/js/jquery.min.map
.  copy_assets:output/assets/js/html5.js
.  copy_assets:output/assets/xml/rss.xsl
.  copy_assets:output/assets/xml/atom.xsl

**Comment by felixfontein** [comment]
`copy_assets` is creating `output/assets/css/code.css`, but only if
```
utils.get_asset_path('assets/css/code.css',
                                              themes=kw['themes'],
                                              files_folders=kw['files_folders'])
```
returns something which evaluates to `False`. That somewhere where I'd start debugging.

**Comment by felixfontein** [comment]
(Actually, `get_asset_path` has a bug I think. When checking the file folders, it always assumes that they are put into `output/` without any subfolder. Maybe that is part of the problem here? Do you have a `assets/css/code.css` in some files folder which isn't copied to `output/` directly?)

**Comment by Aeyoun** [comment]
I used to have one in themes/css/code.css that was empty. I’ve never had that for the other files, though. It’s  been deleted and any conceivable cache have been deleted including the  output folder.

**Comment by Kwpolska** [comment]
I use the auto-generated file and also have this problem:

```
(nikola-py3)[kwpolska@kw-cassandra nikola Gmaster]% nikola check -fl
Scanning posts......done!
[2015-09-21T15:34:01Z] WARNING: check: Files from unknown origins (orphans):
[2015-09-21T15:34:01Z] WARNING: check: output/assets/css/code.css
```

**Comment by ralsina** [comment]
This happens even in the demo site, so we should (in any order):

1) add a check to detect it
2) fix it

**Comment by ralsina** [comment]
So, we had tests for "check -l" and "check -f" on the demo site but they were broken and succeeded even though the checks failed.
