### ISSUE TITLE
Make nikola auto rebuild when plugins or nikola itself changes.

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2113]
It's not hard to implement:

1) Add watches for where nikola and all the plugins are
2) Trigger as needed

~~But, is it **right**?~~ Yes, yes it is.

**Comment by Kwpolska** [comment]
IMO yes.  Plugin and Nikola developers would really appreciate this.  As for everyone else, they don’t really care.

**Comment by ralsina** [comment]
Ok then.
