### ISSUE TITLE
.. template: directive is not used in translated pages (.en.rst)

### ISSUE THREAD

**Issue by humitos** [getnikola/nikola#2114]
I have a multilanguage site and I have some pages (under `stories/`) which are translated. For example:

* home.rst
* home.en.rst

(the repo is here: https://github.com/humitos/argentinaenpython.com.ar)

If I use `.. template: englishpage.tmpl` in the `home.en.rst` doesn't work. Nikola just use the same template to render both files.

**Comment by ralsina** [comment]
The fix here is to make Post.template_name respect the locale. Should be a 2-liner, give or take a line.
