### ISSUE TITLE
Use a different template for all the translated pages

### ISSUE THREAD

**Issue by humitos** [getnikola/nikola#2115]
It's related to #2114 

Suppose that I want to use a different template for all the translated pages. I would change the `PAGES` variable in `conf.py` to be like this:

```
PAGES = (
    ("stories/*.rst", "", "story.tmpl"),
    ("stories/*.txt", "", "story.tmpl"),
    ("stories/*en..rst", "", "englishpage.tmpl"),

)
```

But this generates an issue:
```
[2015-09-23T20:02:33Z] ERROR: Nikola: Two posts are trying to generate en/./index.html: stories/home.en.rst and stories/home.rst
```

Is there any solution for this? Is it a bug?

**Comment by ralsina** [comment]
There is no solution for this, and changing it would be very, very difficult.

One thing you *could* try is to make a template that uses language to change things, since "lang" is available at the template level.
