### ISSUE TITLE
Removing a page does not remove it from the rendered output

### ISSUE THREAD

**Issue by millenniumhand** [getnikola/nikola#2119]
I'm not sure if there's something else I should be doing aside from deleting by hand from the output. I have tried `nikola clean --clean-all`

**Comment by Aeyoun** [comment]
`nikola check --clean-files` will be more effective.

**Comment by schettino72** [comment]
this keeps coming up... why there is no task to do that automatically?

**Comment by ralsina** [comment]
Because deleting files without user's explicit command is scary :-)

**Comment by Aeyoun** [comment]
Deleting files that Nikola literally don’t know how to recreate is even scarier.

**Comment by Aeyoun** [comment]
If anyone have ideas for improving the usability and discoverability of these features, that would certainly help.
