### ISSUE TITLE
output/assets/css/code.css task is always outdated

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#2120]
and orphaned.

**Comment by ralsina** [comment]
The orphan thing I thought I fixed?

**Comment by Aeyoun** [comment]
Installed master just now.

    d:~/blog$ nikola build
    Scanning posts................done!
    .  copy_assets:output/assets/css/code.css
    d:~/blog$ nikola build
    Scanning posts................done!
    .  copy_assets:output/assets/css/code.css

**Comment by ralsina** [comment]
grmbl.

**Comment by ralsina** [comment]
I must say I am totally stumped and unable to reproduce this one.

**Comment by Aeyoun** [comment]
I can’t reproduce it on demand either. It happens all the time given that I’m not trying to reproduce it. If I leave auto running it will just keep rebuilding indefinitely.

**Comment by Kwpolska** [comment]
Closing as *cannot reproduce*.
