### ISSUE TITLE
Add 2.7 deprecation warning

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2121]
Should link to https://getnikola.com/blog/env-survey-results-and-the-future-of-python-27.html and it should not be *too* annoying.

**Comment by Aeyoun** [comment]
Once per day/week when running any command? plus every time deploy is run?

**Comment by Kwpolska** [comment]
We could do that.  And have a congratulatory message if the cache/py2-last-warning file exists and the user is running Python 3.

**Comment by Kwpolska** [comment]
That’s finished, right?
