### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by cursorius-cursor** [getnikola/nikola#2123]
I made a fresh installation in a Python 3.5 virtual environment. Next installed a demo site. After the first "nikola build" a  package was missed: typogrify. No problem so far:  pip install typogrify but should not happend at the beginning.

**Comment by ralsina** [comment]
Thanks for the heads up, I added a bit to the demo which requires typogrify and forgot to add the dependency.

**Comment by Kwpolska** [comment]
Should we mandate `typogrify` or show a warning and disable the filters if it’s not there?

**Comment by ralsina** [comment]
I think it's just a matter of marking a req_missing as optional and doing nothing.
