### ISSUE TITLE
Sphinx Autodoc? 

### ISSUE THREAD

**Issue by techdragon** [getnikola/nikola#2124]
Since #1611 has been closed with the promise that everything is in either the conf file or the docstrings, and mentioned that keeping a list of them up to date in the documentation would be prohibitively difficult, it would be nice if the docstrings themselves were better exposed as part of the project documentation. 
There is an internals page but no "API documentation".

Sphinx's Autodoc tools typically make this a painless addition to a projects documentation..

**Comment by Kwpolska** [comment]
We could probably try convincing Sphinx, we already run it on RTD via `docs.getnikola.com`.  Someone just needs to invest time in it.

**Comment by ralsina** [comment]
Done in bf1e9fd

**Comment by ralsina** [comment]
Or rather, in https://github.com/getnikola/nikola/commit/9b18210ef74430d8ccf65d12faac4281ec7d402d
