### ISSUE TITLE
Extension to support HandsOnTable

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2127]
Currently, if a user wants to do tabular data, he's going to end up embedding a google sheet.

That has the downside that:

1) It sort of looks like ass
2) It bounds you to google (I don't mind, others do)
3) It's often like killing a fly with a M50

So, I looked and found a very simple sheet-like thing, with MIT license, maintained, that works, and has a very simple API:

http://handsontable.com/

Adding this as a rest extension would not be horribly hard. Imagine if we could use it as a custom replacement for some tables? That would be awesome!

Anyway, just putting it here so I don't forget about it.

**Comment by Kwpolska** [comment]
This should be a very optional plugin.

Also, how is this better than a normal reST table?  It’s editing features certainly don’t work correctly, as copying cells uses a “repeat selected” algorithm instead of the Excel/LO standard intelligent sequence detection.

**Comment by ralsina** [comment]
Yes, totally optional. User can even edit and save locally!

**Comment by ralsina** [comment]
Nevermind.
