### ISSUE TITLE
Support critical CSS

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2128]
This makes pages **appear** to load faster. Maybe we can integrate it as a filter?

http://www.smashingmagazine.com/2015/08/understanding-critical-css/

**Comment by Aeyoun** [comment]
Should be made redundant by HTTP/2 server-push. The whole round-trip latency issue will disappear.

**Comment by ralsina** [comment]
But isn't this caused by the processing order, instead of latency?

**Comment by Aeyoun** [comment]
Well, if the browser has all the resources available it doesn’t really matter. Modern PCs are really fast, you know. Latency is by far the slowest factor. Play a bit inn the various browser’s performance and drawing tools (part of every browser’s devtools). Drawing the page takes no time at all compared to getting the resources in the first place.

**Comment by ralsina** [comment]
Not worth doing, then.
