### ISSUE TITLE
Update of Pillow 3.0.0 seems to have broke some APIs

### ISSUE THREAD

**Issue by elpasmo** [getnikola/nikola#2130]
After upgrading Pillow to 3.0.0 and ~~logbook 0.11.2~~ with a `pip install --upgrade nikola` command, `nikola build` raises a TypeError at line 107 of "/nikola/lib/python3.4/site-packages/nikola/image_processing.py".

> in image_date  value, r'%Y:%m:%d %H:%M:%S')
> TypeError: must be str, not tuple

**Comment by Kwpolska** [comment]
(this moved down to line 152 on master)
