### ISSUE TITLE
anchor links are improperly rewritten

### ISSUE THREAD

**Issue by ricardokirkner** [getnikola/nikola#2132]
When writing raw html pages that contain local anchor links they get rewritten improperly. Example

Create a page with the following content

.. raw:: html

    <a href="#foo">a link</a>

When building that page, the generated html will look like

<a href=".#foo">a link</a>

but should really look like

<a href="#foo">a link</a>

**Comment by ralsina** [comment]
On default configuration this works correctly, so it looks like interaction with "something" in the config. Following up.

**Comment by ralsina** [comment]
Even though it does something that works, url_replacer sure is failing to fullfill the "* Leaves fragments unchanged" part of its docstring.

**Comment by ricardokirkner** [comment]
I followed these steps

virtualenv env
source env/bin/activate
pip install nikola
pip install "Pillow<3.0" (to avoid a bug with Pillow 3.0)

nikola init --demo foo
nikola new_page

created the page by adding

    .. raw:: html

        <a href="#foo">a link</a>

nikola build
nikola serve

checked out the html in the browser

see this

    <a href=".#foo">a link</a>

**Comment by Aeyoun** [comment]
What does this page’s permalink look like? Are you sure the source is rewritten in the files? or is it just the browser’s interpretation (could be `<base>` related)?

**Comment by ricardokirkner** [comment]
Ok, with help of pdb, I found where the anchor is being incorrectly rewritten.

Inside url_replacer (in nikola.py) around line 1241 you find

if not result:
    result = "."

This is the culprit of the bad rewrite. From here on, the fragment is properly added to result later on, but the original anchor "#foo" is rewritten as ".#foo".

Haven't spent enough time following the code to come up with a proper patch for this, but in time I might.

**Comment by ralsina** [comment]
Actually that seems to me to be the right fix.
