### ISSUE TITLE
Support “Accelerated Mobile Pages” (AMP HTML)

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#2136]
:zap: So Google and friends want to speed up the mobile web again by forking HTML into a minimal versions and have Google Search return these rather than the normal full versions.

You can adapt an existing HTML document to become a HTML AMP document, but this would place unacceptable limitations on use of embedded content and scripts. So we’ll go with a separate and minified HTML AMP document instead because we can do that fully automatically without requiring users to do squat.

_Not ready for implementation. Pending on more example implementations._

Resources:
* [Accelerated Mobile Pages Project page](https://www.ampproject.org/)*
* [HTML-AMP spec](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md) (draft!) – TL;DR: `<!doctype html><html ⚡>`

Nikola implementation detatails:
* Only post pages will be supported because then we can automate microdata requirements
* Start out as an optional plugin but should be a part of core assuming Google are really serious about preferring AMP HTML over  HTML in the future.

Required:
- [ ] Output an extra AMP HTML variant in addition to the regular HTML files (I’m thinking “/amp.html” for pretty URLs and “-amp.html” for _ugly_ [amp is an ISO 639-3 language so “.amp.html” wouldn’t do])
- [ ] Link rewriter (links to post pages should link to their AMP variant)
- [ ] Asset rewriter (from `<img>` to `<amp-img>` plus extra attributes)
- [ ] Minuscule AMP parser to strip banned HTML elements and script-dependent includes and defer readers to “full page version” when encountered
- [ ] Make sure toolchains and filters don’t explode when encountering AMP

**Comment by Kwpolska** [comment]
How is AMP doing and do we really want it?

**Comment by tritium21** [comment]
The hype of last year was "this is cool and absolutely required for mobile!".  What I am seeing more now is still a lot of that hype, but more "well... why not just stop loading angular and jquery on every page, and follow good design principles so that everyone has a faster web page?"

I agree with the latter comment.

**Comment by Aeyoun** [comment]
Google really wants it, so this is pending whether they start deprioritizing non-AMP sites over AMP in search results.

**Comment by tritium21** [comment]
Google will suddenly stop want it to be a thing once they fix javascript on android.  Lets not do this, it is way too much hassle.

**Comment by Kwpolska** [comment]
@Aeyoun [citation needed]. How many sites are available in AMP format today?

**Comment by Aeyoun** [comment]
“Later this year, all types of sites that create AMP pages will have expanded exposure across the entire Google Mobile Search results page […]”
https://webmasters.googleblog.com/2016/09/what-is-amp.html

**Comment by tritium21** [comment]
If someone wants to be hostage to google, they can make a custom theme.

**Comment by felixfontein** [comment]
Since AMP files contain automatic tracking by google, Nikola should NOT generate them by default. Maybe this can be realized as a plugin in the https://github.com/getnikola/plugins/ repository (with some generic support code in Nikola itself which could also be used for other ways to package articles than AMP)?
