### ISSUE TITLE
Bootstrap 4 alpha is ready

### ISSUE THREAD

**Issue by humitos** [getnikola/nikola#2138]
Is it a good idea start working on a theme based on Bootstrap 4 alpha?

http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/

**Comment by ralsina** [comment]
Probably.

**Comment by Kwpolska** [comment]
https://themes.getnikola.com/v7/bootstrap4/ mostly works.

**Comment by Kwpolska** [comment]
Basically done on master.
