### ISSUE TITLE
Provide deep GIT integration

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#214]
Lots of people like GIT. Let's use it behind the scenes to provide awesomeness.

What would this entail? Let's make a list! We can add hook handlers in a plugin, so a hypothetical git plugin would (not all of these may be possible!):

I have implemented most of this in the new [vcs plugin](https://github.com/getnikola/plugins/tree/master/v7/vcs)

- [x] run ```git add``` on post/page addition
- [x] run ```git add``` on new images in galleries
- [x] run ```git commit``` on finding new things
- [x] if the user removes a versioned file, remove it
- [ ] optionally run ```git push``` on deploy?
- [x] Ensure everything that matches ```POSTS``` an ```PAGES``` is versioned
- [x] Ensure ```conf.py``` is versioned
- [x] Ensure ```files/``` is versioned

I am going to assume we are *not* keeping ```output/``` under git, but just the inputs.

http://pythonhosted.org//anyvc looks like a nice starting point for this.

**Comment by e2jk** [comment]
[ ] `git tag` on deploy

**Comment by immanetize** [comment]
One thing I've tried to work out - and the directory structure doesn't quite play along - is keeping the content in one git repo, and the config stuff in another (and maybe a separate one for themes).  Maybe just my personal preference, but, food for thought :)

**Comment by ralsina** [comment]
See https://github.com/getnikola/plugins/tree/master/v7/vcs

**Comment by ralsina** [comment]
Closing, any further improvements will be new issues.
