### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'format'

### ISSUE THREAD

**Issue by yamila-moreno** [getnikola/nikola#2140]
Context: building a nikola with data imported from wordpress, python3.5 and version 7.7.2, I got the next error:
```
AttributeError: 'bool' object has no attribute 'format'
```
After debugging, the problem are the deprecation warnings. Once fixed, the build works properly.

**Comment by Kwpolska** [comment]
Further information on Twitter; tl;dr: RSS_LINKS_APPEND_QUERY → FEED_LINKS_APPEND_QUERY does not create TranslatableSettings properly.

**Comment by Kwpolska** [comment]
That was actually a copy-paste error. Fixed in master.
