### ISSUE TITLE
Galleries should allow loinks to individual photos

### ISSUE THREAD

**Issue by StyXman** [getnikola/nikola#2146]
Right now Nikola's galleries build one page per directory and have a pop-up to show a picture, but there's no way to have a link to that individual image in the pop-up, only to simply send a link to the image file. For instance, with another, non-static gallery (which I want to replace with nikola!), I can do this:

http://grulicueva.homenet.org/~mdione/PhotoShow/?f=lugares%2FEuropa%2FMonaco%2FDSC_4948.JPG

**Comment by Kwpolska** [comment]
Sounds like something that can be easily handled with some JavaScript glue (which we could even steal from that solution of yours), assuming that colorbox allows opening a photo programmatically.

**Comment by ralsina** [comment]
AFAIK yes it does.
