### ISSUE TITLE
watchdog: command 'gcc-4.2' failed with exit status 1

### ISSUE THREAD

**Issue by Nikolaissue** [getnikola/nikola#2148]
Hello.

I am trying to install nikola[extras] with the command

pip install "nikola[extras]" --upgrade

but I get the error below. Is this an issue with watchdog or nikola?

Thank you!

Gerry (Mac OSX 10.6, Python 3.5)

Installing collected packages: watchdog, nikola
  Running setup.py install for watchdog
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 -c "import setuptools, tokenize;__file__='/private/var/folders/Mp/MpSSjvV2FL4+8z2Ek3s55++++TI/-Tmp-/pip-build-9pd_atj7/watchdog/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/Mp/MpSSjvV2FL4+8z2Ek3s55++++TI/-Tmp-/pip-uijes1i6-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.5
    creating build/lib.macosx-10.6-intel-3.5/watchdog
    copying src/watchdog/__init__.py -> build/lib.macosx-10.6-intel-3.5/watchdog
    copying src/watchdog/events.py -> build/lib.macosx-10.6-intel-3.5/watchdog
    copying src/watchdog/version.py -> build/lib.macosx-10.6-intel-3.5/watchdog
    copying src/watchdog/watchmedo.py -> build/lib.macosx-10.6-intel-3.5/watchdog
    creating build/lib.macosx-10.6-intel-3.5/watchdog/observers
    copying src/watchdog/observers/__init__.py -> build/lib.macosx-10.6-intel-3.5/watchdog/observers
    copying src/watchdog/observers/api.py -> build/lib.macosx-10.6-intel-3.5/watchdog/observers
    copying src/watchdog/observers/fsevents.py -> build/lib.macosx-10.6-intel-3.5/watchdog/observers
    copying src/watchdog/observers/fsevents2.py -> build/lib.macosx-10.6-intel-3.5/watchdog/observers
    copying src/watchdog/observers/inotify.py -> build/lib.macosx-10.6-intel-3.5/watchdog/observers
    copying src/watchdog/observers/inotify_buffer.py -> build/lib.macosx-10.6-intel-3.5/watchdog/observers
    copying src/watchdog/observers/inotify_c.py -> build/lib.macosx-10.6-intel-3.5/watchdog/observers
    copying src/watchdog/observers/kqueue.py -> build/lib.macosx-10.6-intel-3.5/watchdog/observers
    copying src/watchdog/observers/polling.py -> build/lib.macosx-10.6-intel-3.5/watchdog/observers
    copying src/watchdog/observers/read_directory_changes.py -> build/lib.macosx-10.6-intel-3.5/watchdog/observers
    copying src/watchdog/observers/winapi.py -> build/lib.macosx-10.6-intel-3.5/watchdog/observers
    creating build/lib.macosx-10.6-intel-3.5/watchdog/tricks
    copying src/watchdog/tricks/__init__.py -> build/lib.macosx-10.6-intel-3.5/watchdog/tricks
    creating build/lib.macosx-10.6-intel-3.5/watchdog/utils
    copying src/watchdog/utils/__init__.py -> build/lib.macosx-10.6-intel-3.5/watchdog/utils
    copying src/watchdog/utils/bricks.py -> build/lib.macosx-10.6-intel-3.5/watchdog/utils
    copying src/watchdog/utils/compat.py -> build/lib.macosx-10.6-intel-3.5/watchdog/utils
    copying src/watchdog/utils/decorators.py -> build/lib.macosx-10.6-intel-3.5/watchdog/utils
    copying src/watchdog/utils/delayed_queue.py -> build/lib.macosx-10.6-intel-3.5/watchdog/utils
    copying src/watchdog/utils/dirsnapshot.py -> build/lib.macosx-10.6-intel-3.5/watchdog/utils
    copying src/watchdog/utils/echo.py -> build/lib.macosx-10.6-intel-3.5/watchdog/utils
    copying src/watchdog/utils/event_backport.py -> build/lib.macosx-10.6-intel-3.5/watchdog/utils
    copying src/watchdog/utils/importlib2.py -> build/lib.macosx-10.6-intel-3.5/watchdog/utils
    copying src/watchdog/utils/platform.py -> build/lib.macosx-10.6-intel-3.5/watchdog/utils
    copying src/watchdog/utils/unicode_paths.py -> build/lib.macosx-10.6-intel-3.5/watchdog/utils
    copying src/watchdog/utils/win32stat.py -> build/lib.macosx-10.6-intel-3.5/watchdog/utils
    running egg_info
    writing entry points to src/watchdog.egg-info/entry_points.txt
    writing requirements to src/watchdog.egg-info/requires.txt
    writing dependency_links to src/watchdog.egg-info/dependency_links.txt
    writing top-level names to src/watchdog.egg-info/top_level.txt
    writing src/watchdog.egg-info/PKG-INFO
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'src/watchdog.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.h' under directory 'src'
    writing manifest file 'src/watchdog.egg-info/SOURCES.txt'
    running build_ext
    building '_watchdog_fsevents' extension
    creating build/temp.macosx-10.6-intel-3.5
    creating build/temp.macosx-10.6-intel-3.5/src
    gcc-4.2 -fno-strict-aliasing -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -isysroot /Developer/SDKs/MacOSX10.6.sdk -g -DWATCHDOG_VERSION_STRING="0.8.3" -DWATCHDOG_VERSION_MAJOR=0 -DWATCHDOG_VERSION_MINOR=8 -DWATCHDOG_VERSION_BUILD=3 -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c src/watchdog_fsevents.c -o build/temp.macosx-10.6-intel-3.5/src/watchdog_fsevents.o -std=c99 -pedantic -Wall -Wextra -fPIC -Wno-error=unused-command-line-argument-hard-error-in-future
    cc1: error: -Werror=unused-command-line-argument-hard-error-in-future: No option -Wunused-command-line-argument-hard-error-in-future
    cc1: error: -Werror=unused-command-line-argument-hard-error-in-future: No option -Wunused-command-line-argument-hard-error-in-future
    lipo: can't figure out the architecture type of: /var/folders/Mp/MpSSjvV2FL4+8z2Ek3s55++++TI/-Tmp-//ccoFqjhZ.out
    error: command 'gcc-4.2' failed with exit status 1
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 -c "import setuptools, tokenize;__file__='/private/var/folders/Mp/MpSSjvV2FL4+8z2Ek3s55++++TI/-Tmp-/pip-build-9pd_atj7/watchdog/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/Mp/MpSSjvV2FL4+8z2Ek3s55++++TI/-Tmp-/pip-uijes1i6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/Mp/MpSSjvV2FL4+8z2Ek3s55++++TI/-Tmp-/pip-build-9pd_atj7/watchdog

**Comment by Kwpolska** [comment]
This isn’t a Nikola error, this is Watchdog-specific.  I’m afraid I can’t help here, there are multiple causes possible…

Google suggests this, but it might not apply to your problem: http://stackoverflow.com/questions/6316583/lipo-cant-figure-out-the-architecture-type-of-var-folders

**Comment by Nikolaissue** [comment]
Thanks for your prompt reply. I'll look into watchdog further.
