### ISSUE TITLE
Breaks Google Custom Search

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#2150]
Nikola turns `<gcse:searchresults-only></gcse:searchresults-only>` into `<searchresults-only></searchresults-only>`.

Solution, use HTML5 capable Google Custom Search Engine elements instead.
https://developers.google.com/custom-search/docs/element#html5

**Comment by Aeyoun** [comment]
This is just for documentation purposes.

**Comment by Kwpolska** [comment]
(This is lxml’s fault, and we know about it since issue #639.)
