### ISSUE TITLE
Using underscores for subscripts in KaTeX breaks formatting.

### ISSUE THREAD

**Issue by kdelwat** [getnikola/nikola#2153]
I've enabled KaTeX support and am using it to render my pages. The problem arises when I use more than one underscore in a line, to create mathematical subscripts. Nikola seems to interpret them as italic marking, breaking the line's formatting.

For example,

`The perpendicular vector resolute is equal to \\(\vec{u} - \vec{u}_{para}\\).`

Renders as the following, as expected.

![2015-10-23-184846_516x39_scrot](https://cloud.githubusercontent.com/assets/1031518/10687173/a8d89bd0-79b6-11e5-9557-7cb1f0282b1c.png)

However, when more than one underscore is present, as in this line:

`Vector \\(\vec{u}\\) can be split into two components, with one component parallel to \\(\vec{v}\\) , \\(\vec{v}\\), denoted \\(\vec{u}_{para}\\), and one perpendicular, denoted \\(\vec{u}_{perp}\\).`

The formatting breaks.

![2015-10-23-185144_596x90_scrot](https://cloud.githubusercontent.com/assets/1031518/10687221/12ed10c8-79b7-11e5-899f-fb97293df650.png)

**Comment by Kwpolska** [comment]
Your input format of choice (probably Markdown) interprets that as italics.
Replace '_' with '\_' or, if you are using reST, you should use the
:math:`2 + 2` role, as described in the documentation.

Closing as won't fix.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by kdelwat** [comment]
Thanks for the tip!
