### ISSUE TITLE
Hero and lead images

### ISSUE THREAD

**Issue by da2x** [getnikola/nikola#2154]
(Hero images are usually giant images at the top of an article. Lead images are small thumbnails usually seen in feeds or in indexes or other list presentation of  posts.)

See [IRC logs](https://irclogs.getnikola.com/logs/2015-10-23/) for background.

Meta data fields `heroimage` and `leadimage` format:

`imagetype: "<sizes-str>", <source-image.jpeg>, [alt]`

Desired output from calling `post.leadimage()` or `post.heroimage()` in a template:

```
<picture class="[hero|lead]-image">
  <source
    sizes="$sizes-str"
    srcset="$srcset-str"
    type="image/webp">
  <img
    alt="$optional-alt"
    sizes="$sizes-str"
    srcset="$srcset-str"
    src="$largest-size-str-image"
    type="image/[jpeg|png]">
</picture>
```

What is needed:
- [ ] Simple [sizes attribute](http://www.w3.org/html/wg/drafts/html/master/semantics.html#image-candidate-string) parser that fins all absolute image sizes (for example `"(min-width:320px) 310px, (min-width: 800px) 720px, 40vw"` should return the absolute image sizes `[310, 720]`
- [ ] Function to create jpeg or png and webp images in sizes returned by the sizes string parser. Plus double and half of that size. If a giant image is provided, consider 4x as well. Plus one in the  original source size. Must be smart enough to not create images larger than the source and fallback to the largest possible instead.
- [ ] Create size-sorted(!) srcset string from all the images: `"path_155w.jpeg 155w, path_310w.jpeg 310w, path_360w.jpeg 360w, path_620w.jpeg 620w, path_720w.jpeg 720w, path_1440w.jpeg 1440w, original.jpeg 5002w"`
- [ ] Function that returns a complete `<picture>` element.
- [ ] Documentation and blog post

**Comment by Aeyoun** [comment]
This should of course be a generic function authors should be able to call from anywhere in their posts.

`<!-- IMAGE: "sizes-string", "source-image.png" -->` ? Treat it like we do PHP?

**Comment by ralsina** [comment]
Some themes do support this sort of thing now (example: canterville)

Then, the authors can use post metadata inside the posts via shortcodes, too.

I think this is "good enough" as it is, specially since the issue is more than a year old.
