### ISSUE TITLE
On my site, nikola orphans reports thousands of files it should not.

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2158]
Specifics are complicated at this point.

**Comment by ralsina** [comment]
Looks like the problem is with very large sites. For example, in mine, render_index only shows 256 subtasks (but I have many more), so in _call_nikola_list() I only get <Task: render_indexes:output/weblog/index-1.html> to 128 and the same for spanish, leaving a bunch out.

**Comment by ralsina** [comment]
Turns out it *is* garbage.

**Comment by Kwpolska** [comment]
what is garbage?

**Comment by polyzen** [comment]
Actual orphans, I take it
