### ISSUE TITLE
"reStructuredText Extensions" in Markdown

### ISSUE THREAD

**Issue by socheon** [getnikola/nikola#2170]
Hi. I have just started experimenting with Nikola.

It will be great if there is a documentation, gathering all the extensions available for Markdown (Pandoc preferably).

Instead of implementing the extensions one by one for Markdown, will it be easy to support the `.. something::` syntax in Markdown, e.g.

```
.. media::
.. vimeo::
.. youtube::
```

Perhaps by running it through some pre or post processor.

**Comment by Kwpolska** [comment]
1. Markdown via Pandoc is not recommended and not officially supported, and if you do use it, please consult [Pandoc documentation](http://pandoc.org/README.html#pandocs-markdown) yourself.  That said, I don’t think you can enable the Pandoc extensions in Nikola…
2. This is sort-of doable. We could just split out the business logic and write some extension factory. We just need a regexp expert, someone who understands this mess and can generalize it:

    ```py
GIST_RST_RE = r'(?m)^\.\.\s*gist::\s*(?P<gist_id>[^\]\s]+)(?:\s*(?P<filename>.+?))?\s*$'

**Comment by socheon** [comment]
Maybe this works. We can process the args and properties in code.

```
pattern = r'(?ms)^\.\.\s*(?P<command>[\w-]+)::\s*(?P<args>[^\n]+)(?P<props>.*?)\n(?!\s)'
input = """

.. media:: http://vimeo.com/72425090

.. vimeo:: 20241459
   :height: 240
   :width: 320

.. code-block:: python
   :number-lines:

   x = 1
   y = 2

.. listing:: foo.py python
"""

for m in re.finditer(pattern, input):
    if m:
        print m.groupdict()
        print
```

Output
```
{'args': 'http://vimeo.com/72425090', 'command': 'media', 'props': '\n'}

{'args': '20241459', 'command': 'vimeo', 'props': '\n   :height: 240\n   :width: 320\n'}

{'args': 'python', 'command': 'code-block', 'props': '\n   :number-lines:\n\n   x = 1\n   y = 2\n'}

{'args': 'foo.py python', 'command': 'listing', 'props': '\n'}
```

**Comment by socheon** [comment]
Not sure how robust is using regexp.
Maybe is better to modify the parser. A rst directive looks a lot like a code block.

**Comment by Kwpolska** [comment]
I’d rather not use a single regex to capture everything, sounds too broad and complicated…

**Comment by socheon** [comment]
Thanks Kwpolska. I spent last week looking at Pandoc in detail. Syntax extensions can be easily written using using Pandoc filters (using Haskell or Python), which use the AST rather than regexp. So, it is quite neat.

> That said, I don’t think you can enable the Pandoc extensions in Nikola…

A filter is just a python script and the Pandoc tool can be simply extended by calling
`pandoc --filter ./filters.py` instead of `pandoc`. So can I just modify the call to `pandoc`?

What features of Nikola would be missing, if I decide to use Pandoc? Would I still have the "fast, incremental build", navigations, theme, as well as automatic build and deploy?

**Comment by ralsina** [comment]
You can already change how pandoc is called via PANDOC_OPTIONS in conf.py

**Comment by ralsina** [comment]
And yes, you will lose some features, basically whatever markup extensions
exist for other markups and not for pandoc. Other than that, nothing.

**Comment by Kwpolska** [comment]
By using Markdown via Pandoc, you lose:

* gist support (fix: just copy-paste HTML from gist.github.com)
* `DEMOTE_HEADERS` (we will not change h1 to h2, fix: do it yourself)
* podcast tag (does anyone even use it?)
* code highlighting (unless Pandoc produces `pre.code` and uses Pygments or something compatible)
* and, of course, any reST-specific extensions (which are not supported by python-markdown either)

Everything else will work fine.

**Comment by ralsina** [comment]
With the new shortcodes, once the rest compiler supports it, we could reimplement most of our rest extensions to also work as shortcodes (see the post-list rest extension for an example)

**Comment by sukiletxe** [comment]
Pandoc does support highlighting code via Highlighting Kate (written by the same author).

**Comment by Kwpolska** [comment]
Are we going to do more of those? `doc`, `slides`, `thumbnail` seem to be left out for now.

**Comment by ralsina** [comment]
I am creating a separate issue about making all docutils extensions into shortcodes so we can have a list.

**Comment by davidak** [comment]
@socheon media shortcode is supported.

See the docs: https://getnikola.com/handbook.html#built-in-shortcodes
