### ISSUE TITLE
Update KaTeX version or make it configurable

### ISSUE THREAD

**Issue by jluttine** [getnikola/nikola#2175]
KaTeX JS version is hard coded in the templates:

```
<script src="//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.3.0/katex.min.js">
```

This URL could be configurable in `conf.py` to allow easy updating. Or if KaTeX has a direct link to the latest version, that could be used?

**Comment by Kwpolska** [comment]
1. There is no link available to the latest version.
2. You can just copy the template and edit it instead. Changing this would complicate things quite a bit.
3. We do the same for other components (namely jQuery and Bootstrap), though we are better at updating them than KaTeX.

**Comment by jluttine** [comment]
Ok, I'll do that, thanks for the response!

**Comment by Kwpolska** [comment]
(In fact, I updated the built-in templates yesterday in dbb28e9.)
