### ISSUE TITLE
Nikola should not depend on a single version of python-dateutil, but be upwards compatible

### ISSUE THREAD

**Issue by marcusmueller** [getnikola/nikola#2180]
this breaks the Fedora 22 package, as its requirements.txt lists

    python-dateutil==2.4.0

but Fedora ships with 2.4.2; Current git master demands

    python-dateutil==2.4.2

which isn't better. If there is a particular reason not to trust future dateutil dependencies, these should lead to reliable reimplementation rather to version lock-in. 

I can't seem to find a reason to stick to a specific version of dateutil (and to a different in a slightly newer version of nikola), so I don't think using `==` is a good choice, here. However, I might be wrong -- I haven't dug too deep into Nikola, yet.

**Comment by Kwpolska** [comment]
There was an API-breaking update in the past, IIRC.  And does Fedora **22** really have an up-to-date version of Nikola in the first place?

>     $ dnf info python3-nikola
>     Version     : 7.3.0

No. That’s horribly outdated.  Fedora 24 is not better with 7.6.4.

We can’t do anything about it. Fedora is free to patch the requirements file though. dateutil issues were reported to them, with no fix.

I’ll set it to >=2.4.0.

cc @immanetize?

**Comment by marcusmueller** [comment]
I agree, you can't change packaging of past versions, and even less, Fedora's packaging! 

However, depending on a specific version if something else should work, too, is technically not "someone else's bug" ;)

By the way, that was *fast* :+1:
