### ISSUE TITLE
github_deploy should commit to the source branch automatically

### ISSUE THREAD

**Issue by shelper** [getnikola/nikola#2186]
I am using the xxx.github.io repo on github, so i set the GITHUB_SOURCE_BRANCH ='source', and GITHUB_DEPLOY_BRANCH='master". and the OUTPUT_FOLDER is default.
so, basically the source branch has folder structure like this:

source
├── README.txt
├── __pycache__
├── cache
├── conf.py
├── files
├── galleries
├── images
├── listings
├── output
├── plugins
├── posts
├── stories
└── templates

and then i run `nikola github_deploy`, i have generated a mater branch which contains the output results, it is folder structure is like below:

master
├── 2015
├── __pycache__
├── archive.html
├── assets
├── authors
├── cache
├── categories
├── favicon.ico
├── galleries
├── images
├── index.html
├── listings
├── output
├── posts
├── robots.txt
├── rss.xml
├── sitemap.xml
├── sitemapindex.xml
├── stories
└── zh_cn

everything works fine, but i have another output folder in this master branch, which contains exactly the same content as its parent folder... am i doing something wrong? or it suppose to be like this?
if so, i think it is more reasonable to just remove this output folder (and the cache folders as well).

ps: everything on github.com is fine, there is no output folder or cache folders in the master branch, so locally if you run `git status` you have:

      Untracked files:
      (use "git add <file>..." to include in what will be committed)
	.doit.db.db
	__pycache__/
	cache/
	output/
	posts/test.rst

**Comment by Kwpolska** [comment]
I think you need to add some things to .gitignore on your source branch, namely

```
cache
*.py[co]
.doit.db
output
```

You might also want to put it in files/ so it gets copied to master.

(why does `.doit.db.db` exist?)

**Comment by shelper** [comment]
`output` is already in the .gitignore list.
based on the source code i read, i think when run 'nikola github_deploy', it pushes the contents in the output folder to the github repo directly, i don't see where the local master branch is generated.

I did an experiment by cloning only the source branch to a local folder/repo, and run `nikola build`, it then adds the mater branch to the local repo, and that master branch has the output folder, while there is no output folder in the github master branch, 

another thing i would suggest is that when run `nikola github_deploy` it may be nice to commit and push the source branch to github as well. currently you have to do it manually

**Comment by Kwpolska** [comment]
We use ghp-import, which does all the branching. About committing, not everyone might want this, but we could make it a setting one day.

**Comment by Kwpolska** [comment]
I’ll try to get this done this week.
