### ISSUE TITLE
Inconsistency: e.g. `install_theme` vs. `plugin --install`

### ISSUE THREAD

**Issue by jean** [getnikola/nikola#2196]
We have `nikola install_theme` but `nikola plugin --install`. Theme management should work the same as plugin management; i.e. `nikola theme --install`. 

When run without parameters, `nikola plugin` prints usage info. 
When run without parameters, `nikola install_theme` prints an error (which does contain usage info).
Running a command without required parameters should always display usage info.

Ideally the [Extending Nikola docs](https://github.com/getnikola/nikola-site/blob/master/stories/extending.txt) should provide guidance. 
Is there a CLI best practice doc out there to reference?

**Comment by ralsina** [comment]
Sadly no such a document exists. There used to be a "install_plugin" plugin much like install_theme but then it was significantly improved and became the current one. Sadly noone did the same thing for install_theme yet.

**Comment by Kwpolska** [comment]
Fixed in #2231/#2239.
