### ISSUE TITLE
Duplicate images in galleries

### ISSUE THREAD

**Issue by humitos** [getnikola/nikola#2202]
Every time I resize the browser's window all the images are duplicated.

You can try this here: http://argentinaenpython.com.ar/galeria/taller-express/

1. Open the link
1. Make the window full screen
1. Make it smaller

All the images are duplicated. If you repeat the steps again you will get more images duplicated in the webpage.

**Comment by ralsina** [comment]
And I think I know how that happens. I'll fix it.

**Comment by ralsina** [comment]
@humitos can you try #2208 ?
