### ISSUE TITLE
EXIF not copied when re-scaling

### ISSUE THREAD

**Issue by humitos** [getnikola/nikola#2204]
If you have images for a gallery with pictures greater than `MAX_IMAGE_SIZE`, when they are re-scaled they loose the EXIF information. So, if you are using `GALLERY_SORT_BY_DATE = True` you will loose the order when they are displayed.

To solve this issue, I use `convert` (from ImageMagick to resize the image). After converting all of them, I revered the sorting order.

**Comment by ralsina** [comment]
Ideally we should be using the date from the source files, not the targets,
right?

**Comment by humitos** [comment]
For me, it's the same from where we should pick up the date.

Why EXIF information is not being copied? I think that is the first question and, depending its answer we should get the date from the scaled or original one.

**Comment by ralsina** [comment]
No, it's not the same. If the date is picked up from the source file, then this bug doesn't exist, at least the part about sort by date not working :-)

Why is the EXIF data not copied? Because I have no idea how to do that using PIL.

**Comment by ralsina** [comment]
So, it's not hard: http://stackoverflow.com/questions/400788/resize-image-in-python-without-losing-exif-data

I'll fix it.

**Comment by ralsina** [comment]
The "easy" solution leaves the resized images with wrong size in the EXIF data.

**Comment by ralsina** [comment]
@humitos #2207 does the simple thing, and you can see why it's not good.
