### ISSUE TITLE
MathJax isn't enabled for posts in non-default language only

### ISSUE THREAD

**Issue by krigstask** [getnikola/nikola#2205]
If there's a math post only in non-default language, Nikola won't enable MathJax there
1) Create new site: `nikola init non-def-math`. All the default values will suffice, just set at least two languages:
```
Language(s) to use [en]: en,pl
```

2) Create a Polish-only post:
```
$ nikola new_post -t "Math test" --tags=mathjax
$ echo '\nEuler’s formula: :math:`e^{ix} = \\cos x + i\\sin x`' >> posts/math-test.rst
$ mv posts/math-test.rst posts/math-test.pl.rst
```

3) `nikola build` will build a post without MathJax:
```
 $ nikola build && grep -r cdn.mathjax.org output || echo "Nope" 
Nope
```

If post has versions for both languages, maths are enabled correctly on both pages.

I did dig a bit in source code, and it seems like [mathjax is tested for presence in tags only for default language](https://github.com/getnikola/nikola/commit/e068305a4eb2099adca3b53e13c35c01b979c367/nikola/post.py#L283) (`nikola.utils.LocaleBorg().current_lang` returns default language).

**Comment by ralsina** [comment]
Good catch!

**Comment by ralsina** [comment]
I am not sure if https://github.com/getnikola/nikola/pull/2206 fixes this or just a related bug, can you check? If it doesn't fix it for you I'll try again ;-)

**Comment by krigstask** [comment]
> Good catch

Yeah, that took a whole lot of "WTF?", "I'm sure that worked!", "Have I screwed up `conf.py`?" and so on :)

> can you check?

Almost done: maths is rendered for [pl/posts/math-test/](http://localhost:8000/pl/posts/math-test/), but not for [posts/math-test/](http://localhost:8000/posts/math-test/) :-)
(That's for `SHOW_UNTRANSLATED_POSTS=True`, of course)

**Comment by ralsina** [comment]
Ah, that's trickier. Trying...

**Comment by ralsina** [comment]
I actually tested it this time and it should now work.

**Comment by krigstask** [comment]
Thanks, seems to be fixed now! Please merge in :)
