### ISSUE TITLE
GitHub deploy: allow source to be in a different respository with the output

### ISSUE THREAD

**Issue by xuhdev** [getnikola/nikola#2217]
Currently it seems that the source and the output are in the same repository. It would be great if a conf option allows two different repositories.

**Comment by Kwpolska** [comment]
This is hard to do and not worth the hassle IMO, but you can just use the regular `nikola deploy` command and set `OUTPUT_FOLDER` to your other repository.

**Comment by xuhdev** [comment]
I wrote a post about this:

Nikola: How to Deploy Compiled Webpages to a Different Git Repository https://www.topbug.net/blog/2018/11/09/nikola-how-to-deploy-compiled-webpages-to-a-different-git-repository/
