### ISSUE TITLE
adding local plugins

### ISSUE THREAD

**Issue by arturoc** [getnikola/nikola#2219]
I'm trying to add a plugin in a site by creating the plugin inside the plugins forlder of the site as:

```
site
  |_plugins
      |_plugin_name
          |_plugin_name.plugin
          |_plugin_name.py
```

i've tried with both command and task and although the plugin seems to be parsed, runing nikola on the site folder throws errors if the plugin code contains any, once the code is correct the plugin doesn't appear in the commands or tasks lists.

not sure if i'm missing something or this is just not possible.

**Comment by Kwpolska** [comment]
Try running with `NIKOLA_DEBUG=1` and tell us what it says about your plugin.

**Comment by arturoc** [comment]
ok, sorry, i was using def instead of class to define the plugin class and it was silently ignoring it

**Comment by ralsina** [comment]
Cool then :-)
