### ISSUE TITLE
Random rebuilds of files

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#2220]
In the last couple of days (might have been for longer), I experienced that some files are seemingly randomly rebuilt when running `nikola run`. I've tracked this down to `doit` config changes. For example, in one call I get:
```
"_link": "<bound method Nikola.link of <Nikola Site: 'A'>>"
```
and in a later call
```
"_link": "<bound method Nikola.link of <Nikola Site: 'B'>>"
```
Here, `A` and `B` are the two titles of my blog (it is bilingual). Whether the title used here is `A` or `B` seems to change from time to time per task, which causes rebuilds if it changes. Similar names (`"<bound method ... of <Nikola Site: 'xxx'>>"`) are generated also for `abs_link`, `exists` and some more.

This probably can be fixed by changing `__repr__` of the `Nikola` class to:
```
    def __repr__(self):
        """Representation of a Nikola site."""
        return '<Nikola Site: {0!r}>'.format(self.config['BLOG_TITLE'](self.config['DEFAULT_LANG']))
```
so that always the default language is used, and not `LocaleBorg`'s current language.

What do you think?

**Comment by felixfontein** [comment]
Changing this locally fixed it somewhat for me, but not totally. While investigating further, I noticed that there's another entry which changes: sometimes, the config contains `"author_pages_generated": false`, while sometimes it does not. That probably depends on the order the plugins were loaded and processed in, as the `plugins/task/authors.py` plugin sets this flag in the `site.GLOBAL_CONTEXT`.

I think the `authors` plugin must be changed since this is clearly a bug. What do you think?

At least, disabling this plugin seemed to have fixed the problem for me, or at least reduced its frequency considerably.

(Also, note that the different orders in which plugins are processed probably occur mostly with Python 3, and not with Python 2.)

**Comment by ralsina** [comment]
Or maybe just load the plugins in a deterministic order.

**Comment by ralsina** [comment]
Your change about the repr LGTM care to propose it?

**Comment by felixfontein** [comment]
That doesn't really fix the problem. I mean, what's the sense of having `author_pages_generated` in `GLOBAL_CONTEXT` for only a subset of all generated pages? Either it should be in all, or in none.

**Comment by felixfontein** [comment]
A fix for the `authors` plugin could be done by adding a hook to be run after `scan_posts` and setting the variable there. That would probably be a much cleaner solution.

**Comment by ralsina** [comment]
I don't see why authors needs to put that in config.... I'll take a look at that part.

**Comment by ralsina** [comment]
So, @felixfontein is there anything else to fix here?

**Comment by felixfontein** [comment]
Nothing that's mentioned yet. But I still have some random rebuilds which I'm currently trying to track down. Let me try a bit more...

**Comment by felixfontein** [comment]
I accidently used a wrong version of Nikola (without the first patch); after I noticed that and changed to the correct one, I wasn't able to trigger another random rebuild in quite some steps. So I assume it is fixed.
