### ISSUE TITLE
Windows bug with github_deploy

### ISSUE THREAD

**Issue by mondus** [getnikola/nikola#2223]
the github_deploy command gives the following error in Windows with Python 3.5.1 and nikola v7.7.4. Mailing list help suggests that this is a windows specific bug.

```
Scanning posts......done!
Scanning posts......done!
[2016-01-19T22:45:12Z] INFO: github_deploy: ==> ['ghp-import', '-n', '-m', 'Niko
la auto commit.\n\nSource commit: e7c6dabef635f205804e8abee5368e256019aa83\nNiko
la version: 7.7.4', '-p', '-r', 'origin', '-b', 'master', 'output']
Traceback (most recent call last):
  File "e:\python\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Python\Scripts\ghp-import.exe\__main__.py", line 9, in <module>
  File "e:\python\lib\site-packages\ghp_import\__main__.py", line 192, in main
    if not try_rebase(opts.remote, opts.branch):
  File "e:\python\lib\site-packages\ghp_import\__main__.py", line 78, in try_reb
ase
    if sp.call(cmd) != 0:
  File "e:\python\lib\subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "e:\python\lib\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "e:\python\lib\subprocess.py", line 1194, in _execute_child
    args = list2cmdline(args)
  File "e:\python\lib\subprocess.py", line 754, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'
[2016-01-19T22:45:12Z] ERROR: github_deploy: Failed GitHub deployment \u2014 com
mand ['ghp-import', '-n', '-m', 'Nikola auto commit.\n\nSource commit: e7c6dabef
635f205804e8abee5368e256019aa83\nNikola version: 7.7.4', '-p', '-r', 'origin', '
-b', 'master', 'output'] returned 1
```

**Comment by Kwpolska** [comment]
Does #2227 fix this for you?

**Comment by mondus** [comment]
What is the command to install the un-merged pull request from github using
pip?

P

On 22 January 2016 at 18:33, Chris Warrick <notifications@github.com> wrote:

> Does #2227 <https://github.com/getnikola/nikola/pull/2227> fix this for
> you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getnikola/nikola/issues/2223#issuecomment-174003617>.
>



-- 
Dr Paul Richmond (Research Fellow) - University of Sheffield
http://www.paulrichmond.staff.shef.ac.uk
p.richmond@sheffield.ac.uk

Department of Computer Science <http://www.sheffield.ac.uk/dcs>
Sheffield NVIDIA CUDA Research Centre
<http://gpucomputing.sites.sheffield.ac.uk/>
Advanced Computing Research Centre <http://www.acrc.com>

**Comment by Kwpolska** [comment]
pip install git+https://github.com/getnikola/nikola@fix-2223#egg=Nikola

If that doesn’t work:

    pip install https://github.com/getnikola/nikola/archive/fix-2223.zip

**Comment by mondus** [comment]
no joy. Still get the following error

```
Traceback (most recent call last):
  File "e:\python\lib\site-packages\doit\doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "e:\python\lib\site-packages\doit\cmd_base.py", line 122, in
parse_execut
e
    return self.execute(params, args)
  File "e:\python\lib\site-packages\nikola\plugin_categories.py", line 124,
in e
xecute
    return self._execute(options, args)
  File
"e:\python\lib\site-packages\nikola\plugins\command\github_deploy.py", li
ne 94, in _execute
    check_ghp_import_installed()
  File
"e:\python\lib\site-packages\nikola\plugins\command\github_deploy.py", li
ne 53, in check_ghp_import_installed
    subprocess.check_output([b'ghp-import', b'-h'])
  File "e:\python\lib\subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "e:\python\lib\subprocess.py", line 696, in run
    with Popen(*popenargs, **kwargs) as process:
  File "e:\python\lib\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "e:\python\lib\subprocess.py", line 1194, in _execute_child
    args = list2cmdline(args)
  File "e:\python\lib\subprocess.py", line 754, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'
```

On 22 January 2016 at 19:46, Chris Warrick <notifications@github.com> wrote:

> pip install git+https://github.com/getnikola/nikola@fix-2223#egg=Nikola
>
> If that doesn’t work:
>
> pip install https://github.com/getnikola/nikola/archive/fix-2223.zip
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getnikola/nikola/issues/2223#issuecomment-174024577>.
>



-- 
Dr Paul Richmond (Research Fellow) - University of Sheffield
http://www.paulrichmond.staff.shef.ac.uk
p.richmond@sheffield.ac.uk

Department of Computer Science <http://www.sheffield.ac.uk/dcs>
Sheffield NVIDIA CUDA Research Centre
<http://gpucomputing.sites.sheffield.ac.uk/>
Advanced Computing Research Centre <http://www.acrc.com>

**Comment by mondus** [comment]
No joy install with either

```
pip uninstall nikola
pip install git+https://github.com/getnikola/nikola@fix-2223#egg=Nikola
```
or
```
pip install --upgrade git+https://github.com/getnikola/nikola@fix-2223#egg=Nikola
```

**Comment by Kwpolska** [comment]
This is a ghp-import bug. Pull request [sent upstream](https://github.com/ionelmc/python-ghp-import/pull/1).

**Comment by mondus** [comment]
Fixed using the following.

pip install --upgrade git+https://github.com/getnikola/nikola#egg=Nikola
pip install --upgrade git+https://github.com/ionelmc/python-ghp-import

The github deployment now completes successfully. Thanks for the help.

Paul
