### ISSUE TITLE
Wordpress importer broke on REDIRECTION

### ISSUE THREAD

**Issue by leoboiko** [getnikola/nikola#2224]
I was following the manual:

```bash
$ nikola import_wordpress thenanbanjinnikki.wordpress.2016-01-21.xml
$ cd new_site
$ nikola build
Scanning posts........done!
ERROR: Task generation 'render_site' has duplicated definition of 'redirect:output/nikki/index.html'

$ nikola version
Nikola v7.7.4
$ grep xmlns:excerpt thenanbanjinnikki.wordpress.2016-01-21.xml 
        xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
```

The problem seems to be that `conf.py` had a lot (23) of duplicated  keys of the form `["nikki/index.html", $something]` on `REDIRECTIONS =`.  I've manually commented those, and then the build did work.

**Comment by Kwpolska** [comment]
We need to see your urlmap.csv (should be created by the importer).

Also, how did your post URLs look on WordPress?

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by leoboiko** [comment]
[Here’s `url_map.csv`](https://github.com/getnikola/nikola/files/99888/url_map.csv.txt) (renamed to .txt to make github happy).


The post URLs are title slugs; you can see the original site at http://namakajiri.net/nikki/ . However, I note that most of the duplicated REDIRECTIONS (17 out of 23) point to number-based targets, like this:

```python
["nikki/index.html",
 "/nikki/posts/191.html"],
```

And they all seem to be post drafts.

**Comment by Kwpolska** [comment]
We will probably need to ignore URLs with query strings when creating
redirections. I'll look into it tomorrow.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by Kwpolska** [comment]
We already handle this for pages that go in the web server root. But if your WordPress blog lives in a subdirectory, you get issues like this. I think I have a fix.

**Comment by Kwpolska** [comment]
Patch in #2226 — please test.

**Comment by leoboiko** [comment]
Worked just fine. Thank you!
