### ISSUE TITLE
Automatic teasers

### ISSUE THREAD

**Issue by entron** [getnikola/nikola#2232]
Is there a way to automatically add teasers to long blog post?

**Comment by Kwpolska** [comment]
No. Adding `.. TEASER_END` manually is not hard, and it lets you specify exactly where to break. Doing it automatically is error-prone and can insert the break in bad places.

**Comment by spollard** [comment]
I agree. I just spent a few hours trying to automate finding a reasonable end of a teaser for a post. It's faster for me to go through my 547 blog posts and insert the teaser end manually.
