### ISSUE TITLE
Chinese not rendering correctly in source 

### ISSUE THREAD

**Issue by entron** [getnikola/nikola#2233]
Here is [one example blog post](http://entron.github.io/boke/posts/2014/08/31/li-jie-hong-lou-meng-yao-yong-yin-xing-ma-er-ke-fu-mo-xing.html) in Chinese and I found that [the source](http://entron.github.io/boke/posts/2014/08/31/li-jie-hong-lou-meng-yao-yong-yin-xing-ma-er-ke-fu-mo-xing.md) (click the button at the top right) is not showing Chinese correctly. Is this a bug?

**Comment by Kwpolska** [comment]
Looks good here (Windows 10, Google Chrome)
![image](https://cloud.githubusercontent.com/assets/327323/12812693/b95107e4-cb33-11e5-9f7f-ecf332b6c543.png)


This is an issue with your browser or the server. Nikola just copies the input file (which must be UTF-8) and hopes the web server and browser handle it correctly. The server does not seem to specify an encoding in the headers, so your browser had to guess, and it guessed incorrectly.

PS. this blog post has broken math. Double backslashes must be used with Markdown:

    \\[80 \times 5 = (50+30) \times 5 = 50 \times 5 + 30 \times 5 = 400\\]

**Comment by entron** [comment]
Thanks for the quick response! I changed a theme and it works also correctly now.
