### ISSUE TITLE
base.tmpl template is not using base_footer.tmpl

### ISSUE THREAD

**Issue by humitos** [getnikola/nikola#2234]
Not sure if it's a bug or so, but I will comment it here just in case.

`base.tmpl` from bootstrap3 theme is not using the `html_footer()` helper from `base_footer.html`

base.tmpl
```
        <footer id="footer">
            ${content_footer}
            ${template_hooks['page_footer']()}
        </footer>
```

I think it should say:
```
<%namespace name="footer" file="base_footer.tmpl" import="*"/>
...
${footer.html_footer()}
```

References:
* https://github.com/getnikola/nikola/blob/master/nikola/data/themes/bootstrap3/templates/base.tmpl#L70
* https://github.com/getnikola/nikola/blob/master/nikola/data/themes/base/templates/base_footer.tmpl

**Comment by Kwpolska** [comment]
I’m not sure about this. We don’t use `base_header.tmpl` either, and in my opinion it’s okay to leave things as-is, because we would only complicate the structure by including a new file that changes everything anyway.

Opinions?

**Comment by humitos** [comment]
Yes I think it will break backwards compatibility and that is not a good 
idea.

So, if we don't use those files, why are they there? Don't we should 
remove them?

At least for me this was confusing. I was modifying base_footer.tmpl and 
nothing happened.

El 05/02/16 a las 06:55, Chris Warrick escribió:
> I’m not sure about this. We don’t use |base_header.tmpl| either, and in
> my opinion it’s okay to leave things as-is, because we would only
> complicate the structure by including a new file that changes everything
> anyway.
>
> Opinions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getnikola/nikola/issues/2234#issuecomment-180319298>.
>

-- 

Kaufmann Manuel
-- http://elblogdehumitos.com.ar/

**Comment by Kwpolska** [comment]
Those files *are* used by the base theme, but not by bootstrap3.
