### ISSUE TITLE
Many themes are not mobile friendly

### ISSUE THREAD

**Issue by entron** [getnikola/nikola#2235]
I found a few nice themes are not mobile friendly and still showing the side block leaving almost no space to display main content.

For example: 

https://themes.getnikola.com/v7/material-theme/index.html

https://themes.getnikola.com/v7/oldfashioned/index.html

**Comment by Kwpolska** [comment]
I’m afraid we can’t do a lot about it ourselves. `material-theme` was contributed by an user, and `oldfashioned` is not really supported. If you want, you might ask the theme authors to fix it, or contribute fixes yourself. Note that mobile conversions are hard.

**Comment by Kwpolska** [comment]
(as a clarification: while we **do** believe that mobile users are important, and our default `bootstrap3` theme is fully mobile-friendly, we do not have the resources to make sure every theme works fine on mobile, and we don’t consider themes part of the core product.)
