### ISSUE TITLE
Add an option to disable the generation of the archive page

### ISSUE THREAD

**Issue by xuhdev** [getnikola/nikola#2236]
This would be useful for site creation (not blog)

**Comment by Kwpolska** [comment]
You can just disable the archives plugin, or is that not enough in your opinion?

**Comment by xuhdev** [comment]
Yes, it works. Thanks! Probably adding some instructions in the "create a site" page is useful :)

> You may consider disable the `render_archive` plugin if you don't need a blog.

**Comment by Aeyoun** [comment]
You can also just remove `POSTS = {}` from config. No post, no archives.

**Comment by ralsina** [comment]
Ok, so we're good?
