### ISSUE TITLE
jinjify: convert a single mako template file to jinja?

### ISSUE THREAD

**Issue by xuhdev** [getnikola/nikola#2240]
It looks like jinjify requires a full theme to work. For example, how do you synchronize the two templates in the [projectpages plugin](https://github.com/getnikola/plugins/tree/master/v7/projectpages/templates) with jinjify?

**Comment by Kwpolska** [comment]
Patches welcome. I did the conversions there by creating fake “themes” with templates/ directories and pointing jinjify at them.
