### ISSUE TITLE
rst.css in boostrap3 theme

### ISSUE THREAD

**Issue by humitos** [getnikola/nikola#2243]
First of all: this is strange.

I'm not getting `.. tip::`, `.. note::` and others styled in `bootstrap3` theme.

The steps to reproduce this are:

    mktmpenv -p python3
    pip install webassets nikola
    nikola init --demo -q mysite
    cd mysite/
    nikola new_post -e -t "Add .. tip:: to your file"
    nikola build ; nikola serve

There, you will see in the post you just created the `.. tip::` directive without style.

In the middle, I found there is an outdated file at `./lib/python3.4/site-packages/nikola/data/themes/bootstrap3/assets/css/rst.css` that is not in the github repository. WTF? I don't know how that file went there.

I ran a `diff -u` between the `rst.css` from `base` theme and that you that you can check in the full log link.

You can see my full log here: http://hastebin.com/ebomabanar.diff

Do you know what is happening here?

**Comment by humitos** [comment]
Removing these files is a workaround that works:

    rm output/assets/css/rst.css
    rm output/assets/css/all*.css
    ./lib/python3.4/site-packages/nikola/data/themes/bootstrap3/assets/css/rst.css

And then re-build the site.

**Comment by Kwpolska** [comment]
It looks like I had a leftover `build/` directory with ancient data in it. Sorry. Please re-install. (Wheel files won’t be available from PyPI for this release, tarball only. I’m not creating a new release just because of that.)

**Comment by ralsina** [comment]
Kwpolska: if you recreate the wheel and change the case in one of the letters (Nikola -> nikola) pypi will let you reupload.

**Comment by Kwpolska** [comment]
@ralsina: I tried that, and `twine` didn’t let me.

**Comment by humitos** [comment]
Isnt it enough to release a new one, like 7.7.6?

**Comment by Kwpolska** [comment]
It normally would be. But Nikola takes upwards of 15 minutes to release. Which is far too long.

And this isn’t a *code* issue, merely a *distribution* one.
