### ISSUE TITLE
Extend "nikola build" with an option to automatically rebuild a site if post has been modified

### ISSUE THREAD

**Issue by LenzGr** [getnikola/nikola#2244]
For local development (using `nikola serve`) it would be useful if `nikola build` would provide some kind of "watch" option, in which the build process monitors the `posts` directory for file modifications and triggers an automatic rebuild if a file has been changed and saved. This would simplify the local development workflow, as I could simply switch between my editor and the web browser, without having to switch to the shell for triggering a rebuild manually.

**Comment by Kwpolska** [comment]
It already exists: try running `nikola auto`.

**Comment by LenzGr** [comment]
Awesome, thanks for the quick hint and sorry for the noise :)

**Comment by Kwpolska** [comment]
(on a side note: `nikola auto` will not only rebuild your site, but it will also (try) to refresh your web browser!)

**Comment by LenzGr** [comment]
So I just noticed, after I fixed the `OSError: inotify watch limit reached` error I first ran into - cool stuff!

We use Nikola to serve our blog at http://blog.openattic.org/ and really like it. Keep up the good work!
