### ISSUE TITLE
In some cases posts generate conflicting cache files and shouldn't

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2246]
If you have markdown (.md) and rst (.rst) posts with the same name and different extension and slug, they conflict on the cache:

```
$ ls posts/
fo.md  fo.rst

$ nikola build
Scanning posts......done!
ERROR: Task generation 'render_site' has duplicated definition of 'render_posts:cache/posts/fo.html'
```

Solution is probably to use something like ```fo.rst.html``` and ```fo.md.html``` as cache filenames.

**Comment by ralsina** [comment]
OH HELL this is bad. We are using post.base_path (which contains CACHE_FOLDER, BTW) in a bunch of places as unique post identifiers. So, ugh.

**Comment by SpotlightKid** [comment]
I'm being bitten by this error as I'm trying to build a site with posts imported from my Wordpress blog:

```
$ nikola --conf=conf-dev.py build
[2016-04-07T18:05:12Z] INFO: Nikola: Using config file 'conf-dev.py'
Scanning posts...........done!
ERROR: Task generation 'render_site' has duplicated definition of 'render_tags:output/categories/midi.xml'
```

I'm not sure where to fix it. The import has only generated `.md` and `.meta` files, so it's not about conflicting ReST and markdown source files.

**Comment by Kwpolska** [comment]
That’s a different error. Please report a bug and check how your tags look — perhaps there is something that duplicates `midi.xml`, or you have a conflict between tags and categories?

**Comment by Kwpolska** [comment]
This is a different problem, please create a new issue. Also, check how your tags and your configuration look. This could be some unusual conflict (we are trying to generate tag XML two times). Are your tags and categories prefixes different? Can you reproduce in a clean site (without your config file)?

**Comment by ralsina** [comment]
Sadly, fixing this bug implies breaking comments for most existing users and that is just unacceptable.
