### ISSUE TITLE
Support easy customization of index page

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2249]
A lot of people want to add a welcome message to their page. We should support a setting that takes HTML to be displayed in /index.html, above all posts.

**Comment by ralsina** [comment]
Fixed in #2253

**Comment by Kwpolska** [comment]
(oh, I forgot about this issue.)

**Comment by dacoex** [comment]
how is this `FRONT_INDEX_HEADER` setting used?

**Comment by Kwpolska** [comment]
Just put any HTML there (in a translatable dict format, or as a regular string), and it will be displayed on the index page of your site, above all posts.
