### ISSUE TITLE
web ui as lektor

### ISSUE THREAD

**Issue by humitos** [getnikola/nikola#2250]
Did you know https://www.getlektor.com/?

It's a static site generator with a web based ui where you can write your posts.

Is this a direction that Nikola would like to follow?

As a comments:
* the installer that it's on their web page did work for me
* I tried with pip and py3 and it gave me SyntaxError
* It seems to work just with py2
* there is a typo on the first command "We jsut need"
* the web ui is very simple and easy to use to just write; I uploaded an image but I don't know how to include it on the post

Anyway, I think we should take a look at this at least.

**Comment by Kwpolska** [comment]
We already have an optional web application for managing a blog. It's
barebones, but you can try it out — search for Coil CMS on our features
page or on our GitHub organisation.

(Contributors welcome!)

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by gour** [comment]
:+1: 

Nikola is, imho, much more mature than Lektor, it works with Python3, rst is 1st class markup etc., so it's a pity not to have better web-ui to compete with Lektor or even with PHP-based Grav. :-(

**Comment by ralsina** [comment]
@gour and we may get it sometime. It's a matter of doing it.

**Comment by gour** [comment]
@ralsina Well, "we may get it..." sounds much better than "we're not interested at all!" :smile: 

I'd like to avoid using PHP (Grav) and trying to be able to cover all my/our needs with Nikola, if possible...so, will add another feature request. :wink:

**Comment by Kwpolska** [comment]
Coil CMS exists, and while it might not do much, it sorely lacks people who actually care and want to contribute (I don’t.)

I’ll close this.
