### ISSUE TITLE
RSS Enclosure size is always 0

### ISSUE THREAD

**Issue by roman-yepishev** [getnikola/nikola#2251]
As per https://github.com/getnikola/nikola/pull/1323/files#diff-2084399e4870b745162c10b0cae1ef0fR171:

```
+def _enclosure(post, lang):
+    '''Default implementation of enclosures'''
+    enclosure = post.meta('enclosure', lang)
+    if enclosure:
+        length = 0
+        url = enclosure
+        mime = mimetypes.guess_type(url)[0]
+        return url, length, mime
```

While this is valid, this makes it look weird in the RSS feed in firefox (is the file empty? is it a bug?):

![screenshot from 2016-02-15 18-23-34](https://cloud.githubusercontent.com/assets/601685/13062984/55e17afe-d411-11e5-8c2f-a02afb4eb2b6.png)

**Comment by Kwpolska** [comment]
I’ve seen bigger services do this. Do you know of any things that actually care and break if the value is wrong? Solving it might be hard, because we would need to get that file, and it might not be local.

**Comment by ralsina** [comment]
Maybe we can put nothing there? Or -1? Or at least check if the file is local, although it's not exactly trivial since we're given a URL.

Also, depending on "things" the file may not even be there or may be the wrong size at the point when this runs.

**Comment by Kwpolska** [comment]
That has to be [accepted behavior](http://www.npr.org/rss/podcast.php?id=510299).

![image](https://cloud.githubusercontent.com/assets/327323/13150073/6e17d71c-d664-11e5-88a7-afb77a4ea111.png)

**Comment by ralsina** [comment]
I agree. If it's good enough for NPR it's good enough for us.

**Comment by Kwpolska** [comment]
(PS. You should totally listen to Ask Me Another.)

**Comment by roman-yepishev** [comment]
Well, I tried various podcast software and had not encountered any issue with the length of 0. So this is just something I noticed while browsing my own feed.
Now, adding anything that would go to the internet and fetch the Content-Length to nikola itself may be an overkill, so I am thinking about doing some post-processing on my generated feed.

Feel free to close as "good enough".
