### ISSUE TITLE
dr-nikolas-vendetta.rst licensing

### ISSUE THREAD

**Issue by aidecoe** [getnikola/nikola#2255]
Text of "A Bid for Fortune; or Dr. Nikola's Vendetta" is taken from Gutenberg Project which publishes text under non-free licenses. This is incompatible with free license of Nikola project and causes problems with packaging. In Gentoo we have replaced "A study in scarlet" from Gutenberg Project with free version from literature.org. Since "A study in scarlet" has been replaced with "A Bid for Fortune; or Dr. Nikola's Vendetta" the issue is coming back. Would it be possible to include free version in Nikola project for this text and any future sample text?

It may sound silly, but it's actually an issue which needs to be solved before providing new version to users in Gentoo and probably other distros...

**Comment by ralsina** [comment]
Just don't ship it.

**Comment by ralsina** [comment]
Or maybe extract the text from here, which seems to be public domain. http://www.feedbooks.com/book/6636/a-bid-for-fortune-or-dr-nikola-s-vendetta

**Comment by aidecoe** [comment]
Unfortunately it's from Gutenberg Project as well:
Source: Project Gutenberg Australia http://gutenberg.net.au/ebooks06/0601591h.html

It's hard to find actual public domain version. So either we won't ship this text with package or you could revert to "A study in scarlet" for which free version can be found on literature.org or just here: https://dev.gentoo.org/~yngwin/distfiles/a-study-in-scarlet.txt

**Comment by ralsina** [comment]
I'd say don't ship it, then.

**Comment by Kwpolska** [comment]
According to [Project Gutenberg](https://www.gutenberg.org/wiki/Gutenberg:No_Sweat_of_the_Brow_Copyright):

> Work performed on a public domain item, known as sweat of the brow, does not result in a new copyright. This is the judgment of Project Gutenberg's copyright lawyers, and is founded in a study of case law in the United States.

Since the author died 111 years ago, the book is considered public domain all over the world. What makes it non-free?

**Comment by aidecoe** [comment]
Citing our licenses specialist, ulm: "it is nonfree, due to clause 1.E.7 "Do not charge a fee ..." from http://www.gutenberg.org/wiki/Gutenberg:The_Project_Gutenberg_License
But I am not going to be a proxy in any argument on licensing black magic. We'll just remove this example text from the package and we're done.

**Comment by Kwpolska** [comment]
Outright removing might be problematic (demo site might have issues). You should replace it with Lorem Ipsum and/or some © information. And make sure you like the license of the /images/, too.
