### ISSUE TITLE
Refresh theming.txt

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2259]
It needs updating with current list of things passed to each template, specially things that are available in all templates.

**Comment by Kwpolska** [comment]
Preferably, in sanely organized tables, and not in running text/prose.

**Comment by felixfontein** [comment]
Isn't this what @Kwpolska just did?

**Comment by Kwpolska** [comment]
It is. I also updated `theming.txt` now.

Closing three issues with one thing means quite a lot.
