### ISSUE TITLE
optional import_wordpress to single file

### ISSUE THREAD

**Issue by davidak** [getnikola/nikola#2262]
instead of separate content and meta data

**Comment by ralsina** [comment]
Should not be horribly hard now that Post objects can sort of save themselves.

**Comment by felixfontein** [comment]
How about adding a new function to `basic_import` which allows to store metadata and content at the same time, and then changing the WordPress importer plugin to use this function? Then we can add a flag to `basic_import` which decides whether that new function stores the result in two files (by calling the existing methods, for example) or into one.

**Comment by Kwpolska** [comment]
You just need to talk to a compiler’s `create_post` function, and provide the content to it (it’s already done by `nikola new_post -i` and Coil CMS). You don’t really need a new function for that.

**Comment by felixfontein** [comment]
The functions in `basic_import` also take care of rewriting HTML if asked to, so either that functionality has to be refactored somewhere else, or another function is needed (which can call compiler's `create_post`).

**Comment by ralsina** [comment]
Specifically, this code in import_wordpress.py and the methods it calls in basic_import.py need refactoring:

```python
                self.write_metadata(os.path.join(self.output_folder, out_folder,
                                                 out_meta_filename),
                                    title, meta_slug, post_date, description, tags, **other_meta)
                self.write_content(
                    os.path.join(self.output_folder,
                                 out_folder, out_content_filename),
                    content,
                    rewrite_html)
```

I would do a write_post in basic_import.py and just let that one sort it out. Not sure how many other importer plugins need touching to use that, so probably just add that new method and keep the current ones too.

**Comment by ralsina** [comment]
Oh what the heck, in progress.

**Comment by ralsina** [comment]
Done
