### ISSUE TITLE
Nikola output is garbage for a Jupyter notebook

### ISSUE THREAD

**Issue by geekraver** [getnikola/nikola#2269]
I've just tried my first notebook post and the result is just a mess. You can see the end result at http://www.grahamwheeler.com/posts/using-jupyter-as-a-music-notebook.html. I have attached the notebook and the HTML that Nikola generated.

[jupyter.zip](https://github.com/getnikola/nikola/files/149464/jupyter.zip)

**Comment by Kwpolska** [comment]
Cannot reproduce. This looks like something that would be done by an ancient Nikola version. Please upgrade to the most recent version and try again.

**Comment by geekraver** [comment]
I am using the latest version. Created a new virtualenv and installed last
night.

**Comment by Kwpolska** [comment]
That’s really unusual.

* What does `python --version && nikola version` say?
* What version are your Jupyter-related packages (`nbconvert` in particular)?
* How does `cache/posts/<name of your post>.html` look?
* Have you made any customizations to the config file or the theme?

**Comment by geekraver** [comment]
(nikola)GramMBP:grahamwheeler gram$ nikola version
Nikola vv7.7.6
(nikola)GramMBP:grahamwheeler gram$ python --version
Python 3.5.1 :: Continuum Analytics, Inc.
(nikola)GramMBP:grahamwheeler gram$ jupyter nbconvert --version
4.1.0

The cache/posts version of the HTML looks fine; it has the notebook content.

I'm using an uncustomized zen-ipython theme.

**Comment by Kwpolska** [comment]
Please try creating a `using-jupyter-as-a-music-notebook.meta` file like this:

```
.. title: Using Jupyter as a Music Notebook
.. slug: using-jupyter-as-a-music-notebook
.. date: 2016-02-27 20:00:00 UTC
```

Does it fix your problems?

Also, I can’t run zen-ipython here.

**Comment by geekraver** [comment]
The theme is at https://themes.getnikola.com/#zen-ipython

Adding the meta file did not help, unfortunately.

**Comment by Kwpolska** [comment]
I got the file name wrong; it should match your ipynb file — it should be posts/Using Jupyter as a Music Notebook.meta

Open `nikola console` and try:

```python
print(site.timeline[0].source_path)
print(site.timeline[0].title())
print(site.timeline[0].text())
```

(you might need to adjust [0])

**Comment by geekraver** [comment]
Yes, that's actually what I did for the meta file anyway.

Console output:

In [1]: print(site.timeline[0].source_path)
    posts/Using Jupyter as a Music Notebook.ipynb
    
    In [2]: print(site.timeline[0].title())
    Using Jupyter as a Music Notebook
    
    In [3]: print(site.timeline[0].text())
    <body><p>!   D   O   C   T   Y   P   E       h   t   m   l   &gt;
       <dic8 _recurs="None):" if is none: fulluri="makeFullURI(uri)" try: data="/posts/_gatekeeper.get(fulluri," check="False)" except: return this already a feed couldbefeeddata newuri="tryBrokenRedirect(data)" and not in _recurs: _recurs.append feeds all="all," querysyndic8="querySyndic8," nope it page try link tags first _debuglog for outfeeds="getLinks(data," through len or outfeeds: no look regular> links that point to feeds
            _debuglog('no LINK tags, looking at A tags')
            try:
                links = getALinks(data, fulluri)
            except:
                links = []
            locallinks = getLocalLinks(links, fulluri)
            # look for obvious feed links on the same server
            outfeeds.extend(filter(isFeed, filter(isFeedLink, locallinks)))
            if all or not outfeeds:
                # look harder for feed links on the same server
                outfeeds.extend(filter(isFeed, filter(isXMLRelatedLink, locallinks)))
            if all or not outfeeds:
                # look for obvious feed links on another server
                outfeeds.extend(filter(isFeed, filter(isFeedLink, links)))
            if all or not outfeeds:
                # look harder for feed links on another server
                outfeeds.extend(filter(isFeed, filter(isXMLRelatedLink, links)))
        if all or not outfeeds:
            _debuglog('no A tags, guessing')
            suffixes = [ # filenames used by popular software:
              'atom.xml', # blogger, TypePad
              'index.atom', # MT, apparently
              'index.rdf', # MT
              'rss.xml', # Dave Winer/Manila
              'index.xml', # MT
              'index.rss' # Slash
            ]
            outfeeds.extend(filter(isFeed, [urlparse.urljoin(fulluri, x) for x in suffixes]))
        if (all or not outfeeds) and querySyndic8:
            # still no luck, search Syndic8 for feeds (requires xmlrpclib)
            _debuglog('still no luck, searching Syndic8')
            outfeeds.extend(getFeedsFromSyndic8(uri))
        if hasattr(__builtins__, 'set') or __builtins__.has_key('set'):
            outfeeds = list(set(outfeeds))
        return outfeeds
    
    getFeeds = feeds # backwards-compatibility
    
    def feed(uri):
        #todo: give preference to certain feed formats
        feedlist = feeds(uri)
        if feedlist:
            return feedlist[0]
        else:
            return None
    
    ##### test harness ######
    
    def test():
        uri = 'http://diveintomark.org/tests/client/autodiscovery/html4-001.html'
        failed = []
        count = 0
        while 1:
            data = _gatekeeper.get(uri)
            if data.find('Atom autodiscovery test') == -1: break
            sys.stdout.write('.')
            sys.stdout.flush()
            count += 1
            links = getLinks(data, uri)
            if not links:
                print '\n*** FAILED ***', uri, 'could not find link'
                failed.append(uri)
            elif len(links) &gt; 1:
                print '\n*** FAILED ***', uri, 'found too many links'
                failed.append(uri)
            else:
                atomdata = urllib.urlopen(links[0]).read()
                if atomdata.find('<link rel="alternate" print failed uri something that is not a feed failed.append else: backlink="atomdata.split('href=&quot;').pop().split('&quot;')[0]" if uri: wrong data.find href="/posts/')%20==%20-1:%20break%0A%20%20%20%20%20%20%20%20uri%20=%20urlparse.urljoin(uri,%20data.split('&lt;link%20rel=" next count executed len></dic8></p></body>

**Comment by geekraver** [comment]
Needless to say, that text is nothing like what is in my notebook

**Comment by geekraver** [comment]
I changed the file name to be lower case with hyphens and ran it again, and now it has included some other stuff in that file from a later post.

**Comment by geekraver** [comment]
I tried going back to the bootstrap theme to make sure it wasn't the theme that was the problem. Things were still messed up, so switched back to Zen.

**Comment by Kwpolska** [comment]
That’s something really unusual. The code comes from http://www.aaronsw.com/2002/feedfinder/feedfinder.py. Do you have this anywhere in your file system where it could trip up lxml?

To debug this, we would need to a few prints. Open `post.py`, find [the `Post.text` method](https://github.com/getnikola/nikola/blob/master/nikola/post.py#L564), and `print()` out the following:
* `file_name` after line 579
* `data` after line 588
* `document` after line 601
* `data` after line 609

Also, it could be useful to print `lxml`, `lxml.html`, `lxml.html.fromstring`, `lxml.html.tostring`.

**Comment by geekraver** [comment]
I added all of those prints, removed the .ipynb and .html files for that notebook in the outputs directory, and did a `nikola build` and nothing was printed. Then I did a `nikola clean` and `'nikola build` and still nothing.

Is the output from print() being redirected or is print being monkey-patched or something?

**Comment by geekraver** [comment]
I've just tried this on a different machine, and it seems to be working fine. So something must be messed up with the one environment. Will dig some more. Thanks for the help so far.

**Comment by geekraver** [comment]
Ok, interesting. I went to the machine that was working, removed my Anaconda installation, and installed the 64-bit Python 3.5 based Anaconda distribution like I have on my laptop, created a new virtualenv (with `conda create -n nikola3 pip`) and pip installed nikola, jinja2, markdown and webassets, and did a clean and build of the site, and now I have a garbage output on that machine too. So it has something to do with the different environments generated by the two different Anaconda versions.

I ran both build under trace but it was hard to do much useful with the nearly 7 million lines generated just for rebuilding that one post. 

For now I'll go back to the 2.7 version of Anaconda and just use it to generate my Python 3 virtual envs seeing as that seems to work.

**Comment by Kwpolska** [comment]
This is most likely an Anaconda issue. Try using a regular Python install (from eg. Homebrew).

To make the print statements work: `nikola clean && nikola build -v 2`

**Comment by Kwpolska** [comment]
(you may also want to make an edit to your .ipynb file and not run `nikola clean`)

**Comment by geekraver** [comment]
Sorry for the delay, finally got some time to look into this again.

- file_name cache/posts/using-jupyter-as-a-music-notebook.html

- data at 588 is an html document that looks correct; has the notebook content

- document <Element body at 0x107816c28> (str(document) outputs the same)

- data at 609 is messed up:

    <body><p>!   D   O   C   T   Y   P   E       h   t   m   l   &gt;
       </p></body>

**Comment by Kwpolska** [comment]
It seems to be a bug in lxml. But because it’s Anaconda-specific, I think you should start by reporting an Anaconda bug. I’m sorry, I can’t help you here…

But what if you replaced `document.body` with just `document` on line 607? Could it help?

**Comment by Kwpolska** [comment]
Closing due to no response and this being someone else’s bug.
