### ISSUE TITLE
Filter issues (runinplace)

### ISSUE THREAD

**Issue by Jurramach** [getnikola/nikola#2270]
I'm using nikola 7.7.6. I created my own filter following the instructions (https://getnikola.com/handbook.html#post-processing-filters).

This is the relevant part of my _conf.py_:

```
from nikola import filters
def htmlcomp(infile):
    return runinplace(r'java -jar /path-to/htmlcompressor-1.5.3.jar -t html %1 -o %2', infile)

FILTERS = {
   ".html": [filters.htmlcomp],
}

```

When I build the site with  _nikola build_, I get this error:

```
########################################
TaskError - taskid:render_archive:output/2016/index.html
PythonAction Error
Traceback (most recent call last):
  File "/path-to-my-virtualenv/lib/python3.4/site-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/path-to-my-virtualenv/lib/python3.4/site-packages/nikola/utils.py", line 906, in unlessLink
    action(target)
  File "conf.py", line 596, in htmlcomp
    return runinplace(r'java -jar /path-to/htmlcompressor-1.5.3.jar -t html %1 -o %2', infile)
NameError: name 'runinplace' is not defined
```

For some reason, the function _runinplace_ is not found although "filters" has already been imported and this function is defined in the _filters.py_ file.

I can only use my own filters by modifying the filters.py file and adding my own filter function after the _runinplace_ function definition. Tha'ts the relevant part of my _filters.py_:

```
def runinplace(command, infile):
    """Run a command in-place on a file.

    command is a string of the form: "commandname %1 %2" and
    it will be execed with infile as %1 and a temporary file
    as %2. Then, that temporary file will be moved over %1.

    Example usage:

    runinplace("yui-compressor %1 -o %2", "myfile.css")

    That will replace myfile.css with a minified version.

    You can also supply command as a list.
    """
    if not isinstance(command, list):
        command = shlex.split(command)

    tmpdir = None

    if "%2" in command:
        tmpdir = tempfile.mkdtemp(prefix="nikola")
        tmpfname = os.path.join(tmpdir, os.path.basename(infile))

    try:
        list_replace(command, "%1", infile)
        if tmpdir:
            list_replace(command, "%2", tmpfname)

        subprocess.check_call(command)

        if tmpdir:
            shutil.move(tmpfname, infile)
    finally:
        if tmpdir:
            shutil.rmtree(tmpdir)

def htmlcomp(infile): #This is my addition
    return runinplace(r'java -jar /path-to/htmlcompressor-1.5.3.jar -t html %1 -o %2', infile)
```

Now I must change my _conf.py_ like this:

```
from nikola import filters
FILTERS = {
   ".html": [filters.htmlcomp],
}
```

I've eventually managed to make it work, but I shouldn't have needed to modify nikola's source code to make it work. Following the instructions should be enough. So please, can you fix it.

Just in case, I test it in a new virtual environment and the only way to make it work is changing the filters.py file.

**Comment by Kwpolska** [comment]
```py
from nikola import filters
def htmlcomp(infile):
    return runinplace(r'java -jar /path-to/htmlcompressor-1.5.3.jar -t html %1 -o %2', infile)
```

With this import line, you should use `filters.runinplace`. Alternatively, you could also use `from nikola.filters import runinplace`.

(Please test with a “clean” copy of Nikola.)

**Comment by Kwpolska** [comment]
(I added an import line to the example to clear up the confusion.)

**Comment by Jurramach** [comment]
Following your advice, I changed _return runinplace(...)_ to _filters.return runinplace(...)_ in a clean install and it's working fine. This is the relevant part of my _conf.py_ file:

```
from nikola import filters

def htmlcomp(infile):
    return filters.runinplace(r'java -jar /path-to/htmlcompressor-1.5.3.jar -t html %1 -o %2', infile)

FILTERS = {
   ".html": [htmlcomp],
}
```

Thank you very much (especially because it's sunday).
