### ISSUE TITLE
Support tags in pages

### ISSUE THREAD

**Issue by davidak** [getnikola/nikola#2274]
i would like to use tags in pages.

then the visitors can find pages from the tag list.

also private posts and drafts should work then for pages.

https://getnikola.com/handbook.html#drafts

if someone don't want to use tags, he don't has to.

**Comment by tritium21** [comment]
I am minus zero on this.  (I don't like the idea, but won't be offended if someone puts in the work and commits it).

Tags serve a purpose.  they allow you to categorize semi-dynamic data.  About the most dynamic thing in nikola is the post.  It makes sense to tag posts - there are lots of them and they are changing often.

Pages are designed to be much more slower moving.  They are really well suited to be categorized by their inherent structure on the site.  They really lend themselves to being manually added to navigation and the like.

I do not really see why it makes sense to allow tagging for pages, when other means of adding taxonomy to a structure of pages exists.

I am actively -1 on these:

* Private posts does not make any sense at all for pages - pages are not automatically linked anywhere. 
* Same for drafts if you deploy drafts.

**Comment by Kwpolska** [comment]
Actually, pages are automatically linked on story indexes.

For anyone wondering, this is @davidak’s use case:

> 2016-02-25.log:15:13:38 <davidak> hello. i am planing to migrate a wordpress and a dokuwiki to nikola. it will have a very minimalistic design where you can find articles from tags or archive. how can i structure pages so users find interesting topics? can i also display pages on tag pages? my first idea was a 'all pages' site, but that would be very chaotic because i have all topics i'm interested in there…

**Comment by felixfontein** [comment]
I don't mind having tags for pages as well. I'm not sure whether I will use them, but I understand that they can be very useful in some usecases, especially when Nikola is used for a site which is not a blog.

What I do mind, though, is adding them to the current state, before proceeding with #2107. Otherwise we'll just have a larger mess to clean up somewhen later.

**Comment by davidak** [comment]
To explain my usecase i show you my current state: https://davidak.basecom.de/webseite-2016/seiten/

My personal website should contain a blog and other pages with informations that are longer relevant than the time of writing.
i think a blog post is written once, maybe corrected multiple times in the near future but then disappears in the archive.
the content of a wiki should be always relevant (considerable of the last edit date). currently i have a wiki but since i'm the only editor i would like to have it in the site to have the same design and be able to write ReST. I already have a lot documentation in ReST laying around that someone could find useful.

It would be nice to find page content in tag index (and in "similar posts" when such a plugin is created).

I use the [post-list](https://getnikola.com/handbook.html#post-list) directive in the linked page. As you see it is ugly that the page itself is linked. also some "meta-pages" should not get linked like startpage and imprint. so i would tag them `private `.

i'm fine to wait for #2107.

**Comment by Kwpolska** [comment]
There are some design problems to consider when it comes to those tag pages:
* Do we have “tags in posts” and “tags in pages” on separate pages?
* If we don’t, how do we display pages? And how do we sort them?
* If we do, how will tags without pages look like? Or tags without posts? And what if someone does not use tags in pages?

On a side note, the tag page looks awful if you have that many tags (380). It could use an alternate template that puts them under letter headings.

(Your current page can be (mostly) created with STORY_INDEX=True in the config, btw.)

**Comment by davidak** [comment]
>Do we have “tags in posts” and “tags in pages” on separate pages?

I think it would make most sense to have the same tag on posts and pages.

>If we don’t, how do we display pages? And how do we sort them?

just like posts, by date?

>And what if someone does not use tags in pages?

then we have the same situation as now. only objects with tags get displayed, in that case posts.

>tag page looks awful

yes. i will change the whole design. still working on content import. i correct the markup of every imported post and try to delete more tags. i had over 1500 in wordpress...

i use a page for index, so STORY_INDEX don't work.

**Comment by Aeyoun** [comment]
> > On a side note, the tag page looks awful if you have that many tags (380)

> yes. i will change the whole design [… ] to delete more tags

That is why we have the `TAGLIST_MINIMUM_POSTS` option. Use it to hide arcane tags applied to only a handful of posts. By default this is set to 1 (all tags are shown), but the number should be incremented as the total number of tags and posts grow.

**Comment by vincent-ferotin** [comment]
New user of Nikola, used for my professional website (only pages, no posts), I also need that tags work with pages, to offer additional walking to visitors in a dense content.
Also, I spend some time to try understand why my tags on pages didn't work -- that is, this is not the default behavior I expected (and its not directly documented as is)...

**Comment by ralsina** [comment]
I still don't know what tags in pages are supposed to do.

**Comment by ralsina** [comment]
And since nobody has explained that in 4 years...

**Comment by davidak** [comment]
@ralsina it was explained in the issue description and https://github.com/getnikola/nikola/issues/2274#issuecomment-192872587. what is unclear here?

I still have an index site for all pages which get's longer while i add more. I use it like a wiki and keep them up-to-date.

https://davidak.de/seiten/

It would be good if i can find pages by viewing the tag page.

https://davidak.de/thema/

https://davidak.de/thema/3d/

here are just articles. pages could be on top:

```
Pages with tag x
...

Articles with tag x
...
```

**Comment by ralsina** [comment]
No it's not explained in the description. In the tags page you have a list of tags. 

For each tag you have what looks like a "mini blog". Posts in descending date ordering, a RSS feed, and so on.

How do pages fit in that? Adding a metadata field to pages is not any work, you can probably tag pages now! But what should Nikola do with those tagged pages? What new pages should Nikola create? How should it modify the existing tag pages?

Without that it's not a proposal, just an idea.

**Comment by davidak** [comment]
>Without that it's not a proposal, just an idea.

yes, it's just an idea. i don't have a detailed proposal right now

**Comment by ralsina** [comment]
Ok, I will make sure pages can take tags, and then I'll check if template changes are enough to implement what you mention above. At that point, if you or someone else needs the feature he can do the last bit.

**Comment by ralsina** [comment]
I can confirm that pages can be tagged:

![image](https://user-images.githubusercontent.com/1579/79175619-97b54700-7dd4-11ea-8133-fd55c9da5a4a.png)

**Comment by davidak** [comment]
>then I'll check if template changes are enough to implement what you mention above. At that point, if you or someone else needs the feature he can do the last bit.

yes that would solve the presentation. but i don't know what to do about RSS feeds. maybe add new pages like articles? what happens in general when you update an article? will it get added again to RSS feeds? so when i edit it 10 times, update the changed date and publish each time, will it be 10 times in RSS feed or just once with the latest date? but users that already have the last update in their reader will get a new entry?

**Comment by davidak** [comment]
>I can confirm that pages can be tagged:

are the tags used in HTML metadata? that would help with search engines etc

**Comment by ralsina** [comment]
I don't know if it's used in meta tags, have not checked.

Putting pages on RSS feeds makes no sense at all. Pages have no dates.

**Comment by ralsina** [comment]
Yes, pages tags are used as meta tags:

![image](https://user-images.githubusercontent.com/1579/79207208-c9e79880-7e16-11ea-82ed-f6a2d7911ce5.png)

**Comment by ralsina** [comment]
You could get nikola pages listed in tags pages just by changing `apply_to_pages` set to `True` in the `ClassifyTags` class.

However, that creates useless output, where pages are treated exactly like posts, with dummy dates.

The taxonomy stuff is not my favourite, it's complicated and I have little idea how it works.

So, further research needed.

**Comment by ralsina** [comment]
And there you go.

https://github.com/getnikola/plugins/tree/master/v8/tagged_pages

It's not exactly what I would call production quality but it worked in the little testing I did.
