### ISSUE TITLE
nikola plugin install dependency with pip in wrong python version

### ISSUE THREAD

**Issue by davidak** [getnikola/nikola#2275]
i use Nikola with python3, so it has to use pip3 to install dependencys

example: `nikola plugin -i import_page`

**Comment by ralsina** [comment]
So, for python 2 it's guaranteed to be available as pip2 and for python 3 as pip3, right?

**Comment by davidak** [comment]
no, it's not that simple

**Comment by ralsina** [comment]
how isn't it that simple? Anyone has a python 2 without a pip2 and a python3 without a pip3?

**Comment by ralsina** [comment]
Alternatively, it's possible to use pip as a module but I don't have details.

**Comment by Aeyoun** [comment]
Some distros use `pip3.4` with no `pip3` alias. Using the module would probably be a better solution.

**Comment by ralsina** [comment]
Doesn't look very hard. For example, this works:

```python
import pip
pip.main(['freeze'])
```

**Comment by ralsina** [comment]
Blah, pip is really weird. Working through it but it sucks.

**Comment by ralsina** [comment]
Yep, totally not doing this. Sorry.

**Comment by davidak** [comment]
>If it fails to call pip

it just calls `pip` and installs it in the wrong version. can we prevent that?

**Comment by ralsina** [comment]
We can make it stop trying to install things at all.

**Comment by davidak** [comment]
it could just display the command.

**Comment by ralsina** [comment]
And then this bug would be "it's printing the wrong command, I ran it and
it installed things in the wrong python"

**Comment by Kwpolska** [comment]
We could use `sys.executable` for this.
