### ISSUE TITLE
add highlight directive

### ISSUE THREAD

**Issue by dacoex** [getnikola/nikola#2278]
Please add the following directive to set the principal highlighting language at the top of the page:

`.. highlightlang:: python`

In sphinx this is included here:
http://www.sphinx-doc.org/en/stable/_sources/config.txt

**Comment by ralsina** [comment]
While I can add it to enhance our compatibility with sphinx, I can't implement it in a working manner.

IIRC Sphinx basically has a copy of an old version of docutils' syntax highlighting code in order to do this, and I am not going to do such a thing.

**Comment by dacoex** [comment]
I was looking after a convenient method to define all code in a page as same markup.

Feel free to close.
