### ISSUE TITLE
Add an option for "nikola plugin -i" to install dependencies in user's directory (corresponding to `pip install --user`)

### ISSUE THREAD

**Issue by xuhdev** [getnikola/nikola#2279]
Currently it is hardcoded that pip is called to install everything in the global directory. It makes sense to allow users to install dependencies in their home directories.

**Comment by Kwpolska** [comment]
:-1:. You should really be using a virtualenv.

**Comment by xuhdev** [comment]
@Kwpolska That's even better if nikola creates a virtual env for the site, for requirements by the plugins.

**Comment by Kwpolska** [comment]
No, we’re not doing that. You are supposed to take care of it yourself. Our Getting Started guide recommends virtualenvs, and we hope every user does that themselves.

**Comment by ralsina** [comment]
Hong: if you get things installed globally, that means you were running
"nikola plugin -i" as root. That's a much bigger issue :-)

**Comment by xuhdev** [comment]
@ralsina You don't need to run it ad root; Nikola and its dependencies can be installed at home (via pip install --user), so it's global just for me. Its more convenient in this case, as I do not run multiple versions of Nikola and I frequently use Nikola.

**Comment by ralsina** [comment]
@xuhdev I mean, if you are not root, it will fail and tell you "go ahead and install dependencies yourself". It would be worse if it succeeded.

**Comment by xuhdev** [comment]
OK, maybe just being a little more clear on the message is good enough. I suggest

    Contents of the requirements.txt file

to be changed to

    Dependencies of the plugin listed in `/path/to/requirements.txt`:

when the installation of dependencies fail.

**Comment by Kwpolska** [comment]
That’s not the full error message:

```
                LOGGER.error('Could not install the dependencies.')
                print('Contents of the requirements.txt file:\n')
                with io.open(reqpath, 'r', encoding='utf-8') as fh:
                    print(utils.indent(fh.read(), 4 * ' '))
                print('You have to install those yourself or through a '
                      'package manager.')
```

**Comment by xuhdev** [comment]
Right, I meant the part in the middle. Probably someone who does not use Python would be confused by what "requirements.txt" means.
