### ISSUE TITLE
override variable like SITE_URL in different deployments

### ISSUE THREAD

**Issue by davidak** [getnikola/nikola#2285]
from the config, `SITE_URL` is "the URL where Nikola's output will be deployed."

So when you deploy to a different location, you probably have a different domain.
I suggest a solution where you can override **any** variable in the deployment settings. so you are very flexible.
 
current deployment settings:
```
DEPLOY_COMMANDS = {
    'default': [
        "rsync -rav --delete output/ joe@my.site:/srv/www/site",
    ],
    'staging': [
        "rsync -rah --progress --delete output/ root@dkl.cust.basecom.de:/var/www/davidak.basecom.de/webseite-2016",
    ]
}
```

suggestion:
```
if deploy_target == 'default':
    DEPLOY_COMMANDS = [ "rsync -rav --delete output/ joe@my.site:/srv/www/site" ]
elif deploy_target == 'staging':
    SITE_URL = "https://davidak.basecom.de/webseite-2016/"
    DEPLOY_COMMANDS = [
        "rsync -rah --progress --delete output/ root@dkl.cust.basecom.de:/var/www/davidak.basecom.de/webseite-2016",
        "say 'deployment to staging completed!'"
    ]
else:
    print("No command for deploy target {}".format(deploy_target))
```

but you can't change something like SITE_URL without rebuilding the output!
one solution would be to build to `output/` or `output_staging/`.

**Comment by ralsina** [comment]
The solution to all these use-cases is using multiple conf.py files.

**Comment by Kwpolska** [comment]
Also, you can’t do that with `deploy`. `deploy` is generally meant to run commands like `rsync`, maybe a `nikola check`, but it’s not building anything. You could try adding a `nikola build` with the appropriate config file to your deployment commands, but `build` and `deploy` are separate concepts in our minds.
