### ISSUE TITLE
Some plugins call exit()

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2288]
And they should not. Calling exit() breaks ```nikola build -c``` and makes working on "damaged" sites, like what comes from importing wordpress, harder.

**Comment by felixfontein** [comment]
We already had an issue for this earlier: #1839.

**Comment by ralsina** [comment]
@felixfontein indeed we do! Dupe of #1839

**Comment by ralsina** [comment]
I think this was fixed already.
