### ISSUE TITLE
Untranslated posts appear in sitemap.xml

### ISSUE THREAD

**Issue by max-arnold** [getnikola/nikola#2289]
Recently upgraded to 7.7.6 and received a warning from Google Webmaster Tools about increased number of 404s. It looks like sitemap.xml is the cause:

```
$ nikola --version
Nikola vv7.7.6
```

conf.py:
```
# What is the default language?
DEFAULT_LANG = "en"

# What other languages do you have?
# The format is {"translationcode" : "path/to/translation" }
# the path will be used as a prefix for the generated pages location
TRANSLATIONS = {
    DEFAULT_LANG: "",
    "ru": "./ru",
}

SHOW_UNTRANSLATED_POSTS = False
```

```
% tree stories
stories
└── example-post.md
```

sitemap.xml:
```
 <url>
  <loc>https://example.com/stories/example-post/</loc>
  <lastmod>2016-03-07T13:07:00Z</lastmod>
  <xhtml:link rel="alternate" hreflang="ru" href="https://example.com/ru/stories/example-post/" />
 </url>
```

**Comment by ralsina** [comment]
Ack, I will take a look.

**Comment by ralsina** [comment]
@max-arnold can you take a look at #2290 and see if you like what it does?

**Comment by max-arnold** [comment]
Looks good. Thank you Roberto!

**Comment by max-arnold** [comment]
One question though. Should sitemap structure for specific post be different depending on default language?

**Comment by ralsina** [comment]
You're welcome, at least it was an easy fix :-)

**Comment by max-arnold** [comment]
According to Google: https://support.google.com/webmasters/answer/2620865?hl=en

   You must create a separate url element for each URL. Each url element must include a loc tag
   indicating the page URLs, and an xhtml:link rel="alternate" hreflang="XX" subelement for every
   alternate version of the page, including itself.

If I understand this correctly, each translated post should look like this:

```
 <url>
  <loc>https://example.com/es/posts/foo.html</loc>
  <lastmod>2016-03-07T13:35:00Z</lastmod>
  <xhtml:link rel="alternate" hreflang="en" href="https://example.com/posts/foo.html" />
  <xhtml:link rel="alternate" hreflang="es" href="https://example.com/es/posts/foo.html" />
 </url>
 <url>
  <loc>https://example.com/posts/foo.html</loc>
  <lastmod>2016-03-07T13:35:00Z</lastmod>
  <xhtml:link rel="alternate" hreflang="en" href="https://example.com/posts/foo.html" />
  <xhtml:link rel="alternate" hreflang="es" href="https://example.com/es/posts/foo.html" />
 </url>
```
