### ISSUE TITLE
Incorrecnt Indonesian translation for name of language

### ISSUE THREAD

**Issue by abrowne** [getnikola/nikola#2291]
I noticed this on the [MATE Desktop site](http://mate-desktop.org/), which uses Nikola, and it was determined this issue comes from Nikola, not the site's content.

The name of to the Indonesian translation is labeled "Inggris", which means English not Indonesian (like if the French translation was "Anglais"). I think it should be "Bahasa Indonesia". (I'm not an Indonesian speaker, but my university degree is in linguistics, so I know how to look it up ;-)

I see "Inggris" a couple times in translations/nikola.messages/id.po, despite the comment saying it shouldn't be a translation of "English".

**Comment by Kwpolska** [comment]
As I said in the mate issue, we would love an Indonesian speaker to fix it, but if we can’t get one by Thursday, we’ll just roll with “Bahasa Indonesia”.

**Comment by monsta** [comment]
@willysr: can you please look at this issue? I think the guys here could use your help :smile:

**Comment by willysr** [comment]
Yes, it should be "Bahasa Indonesia"

Thanks to @abrowne for spotting it

**Comment by Kwpolska** [comment]
And how would you say "Read in Indonesian"? And could you please fix this
and contribute more translations on Transifex?

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by willysr** [comment]
I have a pull request here
https://github.com/willysr/nikola/pull/1

**Comment by Kwpolska** [comment]
Updated, thanks!
