### ISSUE TITLE
footer missing for markdown posts

### ISSUE THREAD

**Issue by jacksonloper** [getnikola/nikola#2295]
"Footer" may not be the right word here.  I'm talking about the region below the post that tells you what tags are associated with the post and gives you the option to go to the previous or next post.  I believe the relevant section of the bootstrap3 template I'm using is 

    <nav>
    ${helper.html_tags(post)}
    ${helper.html_pager(post)}
    </nav>

It just appears to be a no-op for markdown posts.  Other things don't appear, too, such as the post author or the post date.  The post title appeas though.

So, as an example, this file, test.rst...

    .. title: test
    .. slug: friends
    .. date: 2016-03-09
    .. tags: flower

    This post is about flowers

Has a little "flower" bubble at the bottom of it, indicating that this post is tagged as a "flower" post.  It also has a "next post" "previous post" links.  It indicates the date and author of the post below the post title.  On the other hand, this file, test2.md

    

    This post is about flowers

when rendered, does not have a little "flower" bubble at the bottom of the page, nor the "next post" "previous post" links, nor the author nor the date.

Any clues?  Am I the only person having this problem?  nikola isn't giving any error messages...

I'm running nikola v7.7.6 with the bootstrap3 theme.  Thanks!

**Comment by ralsina** [comment]
Just tried it and can't reproduce...

**Comment by jacksonloper** [comment]
I'm an idiot. I had

    POSTS = (
     ("posts/*.rst", "posts", "post.tmpl"),
     ("posts/*.md", "posts", "story.tmpl"),
     ("posts/*.txt", "posts", "post.tmpl"),
     ("posts/*.html", "posts", "post.tmpl"),
    )

Sorry!  Thanks again!

**Comment by ralsina** [comment]
Oops :-)
