### ISSUE TITLE
the example re for the FILE_METADATA_REGEXP doesn't work

### ISSUE THREAD

**Issue by tannie** [getnikola/nikola#2296]
The example re for the FILE_METADATA_REGEXP in the default conf.py currently reads:  
`'(?P<date>\d{4}-\d{2}-\d{2})-(?P<slug>.*)-(?P<title>.*)\.md'`

This did not work for me because my files reside (as the default conf.py suggests) in 'posts'. The documentation in that area only mentions the filename, not the path. It could probably use a little clarification?  
It works fine for me now that I use:  
`'.*\/(?P<date>\d{4}-\d{2}-\d{2})-(?P<slug>.*)-(?P<title>.*)\.rst'`

I tested this on a new installation with version 7.7.6

**Comment by ralsina** [comment]
Hmmm looks like you are right. Congratulations, you found a bug! :-D

I'll fix it first thing in the morning tomorrow.

**Comment by Kwpolska** [comment]
It looks like you forgot about this. Fixed that.

**Comment by ralsina** [comment]
INdeed I did, thanks for fixing it :-)
