### ISSUE TITLE
Add  the possibility of page range navigation

### ISSUE THREAD

**Issue by sukiletxe** [getnikola/nikola#2299]
I have seen that some blogging platforms (like Wordpress or Blogger) allow the user to navigate the indexes up to a page range. That is to say, instead of showing "Older posts" /"Newer posts" they usually show a page range to navigate between indexes of posts.
I think this eases navigation a lot (particularly with large blogs). Could an option be implemented for the blogger to choose from classical older / newer style links or page range navigation?

**Comment by felixfontein** [comment]
I've created a PR for this. @sukiletxe: feel free to add some CSS styling/improving the template for this.
