### ISSUE TITLE
why almost throw this excetpino? by version 7.7.7

### ISSUE THREAD

**Issue by mckobe23** [getnikola/nikola#2300]
```
(nikola)➜  blog nikola new_post -f markdown

[2016-03-18T08:33:15Z] ERROR: new_post: Unknown post format markdown, maybe you need to install a plugin?
Available input formats:

 NAME      DESCRIPTION               EXTENSIONS

 html      HTML                      .html, .htm
 rest      reStructuredText          .rst, .txt
!ipynb     Jupyter/IPython Notebook  .ipynb
!markdown  Markdown                  .md, .mdown, .markdown
!php       PHP                       .php
~pandoc    Pandoc                    (disabled: not in COMPILERS)

    More compilers are available in the Plugins Index.

    Compilers marked with ! and ~ require additional configuration:
        ! not in the PAGES/POSTS tuples (unused)
        ~ not in the COMPILERS dict (disabled)
    Read more: https://getnikola.com/handbook.html#configuring-other-input-formats

**Comment by Kwpolska** [comment]
In order to use Markdown, you need to add `posts/*.md` or similar to your POSTS tuple. Read [the link the error message points to](https://getnikola.com/handbook.html#configuring-other-input-formats).

**Comment by cowlicks** [comment]
@Kwpolska note that `.md` is listed as a valid extension in the error message. So maybe it should be recognized as one automatically or the error message should be changed.

**Comment by Kwpolska** [comment]
>     !markdown  Markdown                  .md, .mdown, .markdown
>
>        Compilers marked with ! and ~ require additional configuration:
>            ! not in the PAGES/POSTS tuples (unused)

**Comment by felixfontein** [comment]
Maybe it would help to change `Unknown post format markdown, maybe you need to install a plugin?` into something like `Unknown post format markdown, maybe you need to install a plugin or enable an existing one by adding it to POSTS/PAGES?`.

**Comment by Kwpolska** [comment]
Added a few words in 0bff44f1eee7c73b9bc515cdbb48a1c1d1aa9490 .
