### ISSUE TITLE
Omit bundeled CSS and JS from the output directory

### ISSUE THREAD

**Issue by tritium21** [getnikola/nikola#2303]
As it currently stands, when using bundles, all the theme JS and CSS are copied to the output directory, then the bundles are created.  It might be useful in some scenarios to omit the source JS and CSS files from the output directory, either by creating the bundles in the cache and copying all.js, et. al. into the output directory, or deleting the source JS and CSS from the output directory as part of a task.

(I consider this a 'Whenever' idea)

**Comment by Kwpolska** [comment]
> It might be useful in some scenarios

What scenarios? Be specific.

I think that this feature is rather hard to implement and not worth the hassle. Most people won’t mind those files, and it simplifies bundles greatly. Deleting files is a no-go.

**Comment by tritium21** [comment]
Where you are deploying over FTP, and for whatever reason the FTP server does not generate listings with realistic mtimes or ctimes, all files in the output directory have to be uploaded (there is no real way to sync files sanely over ftp if one side isn't playing nice.)  Couple this with limited bandwidth, the unneeded JS is increasingly annoying.

**Comment by ralsina** [comment]
@tritium21 sorry, doing that is pretty difficult because of how bundles work, and considering the scenario is fairly unusual, I don't think we'll do it.
