### ISSUE TITLE
Rebuilding the site does not clean output directory

### ISSUE THREAD

**Issue by TheHellstorm** [getnikola/nikola#2305]
Hi,

I have versioned my Blog in Git and created a branch where I am testing the custom.css file (by putting it in files/assets/custom.css). When building the site, the custom.css gets copied to the correct folder. So far, so good.

But if I change the branch to master, and build the site again, Nikola does not see that the custom.css is not present in the master branch and just leaves it where it is (I am not tracking the output folder via CSS).

Doing a nikola clean will not delete it either. The only way which I found was to manually remove all files in the folder.

Is this a problem of Nikola (or of Doit?) or is this intentionally with some good reason?

Thanks :)

**Comment by Kwpolska** [comment]
We can’t do that. What if you removed a file from your sources by accident? What if you put a file in your output/ directory, because you did not know about `files/`?

Plus, Nikola is unaware of files you deleted from the source. You can, however, use `nikola check` or `nikola orphans` to remove all orphaned files.

**Comment by MrClever** [comment]
Personally if I want to break out the big stick and completely rebuild my websites, I use a Makefile:
`all: build deploy

clean:
	rm -rf output/[A-Za-z0-9]*
	rm -rf cache/posts/[A-Za-z0-9]*
	rm -rf cache/webassets/[A-Za-z0-9]*

build:
	nikola build

deploy:
	nikola deploy`

For normal builds, I just "make". If I want to clean it all out and start fresh "make clean all".

YMMV.

**Comment by ralsina** [comment]
Hopefully the reason why Nikola doesn't do that by default should be pretty obvious.

**Comment by MrClever** [comment]
TBH I can't remember anything recently that required me to hose the output/cache directories, and I can totally understand why Nikola doesn't do this by default (eep!). From memory I think it was a version jump that skipped an intermediate version that caused me grief (might be wrong...it's a bit hazy). I just remember having a problem a while ago and baked the "solution" into my Makefile and figured sharing is caring.

**Comment by eddiefiggie** [comment]
I've built a Nikola site a few months back.  Mostly for learning.  Everything worked as documented.  Recently I wanted to revisit the exercise, and thought I was doing it by scratch.  I ran nikola init in a new director, created a new blog post, rebuilt...  After deploying it to the webserver, I noted my original blog post from months ago was still noted in the archive.  Following this thread, I got to a point where the file is now gone, but the pointers are still there.

Pardon my inexperience, but can someone help me understand the mechanic I am missing?  Rebuilt the site in new director?  Where are these "ghosts" living so I can find them, and remove them.

Appreciate your patience.

**Comment by Kwpolska** [comment]
@eddiefiggie If you did not clean your web server target directory as part of your deployment (`--del` option to rsync, for example), files will stay where they are. If you can’t find the “ghost” in `output/`, it means it stayed on the server that way.

**Comment by eddiefiggie** [comment]
@Kwpolska That's what I initially thought as well.  That said, I have literally "rm -r" the entire directory from my web server, created a blank directory for the site and then pushed the content over.  Again, confirming there was no "oldpost" in the content.  It is quite weird.  This old blog is literally like a ghost.

When I go to Archives>>2017 I can still see that "oldpost".

**Comment by Kwpolska** [comment]
@eddiefiggie Nikola doesn’t have any sort of global database of posts/state. You must have the “ghost” post left over somewhere even though you think you deleted it.

1. Clean the server directory again.
2. Check if the “ghost” post is in posts/ locally.
3. Check your local output/archive.html, output/2017/, output/posts places if they show the “ghost” post.
4. Try deploying again. Make sure you’re working on the correct paths everywhere.

**Comment by eddiefiggie** [comment]
It seems it was cached in my browser (Firefox 57).  *face palm*

Everything within this solution had seemed to straight forward....then I started getting this haunting! 

Anyway, your directions had worked, I just needed to clear the cache in my browser.

Everything is working as it should.
