### ISSUE TITLE
rendering icalendar files

### ISSUE THREAD

**Issue by gour** [getnikola/nikola#2306]
Hello,

I'm still waiting for ownCloud to get possibility to embed *.ics calendar files and the feature is scheduled for 9.1.

Otoh, I've found out that Pelican has nice feature in the form of [ical](https://github.com/getpelican/pelican-plugins/tree/master/ical) plugin which is able to render .ics calendar file referenced in the page's metadata section, so I believe it would be useful add-on for Nikola?

**Comment by ralsina** [comment]
It's interesting. The code is very simple: https://github.com/getpelican/pelican-plugins/blob/master/ical/ical.py

We could do this a few different ways:

1. Add metadata support for it. That way the Post object would grow extra calendar-related fields which can be used in templates.

2. Add a shortcode / rst directive to just show the ical entries nicely.

**Comment by gour** [comment]
Whichever you find simpler to implement/ maintain...although 

> Add a shortcode / rst directive to just show the ical entries nicely.

looks good-enough for me.

**Comment by ralsina** [comment]
https://github.com/getnikola/plugins/pull/160

**Comment by ralsina** [comment]
Closing here, the mentioned branch will merge eventually after a prerequisite branch merges in Nikola.
