### ISSUE TITLE
The language for each post is not used in the templates

### ISSUE THREAD

**Issue by sukiletxe** [getnikola/nikola#2307]
Currently, the `lang` attribute is only set in the html tag. As a result of this, if, for example, there is a post in the Spanish version of a blog in English, it will be spoken using the Spanish voice by a screen reader.
I believe that `lang`should be set for the links below `NAVIGATION_LINKS`, for post titles, post texts and dates.

**Comment by Kwpolska** [comment]
:-1:

This is hard to do. We won’t rewrite every link. It’s also hard to know that, because if you enable untranslated posts (hint, hint) we work with them as if they were “native”.

**Comment by ralsina** [comment]
@sukiletxe like @Kwpolska said: if you set SHOW_UNTRANSLATED_POSTS to False (which we should probably default to in the future) then you will only have posts appear in the languages to which they are translated.

If you don't, then Nikola doesn't really know much about those posts.

For example, if your blog is mainly english with a spanish translation, and your post is in english and not translated. How exactly would we "set lang for the post title" as you suggest? That title is in english!

**Comment by sukiletxe** [comment]
I assumed that the post's language was exposed in some way to the template. Turns out I was wrong. I'll just disable SHOW_UNTRANSLATED_POSTS and display a warning.
@kwpolska: What do you mean by "We won’t rewrite every link"?
@ralsina: If the post's language was exposed as I thought, it could just be lang = 'en' twice. I don't think browsers or validators would complain.

**Comment by Kwpolska** [comment]
> I believe that `lang` should be set for the links below NAVIGATION_LINKS, for post titles, post texts and dates.

In other words: add something so that Nikola determines the locale of every single link and adds it to the output. Which wastes a lot of time and effort for not a lot of profit.

Closing.
