### ISSUE TITLE
Set permission for output files?

### ISSUE THREAD

**Issue by lyndametref** [getnikola/nikola#2308]
With Nikola v7.7.7 the generated files have the permission `-rwx------`. Is it possible to set custom permissions for the output files?

**Comment by ralsina** [comment]
AFAIK the permissions will be for most cases the following:

1. The permission in the input files, when they are simply copied
2. Those determined by your umask, when they are created

If that's not the case, then we should fix it, of course.

**Comment by lyndametref** [comment]
Oupst, found where it comes from, my files are on fat fs ^.^'... sorry about that... 

I worked around it by tweaking the rsync when deploying `rsync -av --chmod=Dugo=rx,Fugo=r,u+w --delete output/ me@site:~/site`

**Comment by ralsina** [comment]
Cool, nice to see it worked out well for you!
