### ISSUE TITLE
Using SVG images as logo?

### ISSUE THREAD

**Issue by lyndametref** [getnikola/nikola#2314]
Is it possible to use an SVG file as site logo (or any other image on the website)? I have put an SVG in the image folder and got an error from the image scaling task. Is there another place I should place the SVG in? Is it supported? 

I will be grateful for input on this matter.

**Comment by Kwpolska** [comment]
On Thu, Apr 07, 2016 at 05:35:40AM -0700, Lynda Metref wrote:
> Is it possible to use an SVG file as site logo (or any other image on the website)? I have put an SVG in the image folder and got an error from the image scaling task. Is there another place I should place the SVG in? Is it supported? 
> 
> I will be grateful for input on this matter.
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/getnikola/nikola/issues/2314

We have a svg logo on our very own website.

If you have issues with the scaling task, make sure your copy of Nikola is up
to date, and show us the traceback.

Using the scaling feature is not neceessary, you can put your svgs in files/
(scaling svgs is not useful anyway)

-- 
Chris Warrick <https://chriswarrick.com/>
PGP: 5EAAEA16

**Comment by lyndametref** [comment]
It works indeed when placing images in files. Thank you very much!

**Comment by Kwpolska** [comment]
We could still use the error information, because there might be yet another bug in the image scaling that could use a fix.

**Comment by lyndametref** [comment]
Sorry I did not see your question right away. I am using Nikola v7.7.7
When I have a svg in the `/images` I get the following error:

```
Scanning posts.....done!
.  render_posts:timeline_changes
.  scale_images:output/images/logo.svg
########################################
TaskError - taskid:scale_images:output/images/logo.svg
PythonAction Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/nikola/plugins/task/scale_images.py", line 74, in process_image
    self.resize_image(src, dst, self.kw['max_image_size'], False, preserve_exif_data=self.kw['preserve_exif_data'])
  File "/usr/local/lib/python3.5/dist-packages/nikola/image_processing.py", line 58, in resize_image
    self.resize_svg(src, dst, max_size, bigger_panoramas)
  File "/usr/local/lib/python3.5/dist-packages/nikola/image_processing.py", line 110, in resize_svg
    tree = lxml.etree.XML(xml)
  File "src/lxml/lxml.etree.pyx", line 3192, in lxml.etree.XML (src/lxml/lxml.etree.c:82678)
  File "src/lxml/parser.pxi", line 1814, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:124471)
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

**Comment by Kwpolska** [comment]
That bug is fixed in master.
