### ISSUE TITLE
nikola/plugins/command/status.py uses old method of getting last deploy

### ISSUE THREAD

**Issue by tritium21** [getnikola/nikola#2317]
The current version of the file uses an [old method of getting the last deploy time
](https://github.com/getnikola/nikola/blob/e068305a4eb2099adca3b53e13c35c01b979c367/nikola/plugins/command/status.py#L78), but that method is [not being updated anymore](https://github.com/getnikola/nikola/blob/master/nikola/plugins/command/deploy.py#L63).

Related, a [recent change](https://github.com/getnikola/nikola/commit/027a0400344f2a5cbbb66db5e0ff95b3eb35a608) probably should have added the CACHE_FOLDER path component instead of eliminating the os.path.join, in retrospect.

**Comment by Kwpolska** [comment]
@ralsina, mind fixing that one?
