### ISSUE TITLE
Positional argument support for template shortcodes

### ISSUE THREAD

**Issue by SpotlightKid** [getnikola/nikola#2319]
Currently template-based shortcodes support only keyword-style arguments:

    {{% shortcode arg=foo %}}

In fact, if you use non-keyword arguments, they break the template shortcode functions, because it doesn't accept positional args. Or, if you use only one positional arg in the shortcode, it will overwrite the template source, due to the way the function is defined.

From [nikola.Nikola._register_templated_shortcodes](https://github.com/getnikola/nikola/blob/master/nikola/nikola.py#L1319):

    ....
    def render_shortcode(t_data=template_data, **kw):
        return self.template_system.render_template_to_string(t_data, kw)
    
    self.register_shortcode(name, render_shortcode)

Which is called from [shortcodes.apply_shortcodes](https://github.com/getnikola/nikola/blob/master/nikola/shortcodes.py#L313) like this (where `registry` references `Nikola.shortcode_registry`):

    res = registry[name](*args, **kw)

I propose to change the `render_shortcode` function to something like this:

        def render_shortcode(*args, **kw):
            kw['_args'] = args
            return self.template_system.render_template_to_string(template_data, kw)

`template_data` will be resolved from the parent namespace, so it isn't necessary to pass it explicitly. The function puts positional args it receives into the template context as the `_args` list. Suggestions for another name welcome.

**Comment by ralsina** [comment]
Well, originally it was supposed to take positional arguments, and IIRC it did, until my handmade crufty code was replaced with a parser I don't quite understand, so I can't really fix this much.

**Comment by SpotlightKid** [comment]
@ralsina: The parser can handle non-keyword args without problem. `render_shortcode` just doesn't handle them correctly, atm.

--- 

I just did a test and I'm wrong about the need to pass `template_data`.At the moment is passed as a default arg, because if you access `template_data` from the parent scope, it will have the value from the last iteration of the for-loop, i.e. the last template file read.

Demonstration code:

```
registry = {}

def register():
    for name in "foo bar baz".split():
        def inner(*args):
            print("hello, %s: %r" % (name, args))

        registry[name] = inner

register()

for i, name in enumerate(registry):
    registry[name](i)
```

Outputs:

    hello, baz: (0,)
    hello, baz: (1,)
    hello, baz: (2,)

:(

**Comment by felixfontein** [comment]
I think the new shortcode parser is still parsing positional arguments and passes them on; take a look here: https://github.com/getnikola/nikola/blob/master/nikola/shortcodes.py#L313

**Comment by felixfontein** [comment]
@SpotlightKid: to fix this problem, you can define `inner` in another function call:
```
registry = {}

def make_inner(name):
    def inner(*args):
        print("hello, %s: %r" % (name, args))
    return inner

def register():
    for name in "foo bar baz".split():
        registry[name] = make_inner(name)

register()

for i, name in enumerate(registry):
    registry[name](i)
```
That produces
```
hello, bar: (0,)
hello, baz: (1,)
hello, foo: (2,)
```
as expected.

**Comment by felixfontein** [comment]
(You can probably also define `make_inner` inside `register`. I guess we should change `nikola.Nikola._register_templated_shortcodes` in that manner to get rid of the `t_data` argument.)

**Comment by SpotlightKid** [comment]
Yes, I just successfully tested something like this:

    def _register_templated_shortcodes(self, shortcodes):
        # normally would read shortcode template from directory
        for name, templ in shortcodes:
            def make_render_func(template_data):
                def render_shortcode(*args, **kw):
                    kw['_args'] = args
                    return self.template_system.render_template_to_string(template_data, kw)
                return render_shortcode

            self.register_shortcode(name, make_render_func(templ))

**Comment by SpotlightKid** [comment]
I've submitted PR #2320 based on my comment above.

**Comment by Kwpolska** [comment]
PR merged, this can be closed.
