### ISSUE TITLE
Gist URLs changed

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2322]
New URLs:

https://gist.githubusercontent.com/mrabbitt/4747847/raw/zen.py
https://gist.github.com/mrabbitt/4747847.js

This needs to be changed in our test suite, possibly in our docs. New gists have even worse URLs with sha1 hashes, and less predictable raw URLs…

**Comment by ralsina** [comment]
sigh.

**Comment by Kwpolska** [comment]
I’m deleting the gist tests, since we shouldn’t depend on a third-party service in our test suite.
