### ISSUE TITLE
wishlist - Option to remove geotags from exif data in images

### ISSUE THREAD

**Issue by mmattice** [getnikola/nikola#2323]
This can totally be done by hand obviously, but automation.

**Comment by ralsina** [comment]
I am looking into a decent way to handle EXIF data in general. So far:

1) pyexiv2 is deprecated for GExiv2
2) GExiv2 is not in PyPI
3) exifyay looks promising (and not overly impossible to install)
4) piexif is pure python (yay) and has a recent release

So, going to try with piexif for the time being.

**Comment by ralsina** [comment]
@mmatice what do you think of this branch?

https://github.com/getnikola/nikola/pull/2396
