### ISSUE TITLE
Media with https

### ISSUE THREAD

**Issue by aledeg** [getnikola/nikola#2324]
I am not sure if I should post here or [here](https://github.com/coleifer/micawber).

Here is my problem.
I am trying to embed that [video](http://www.dailymotion.com/video/x1apjif_une-arbalete-de-poche-fabriquee-manuellement_tv) in my blog post.
To do that I used the following instruction:
```rst
.. media:: http://www.dailymotion.com/video/x1apjif_une-arbalete-de-poche-fabriquee-manuellement_tv
```

It was working fine when I served it locally for preview but when I deployed it, it wasn't working anymore. After some search, I found out that the problem is that my website is served in https and the video in http. So I changed my code to:
```rst
.. media:: https://www.dailymotion.com/video/x1apjif_une-arbalete-de-poche-fabriquee-manuellement_tv
```

But it's still not working. The embed video still links to its http version. Is there something I should do to fix that?

I am currently using:

- nikola 7.7.7
- micawber 0.3.3

Edit: Firefox is blocking the rendering because it considers that the content is not safe to be displayed since it's a http content.

**Comment by ralsina** [comment]
Easiest thing is to check what micawber does. If it turns the https:// to
http:// then it should be reported there.
And it seems to do just that:

>>> import micawber
>>> providers = micawber.bootstrap_basic()
>>> providers.request('
https://www.dailymotion.com/video/x1apjif_une-arbalete-de-poche-fabriquee-manuellement_tv
')
{'width': 480, 'html': '<iframe frameborder="0" width="480" height="271"
src="http://www.dailymotion.com/embed/video/x1apjif"
allowfullscreen></iframe>', 'provider_name': 'Dailymotion', 'author_name':
'Gentside', 'thumbnail_height': 240, 'type': 'video', 'thumbnail_url': '
http://s2.dmcdn.net/DfkBd/x240-XC7.jpg', 'title': 'Une arbalète de poche
fabriquée manuellement', 'thumbnail_width': 424, 'author_url': '
http://www.dailymotion.com/Gentside', 'url': '
https://www.dailymotion.com/video/x1apjif_une-arbalete-de-poche-fabriquee-manuellement_tv',
'version': '1.0', 'description': '
http://www.gentside.com/insolite/il-fabrique-une-arbalete-de-poche-avec-une-epingle-a-linge_art58612.html',
'height': 271, 'provider_url': 'http://www.dailymotion.com'}

Of course this is probably not actually a bug in micawber but instead on
the OEmbed endpoint in dailymotion.

**Comment by aledeg** [comment]
Ok, thanks!
