### ISSUE TITLE
Relative links to bower_components.

### ISSUE THREAD

**Issue by TierraDelFuego** [getnikola/nikola#2333]
I really am just kicking the tires of nikola so I know very little about it. I don't know if this is a bug or a feature. I see these relative links to non-existant directories. Do I misunderstand something?

grep -r "\.\./\.\."

output/assets/css/bootstrap.css:../../../../../../bower_components/bootstrap/dist/css/bootstrap.css
output/assets/css/bootstrap.css.map:../../../../../../bower_components/bootstrap/dist/css/bootstrap.css.map
output/assets/css/images/loading.gif:../../../../../../../bower_components/jquery-colorbox/example3/images/loading.gif
output/assets/css/images/controls.png:../../../../../../../bower_components/jquery-colorbox/example3/images/controls.png
output/assets/css/bootstrap-theme.min.css.map:../../../../../../bower_components/bootstrap/dist/css/bootstrap-theme.min.css.map
output/assets/css/bootstrap-theme.css:../../../../../../bower_components/bootstrap/dist/css/bootstrap-theme.css
output/assets/css/bootstrap-theme.css.map:../../../../../../bower_components/bootstrap/dist/css/bootstrap-theme.css.map
output/assets/css/colorbox.css:../../../../../../bower_components/jquery-colorbox/example3/colorbox.css
output/assets/css/bootstrap.min.css:../../../../../../bower_components/bootstrap/dist/css/bootstrap.min.css
output/assets/css/bootstrap-theme.min.css:../../../../../../bower_components/bootstrap/dist/css/bootstrap-theme.min.css
output/assets/css/bootstrap.min.css.map:../../../../../../bower_components/bootstrap/dist/css/bootstrap.min.css.map
output/assets/js/bootstrap.min.js:../../../../../../bower_components/bootstrap/dist/js/bootstrap.min.js
output/assets/js/moment-with-locales.min.js:../../../../../../bower_components/moment/min/moment-with-locales.min.js
output/assets/js/jquery.min.js:../../../../../../bower_components/jquery/dist/jquery.min.js
output/assets/js/jquery.slim.js:../../../../../../bower_components/jquery/dist/jquery.slim.js
output/assets/js/jquery.min.map:../../../../../../bower_components/jquery/dist/jquery.min.map
output/assets/js/bootstrap.js:../../../../../../bower_components/bootstrap/dist/js/bootstrap.js
output/assets/js/colorbox-i18n/jquery.colorbox-fr.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-fr.js
output/assets/js/colorbox-i18n/jquery.colorbox-pl.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-pl.js
output/assets/js/colorbox-i18n/jquery.colorbox-no.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-no.js
output/assets/js/colorbox-i18n/jquery.colorbox-da.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-da.js
output/assets/js/colorbox-i18n/jquery.colorbox-he.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-he.js
output/assets/js/colorbox-i18n/jquery.colorbox-bg.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-bg.js
output/assets/js/colorbox-i18n/jquery.colorbox-ca.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-ca.js
output/assets/js/colorbox-i18n/jquery.colorbox-tr.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-tr.js
output/assets/js/colorbox-i18n/jquery.colorbox-gr.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-gr.js
output/assets/js/colorbox-i18n/jquery.colorbox-sr.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-sr.js
output/assets/js/colorbox-i18n/jquery.colorbox-es.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-es.js
output/assets/js/colorbox-i18n/jquery.colorbox-ar.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-ar.js
output/assets/js/colorbox-i18n/jquery.colorbox-cs.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-cs.js
output/assets/js/colorbox-i18n/jquery.colorbox-ru.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-ru.js
output/assets/js/colorbox-i18n/jquery.colorbox-uk.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-uk.js
output/assets/js/colorbox-i18n/jquery.colorbox-et.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-et.js
output/assets/js/colorbox-i18n/jquery.colorbox-id.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-id.js
output/assets/js/colorbox-i18n/jquery.colorbox-nl.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-nl.js
output/assets/js/colorbox-i18n/jquery.colorbox-fi.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-fi.js
output/assets/js/colorbox-i18n/jquery.colorbox-pt-BR.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-pt-BR.js
output/assets/js/colorbox-i18n/jquery.colorbox-fa.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-fa.js
output/assets/js/colorbox-i18n/jquery.colorbox-bn.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-bn.js
output/assets/js/colorbox-i18n/jquery.colorbox-si.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-si.js
output/assets/js/colorbox-i18n/jquery.colorbox-sk.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-sk.js
output/assets/js/colorbox-i18n/jquery.colorbox-ro.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-ro.js
output/assets/js/colorbox-i18n/jquery.colorbox-zh-TW.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-zh-TW.js
output/assets/js/colorbox-i18n/jquery.colorbox-gl.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-gl.js
output/assets/js/colorbox-i18n/jquery.colorbox-sv.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-sv.js
output/assets/js/colorbox-i18n/jquery.colorbox-ja.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-ja.js
output/assets/js/colorbox-i18n/jquery.colorbox-de.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-de.js
output/assets/js/colorbox-i18n/jquery.colorbox-lv.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-lv.js
output/assets/js/colorbox-i18n/jquery.colorbox-lt.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-lt.js
output/assets/js/colorbox-i18n/jquery.colorbox-my.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-my.js
output/assets/js/colorbox-i18n/jquery.colorbox-zh-CN.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-zh-CN.js
output/assets/js/colorbox-i18n/jquery.colorbox-hr.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-hr.js
output/assets/js/colorbox-i18n/jquery.colorbox-kr.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-kr.js
output/assets/js/colorbox-i18n/jquery.colorbox-it.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-it.js
output/assets/js/colorbox-i18n/jquery.colorbox-hu.js:../../../../../../../bower_components/jquery-colorbox/i18n/jquery.colorbox-hu.js
output/assets/js/jquery.slim.min.js:../../../../../../bower_components/jquery/dist/jquery.slim.min.js
output/assets/js/jquery.colorbox.js:../../../../../../bower_components/jquery-colorbox/jquery.colorbox.js
output/assets/js/jquery.colorbox-min.js:../../../../../../bower_components/jquery-colorbox/jquery.colorbox-min.js
output/assets/js/jquery.js:../../../../../../bower_components/jquery/dist/jquery.js
output/assets/js/jquery.slim.min.map:../../../../../../bower_components/jquery/dist/jquery.slim.min.map
output/assets/fonts/glyphicons-halflings-regular.ttf:../../../../../../bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
output/assets/fonts/glyphicons-halflings-regular.svg:../../../../../../bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
output/assets/fonts/glyphicons-halflings-regular.woff:../../../../../../bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
output/assets/fonts/glyphicons-halflings-regular.woff2:../../../../../../bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2
output/assets/fonts/glyphicons-halflings-regular.eot:../../../../../../bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.eot

**Comment by Kwpolska** [comment]
This really should not happen. How did you install Nikola (exactly), what is your operating system and Python version?

**Comment by TierraDelFuego** [comment]
I will try to recreate, I am pretty sure I did not do anything tricky. But maybe python 3.5 is causing it or a virtual environment via pyvenv is the problem?  I don't have my command history so will retry.

Working a virtual env under python 3.5.

`# EASY-INSTALL-ENTRY-SCRIPT: 'Nikola==7.7.8','console_scripts','nikola'
__requires__ = 'Nikola==7.7.8'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('Nikola==7.7.8', 'console_scripts', 'nikola')()
    )`

**Comment by Kwpolska** [comment]
pyvenv tends to be pretty broken, but it shouldn’t be that dumb. How, exactly, did you install Nikola?

**Comment by TierraDelFuego** [comment]
I think I used pip install nikola.  Haven't had a chance to retry but I usually do this.

pyvenv /home/me/p35virtual
. /home/me/p35virtual/bin/activate
pip install nikola

**Comment by Kwpolska** [comment]
Could you try with virtualenv? Also, make sure your versions of pip, setuptools and wheel are up-to-date.

**Comment by TierraDelFuego** [comment]
I will try it although I don't know it. I am hesitant to stray too far from a basic python install because this makes more work now and later.

**Comment by Kwpolska** [comment]
Cannot reproduce with your commands and Python 3.5.1 on Arch Linux on an ext4 drive.

**Comment by TierraDelFuego** [comment]
I tried out virtualenv and also tried another pyvenv. I didn't see this problem. Not sure about wheel and setuptools.

**Comment by Kwpolska** [comment]
Well then, looks like there was some glitch with your original download. Have fun using Nikola!

**Comment by TierraDelFuego** [comment]
I had another thought occur to me in a quiet moment. 

Is it possible that due to this setup I encountered the problem? I won't have time to test it very soon.
1 == a mount point distinct from 2
2 == a mount point distinct from 1
fable == sym link to thebearandjupiter on mount 1

 ```shell
/1/aesop/thebearandjupiter
/2/home/me/fable
```

I run nikola from /2/home/me with output going to fable. I am guessing that link traversal caused the glitch.

**Comment by Kwpolska** [comment]
This might be possible, but I don’t think that would be the cause. It works, so at least that’s good.

**Comment by TierraDelFuego** [comment]
I was in that mode of just trying out different software and was quickly doing things so I just don't recall the specifics. And it works, so that is good.
