### ISSUE TITLE
init leaves a cache directory in the current working directory

### ISSUE THREAD

**Issue by TierraDelFuego** [getnikola/nikola#2334]
nikola init someproj

$ ls -1
someproj
cache

There shouldn't be any directories created in current working directory. It would be a bad idea to write into an existing cache directory. Could cause confusion or worse.

**Comment by Kwpolska** [comment]
That’s a bug in our Persistor system, which tries to create the `cache/` destination directory no matter what. I limited this to configured sites only.

Thanks for reporting!
