### ISSUE TITLE
Terminal freezing when executing nikola build

### ISSUE THREAD

**Issue by drym3r** [getnikola/nikola#2335]
There's not much more than that. I've tried using the auto parameter, but it happened the same. I'm not sure how to debug it more, some indications would be good.

It only happens on one PC of the two I use with nikola. It's a old netbook, but it shouldn't be a problem, since the building is not a very stressing activity.

Thanks

**Comment by Kwpolska** [comment]
> It only happens on one PC of the two I use with nikola. It's a old netbook, but it shouldn't be a problem, since the building is not a very stressing activity.

Um, it sort of is. We need to load a lot of plugins from the hard drive. To see some extra debug output when Nikola does that:

    NIKOLA_DEBUG=1 nikola build

Or look at `strace` and `htop`.

Does waiting resolve the issue? (We don’t recommend running Nikola on SD cards and really slow drives.)

**Comment by drym3r** [comment]
Well, I'm talking about a lot of minutes. I'm able to compile big programs or the kernel in a few hours, so it shouldn't be a problem. It gets stuck when it finishes, when arriving on robots_file. I'll leave it all the night and I'll update this post.

**Comment by Kwpolska** [comment]
No idea, sorry… perhaps there’s something else that’s going on?

For an ultimate test, try:

   NIKOLA_DEBUG=1 strace nikola build -v 2 -r console

Also, try disabling the robots plugin, maybe that will fix it?

(also, please don’t edit posts with details, we don’t get notifications for that)

**Comment by drym3r** [comment]
Ok, I'll try in a few days (and won't edit the post).

**Comment by felixfontein** [comment]
One thing I experienced is that sometimes, my terminal (terminator, Gnome-Terminal-based) freezes when there's too much output. As soon as I scroll a screen up, it just continues and everything's fine. This seems to be a bug in the Gnome terminal. Since Nikola can generate a lot of output (for bigger blogs) this sometimes happens to me with Nikola as well.

**Comment by Kwpolska** [comment]
@felixfontein Nikola can’t fix your terminal. Please report a bug to terminator.

I’m closing this due to no response from the OP in over 6 weeks.

**Comment by felixfontein** [comment]
That's why I'm mentioning that: wouldn't be a Nikola bug then.

**Comment by drym3r** [comment]
Sorry for not saying anything else, FYI I found the problem (not a bug). I copied my nikola's web directory to another PC and when executing it it gave an error, which didn't happen with my main PC. It was just a .pyc file compiled in another different architecure. I don't know why it didn't say that on the first PC and just hang, but I don't think is nikola's problem. Anyway, thanks for your time.
