### ISSUE TITLE
Complete _WINDOWS_LOCALE_GUESSES

### ISSUE THREAD

**Issue by sukiletxe** [getnikola/nikola#2343]
Currently, `_WINDOWS_LOCALE_GUESSES` has only 20 of 30+ locales. It should be updated to try to equate it with `TRANSLATIONS`.

**Comment by Kwpolska** [comment]
@ccanepa, where is this information? There was a link, but the information is gone. Any hints?

**Comment by sukiletxe** [comment]
You could try with https://msdn.microsoft.com/en-us/goglobal/bb964664.aspx

**Comment by Kwpolska** [comment]
This is a list, but for Windows XP: https://msdn.microsoft.com/en-us/goglobal/bb895996

@sukiletxe would you mind doing that, or should I try?

**Comment by sukiletxe** [comment]
Oops, I sent you the wrong page. Anyways, the list you sent seems to be 
pretty complete. I'll try fixing this myself.


Just one thing: it seems that some locales have their own dialects (such 
as Arabic), and no generic locale. Nontheless, I will try with just the 
generic name, as it has worked for English.

**Comment by sukiletxe** [comment]
Problem: This list seems to not work in Windows 7. The locales ending in 
_Latin or _Cyrillic (Bosnian and Serbian), Norwegian_Bokmal and 
Portuguese_Standard throw an error when passing them to 
locale.setlocale. Portuguese_Standard can be replaced with 
Portuguese_Portugal and it works.

I'm sending the pr now without these locales.

To fix this, I'd probably need to use Applocale with Python itself (I 
hope it works), and retrieve the valid locales. But maybe this would 
break compatibility with XP.

**Comment by Kwpolska** [comment]
We don’t care about Windows XP in the slighest.

**Comment by sukiletxe** [comment]
Oh, poor users! (sarcasm, they should have updated ages ago).

Then I'll go for AppLocale.
