### ISSUE TITLE
cannot indent code blocks 

### ISSUE THREAD

**Issue by shelper** [getnikola/nikola#2349]
the code block only will be rendered if it starts at the very beginning of the line, e.g. 
'''python
import os
'''
but if i insert space before each line, it cannot be rendered correctly

> '''python
> import os
> '''

it would be desirable to enable code block indentation

(i am using ''' instead of ``` to avoid the auto format of code blocks)

**Comment by Kwpolska** [comment]
Why do you want to indent that? Also, this is not a Nikola issue, it’s caused by your Markdown compiler — perhaps ask on their bugtracker.

**Comment by shelper** [comment]
say i want to embed the code blocks in the lists, since the lists are
indented usually,  indent the code block make it look nicer...

it also provides a more structured view of the source .md file

**Comment by Kwpolska** [comment]
Please report an issue with python-markdown (or whatever your markdown engine is).
