### ISSUE TITLE
Plugins should be able to insert CSS/JS in output

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2354]
As discussed in nikola-discuss:

In some cases, plugins will extend Nikola with support for external services. For example, a calendar plugin may generate markup to insert a calendar.

In some cases, that calendar may require plugin-specific CSS and JS to be added to the pages that contain that post, and not to others.

Therefore:

- [ ] A plugin should be able to inform a post of its requirements
- [ ] Templates should be able to obtain said requirements from the post objects it contains
- [ ] Templates should be able to insert those requirements in the right places if needed

**Comment by ralsina** [comment]
This is pretty much exactly template hooks, now that I bothered reading the doc for it ;-)

**Comment by felixfontein** [comment]
Cool! That's one feature I wanted to use but thought it isn't available yet.

If anyone else wonders how to do it: https://getnikola.com/extending.html#template-hooks
