### ISSUE TITLE
output of 'nikola auto' not visible with light themes

### ISSUE THREAD

**Issue by gour** [getnikola/nikola#2360]
I use solarized-light theme in my(gnome) terminal and when I e.g. run 'nikola build', most of the output is not clearly visible - see the shot: http://pasteboard.co/1pIJ9kw9.png, so wonder if something can be done to make it more ui-friendly for light color themes?

**Comment by Kwpolska** [comment]
Use a black theme. Will solve so many problems.

**Comment by gour** [comment]
> Use a black theme. Will solve so many problems.

I was using dark themes, but found out it's not good for my eyes...and everything else does not matter in comparison. ;)

**Comment by ralsina** [comment]
Ok, so, Nikola can not know what the color scheme you are using is. Right?

So, going to add an option to deactivate color output globally, and then you can use it.

**Comment by ChillarAnand** [comment]
> Ok, so, Nikola can not know what the color scheme you are using is. Right?

Users can set env variable or add an option in config?

**Comment by Kwpolska** [comment]
Try the `NIKOLA_MONO` environment variable (or a dark terminal, those are really good).
