### ISSUE TITLE
possibility to make lxml doing "smart things"

### ISSUE THREAD

**Issue by s2hc-johan** [getnikola/nikola#2368]
When developing a custom theme, in some pages I get strange div tags, breaking the page design.

After dicussion with @ralsina on irc, an ide could be that my templates have an error, and lxml tries to fix it.

In the cases where lxml is unable to fix the error, it's hard to track down the original error, when we have extra things inserted from lxml.

A good solution, from @ralsina, would be to have a flag to disable the "smart" things, so we get a more raw output of from the templates

**Comment by ralsina** [comment]
On second look, we can't do this. We use the lxml document-rewriting to fix the links everywhere. If we don't do that your site is going to be very very very broken.
