### ISSUE TITLE
Add a signal after a post is compiled.

### ISSUE THREAD

**Issue by tritium21** [getnikola/nikola#2369]
I want to write a plugin to post-process the compiled HTML fragment output by Pandoc, though what I want to do could be applied to any of the compilers.  I need to hook into Nikola before post teasers are extracted from the compiled HTML fragments.  There is no way to do what I want without re-implementing the compiler plugin.

For Pandoc, this is no great burden - the method in question is 11 lines of code, and the entire module, including boilerplate and license is only 85 lines long.  It is almost trivial to just replace the plugin.  However, if I wanted to do something more general, and support RestructuredText, for example, that is a much bigger burden.

I propose that a signal be added (probably to ``nikola.post.Post.text(...)`` or ``nikola.post.Post.compile(...)``) to allow SignalHandler plugins to intercept when a page is compiled to cache, before nikola does anything else with it.  The data on the signal should be a dictionary of the post source path, the cache file path, and the post object; perhaps more, but that is what comes to mind at least to me.

I considered suggesting that the signal be emitted from the compiler's ``compile_html`` method, however I decided against suggesting that - that would change the plugin api on everyone implementing compilers.

**Comment by Kwpolska** [comment]
:+1: for this.

**Comment by Kwpolska** [comment]
Closing via #2370.
