### ISSUE TITLE
Pandoc does not demote headers

### ISSUE THREAD

**Issue by tritium21** [getnikola/nikola#2371]
Documents compiled with pandoc do not demote headers.  I cannot tell if this is intentional (with the user intended to provide a filter or some other command line options in PANDOC_OPTIONS), or not, but turning this behavior on is a one line delta (set demote_headers = True in CompilePandoc).

**Comment by sukiletxe** [comment]
In Pandoc, you can achieve the same effect by using 
`--base-header-level==number`.

**Comment by tritium21** [comment]
@sukiletxe Does that mean the intended use of the pandoc plugin is to provide that argument in PANDOC_OPTIONS?  If so, then that should be documented (probably in the example comment in conf.py.in).  If it is not the intended use of the pandoc plugin, then the one-line delta to use Nikola's header demotion should be added.

**Comment by Kwpolska** [comment]
Intentional behavior. I think that demoting headers is fine for lightweight formats, like reST or Markdown, but Pandoc does formats that might work better as-is. Would you want to add a note to the `conf.py` file or should I do that myself?

**Comment by tritium21** [comment]
I'll write up a pull request.  Is changing the default example of PANDOC_OPTIONS acceptable

**Comment by Kwpolska** [comment]
If it’s commented out sure.

**Comment by Kwpolska** [comment]
PS. in the future, do this: https://help.github.com/articles/closing-issues-via-commit-messages/
