### ISSUE TITLE
Can mako templates use nikola caching?

### ISSUE THREAD

**Issue by leingang** [getnikola/nikola#2372]
Mako templates can be [cached](http://docs.makotemplates.org/en/latest/caching.html) on the level of defs, blocks, or pages.  They provide two hard-core caching backends: Beaker and Dogpile, but also an interface to plug in any caching system.

Nikola has a rudimentary [caching system](https://getnikola.com/extending.html#state-and-cache) to speed up page generation.  Caching is much less of an issue since, in a static site, pages are normally generated far less frequently than they are viewed.

However, since the pieces are there, can they not be glued together?

**Comment by ralsina** [comment]
We have enabled a mako template cache, it's in cache/.mako.tmp

**Comment by ralsina** [comment]
On second thought, we seem to b clearing that cache between runs!

**Comment by leingang** [comment]
How do I use it then? Because when I write a template like

    <%def name="html_main_nav()" cached="True">...

I get an exception:

    mako.exceptions.RuntimeException: Can't initialize Beaker plugin; Beaker is not installed.

**Comment by ralsina** [comment]
That makes no sense at all in Nikola. That's meant for dynamic systems, where you have to render the template everytime the page is requested. I *could* try to make Mako ignore the cached parameter somehow, though.

**Comment by ralsina** [comment]
Ahhhh I see, there are two cache things in Mako, what we are using is the module_directory, which is where Mako keeps the compiled templates so they don't have to be recompiled, this other cache option would keep the template instance in memory.

I'll take a look at it!

**Comment by leingang** [comment]
I agree it's not a priority for a static site generator that pages be rendered fast.  I'm only noticing it now because I'm in development mode—editing plugin modules or templates and rebuilding the site every few minutes.  

If you want to no-op caching, maybe add a warning that there is no caching taking place?

**Comment by ralsina** [comment]
The main problem with the available caching implementations is the added dependencies. I could check so that if dogpile is available it's used.

**Comment by ralsina** [comment]
Blah, dogpile doesn't even install correctly :-(

```
$ pip install dogpile
Collecting dogpile
  Downloading dogpile-0.2.2.tar.gz (101kB)
    100% |████████████████████████████████| 102kB 151kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vgrhixps/dogpile/setup.py", line 22, in <module>
        long_description=file(readme).read(),
    NameError: name 'file' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vgrhixps/dogpile/
(nikola) ralsina@clakker:~/Desktop/proyectos/nikola/master/nikola/plugins/template$ python
Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dogpile.cache
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'dogpile'
>>> 

```

**Comment by ralsina** [comment]
@leingang Looks like all you need to do is pip install beaker.

**Comment by leingang** [comment]
Excellent idea.

**Comment by ralsina** [comment]
If it does, we can add a note in the manual.

**Comment by tritium21** [comment]
@ralsina 'dogpile'  is dogpile.core  'dogpile.cache' ....should install.

**Comment by leingang** [comment]
I cleaned and rebuilt my site six times; the builds took an average of 20.43 seconds.  Then I cached one template def (the menu) and repeated the process.  The builds took an average of 19.11s.  So a 6% savings.

**Comment by ralsina** [comment]
@leingang it may be more if you cache more, right?

**Comment by leingang** [comment]
I would think so.  I targeted the menu because it's pretty big and it appears on every page.  I'll do the same with some of the other elements (the footer is another big one) and see what happens.

**Comment by ralsina** [comment]
Ok, so, no action really needed except adding a note in the docs. I will do that and close the issue.
