### ISSUE TITLE
Offer Nikola as a snap

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2374]
Hey, I work in related stuff, so it's going to be good practice for me, and the promise is that if it's done right, then installing Nikola on any Linux will be:

```
apt install snapd
snap login
snap install nikola
```

And how cool would that be? No more questions about libxml2, no more PIP+venv weirdness...

Tasks to consider this done:

- [x] Write basic snapcraft.xml including most used libraries for plugins
- [x] Register and upload to the store
- [x] Automate uploading of new snaps for releases in stable channel
- [x] Automate uploading snaps for master, per-commit via travis in edge channel
- [ ] Automate build/upload via travis?

* Automation is blocked until snapcraft supports pushing to specific channels and publishing uploads.
* Notebook don't pack well with latest snapcraft, bug reported

**Comment by Kwpolska** [comment]
> on any Linux

Even on Gentoo?

**Comment by ralsina** [comment]
Well, replace apt with "whatever" but yes.

**Comment by ParaplegicRacehorse** [comment]
Granted, Fedora 24 already appears to have snap support, but what about Flatpack?

**Comment by Kwpolska** [comment]
We’d need someone familiar with it. Also, it might be nicer to wait a while for the format wars to calm down.

*full disclosure: @ralsina is a Canonical employee.*

**Comment by ralsina** [comment]
Marking this as done, will someday automate.
