### ISSUE TITLE
How about to insert teaser end automatically?

### ISSUE THREAD

**Issue by re4lfl0w** [getnikola/nikola#2376]
I don't know How do I change my conf.py

I want to show teaser in index.html

reference: https://github.com/damianavila/damian_blog/blob/master/conf.py#L625
Ideal site: http://www.damian.oquanta.info/

- Show Read more.

but my site
https://re4lfl0w.github.io/
- didn't read more
- show me a lot of blog text. I hate this situation

- https://github.com/re4lfl0w/re4lfl0w.github.io/blob/src/conf.py#L773
- I check a lot of times. but I don't know why INDEX_TEASER didn't work.

**Comment by re4lfl0w** [comment]
I solved problem.
https://getnikola.com/handbook.html#teasers

I insert .. teaser end
success!

**Comment by re4lfl0w** [comment]
# How about to insert teaser end automatically?

- or how to set html[:200] -> teaser setting? Yes. I show about 200 length in html.

**Comment by ralsina** [comment]
Could you request that in a new issue instead of reviving this one? Makes the issue list messy :-)
