### ISSUE TITLE
Avoid percent encoding URLs

### ISSUE THREAD

**Issue by izahn** [getnikola/nikola#2377]
I'm deploying my blog to a web server provided by my employer. The URL includes `/~user`, which nikola converts to `/%7Euser`. I really wish that did not happen, both because it looks ugly, but more imprtantly because it breaks the isso commenting system. Can I somehow tell nikola to leave my URLs alone?

I read the documentation carefully but could not find an answer. I hope I didn't miss something obvious. If there is no setting to disable this than I suppose I can use the FILTER feature, bit I'm hoping there is an easier and better way.

**Comment by Kwpolska** [comment]
This is caused by the `encodelink()` function messing with absolute URLs and probably others. Do we really need it though? @Aeyoun?

**Comment by Aeyoun** [comment]
Yes, it’s still needed because Nikola allows all sorts of characters in tags and slugs.

`~` isn’t a reserved character and shouldn’t have be encoded (RFC 3986). This is a bug in encodelink().

**Comment by Aeyoun** [comment]
`urllib.parse.quote("/~testuser/docs")` returns `'/%7Etestuser/docs'` but `'/~testuser/docs'` is expected.

**Comment by Kwpolska** [comment]
Doesn’t work: https://travis-ci.org/getnikola/nikola/jobs/138386084#L1241
