### ISSUE TITLE
Allow setting custom GUID in feeds

### ISSUE THREAD

**Issue by julianbrost** [getnikola/nikola#2378]
It should be possible to set the GUID in RSS feeds or ID in Atom feeds to a value set in the post metadata. This helps renaming pages or moving the whole site to a new domain without the posts showing up as new in feedreaders.

I've already implemented this and I will submit a pull request soon.

I'm not yet sure about a detail: What should be the default GUID of new posts? It could either be their URL as it always is at the moment or a random value could be written to the file.

**Comment by Aeyoun** [comment]
Do you have a really good reason for adding this? This sounds like adding entirely unnecessary complexity with no practical purpose. What does Nikola gain from this feature?

As I see it, Nikola should not add the complexity of having separate IDs for GUIDs. Pretty much every CMS on the planet use the permalink as the GUID. It’s reliable and Nikola doesn’t need to keep track of custom GUIDs. There is no gain in allowing to customize this, and there is practically no purpose in preserving alternate GUID schemes from other CMSes that may use them either.

**Comment by julianbrost** [comment]
I'm thinking of moving my blog to a different domain, currently I see no way to do this with Nikola without having all posts show up as new in feed readers.

**Comment by Aeyoun** [comment]
> without having all posts show up as new in feed readers.

Very few feed readers actually use the GUID to determine whether soemthing is new or not. It’s more common to check if the URL and time stamp has changed.

**Comment by ralsina** [comment]
In any case, of those that use GUIDs, even fewer use the GUIDs to determine if something is new when the feed changes domain. Probably not worth your effort.

Yes, you will flood the planets once. It happens :-P

**Comment by julianbrost** [comment]
IMHO it's not a very good argument that there is software which does it wrong. Also the added complexity is very little. I also recommend reading https://web.archive.org/web/20110514113830/http://diveintomark.org/archives/2004/05/28/howto-atom-id

**Comment by tritium21** [comment]
Nikola is a very _Practicality Over Purity_ project.  This idea is great for purity to the spec, but in practical terms, adds little to nothing for a lot of increased complexity.  Practically speaking, if you change the URL of a feed in many (every single one I have used), the entire feed is treated as new no matter what the GUID of each item is set to.

**Comment by Aeyoun** [comment]
I’m kind of a feed geek and I implemented Atom in Nikola. I thought about having custom GUIDs, but I found no use for them whatsoever then. I haven’t seen anything to change my mind about it since.

**Comment by Kwpolska** [comment]
The consensus seems to be to reject this idea. I’ll close this.

**Comment by Kwpolska** [comment]
@julianbrost, could you make a pull request with your custom-guid branch?

**Comment by julianbrost** [comment]
Sure, #2687. Apart from rebasing, I changed two things: The documentation now suggests that the permalink is the default value for the GUID and the `lang` parameter is now passed from both call sites.
