### ISSUE TITLE
new_post -2 -i could (should?) copy a file instead of read it.

### ISSUE THREAD

**Issue by tritium21** [getnikola/nikola#2380]
I write my posts in MS Word, and have recently started trying to use the .docx files directly with Nikola.  Nikola supports compiling these documents out of the box, which is nice.  However, I would like to streamline the process further by using Nikola's built in import file functionality.

Currently, it attempts to read the file contents and pass it to the compiler's create post function.  While this works for most file types, it does not work for docx's binary file type (zipped xml) as it attempts to read the file as utf-8.

Because file types like docx have to use two file mode anyways, it would be convenient to copy the file instead of trying to read it when -2 is passed to new_post.

**Comment by ralsina** [comment]
Sounds good.

**Comment by Kwpolska** [comment]
:+1: from me. I’ll work on this later.

**Comment by tritium21** [comment]
The PR works great on my end.
