### ISSUE TITLE
 ReST plugin strips single title

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#2382]
I've noticed that if I have a .rst post which has one header, that one will be removed from the output. So if I have two pages:

Page 1:

```
Test
====

This is a test.
```

Page 2:

```
Test
====

This is a test.

Test2
=====

This is another test.
```

Then I would expect that Page 1 looks like Page 2 with the second section removed, but it ends up being just "This is a test." for Page 1 with the section header removed. I don't know why this is the default behavior, but I noticed it can be changed by modifying the ReST plugin by replacing

``` .py
return pub.writer.parts['docinfo'] + pub.writer.parts['fragment'], pub.document.reporter.max_level, pub.settings.record_dependencies
```

with

``` .py
return pub.writer.parts['html_title'] + pub.writer.parts['docinfo'] + pub.writer.parts['fragment'], pub.document.reporter.max_level, pub.settings.record_dependencies
```

at the end of `rst2html`.

I guess changing the default is not a good idea, but would it be acceptable to add an option to force inclusion of the HTML title?

**Comment by Kwpolska** [comment]
This is a rather problematic thing. You see, the first paragraph is considered the document title by reST. We accept that as a way of specifying the title of the entire post.

If we display that, people who use this format will have their post titles duplicated. Doing this in config might be problematic for people with mixed styles — and the Pelican support (which does not exist yet…) would actually require that. I think this can be made a bit smarter, but we need to know whether or not the document title was used. But then we’d need to tell the compiler that.

**Comment by felixfontein** [comment]
That's true, but even if I create a post with two headers:
```
Test
====

Test
-----

This is a test.
```
it will also result in just "This is a test.". (I think I even tried three different levels; they all went away.)

What about adding support for setting this via metadata? I.e. I could write:
```
.. title: This is a title.
.. show_all_titles: True

Test
====

This is a test.
```
And it will include the title. Would that be an acceptable solution?

(This could also be combined with a global variable which is by default `False`, and if the setting is specified in a post it will override the global behavior. But I'm already happy enough about being able to control this per post/page.)

**Comment by Kwpolska** [comment]
Your first thing is probably caused by subtitles also being a reST feature.

A best implementation is a silent one that does the right thing: it knows where the title came from. But this might require a change of things, because we’d need to tell `compile_html` about that.

**Comment by felixfontein** [comment]
Hmm, extracting that from the metadata and passing it on to `compile_html` is kind of more challenging; adding a new argument breaks compile plugins not delivered with Nikola. I guess that's not an option :)

Another possibility would be adding a new function to `PageCompiler`, like `compile_html_new`, which accepts one more argument, and then by default calls the old `compile_html` with less arguments, except for the ReST plugin, where it passes the parameters on. That's backwards compatible, but kind of sucks (the `PageCompiler` interface gets more messy).

The third option is to implement a global setting only. That doesn't require more information to be passed to `compile_html`. It has the drawback that you cannot toggle the setting per post, though. (For me that's fine, but as you mentioned it, for others it might not be.)

Or is there another (halfway clean) option?

**Comment by felixfontein** [comment]
(Ok, another solution is to create my own ReST plugin which re-uses most of Nikola's ReST plugin's code and changes this bit. This is what I'm doing now, until this issue gets resolved in one way or another.)

**Comment by ralsina** [comment]
Another solution is to make the rest plugin not use the DocTitle transform.

**Comment by felixfontein** [comment]
Works perfectly! Thanks a lot :)
