### ISSUE TITLE
CATEGORY_PAGES_DESCRIPTIONS is hierarchical, but CATEGORY_PAGES_TITLES is not

### ISSUE THREAD

**Issue by leingang** [getnikola/nikola#2384]
In a fresh site, I modified `conf.py` like this:

```
CATEGORY_ALLOW_HIERARCHIES = True
#...
# Set descriptions for category pages to make them more interesting. The
# default is no description. The value is used in the meta description
# and displayed underneath the category list or index page’s title.
CATEGORY_PAGES_DESCRIPTIONS = {
   DEFAULT_LANG: {
       "blogging": "Meta-blog posts about blogging about blogging.",
       "open source": "My contributions to my many, varied, ever-changing, and eternal libre software projects.",
       "open source/nikola" : "My contributions to Nikola"
   },
}

# Set special titles for category pages. The default is "Posts about CATEGORY".
CATEGORY_PAGES_TITLES = {
   DEFAULT_LANG: {
       "blogging": "Meta-posts about blogging",
       "open source": "Posts about open source software",
       "open source/nikola" : "Nikola posts",
       "nikola" : "Famous Nikolas"
   },
}
```

After building The category page for `open source/nikola` has the description "My contributions to Nikola" and title  "Famous Nikolas".

[niktest.zip](https://github.com/getnikola/nikola/files/337029/niktest.zip)

**Comment by felixfontein** [comment]
@leingang: can you verify that the `fix-category-hierarchy-title` branch fixes the problem for you?

**Comment by leingang** [comment]
I tried, but didn't notice a difference.  But I am new to this, and perhaps I didn't do it right.  Here's what I did to run the branch version:

1. Create a new virtualenv called `nikola-test`.  Activate it.
2. `pip install https://github.com/getnikola/nikola/archive/fix-category-hierarchy-title.zip`
3. Check that `which nikola` returns the one in the `nikola-test` directory.  
4. In the MWE directory, run `nikola clean; nikola build`. 

Still `http://0.0.0.0:8001/categories/cat_open-source-nikola.html` has the title I gave to the `nikola` category instead of the one I gave to the `open source/nikola` category.

**Comment by ffdybuster** [comment]
Hmm, I don't know what you did wrong, but for me the branch fixes the problem. I created a new demo site, added your config extract from above into `conf.py`, and changed the category of the default post to `open source/nikola`. The resulting category's page starts with:
```
Nikola posts

My contributions to Nikola```
Did you try to delete the `output` folder and rebuilding the whole blog? Also, try `less output/categories/cat_open-source-nikola.html` to inspect whether the generated HTML equals what is shown in your browser.

**Comment by felixfontein** [comment]
(Sorry, logged in with wrong account.)

I also tried your demo page (`niktest.zip`), after running `nikola build` the title was "Nikola posts" instead of "Famous Nikola".

**Comment by leingang** [comment]
OK, I'll recheck.

**Comment by leingang** [comment]
It seems to work now.  I think the problem was that in my shell, I have `nikola` aliased to my "regular" virtualenv executable.  Despite the fact that `which nikola` was returning the test-branch one, I was actually running v7.7.8. 😊  Good to go!

**Comment by felixfontein** [comment]
Cool! I'll merge, then.
