### ISSUE TITLE
Default RSS link is ugly

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [getnikola/nikola#2387]
I can't help but think if the RSS link is to be in the menu, it should be a proper page with the navigation and any other whizbang site elements included. Most RSS readers, when pointed at the root URI, will find the file rss.xml without need for a direct reference.

I suppose I could create this on my own, but I really think this should be a default behavior; or at least an option in conf.py.

![Yuck!](https://cloud.githubusercontent.com/assets/7605896/16541813/094ab584-403b-11e6-91ea-c54fb58fd0fd.png)

**Comment by Kwpolska** [comment]
We’d need to work on a custom XSLT template for every theme. Not worth the hassle. You can always [write your own](https://github.com/getnikola/nikola/blob/master/nikola/data/themes/base/assets/xml/rss.xsl).

**Comment by Aeyoun** [comment]
@ParaplegicRacehorse, I think you’re misunderstanding what you’re seeing. Look at the RSS address shown on the page, and then look at the page’s URL … . That “ugly page” is the actual RSS file. The text is just there to help people put it into their readers if their browser hasn’t pushed the RSS to their feed readers automatically. You can modify the XSLT to your hearts contents. Please do feel free to share your modified XSLT if you believe you make make a more helpful and prettier page.

**Comment by ralsina** [comment]
I don't understand the issue.

If giving the root URL is enough, just give the root URL. If you don't want
the RSS link in the lanyon theme's left bar, don't put it in your
navigation links :-)
