### ISSUE TITLE
Using special font for blog-title

### ISSUE THREAD

**Issue by Fotofreund** [getnikola/nikola#2388]
I want to create a new site for a photo club with Nikola 7.7.9 and Bootstrap3.
The menu bar should look like this:

| Our Photo Club | Galleries (submenu) | Photographers (submenu) | Legal info (submenu) |

The blog-title "Our Photo Club" should use a special free web font. Unfortunately I cannot figure out where and how I have to add the information about this font.

Can someone give me some help?

**Comment by ralsina** [comment]
You can do that using CSS.

In the bootstrap3 theme, that title has ID "blog-title", so you can create
a files/assets/css/custom.css and something like

#blog-title {
   font-name: whatever
}

If you need to load the font from the web, you should add the proper link
element for that in conf.py in EXTRA_HEAD_DATA, which gets added in all
your pages' <head> element.

**Comment by Fotofreund** [comment]
Thanks for the fast answer. But it is not yet working.
The assets/css/custom.css contains:

`#blog-title { font-name: Romaneste-Regular } `

In  conf.py I have this:

```
# Extra things you want in the pages HEAD tag. This will be added right
# before </head>
# (translatable)
EXTRA_HEAD_DATA = "@font-face {font-family: 'Romaneste-Regular'; src:url('/assets/fonts/Romaneste-Regular.ttf.woff') format('woff'), url('/assets/fonts/Romaneste-Regular.ttf.svg#Romaneste-Regular') format('svg'), url('/assets/fonts/Romaneste-Regular.ttf.eot'), url('/assets/fonts/Romaneste-Regular.ttf.eot?#iefix') format('embedded-opentype'); font-weight: normal; font-style: normal;}"

```

In the index.html it is not added before  `</head>` but after `<body>` :
```
<link rel="icon" href="images/ffh_symbol.jpg" sizes="158x158">
<!--[if lt IE 9]><script src="assets/js/html5.js"></script><![endif]-->
</head>
<body>
<p>

    @font-face {font-family: 'Romaneste-Regular'; src:url('/assets/fonts/Romaneste-Regular.ttf.woff') format('woff'), url('/assets/fonts/Romaneste-Regular.ttf.svg#Romaneste-Regular') format('svg'), url('/assets/fonts/Romaneste-Regular.ttf.eot'), url('/assets/fonts/Romaneste-Regular.ttf.eot?#iefix') format('embedded-opentype'); font-weight: normal; font-style: normal;}


        <link rel="prefetch" href="posts/experimente-mit-der-logo-schrift/" type="text/html"></p>
<a href="#content" class="sr-only sr-only-focusable">Springe zum Hauptinhalt</a>

<!-- Menubar -->
```

Even if I open the `index.html` and move this `@font-face `part before the `</head>` it is not working.

Mmmmh, any idea?

**Comment by ralsina** [comment]
That appearing after <body> is because your EXTRA_HEAD_DATA is not valid HTML, it's CSS, and putting it in HEAD would make the page invalid. 

You should wrap it in a <style> tag:

```
<style media="screen">
@font ....
</style>
```

Or perhaps put it in files/assets/css/custom.css instead

**Comment by Fotofreund** [comment]
Thanks a lot. That did most of the job.

Together with one of my colleagues I found some other faults I had done. Getting the quoting of EXTRA_HEAD_DATA right, putting the custom.css in the correct folder and fixing some links.

Now I can try to convince the other club members and publish the new static web site.
