### ISSUE TITLE
Changes to template used by .. post-list do not trigger a rebuild

### ISSUE THREAD

**Issue by tritium21** [getnikola/nikola#2391]
What it says on the tin.  When using a custom template in the ``.. post-list`` directive...

    .. post-list::
       :tags: some-tag
       :reverse:
       :template: my_template.tmpl

... and you edit the template, ``nikola build`` will not see the post (page in my case) as out of date.  I can understand why this might be unfixable (I cannot think of a way of injecting into file deps from inside a directive, or modify uptodate for that matter), but if it is fixable, it might be a route towards fixing the other warnings given about the directive in the handbook.

**Comment by tritium21** [comment]
Actually, looking at the code, you could do ``state.document.settings.record_dependencies.add`` on the template, and perhaps on the files of the already included posts' ``translated_source_path``.  Without refactoring what site.timeline is (something which has come up on irc), I can't think of a way to get rid of the magic dependency on the timeline itself.

**Comment by Kwpolska** [comment]
Do we need `translated_source_path`? Is the base path not enough?

**Comment by tritium21** [comment]
Thats the solution already in place, and the handbook admonishes users that updating the contents of a post may not trigger an update to posts with this directive.  If translated base path is enough, perhaps the docs should be updated?

**Comment by Kwpolska** [comment]
> Any post or page that uses this directive will be considered out of date, every time a post is added or deleted, causing maybe unnecessary rebuilds.

>   On the other hand, it will sometimes **not** be considered out of date if post content changes, so it can sometimes be shown outdated, in those, use ``nikola build -a`` to force a total rebuild.

This might refer to other corner cases, I honestly don’t know. Let’s just leave it as is.
