### ISSUE TITLE
Migrating from blogger to Nikola

### ISSUE THREAD

**Issue by ChillarAnand** [getnikola/nikola#2398]
`import_blogger` has done most of the work. Thanks for amazing work.

I am facing some issues. If there are any solutions, please let me know.

-  Is it possible to disable colored logging or support white colored themes also(like ipython)? It is very hard to read errors on white colored themes.

![nn](https://cloud.githubusercontent.com/assets/4463796/17079668/15ecc95c-5135-11e6-978b-5e49b881a81c.png)
![nn2](https://cloud.githubusercontent.com/assets/4463796/17079667/15eb8dda-5135-11e6-852a-800403353163.png)
-  url redirections is throwing error.

```py
REDIRECTIONS = [
    ('/2016/06/auto-completion-for-custom-search.html', '/posts/201606auto-completion-for-custom-search.html'),
]
```
is throwing 
```py
[2016-07-23T18:55:51Z] ERROR: auto: Scanning posts.....done!
.  redirect:/2016/06/auto-completion-for-custom-search.html
########################################
TaskError - taskid:redirect:/2016/06/auto-completion-for-custom-search.html
PythonAction Error
Traceback (most recent call last):
  File "/home/chillaranand/.virtualenvs/exp/lib/python3.5/site-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/chillaranand/.virtualenvs/exp/lib/python3.5/site-packages/nikola/utils.py", line 1654, in create_redirect
    makedirs(os.path.dirname(src))
  File "/home/chillaranand/.virtualenvs/exp/lib/python3.5/site-packages/nikola/utils.py", line 232, in makedirs
    os.makedirs(path)
  File "/home/chillaranand/.virtualenvs/exp/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/chillaranand/.virtualenvs/exp/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/2016'
```

-  url_map.csv created by nikola has extra `/` on to urls

```
http://www.avilpage.com/2013/03/avil-page-unblock-me-all-solutions.html,http://www.avilpage.com//posts/201303avil-page-unblock-me-all-solutions.html
http://www.avilpage.com/2014/01/list-of-tollywood-movies-copied-from-hollywood.html,http://www.avilpage.com//posts/201401list-of-tollywood-movies-copied-from-hollywood.html
http://www.avilpage.com/2014/01/jason-wishnow-quote-on-creativity.html,http://www.avilpage.com//posts/201401jason-wishnow-quote-on-creativity.html
```

- Is it possbile to remove `/posts` slug from post urls?

**Comment by punchagan** [comment]
> Is it possbile to remove /posts slug from post urls?

Setting POSTS to something like this, should fix this. 

```python
POSTS = (
    ("posts/*.rst", "", "post.tmpl"),
    ("posts/*.txt", "", "post.tmpl"),
    ("posts/*.html", "", "post.tmpl"),
)
```

[This section](https://getnikola.com/handbook.html#how-does-nikola-decide-where-posts-should-go) of the handbook may be useful to read.

**Comment by punchagan** [comment]
> Is it possible to disable colored logging or support white colored themes also(like ipython)? It is very hard to read errors on white colored themes.

https://github.com/getnikola/nikola/issues/2360

**Comment by Kwpolska** [comment]
> url redirections is throwing error.
> ```py
REDIRECTIONS = [
    ('/2016/06/auto-completion-for-custom-search.html', '/posts/201606auto-completion-for-custom-search.html'),
]
```

The problem here is the leading slash, it means “directory /2016 from the **root** of your hard drive. Remove the first slash:

```py
REDIRECTIONS = [
    ('/2016/06/auto-completion-for-custom-search.html', '/posts/201606auto-completion-for-custom-search.html'),
]
```

Were those generated by `import_blogger` or did you do that yourself? This could be a bug.

> Is it possbile to remove /posts slug from post urls?

Yes, look at @punchagan’s example. You could also try preserving your old directory structure (which means you won’t need redirections):

```
mkdir -p posts/2016/06
mv posts/201606auto-completion-for-custom-search.html posts/2016/06/auto-completion-for-custom-search.html
# edit the .html file and remove 201606 from slug
# this can all be automated
```

**Comment by ChillarAnand** [comment]
`import_blogger` has generated a csv file like this

```
http://www.avilpage.com/2013/03/avil-page-unblock-me-all-solutions.html,http://www.avilpage.com//posts/201303avil-page-unblock-me-all-solutions.html
http://www.avilpage.com/2014/01/list-of-tollywood-movies-copied-from-hollywood.html,http://www.avilpage.com//posts/201401list-of-tollywood-movies-copied-from-hollywood.html
http://www.avilpage.com/2014/01/jason-wishnow-quote-on-creativity.html,http://www.avilpage.com//posts/201401jason-wishnow-quote-on-creativity.html
http://www.avilpage.com/2014/01/list-of-bangalore-start-up-companies.html,http://www.avilpage.com//posts/201401list-of-bangalore-start-up-companies.html
http://www.avilpage.com/2013/12/top-10-most-visited-telugu-websites.html,http://www.avilpage.com//posts/201312top-10-most-visited-telugu-websites.html
http://www.avilpage.com/2014/11/pandoc-best-way-to-convert-markdown-to.html,http://www.avilpage.com//posts/201411pandoc-best-way-to-convert-markdown-to.html
```

Since `REDIRECTIONS` need relative url, I have changed them to 

```
REDIRECTIONS = [
    ('/2016/06/auto-completion-for-custom-search.html', '/posts/201606auto-completion-for-custom-search.html'),
]
```

**Comment by ChillarAnand** [comment]
- Is it possible to redirect home page to archives page?

- How to modify archive page? I couldn't find which template is being used for that?

**Comment by ralsina** [comment]
Sure, playing with ARCHIVE_PATH and ARCHIVE_FILENAME should do it. You may run into collisions with the usual indexes that can be avoided playing with INDEX_PATH

Something like this:

```
INDEX_PATH = 'blog'
ARCHIVE_PATH = ''
ARCHIVE_FILENAME = 'index.html'
```

**Comment by ralsina** [comment]
Archives use list_post.tmpl

**Comment by ChillarAnand** [comment]
Thank you @punchagan @Kwpolska @ralsina for the help :-)

**Comment by ChillarAnand** [comment]
In Nikola, all posts tagged with `python` appear at `/categories/python.html`. Blogger used to show them at `/search/label/python`. Since there are several such links in posts, I created a redirection rule

    ('/search/label/python', '/categories/python.html'),

Now, when I visit `/search/label/python`, it is not redirecting to target. Instead it is downloading the file with redirection details. I guess this is happening as there is no trailing `.html` in from url. Can you suggest a way to fix this?

Also if i set `PRETTY_URLS = True`, nikola generates `/some-slug/index.html`. Is there a way to remove `.html` from url completely and just keep `/some-slug` ?

**Comment by Kwpolska** [comment]
> Now, when I visit /search/label/python, it is not redirecting to target. Instead it is downloading the file with redirection details. I guess this is happening as there is no trailing .html in from url. Can you suggest a way to fix this?

Use `search/label/python/index.html` in your redirections.

> Also if i set PRETTY_URLS = True, nikola generates /some-slug/index.html. Is there a way to remove .html from url completely and just keep /some-slug ?

If you use `PRETTY_URLS`, Nikola does generate that HTML file, but it’s referred to as  `/some-slug/` — set `STRIP_INDEXES = True` to use `/some-slug/` instead of `/some-slug/index.html`.

You can’t get URLs without a slash (at least, not without doing multiple hacky things); your web server will redirect `/foo` to `/foo/` automatically.

**Comment by ralsina** [comment]
Not from within Nikola. That is webserver configuration.

**Comment by ChillarAnand** [comment]
Thanks. Setting `STRIP_INDEXES = True` helped. Now all old posts/links are working fine.

If a new post `foo` is created with `new_post` command, it is throwing error.

```sh
[2016-07-30T15:41:15Z] INFO: auto: REBUILDING SITE (from posts/foo.txt)
[2016-07-30T15:41:18Z] ERROR: auto: Scanning posts......done!
ERROR: Two different tasks can't have a common target.'output/foo/index.html' is a target for render_indexes:output/foo/index.html and render_pages:output/foo/index.html.
```

**Comment by ralsina** [comment]
That means you have a post with slug 'index' in the same folder as where
your blog's indexes go. Move one or the other, or change the slug.

**Comment by ChillarAnand** [comment]
I already tried that, no matter what the slug is, it always throws the error.

```
[2016-07-30T15:54:57Z] INFO: auto: REBUILDING SITE (from posts/foobar.txt)
[2016-07-30T15:55:00Z] ERROR: auto: Scanning posts......done!
ERROR: Two different tasks can't have a common target.'output/foobarbbbbbbbbbbbbbbbbbb-bbbbbbbb/index.html' is a target for render_pages:output/foobarbbbbbbbbbbbbbbbbbb-bbbbbbbb/index.html and render_indexes:output/foobarbbbbbbbbbbbbbbbbbb-bbbbbbbb/index.html.
```
