### ISSUE TITLE
Directive "post-list" generates "[]" as text instead of no text when the search for a tag returns nothing

### ISSUE THREAD

**Issue by richieadler** [getnikola/nikola#2400]
If a post-list directive for a certain tag finds no posts or pages containing the tag, the directive prints "[]" instead of just no text.

For instance, check http://www.sindioses.org/cienciaorigenes/indiceac/lista.html#cb700. The section CB700 is generated by the following fragment:

```rest
.. _CB700:

* CB700: Biología del desarrollo

  .. post-list::
     :tags: CB700
     :sort: title
     :template: post_list_bullet.tmpl
     :all:
```

There's no posts nor pages with metadata ```.. tags: CB700```.

This is on Nikola v7.7.8 (Windows 7, Python 3.4.3)

**Comment by Kwpolska** [comment]
Fixed in v7.7.11, please upgrade.
