### ISSUE TITLE
System message for slug not found does not contain the slug name.

### ISSUE THREAD

**Issue by richieadler** [getnikola/nikola#2401]
All missing slug error messages now report the slug name as `"None"` instead of the slug.

**System Message: ERROR/3 (\<string\>, line 10); backlink
“None” slug doesn’t exist.**

Nikola 7.7.11, Windows 7, Python 3.5.1

**Comment by tritium21** [comment]
That looks like there is a blank metadata directive.  Can you post the metadata section of the offending post?

**Comment by Kwpolska** [comment]
It was returning `None` instead of the slug, sorry. Fixed in master.
