### ISSUE TITLE
How to add statics files?

### ISSUE THREAD

**Issue by ChillarAnand** [getnikola/nikola#2414]
I am trying to add a [style sheet](https://github.com/ChillarAnand/avilpage.com/blob/master/themes/avilpage/assests/css/style.css)  in [base template](https://github.com/ChillarAnand/avilpage.com/blob/master/themes/avilpage/templates/base_helper.tmpl#L18-L21) for a custom theme.

If you look into source code of [this page](https://chillaranand.github.io/avilpage.com/), nikola is not serving that file?

**Comment by Kwpolska** [comment]
> assests/css

You mispelled the word `assets`

PS. for general usage advice, we prefer IRC (#nikola @ freenode) or the mailing list (nikola-discuss).
