### ISSUE TITLE
Gallery index links have `%2F` at the end (windows)

### ISSUE THREAD

**Issue by jladan** [getnikola/nikola#2416]
The auto-generated index of galleries (/galleries/) adds `%2F` into the links. I think this is a Windows specific bug, because `%2F` is the url encoding for `\`.

Example of generated html:

```
<li><a href="test%2F"><i class="icon-folder-open"></i> test</a></li>
```

I'm using the "base" theme.

**Comment by Kwpolska** [comment]
The base theme was using a `u` filter for some reason, fixed. Also, U+002F is *forward* slash (`/`), so it was probably an issue on other OS-es, too.
