### ISSUE TITLE
'nikola new_page -2' with nested path places .meta at pages root, content file at indicated path

### ISSUE THREAD

**Issue by barryhawkins** [getnikola/nikola#2420]
Steps to Reproduce
================
Hi, while creating new content in a directory beneath the root of my pages directory, I am seeing the following behavior:

    $ nikola new_page --title="Two-File Page in Nested Folder Places meta in Pages Root" --author="Barry Hawkins" -2 --format=markdown stories/nested-content/two-file-page-in-nested-folder-places-meta-in-pages-root.md
    Creating New Page
    -----------------
    
    Title: Two-File Page in Nested Folder Places meta in Pages Root
    Scanning posts........done!
    [2016-07-31T23:12:05Z] INFO: new_page: Your page's metadata is at: stories/two-file-page-in-nested-folder-places-meta-in-pages-root.meta
    [2016-07-31T23:12:05Z] INFO: new_page: Your page's text is at: /home/barryh/Projects/two-file-non-root-page-error/stories/nested-content/two-file-page-in-nested-folder-places-meta-in-pages-root.md

The result is that the .meta file is placed in `stories`, while the .md file is placed appropriately in its indicated path:

    $ ls -R stor*
    stories:
    nested-content  two-file-page-in-nested-folder-places-meta-in-pages-root.meta
    
    stories/nested-content:
    two-file-page-in-nested-folder-places-meta-in-pages-root.md

This definitely seems to not be intended, as a build reveals that the rendered page does not include the title value for the page that is indicated in the associated .meta file:

    <header><h1 class="p-name entry-title" itemprop="headline name"><a href="." class="u-url">two-file-page-in-nested-folder-places-meta-in-pages-root</a></h1>
    </header>

Manually moving the .meta file to reside alongside the .md file results in the title being appropriately placed into the rendered page:

    $ mv stories/two-file-page-in-nested-folder-places-meta-in-pages-root.meta stories/nested-content
    $ ls -R stor*stories:
    nested-content
    
    stories/nested-content:
    two-file-page-in-nested-folder-places-meta-in-pages-root.md
    two-file-page-in-nested-folder-places-meta-in-pages-root.meta`

Following that step, the desired result for the title appears:

    <header><h1 class="p-name entry-title" itemprop="headline name"><a href="." class="u-url">Two-File Page in Nested Folder Places meta in Pages Root</a></h1>
    </header>

Suggestion
=========
If the .meta file placement could follow the same directive as the compiler-formatted file (I tested this behavior with rest as well), that should resolve the issue. Thanks for all your work on this tool!

**Comment by Kwpolska** [comment]
Good catch, fixed. Thanks!

(PS. You don’t need to write all this when reporting a bug to us, it’s obvious from just the `new_page` terminal transcript — thanks for trying to debug yourself though)
