### ISSUE TITLE
admonitions (warning, attention, hint, ...) not localized

### ISSUE THREAD

**Issue by Netspider** [getnikola/nikola#2422]
(reST?) Admonitions are not localized in Nikola. The Docutils localization strings are already present in **docutils/languages/de.py**, but changing DEFAULT_LANG to "de" in conf.py does not use these localized strings when using the following (reST) code:

    .. attention:: Headline
    
            Contents

The heading should be "Achtung!" but instead it is "Attention!"

**Comment by Netspider** [comment]
there is a workaround if the whole blog only contains one language:

    cat ~/.docutils
    [general]
    language_code=de

**Comment by ralsina** [comment]
Looks like we are not passing language_code to docutils, should not be hard to fix, taking a look now.
