### ISSUE TITLE
Make shortcodes a first-class citizen

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2424]
Looking at #2306 I decided to implement it as a shortcode that would live in our plugins repo.

I ran into a few problems, so I plan to solve them to make writing shortcodes a good way to contribute to Nikola. Listing them here as I find them.

- [x] There is no shortcode plugin type. Can't use BasePlugin because those are never activated, other types have other functions (#2425).
- [x] For shortcodes that use templates, the template is not accounted for as a post dependency.
- [x] For shortcodes that use a data file (in this example, a calendar file), it's not accounted for as a dependency
- [x] Shortcodes with templates are limited to monolingual templates
- [x] Shortcodes with templates don’t have access to global context

**Comment by Kwpolska** [comment]
> Shortcodes with templates are limited to monolingual templates

Do we pass any context to those templates? If yes, we could just give them `lang` and let users make an if-elif-else tree, or if they’re doing Mako, dict dispatch.

**Comment by ralsina** [comment]
@Kwpolska that sounds reasonable, I'll give it a try

**Comment by ralsina** [comment]
The two last items are implemented in #2443

**Comment by IbnSaeed** [comment]
Will it be released in 7.7.13 ?

**Comment by Kwpolska** [comment]
Of course. (Unless we release v7.8.0 or v8.0.0 next.)
