### ISSUE TITLE
EXTRA_THEMES_DIRS?

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#2427]
I started reorganizing my Nikola projects (by moving them around), when I noticed that Nikola will load themes only from `./themes` or from the `themes` directory from Nikola's install, and that it is not possible to specify additional theme dirs (similar to `EXTRA_PLUGINS_DIRS`).

Is there a reason for this? Or does anyone mind if I add a setting `EXTRA_THEMES_DIRS`?

**Comment by ralsina** [comment]
Fine by me.
