### ISSUE TITLE
Asciidoc build fails on nikola 7.7.12

### ISSUE THREAD

**Issue by IbnSaeed** [getnikola/nikola#2431]
Hello

I have installed asciidoc plugin and made the following changes in conf.py

> POSTS = (
>     ("posts/*.rst", "posts", "post.tmpl"),
>     ("posts/*.txt", "posts", "post.tmpl"),
>     **("posts/*.adoc", "posts", "post.tmpl"),**
>     ("posts/*.html", "posts", "post.tmpl"),
> )
> PAGES = (
>     ("stories/*.rst", "stories", "story.tmpl"),
>     **("stories/*.adoc", "stories", "story.tmpl"),**
>     ("stories/*.txt", "stories", "story.tmpl"),
>     ("stories/*.html", "stories", "story.tmpl"),
> )
> 

----

> COMPILERS = {
>     "rest": ('.rst', '.txt'),
>     "markdown": ('.md', '.mdown', '.markdown'),
>     "textile": ('.textile',),
>     **"asciidoc": ('.asciidoc', '.adoc', '.asc'),**
>     "txt2tags": ('.t2t',),
>     "bbcode": ('.bb',),
>     "wiki": ('.wiki',),
>     "ipynb": ('.ipynb',),
>     "html": ('.html', '.htm'),
>      "php": ('.php',),
>  }
> 

After creating a new post with `nikola new_post -f asciidoc`

I am having the following issue when running `nikola build`

> Scanning posts.........done!
> .  render_posts:cache/posts/asciidoc.html
> ########################################
> TaskError - taskid:render_posts:cache/posts/asciidoc.html
> PythonAction Error
> Traceback (most recent call last):
>   File "/home/user/ssg/nikola/mysite/plugins/asciidoc/asciidoc.py", line 56, in compile_html
>     subprocess.check_call((binary, '-b', 'html5', '-s', '-o', dest, source))
>   File "/usr/lib/python3.5/subprocess.py", line 576, in check_call
>     retcode = call(*popenargs, **kwargs)
>   File "/usr/lib/python3.5/subprocess.py", line 557, in call
>     with Popen(*popenargs, **kwargs) as p:
>   File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
>     restore_signals, start_new_session)
>   File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
>     raise child_exception_type(errno_num, err_msg)
> FileNotFoundError: [Errno 2] No such file or directory: 'asciidoc'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/user/ssg/nikola/nikola-env/lib/python3.5/site-packages/doit/action.py", line 383, in execute
>     returned_value = self.py_callable(*self.args, **kwargs)
>   File "/home/user/ssg/nikola/nikola-env/lib/python3.5/site-packages/nikola/post.py", line 512, in compile
>     self.is_two_file)
>   File "/home/user/ssg/nikola/mysite/plugins/asciidoc/asciidoc.py", line 58, in compile_html
>     if e.strreror == 'No such file or directory':
> AttributeError: 'FileNotFoundError' object has no attribute 'strreror'
> 

Any tips on solving this issue ?

**Comment by IbnSaeed** [comment]
Found the issue.

I did not have asciidoc on my system installed. Just installed it and now the build works fine.

Please close this ticket as its solved.

**Comment by Kwpolska** [comment]
I pushed a very minor patch to the plugin to make reporting better.

**Comment by IbnSaeed** [comment]
@Kwpolska Thanks for the patch. It would help others who get into the same issue.
