### ISSUE TITLE
How to translate the following code from rSt ?

### ISSUE THREAD

**Issue by IbnSaeed** [getnikola/nikola#2432]
I have installed the following plugin `book_figure`

> 
>     .. book_figure:: Get Nikola
>         :class: book-figure
>         :url: http://getnikola.com/
>         :author: Roberto Alsina
>         :author_url: http://ralsina.me/
>         :isbn_13: 1234567890123
>         :isbn_10: 1234567890
>         :asin: B001234567
>         :image_url: http://getnikola.com/galleries/demo/tesla2_lg.jpg
> 
>         Your review.

I got it to work with rSt markup, but how do i do it in asciidoc ?

**Comment by Kwpolska** [comment]
The book figure plugin supports only reST markup. You can easily create your own [template shortcode](https://getnikola.com/handbook.html#shortcodes) for AsciiDoc (and any other input format). While certain reST extensions are available as shortcodes, most of them aren’t.

The plugin just takes data and displays it nicely, your shortcode can do the same pretty easily. You could also contribute your shortcode to our docs.

**Comment by Kwpolska** [comment]
Also, generic usage questions are best asked [on the mailing list or on IRC](https://getnikola.com/contact.html), GitHub Issues are better for bugs/issues/weird behavior/your contributions to Nikola.

**Comment by IbnSaeed** [comment]
@Kwpolska Thanks.

**Comment by ralsina** [comment]
OTOH, I am not sure I added shortcode support to the asciidoc plugin. It's easy to do, tho :-P
