### ISSUE TITLE
Docutils system messages: language "fa" not supported: Docutils-generated text will be in English.

### ISSUE THREAD

**Issue by shahinism** [getnikola/nikola#2437]
I'm getting this error message with of some of my `Persian (fa)` posts (not all of them). But there is no obvious problem in rendered results. 

![screenshot from 2016-08-10 00-21-39](https://cloud.githubusercontent.com/assets/698857/17531422/0bac134e-5e91-11e6-819d-a4d38f09f07f.png)

It seems to happen due to absence of Persian language in `Docutils` supported languages.

**Comment by ralsina** [comment]
Indeed that is the cause. You could offer to translate docutils, but it's a very slow project :-(

OTOH, you will mostly notice this in things like ".. contents::" ... and Nikola would not support translating those until a couple of weeks ago ;-)

**Comment by shahinism** [comment]
[Patch request submitted to docutils repo](https://sourceforge.net/p/docutils/patches/133/).

**Comment by Kwpolska** [comment]
Perhaps a better solution would be to default to 'en' if there is no translation (as we do with moment.js and colorbox)?

-- 
Chris Warrick <https://chriswarrick.com/>
PGP: 5EAAEA16

**Comment by ralsina** [comment]
@Kwpolska as a fallback, sure. I am not sure how to detect if docutils is missing a translation, tho.

**Comment by shahinism** [comment]
The patch [applied](https://sourceforge.net/p/docutils/patches/133/)

**Comment by ralsina** [comment]
@shahinism Awesome. It should be released before 2019, I expect ;-)
