### ISSUE TITLE
Auto does the wrong thing when code changes

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2441]
```nikola auto``` detects code changing, but instead of reloading the code and THEN launching a rebuild, it just launches a rebuild with the code from memory, which is still the old one, so that's useless.

**Comment by ralsina** [comment]
I may be saying complete nonsense.

**Comment by Kwpolska** [comment]
The only thing that wouldn't be reloaded is the auto server code itself,
which we can't fix anyways (at least not nicely)

-- 
Chris Warrick <https://chriswarrick.com/>
