### ISSUE TITLE
Tag descriptions are wiped out when TAG_PAGES_ARE_INDEXES is True

### ISSUE THREAD

**Issue by OvermindDL1** [getnikola/nikola#2444]
Same with categories.

What is happening is that it renders the page as a list of teaser posts, which is correct, however it does it by following the generic index callpath via `generic_index_renderer`, which then calls `generic_post_list_renderer`, which then does https://github.com/getnikola/nikola/blob/42a0b7f09a49972ea2970cd442111107716aa92f/nikola/nikola.py#L2001, which overwrites the tag/category description with the with the default blog description via `context["description"] = self.config['BLOG_DESCRIPTION'](lang)`, thus meaning that we cannot set it in our templates.

If https://github.com/getnikola/nikola/blob/e525b32ff0990efb81536da6d44cebaa95da4dfa/nikola/plugins/task/tags.py#L294 were changed to not set to "description" but rather something like "tag_description" then we would still be able to access it within our template.  And as it is I am unsure if description ever makes it through clobbered, so unsure why it is being set here at all..

**Comment by ralsina** [comment]
Good catch!

**Comment by ralsina** [comment]
Looking at that code, if the tag description was sent in ``extra_context['description']`` it would work, so it should be fixable.

**Comment by ralsina** [comment]
The problem seems to not be the clobbering, but just that the template used doesn't display the description. I need to think a little about this, probably needs some subtle tweaking (we probably don't want the main post indexes showing description)

**Comment by OvermindDL1** [comment]
I was trying to add such a description in my own template if the description exists, however it was being overwritten with another.  A separate name for the description or so would be perfect, basically if it exists then put it, else don't.  :-)

Hmm, actually the main post indexes would just be blank by default, but perhaps you could specify the empty key of "" to be the index, so someone could add a description if they want (arbitrary html maybe?  Would be great for a little news area or so).

**Comment by ralsina** [comment]
Check commit https://github.com/getnikola/nikola/commit/e3f12a66637ea817512138134d1c8f3aa2b8e489 it fixes this for me. Still the tagindex and tag templates need some rejiggering.

**Comment by OvermindDL1** [comment]
Awesome, I'll try it on my next site update and report if any issues.  I'm not noticing that the description is not being not overwritten in that commit though, did it happen in another?

**Comment by ralsina** [comment]
They were not overwritten at all :-)

If you check a few lines below where they appear to be overwritten, you'll see ``context.update(extra_content)`` ... that un-overwrites them, so to speak.
