### ISSUE TITLE
wordpress importer puts comma after each tag in url_map.csv

### ISSUE THREAD

**Issue by COLABORATI** [getnikola/nikola#2445]
I see in url_map.csv urls that have a comma after the tag, like
`http://example.com/tag/mycooltag,/categories/mycooltag.html`

This error seems to be only in that file, at least I do not see that in generated post meta data.

**Comment by Kwpolska** [comment]
This is correct. This is a URL map, which maps old WordPress URLs to your new Nikola URLs, for use with DISQUS or your web server redirections (both require extra parsing).
