### ISSUE TITLE
base.tmpl in templates/ is ignored

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2446]
Steps to reproduce:

```
nikola init -q foo
cd foo
nikola theme -c base.tmpl
nikola build # site will look normal
vim templates/base.tmpl # Change something obvious
nikola build #site doesn't reflect changes in template
```

This happens because it's not being detected as changed, and a ``nikola build -a`` fixes it.
So, it's a template dependency issue.

**UPDATE** a dumpdb shown nothing depends on base.tmpl. Ouch?

**UPDATE 2** This is wrong, index.tmpl inherits base.tmpl and should have it as dependency:

```
In [1]: site.template_system.template_deps('index.tmpl')
Out[1]: 
['/home/ralsina/Desktop/proyectos/nikola/master/nikola/data/themes/base/templates/index.tmpl',
 '/home/ralsina/Desktop/proyectos/nikola/master/nikola/data/themes/base/templates/comments_helper_disqus.tmpl',
 '/home/ralsina/Desktop/proyectos/nikola/master/nikola/data/themes/base/templates/comments_helper_livefyre.tmpl',
 '/home/ralsina/Desktop/proyectos/nikola/master/nikola/data/themes/base/templates/comments_helper_intensedebate.tmpl',
 '/home/ralsina/Desktop/proyectos/nikola/master/nikola/data/themes/base/templates/comments_helper_muut.tmpl',
 '/home/ralsina/Desktop/proyectos/nikola/master/nikola/data/themes/base/templates/comments_helper_googleplus.tmpl',
 '/home/ralsina/Desktop/proyectos/nikola/master/nikola/data/themes/base/templates/comments_helper_facebook.tmpl',
 '/home/ralsina/Desktop/proyectos/nikola/master/nikola/data/themes/base/templates/comments_helper_isso.tmpl',
 '/home/ralsina/Desktop/proyectos/nikola/master/nikola/data/themes/bootstrap3/templates/base_helper.tmpl',
 '/home/ralsina/Desktop/proyectos/nikola/master/nikola/data/themes/base/templates/annotation_helper.tmpl']
```

**Comment by felixfontein** [comment]
What do you mean by "put a `templates/base.tmpl` in my site"? If your `conf.py` is in `path/`, did you have the file in `path/templates/base.tmpl`? I didn't knew this was possible at all, I thought you had to create a theme (with parent `base`) for this.

**Comment by ralsina** [comment]
Yes, you totally can put a template in templates/whatever.tmpl and it will override your theme's :-)

In fact, if you just want to tweak one of your theme's templates, you can

```
nikola theme -c foo.tmpl
```

And it will copy the currently-used foo.tmpl into templates for you :-)

**Comment by ralsina** [comment]
BTW, I can't reproduce this anymore. DAAAAAAAAMN

**Comment by ralsina** [comment]
And now I can. Oh, mine, this bug is weird.
