### ISSUE TITLE
Subfolders in `templates/` of theme don't work anymore.

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#2447]
This line: https://github.com/getnikola/nikola/commit/a007b5bb#diff-aa5d5f047563cb707774460c7fb9a429R72 breaks my blogs where I have been doing the following in a theme:

In `themes/mytheme/templates`, I created a subfolder `include` and for example in `themes/mytheme/templates/index.tmpl`, I wrote
```
<%namespace name="helper" file="include/index_helper.tmpl"/>
```
to include `themes/mytheme/templates/include/index_helper.tmpl`. This worked fine until that a007b5bb stopped Nikola from finding that file and providing its path.

So I am wondering: am I doing something which shouldn't be allowed, or is Nikola doing something it shouldn't do?

**UPDATE** Currently it fails like this:

```
  File "/home/ralsina/.virtualenvs/nikola/lib/python3.5/site-packages/doit-0.29.0-py3.5.egg/doit/dependency.py", line 417, in get_state
    timestamp = os.path.getmtime(dep)
  File "/home/ralsina/.virtualenvs/nikola/lib/python3.5/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: 'includes/foo.tmpl'
```

Which suggests doit is getting that ``includes/foo.tmpl`` path in a dependency, which is wrong.

Yep, that's is:

```
In [1]: site.template_system.get_deps('/home/ralsina/Desktop/proyectos/nikola/master/foo/themes/base/templates/base.tmpl')
Out[1]: 
['themes/base/templates/base_helper.tmpl',
 'themes/base/templates/base_header.tmpl',
 'themes/base/templates/base_footer.tmpl',
 'themes/base/templates/annotation_helper.tmpl',
 'includes/foo.tmpl']
```

**Comment by ralsina** [comment]
I think this is the same problem as #2446

**Comment by ralsina** [comment]
It's *meant* to work, so it's a bug.

**Comment by felixfontein** [comment]
In that case, removing the `if` statement in that line might fix that. At least, it fixes this problem. I'm just wondering what other things it might break; I guess you didn't put that `if` in there just for fun ;)

**Comment by ralsina** [comment]
I suspect https://github.com/getnikola/nikola/blob/master/nikola/plugins/template/mako.py#L71 is baaaad.

**Comment by ralsina** [comment]
Probably breaks looking up templates in shortcodes if I remove it, which is less important anyway, but I'd prefer to make both things work :-)

**Comment by felixfontein** [comment]
Do you have an example of something which won't work without the `if`?

**Comment by ralsina** [comment]
IIRC: create shortcodes/foo.tmpl:

```
<% include bar.tmpl />
```

And then put a bar.tmpl in templates/ with anything in it.

Then, create a post saying

```
{{% foo %}}
```

That should show the content of bar.tmpl

**Comment by felixfontein** [comment]
Hmm, that works fine for me with the `if` removed.

**Comment by ralsina** [comment]
Then maybe it's not needed. It used to be, but maybe I fixed the same problem twice :-)

**Comment by ralsina** [comment]
@felixfontein can you check if https://github.com/getnikola/nikola/commit/e1d16418cdadc348ff729a5e70c1a8227eb04d50 fixes this one too?

**Comment by ralsina** [comment]
@felixfontein I *think* that fixes it and breaks nothing.

**Comment by felixfontein** [comment]
Good. Current master (rebased with from `earlytask_impl`) works fine for me.
