### ISSUE TITLE
When you have a markdown-only site, you miss shortcodes

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2449]
Because the shortcodes are implemented in reSt extension plugins, and those are not loaded.
Now that we have shortcode plugins, this needs refactoring.

**Comment by tritium21** [comment]
docutils is a non-optional requirement.  Unconditionally load it.

**Comment by ralsina** [comment]
Yes, but the code is still backwards. We should be more compiler agnostic,
not less.

**Comment by ralsina** [comment]
This will be fixed as part of #2459
