### ISSUE TITLE
listing: add a download link?

### ISSUE THREAD

**Issue by xuhdev** [getnikola/nikola#2452]
Do you think it would be a good idea if a download link can be provided for each listing?

**Comment by ralsina** [comment]
It's there now, each listing has a title and a link to the source file (as long as COPY_SOURCES is True in your conf.py) https://github.com/getnikola/nikola/issues/1995

Still not released, but if you get master from github it should "just work"

**Comment by xuhdev** [comment]
@ralsina Is it possible to make them two different options? `COPY_SOURCES` seem to be the option for the page sources.

**Comment by Kwpolska** [comment]
IMO listings should always copy source files so raw links are guaranteed to
work even for people who don't want post source files.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by tritium21** [comment]
Listings *are* source files though.

**Comment by ralsina** [comment]
We could except listings from the COPY_SOURCES setting.

**Comment by xuhdev** [comment]
Right, logically listings are source files, but from the perspective of user experience it's a very different thing.

Any way, I have another suggestion: in the listing page, instead of use the link `(source)`, would it be better to use `(download)`?
