### ISSUE TITLE
tag.tmpl and tagindex.tmpl need reviewing

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2457]
They differ in things they should be alike (like the metadata div) and have some repeated stuff that could be fixed via some inheritance or a helper tmpl.

**Comment by micheal** [comment]
Can I add in my +1? These templates caused me some headache while working on a custom theme for my site. I took me a while to figure it out.

**Comment by ralsina** [comment]
They caused me problems too, so let's fix this. Self-assigning.

**Comment by ralsina** [comment]
On second thought, I am not sure what I meant anymore. Stepping down.

**Comment by h4ckninja** [comment]
For me, the confusion was around `tagindex.tmpl` versus `tags.tmpl` vs `tag.tmpl` and the intermingling of categories in to that. At the time, I wanted the display of categories to be different from the display of tags, and it made things very frustrating.
