### ISSUE TITLE
Python 2 deprecated

### ISSUE THREAD

**Issue by augustot2** [getnikola/nikola#2461]
So, I recently started using nikola but although i've switched my python alias to :

> alias python='/usr/bin/python3'

I'm still getting the WARNING: Nikola: Python 2 is old and busted... message when I do nikola build command.

**Comment by ralsina** [comment]
@augustot2 what's the 1st line in the nikola script?

**Comment by augustot2** [comment]
sorry, what do you mean by nikola script?

**Comment by punchagan** [comment]
Running the command `which nikola` will tell you what the nikola script is.  What's the top line in it? 

Or just paste the output of:

```
head -n 2 `which nikola`
```

**Comment by ralsina** [comment]
Well, if @ãugusto2 is in some sort of Linux-like thing, that is.

**Comment by augustot2** [comment]
Sorry for not letting you know, I'm using Linux Ubuntu 16.04.
my output is:
#!/usr/bin/python

**Comment by ralsina** [comment]
@augustot2 so, that's the problem :-)

It's explicitly running ``/usr/bin/python`` which is python2, having an alias won't make a difference.
Also, your Nikola is probably installed in python2, not in python3, so if you were to edit that file and change it to python3 it would not work at all.

**Comment by augustot2** [comment]
It worked.Sorry for the dumb question!

**Comment by Kwpolska** [comment]
What worked? Installing with Python 3?

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by augustot2** [comment]
Yes, just uninstalled and reinstalled with python 3!
