### ISSUE TITLE
Support images in NAVIGATION_LINKS

### ISSUE THREAD

**Issue by xuhdev** [getnikola/nikola#2464]
I put the following in the navigation links

    ("some/url", '<img src="foo.png" width=40 height=40 />')

which does not seem to work well: the padding areas are too large around the image. After some inspection, it was caused by its parent `a`'s padding. The solution would be simple: allow users to specify the whole `a`, instead of the URL and the text separately. For example, users should be able to insert the following to NAVIGATION_LINKS:

    ('<a href="some/url" padding=0><img src="foo.png" width=40 height=40 /></a>',)

**Comment by tritium21** [comment]
It does not look like bootstrap even supports that.  However if it does, this is  a template modification you can make yourself relatively easily.

**Comment by Kwpolska** [comment]
Huge :-1: for providing custom <a> elements. You could add some custom CSS for images in links in the navigation bar. We do something like this for logo images

**Comment by ralsina** [comment]
Also, you can just put whatever you want there, and override the html_navigation_links function base_helper:

```
nikola theme -c base_helper.tmpl
```

Then edit it and make it create the right HTML. It's what the zen theme does, for example.

**Comment by ralsina** [comment]
So, let's close this. @xuhdev , try using one of these workarounds, feel free to ask if you run into trouble.
