### ISSUE TITLE
.. data:: could support TOML

### ISSUE THREAD

**Issue by tritium21** [getnikola/nikola#2466]
https://github.com/avakar/pytoml

Rational:
* TOML is a format that is coming into use in the python community (its being standardized as the config format of python package distributions)
* Its INI-like and therefor very human readable
* pytoml has an identical api to json and pyyaml
* it will take a couple of minutes to hack it into nikola.utils.load_data

I would have done the branch and PR myself right now, but... weekend, family, etc.

**Comment by ralsina** [comment]
Done in https://github.com/getnikola/nikola/commit/3bd89b7300c398b3260a71eaf63305693bd8061a
