### ISSUE TITLE
Research staticman

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2467]
https://staticman.net/

So, staticman lets you do forms, and then said forms get the data committed in a GH repo. The posts I've seen do things like using that to do comments by rebuilding the site using Jekyll's data feature.

I say no! I say we create a separate GH repo and then we use JS to get the data and do the right thing, no rebuilding needed, and then write a post about it and then live happily ever after.

**Comment by Kwpolska** [comment]
Staticman depends on someone else (GitHub) to rebuild stuff. If we were to integrate this/something similar, users would need to configure Travis CI or a custom build server.

**Comment by tritium21** [comment]
https://developer.github.com/v3/repos/contents/#get-contents

**Comment by ralsina** [comment]
There are tricks. I am good at tricks.

**Comment by ralsina** [comment]
Minor progress made here:
https://github.com/ralsina/staticman-data

That *should* be enough to let index.html post data to the repo (staticman is added as collaborator) but ... no dice. Asked for help in twitter, we'll see.

**Comment by ralsina** [comment]
After help from staticman, I have this pretty much understood.

- [ ] Add a staticman.yml file in a mostly empty repo
- [ ] Give staticman commit rights to that repo
- [ ] Use a form with a magic POST URL
- [ ] Use Nikola to parse that data or JS to fetch the data *
- [ ] Display the data *

And voilá, static, self-owned, self-hosted comments. Or pretty much anything else you really want to use a form for, really.

-----

* Work needed, not done yet

**Comment by ralsina** [comment]
Sorry, closed by accident.

**Comment by Kwpolska** [comment]
This is done, right?
