### ISSUE TITLE
Only read config when necessary

### ISSUE THREAD

**Issue by polyzen** [getnikola/nikola#2468]
Useful for commands like version and help (though @ralsina found no speed improvements when skipping this).

"although it probably needs a separate flag, needs_config is not perfect for this"

**Comment by ralsina** [comment]
Surprise! Reading the code, it turns out we already do this :-)

```python
        # Help and imports don't require config, but can use one if it exists
        needs_config_file = (argname != 'help') and not argname.startswith('import_')
```

Closing because really, it's very complicated to make smarter, and it will probably break a bunch of things for very little gain.
