### ISSUE TITLE
Global data support

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2477]
Jekyll-style: load data files from data/ and put them in global context, it's probably a 10-line patch

**Comment by tritium21** [comment]
Data should be namespaced in the global context.  I wouldn't want a misspelled key in a datafile to b0rk my entire site (very likely without an error message for feedback)

**Comment by ralsina** [comment]
Yes, it will be in GLOBAL_CONTEXT[data][nameofthefilewithoutextension]
