### ISSUE TITLE
Use the new data features and redo themes/plugins sites using Nikola

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2482]
For realz.

**Comment by Kwpolska** [comment]
I’m building something for this, without using data files (pre-alpha status): https://github.com/Kwpolska/nikola-plugins-v2

Work in progress (but patches and comments welcome).

**Comment by felixfontein** [comment]
I fixed some little things in https://github.com/Kwpolska/nikola-plugins-v2/commit/5be1006de267f8c2850a0f1a1ddfba324116fba0. In general, how should the workflow be? Creating PRs and merging them? Or just committing directly to master?

**Comment by Kwpolska** [comment]
Whatever.

**Comment by felixfontein** [comment]
BTW, your fix to `notebook_shortcode` doesn't work, as the field's name is `plugincategory` and not `Category`. (And yes, `Category` would have been a much better name.)

**Comment by Kwpolska** [comment]
That happens when you try to do stuff from memory. Fixed again.

**Comment by felixfontein** [comment]
(And the documentation in https://github.com/getnikola/plugins/blob/master/README.md is wrong, too: it mentiones `Category` instead of `plugincategory`.)

**Comment by felixfontein** [comment]
Maybe we should deprecate `plugincategory` and rename it to `Category`?

**Comment by Kwpolska** [comment]
We can’t, without breaking all backwards compatibility with any v7 release (Nikola depends on `plugincategory` in some places).

Speaking of v7 releases, v7.8.2 is going out tomorrow (cc @ralsina) and it might be nice to get some translations on Transifex before that.

**Comment by felixfontein** [comment]
BTW, `plugincategory` is used with two different cases (`PluginCategory` and `plugincategory`) in `nikola.py`:
```
                    if p[-1].details.has_option('Nikola', 'plugincategory'):
                        # FIXME TemplateSystem should not be needed
                        if p[-1].details.get('Nikola', 'PluginCategory') not in {'Command', 'Template'}:
[...]
                            p[-1].details.has_option('Nikola', 'plugincategory') and p[-1].details.get('Nikola', 'PluginCategory') in ('Compiler', 'PageCompiler'):
```
Is `has_option`/`get` case-insensitive?

**Comment by felixfontein** [comment]
Shouldn't `io.open(conf_sample, 'r', encoding='utf-8').read()` (and similar ones) use a `with` statement so that the file is closed again?

**Comment by Kwpolska** [comment]
(1) case-insensitive, I updated it to 'PluginCategory' all over the place. (2) Probably yes.

**Comment by felixfontein** [comment]
Ok, I'll change (2).

**Comment by felixfontein** [comment]
So, what's actually left to do for the new plugins page? It looks pretty much complete to me.

What about v6 plugin support? Is that going to be dropped?

**Comment by Kwpolska** [comment]
My plan is to remove the v6 directory and move all plugins to v7, because we don’t need to support v6. I guess I can look around for missing things and make it the new page, perhaps later today.

**Comment by felixfontein** [comment]
Ok, sounds good.

**Comment by felixfontein** [comment]
There's a problem with the generated plugin pages: the first paragraph in `README.md` is missing! See for example `/plugins/v7/german_slugify/`, where now most of the documentation is missing (since there's only a very short second paragraph and everything else was in the first).

**Comment by felixfontein** [comment]
That's because the `Post` object things the `.md` file has metadata at the top because `is_two_file` is set to `False`. Explicitly setting it to `True` in `pkgindex_scan.py` after constructing the `Post` object will fix this. That's not a really clean solution, though. Any better ideas?

**Comment by Kwpolska** [comment]
That’s the best fix we can do, really. At least without further hacks.

**Comment by felixfontein** [comment]
Ok. I've checked that in.

**Comment by Kwpolska** [comment]
Done on https://plugins.getnikola.com/ !

**Comment by felixfontein** [comment]
Cool!
