### ISSUE TITLE
Make config more consistent

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2485]
- [x] Rename POST_SECTION_NAME/TITLE → NAMES/TITLES (for consistency with similar settings for tags and categories)?
- [x] Update CODE_COLOR_SCHEME list, and make it two-three lines
- [x] Get rid of THEME_REVEAL variables from conf.py.in
- [x] Unify code for deprecating variables?

**Comment by mckea** [comment]
In the comments of conf.py, the example rst image directive appears to have a typo - missing space following the ".." ?

https://github.com/getnikola/nikola/blob/master/nikola/conf.py.in#L675

This is also the case with the example given in the handbook.

**Comment by Kwpolska** [comment]
Fixed that typo (and so could you with a simple pull request).
