### ISSUE TITLE
PostScanner plugins have problems due to compilers being disabled if not used by default post scanning plugin

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#2496]
Nikola only enables compilers which are used by posts found by the standard post scanning plugin (i.e. posts mentioned in `POSTS` and `STORIES`) despite them being mentioned in `COMPILERS`. So if another post scanning plugin tries to add posts which use compilers which appear in `COMPILERS`, but do not appear in `POSTS` and `STORIES`, Nikola won't compile these posts and stop with an error.

The main problem are the following lines in `nikola/nikola.py`:

``` .py
        # Avoid redundant compilers
        # Remove compilers that match nothing in POSTS/PAGES
        # And put them in "bad compilers"
        pp_exts = set([os.path.splitext(x[0])[1] for x in self.config['post_pages']])
        self.config['COMPILERS'] = {}
        self.disabled_compilers = {}
        self.bad_compilers = set([])
        for k, v in compilers.items():
            if pp_exts.intersection(v):
                self.config['COMPILERS'][k] = sorted(list(v))
            else:
                self.bad_compilers.add(k)
```

If `pp_exts.intersection(v)` is replaced by `True`, this problem goes away.

**Comment by ralsina** [comment]
Probably because I had totally forgotten post scanner plugins existed. I'll
take a look this weekend. Worst case, this optimization goes away.

**Comment by felixfontein** [comment]
One way to rescue the optimization is to ask the post scanner plugins which extensions they can find. And offer a way to indicate "I don't know" (by returning `None` instead of a list, or something like that), which results in this optimization to be disabled.

**Comment by ralsina** [comment]
@felixfontein Yes, if that can be done without breaking compatibility (meaning current behaviour is "I don't know") that works.

**Comment by felixfontein** [comment]
Hmm, I tried to give this a shot, but I found a pretty bad problem. @ralsina, what do you think? Feel free to play around with the branch or to delete it if you don't think this will ever work.
