### ISSUE TITLE
Set title for blog index

### ISSUE THREAD

**Issue by leonardder** [getnikola/nikola#2507]
Similar to getnikola.com, I have a site with a blog as a custom page. Where all the pages have a specific title as prefix before the main title, the blog page does not have one, which feels a bit inconsistent. Adding the functionality to give post page overviews a title like Blog, News or whatever would be very helpful.

**Comment by Kwpolska** [comment]
Are you talking about the `<title>` tag? Set `INDEXES_TITLE` in your `conf.py`.

**Comment by leonardder** [comment]
I'm sorry, I completely missed that one. Thanks!
