### ISSUE TITLE
ReCommonMark Compiler

### ISSUE THREAD

**Issue by tritium21** [getnikola/nikola#2508]
[Read the Docs](https://github.com/rtfd/recommonmark) has [written a wrapper](http://recommonmark.readthedocs.io/) around CommonMark that parses Markdown into a docutils AST.  This would let you - with a tiny bit of extra syntax - use any and all docutils directives in a Markdown document.

````rst
    ``` important:: Its a note! in markdown!
    ```
````

would be the same as the RST version...

`````rst
    .. important:: Its a note! in markdown!
`````

This *probably* should be a plugin.

**Comment by tritium21** [comment]
Prior art - [Remarkdown](https://github.com/sgenoud/remarkdown) also exists, but seems to be dormant/dead/unmaintained, and does the same thing.  RTFD is aware of this project, and decided to go another way.  As far as I understand it, ReCommonMark is used in production at Read the Docs.

**Comment by tritium21** [comment]
@ralsina did some benchmarking on IRC which found that the commonmark plugin we have is about 30 times faster than the built in markdown compiler... perhaps we could consider this for core.

**Comment by tritium21** [comment]
Ok, so I have this working, and I want advice on how to proceed.  I will show the entire plugin but in reality, it's just subclassing `rest`, and changing one method.  The only change to the method is subbing in an additional argument to one library call (nikola is structured REALLY well, i have to say)

The change is the call to rst2html.  All that was needed was to pass an instance of `CommonMarkParser` as the `parser` argument (and setting `parser_name` to `None` for safety - not sure if that was 100% required).  Everything else is copypasta.

```python
import os

from nikola.nikola import LEGAL_VALUES
from nikola.plugins.compile.rest import CompileRest, rst2html
from nikola.utils import unicode_str, LocaleBorg
from recommonmark.parser import CommonMarkParser


class CompileRCM(CompileRest):
    friendly_name = "MarkDocutils"
    name = "markdocutils"

    def compile_html_string(self, data, source_path=None, is_two_file=True):
        """Compile reST into HTML strings."""
        # If errors occur, this will be added to the line number reported by
        # docutils so the line number matches the actual line number (off by
        # 7 with default metadata, could be more or less depending on the post).
        add_ln = 0
        if not is_two_file:
            m_data, data = self.split_metadata(data)
            add_ln = len(m_data.splitlines()) + 1

        default_template_path = os.path.join(os.path.dirname(__file__), 'template.txt')
        settings_overrides = {
            'initial_header_level': 1,
            'record_dependencies': True,
            'stylesheet_path': None,
            'link_stylesheet': True,
            'syntax_highlight': 'short',
            'math_output': 'mathjax',
            'template': default_template_path,
            'language_code': LEGAL_VALUES['DOCUTILS_LOCALES'].get(LocaleBorg().current_lang, 'en')
        }

        output, error_level, deps = rst2html(
            data,
            parser=CommonMarkParser(),
            parser_name=None,
            settings_overrides=settings_overrides,
            logger=self.logger,
            source_path=source_path,
            l_add_ln=add_ln,
            transforms=self.site.rst_transforms,
            no_title_transform=self.site.config.get('NO_DOCUTILS_TITLE_TRANSFORM', False)
        )
        if not isinstance(output, unicode_str):
            # To prevent some weird bugs here or there.
            # Original issue: empty files.  `output` became a bytestring.
            output = output.decode('utf-8')
        return output, error_level, deps
```

**Comment by tritium21** [comment]
By "Works", by the way, the transformer that autoruns rst directives embeded in markdown does not yet work, but it does compile

**Comment by ralsina** [comment]
@tritium21 hey, one step at a time :-)

**Comment by tritium21** [comment]
Turns out this is an incomplete implementation that only does what RTFD needs in a tightly coupled way.
