### ISSUE TITLE
Make "Toggle navigation" button in bootstrap theme translatable

### ISSUE THREAD

**Issue by leonardder** [getnikola/nikola#2509]
In the Bootstrap3 theme in base.tmpl, there is a button with class sr-only labeled "toggle navigation". This is a button for screen reader users to make the navigation visible when hidden. However, this button is always in English, it would be great if we could make it nikola language specific.

**Comment by stefanos82** [comment]
Weird...I have bootstrap3 installed, but I don't have "toggle navigation" anywhere inside `base.tmpl`.

Anyhow, I have resized my browser to the dimensions of a smart device and by clicking on the navigation button would just drop down, but not toggle back the menu; it just stays down.

I have just checked it on both Firefox and Chromium.

**Comment by ralsina** [comment]
It is there: https://github.com/getnikola/nikola/blob/master/nikola/data/themes/bootstrap3/templates/base.tmpl#L20 I'll do it.
