### ISSUE TITLE
Suggestion for import_blogger

### ISSUE THREAD

**Issue by stefanos82** [getnikola/nikola#2511]
Blogger's URI format follows this certain scheme:

`awebsite.blogspot.com/<year>/<month></day>/<post-name>.html` for posts and
`awebsite.blogspot.com/p/<page-name>.html`.

When we import data from blogger, it places pages inside `nikola-project/stories/p/`.

It would be nice to import pages inside a `pages` directory and not `stories` as `stories/p/<page-name>.html`; something like

`nikola-demo.com/pages/<page-name>.html`.

Why are we even having a `stories` directory anyway? I never really understood this naming.

Can any of you @ralsina or @Kwpolska enlighten me please?

Cheers.

**Comment by Kwpolska** [comment]
`import_blogger` probably leaves the original setting for `PAGES`, which we would need to modify. And `stories` comes from some ancient blog generator @ralsina used before Nikola.

(It might also be nice to make importers follow the original URL scheme for posts.)

**Comment by stefanos82** [comment]
That's nice to know. When I first found `stories` inside `conf.py` I said to myself "shouldn't stories be considered a user's posts?"; because frankly, each post should be considered a short or a long story depending on a blogger's writing skills.

**Comment by ralsina** [comment]
Splitting the difference:

It will now put them in pages/p/<whatever>.html
