### ISSUE TITLE
question: jinja shortcode tmpl? (seems to only work using mako)

### ISSUE THREAD

**Issue by Fuzzwah** [getnikola/nikola#2528]
The shortcodes template exmaple shows using jinja2 in the template file:

https://getnikola.com/extending.html#template-based-shortcodes

I have created a file ````shortcodes/image.tmpl```` and am trying to use the shortcode in an .rts file:

````{{% image src=https://farm1.staticflickr.com/138/352972944_4f9d568680.jpg %}}````

However I can't get jinja2 templates to work. Example:

````<img class="img-responsive img-thumbnail img-rounded" style="margin-bottom: 10px" src="{{src}}">````

However it works fine if I use mako style templating:

````<img class="img-responsive img-thumbnail img-rounded" style="margin-bottom: 10px" src="${src}">````

Is there something that I'm missing?

**Comment by Fuzzwah** [comment]
I now notice that the handbook only talks about mako. Bums me out that jinja2 used to be supported too (as I have experience with jinja2 but mako is new to me... seems similar enough that it won't be hard to get my head around, but I'm using jinja2 for other templating on the same site already).

**Comment by Kwpolska** [comment]
On Tue, Oct 11, 2016 at 08:36:05PM -0700, Fuzzwah wrote:
> I now notice that the handbook only talks about mako. Bums me out that jinja2 used to be supported too (as I have experience with jinja2 but mako is new to me... seems similar enough that it won't be hard to get my head around, but I'm using jinja2 for other templating on the same site already).
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/getnikola/nikola/issues/2528#issuecomment-253110533

Jinja2 templates are still supported. Theming documentation still mentions
them, and we still ship and support base-jinja and bootstrap3-jinja.
Template-based shortcodescuse the same template system your current theme uses.
So if you want Jinja2, make sure you're using a Jinja2-based theme.

-- 
Chris Warrick <https://chriswarrick.com/>
PGP: 5EAAEA16

**Comment by ralsina** [comment]
@Fuzzwah like @Kwpolska said, to use jinja shortcuts, use a jinja theme, and it will work. The docs say more about Mako because it's the one I use, and I wrote most of those docs :-)

Jinja is just as much a 1st-class citizen as Mako, we have no mako-specific features anywhere.
