### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by yitzhakbg** [getnikola/nikola#2529]
Can support for RTL languages be added to Nikola? A least to add dir=rtl to the html element
[Right to Left text in Markup languages](http://www.i18nguy.com/markup/right-to-left.html)

**Comment by Kwpolska** [comment]
We’re supposed to [be doing that](https://github.com/getnikola/nikola/blob/master/nikola/data/themes/bootstrap3/templates/base_helper.tmpl#L22) with the built-in themes. Is there anything else that can be done? Does this not work?

(List of RTL languages: Arabic, Persian, Hebrew, Urdu)

**Comment by ralsina** [comment]
Sure. There are in fact some RTL sites done using Nikola, I am guessing
they added it to the template themselves.

Maybe if we know which languages are RTL we can make it automatic, at least
for the included themes.

**Comment by yitzhakbg** [comment]
Thank you immensely for the willingness and cooperation.

**Comment by Kwpolska** [comment]
On a side note, it looks like the Hebrew translation has a bug (that I just fixed). If you want to use it, you might need to manually update your `messages_he.py` file from commit 660f7fa.

(RTL is hard.)

**Comment by yitzhakbg** [comment]
Yes, it wasn’t clear to me in which direction the non-Hebrew strings would
ultimately appear within the Hebrew strings. Thanks for the corrections

-- 
Yitzhak Bar Geva <https://www.linkedin.com/in/yitzhakbg>

On 14 October 2016 at 10:03:01, Chris Warrick (notifications@github.com)
wrote:

On a side note, it looks like the Hebrew translation has a bug (that I just
fixed). If you want to use it, you might need to manually update your
messages_he.py file from commit 660f7fa
<https://github.com/getnikola/nikola/commit/660f7fad9973c04a7197e7b5dd27ed8b29a29c1d>
.

(RTL is hard.)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/getnikola/nikola/issues/2529#issuecomment-253724816>,
or mute the thread
