### ISSUE TITLE
Pass post object to compile_html

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2531]
Instead of using a hack with paths to save dependencies (and potentially do other things), we could just pass a `post` argument to `compile_html`.

**Comment by felixfontein** [comment]
That's a great idea! (I've already longed for that while hacking on some test plugins, and always came up with some ugly but working workarounds...)

And while we're at it: let's also pass `lang`!

BTW, there's a way to make this not breaking backwards compatibility: add a new function which accepts a `Post` object to the `PageCompiler` definition which by default calls the old `compile_html` function (which should be marked as deprecated). Compile plugins can then gradually be migrated to right away implement the new method.

**Comment by felixfontein** [comment]
And the old `compile_html` can then be removed in v8. :)

**Comment by Kwpolska** [comment]
You’re right. I’ll have a PR out in a minute.
