### ISSUE TITLE
Let compiler specify additional targets

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#2536]
What do you think about a change to the `posts` plugin to allow the post's compiler to specify more targets than the HTML fragment?

With this, post compilers can make sure that cache files which contain dependencies (read by `register_extra_dependencies`) is re-created even when the resulting HTML fragment is there, making the whole mechanism to write dependencies to files less hackish.

**Comment by ralsina** [comment]
But why would extra targets change how dependencies work? Can you give me
an example?

**Comment by felixfontein** [comment]
Assuming there's only a simple list of dependent files (such as created by ReST plugin etc.): assume someone partially deleted their `cache` folder, so that for one post the `.html` fragment is there but the `.dep` file is gone. Then if the dependency is changed and `nikola build` is run, Nikola assumes the post has no dependencies and doesn't recompile it.

Or assume the compiler generates some other files out of the post and somewhere wants to keep track which files it actually generates, so a closely related plugin can make sure that the files are really there. For that, it must be possible to enforce that the compiler is re-run when that file or the generated files mentioned in there suddenly go missing. (For example, because someone deleted `output` but not `cache`.)

**Comment by felixfontein** [comment]
I forgot: if the generated file which keeps track of the dependencies is a target, doit will recompile the post when that file goes missing. So it cannot happen that some change gets lost because the dependency file got deleted (or some other generated files, or whatever else).

**Comment by ralsina** [comment]
OK, I agree that .deps should be a target of the compiler plugin, and that
if a compiler produces more than one file it should mark them all as
targets.

The last part about output/ doesn't sound as good. We need to trust doit.
If we produce a file, and it's deleted, it will be rebuilt. If we need to
manually account for special cases we are doing it wrong.

**Comment by felixfontein** [comment]
This was fixed in #2547.
