### ISSUE TITLE
build fails on bad image file: OSError: cannot identify image file

### ISSUE THREAD

**Issue by Fuzzwah** [getnikola/nikola#2537]
I'm wondering if a try / except could be rigged up in the image_processing.py functions to better handle issues with image files?

I have an automated system which downloads images and builds pages with them embedded. I'd much prefer logging the error and continuing with the build process (with the image not included in the post), than noticing that my builds are crashing and having to fix the image file.

**Comment by ralsina** [comment]
If you want to continue after errors, use "nikola build -c"
If nikola is actually crashing on broken images, please post a backtrace so I can check it out.

**Comment by adarshdec23** [comment]
The error occurs while opening a damaged image file. 


Scanning posts......done!
.  scale_images:output/images/9b6718aba02878c24161e27c63c95eef.jpg
########################################
TaskError - taskid:scale_images:output/images/9b6718aba02878c24161e27c63c95eef.jpg
PythonAction Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/ubuntu/workspace/nikola/plugins/task/scale_images.py", line 74, in process_image
    self.resize_image(src, dst, self.kw['max_image_size'], False, preserve_exif_data=self.kw['preserve_exif_data'], exif_whitelist=self.kw['exif_whitelist'])
  File "/home/ubuntu/workspace/nikola/image_processing.py", line 100, in resize_image
    im = Image.open(src)
  File "/usr/local/lib/python3.4/dist-packages/PIL/Image.py", line 2319, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'images/9b6718aba02878c24161e27c63c95eef.jpg'

**Comment by Kwpolska** [comment]
This is a user error then.
