### ISSUE TITLE
Plugins use 'Compiler' instead of 'PageCompiler' in plugin category metadata

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2543]
We should fix that, but we can’t do it before v8 for backwards compatibility reasons.

**Comment by tritium21** [comment]
Could you change it so that `Compiler` is a synonym for `PageCompiler` in the interim, and update stock plugins to use the latter?

**Comment by Kwpolska** [comment]
That’s a really minor thing, so not worth the effort.

**Comment by ralsina** [comment]
Actually, seems to me like Compiler and PageCompiler are synonimous already?

**Comment by Kwpolska** [comment]
They are synonymous, it’s just that we’re using the “wrong” name now. (A really minor “issue”.)
