### ISSUE TITLE
Cant install the Nikola Snap package

### ISSUE THREAD

**Issue by gntech** [getnikola/nikola#2549]
I can find Nikola when I search for it using the snap command but I cant install it. I am running Ubuntu Mate 16.10.

```
» snap find nikola
Name    Version  Developer  Notes  Summary
nikola  7.8.1    ralsina    -      A modular, fast, simple, static website and blog generator

» snap install nikola
error: cannot install "nikola": snap not found
```

**Comment by ralsina** [comment]
Ok, that's weird. Are you on an arm platform by chance?
If you are on e aregular PC it should be available.

**Comment by gntech** [comment]
No I am on x86_64 but I have found the solution now. I had to add the option --edge to make it work:

```
» snap install --edge nikola
nikola (edge) master from 'ralsina' installed
```

**Comment by gntech** [comment]
Maybe it should be availabel on the "stable" channel to allow install using only `snap install nikola`

**Comment by Fotofreund** [comment]
The version numbers seem to be mixed-up.

I had the same problems and just installed it with "snap install --edge nikola".
When I enter > nikola version  
The output is : Nikola v7.7.12

**Comment by ralsina** [comment]
Edge is not being updated because automation is not there yet (working on it)
Stable channel has the latest release.

**Comment by Fotofreund** [comment]
Sorry, but it is still not working:


    Fotofreund@NVM:~$ sudo snap find nikola
    [sudo] Passwort für Fotofreund: 
    Name    Version  Developer  Notes  Summary
    nikola  7.8.1    ralsina    -      A modular, fast, simple, static website and blog generator
    
    Fotofreund@NVM:~$ sudo snap install nikola
    error: cannot install "nikola": snap not found
    
    Fotofreund@NVM:~$ sudo snap install --stable nikola
    error: cannot install "nikola": snap not found

I use standard Ubuntu 16.04 64 bit.

**Comment by ralsina** [comment]
@Fotofreund it does work for me, I'll ping someone at the snap store to see if they have any idea what's happened.

**Comment by ralsina** [comment]
Closing because I can't publish snaps right now.
