### ISSUE TITLE
bootstrap3: navbar-inverse used 

### ISSUE THREAD

**Issue by eudoxos** [getnikola/nikola#2552]
`themes//bootstrap3/templates/base.tmpl` (https://github.com/getnikola/nikola/blob/master/nikola/data/themes/bootstrap3/templates/base.tmpl#L16): `navbar navbar-inverse navbar-static-top` is used for the navigation bar; this should be documented and explained, or made configurable, or changed to `navbar-default`. Bootswatch themes previews (http://bootswatch.com/) are less usable, since navbar ends up with different color. I understand nothing can be infinitely flexible, but this seems like an arbitrary decision and perhaps `navbar-default` should be used by ...ehm... default :)

**Comment by Kwpolska** [comment]
You can always use `nikola theme -c base.tmpl` and change your navbar. We think black navbars are cooler. (and everything is arbitrary, including the “defaultness” of a grey navbar)

While we could make this configurable, how many people would actually use this feature? Why make yet another setting buried deep in `conf.py`?

**Comment by eudoxos** [comment]
Inverse navbars are not black in the dark themes. Yes, that's what I did, copying the base.tmpl, but it felt like an overkill. True that adding that to config would be an overkill. Sorry for noise. Cheers!

**Comment by Kwpolska** [comment]
(I hope you didn’t take this personally.)

**Comment by eudoxos** [comment]
Thanks for care. But no, I did not :)
