### ISSUE TITLE
Wordpress Importer: Tags: &amp; should be just &

### ISSUE THREAD

**Issue by okin** [getnikola/nikola#2557]
I noticed that imports made through the wordpress importer plugin does not correctly handle ampersands (*&*) in tags and writes them into the new site as &amp;.

This probably applies to other HTML entities aswell.

**Comment by felixfontein** [comment]
So in the post file, in the `.. tags:` line, there is an `&amp;`?

**Comment by okin** [comment]
Yes, exactly that.

Am 6. November 2016 21:45:27 MEZ, schrieb Felix Fontein <notifications@github.com>:

**Comment by felixfontein** [comment]
Can you create a small `.xml` where this happens? If yes, please also test some other special chars (umlauts, typographical quotation marks, ...) so I can see how WordPress treats these.

**Comment by okin** [comment]
I currently do not have a running WordPress. Maybe I can dig up some old export for that. 

Am 12. November 2016 11:23:01 MEZ, schrieb Felix Fontein <notifications@github.com>:

**Comment by okin** [comment]
Part of an older export that had the same problem:
`<wp:tag><wp:term_id>163</wp:term_id><wp:tag_slug>1-und-1</wp:tag_slug><wp:tag_name><![CDATA[1&amp;1]]></wp:tag_name></wp:tag>`

The blog where this came from had a tag `1&1`.
This shifts the question to wether Nikola should transform the data here or make a more or less dumb import.
I think transformation should be the way to go to get a nicer user experience.
