### ISSUE TITLE
Share section (bottom left of post) is not removed, gets added

### ISSUE THREAD

**Issue by antrodcam** [getnikola/nikola#2558]
Since I intend to use nikola for a very low key, rarely updated website, made a few changes to conf.py, detailed below:
1. deleted SOCIAL_BUTTONS section: from line starting with SOCIAL_BUTTONS_CODE, a few more, all the way to """
2. Removed # sign of line GENERATE_RSS, set it to false.
3. Removed rss containing lines from NAVIGATION_LINKS

However, after compiling with nikola build, and with nikola build -a, the section described on the title still appears in the ouput html. This is what shows up in the html source:
`
<div id="addthisbox" class="addthis_toolbox addthis_peekaboo_style addthis_default_style addthis_label_style addthis_32x32_style">
<a class="addthis_button_more">Share</a>
<ul>
<li>
<a class="addthis_button_facebook"></a>
</li>
<li>
<a class="addthis_button_google_plusone_share"></a>
</li>
<li>
<a class="addthis_button_linkedin"></a>
</li>
<li>
<a class="addthis_button_twitter"></a>
</li>
</ul>
</div>
<script src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4f7088a56bb93798"></script>
`
I have been removing it by hand.
Thanks.

**Comment by Kwpolska** [comment]
Pastebin your configuration file and post a link here. Also, are you using
the newest version? That should not appear by default.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by ralsina** [comment]
Six months, no response, closing.
