### ISSUE TITLE
Katex with math directive

### ISSUE THREAD

**Issue by zhy0** [getnikola/nikola#2561]
I've noticed that the `.. math` directive produces an `\begin{equations*}` environment which doesn't work with Katex. Is there a way to make the math directive work with Katex, like making it not produce the `\begin{equations*}` environment when `USE_KATEX` is set to `True`? Or is this something inherent in reST that's not easily altered?

**Comment by Kwpolska** [comment]
You might try to change `KATEX_AUTO_RENDER` to contain `\begin{equation*}` and `\end{equation} as the delimiters. Otherwise, it would require messing with reST internals.

**Comment by zhy0** [comment]
Thanks, that works like a charm!

~~~
KATEX_AUTO_RENDER = """
delimiters: [
    {left: "\\\\begin{equation*}", right: "\\\\end{equation*}", display: true},
    {left: "$$", right: "$$", display: true},
    {left: "\\\[", right: "\\\]", display: true},
    {left: "$", right: "$", display: false},
    {left: "\\\(", right: "\\\)", display: false}
]
~~~
