### ISSUE TITLE
Feature request github_deploy with a prefix

### ISSUE THREAD

**Issue by rainwoodman** [getnikola/nikola#2562]
Please consider allowing a prefix argument to github_deploy.

Rational:

We'd like to be able to preview pull requests for our small, multi-contributor website, in addition to the Travis rebuild guide in https://getnikola.com/blog/automating-nikola-rebuilds-with-travis-ci.html. 
We can do this if we can deploy pull request to subdirectory different directory for previewing. e.g.

- .pullrequests/$TRAVIS_PULL_REQUEST for PR, and

- .branches/$TRAVIS_BRANCH for branches

- / for the latest tagged release.

Possible Implementation:

The way we can do this is to first checkout the gh-page branch to a temp directory, copy the output as a subdirectory, then run ghp-import on the temp directory.

Of course if two PR are opened at the same time we will have some race condition, but I suspect in practice  it is unlikely to happen and easy to work around for for small sites.

Thanks.

**Comment by Kwpolska** [comment]
I don’t understand what you mean here. So, please rephrase, and probably show a real world example of what you have and what `nikola github_deploy` would do. But remember that if you have some special needs that `nikola github_deploy` does not fulfil, you can always use `ghp-import` or even `git` commands directly.

**Comment by rainwoodman** [comment]
Here is a real world example:

https://travis-ci.org/bccp/website/builds/176177771#L575

The master branch is deployed at:

https://bccp.github.io/website-preview/br/master/

instead of the root location. The prefix in this scenario is br/master.
PR is supposed to be deployed to pr/$prid, but I haven't tested if it works as expected.

I indeed am by-passing nikola's github_deploy  with the code here:

https://github.com/bccp/website/blob/master/travis-action.sh

 but it would be nice if nikola github_deploy handles this instead.

**Comment by Kwpolska** [comment]
The goal of `nikola github_deploy` is to handle the case most people want, which is a straightforward deploy from one branch to another. Your idea seems to involve either extra clones or magic git incantations. I’m going to mark this as *wontfix*, sorry. (Unless there are lots of people who want this pretty narrow use-case)
