### ISSUE TITLE
scale_images has unusal ignoring setup

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2566]
```py
         ignore = set(['.svn'])
```

WTF, svn? This is 2016. Also, why is this a set?

```py
                 if src_name in ('.DS_Store', 'Thumbs.db'):
```

Should probably be merged with dictionary ignores. (Not sure if we need to make this customizable?)

**Comment by blubberdiblub** [comment]
Just a thought: relying on the letter case of `Thumbs.db` might not be such a good idea, either, as Windows is case insensitive by default and I'm almost sure I've already seen instances of that file named `thumbs.db`.

**Comment by ralsina** [comment]
Anyway it does nothing, since noone wil ever have .db as an "image
extension" ... right?

**Comment by ralsina** [comment]
And for .DS_Store ... isn't that usually a directory?

**Comment by Kwpolska** [comment]
No, it’s a file.

**Comment by ralsina** [comment]
Ok then, but, once more, not something that is going to be considered an image, so it's skipped anyway.

**Comment by Kwpolska** [comment]
So, nuke both ignores? Does svn really put its folders in every directory of a repo?

**Comment by blubberdiblub** [comment]
I believe there where different versions of svn where either the older or the newer one put `.svn` into every subdirectory and the other one just into the repository root, but don't quote me on that.

**Comment by ralsina** [comment]
if SVN does put the .svn everywhere, *and* it creates things called ".jpg" or whatever inside the .svn then maybe we have to hold our noses and keep it. The other one, I say kill it.

**Comment by felixfontein** [comment]
Older versions of Subversion did that, newer ones don't. The behavior changed in version 1.7 (http://subversion.apache.org/docs/release-notes/1.7.html#wc-ng).

**Comment by felixfontein** [comment]
I'm not sure anymore (and can't find anything quickly), but it could have been that in Subversion 1.6.x and earlier, the `.svn` folder contains files with the same name as in the folder containing `.svn`, i.e. that could include `.jpeg` files. (It could also have been that some extension was added. I'm not sure anymore.)
