### ISSUE TITLE
smartypants' oldschool

### ISSUE THREAD

**Issue by gour** [getnikola/nikola#2574]
Hello,

While using Emacs, I did use its typoel package to automatically enter correct typographical marks for minus, endash, emdash, ellipsis as well as for quotes...

Now after leaving Emacs, I'm (again) faced with the dilemma how to conveniently get them while using Nikola. One possibility would be to convert input (rst) with Pandoc by using `--smart`option.

However, better option would be to simply enter quotes (" "), minus ('-'), endash ('--'), emdash ('---'), ellipsis ('...') and let the typogrify/smartypants do their job.

However, problem is that current invocation of smartypants:

`data = typo.smartypants(data) `

does not produce emdash & endash.

Here is the snippet:

```
$ (nikola) python
Python 3.5.2 (default, Sep 14 2016, 11:28:32) 
[GCC 6.2.1 20160901 (Red Hat 6.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import smartypants
>>> text = 'SmartyPants testing - (minus), endash -- and emdash --- as well as ellipsis...'
>>> print(smartypants.smartypants(text))
SmartyPants testing - (minus), endash &#8212; and emdash &#8212;- as well as ellipsis&#8230;
>>> 
```

where we can see that smartypants doesn't distinguish between emdash and endashes with default settings.

In order to get proper (aka _oldschool_) behaviour it is required:

```
$ (nikola) python
Python 3.5.2 (default, Sep 14 2016, 11:28:32) 
[GCC 6.2.1 20160901 (Red Hat 6.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import smartypants
>>> text = 'SmartyPants testing - (minus), endash -- and emdash --- as well as ellipsis...'
>>> print(smartypants.convert_dashes_oldschool(text))
SmartyPants testing - (minus), endash &#8211; and emdash &#8212; as well as ellipsis...
>>> 
```

Don't know why it's called _oldschool_, but I know that's how it's used in LaTeX and Pandoc's `--smart` option is [described](http://pandoc.org/MANUAL.html) as follows:

> If the --smart option is specified, pandoc will produce typographically correct output, converting straight quotes to curly quotes, --- to em-dashes, -- to en-dashes, and ... to ellipses. Nonbreaking spaces are inserted after certain abbreviations, such as “Mr.”

So, my suggestion is to setup smartypants (in Nikola) to either use _oldschool_ behaviour or to provide user-definable setting(s) to control it?

Nikola has a lot to do with the content, so it would be nice to have proper support for quality typography...

**Comment by felixfontein** [comment]
What you can always do is copying the definition of the `typogrify` filter into your blog's config (with the necessary imports) and adjust it to your needs. I did that with the `closure_compiler` filter because the executable is named differently on my machines.

It would be nice to be able to configure at least some of the filters, though. I guess the biggest question is how that should be implemented. The filters cannot access the site's configuration, so having factory functions for filters with options would be a viable solution. @Kwpolska, @ralsina: what do you think about this in general?

**Comment by gour** [comment]
@felixfontein I know one can somehow tweak thing to make it work, but, imho, the current behaviour is simply not correct. Take e.g. look [here](https://tex.stackexchange.com/questions/3819/dashes-vs-vs#3821)!

**Comment by ralsina** [comment]
Adding a second filter is trivial, let me take a shot at it.

**Comment by ralsina** [comment]
There you go, totally untested PR here: https://github.com/getnikola/nikola/pull/2575

If you say it's ok, I'll merge.

**Comment by gour** [comment]
> If you say it's ok, I'll merge.

I've tried it here and it works. ;)
![oldschool](https://cloud.githubusercontent.com/assets/114592/20835044/b353f858-b898-11e6-9a5e-a9bfed06c53f.png)

Thank you very much for support!

**Comment by ralsina** [comment]
@gour you're welcome.

Now, after this has been done, I can point out that what I did is exactly the same hack that was proposed, except I DID IT IN THE RIGHT PLACE.

Feel free to propose hacks, y'all, github doesn't bite :-)

**Comment by Kwpolska** [comment]
May I propose a real solution for @gour? Just make a keyboard layout that includes all the fancy characters you want to use. Like I did, with typographically correct typing (eg. „ “—” ‘–’ «—»), and support for quite a few European languages.

Since #2575 is merged, I’ll close this.
