### ISSUE TITLE
Taxonomies can’t be disabled

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2581]
Previously, I could do this:

```py
DISABLED_PLUGINS = ['render_indexes']
```

That won’t work anymore, because now everything is handled by `render_taxonomies`. There should be a way to disable taxonomies at will. Via #2535.

**Comment by felixfontein** [comment]
Use
```
DISABLED_PLUGINS = ['classify_indexes', 'classify_sections', 'classify_page_index']
```
to disable the three plugins which do what `render_indexes` used to do.

**Comment by felixfontein** [comment]
(If you disable a taxonomy plugin, `render_taxonomies` won't generate anything for it anymore.)

**Comment by felixfontein** [comment]
Continuing the discussion from #2535: I'll start working on that later. First I'll prepare dinner and eat something ;)

**Comment by felixfontein** [comment]
PR #2583 should do what I promised in #2535.
