### ISSUE TITLE
Allow plugins to insert data into page's context

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#2587]
What about allowing plugins to insert data into a page's context (the ones rendered by the `render_pages` plugin)? Such plugins could connect to the `scanned` signal and then go through all posts and use a (to be defined) interface of the `Post` object to add data (per language or language-independent) which will then be used by `Nikola.generic_page_renderer` to populate the post's context (and its dependence dict).

(Alternatively, one could monkey-patch the post object to add additional data, but that sounds much more hackish to me.)

What do you think?

**Comment by Kwpolska** [comment]
That’s not monkey-patching, this is just how Python works. You could just make an “official” dict for those plugin additions in the Post object, without any generic_page_renderer tricks.

**Comment by felixfontein** [comment]
Ok, if that's fine, I can live with that.
