### ISSUE TITLE
deploy: warns about using Nikolas Disqus but COMMENT_SYSTEM is disabled

### ISSUE THREAD

**Issue by okin** [getnikola/nikola#2588]
I get a warning about using the nikolademo Disqus account whenever I deploy with `nikola deploy` even though I have set `COMMENT_SYSTEM = None` and commented the line starting with `COMMENT_SYSTEM_ID` in my `conf.py`.

The warning shown is:

    [2016-12-09T13:05:21Z] WARNING: deploy: 
    WARNING WARNING WARNING WARNING
    You are deploying using the nikolademo Disqus account.
    That means you will not be able to moderate the comments in your own site.
    And is probably not what you want to do.

I would expect this message to not appear.

Tested with Nikola 7.8.1.

**Comment by Kwpolska** [comment]
Fixed. This message won’t appear anymore if COMMENT_SYSTEM is falsey (empty string, False, None).
