### ISSUE TITLE
Theme Install: SSL Handshake Error

### ISSUE THREAD

**Issue by clightfield** [getnikola/nikola#2595]
New install by running the following commands in this order:
`pip install "Nikola[extras]"`
`nikola init --demo ./NikolaTestSite`
`cd NikolaTestSite`
`nikola bootswatch_theme -n custom_theme -s flatly -p bootstrap3`

There are lots of errors, but all of them are SSL related.

```bash
.....
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:646)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 624, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:646)

During handling of the above exception, another exception occurred:
.....
```

**Comment by Kwpolska** [comment]
I can’t reproduce with macOS Sierra and Python 3 from Homebrew (I have openssl installed too, not sure if that matters). How did you install Python, did you do anything SSL-related on your system?

Also, `nikola bootstwatch_theme` depends on a third-party service we are not responsible for.

**Comment by clightfield** [comment]
Thank you for looking into this. I haven't altered my SSL configuration, but I'm using version 0.9.8zh. Perhaps that's out of date. The SSL errors seem to be pervasive. Running `nikola plugin -l` I get

```bash
WARNING: plugin: SSL error, using http instead of https (press ^C to abort)
```

I didn't use Homebrew for my python install, so that may be the issue. I installed python by downloading the installer from here: https://www.python.org/downloads/.

Since it's not reproducible and bootswatch is a separate service, this doesn't seem to be a Nikola issue. Thanks for the help. Feel free to close this issue.

**Comment by Kwpolska** [comment]
This is not a Nikola issue, but not because of Bootswatch, but rather because your system SSL configuration is broken.
