### ISSUE TITLE
Nikola breaks if code.css is generated by LESS/SASS (or somehow else)

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#2597]
When I try to generate `code.css` with SASS (same will happen with LESS or if I use any self-written plugin to generate it):
```
ERROR: Two different tasks can't have a common target.'output/assets/css/code.css' is a target for build_sass:output/assets/css/code.css and copy_assets:output/assets/css/code.css.
```
I know that this isn't very easy to resolve, but: what about adding a option to just disable automatic generation of `code.css`? That would at least allow users to work around this problem (without modifying nikola sources).

**Comment by Kwpolska** [comment]
What would SASS/LESS do in this case? We assume code.css to contain things usable by our pygments listings.

**Comment by felixfontein** [comment]
Thanks for implementing that!

Which case do you mean in "what would SASS/LESS do in this case"?

Of course, it is my own responsibility to ensure that `code.css` satisfies all requirements for pygments. I had my own copy in `assets/css` of my theme anyway, and now I decided to convert all CSS files to SASS.

**Comment by Kwpolska** [comment]
How is your `code.css` — no matter how it gets created — going to be better than whatever Pygments itself would produce for you?

**Comment by felixfontein** [comment]
I wanted one which uses no colors: neither background colors nor other colors. I don't know of any built-in style which does that (`bw` uses background-color for everything and color for errors).
