### ISSUE TITLE
Make Post objects sortable/comparable

### ISSUE THREAD

**Issue by liffiton** [getnikola/nikola#2602]
I'd like to be able to [re]order the posts in a template (e.g., ``tag.tmpl``, and specifically in Jinja in my case) by their titles.

I'm imagining I'd write something like ``for post in posts|sort``.  That does work after adding an ``__lt__`` operator to the Post class:

```python
def __lt__(self, other):
   return self.title() < other.title()
```

I realize that sorting by title is not the only way to sort posts, though, so making the sort filter order in this way may not be the best implementation.  An alternative would be to leverage the "attribute" parameter of Jinja's [sort filter](http://jinja.pocoo.org/docs/dev/templates/#sort), which lets one tell it what to sort by; this would require exposing the Post object's title as an attribute:

```python
@property
def title_str(self):
    return self.title()
```

Then this would work: ``for post in posts|sort(attribute="title_str")``

**Comment by Kwpolska** [comment]
I can think of a better solution: a smarter `sort_posts` filter/function, available for templates and general use, that would handle all those edge cases. I’ll work on it later.
