### ISSUE TITLE
Adding more signal handlers?

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#2603]
How about adding some more signals to various places and core plugins?

For example:
 * Adding `render_post` signal (which receives `context`) to `Nikola.generic_page_renderer`?
 * Adding `taxonomies_classified` signal to the end of the taxonomy classification process in `TaxonomiesClassifier._do_classification`?
 * Adding `generate_classification_overview` signal (which receives `taxonomy`, `context`, `kw`, `lang`) to `RenderTaxonomies._generate_classification_overview` (and `RenderTaxonomies._generate_tag_and_category_overview`)?
 * Adding `generate_classification_page` signal (which receives `taxonomy`, `classification`, `context`, `kw`, `lang` and `filtered_posts`) to `RenderTaxonomies._generate_classification_page`?

For example, hooking up to the signals in the second and fourth point would allow implementation of #2599 without touching Nikola core.

**Comment by Kwpolska** [comment]
Signal handlers don’t cost anything, feel free to add some.
