### ISSUE TITLE
Improving language support

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2606]
Current situation:

* messages files do not have any support for plural numbers, meaning some things may look awkward (numbers don’t appear often in messages) — but note eg. Microsoft famously sucks at it
* dates may be formatted incorrectly (eg. in Polish: 25 grudnia vs 25 grudzień; the first form is grammatically correct) — this is something computers, including Windows, are expected to get right

We can do better than that, if we use the [Babel](http://babel.pocoo.org/en/latest/) library, which will:

* provide real localisation support (`.po`/`.mo` files, `messages_*.py` will have to go) with support for [plural forms](https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/Plural-forms.html)
* have date formats from CLDR, along with good date declension etc.

cc @felixfontein, @ralsina

**Comment by felixfontein** [comment]
(An earlier discussion about dates including code samples can be found in #2601.)

**Comment by sukiletxe** [comment]
In <https://gitlab.com/sukiletxe/sukiletxe.gitlab.io> I have created a plugin which uses Babel for date formatting, to overcome the fact that Alpine Linux doesn't use "real" locales (they are correctly detected and such, but then the dates are in English). You can adapt that code, if you wish.  Note: It **only** formats dates.

**Comment by Kwpolska** [comment]
That’s a bug in Alpine Linux, please complain to them.

**Comment by sukiletxe** [comment]
Done. To  be clear, I never said it was your bug.

**Comment by ralsina** [comment]
IIRC the main problem was that using the traditional gettext toolchain in anything other than Linux was a pain. If someone wants to change to whatever, I don't mind.
