### ISSUE TITLE
Per page pretty url config is not working

### ISSUE THREAD

**Issue by ChillarAnand** [getnikola/nikola#2613]
I have disabled pretty urls in `conf.py`

```py
PRETTY_URLS = False
```

For some posts, I don't want this, so I have set 

```
.. pretty_url: True
```

But Nikola is ignoring this.

**Comment by felixfontein** [comment]
I think it only works the other way around: if you set `PRETTY_URLS` to `True`, you can disable it for a specific post by specifying `.. pretty_url: False`. At least that's what the code does. From what I understand, that's also what the manual is saying.

**Comment by Kwpolska** [comment]
This seems to be intentional, and our docs state that you can *disable* PRETTY_URLS on a per-page basic. However, adding support should not be hard — but is that necessary? If you need URLs like those only for a few pages, you can create those pretty easily with `posts/foo/index.rst` with the slug `index`.

**Comment by ChillarAnand** [comment]
@Kw Thanks for quick fix. 

> If you need URLs like those only for a few pages, you can create those pretty easily with posts/foo/index.rst with the slug index.

This is excellent idea. I just created `posts/foo/index.md` with slug `index` and Nikola is throwing this error.

```
Scanning posts.......done!
ERROR: Two different tasks can't have a common target.'output/foo/index.html' is a target for render_pages:output/foo/index.html and render_indexes:output/foo/index.html.
```

I have searched for all directories, but there is no other `foo` folder.

```
→tree | grep foo
│   ├── foo

→
```

This problem [happened before also](https://github.com/getnikola/nikola/issues/2398#issuecomment-236372958). I am not sure how this is getting triggered.

**Comment by Kwpolska** [comment]
This one is caused by either PAGE_INDEXES or sections, perhaps some extra code is needed.
