### ISSUE TITLE
Add support for alternatley named Tidy packages

### ISSUE THREAD

**Issue by disconsented** [getnikola/nikola#2615]
Some distros (Arch for example) will package Tidy5 as Tidy, which will cause Nikola to fail when it attempts to make use of filters. In the meantime filters.py can be edited to resolve the issue until there is an offical fix (rename tidy5 to tidy for each of the filters you use).

**Comment by felixfontein** [comment]
I had that problem before (both with `tidy` and `closure_compiler`, which was called differently for some time in Arch until it was renamed recently). I ended up copying the filters into my `conf.py` and adjusting them there.

**Comment by felixfontein** [comment]
What you can do is:
```
from nikola import filters
from functools import partial
```
and then use `partial(filters.html_tidy_withconfig, executable='tidy')` instead of `filters.html_tidy_withconfig` directly. Kind of ugly, but works :)

**Comment by felixfontein** [comment]
@Kwpolska: do you have a better suggestion? Especially to make it easier to use for non-programmers?

**Comment by Kwpolska** [comment]
Perhaps a simple config option, that we could apply with `functools.partial` in `nikola.py`?

**Comment by felixfontein** [comment]
How should that work? I.e. how can Nikola distinguish which filter is which one, i.e. to which one apply `functools.partial` with which option?

**Comment by Kwpolska** [comment]
We could give some special attribute to all tidy-related functions, iterate over filters, and if we find a callable with that attribute, wrap it with `partial`.

**Comment by felixfontein** [comment]
How about something slightly more general (i.e. it not just works for `tidy`):
```
class configurable_filter(object):
    def __init__(self, **configuration_variables):
        self.configuration_variables = configuration_variables

    def __call__(self, f):
        f.configuration_variables = self.configuration_variables
        return f
```

Then one could do something like
```
@configurable_filter(executable='TIDY_EXECUTABLE')
def some_tidy_filter(filename, executable='tidy'):
    ...
```
and process filters as follows:
```
for i, f in enumerate(filters):
    if hasattr(f, 'configuration_variables'):
        args = {}
        for arg, config in f.configuration_variables.items():
            if config in site.config:
                args[arg] = site.config[config]
        if args:
            filters[i] = functools.partial(f, **args)
```
and if `TIDY_EXECUTABLE` is defined in the config, the argument `executable` of `some_tidy_filter` is replaced with it's value.

**Comment by Kwpolska** [comment]
Make that a PR.
