### ISSUE TITLE
Suggestion for adding a generator meta tag

### ISSUE THREAD

**Issue by stefanos82** [getnikola/nikola#2619]
I have been using [wappalyzer](https://www.wappalyzer.com/) for a number of years now and what I personally find impressive about it is that it gives me the opportunity to discover new programs or projects every time I browse a website; thus making me a new user to that particular set of tools, like many other users of it.

I have noticed that projects like Hugo, Blogger, Jekyll, and so forth are detected by wappalyzer, whereas Nikola websites are not.

After a couple of seconds of investigation I have noticed that Nikola does not use a `<meta name="generator" content="Nikola 7.8.1">` meta tag.

In my humble, yet honest opinion, if we added this specific meta tag in Nikola, it would broaden its user base even further.

What do you guys think?

**Comment by Kwpolska** [comment]
I’m :+1:, but without the version number (requires rebuilding every single page).

**Comment by felixfontein** [comment]
We should maybe also add this to the themes in the [themes repository](https://github.com/getnikola/nikola-themes).
