### ISSUE TITLE
Nikola installed from snap cannot work with existing Nikola project

### ISSUE THREAD

**Issue by Fotofreund** [getnikola/nikola#2621]
My old notebook has a dual-boot configuration with rolling release Antergos and LTS Ubuntu 16.04.
On Antergos I installed Nikola 7.8.1 from the AUR and created a new project. Unfortunately the current Linux kernel has some problems with the old graphics controller.

Therefore, I used the standard Ubuntu software tool to install the current Nikola snap and created a symlink to the folder with the existing Nikola project. 

When I try to work with the existing project, I get a strange error message.  

````

fotofreund@Latitude-D:~/fotofreunde$ snap list
Name    Version  Rev  Developer  Notes
core    16.04.1  641  canonical  -
nikola  7.8.1    18   ralsina    -

fotofreund@Latitude-D:~/fotofreunde$ nikola version
Nikola v7.8.1

fotofreund@Latitude-D:~/fotofreunde$ nikola build
[2017-01-08T10:26:40Z] ERROR: Nikola: This command needs to run inside an existing Nikola site.
````

What does it mean?

**Comment by Kwpolska** [comment]
Snapcraft is kinda special and experimental. Did you [follow the instructions](https://getnikola.com/blog/nikola-available-as-a-snap.html) and allow home directory access?

In any case, you may prefer [virtualenv-based install](https://getnikola.com/getting-started.html).

**Comment by Fotofreund** [comment]
I did not use the command line tool `snap install nikola` because I had some problems with a different notebook as I had mentioned before: [https://github.com/getnikola/nikola/issues/2549](url).
I used the standard graphical software installation tool that is a part of the standard Ubuntu 16.04 LTS.
Then I created a new project with `nikola init --demo` which worked fine.
Then I created the symlink to the other project folder and `nikola build` produced the error.
Afterwards, I entered 
```
snap connect nikola:home core:home
snap connect nikola:network core:network
snap connect nikola:network-bind core:network-bind

```
But nothing changed.

**Comment by ralsina** [comment]
@Fotofreund if it's a confinement problem, you should have relevant apparmor errors in your syslog, can you check?

**Comment by Fotofreund** [comment]
Sorry, but I switched to the virtualenv-based install and removed the snap some weeks ago.

**Comment by ralsina** [comment]
Closing all snap-related issues, because I can't publish snaps right now because of bureaucracy.

**Comment by Kwpolska** [comment]
Reasons why you should never trust centralized systems, episode 1337.

**Comment by ralsina** [comment]
Oh, I can build them and I could give them to people to sideload but it's a bit of a hassle.
