### ISSUE TITLE
Provide compile_string API in every compiler

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2624]

**Comment by felixfontein** [comment]
Missing are:
- [ ] ipynb
- [ ] pandoc
- [ ] php
- [ ] html

**Comment by felixfontein** [comment]
How about also providing `lang` as an argument for the `compile_string` API, now that we added that to `compile` as well?

**Comment by Kwpolska** [comment]
Would anything inside `compile_string` need that?

**Comment by Kwpolska** [comment]
See #2623 for PR.

**Comment by felixfontein** [comment]
Not necessarily (at least not now), but then, why not pass it everything that `compile` also gets? Some compiler could do language-dependent stuff.

**Comment by Kwpolska** [comment]
I did it with `lang`. Please review #2623 again, with extra care needed for `ipynb`.
