### ISSUE TITLE
option to restrict next/previous post to posts of the same section

### ISSUE THREAD

**Issue by wirew0rm** [getnikola/nikola#2625]
I'm using the sections feature, which is really great, but for my usecase it is rather irritating that the next/previous links lead to articles from different sections as I'm not using the global posts index at all.

The current definition of the previous and next posts is defined [here](https://github.com/getnikola/nikola/blob/master/nikola/nikola.py#L2078).

I think it would be possible to just change it to only put links to posts in the same section, probably controlled by a global setting like POSTS_SECTION_LOCAL_NAVIGATION.
As far as i could find out by greping the source, p.prev_post is only used for rendering the link and not for example to iterate over posts.

Another option might be to implement it as a plugin, but I'm still looking up if i would have to reimplement scan_posts or just add another scan_posts plugin that can then overwrite the prev_post/next_post attributes.

I'm trying to solve the problem myself for now, because I think it's a good and not to complicated task to get some understanding of the nikola codebase, but please let me know if you consider it a good/bad idea or if I'm on the completely wrong way :)

**Comment by felixfontein** [comment]
So you want different sections to behave a bit like individual blogs. For me, this is kind of similar (conceptually) to #2538.

**Comment by wirew0rm** [comment]
yes, it's the same basic problem that there are 2 representations for all posts, flat and sectioned.
#2538 should be just an additional taxonomy plugin, if I read the latest anouncement correctly.
Maybe this plugin could/should also overwrite the prev_post/next_post attribute to solve my problem on the way.

The problem of how I want to navigate with previous/next post is I think inherent with static blogs, because the page does not know if the user comes from the global index or the section index.
So the author of the blog has to decide which fits better.

In my case I have a travel centered section and a programming/linux centered section and i think it would be weird if these get mixed together.

**Comment by felixfontein** [comment]
#2538 cannot be just an additional taxonomy plugin, as #2538 asks for getting taxonomies for every single section, which Nikola simply doesn't support right now. That would require some major design changes.

The prev/next problem also happens with "dynamic" blogs, since prev/next should *not* depend on how you got to a page but only on the URL of the page.

@Kwpolska, @ralsina: perhaps it would make sense to add an option which sets on which taxonomy (or none, by default) the prev/next links are based on? Then one could set it to `section` to get in-section navigation, set it to empty string/None/False to get the classic prev/next links? The taxonomy would be required to have precisely one classification per post, though (or maybe at most one, the all posts not having one be considered as one classification as well?).

**Comment by Kwpolska** [comment]
There are a few things to consider:

* is implementing this feature worth it?
* how much new code will this need?
* how popular would it be?

**Comment by felixfontein** [comment]
I'd rather have this be combined with #2538 to be able to have multiple blogs in one Nikola site, each with its own tags, archives, and prev/next links. That's probably more popular, but on the other hand would require a larger refactoring (and might be break backwards compatibility).

BTW, this feature (prev/next links) can also be implemented by a `SignalHandler` plugin which simply sets `next_post` and `prev_post` when the signal `scanned` is caught. There'd be no need to add any additional code to Nikola core for only this feature.

**Comment by wirew0rm** [comment]
ok, I've started woking on a small plugin for just solving the prev/next problem.
Once I got it running I'll put it in the plugin repository.
https://github.com/wirew0rm/nikola-plugins/tree/section_prevnext/v7/section_prevnext

As for @Kwpolska's questions, I think the way sections work now is nice, but at least if you're new to nikola you easily end up with something that is like 90% of what you want (some indices can not be generated, some navigation feels weird).

**Comment by felixfontein** [comment]
The plugin looks fine. Just outcomment it, replace `iteritems` with `items` (then it also works fine with Python 3), replace `sectionposts[-1].next_post = None` by `sectionposts[-1].prev_post = None`, and remove most of the imports. At least for me (with a tiny little test site), it seems to work fine.

**Comment by felixfontein** [comment]
Closing since this was fixed by getnikola/plugins#204.
