### ISSUE TITLE
Assets locations doesn't respect SITE_URL

### ISSUE THREAD

**Issue by akhmerov** [getnikola/nikola#2629]
At least in the `bootstrap3_jinja` theme, css are loaded in `base_helper.tmpl` from `/assets/css` without being relative to `SITE_URL`, therefore breaking installation into a folder.

**Comment by felixfontein** [comment]
Aren't URLs such as `/assets/css` being rewritten in Nikola to respect `SITE_URL` in `Nikola.render_template` (by calling `Nikola.rewrite_links`)? I.e. do you see the wrong paths in the output generated by Nikola, or only in the template definition?

**Comment by akhmerov** [comment]
On nikola 7.8.2 after setting `SITE_URL = /test/`, and using a bootstrap3_jinja + bootswatch theme I see the unchanged paths int `output`.

**Comment by Kwpolska** [comment]
Cannot reproduce. What is your URL_TYPE value? How do the links look in output/index.html and output/some subdirectory/index.html?

**Comment by akhmerov** [comment]
I see, it didn't work with `URL_TYPE = 'rel_path'`, and did work with `full_path`. Is that as intended?

Also I observe that setting `SITE_URL = '/test/'` + `URL_TYPE = 'full_path'` breaks `nikola serve`.

**Comment by Kwpolska** [comment]
`full_path` breakage in `serve` is expected, because the /test/ path is not on the server. Here is what happens with `bootstrap3-jinja`+bootswatch and rel_path:

```
(nikola) [kwpolska@Kw-Farore n]% cat output/index.html|grep css
<link href="assets/css/all-nocdn.css" rel="stylesheet" type="text/css">
(nikola) [kwpolska@Kw-Farore n]% cat output/2012/index.html|grep css
<link href="../assets/css/all-nocdn.css" rel="stylesheet" type="text/css">

**Comment by akhmerov** [comment]
Sorry, I see, everything works. Thanks for the clarification.
