### ISSUE TITLE
new install - new_page fails

### ISSUE THREAD

**Issue by elguavas** [getnikola/nikola#2631]
steps to reproduce:

1. install nikola.
2. init a new project and cd to it's dir
3. run "nikola new_page" throws an exception.
4. however, run "nikola new_post -p" and it works just fine!??

i am puzzled, why does "new_post -p" work and "new_page" fail???

the exception trace i get is:
Traceback (most recent call last):
  File "/home/smg/.virtualenvs_py3/nikola/lib/python3.5/site-packages/doit/doit_cmd.py", line 167, in run
    return command.parse_execute(args)
  File "/home/smg/.virtualenvs_py3/nikola/lib/python3.5/site-packages/doit/cmd_base.py", line 120, in parse_execute
    return self.execute(params, args)
  File "/home/smg/.virtualenvs_py3/nikola/lib/python3.5/site-packages/nikola/plugin_categories.py", line 130, in execute
    return self._execute(options, args)
  File "/home/smg/.virtualenvs_py3/nikola/lib/python3.5/site-packages/nikola/plugins/command/new_page.py", line 113, in _execute
    return p.execute(options, args)
  File "/home/smg/.virtualenvs_py3/nikola/lib/python3.5/site-packages/nikola/plugin_categories.py", line 130, in execute
    return self._execute(options, args)
  File "/home/smg/.virtualenvs_py3/nikola/lib/python3.5/site-packages/nikola/plugins/command/new_post.py", line 244, in _execute
    date_path_opt = options['date-path']
KeyError: 'date-path'

**Comment by elguavas** [comment]
oh and i'm installing latest nikola via pip...  v7.8.2,   with [extras].

**Comment by felixfontein** [comment]
There's a little thing missing. I've added a fix in PR #2632.

**Comment by elguavas** [comment]
ok, cool. thanks for quick response! :) maybe some tests missing to prevent things like this from being in releases? do you know when there's likely to be a fixed version in pip?

**Comment by Kwpolska** [comment]
1. Tests are always good, but nobody wants to write them.
2. We don’t have strict timelines; a month is probably the minimum. If this was `new_post`, I’d opt to rush a release, but `nikola new_page` can be replaced by `nikola new_post -p` which will work, too (so functionality isn’t really lost, only a minor inconvenience in my opinion).

**Comment by elguavas** [comment]
thanks chris.

On 13/01/17 01:43, Chris Warrick wrote:
>  1. Tests are always good, but nobody wants to write them.

yep. wasn't trying to be critical here and i'm an open source developer 
myself so i know the story.

just thought in this case since it was an actual command that was broken 
and from the look of the patch it might not be difficult to catch with a 
test. no "please get right on it" implied at all.

>  2. We don’t have strict timelines; a month is probably the minimum. If
>     this was |new_post|, I’d opt to rush a release, but |nikola
>     new_page| can be replaced by |nikola new_post -p| which will work,
>     too (so functionality isn’t really lost, only a minor inconvenience
>     in my opinion).

yep using new_post -p is what i've been doing after looking in the docs 
and finding this, as per my bug report.

now, again, i'm not trying to say you need to do anything about this 
right away or anything, but consider my experience:

i was evaluating python static site generators and trying nikola for the 
first time, since the site i want to use it on is not a blog i followed 
< https://getnikola.com/creating-a-site-not-a-blog-with-nikola.html > in 
the nikola docs.

at step 3. in that tutorial i got an exception. so this was not a great 
look for my nikola trial.

luckily i hunted around in the docs and, fully expecting it to fail, i 
tried new_post -p, and was very puzzled to find it worked.

why should what seems to be a different way of invoking the same command 
lead to a different result? was i doing something wrong? was i failing 
to find something pertinent in the docs?

anyway i took the chance that i wasn't just being an idiot and put in 
this bug report, pretty much as a description of puzzling behaviour, in 
case it was actually a bug in a documented core command, which it turns 
out it was.

my extremely humble and freely ignorable (as a non contributor) opinion, 
is that a bug in a the pip release of a core command that bites people 
trying nikola for the first time by following the docs, is probably 
worth an out of band bugfix release.

i'm, just trying to be helpful here, not pushy. the reason i stuck with 
it and filed a bug rather than just giving up when following the docs 
lead to an exception is i think nikola looks good and so i wanted to 
bring that problem to your attention.

cheers.

**Comment by Kwpolska** [comment]
Well, your arguments make sense. I’ll try to get a release out now.
