### ISSUE TITLE
Support for Sphinx-style “link to here” headers

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2636]
Sphinx can show ¶ after a header, which offers a link to this section (#foo). This feature can also be useful for some Nikola sites.

**Comment by ralsina** [comment]
That is just a CSS tweak isn't it?

**Comment by Kwpolska** [comment]
No, it requires special handling in reST/other markup formats. [Pelican plugin](https://github.com/getpelican/pelican-plugins/blob/master/headerid/headerid.py); Sphinx also customizes it like this.

**Comment by ralsina** [comment]
It can be done using CSS+JS:

http://ben.balter.com/2014/03/13/pages-anchor-links/

Or a 3rd-party JS thing: https://github.com/bryanbraun/anchorjs

And I am pretty sure there is a pure-CSS version somewhere, something like

h4:after { content: "<a href=\"#" attr(id) "\">¶</a>" ; }

**Comment by Kwpolska** [comment]
All three are ugly hacks.

**Comment by ralsina** [comment]
We can do it in our HTML processing step in Post.compile_html
