### ISSUE TITLE
Hardcoded colors

### ISSUE THREAD

**Issue by drym3r** [getnikola/nikola#2639]
In nikola serve or nikola auto, concretely. If any of that orders are used on a dummy terminal without color support, the symbols are shown like symbols, not colors. For example, I use emacs and I execute the function start-process-shell-command with nikola and this is what I see on the buffer:

    ^[[37m[2017-01-16T10:16:08Z] INFO: serve: Serving HTTP on 127.0.0.1 port 8000...^[[39;49;00m

I've being told that what it should be done is make the program detect the curses library, but I'm not sure. If required, I could ask more information.
PD: Not sure if relevant, but I can't get rid of the symbols even with sed like ``nikola serve | sed "s/\^\[\[//g"

**Comment by Kwpolska** [comment]
Workaround:

    NIKOLA_MONO=1 nikola serve

A lot of programs struggle when run inside non-terminals. I’m willing to blame Emacs here, for lying that it is a TTY. We use this check for color support:

```py
    if sys.stderr.isatty() and os.name != 'nt' and os.getenv('NIKOLA_MONO') is None:
        colorful = True
```

If you know of a more reliable check, in more exact terms, let us know.

**Comment by wasamasa** [comment]
Um, you *are* connected to a tty (as opposed to have your input/output redirected to a file which would make that check fail), but you aren't checking whether the underlying thing supports colors.  The easiest way of testing this is checking the value of `TERM` against a known set of values associated with dumb ttys, including "dumb".  Emacs happens to set `TERM` to "dumb" and lots of other programs do as well, so doing that check is a nobrainer.

**Comment by lokedhs** [comment]
Just knowing you're connecting to a tty isn't enough. You also need to heal with the fact that different types of tty's handle colours differently. The correct way to do this is though a library that is designed to handle the particulars of different types, such as terminfo or curses.

**Comment by drym3r** [comment]
Yeah, the workaround works nicely, thank you very much. 
I actually don't know how it would be "better", I just asked on the #emacs irc channel and somebody answered me that this was the problem. If you are actually handling it, I don't know what else do. I'll close the issue, and if I can find some more information, I'll reopen it. 
Thanks.

**Comment by Kwpolska** [comment]
Well, we are not handling it perfectly. @wasamasa where do I find a trustworthy, up-to-date list of $TERM settings?

**Comment by lokedhs** [comment]
I'd recommend using the terminfo API which will handle all of this regardless of terminal settings. The API is part of Curses (or Ncurses if you prefer): https://en.wikipedia.org/wiki/Terminfo

I've used this API before and I am somewhat comfortable with it. I'll be happy to help explain things.

**Comment by Kwpolska** [comment]
It looks like terminfo is taken care of by the `curses` library in Python. Is [curses.can_change_color](https://docs.python.org/3.6/library/curses.html#curses.can_change_color) enough?

**Comment by lokedhs** [comment]
Very likely, yes. But ideally you should also use the same library to determine which escape sequence you should send instead of hardcoding them. There are terminal types that use different escape sequences (although they are getting more and more rare these days), but using the library to generate the sequences is also more clear, and it's guaranteed to always work.

**Comment by Kwpolska** [comment]
1. Those escapes are taken care of by a different library. Also, I am not willing to support any crazy terminals.
2. `can_change_color` requires the whole curses shebang (`curses.initscr()`) which breaks things (clears screen). Are you aware of any other solutions in Python?

**Comment by lokedhs** [comment]
Did you try to use `setupterm()` instead? `initscr()` is used to initialise the temrinal for full cursor control. `setupterm()` simply initialises the library.

**Comment by Kwpolska** [comment]
```
$ python -c 'import curses; curses.setupterm(); print(curses.can_change_color())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
_curses.error: must call initscr() first
```

**Comment by lokedhs** [comment]
Doesn't the Python interface provide a `setupterm()` function?

**Comment by Kwpolska** [comment]
```
$ python -c 'import curses; curses.setupterm(); print(curses.can_change_color())'
                            ^^^^^^^^^^^^^^^^^^
```

**Comment by lokedhs** [comment]
I'm not sure what that means, but I'm guessing that the Python API doesn't
expose that function?

If so, the least invasive solution I can think of is to look directly at
the `TERM` environment variable and decide if it's one of the values that
supports colour, and fall back to plain text otherwise. The typical one is
`xterm-256color`, but also `xterm-color`.

There may be others, and if you really want to know which ones they are you
could take a look at the data files for terminfo manually, but those two
will cover amost all cases.

**Comment by Kwpolska** [comment]
The function exists, but `can_change_color()` really wants `initscr()`. `xterm` also supports color, for example. I guess we can go with that.

@drym3r are you using Emacs from within a terminal emulator, or a GUI? What does `echo $TERM` say when doing it in both modes?

**Comment by lokedhs** [comment]
There are two typical ways to run a terminal in Emacs. One uses a full terminal emulator (not fully compatible with `xterm-256color`, so to support it you'd need to use terminfo). This mode uses a `TERM` value `eterm-color`. The other is a a mode which is a proper Emacs buffer so it has no terminal emulation at all. In this mode the value of `TERM` is `dumb`. This is a typical value used for terminals that provides no features at all.

**Comment by wasamasa** [comment]
@Kwpolska If you insist on doing this the perfect way, you'll need to query `TERM` against the termcap database and check for the color capabilities.  The practical way is checking against a set of known `TERM` values that do under no circumstances support color, the most common one of those being "dumb".  All you need to do is just add a `os.getenv('TERM') != 'dumb'`, really.
