### ISSUE TITLE
How to arrange several figures in a flexible list (like standard gallery)?

### ISSUE THREAD

**Issue by Fotofreund** [getnikola/nikola#2647]
The standard gallery puts several thumbnails in a flexible list depending on the screen size. When the mouse points at a thumbnail, a tool-tip shows the file name.

The standard figure puts only one image with an optional caption in a separate block.

I would like to places several figures with captions in a flexible list. Has anyone tried something similar?

**Comment by ralsina** [comment]
There is a gallery directive plugin for restructured text that could do
what you want. It's a hack.

https://plugins.getnikola.com/v7/gallery_directive/

Basically:

* Put your images in galleries/whatever
* In your document: .. gallery:: whatever

And that should do it.

**Comment by Fotofreund** [comment]
Thanks for the fast answer.

I tried it with a sample gallery, and I got a double navigation bar and a double footer.

![grafik](https://cloud.githubusercontent.com/assets/20303883/22308095/d7edfe3e-e345-11e6-9c55-6bbbc798ef58.png)
![grafik](https://cloud.githubusercontent.com/assets/20303883/22308139/0853176c-e346-11e6-85d0-349fa19a39af.png)

This looks quite strange.

**Comment by ralsina** [comment]
Hey, it's a hack, looks like it needs some extra hacking nowadays ;-)
