### ISSUE TITLE
allow specifying of section only via path, then let nikola append filename

### ISSUE THREAD

**Issue by t-animal** [getnikola/nikola#2651]
There is currently no easy way to specify a section for a new post.
`nikola new_post posts/sectionname/here-i-have-to-think-of-the-slug-of-the-title-already.md` and then specifying the Title in nikola seems error prone. It would be much nicer if one could specify the section-path only and the filename would then be appended: `nikola new_post posts/sectionname`.

**Comment by ralsina** [comment]
But Nikola needs to create the file to let you edit it, there is no way around that.

There is no reason why the filename you edit and the slug have to match, tho.

**Comment by Kwpolska** [comment]
What @t-animal wants, and what is feasible IMO, is for `nikola new_post posts/directory` to create `posts/directory/slug.rst` automatically.

**Comment by t-animal** [comment]
Yes @Kwpolska is right, sorry if I did not state that clearly

**Comment by ralsina** [comment]
I still don't get it. what would "slug" be in that case? index?

**Comment by Kwpolska** [comment]
No, it would be whatever the user-provided title slugifies to. So basically, what we do when no path is specified, but with the user choosing the exact location for their new post.

**Comment by t-animal** [comment]
maybe i used the wrong words here. when I create a new post using `nikola new_post` i am asked for a title of that post. the resulting file will be named similarly to the title, let's call that filename `f`. when i create a post in a specific section by specifying `nikola new_post posts/sectionname/<f>` I have to think of how nikola creates `f`. i think it would be easier to do `nikola new_post posts/sectionname/`, be asked for a title and let nikola decide how the new file should be called.
