### ISSUE TITLE
Nikola 7.8.3 does not work with rest_html5 plugin

### ISSUE THREAD

**Issue by andredias** [getnikola/nikola#2657]
I've just upgraded Nikola from 7.7.8 to 7.8.3 and it stopped working. Any command I try to execute gives an error like this:

```
Unable to open source file for reading:
  InputError: [Errno 2] File or directory not found: 'new_post'
```
I've managed to discover the source of error. It is the `rest_html5` plugin. If I remove it, Nikola works again.

**Comment by Kwpolska** [comment]
What if you upgrade that plugin (re-install)? Also, do you have any files named `new_post`?

**Comment by Kwpolska** [comment]
It’s a bug in rst2html5 — it breaks with `docutils==0.13.1`. That error message comes from docutils, and also comes up when running `rst2html5 version`; I can cause it if I replace all function code in the Nikola plugin with `return`.

https://bitbucket.org/andre_felipe_dias/rst2html5/issues/27/incompatible-with-docuitls-0131-in-nikola

**Comment by andredias** [comment]
you're right. Sorry for that.
