### ISSUE TITLE
table of content generation

### ISSUE THREAD

**Issue by shelper** [getnikola/nikola#2658]
i wonder how the TOC of this page was generated? 
https://getnikola.com/handbook.html
if possible, would it be nice that we can specify whether to generate TOC of an article in the header file, e.g. by adding a toc option to the header and if the value is True, a TOC will be generated for the page/post. 

 
```
<!--
.. title: 
.. slug: 
.. date: 
.. tags:
.. category: 
.. link:
.. description:
.. type: text
.. toc: False
-->
```

**Comment by felixfontein** [comment]
Take a look at its source code: https://github.com/getnikola/nikola-site/blob/master/stories/manual.txt

**Comment by Kwpolska** [comment]
In reStructuredText, use `.. contents::` and in any other input format, use whatever that input format offers (if it does).

**Comment by fullpwemium** [comment]
@shelper did you ever figure this out?

**Comment by AtmaMani** [comment]
I am looking for suggestions to auto build and insert a ToC pane for Jupyter notebooks and markdown files. If you have an idea, please share.

**Comment by Kwpolska** [comment]
@AtmaMani Did you try googling "jupyter table of contents"? There might be extensions for Jupyter to solve your problem.

**Comment by AtmaMani** [comment]
@Kwpolska Yes, I am using [Table of Contents 2](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/toc2/README.html) extension and it works out quite well. While this is something, I wanted to know if Nikola nb processor could generate it automatically and give a sidebar layout.
