### ISSUE TITLE
Post-list plugin shouldn't list the post where the post-list directive is declared

### ISSUE THREAD

**Issue by andredias** [getnikola/nikola#2666]
Post: `posts/xyz.rst` with tags: `version control`, `mercurial`

At the end, I declare:

```rst
.. post-list::
    :tags: version control, mercurial
```

The problem is that the post `xyz.rst` is listed at the post-list. This is redundant.

I have an idea how to fix this, but I need some feedback about the changes I'd make.
I know the post path being compiled is stored at `self.state.document.settings._nikola_source_path`.
I could pass this piece of information to `_do_post_list` via the `filename` parameter and then remove the post from the `timeline`. However, I'm not sure about the impact in `self_post`. Would it still be necessary if the post is removed?

Any suggestions?

**Comment by ralsina** [comment]
It's probably easier to just try it and see if it works :-)

**Comment by andredias** [comment]
Ok!

**Comment by Kwpolska** [comment]
> I know the post path being compiled is stored at `self.state.document.settings._nikola_source_path`.

You cannot depend on that if shortcodes are used.

**Comment by andredias** [comment]
Is there another way to get this information?

**Comment by ralsina** [comment]
Shortcodes have a filename parameter
