### ISSUE TITLE
Teasers subsection not available in manual 

### ISSUE THREAD

**Issue by KozakIvan** [getnikola/nikola#2667]
After install nikola i made new site with -d option and built him. Teasers subsection not available in result html manual, but in the source manual it is present. Sorry for my English.

**Comment by Kwpolska** [comment]
Weird. It works for me. Try rebuilding with `nikola build -a` (just in case) and compare the contents of `output/pages/handbook/index.rst` and `output/pages/handbook/index.html`.

**Comment by KozakIvan** [comment]
look at https://getnikola.com/handbook.html#teasers not available

**Comment by Kwpolska** [comment]
What version are you using?

    nikola version

**Comment by KozakIvan** [comment]
$ nikola version
Nikola v7.8.3

**Comment by Kwpolska** [comment]
In your Nikola site:
```
grep -R Teasers .
```
And please show a screenshot of your site with the section missing.

**Comment by KozakIvan** [comment]
look at the main site https://getnikola.com/handbook.html#teasers, my problem is the same. Subsection Teasers is not available in handbook

**Comment by Kwpolska** [comment]
This is what I can see:

![image](https://cloud.githubusercontent.com/assets/327323/23022820/2013277a-f453-11e6-908d-f80c360dc796.png)

**Comment by KozakIvan** [comment]
![2017-02-16 16 22 01](https://cloud.githubusercontent.com/assets/1391196/23022854/1be3010a-f464-11e6-877c-d42ec6f61fe2.png)

**Comment by Kwpolska** [comment]
Your uBlock setup removes `#teasers`. Disable uBlock on our site (we don’t have any ads), and report it to uBlock (check which filter does that).

**Comment by KozakIvan** [comment]
You're right, sorry

**Comment by Kwpolska** [comment]
It’s not your fault.

**Comment by felixfontein** [comment]
It's probably not uBlock, but EasyList or some other filter list which does that. I recently also had some "fun" with it since it blocks all images files containing `-300x600.` (easylist/easylist#79).
