### ISSUE TITLE
Thumbnails for files in IMAGE_FOLDERS are not generated

### ISSUE THREAD

**Issue by laodzu** [getnikola/nikola#2672]
According to the documentation thumbnails should be generated for files in IMAGE_FOLDERS so they can be accessed from the ReST ..thumbnail construct.  This is not happening but I also don't get any error.  Running "nikola check -l" gives WARNINGS about the broken link for the "xxx.thumbnail.png" file, but I see no way how to generate the thumbnails.

What am I doing wrong?

nikola v7.6.4

**Comment by ralsina** [comment]
The thumbnails should be automatically generated when you run nikola to build the site, there is no specific explicit step to do it.
If they are not, then there is some problem. Could you try to use a newer version so we are sure we are all testing the same code?

**Comment by tritium21** [comment]
You *might* want to upgrade to a recent version of Nikola and try again.  if that doesn't help, come back and tell us.

**Comment by Kwpolska** [comment]
You are using an ancient version of Nikola, which does not support the thumbnail feature. Please complain to Debian/Ubuntu and install [the recommended way](https://getnikola.com/getting-started.html).

**Comment by ralsina** [comment]
@Kwpolska really? According to the changelog, it was added in 7.3.0

* New plugin for creating image thumbnails, and a corresponding reST
  plugin (Issue #1527)

**Comment by Kwpolska** [comment]
If the issue persists in a newer version, @laodzu can always reopen.

**Comment by laodzu** [comment]
Ok, thanks for the info.  Indeed I'm using nikola from Debian stretch.  The installed manual (/usr/share/doc/nikola/manual.txt.gz) does claim that thumbnails are supported though.

**Comment by laodzu** [comment]
Unfortunately still no success:

(nikola) dzu@deepthought:~/blog$ nikola build
Scanning posts....done!
(nikola) dzu@deepthought:~/blog$ nikola check -l
Scanning posts....done!
[2017-02-17T16:10:13Z] WARNING: check: Broken link in output/posts/trip-planning-for-road-bikes.html: ../images/route-outdooractive.thumbnail.png
(nikola) dzu@deepthought:~/blog$ nikola --version
Nikola v7.8.3
(nikola) dzu@deepthought:~/blog$ 

Any more hints?

**Comment by Kwpolska** [comment]
Show us:

* contents of `images/`
* contents of `output/images/`
* `IMAGE_FOLDERS` from conf.py

**Comment by laodzu** [comment]
Ouch.  Indeed I introduced a typo in conf.py upon the update...

Upon correcting this, it now indeed works as expected, thanks!
