### ISSUE TITLE
Shipped moment-with-locales doesn't have Basque

### ISSUE THREAD

**Issue by sukiletxe** [getnikola/nikola#2678]
### Environment (if reporting a bug)

**Python Version:** 3.6

**Nikola Version:** 7.8.3

**Operating System:** Windows 7

### Description:

Oddly, the  `moment-with-locales.min.js` and the `locales.min.js` files do not include Basque. It is, however, included in the non-minified versions. This got fixed (although I can't find any changelog entry) in 2.16.0 (Nikola uses 2.10.6, I believe).
(Disclaimer: I don't use Moment. I saw it didn't work when testing and decided to investigate.)

**Comment by Kwpolska** [comment]
The Node ecosystem can be hard sometimes. It should work on master.
