### ISSUE TITLE
Uncomment default values in conf.py

### ISSUE THREAD

**Issue by sukiletxe** [getnikola/nikola#2680]
### Environment (if reporting a bug)

**Python Version:**

**Nikola Version:**

**Operating System:**

### Description:
Currently, `conf.py` contains default options which are commented; that is to say, options which have the same value as the default one, which are commented out. For consistency reason, they should be uncommented.

**Comment by Kwpolska** [comment]
Should they really? Sometimes it might be better to upgrade defaults for users. By leaving an option uncommented, you effectively say “I don’t care”.

**Comment by sukiletxe** [comment]
Well, that's true. Let me explainmyself: The scenario behind my proposal was that I sometimes can't figure out if the commented setting is a default value or a disabled one.

**Comment by tritium21** [comment]
If the stock `conf.py` comments out a line, thus disabling a feature, then the default for the feature is *disabled*.  If you, the user, comment out a line, and need a way to note that... its a comment.  You can write anything you want after the `#`

**Comment by Kwpolska** [comment]
Let’s leave this as-is.
