### ISSUE TITLE
article author is not recognized (microformat?) by Google Search Console

### ISSUE THREAD

**Issue by wichtounet** [getnikola/nikola#2691]
Hi, 

I recently noticed that my site generated with Nikola and the bootstrap3 theme (customized in a sub theme) has issues with Google Search Console for the article information. The hentry author is not detected in Google Search Console. And there are a few other errors as well. 

The website is available online: For instance, this post: http://baptiste-wicht.com/posts/2017/03/disappointing-zapcc-performance-on-deep-learning-library-dll.html

The results are here:
https://search.google.com/structured-data/testing-tool?url=http://baptiste-wicht.com/posts/2010/07/osgi-hello-world-services.html#url=http%3A%2F%2Fbaptiste-wicht.com%2Fposts%2F2017%2F03%2Fdisappointing-zapcc-performance-on-deep-learning-library-dll.html

This is probably not a big deal, but I'd rather fix these errors. Is there something I can change in the config to fix this or do I have to edit the theme myself ? 

I have the following versions: 
Nikola 7.7.4
Python 2.7.12

Thanks

Baptiste Wicht

**Comment by Kwpolska** [comment]
`itemprop="author"` on `<span class="byline-name fn">` will fix the author complaint, and I pushed that to master. `publisher` requires `Organization` as type (which is pretty crazy) — you’re on your own on how to provide that, because does Google really care about that information anyway?

**Comment by wichtounet** [comment]
Thanks for the very quick fix!

I'll see for the others myself.
