### ISSUE TITLE
Duplicated description in generated HTML ?

### ISSUE THREAD

**Issue by wichtounet** [getnikola/nikola#2694]
Hi, 

I just ran an online SEO analysis on my website and found out that the pages had duplicated description. 

In the head, I found these three:

```
<meta name="description" content="Description on how I added MiLight smart LED Bulbs in my home and monitored them in Domoticz.">
<meta name="description" itemprop="description" content="Description on how I added MiLight smart LED Bulbs in my home and monitored them in Domoticz.">
<meta property="og:description" content="Description on how I added MiLight smart LED Bulbs in my home and monitored them in Domoticz.">
```

(The og:property is probably not a duplicate of the others)

And in the body (under the source link): 

```
<meta name="description" itemprop="description" content="Description on how I added MiLight smart LED Bulbs in my home and monitored them in Domoticz.">
```

I'm using a theme with bootstrap3 as parent. 

This can be seen online: http://baptiste-wicht.com/posts/2017/01/add-milight-smart-lights-to-domoticz-home-automation-system.html

I have the following versions:
Nikola 7.8.3
Python 3.4

Is there anyway to avoid this ? 

Thanks

Baptiste

**Comment by Kwpolska** [comment]
There seems to be a bug in the template, which needs to be fixed to “avoid this”.

**Comment by wichtounet** [comment]
Thanks for the quick reply :)

**Comment by wichtounet** [comment]
Thank you very much, it works great with the new release.
