### ISSUE TITLE
language href points to the SITE_URL 

### ISSUE THREAD

**Issue by diramazioni** [getnikola/nikola#2697]
### Environment (if reporting a bug)

**Python Version:**
3.6
**Nikola Version:**
Nikola-7.8.3
**Operating System:**
ubuntu
### Description:

The href defined in `html_translations()` in `templates/base_helper.tmpl` points to the final url ie. `http://foo.com/en/` not to `/en/` so it's not working until it's fully deployed.

**Comment by Kwpolska** [comment]
This is intended behavior — our translations and site title link to the absolute URL, so that they point to the one true URL for the site. Feel free to remove `abs_link()` from the template.

**Comment by diramazioni** [comment]
Well it works as expected for subpages ie for new pages in pages/sub but not for pages in /
I should have specified that I'm following the configuration described in "creating a site not a blog"

**Comment by Kwpolska** [comment]
I’m not sure what you mean. The translations and logo are *meant* to be absolute URLs, the rest should be relative.

**Comment by diramazioni** [comment]
never mind I was seeing a defect that I can't reproduce anymore.
thanks
