### ISSUE TITLE
json.decoder.JSONDecodeError when not in virtualenv root folder

### ISSUE THREAD

**Issue by ulno** [getnikola/nikola#2708]
### Environment (if reporting a bug)

**Python Version:**
Python 3.5.2+

**Nikola Version:**
Nikola v7.8.4

**Operating System:**
Ubuntu 16.10

### Description:
I just upgraded my Nikola virtual python environment and started getting this error:
```
(nikola) ulno@ulno-surface3:~$ nikola
Traceback (most recent call last):
  File "/home/ulno/apps/nikola/bin/nikola", line 11, in <module>
    sys.exit(main())
  File "/home/ulno/apps/nikola/lib/python3.5/site-packages/nikola/__main__.py", line 167, in main
    site = Nikola(**config)
  File "/home/ulno/apps/nikola/lib/python3.5/site-packages/nikola/nikola.py", line 989, in __init__
    self._set_global_context_from_data()
  File "/home/ulno/apps/nikola/lib/python3.5/site-packages/nikola/nikola.py", line 1245, in _set_global_context_from_data
    data = utils.load_data(fname)
  File "/home/ulno/apps/nikola/lib/python3.5/site-packages/nikola/utils.py", line 2027, in load_data
    return loader.load(inf)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
If I first navigate to apps/nikola (with cd apps/nikola), it runs fine. So something with the paths seems to be messed up.

This makes it pretty much impossible for me to compile my website as it is in a different folder than $HOME/apps/nikola

Any idea what is going wrong - seems like others should be affected too?

**Comment by ulno** [comment]
I also tried upstream github, also showing version v7.8.4 -> same issues.

However, I discovered that running Nikola from $HOME/apps (apps is the directory in which the nikola virtual environment, named Nikola,  is) still works. If I execute it from $HOME/ it does not work.

So, my current work-around is to make a symbolic link from the Nikola virtual environment into my website-folder.

Still strange though, but workable.

**Comment by Kwpolska** [comment]
Have you got a `data` directory in your home?

Make a small debug patch: file "/home/ulno/apps/nikola/lib/python3.5/site-packages/nikola/utils.py", line 2026, in load_data:

```py
    with io.open(path, 'r', encoding='utf8') as inf:
        print(path)
        return loader.load(inf)
```

and run `nikola build -v 2`.

**Comment by ulno** [comment]
Ok, I must have miss judged. In my build directory it works also without
the link. So it IS the data directory in my home directory.

It prints out a path to simplejax.js in one of the subfolders of
/home/ulno/data.

So it is not really so critical, however a bit confusing as I just wanted
to look at the possible commands as I was considering building some
auto-post mechanism to post new articles to Twitter and Facebook and wanted
to check out the existing plugins.

Ulno

**Comment by felixfontein** [comment]
@Kwpolska: maybe we should only try to load the data if a config file was loaded? Or is there a reason why the data should always be loaded?

**Comment by Kwpolska** [comment]
Sure, did exactly that.

**Comment by ulno** [comment]
Confirming, this solves my initial confusion and doesn't fail anymore now - even when run from my home directory directly.
