### ISSUE TITLE
`Read More` link text must be unique

### ISSUE THREAD

**Issue by ivanteoh** [getnikola/nikola#2709]
### Environment (if reporting a bug)

**Python Version:** All Python version

**Nikola Version:** v7.8.3

**Operating System:** All operating system

### Description:
Current `Read More` link text is not unique on the index page. 

It fails accessibility report. More info at https://fae.disability.illinois.edu/rulesets/LINK_2/.

### Option solutions:

- [ ] give more tags for generating unique link text. For example, post title. https://github.com/getnikola/nikola/blob/3835c95adebc227e5a1167d981c659be279bc732/nikola/post.py#L690-L697

Any more suggestions?

**Comment by Kwpolska** [comment]
Add a `title` tag to those anchors if you really need it. In my opinion, it makes no sense whatsoever.

**Comment by ivanteoh** [comment]
@Kwpolska where to get `title` tag value? Currently, `INDEX_READ_MORE_LINK = '<p class="more"><a href="{link}">{read_more}…</a></p>'` If I want to add `title` tag, the html code will be `<p class="more"><a title="{post_title}" href="{link}">{read_more}…</a></p>'`. So I need more tags, or that is another way to do it? Thanks.

**Comment by Kwpolska** [comment]
This would require modifying the codebase. master now supports `{post_title}`.

**Comment by ivanteoh** [comment]
@Kwpolska , great and thanks .
