### ISSUE TITLE
Where can I find what default fields are available in templates?

### ISSUE THREAD

**Issue by adamcavendish** [getnikola/nikola#2712]
For example, in templates, we have `${header.html_site_title()}` for the site title. Where can I find the whole list?

**Comment by felixfontein** [comment]
That is template dependent. You can grep for `<%def name"` to find all Mako block definitions.

(You might also be interested in #2328, which deals with variables available in templates.)

**Comment by Kwpolska** [comment]
Unfortunately, we don’t have complete theme documentation. In this case, `html_site_title()` is a function that comes from whatever was imported as `header` — using `<%namespace name="header" file="base_header.tmpl" import="*"/>`.

**Comment by adamcavendish** [comment]
Ok, I see... What about the `${blog_title}` kind of variables?

**Comment by Kwpolska** [comment]
Variables and functions may come from three places:

* the global Nikola context, eg. `blog_title` — search for `GLOBAL_CONTEXT` in [nikola.py](https://github.com/getnikola/nikola/blob/master/nikola/nikola.py)
* the local context of a function, eg. `post` in `post.tmpl` — those are hidden in every
* imported templates, eg. `header.html_site_title()` — see the imports at the top of a template

Documenting it is a task we’ve never really gotten to, sorry.

**Comment by adamcavendish** [comment]
Ok, got it. Thx.

**Comment by Kwpolska** [comment]
It’s not really solved, so reopening.
