### ISSUE TITLE
Fetch posts / articles from gdrive

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2716]
I am writing some stuff at work that will end up in my personal blog.

I have been using stackedit.io with a google drive backend, so that I can edit anywhere and things end in a folder in google drive.

So, proposed feature:

* Specify somehow a source of files from gdrive in conf.py
* Specify credentials in conf.py
* Have a plugin that fetches / syncs / something those files
* Add them to the build
* ????
* profit

Since this is something I would like working, I will get to it as time permits.

This may connect to #2659 depending on how it's implemented.

**Comment by Kwpolska** [comment]
If you used Dropbox, you could just use the Dropbox client and put it in POSTS/symlink it somewhere; Google Drive still lacks a Linux client.

**Comment by ralsina** [comment]
Well, Drive is accessible via APIs, so if "file-less posts" would work, then the contents could be fetched on demand.

**Comment by Kwpolska** [comment]
File-less posts are pretty dangerous here — what if you build the site offline?

**Comment by felixfontein** [comment]
The best solution is probably to let the build fail.

BTW: What do we currently do when a gist is included in a page and one tries to build the site offline?

**Comment by tritium21** [comment]
Gists have JS embed codes.  I assumed (but have not confirmed) that Nikola just uses those.

**Comment by felixfontein** [comment]
I just looked at the code: it does create JS, but it also adds a `<noscript>` with the raw gist code (by downloading it with `requests`). It will generate an error if it cannot get the raw gist from `gist.github.com`.

**Comment by ralsina** [comment]
Since I asked for this and have done nothing about it, clearly I did not want it THAT much.
