### ISSUE TITLE
-bash: nikola: command not found

### ISSUE THREAD

**Issue by JMITCHELL93** [getnikola/nikola#2721]
Until now I have been using linux to develop my website.  I wanted to try on my Mac.

After I installed, I cd to the location of my webpage but when I run 'nikola build' I get:
-bash: nikola: command not found

Any ideas, perhaps a path issue?

Jamie

**Comment by Kwpolska** [comment]
How did you install Nikola and Python?

**Comment by JMITCHELL93** [comment]
Hi Kwpolska,

I installed both using the instructions on the getting started website (see section under installing on MacOS):
https://getnikola.com/getting-started.html

**Comment by Kwpolska** [comment]
So you’re using a virtualenv. Have you *activated* it before running Nikola?

**Comment by JMITCHELL93** [comment]
Hi Kwpolska,

I have now solved the issue.  It was an lxml runtime issue.  The solution I used for anyone else having problems is here: http://stackoverflow.com/questions/23172384/lxml-runtime-error-reason-incompatible-library-version-etree-so-requires-vers

Thanks for your help.

**Comment by Kwpolska** [comment]
This should not cause a “command not found” error. Are you sure you are not mixing up two different problems?
