### ISSUE TITLE
Sections conflict with pages that would replace them

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2724]
> ERROR: Two different tasks can't have a common target.'output/sec1/index.html' is a target for render_pages:output/sec1/index.html and render_taxonomies:output/sec1/index.html.

To reproduce:

* set POSTS and PAGES to output to the root of the site
* create `posts/sec1/foo.rst` and `pages/sec1.rst`

`should_generate_classification_page` is supposed to prevent this, but it fails — `post_list` only contains posts from the section, so it doesn’t check the page, and thus fails. Perhaps we could fix it by giving all posts/pages to that function?

**Comment by felixfontein** [comment]
The function already has access to all posts and pages because it has access to the `site` object.
