### ISSUE TITLE
typogrify filter mangles & in <title>

### ISSUE THREAD

**Issue by Anteru** [getnikola/nikola#2732]
### Environment (if reporting a bug)

**Python Version:** 3.5

**Nikola Version:** 7.8.4

**Operating System:** Ubuntu 17.04

### Description:

The `typogrify` filter will wrap & with `<span class="amp"></span>` - even if the & is inside the `<title>`. It's easy to reproduce, create a blog post with a & in the title, enable the typogrify filter, and notice the resulting `<title>` tag has the & wrapped in the span, which ends up like this in the browser's page title.

I guess the solution is to make sure typogrify only works on the `<body>` of the page.

**Comment by Kwpolska** [comment]
Perhaps report a bug to typogrify? Some of their filters are limited to specific HTML tags, so this one could be too.

**Comment by Kwpolska** [comment]
[(over here)](https://github.com/mintchaos/typogrify/issues) — if they won’t do it, reopen this issue and we’ll try to handle it on our end.

**Comment by Anteru** [comment]
Filed it over there (https://github.com/mintchaos/typogrify/issues/48) -- I noticed there was already one of the typogrify filters disabled in Nikola and I thought that's would be similar issue. Thanks for the pointer!

**Comment by Anteru** [comment]
Doesn't look like they're actually fixing things either, last commit from 3 years ago?
