### ISSUE TITLE
Change the output location for sections

### ISSUE THREAD

**Issue by h4ckninja** [getnikola/nikola#2738]
### Environment (if reporting a bug)

**Python Version: 3.6.1**

**Nikola Version: Nikola v7.8.4**

**Operating System: macOS 10.12**

### Description:
With sections, some of the expected behavior appears to be missing as it was with categories. I do see that #2486 is to work on one of the wants I have. For now, I'm fine with setting the metadata for my files.

However, with categories, I have the following set:

~~~
CATEGORY_PATH = 'blog/categories/'
CATEGORY_PREFIX = ''
CATEGORIES_INDEX_PATH = 'blog/categories.html'
~~~

With sections, I don't see such an option available to control the output location. I'd like to have the ability to control the output location as I can with categories.

**Comment by Kwpolska** [comment]
Sections are a bit special, in that they sometimes assume a relation to the filesystem — they were originally built so that `foo/bar.rst` was in the `foo` section, but also allow specifying those in post metadata.

This should get fixed — and in the long term, we could probably clean up categories vs sections.

**Comment by felixfontein** [comment]
Do you just want to move the section indexes/feeds/..., or also the posts in the sections? The placement of the posts in the output tree is already managed by the `POSTS` variable.

Implementing a `SECTION_PATH` which just moves the indexes, feeds etc. around is pretty simple, you just need to modify `ClassifySections.get_path` accordingly in `plugins/task/sections.py`. If you're happy with that, I can do a PR.

**Comment by felixfontein** [comment]
Yes. A setting `SECTION_PATH` would allow you to place the section indexes where you want them, like in this case probably in `/blog/` as well.

**Comment by h4ckninja** [comment]
Ah, yes. That is what I am looking for.
