### ISSUE TITLE
Be able to set the URL name andfile extension of posts and other files

### ISSUE THREAD

**Issue by h4ckninja** [getnikola/nikola#2739]
### Description:

Perhaps a feature request for v8 #1718? I'd like to be able to set filename and file extension for posts and other files that get written. If you turn off pretty URLs, you are stuck with `.html`. Usually that's fine, but it'd be nice (which is why I think this is probably better as a v8 request) to be able to control the extension.

In the same idea, it'd be nice to control other files that get written more explicitly. For example, the following setting is present:

~~~
RSS_PATH = 'blog/feed'
~~~

However, this forces the user to have `.xml` as the extension. I'd like to be able to set that as `.rss`.

This idea also applies to really any URL to expose more control to the user as to what they want to set, such as the sitemap, pagination, etc.

**Comment by Kwpolska** [comment]
Which extension would you use for HTML files? Why that one? Why not enable PRETTY_URLS?

As for the RSS files — do you really need it? Your users won’t notice the RSS path at all, it will be abstracted away by their feed reader — those are all internal details.

In my opinion, this would be overengineering, and not really used.

**Comment by h4ckninja** [comment]
Why not pretty URLs? - Personal preference, I don't consider creating folders for a resource very pretty. I'd like to be able to set any extension, or no extension for the URLs on my site.

RSS files - My return question would be: Why force the user to have hard-coded things for their own site? It's their content, shouldn't they have a say in what gets set? That said, the RSS filename is less important to me than the extensions for other things.

**Comment by felixfontein** [comment]
You can define your own post/page paths (except extension) by creating a post scanning plugin which extracts the metadata before creating the `Post` object, and by then adjusting the post's path accordingly.

The file extension for posts and pages is fixed to `.html`, though. The only way to override it is when the page compiler specifies an explicit extension, which will then be used for *all* posts and pages using that compiler. In general, `.html` is hardcoded in several places, so getting rid of `.html` won't be easy without some refactoring or a lot of (really ugly) monkey-patching.

**Comment by Kwpolska** [comment]
You don’t need a fancy plugin if you create the right directory hierarchy in your source, perhaps set POSTS/PAGES accordingly (to remove `posts/`) and use any slug you want.

**Comment by h4ckninja** [comment]
>The file extension for posts and pages is fixed to .html, though. The only way to override it is when the page compiler specifies an explicit extension, which will then be used for all posts and pages using that compiler. In general, .html is hardcoded in several places, so getting rid of .html won't be easy without some refactoring or a lot of (really ugly) monkey-patching.

I appreciate the explanation. I kinda figured that'd be the case from what digging around I have done so far. Maybe make this a feature suggestion for some future refactoring of the relevant classes? My intention wasn't to say that this is a bug - it isn't. It works as described. I just would like some additional flexibility for my content and site.

**Comment by ralsina** [comment]
3 years, no movement, we clearly don't really want this.
