### ISSUE TITLE
Nikola auto builds too much

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2740]
It doesn't ignore some extensions that are created by editors, so it ends doing too much work.

For example, pycharm saves "foo.txt" as "foo.txt__jb_bak" and everything gets rebuilt twice :-P

**Comment by Kwpolska** [comment]
We could also make it so if an event was received before the last build started, it’s ignored.

**Comment by ralsina** [comment]
Sadly the events don't have a timestamp :-P

Maybe there is a way to consume the queue when we are abou to rebuild, but a quick look at the watchdog docs don't show it.
