### ISSUE TITLE
Animation of Animated GIFs being removed by build process

### ISSUE THREAD

**Issue by subject117** [getnikola/nikola#2750]
**Python Version:**
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00)
**Nikola Version:**
Nikola v7.8.4
**Operating System:**
Ubuntu 17.04

### Description:

When I deploy an Animated GIF in the `images/` folder it gets copied to the `output/` folder with the animation frames removed. The pixel dimensions are the same but the file size is smaller.

I can circumvent the problem by adding the same GIF to the appropriate location in the `files/` directory.

**Comment by ralsina** [comment]
Problem is when we load/save the image using Pillow we are removing all frames except the 1st one.

**Comment by subject117** [comment]
Thank you very much. Looking forward to the next release.

**Comment by ralsina** [comment]
You could apply the patch now, it's pretty simple :-)
