### ISSUE TITLE
Change drafts to be its own metadata instead of special tag

### ISSUE THREAD

**Issue by h4ckninja** [getnikola/nikola#2761]
For a future version, I'd like to see Nikola change the way it handles drafts.

Today, drafts are handled in a way that isn't as straight-forward to the user by having a special tag.

Instead, I'd like to see drafts defined by a separate piece of metadata:

~~~
.. title: My Super Title Here About Python
.. slug: my-super-title-here-about-python
.. date: 2017-05-13 00:00:00 UTC
.. tags: python, pip, venv
.. section: Developers
.. description: My Python Post
.. status: published
~~~

**Why?**

By having an explicit status of draft or published, and with a default set in `conf.py`, the user can clearly see that a post is published or not. As an example, `conf.py` may have a default post setting:

~~~
DEFAULT_POST_STATUS='draft'
~~~

"But tags already do that." Sort of. I see this as a combination of User Experience and a technical abstraction of post creation to be extensible. By keeping special meaning out of tags, users:

- won't accidentally remove a draft tag while editing their post (UX)
- the user has to explicitly say a post is ready to be published (or explicitly say it is draft) making it clear what's happening to the content (UX)
- this can later on allow extensible post compiling to do things like have separate configs for publishing for only posts that are marked as having a status of published by having a config for dev and a config for prod.

**Comment by felixfontein** [comment]
I'm in favor of this; I'd extend this to get rid of *all* special tags and use metadata instead. The other special tags besides `draft` I know of are `retired`, `private`, `mathjax`. (`retired` is marked as "remove in v8".)

Another (probably the main!) reason why I don't like the "use special tags as metadata" is that you cannot use these tags for real tagging. Like what if you want to have a tag `private` for posts about your private life? (As opposed to whatever else you're blogging about normally.) You simply cannot do that. Or if you write a post *about* mathjax and want to distinguish it from posts which *use* mathjax? No way to do that with tags. Or if you want to write a post about you being retired? You cannot use `retired` as a tag for that. Also, draft has [many different meanings](https://en.wikipedia.org/wiki/Draft), so you might want to tag a post with `draft` if it is about something in that list.

**Comment by felixfontein** [comment]
Out of curiosity: why are tags used for this in Nikola at all? I'd speculate that this is rooted in the old-style metadata, where text being on a specific line had a specific interpretation, so it wasn't easy/feasible to add extra metadata. But with modern metadata (`.. xxx: yyy`), that's not relevant anymore.

Anyway, if we decide to change this, we need to provide a conversion tool for users which rewrite metadata accordingly. Nobody wants to do that by hand for 100+ posts/pages.

**Comment by gour** [comment]
@felixfontein 
> Like what if you want to have a tag private for posts about your private life? (As opposed to whatever else you're blogging about normally.) You simply cannot do that. 

What about using category for that?

**Comment by felixfontein** [comment]
Categories are about to be deprecated. But then I could use sections.

And I know that I can use something else. It's just annoying that three is a (especially to the non-technical user) random choice of tags you simply cannot use as tags.

**Comment by ralsina** [comment]
@felixfontein yes, IIRC this is because old metadata was not flexible enough.

**Comment by felixfontein** [comment]
@ralsina: would you mind if all these special usages of tags are moved to proper metadata? Or just some of them?

**Comment by ralsina** [comment]
I don't mind if all get moved, except that, of course, we need to think of compatibility with existing installations.

We could do a once-only modification of the user's posts, or we could support both and mark for v8 removal of the tag support.

OTOH, I don't see us shipping v8 soon...

**Comment by felixfontein** [comment]
My idea would be to:
 - add support for both,
 - add config setting to disable old tags,
 - add post conversion tool,
 - print warnings for the old tags (when config setting is not set), point to automatic conversion tool,
 - remove support for old tags in v8 (but still include conversion tool, so that older blogs can be converted).
Does that sound good?

**Comment by ralsina** [comment]
+1

**Comment by Kwpolska** [comment]
Regarding post conversion, there’s the `upgrade_metadata` plugin written by yours truly, which could be extended/used as a base for this (and that is already advertised for old-style posts).

So, any takers?

**Comment by h4ckninja** [comment]
I can try my hand at it. I'll take a look at it tonight.

**Comment by h4ckninja** [comment]
While I'm working on the plugin and learning the internals, I was thinking about pulling the tags out to be the following. Please let me know if you disagree. I've outlined these in the format of `$tag => $metadata_name: $default_value`.

~~~
draft => status: draft
mathjax => mathjax: yes
private => private: yes
retired => private: yes
~~~

**Comment by Kwpolska** [comment]
Change 'mathjax' to 'math' or maybe 'has_math' (because we support KaTeX
and perhaps other engines in the future).

Also, I think using status: private will be more consistent (using private
and draft simultaneously doesn't sound useful to me)

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by h4ckninja** [comment]
>Change 'mathjax' to 'math' or maybe 'has_math' (because we support KaTeX and perhaps other engines in the future).

👍 

>Also, I think using status: private will be more consistent (using private and draft simultaneously doesn't sound useful to me)

Ahhhh, that makes sense. Sounds good to me.

**Comment by Kwpolska** [comment]
@h4ckninja, any progress on this?

**Comment by felixfontein** [comment]
> I've outlined these in the format of $tag => $metadata_name: $default_value.
> 
> ```
> draft => status: draft
> mathjax => mathjax: yes
> private => private: yes
> retired => private: yes
> ```

So the current map would be:

```
draft => status: draft
mathjax => has_math: yes
private => status: private
retired => status: private
```

I guess the default value (i.e. when not specified) for `status` should be `published` (or `publish`?), and the default value for `has_math` should be `no`.

**Comment by Kwpolska** [comment]
`published`, yes.

We could also support `status: private,draft` and `status: draft,private` (if mixing those makes a difference)

**Comment by felixfontein** [comment]
I don't think mixing makes sense. Draft posts are the same as private posts if `DEPLOY_DRAFTS` is `True`, and draft posts are not complied and put on the page if `DEPLOY_DRAFTS` is `False` (while private posts are). At least that's what I *thought* I understood; from the code (and tests), it looks like `DEPLOY_DRAFTS` is mostly ignored (except in `utils.clean_before_deployment`), so they are essentially the same.

**Comment by h4ckninja** [comment]
> @h4ckninja, any progress on this?

Yes. Sorry, I've been busy with $dayJob and some other things.

**Comment by felixfontein** [comment]
Any news on this @h4ckninja?

**Comment by Kwpolska** [comment]
@felixfontein, could you please do this?
