### ISSUE TITLE
Support for commento

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2773]
I know, I know, Yet Another Comment System. But hey:

* It's self hosted
* It takes like 30 seconds to get running via docker
* It looks easy to support

**Comment by Kwpolska** [comment]
Looks *very* immature with 62 commits and effectively one contributor.

**Comment by ralsina** [comment]
However I tried it and it works just fine.

**Comment by felixfontein** [comment]
For anyone else wondering what commento is: https://github.com/adtac/commento

A good summary of what it is and what it wants to achieve can be found in the [manifesto](https://github.com/adtac/commento/blob/master/manifesto.md).

**Comment by adtac** [comment]
Hello everyone! I'm the author of Commento and a Nikola user pointed me to this issue.

>Looks very immature with 62 commits and effectively one contributor.

Guilty as charged. At least before. These days, I'd say Commento is pretty mature and worth looking into once more. I've had several contributors from all around the globe help with refactors, build new features, tests, security reports, and other stuff. I'm still the major contributor, but there is a community around the project now.

About the stability of the software itself: I expect Commento to reach stable 1.0 very shortly. There are no API breakages or design changes planned until then.

>For anyone else wondering what commento is: https://github.com/adtac/commento

If you're looking for a demo: https://commento.adtac.pw/

>A good summary of what it is and what it wants to achieve can be found in the manifesto.

That link is now broken as I have moved the manifesto into the README itself.

If you have any questions about Commento, what's planned for the future, or any help integrating Commeto into Nikola, feel free to ask me.

**Comment by tritium21** [comment]
I think the stock response to supporting new comment systems is "Is there a way we can do this in plugins?"

**Comment by felixfontein** [comment]
@tritium21: the way commenting systems work in Nikola is that the theme templates must support them (if the templates use `comments_helper`, it suffices if the `base` theme supports them) explicitly for every commenting system; see https://github.com/getnikola/nikola/blob/master/nikola/data/themes/base/templates/comments_helper.tmpl
It would be nice if this could be improved upon so that you could add new commenting systems using plugins, but currently that's not possible.

**Comment by tritium21** [comment]
@felixfontein Oh, I am aware of that, and yeah, it makes plugins kinda painful.

The only way I could think of doing it is to have a registry of template files for plugins that gets passed to the renderer, have a template macro to load templates from that registry, and to have the plugin extend the template path.

That would be easier if there was only one template system, too.

**Comment by ralsina** [comment]
Ah, but plugins can provide templates!

We could have a plugin that provides the comments_helper bit at least, and we could change main.tmpl so it's smarter about how to load the comment system... hmmm.

**Comment by tritium21** [comment]
This has come up enough in issues that making main.tmpl a bit smarter might be worth looking into.

**Comment by ralsina** [comment]
Yup.

**Comment by gour** [comment]
Here is the data posted by Commento's author in Gitter:

| Parameter | Commento | Isso | Schnack |
| - | - | - | - |
| Latency (50% percentile) | 17 ms | 169 ms | 236 ms |
| Latency (99% percentile) | 132 ms | 664 ms | 313 ms |
| Requests per second | 21,764 RPS | 692 RPS | 3,392 RPS |
| Memory usage | 240 kB | 2.2 MB | 2.4 MB |
| Payload | 15.9 kB | 173 kB | 40 kB |

with the following comment:
> All these numbers are for servers hosted in localhost; admittedly it's not the real thing, but the scale of numbers is pretty damning

so it looks as another 'pro' for supporting Commento in Nikola.

**Comment by ralsina** [comment]
Now I also need to google what schnack is ;-)

**Comment by ralsina** [comment]
@adtac I just implemented this (sorry about the long periods of not doing anything about it) ... does commento support a link showing the number of comments in a post like Disqus does?

**Comment by adtac** [comment]
@ralsina not right now. But IIRC there's an issue open to allow for an API endpoint to query for the number of comments. I'll move it up my priority if there's enough interest :)

**Comment by ralsina** [comment]
Done.
