### ISSUE TITLE
Use a lightbox that doesn't require JQuery

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2777]
Now the base theme is using BaggetteBox.js

Still TBD:

- [x] Use captions
- [ ] Use it in bootstrap3
- [ ] Remove colorbox?

**Comment by Kwpolska** [comment]
(If we can find a flowr alternative that does not use jQuery, that would be great)

**Comment by ralsina** [comment]
PR #2929 does the rest of this issue.

**Comment by ralsina** [comment]
This is done.
