### ISSUE TITLE
Thumbnail too small for (very) wide images

### ISSUE THREAD

**Issue by StyXman** [getnikola/nikola#2780]
### Environment (if reporting a bug)

**Python Version:** Python 3.5

**Nikola Version:** 7.8.5

### Description:

Sometimes I stich images. The thumbnail generated is too small, for instance, in this case:

http://grulicueva.homenet.org/~mdione/nikola-gallery/galleries/Trips/2016/12-24%20-%20Isola%202000/

The thumbnail is 180px × 24px, but it's being shown (in my computer) with this CSS style:

`<div class="image-block" title="" data-toggle="tooltip" data-original-title="12 24t13 05 23" style="width: 1130px; height: 151px; margin-bottom: 5px; margin-left: 0px;"><a href="2016-12-24T13.05.23.jpg" class="image-reference cboxElement"><img src="2016-12-24T13.05.23.thumbnail.jpg" style="max-width: 100%;" height="151" width="1129"></a></div>`

so it's scaling it 6x at least. Maybe this could be fixed with a minimum height x width instead of width alone, but I understand it's a complex problem.

**Comment by ralsina** [comment]
right, yes, this can be special-cased. I'll take a look.

**Comment by ralsina** [comment]
Yes, this is a problem. I will take a look eventually.
