### ISSUE TITLE
Remove strange behavior of category and tag taxonomies which generate untranslated tag/category pages

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#2785]
This is caused by setting `also_create_classifications_from_other_languages = True` in a taxonomy plugin (which unfortunately is default right now). All core taxonomies except category and tag actively disable this.

I don't know why this was ever the behavior of tags and categories, and as mentioned in getnikola/plugins#229, I'd really like to disable this and remove the `also_create_classifications_from_other_languages` functionality in v8.

This issue is to discuss this (anyone wants to keep the current behavior? are there good reasons for it?) and so we won't forget.

**Comment by ralsina** [comment]
Probably because it's also default to show posts on languages for which they are not translated. If tag pages are not generated you may end up with a post linking to a tag which doesn't exist.

**Comment by felixfontein** [comment]
So you'd want tag pages generated for tags which are not translated. By why generate ALL tag pages, no matter whether they are ever used or not?

For tags, the code is already correctly determining which tags are actually in used (both by translated posts, and by untranslated posts if `SHOW_UNTRANSLATED_POSTS` is `True`; that's handled by `Post.tags_for_language` which is called by `ClassifyTags.classify`). For categories, it might some adjustment.

**Comment by ralsina** [comment]
@felixfontein suppose I have en and es languages. I write a post en-only but I want it to appear in the es version of the site, so I have SHOW_UNTRANSLATED=True. 

The post has tag en-tag. If I did not generate tag pages for it, then there would be a dead link in the post when it appears in the es-site, wouldn't it?

But hey, after all the taxonomy work I will be the 1st to accept I don't understand that code anymore, so if you say that would work, feel free to change it. As long as it does work, because what I just described is my site ;-)

**Comment by felixfontein** [comment]
For me, the code is only correct if it doesn't produce dead links. So yes, that should still work fine :)

I'll take a look at it later or so...

**Comment by felixfontein** [comment]
Ok, I did some tests with tags, categories, sections, and authors. If I set `also_create_classifications_from_other_languages = False` for tags and categories, everything works fine for all four taxonomies, EXCEPT that author pages, tags and categories include RSS links to ALL translations of the same tag name, which of course results in dead links when the tag names are not used in other languages.

This means in particular that the authors taxonomy is already broken right now, i.e. it generates broken links. To fix this, I'd prefer to get #993 merged first (or include it there) to avoid coding some stuff twice.

**Comment by ralsina** [comment]
Let's make this depend on #993 then, is that ok?

**Comment by ralsina** [comment]
Ok, I admit it, I just wanted to see how the dependency feature works.

**Comment by felixfontein** [comment]
Sure, make it dependent :)
