### ISSUE TITLE
Bower is deprecated

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2790]
Installing it, it says:

npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects! Please read our blog for more.

So, maybe someday, drop it.

**Comment by Kwpolska** [comment]
I had that on my task list. We’ll have to replace it one day by a bunch of node stuff (the Bower guys suggest Yarn + Webpack)

Why the JS folks change everything — package managers, client-side frameworks, entire server stacks — every week or so is completely beyond me.

**Comment by ralsina** [comment]
We can assume it will keep working for at least a year or so. And if it
stops updating all that happens is that we don't get newer JS, so who cares.

**Comment by fankertiban** [comment]
Javascript programmers with chopped off heads are able to continue writing a new JS-framework up to 20 minutes.
Sorry guys, but I couldn't resist the temptation to quote this joke. :-D
