### ISSUE TITLE
Email address obfuscation

### ISSUE THREAD

**Issue by max-arnold** [getnikola/nikola#2796]
I get lots of spam to my blog email address. Is there any way to insert JavaScript code into `CONTENT_FOOTER` instead of default plain text to hide `BLOG_EMAIL`? Right now I get this due to JS brace syntax:

```
ValueError: unexpected '{' in field name
```

I used these generators:

http://www.jottings.com/obfuscator/
http://hivelogic.com/enkoder/

**Comment by Kwpolska** [comment]
Use double braces `{{` and `}}`. We pass CONTENT_FOOTER through `str.format`, which uses `{}` as delimiters, so you need escaping like that.

**Comment by max-arnold** [comment]
Maybe it is worth to mention this in the docs? It would be great to prevent email exposure right from the start when someone just begins to configure his/her Nikola blog.

**Comment by Kwpolska** [comment]
I added a mention about how to use braces in `CONTENT_FOOTER`. Regarding obfuscation in docs: meh. Without something like reCAPTCHA’s or CloudFlare’s email obfuscation service, all those “obfuscators” are easily defeated with Selenium or otherwise running javascript in your bot. (And with CAPTCHAs, it takes pennies to hire a human CAPTCHA solver.)

**Comment by max-arnold** [comment]
Thank you Chris!

**Comment by ThomasJanotta** [comment]
Hi, I think he also means in the html-code (in normal texts), where an email appears. couldn't there be a (permanent) filter that obfuscates / converts this. the cms contao converts email-links to hexa-codes:

%61@%62%2ed&#x65;

**Comment by ralsina** [comment]
If you really really don't want to publish your email, don't publish it :-)

Most measures you can take that keep it published are defeatable by those who want to harvest it.

One possible alternative is to use a spam-protected contact form service, such as https://formspree.io/ or https://kontactr.com/
