### ISSUE TITLE
UnboundLocalError: local variable 'locale_n' referenced before assignment

### ISSUE THREAD

**Issue by x1101** [getnikola/nikola#2806]
### Environment (if reporting a bug)

**Python Version:**
% python --version                                                                                                                                                         
Python 3.6.1

**Nikola Version:**
Nikola==7.8.6

**Operating System:**
Arch Linux x86_64

### Description:
All nikola commands crash with the following error after upgrade to 7.8.6

```Traceback (most recent call last):
  File "/usr/bin/nikola", line 11, in <module>
    load_entry_point('Nikola==7.8.6', 'console_scripts', 'nikola')()
  File "/usr/lib/python3.6/site-packages/nikola/__main__.py", line 167, in main
    site = Nikola(**config)
  File "/usr/lib/python3.6/site-packages/nikola/nikola.py", line 902, in __init__
    self.config.get('LOCALES', {}), self.translations)
  File "/usr/lib/python3.6/site-packages/nikola/nikola.py", line 2758, in sanitized_locales
    locale_n = guess_locale_fom_lang(lang)
  File "/usr/lib/python3.6/site-packages/nikola/nikola.py", line 2829, in guess_locale_from_lang_posix
    if not locale_n.startswith(lang.lower()):
UnboundLocalError: local variable 'locale_n' referenced before assignment
```

If the following line is added the crash stops, but I don't know if its a good solution to the issue

```# Guess using locale.getdefaultlocale()
        try:
            # str() is the default string type: bytes on py2, unicode on py3
            # only that type is accepted by the locale module
            locale_n = str('.'.join(locale.getdefaultlocale()))
        except (ValueError, TypeError):
            pass
            locale_n = ""
```
The last line, defining `locale_n` as an empty sting is what's added here. This is at `2827` at least on my local copy of `nikola.py`

Please let me know if there's more information I can provide to clarify this issue

**Comment by Kwpolska** [comment]
Yeah, that’s a bug. Sorry, fixed on master.

Note that you should probably fix your [locale settings](https://wiki.archlinux.org/index.php/locale) (generate and set the appropriate locale).
