### ISSUE TITLE
uppercase slugs

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2807]
When trying to modernize the docutils site, I ran into a Nikola limitation:

There are files with names in upper case: README.txt but the slug will be "readme" which breaks the expected URL.

**Comment by felixfontein** [comment]
Cannot you get upper-case slugs when explicitly specifying a slug for a post/page?

And who is generating the broken link with the wrong slug? Is that docutils?

**Comment by ralsina** [comment]
This was when I was trying to port the docutils site.

Basically: they were keeping the filenames, so README.rst -> README.html and links were written accordingly, and I couldn't reproduce the behaviour because I did not want to assign slugs manually.

Anyway, that's dead, so closing.
