### ISSUE TITLE
Question: Do we need ID tags in h2 for Handbook page?

### ISSUE THREAD

**Issue by stefanos82** [getnikola/nikola#2811]
@ralsina Now that Nikola supports permalinks on header tags, do we need ID tags? 

For example, for **All You Need to Know** `h2` tag we have a link `https://www.getnikola.com/handbook.html#id11`, but right next to **Contents** sidebar, if we hover on **All You Need to Know** bullet point, we get the following link `https://www.getnikola.com/handbook.html#all-you-need-to-know` that matches the new permalink.

Should we consider ID tags as a deprecated feature or what is not removed by mistake?

Cheers.

**Comment by Kwpolska** [comment]
Those `#idXX` tags link back to the table of contents, and are created by of reST/docutils. `#all-you-need-to-know` is also created by reST, not Nikola — in case of reST documents, Nikola only adds the ¶ links. I don’t think any changes in this are necessary.
