### ISSUE TITLE
Make shortcode accessible from templates

### ISSUE THREAD

**Issue by xuhdev** [getnikola/nikola#2814]
Currently it seems no way (at least undocumented) to access shortcode from within templates themselves. It would be nice to have this feature.

**Comment by felixfontein** [comment]
I think it's not really feasible to use the same syntax as in posts in templates. That would require a *lot* of modifications to Mako *and* Jinja2 to get this working.

What *could* be done is providing a function in the global context which allows to execute shortcodes. That should actually be pretty simple; the hardest part is probably to determine how the `data` part should be passed.

**Comment by Kwpolska** [comment]
`data` is easy, just require it to be a keyword argument. The real problem is dependencies. I don’t think there’s a way for a global context function to set the dependencies for the output file.

But I’m not exactly sure, what use-case there is for shortcodes inside templates? Which shortcodes make sense in all files that use a template?

**Comment by felixfontein** [comment]
I guess that if you for example have created a shortcode which displays something (like an address) in your own personal style, you would also like to be able to use that shortcode to print your own address in the footer or sidebar or whereever. So I can see why one would want to do this.

And yes, dependencies probably won't work.

**Comment by Kwpolska** [comment]
If it’s a templated shortcode, you could just use the import system of your template handler (make a macro in foo.tmpl, import it in post.tmpl and shortcode.tmpl, run it in both).

**Comment by xuhdev** [comment]
@Kwpolska Can you show an example for that, please? Thank you! Perhaps it's worth to add to the document.

**Comment by Kwpolska** [comment]
Put shared code in templates/foo.tmpl, use a `<%namespace />` directive in templates/post.tmpl and shortcodes/foo_sc.tmpl, and call the macro defined in `foo.tmpl` in both templates. Shortcodes can import any template inside ``templates/`` and themes, and call any macros defined in those.

**Comment by ralsina** [comment]
To be honest, I am not even sure you can't use templates from shortcodes/ the same way.

**Comment by Kwpolska** [comment]
You can’t, Mako won’t let you use `../` in template includes, and shortcodes are not part of the template lookup.
