### ISSUE TITLE
jinja-themes broken without warning if parent-file exists 

### ISSUE THREAD

**Issue by t-animal** [getnikola/nikola#2816]
When a jinja-template contains a "parent"-file (how theme parents were handled before 7.8.6) referencing base-jinja nikola screws up templateing and renders the template-files instead of the actual content. Presumably it uses the mako engine to render the jinja templates.

This happens without a warning, website could be deployed completely broken without the user noticing unless they manually check the output-folder. This is probably affects all people who are using old-style parent-files with jinja templates.

Affects Nikola v7.8.6. Im running python3.6.1 on an arch linux.

**Comment by Kwpolska** [comment]
This happens when `engine` does not exist in the child theme. It used to work because `base-jinja` would provide a parent name, but that went out of the window when theme meta files were introduced. I’ll fix it tomorrow. (This might be fast-release-worthy.)
