### ISSUE TITLE
What category of plugins adds site data to global context?

### ISSUE THREAD

**Issue by leingang** [getnikola/nikola#2826]
I'm using a theme which has a lot of summary information on each page.  For instance:

* a count of the number posts, categories, and tags in the site
* a list of top tags, sorted by popularity

This is information which can be extracted from the main site object, but isn't available to the templates out of the box.  So, inspired by the [navstories](https://github.com/getnikola/plugins/tree/master/v7/navstories) config plugin, I wrote a few small plugins to pass this data to the site's global context.  Now I can access it in the templates.  

I'd like to contribute these plugins, but before I do I wanted to make sure my methods are sound.  Is this a good case of a Config plugin, or is a better suited as a Task or SignalHandler?

**Comment by Kwpolska** [comment]
ConfigPlugin would be the best. A task is something that has files as output, whereas a SignalHandler is best suited for well, signal handling. You can just create a simple ConfigPlugin with only a `set_site` method.

**Comment by leingang** [comment]
Thanks, that makes sense.  Sounds like I did the right thing.
