### ISSUE TITLE
[RFC] Metadata extraction plugins

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2830]
`get_meta` is complicated and hard to extend (eg. plugins.getnikola.com needs a special compiler to read meta). So, perhaps we could split this out into special plugins?

Some preliminary ideas:

* plugins can specify supported file formats (extensions)/compilers
* plugins can specify whether they should be used as fallback or not (eg. regex title/filename hacks)
* plugins can specify other characteristics (eg. first line of file)
* built-in stuff *should not* be real yapsy plugins for performance reasons (that would require reading way too many files)

**Comment by felixfontein** [comment]
Me too. I guess it is also related to #1278.
