### ISSUE TITLE
[v8] Merge categories and sections

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2833]
Sections are an unfinished feature:

* have no list of all sections page
* are sort-of tied to the filesystem
* don’t support nesting of any kind
* expect paths like `/foo/` *exactly* (sucks!), but can also be used from a meta field
* have some pretty weird code attached to them (section_slug)
* have a rather weird coloring feature that should not be specific to sections, and probably should not be on the post object

I propose the following in v8:

* drop sections altogether
* support getting category names from filesystem (optional feature), with support for hierarchies and prefixes (eg. `blog/foo` → `foo`, `blog/bar/baz` → `bar/baz`)
* accept `section` meta data as equivalent to `category` (?)
* support category indexes in `blog/foo/index.html` for fans of sections (?)

**Comment by ralsina** [comment]
I guess this means #2486 and #2484 are not needed anymore.

**Comment by Kwpolska** [comment]
And #2067 as well.
