### ISSUE TITLE
[discussion] Plugins

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#2836]
I'd like to start a discussion on two plugin-related points:

1. In #2820, @Kwpolska wrote "built-in stuff should not be real yapsy plugins for performance reasons (that would require reading way too many files)".

2. Some of my internal plugins have strong dependencies (one must be there for the other to make sense and actually work), and they also share code, which is pretty hard to implement if I don't want to fix where they are loaded from; I need to use the `inspect` module to find their location on disk and use `importlib.machinery` (Python 3) resp. `imp` (Python 2) to load the other file, and of course I have to assume that all plugin files are in the same directory.

I thought a bit about how to improve on this situation; here are two ideas:

a) Allow to inject plugins without yapsy. This could be done by Nikola core to add a bunch of plugins without the need to put them into own files (or even to define them in different files).

b) Allow bundled plugins (a new plugin type like `CombinedPlugins`), which are one yapsy plugin and which provide several Nikola plugins from one source file (or one package).

Both ideas would share some code in `nikola.py`, and only differ in how they are seen from the point of the `DISABLED_PLUGINS` config and the `plugin` command plugin. (Idea a) plugins should be treated as different ones, idea b) plugins as one big plugin.)

This would allow to keep a loose coupling of plugins, like for #2820, without the need to have too many plugin files. What do you think?

**Comment by ralsina** [comment]
Or we could drop Yapsy, if there's another better mechanism.

**Comment by felixfontein** [comment]
That's a possibility, too. I don't know any other and/or better system, though.

**Comment by ralsina** [comment]
There's this:

https://aroberge.blogspot.com.ar/2008/12/plugins-part-6-setuptools-based.html

**Comment by Kwpolska** [comment]
> 2008

Maybe not.

If we’re to change our system, there’s [straight.plugin](https://github.com/ironfroggy/straight.plugin) and [stevedore](https://github.com/openstack/stevedore).

**Comment by ralsina** [comment]
Well, stevedore is based on the same setuptools stuff :-)

Both are interesting!

**Comment by jean** [comment]
Another data point: https://github.com/NextThought/nti.nikola_chameleon#installation railing against `yapsy` in a rather persuasive manner. 
Setuptools _entry points_ (as used by `stevedore`) seem to me to be the most obvious Pythonic way to go.
Doesn't this sound lovely?

> Entry points are a simple way for distributions to “advertise” Python objects (such as functions or classes) for use by other distributions. Extensible applications and frameworks can search for entry points with a particular name or group, either from a specific distribution or from all active distributions on `sys.path`, and then inspect or load the advertised objects at will.
[ref](http://setuptools.readthedocs.io/en/latest/pkg_resources.html?#entry-points)

**Comment by Kwpolska** [comment]
> That makes it incredibly difficult to install plugins; it's not enough just to `pip install` a package from PyPI.

`pip install` is a no-go in my mind.

**Comment by jean** [comment]
What am I missing, why would `pip install` be a no-go?
I believe entry-points enables `pip install`, by making installed plugin modules discoverable via the registered namespaces.

**Comment by Kwpolska** [comment]
It litters the PyPI and adds all the complexity of running `pip` (virtualenvs/user installs/no sudo/distros may do weird stuff) to managing a page. There is also no way to make some plugins specific to a page.

**Comment by jamadden** [comment]
@jean I have no problems with stevedore. As I understand it, it reuses entry points, so it's compatible with PyPI and all the standard setuptools-based ecosystem. (Disclaimer: I haven't written anything that uses it.)

As a plugin user, I want to be able to use my tool of choice to manage all the dependencies of my site. That could be `pip --user`, `pip` + virtualenvs, `apt-get` or my system's standard package manager, or `pipenv` or `buildout`, or whatever else --- the ecosystem is both broad and evolving here. I also want to be able to browse for plugins on PyPI just like you can with, e.g., [Pelican](https://pypi.org/search/?q=&o=&c=Framework+%3A%3A+Pelican+%3A%3A+Plugins). I *don't* want to have to check in any Python code into my site.

As a plugin developer, I don't want to have to send a PR to a centralized github repo to enable usage of my plugin, especially if there's going to be code there that will have to be updated periodically as the rest of the plugin changes (`from external.module import *` is a poor workaround, ISTM). I want to be able to use the full power of setuptools (like `requires_python`) to ensure that users get correct code versions. I also want my code and its dependencies to be on `sys.path` so that all of the usual Python tools that use `sys.path` work as expected---`zope.configuration` being one example I ran into that breaks otherwise.

Don't get me wrong, I *adore* Nikola. It's working well for us, and we found a workaround to be able to manage our plugin in the way we're used to. We're a shop full of Python developers used to building and deploying production apps, though, so our usage and desires may not be typical of the whole audience. That, plus the fact that we haven't had any feedback from plugin users outside our immediate circle, is why we haven't tried to bring any of this up.

**Comment by jamadden** [comment]
> adds all the complexity of running pip...to managing a page. 

The [getting started documentation](https://getnikola.com/getting-started.html) is based on, or heavily promotes, virtualenv and pip:

> The best way to install Nikola is to use pip in a virtualenv.

**Comment by jean** [comment]
It doesn't _have_ to litter PyPI, you can give `pip` a filesystem path, a git repo URL, etc. 
Entrypoints don't have to come from separate repos either, e.g. here [avocado](https://github.com/avocado-framework/avocado/tree/master/examples/plugins) has some bundled in a subdirectory.
I also _like_ being able to search PyPI plugins. The Pelican example is good.

**Comment by jamadden** [comment]
> With stevedore, can I make it so a plugin is only installed for a specific Nikola site, without a separate virtualenv for said page?

If stevedore is based on pkg_resources and entry points, that means that it is based on `sys.path`, or, more generally, the pkg_resources working set/distribution model. So yes, that should be possible by manipulating one or the other of those things.

* he says, not having tried that specifically.

**Comment by schettino72** [comment]
Sorry for coming late to the discussion.
Not sure you guys are aware doit has its own plugin system [1].
Features:

- can mix core implementations and *real* plugins
- plugins are loaded (imported) only when required/used
- integrate (optionally) with pkg_resources
- non-core, non-pkg_resources plugins can be defined as a dict (in doit indirectly from INI ConfigParser)

Documentation about it is not great...
But it is under 100 lines of code and pretty straightforward IMO.
Just let me know if you have any questions.

[1] https://github.com/pydoit/doit/blob/master/doit/plugin.py

**Comment by Xeverous** [comment]
Posting on this - I have no knowledge of Plugins in Python but I'm interested in the issue.

I have same problem as @felixfontein - some of my plugins need to share some code. I don't understand the mentioned import hack, currently I'm unable to make my build work where 2 plugins import the same file. I either get an error that import is not found or that relative imports do not work outside packagaes. [More details in this reddit post](https://www.reddit.com/r/learnpython/comments/crsw49/sharing_python_code_between_multiple_yapsy/) - does Nikola support such thing? How should I share some code between Yapsy plugins inside Nikola?

**Comment by ralsina** [comment]
Plugins are plain python code. There are a number of ways to share code
between them.

You can even just put all the code in one plugin and import it from the
other.

The thing about "not a package": a package in python is just a folder with
a __init__.py in it (even an empty one) so maybe you are just missing one
of those somewhere along the way.

If you can share the code where you have the problem I can take a look into
making it work.

**Comment by Xeverous** [comment]
Clone this branch and try to build it. I can not find any way for `metadata.py` to be importable for plugins.

https://github.com/Xeverous/the_website/tree/feature-metadata-plugins

**Comment by Xeverous** [comment]
Good news: asked help from someone else and got a clean solution.

in `plugins/__init__.py` this needs to be added:

```python
import sys
import os
sys.path.append(os.path.abspath(os.path.dirname(__file__)))
```

Then, each file in `plugins` directory can do `import plugins.filename`.

**Comment by ralsina** [comment]
There is no metadata.py file in that branch.

But let's create one, and put it in plugins/metadata.py

In the plugin I tried

from plugins.metadata import foo

And that, surprisingly, failed! There are a number of tricks that could be
done to make this work, like sys.path editing but it's really not a great
situation.

In my (fuzzy, this project is pretty old!) memory I thought we were setting
the site's path as part of our import path, but I suspect we are not.

I can make that happen, in the meantime, you can just set PYTHONPATH=. (or
whatever) before calling Nikola

**Comment by Xeverous** [comment]
> There is no metadata.py file in that branch.

https://github.com/Xeverous/the_website/blob/feature-metadata-plugins/website/plugins/metadata.py ?

Anyway, I have found a workaround. See my previous comment. Note: in order for this to make an effect, I had to clean Python's caches.

**Comment by ralsina** [comment]
I think it's extremely unlikely that we will stop using Yapsy at this point.

**Comment by ralsina** [comment]
If someone comes up with a proper plan, that can be done without massive effort by someone else, let's reopen this.
