### ISSUE TITLE
Latex rendering broken after conversion of ipython notebooks

### ISSUE THREAD

**Issue by redwanhuq** [getnikola/nikola#2841]
### Environment (if reporting a bug)

**Python Version: 3.6.1**
**Nikola Version: 7.8.8**
**Operating System: Windows 10 Home 64-bit**

### Description: 

Just discovered that ipython notebooks converted by Nikola to HTML no longer render LaTeX. I only see the raw LaTeX after executing `nikola build` and serving the HTML locally. However, LaTeX renders just fine in the ipython notebook itself. I haven't changed any settings in conf.py for MathJax and never had any LaTeX rendering issues before.

Of note, the converted HTML posts on my [blog](http://inmachineswetrust.com) use MathJax v2.7.0, as found by inspecting the page source, and render Latex correctly; whereas newly generated, locally served HTML files use v2.7.1 and fail to render Latex. Digging a little deeper into the source, I found that the <script> tag for MathJax (`<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1...`) contains two attributes: `integrity` and `crossorigin`. It looks like these tags prevent accessing compromised CDN servers (https://github.com/sphinx-doc/sphinx/issues/3784). Manually removing these 2 tags fixes the problem entirely. On the other hand, the problem is also fixed if the 2 tags are left alone while using MathJax 2.7.0 instead of 2.7.1. 

Does Nikola automatically generate the hash for this integrity tag? If so, is it possible to update the tag since the MathJax version has changed (I'm not sure if the hash is linked to a specific version)? Or can the tags be excluded entirely during nbconversion?

**Comment by Kwpolska** [comment]
The hash is different for every version (just like for any other files). MathJax got upgraded to v2.7.0, but the hash was not changed due to oversight. There was also a change in KaTeX rendering that made it mostly unusable. I fixed both on the `v7-maintenance` branch as commit 8a339484. You can update templates manually — a Nikola release might take some time since we’re somewhere between v7 and v8.

Sorry for the inconvenience!

**Comment by redwanhuq** [comment]
No problem, an easy temporary fix 👍
