### ISSUE TITLE
Stop creating `archive.html` when `ARCHIVES_ARE_INDEXES` and `CREATE_FULL_ARCHIVES` are `True`?

### ISSUE THREAD

**Issue by felixfontein** [getnikola/nikola#2845]
Currently, when `ARCHIVES_ARE_INDEXES` and `CREATE_FULL_ARCHIVES` are set to `True`, a second index `archive.html` is created, which -- except its title -- is identical to the main index in `index.html`. Also, the parent archive navigation of f.ex. the 2017 index points not to the main index, but to `archive.html`.

This is kind of annoying, as there is no difference between `archive.html` and `index.html` (except the title maybe), so we have unecessary duplicated content where users end up when following archive navigation (assuming you don't have a direct link to `archive.html` in the sidebar/menu/whereever).

I propose that in this situation, we get rid of `archive.html`, and link to `index.html` instead.

**Comment by Kwpolska** [comment]
Perhaps we should warn users to disable the archive plugin and delete archive.html and any links themselves? Our current default config links to archives, for example, and some people may be unaware. And if you stop generating a file, it will have stale content from the last time the settings were different.

(It’s an edge case, and very far on that edge, mind you)

**Comment by felixfontein** [comment]
But that will generate no archives at all. I want archives, but not `archive.html`, which is superfluous when `ARCHIVES_ARE_INDEXES = True` and `CREATE_FULL_ARCHIVES = True` (but very much needed when not both are `True`).

**Comment by felixfontein** [comment]
I'm also happy with leaving this as it is; I've tried this out yesterday in a modified version of Nikola's archive taxonomy (with disabling the original) and I can also keep using the modified version for my special needs.

**Comment by Kwpolska** [comment]
The warnings should appear *only* if the user has this unusual combination. Those users don’t seem to want archives — but then why wouldn’t they just disable the plugin?

**Comment by felixfontein** [comment]
Oh, but these users *want* archives. Just not `archive.html`, but the year/month(/day) archives (as indexes).

**Comment by Kwpolska** [comment]
Let’s leave it as-is then.

**Comment by felixfontein** [comment]
Ok.
