### ISSUE TITLE
github_deploy shouldn’t fail if it can’t determine the source commit

### ISSUE THREAD

**Issue by asmeurer** [getnikola/nikola#2847]
[github_deploy](https://github.com/getnikola/nikola/blob/34e4767194c72c473ff4a31b9a8738f8cc6d662e/nikola/plugins/command/github_deploy.py#L128) tries to deploy from the branch specified by `GITHUB_SOURCE_BRANCH`, which [defaults](https://github.com/getnikola/nikola/blob/34e4767194c72c473ff4a31b9a8738f8cc6d662e/nikola/nikola.py#L620) to `master`. 

This doesn't make sense to me. The default behavior that I would expect would be to just deploy the current contents of the repo.

**Comment by Kwpolska** [comment]
`github_deploy` requires a special branching model. There are two branches, one for page source, and another for the page itself. By default, Nikola automatically commits to the source branch for you, so you can keep your site data in sync between different machines. If you don’t want this, just set `GITHUB_COMMIT_SOURCE` to False — but then you need to remember to do your own committing and take care of branches yourself.

**Comment by asmeurer** [comment]
This should at least be documented. `nikola github_deploy --help` says nothing about this.

**Comment by asmeurer** [comment]
I also really think that the default should be False for that variable. I don't really understand that use-case. To me, the purpose of `github_deploy` is to add the built pages to the `gh-pages` branch and push it up, nothing more.

**Comment by asmeurer** [comment]
OK, I tried setting that (is [this](https://github.com/asmeurer/blog/commit/671a86bd131578910a821c6c772746bae9d6b5b3) correct?), but I still get this, indicating it is trying to do stuff with the "source" branch.

```
nikola github_deploy
[2017-06-18T22:45:39Z] WARNING: Nikola: The COMMENTS_IN_STORIES option is deprecated, use COMMENTS_IN_PAGES instead.
[2017-06-18T22:45:41Z] WARNING: Nikola: The COMMENTS_IN_STORIES option is deprecated, use COMMENTS_IN_PAGES instead.
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Scanning posts............done!
.  render_posts:timeline_changes
Scanning posts............done!
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/doit/doit_cmd.py", line 167, in run
    return command.parse_execute(args)
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/doit/cmd_base.py", line 120, in parse_execute
    return self.execute(params, args)
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/nikola/plugin_categories.py", line 134, in execute
    return self._execute(options, args)
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/nikola/plugins/command/github_deploy.py", line 108, in _execute
    self._commit_and_push(options['commit_message'])
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/nikola/plugins/command/github_deploy.py", line 150, in _commit_and_push
    source_commit = uni_check_output(['git', 'rev-parse', source])
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/nikola/plugins/command/github_deploy.py", line 43, in uni_check_output
    o = subprocess.check_output(*args, **kwargs)
  File "/opt/python/3.6.1/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/opt/python/3.6.1/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'master']' returned non-zero exit status 128.
Note: checking out '671a86bd131578910a821c6c772746bae9d6b5b3'.
```

The context here is that I am trying to get my blog to deploy to gh-pages from Travis CI, which doesn't have `master` in this case because it's a different branch name that I'm building from.

**Comment by Kwpolska** [comment]
This is documented in the manual: https://getnikola.com/handbook.html#deployment

> GITHUB_COMMIT_SOURCE controls whether or not the source branch is automatically committed to and pushed. We recommend setting it to True, unless you are automating builds with Travis CI.

And we have a guide for Travis as well: https://getnikola.com/blog/automating-nikola-rebuilds-with-travis-ci.html

**Comment by asmeurer** [comment]
Well I did set GITHUB_COMMIT_SOURCE to False, and it still wants to commit use the source. So either the docs are wrong or there is a bug. I would prefer the latter interpretation because I would really like the command to be modified so that it doesn't use git for anything other than the gh-pages branch. 

And being documented in the manual is a lot less helpful than being documented in the command help. One is easy to find and the other is only found after a core developer points it out to you.

**Comment by Kwpolska** [comment]
Regarding the manual vs command line: documenting software is hard. We expect users to read the manual as well if they want to know more. The manual is also a place where we can describe everything in prose, not tied to config variables or commands.

Could you please show output from a session where `GITHUB_COMMIT_SOURCE = False` doesn’t work? What commands are displayed?

**Comment by asmeurer** [comment]
> Regarding the manual vs command line: documenting software is hard. We expect users to read the manual as well if they want to know more. The manual is also a place where we can describe everything in prose, not tied to config variables or commands.

Well you could at least link to the manual from the command line. 

> Could you please show output from a session where GITHUB_COMMIT_SOURCE = False doesn’t work? What commands are displayed?

See https://github.com/getnikola/nikola/issues/2847#issuecomment-309311127

**Comment by Kwpolska** [comment]
Ah, I see. This isn’t creating a new commit, it merely tries to grab the commit hash for the source commit. This should work if you’re running on the source (master) branch, because that’s the branch that’s just been cloned. Travis should be disabled for the deploy (gh-pages) branch.

**Comment by asmeurer** [comment]
That was the Travis "push" build. It also ran in the Travis "PR" build, which apparently does have a `master`, and it tried to run it from master (I know because it failed there, because of a fix I did in my branch for the newest version of Nikola). So the flag doesn't do at all what it says it does.

**Comment by Kwpolska** [comment]
Yes, it does. With the option enabled, the thing creates a commit with `git commit` et al [(lines 133-147)](https://github.com/getnikola/nikola/blob/34e4767194c72c473ff4a31b9a8738f8cc6d662e/nikola/plugins/command/github_deploy.py#L133-L147). But regardless of that setting, we use `rev-parse` to get the latest commit hash to use in the commit message. Your scenario and usage is kinda unusual (using different branches and some third-party tool). Since that source check is not important, we could make failure non-fatal.

**Comment by asmeurer** [comment]
I've ditched using github_deploy for Travis (I'll still use it for deploying locally, if I ever decide to do that). It is trying to be too smart, and all it really needs to do is sync files from `output/` to the `gh-pages` branch, which [doctr](https://drdoctr.github.io/doctr/), the tool I wrote, already does. 

I wrote [a post](https://drdoctr.github.io/doctr/) on how I am deploy my site. I much prefer it to the method outlined in [your docs](https://getnikola.com/blog/automating-nikola-rebuilds-with-travis-ci.html) because doctr handles all the SSH key stuff for you, and also the syncing. 

I still think that github_deploy should (by default) just deploy the files as they are, i.e., even if there are uncommitted files they should be built and deployed.

**Comment by asmeurer** [comment]
@Kwpolska what about the other issues here?

**Comment by Kwpolska** [comment]
What issues? `github_deploy` DOES NOT change branches nor commit anything if the option is disabled. We use `ghp-import` to do all the heavy lifting, and AFAIK it shouldn’t force any branching either. The last commit should fix the crash you had in https://github.com/getnikola/nikola/issues/2847#issuecomment-309311127.

**Comment by asmeurer** [comment]
You can tell me if I enabled the [option wrong](https://github.com/asmeurer/blog/blob/199d8e73595ba550b3911a080900055a973d32bb/conf.py#L23), but that's not what I saw. I'll test it again later.

There's also the documentation issue.

And lastly, I really think the defaults should change here.

**Comment by Kwpolska** [comment]
> You can tell me if I enabled the option wrong, but that's not what I saw. I'll test it again later.

You’re confusing two things here. Nikola tries to fetch the commit hash from the source branch. I made failures to do that non-fatal in #2848 . If the auto-commit mode is enabled, you would see something like `==> ['git', 'checkout', 'master']` in output — and that did not appear.

> There's also the documentation issue.

I’ll add a link to the manual to `nikola help github_deploy`. (The online manual is better for showing long docs, plus it’s less documents to keep it in sync.)

> And lastly, I really think the defaults should change here.

I disagree. The default is handy for users of `github_deploy` who use the command manually. And you need to configure `github_deploy` to get it to work anyway.

**Comment by asmeurer** [comment]
OK, I took a deeper look and I think another part of my build was checking out master.
