### ISSUE TITLE
theme blogtxt does not support image galleries

### ISSUE THREAD

**Issue by x1101** [getnikola/nikola#2859]
Per the theme's README, it does not support image galleries.

>README.md: This theme doesn't support slides or image galleries in any useful way.

When rendering a gallery, the entire section is wrapped in `<noscript>` tags, as seen [here](https://urandom-podcast.info/galleries/screen_test/)

**Comment by ralsina** [comment]
There is no reason why it shouldn't now since current image galleries don't depend on JQuery anymore. Can you check if the theme has a gallery.tmpl in it, and what happens if you remove it?

**Comment by x1101** [comment]
Here's what's in the theme directory. No `gallery.tmpl`. But I installed this theme _ages_ ago. I can always try to remove and reinstall it.

```themes/blogtxt/templates  master ✔                                                                                              9d
▶ ls -1
base.tmpl
index.tmpl
post.tmpl
```

**Comment by Kwpolska** [comment]
The gallery template requires the extra_js` block, which is not present in `blogtxt`.

**Comment by ralsina** [comment]
Fixed.
