### ISSUE TITLE
Tumblr importer

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#286]
Tumblr doesn't seem to offer a reasonable export feature. 

But they have a decent API.

**Comment by e2jk** [comment]
I hadn't noticed there was a Tumblr plugin, but I used the [Edison](https://github.com/DoctorMalboro/Edison) project which, after some small tweaking, allowed me to import all Tumblr-published posts into Nikola. Just mentioning it here, should anyone else need it.
