### ISSUE TITLE
SNAP: Unable to use "commonmark" instead of "markdown"

### ISSUE THREAD

**Issue by uli-heller** [getnikola/nikola#2867]
### Environment (if reporting a bug)

**Python Version:** 3.5

**Nikola Version:** v8-dev

**Operating System:** Ubuntu-14.04 using a snap created on ubuntu-16.04

### Description:

* `snap run nikola` ... shows usage information
* `snap run nikola build` ... works for an standard site
* `snap run nikola build` ... does not work when activating "commonmark" in conf.py
* `nikola build` ... works OK when using a version installed in a virtualenv

Details:

```
uli@ulinuc:~/git/pag/nikola-pag-webpp-betrieb-intern$ snap run nikola build
2017/07/16 18:46:25.048376 cmd_run.go:275: WARNING: XAUTHORITY environment value is not a clean path: "/run/gdm/auth-for-uli-kiCwqE/database"
[2017-07-16T16:46:26Z] WARNING: Nikola: The UNSLUGIFY_TITLES setting was renamed to FILE_METADATA_UNSLUGIFY_TITLES.
[2017-07-16T16:46:26Z] WARNING: Nikola: Could not guess locale for language de, using locale en_US.UTF-8
[2017-07-16T16:46:26Z] WARNING: Nikola: Please fix your OS locale configuration or use the LOCALES option in conf.py to specify your preferred locale.
[2017-07-16T16:46:26Z] WARNING: Nikola: Make sure to use an UTF-8 locale to ensure Unicode support.
Scanning posts........done!
.  render_posts:cache/posts/zertifikat-verlaengern.en.html
########################################
TaskError - taskid:render_posts:cache/posts/zertifikat-verlaengern.en.html
PythonAction Error
Traceback (most recent call last):
  File "/snap/nikola/x1/lib/python3.5/site-packages/doit/action.py", line 403, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/snap/nikola/x1/lib/python3.5/site-packages/nikola/post.py", line 576, in compile
    lang)
  File "/snap/nikola/x1/lib/python3.5/site-packages/nikola/plugin_categories.py", line 306, in compile
    raise NotImplementedError()
NotImplementedError
```

**Comment by uli-heller** [comment]
Maybe I do have some misunderstandings on what happens during plugin installation.
Currently, it seems that
* some modifications are done within the plugins folder of the site
* additional modifications are done within the virtualenv/snap of the nikola installation
Since snaps are probably read-only, this cannot work.

**Comment by ralsina** [comment]
Snap installation gives you a rather constrained environment, so some functionality may fail, specially since noone has tried this specific thing before :-)

I can debug it but don't expect a very quick fix. in the meantime you can continue using the version from your virtualenv, or maybe install the snap using --devmode.

In fact, I am thinking it may make sense to make nikola a "--classic" snap which should fix most of these things.

**Comment by uli-heller** [comment]
I checked with `--devmode` roughly half an hour ago. It doesn't work either.

I'll create a private snap next which contains the commonmark plugin. If this works, I'll be happy for now. And maybe the issue cannot be solved in a better way if this is true since you cannot modify the content of a snap once it is created (... according to my knowledge).

I'll post my updates to this ticket.

**Comment by Kwpolska** [comment]
This is an issue with the `commonmark` compiler, actually. There was an API change this plugin is not compatible with (and you are using Nikola v8-dev from `master`)

**Comment by uli-heller** [comment]
Thanks for giving this hint! I'll have to double check, my assumptions seem to be totally wrong :(

* I downloaded the 7.8.9 tarball
* I created the SNAP within the extracted download
* So I assumed the SNAP is based on 7.8.9

**Comment by uli-heller** [comment]
OK, now I see:

```
...
    nikola:
        source: git://github.com/getnikola/nikola.git
...
```

So the latest version from git gets into the snap.

**Comment by uli-heller** [comment]
Now I've created a 7.8.9 snap. I see this error message:

```
...
.  render_galleries:output/en/galleries/rss.xml
.  render_posts:timeline_changes
.  render_posts:cache/posts/zertifikat-verlaengern.html
[2017-07-17T06:34:21Z] ERROR: Nikola: In order to build this site (compile with CommonMark), you must install the "commonmark" Python package.
[2017-07-17T06:34:21Z] ERROR: Nikola: Exiting due to missing dependencies.
```

**Comment by ralsina** [comment]
It's supposed to get git master into edge, but only releases are manually
promoted to the stable channel.

**Comment by uli-heller** [comment]
I have created a snap that works. Basically:

* Use nikola-7.8.9 instead of head of the master
* Add "commonmark" to python-packages within snapcraft.yaml

I think you cannot use this approach for a generic snap, since most people probably don't want to
use commonmark. Upon request, I can provide a pull request or a patch.

**Comment by ralsina** [comment]
The snap comes with most common plugins builtin because I have not really tried installing any extras.

I assume it's going to run into some confinement issues for any plugins that have dependencies (pure python plugins may actually work)

**Comment by ralsina** [comment]
Ok, in general, all plugins with python dependencies will fail because the snap doesn't have permission to read /etc which pip requires.

**Comment by uli-heller** [comment]
What is our strategy related to this?

* Add all potential python dependencies to the snap in advance so it will work with most of the plugins?
  (This is what I currently do within my fork)
* Try to find a way to install python dependencies to the snap afterwards?
  (This might be impossible to do, I'm keeping an eye on this...)

Please note: There are other issues with the snap, for example `nikola deploy`. Even installing openssh-client within the snap doesn't fix the rsync issues probably due to access restrictions to ~/.ssh/config.

**Comment by ralsina** [comment]
Yes, calling external tools is just not practical from a snap.

I will probably change it to a "classic" confinement snap. That involves manual review to get in the store, but it should fix all the problems and still provide a simple way to install nikola.

**Comment by uli-heller** [comment]
I've tried to create a classic confinement snap by  changing one 
parameter within the snapcraft.yaml.

Unfortunately, the resulting snap does not work at all:

```
uli@ulinuc:~/git/pag/nikola-pag-webpp-betrieb-intern$ nikola build
2017/07/28 06:23:55.200348 cmd_run.go:275: WARNING: XAUTHORITY 
environment value is not a clean path: 
"/run/gdm/auth-for-uli-AGH3Bz/database"
Traceback (most recent call last):
   File "/snap/nikola/x3/bin/nikola", line 6, in <module>
     from pkg_resources import load_entry_point
   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in 
<module>
     working_set = WorkingSet._build_master()
   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in 
_build_master
     ws.require(__requires__)
   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in 
require
     needed = self.resolve(parse_requirements(requirements))
   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in 
resolve
     raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: Nikola==7.8.9
```

-- 
Uli Heller

daemons point Gesellschaft für Datenverarbeitung mbH
Zahn-Nopper-Straße 1-3, 70435 Stuttgart
Internet: www.daemons-point.com
Mobil: +49 17273 05646, Tel: +49 711 806708 0, Fax: +49 711 806708 19
mailto:uli.heller@daemons-point.com

**Comment by ralsina** [comment]
@uli-heller There are a bunch of hacks that need to be reconsidered to do that.

**Comment by ralsina** [comment]
I have started the process to turn nikola into a "classic" snap and it's just too annoyingly bureocratic, so I whitdrew it. Screw snaps.

**Comment by ralsina** [comment]
84b0c62311547f81401fa1f5802d945872e2b20d
