### ISSUE TITLE
shortcode for equivalent of ReST listing directive

### ISSUE THREAD

**Issue by RobinD42** [getnikola/nikola#2868]
Feature request:  It would be very nice to be able to have a shortcode that would enable the equivalent of the `.. listing::` ReST directive for the other compilers. Most of my existing docs are in Markdown and converting one to ReST in order to add a listing seems like it shouldn't be necessary.

**Comment by ralsina** [comment]
https://github.com/getnikola/nikola/pull/2880/

**Comment by Kwpolska** [comment]
Fixed in #2880.
