### ISSUE TITLE
Latex rendering problem in markdown format

### ISSUE THREAD

**Issue by bebound** [getnikola/nikola#2870]
### Environment (if reporting a bug)

**Python Version:3.5.2

**Nikola Version:7.8.9

**Operating System:macos

### Description:

I have a problem when trying to render this latex expression: 
`$$T_{ij}=P(j \rightarrow i)=\frac{w_{ij}}{\sum^{l+u}_{k=2}w_{kj}}$$`

This will convert to `$$T_{ij}=P(j \rightarrow i)=\frac{w_{ij}}{\sum^{l+u}<em kj>{k=2}w</em>}$$` in HTML. Hmm, it looks weird... especially this tag: `<em kj>`

Is there any simple way to make it works? Such as stop convert md to html in `$$` tag. Thank you.

My mathjax conf is 
```
MATHJAX_CONFIG = """
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
    tex2jax: {
        inlineMath: [ ['$','$'], ["\\\(","\\\)"] ],
        displayMath: [ ['$$','$$'], ["\\\[","\\\]"] ],
        processEscapes: true
    },
    displayAlign: 'left', // Change this to 'center' to center equations.
    "HTML-CSS": {
        styles: {'.MathJax_Display': {"margin": 0}}
    }
});
</script>
"""
```

**Comment by ralsina** [comment]
You want to make sure markdown doesn't alter your math.

One way to do that, IIRC is to wrap it in a ``<div>`` tag, which makes markdown ignore the content. For inline math, maybe ``<span>`` tag can do the same thing

**Comment by bebound** [comment]
@ralsina  Thanks, the `div` tag works.
