### ISSUE TITLE
Nikola is not detecting dependencies when installed in Anaconda 

### ISSUE THREAD

**Issue by mfcabrera** [getnikola/nikola#2871]
### Versions

Pytho version: Python 3.6.1 :: Anaconda 4.4.0 (x86_64)
conda 4.3.21
Nikola==7.8.9
`which nikola` /Users/miguel/anaconda3/bin/nikola
`which ipython` /Users/miguel/anaconda3/bin/ipython
Mac OSX 10.12.5 (16F73)

### Description:
When I install Nikola with all the dependencies I get the following messages:

```$ nikola build
[2017-07-17T13:15:11Z] WARNING: Nikola: In order to USE_BUNDLES, you must install the "webassets" Python package.
[2017-07-17T13:15:11Z] WARNING: bundles: Setting USE_BUNDLES to False.
Scanning posts.....[2017-07-17T13:15:11Z] ERROR: Nikola: In order to build this site (compile ipynb), you must install the "notebook>=4.0.0" Python package.
[2017-07-17T13:15:11Z] ERROR: Nikola: Exiting due to missing dependencies.

$ nikola console
[2017-07-17T13:16:05Z] WARNING: Nikola: In order to USE_BUNDLES, you must install the "webassets" Python package.
[2017-07-17T13:16:05Z] WARNING: bundles: Setting USE_BUNDLES to False.
Scanning posts.....[2017-07-17T13:16:05Z] ERROR: Nikola: In order to build this site (compile ipynb), you must install the "notebook>=4.0.0" Python package.
[2017-07-17T13:16:05Z] ERROR: Nikola: Exiting due to missing dependencies.
```

I install all the required dependencies but Nikola does not seem to pick them from the Anaconda root environment or any other. 

```
$ pip freeze | grep webassets
webassets==0.12.1
$ pip freeze | grep watchdog
watchdog==0.8.3
$ pip freeze | grep notebook
notebook==5.0.0
```

Any hints?

**Comment by Kwpolska** [comment]
Please test with absolute paths:

```
/Users/miguel/anaconda3/bin/pip freeze | grep webassets
/Users/miguel/anaconda3/bin/nikola console
```

Nikola’s “detection” is really attempting `import webassets` (or whatever) and showing a warning when imports fail. Perhaps your `pip` installs things somewhere else? Or your Anaconda has some path issues?

**Comment by mfcabrera** [comment]
This is a strange behavior:

```
$ /Users/miguel/anaconda3/bin/pip freeze | grep webassets
webassets==0.12.1 

$ which nikola
/Users/miguel/anaconda3/bin/nikola

$ nikola console
[2017-07-17T18:06:49Z] WARNING: Nikola: In order to USE_BUNDLES, you must install the "webassets" Python package.
[2017-07-17T18:06:49Z] WARNING: bundles: Setting USE_BUNDLES to False.
Scanning posts.....[2017-07-17T18:06:50Z] ERROR: Nikola: In order to build this site (compile ipynb), you must install the "notebook>=4.0.0" Python package.
[2017-07-17T18:06:50Z] ERROR: Nikola: Exiting due to missing dependencies.

$  /Users/miguel/anaconda3/bin/nikola console
Scanning posts..............done!
Python 3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09)
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.


Nikola v7.8.9 -- IPython Console (conf = configuration file, site = site engine, commands = nikola commands)

```

So if I use the full path it works. Otherwise it fails. This is a fresh Anaconda installation so I don't belive there is an issue with it.

Any ideas? Or should I use full path from now on?

**Comment by Kwpolska** [comment]
This is pretty strange, but not a Nikola bug.

* Could you try removing Nikola (using `Users/miguel/anaconda3/bin/pip uninstall -qy Nikola`)? What happens in that case?
* What is your `$PATH`? Have you got any unusual aliases for `nikola` in your shell? 
* [Do you really need Anaconda?](https://chriswarrick.com/blog/2017/07/03/setting-up-a-python-development-environment/#distributions) A much better option would be to install Python 3 from Homebrew, a virtualenv, and then install Nikola.

**Comment by mfcabrera** [comment]
Hi!
I found the issue. I found a `/user/local/bin/nikola` binary. (I don't know where it came from). I deleted nikola, that binary and re-installed and it worked. Thanks a lot.

**Comment by Kwpolska** [comment]
This is pretty strange behavior nevertheless.
