### ISSUE TITLE
Plugin with a path handler generating external links

### ISSUE THREAD

**Issue by vkazanov** [getnikola/nikola#2876]
### Description:
I wanted to write a plugin allowing me register a path handler which would give me a possibility to share a bibliography of useful externals links between posts.

For example:
```rst
__ link://biblio/linkname ---> https://some.random.site.com/path/to/resource
```
Turns out, judging by the Nikola code, path handlers are only able to generate internal links, which makes the whole link handler mechanism useless for the case.

Is there a way I can help with developing the feature? Or is there an alternative approach to the problem?

**Comment by Kwpolska** [comment]
I think we can modify `Nikola.path` (and possibly `Nikola.link`) to behave differently if the path handler returns a single string instead of a list/tuple. And yes, we welcome contributions from all users, so if you’re willing to do it — please go ahead!

**Comment by ralsina** [comment]
If you are using reStructured text, the suggested answer would be a custom role.

In general, you could use a templated shortcode, it's pretty simple and requires no code.

But yes, it's intriguing if we could provide

**Comment by vkazanov** [comment]
That was fast! :-)

Anyways, I am looking at the code of `Nikola.path` right now. AFAICS, it should be almost trivial to just check if the return value is a string (using `isinstance(path, str)`) and immediately return it.

Am I missing something here..?

**Comment by vkazanov** [comment]
@ralsina Yes, sure, a shortcode is an option but using the path handler mechanism just feels right here.

**Comment by ralsina** [comment]
@vkazanov yeah, that should work. Feel free to PR :-)

**Comment by vkazanov** [comment]
Great! I'll take a look at it.

**Comment by vkazanov** [comment]
Here you go :-)
