### ISSUE TITLE
slides don't work

### ISSUE THREAD

**Issue by mandarup** [getnikola/nikola#2877]
### Environment (if reporting a bug)

**Python Version:**
3.5

**Nikola Version:**
latest

**Operating System:**
ubuntu 16.04

### Description:
slides appear one below other 

![nikola-slides-bug](https://user-images.githubusercontent.com/6325708/28496116-22943986-6f31-11e7-9ecd-25aa8ef0a05d.png)

**Comment by Kwpolska** [comment]
slide support is theme-dependent. Try with `bootstrap3` — if it works there, it means that your theme needs to be changed to support slides.

**Comment by ralsina** [comment]
Also, slides were removed to a plugin :-)
