### ISSUE TITLE
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcd5' in position 2003: surrogates not allowed

### ISSUE THREAD

**Issue by aaawzyaaa** [getnikola/nikola#2891]
**import matplotlib.pyplot as plt
import tensorflow as tf   
import numpy as np
image_raw_data = tf.gfile.FastGFile("path/to/picture",'r').read()

with tf.Session() as sess:
    img_data = tf.image.decode_jpeg(image_raw_data)
    # 输出解码之后的三维矩阵。
   print (img_data.eval())

### Environment (if reporting a bug)

**Python Version:**

**Nikola Version:**

**Operating System:**

**Comment by Kwpolska** [comment]
This is a support forum for Nikola, a static site generator — not matplotlib, tensorflow, or numpy. Please find the correct place for your question. If this is Nikola-related, please provide additional context.
