### ISSUE TITLE
selecting metadata format in new_post

### ISSUE THREAD

**Issue by gour** [getnikola/nikola#2893]
Hello,

it would be nice if `new_post` command would have option to select which metadata format to use?

**Comment by Kwpolska** [comment]
What’s the point? Most people will either stick to the default, or set something custom for all new posts as `METADATA_FORMAT`.

**Comment by gour** [comment]
> What’s the point? 

I want to submit/share article/post to someone's blog which does not support  reST and uses e.g. TOML as default while in NIkola I set YAML as METADATA_FORMAT.

The logic is similar as to being able to use different markup per post...

**Comment by ralsina** [comment]
Adding an option to new_post is cheap. PR coming up.
