### ISSUE TITLE
METADATA_FORMAT is not honoured for Asciidoc markup

### ISSUE THREAD

**Issue by gour** [getnikola/nikola#2894]
### Environment (if reporting a bug)

**Python Version:**
Python 3.6.2 (default, Aug 11 2017, 11:59:59) 
[GCC 7.1.1 20170622 (Red Hat 7.1.1-3)] on linux

**Nikola Version:**
Nikola v8.0.0.dev0

**Operating System:**
(Fedora f26) x86_64 GNU/Linux

### Description:

Despite of `METADATA_FORMAT = "YAML"` setting, `nikola new_post  blog/test.adoc` does create post with 'default' markup:

```
////
.. title: Test
.. slug: test
.. date: 2017-09-04 10:02:47 UTC+02:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

////

Write your post here.```

**Comment by Kwpolska** [comment]
YAML won’t work nicely with the asciidoc plugin as-is, since we don’t use `split_metadata` there. Doing that would require writing to a temporary file first (after split_metadata and extracting shortcodes). (Patches welcome, as always.)

The issue is caused by using old-style APIs though.

**Comment by gour** [comment]
> YAML won’t work nicely with the asciidoc plugin as-is, since we don’t use split_metadata there. 

What does it mean 'nicely'?

I've tried in `Nikola v8.0.0.dev0` containing your latest plugin-V8 stuff and it behaves OK.

> The issue is caused by using old-style APIs though.

Is this going to be fixed/improved in V8?

**Comment by Kwpolska** [comment]
>> YAML won’t work nicely with the asciidoc plugin as-is, since we don’t use split_metadata there.
What does it mean 'nicely'?
>I've tried in Nikola v8.0.0.dev0 containing your latest plugin-V8 stuff and it behaves OK.

How is this post handled by YAML + asciidoc?

```
---
title: "foo"
slug: "foo"
date: "2017-09-04 15:10:00 UTC"
---
test post
```
>> The issue is caused by using old-style APIs though.
>Is this going to be fixed/improved in V8?

The plugin needs changing.

**Comment by gour** [comment]
> How is this post handled by YAML + asciidoc?

Ahh, you're correct. I was focusing whether Nikola can build without errors, but, indeed, rendering is bad. 😞

**Comment by ralsina** [comment]
@gour the change in the plugin is really really simple if you want to take a crack at it. If you don't I can do it.

**Comment by gour** [comment]
@ralsina I'm not using Nikola any longer. :-(

**Comment by ralsina** [comment]
@gour ok then!

**Comment by ralsina** [comment]
Fixed.
