### ISSUE TITLE
Nikola init asks twice for blog destination

### ISSUE THREAD

**Issue by max-arnold** [getnikola/nikola#2895]
### Environment (if reporting a bug)

**Python Version:**

3.6

**Nikola Version:**

7.8.9

**Operating System:**

Mac OS

### Description:

Minor bug: `nikola init` asks twice for blog destination:

```
 % nikola init
[2017-09-04T14:17:30Z] WARNING: Nikola: In order to USE_BUNDLES, you must install the "webassets" Python package.
[2017-09-04T14:17:30Z] WARNING: bundles: Setting USE_BUNDLES to False.
Creating Nikola Site
====================

This is Nikola v7.8.9.  We will now ask you a few easy questions about your new site.
If you do not want to answer and want to go with the defaults instead, simply restart with the `-q` parameter.
--- Questions about the site ---
Destination: blog
Destination: blog
Site title [My Nikola Site]:
```

**Comment by Kwpolska** [comment]
I can’t reproduce (macOS Sierra, Python 3.6.2 from Homebrew). Does it happen on any further events?

**Comment by Kwpolska** [comment]
I can’t reproduce (macOS Sierra, Python 3.6.2 from Homebrew). Does it happen on any further attempts?

**Comment by max-arnold** [comment]
I use python from macports, and it looks like this issue is caused by default python build with libedit. I recompiled both python27 and python36 with readline and installed py27-readline and py36-readline and it solved the issue:

```
sudo port install python27 +readline py27-readline python36 +readline py36-readline
```
