### ISSUE TITLE
Support hiding post-list in teaser

### ISSUE THREAD

**Issue by mprasil** [getnikola/nikola#2896]
### Description:
It would be nice if there was an option to hide post-list in the teaser, so that I can add it to the top of the post, but it would be only rendered when directly reading the post, not in the index teaser.

**Comment by ralsina** [comment]
Just put it after the tease-end marker.

**Comment by mprasil** [comment]
Well that's obvious solution, however I'd like to use it right at the top. Something like "hey this post is part of series of articles, you might want to check previous parts first"

It makes sense to have that at the top rather than further down the post after teaser break.

**Comment by Kwpolska** [comment]
We render the post only once, so we can’t do it at the render step. You can, however, do something else: duplicate the teaser text, and only render the “main” post on post pages. [Here’s my code that does some different magic to the teaser.](https://github.com/Kwpolska/chriswarrick.com/blob/3a4b2fc742affe7a65e901d4f6f69e67912902c9/conf.py#L615-L629)

**Comment by mprasil** [comment]
Oh I haven't realized the post is only rendered once. Always thought it's rendered in teaser and full form separately. 

I like your solution, perhaps I can even parse out the post-list so I don't have to duplicate the teaser text. Alternatively I can just hide the post-list via css.

**Comment by ralsina** [comment]
There are several  options :-)

I will close the issue, feel free to reopen if you run into trouble.
