### ISSUE TITLE
Support single language sites with occasional different language posts

### ISSUE THREAD

**Issue by jcea** [getnikola/nikola#2901]
My blog is written mainly in Spanish but I publish English only posts from time to time.

Nikola multilanguage sites are not appropriate because not every article is translated. In fact there are no translated articles at all: most articles are written in Spanish and some are written in English, with no Spanish translation at all.

Would be really nice if nikola supports this. Currently if I write a post in English, tags like "warning" or "source code" are translated to Spanish.

If posts could have a metadata tag for language, with default being "site wide default language", would be nice.

Thanks.

**Comment by michaelb42** [comment]
What about this section from conf.py?
```
# If this is set to True, the DEFAULT_LANG version will be displayed for
# untranslated posts.
# If this is set to False, then posts that are not translated to a language
# LANG will not be visible at all in the pages in that language.
# Formerly known as HIDE_UNTRANSLATED_POSTS (inverse)
SHOW_UNTRANSLATED_POSTS = True
```
Regards.

**Comment by Kwpolska** [comment]
Sorry, that won’t cut it. If those posts were English-only, they would not appear on the default Spanish site, archives, feeds, severely impacting discoverability of those posts. There would be an English link in the navbar to a desolate place with only a few entries, and some files/parts of the site would be needlessly duplicated

**Comment by michaelb42** [comment]
Hm, nikola *single* language sites do not support posts in different languages, but multi language sites may be configured to
- show untranslated posts in all languages
- show untranslated posts in recent posts list, archive, etc. for all languages
- have a default language
Files of untranslated posts will be duplicated, but that's the way a multi language site is supposed to work and should be no real problem.

**Comment by jcea** [comment]
I would like to be able to post a english article from time to time, when 99% of my posts are in spanish. This is not a multilanguage site, it is a spanish site.

Would an optional "lang" metadata field in the article be enough?. That would just override the default language for THAT post.

**Comment by Kwpolska** [comment]
Sure, it will work. However, implementing it probably won’t be easy.

**Comment by mardy** [comment]
@jcea I'm using a multi-language site, where English is the default language. I write posts in English, Interlingua and Italian, and only very rarely my posts are translated; that is, most of the times I do write in a language only, which might be any of those three.

I don't see a problem with that, but maybe you can point out what you believe is wrong? My site is [here](http://www.mardy.it).

**Comment by ralsina** [comment]
I think a possible approach for this (yes, I know the issue is 3 years old) is a metadata "language" field. I'll give it a shot but it's ... complicated.

**Comment by ralsina** [comment]
In fact, this works now, I think.

If you write occasional posts in another language (say, spanish), just add that language as a translation. The content, when shown in the other languages will have the correct in-context translation for generated content.

For example, this is a site that has english as main language, but a single post that is spanish. Only change to config was to add spanish as a translation.

![image](https://user-images.githubusercontent.com/1579/79131546-27c8a180-7d7f-11ea-92ea-fb25c1b9767d.png)

As you can see, the docutils-generated admonition title is correctly in spanish, as it should be, even when reading the "english" side of the site.

If the translated posts are not enough to justify the whole "dual" site where you have a spanish and an english version just tweak the templates to not generate the links to the other languages?
