### ISSUE TITLE
Archive structure

### ISSUE THREAD

**Issue by davidak** [getnikola/nikola#2902]
### Description:

The current archive is an endless list of posts when you have lot's of articles.

See for example my website: https://davidak.de/archiv/

I would like to have a structure like this:

# 2017
## March
- An article about some stuff
- Another awesome article
## February
- maybe not my best article
- you should read this
## January
- Happy New Year

# 2016
## December
- an old article

---
Day in front of the link can be optional like here https://bradleyallen.net/archives/

Also links to every year section on the top.

Is this something you would integrate into nikola?

**Comment by Kwpolska** [comment]
Right now, there are four basic styles of archives available:

* all on one page, just like your blog
* one page per year, like [chriswarrick.com](https://chriswarrick.com/blog/)
* year/month
* year/month/day, like [ralsina.me](http://ralsina.me/weblog/archive.html)

(and a few more unusual combinations of those)

We currently don’t have anything that works the way you proposed. Implementing it wouldn’t be impossible though, if there’s interest.

**Comment by davidak** [comment]
@Kwpolska could this replace the first option or do you see it useful?

When i find some time i can implement it.

**Comment by Kwpolska** [comment]
It’s not *replacing* anything. It could be implemented as an alternative way to display single archives. Feel free to look into implementing it.

**Comment by ralsina** [comment]
It could be just a template and some logic.

**Comment by felixfontein** [comment]
To do it properly, code support would be better. A setting similar to `CREATE_ARCHIVE_NAVIGATION` could insert the necessary hierarchical data into the context, which could then be used by the template to render the correct structure.

**Comment by ralsina** [comment]
With https://github.com/getnikola/nikola/pull/3366 it can be done. An example archive.tmpl template would look like this:

```mako
<%block name="content">
<article class="listpage">
    <header>
        <h1>${title|h}</h1>
    </header>
    ${archive_nav.archive_navigation()}
    %if posts:
    <ul class="postlist">
    % for post in posts:
        <%!
        import calendar
        cur_year = 0
        cur_month = 0
        %>
        <% global cur_year; global cur_month %>
        % if cur_year != post.date.year or cur_month != post.date.month:
            <%  cur_year = post.date.year ; cur_month = post.date.month %>
            </ul>
            <h3>${calendar.month_name[post.date.month]} ${post.date.year}</h3>
            <ul class="postlist">
        % endif
        <li><a href="${post.permalink()}" class="listtitle">${post.title()|h}</a>  - <time class="listdate" datetime="${post.formatted_date('webiso')}" title="${post.formatted_date(date_format)|h}">${post.formatted_date(date_format)|h}</time></li>
    % endfor
    </ul>
    %else:
    <p>${messages("No posts found.")}</p>
    %endif
</article>
</%block>
```

**Comment by ralsina** [comment]
Closing since the separate archive template was merged and this works now.
