### ISSUE TITLE
Feature request: exclude some dot files when scanning post

### ISSUE THREAD

**Issue by ashfinal** [getnikola/nikola#2906]
I'm on macOS. Usually I use `nikola auto -b` to launch site preview in default browser. 
I found `.DS_Store` file (which is automatically produced by macOS) will trigger the site to rebuild, as we see in below:

```
[2017-09-24T09:29:25Z] INFO: auto: ---> /sitemap.xml
[2017-09-24T09:29:28Z] INFO: auto: REFRESHING: output/posts/.DS_Store
[2017-09-24T09:29:28Z] INFO: auto: ---> /posts/.DS_Store
[2017-09-24T09:29:28Z] INFO: auto: REFRESHING: output/authors/.DS_Store
[2017-09-24T09:29:28Z] INFO: auto: ---> /authors/.DS_Store
```

I guess Nikola will encounter this problem on Windows, as some files like `.thumb.db` might also be produced automatically. 

Is there any way that I can stop this behaviour?

**Comment by Kwpolska** [comment]
Ah, the lovely .DS_Store file. I think we could ignore all dotfiles for auto. Windows’ Thumbs.db has no dot — would need a special case.

(Tthis can also be “solved” by not opening your site in Finder.)

**Comment by amunozf** [comment]
I don't think you should ignore all dotfiles. At least, not the .htaccess file.

**Comment by ralsina** [comment]
@amunozf for the "auto" command .htaccess doesn't do anything.

**Comment by amunozf** [comment]
I take it back then, @ralsina Don't mind me.

**Comment by tritium21** [comment]
You can check for hidden files on windows by doing os.stat on them, and looking at the  st_file_attributes member in python 3.5+.  This would cover Thumbs.db and any other hidden file.

**Comment by ralsina** [comment]
Current code seems to already ignore files where the name starts with "." however it will not ignore files inside folders that start with "."

Doing a PR with some hopeful improvements.

**Comment by ralsina** [comment]
https://github.com/getnikola/nikola/pull/2928

**Comment by ralsina** [comment]
This is fixed.
