### ISSUE TITLE
"Also available in: ... " removable?

### ISSUE THREAD

**Issue by dprada** [getnikola/nikola#2910]
Is the header "Also available in: ... " removable by any mean?

This header has an automatic presence when translated pages are used. See for instance [www.uibcdf.org](http://www.uibcdf.org) with source code [here](https://github.com/uibcdf/uibcdf.github.io).

Would it be possible having an option in the conf.py to turn it off? There is already a language switcher in the menu bar.

Thanks in advance.
We really appreciate your effort.

**Comment by Kwpolska** [comment]
The top navbar link leads to the Spanish index, whereas *Also available in* leads to the same page.

To get rid of “Also available in:”, you can override `post_header.tmpl`: https://github.com/getnikola/nikola/blob/master/nikola/data/themes/base/templates/post_header.tmpl#L14 (or do it in story.tmpl, or something)

**Comment by dprada** [comment]
Done!

Thanks a lot.
