### ISSUE TITLE
Bootswatch Error 404

### ISSUE THREAD

**Issue by HoracioNakama** [getnikola/nikola#2916]
Hi! I'm using Nikola v7.8.10, and when I try used a new theme:

$ nikola bootswatch_theme -s journal

It returns:

[2017-11-07T20:35:56Z] ERROR: bootswatch_theme: Error 404 getting https://bootswatch.com/journal/bootstrap.min.css

But, if I search in www.bootswatch.com, I can see journal theme in: https://bootswatch.com/3/journal/bootstrap.min.css

How can I fixed this? I only need change the url from where download the css file. Thank you!

**Comment by Kwpolska** [comment]
Bootswatch changed their URLs again. Pushed fix to `master` and `v7-maintenance`. Thanks for reporting this!
