### ISSUE TITLE
Add placeholder images to gallery

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2918]
Maybe on other places too. Here is a great article showing different ways to do it:

https://medium.com/@jmperezperez/using-svg-as-placeholders-more-image-loading-techniques-bed1b810ab2c

**Comment by Kwpolska** [comment]
Have you seen a library that can do it without looking worse and having a worse UX? Many websites that do this often end up taking extra time to load the *real* image than just fetching it all on page load.

**Comment by ralsina** [comment]
I am actually running into this mostly on galleries because those have a LOT of images. It would be optional.

**Comment by ralsina** [comment]
This is probably trivial to do using

https://github.com/tuupola/jquery_lazyload

and

https://github.com/imsky/holder

as long as we are ok with regular flat placeholders.

In fact, it can be done completely template-side with that caveat.

**Comment by ralsina** [comment]
Nowadays a better idea is to just mark gallery images as lazy loading, which is just a template fix.

**Comment by ralsina** [comment]
Proposed in https://github.com/getnikola/nikola/pull/3371
