### ISSUE TITLE
Pages are scheduled when SCHEDULE_ALL is set to True

### ISSUE THREAD

**Issue by sukiletxe** [getnikola/nikola#2921]
### Environment (if reporting a bug)

**Python Version:** 3.6

**Nikola Version:** 7.8.10

**Operating System:** Windows 7

### Description:

If I have set `SCHEDULE_ALL` in `conf.py` to True, pages get scheduled. I don't know how to solve this (an exception to the rule if a page is being created, maybe), but I think the root of the problem is:
`new_post.py`, l347:
`schedule = options['schedule'] or self.site.config['SCHEDULE_ALL']`
Which will return True, because `SCHEDULE_ALL` is True.

**Comment by Kwpolska** [comment]
I think special-casing pages makes sense. I’ll take care of that.
