### ISSUE TITLE
ipynb code blocks have erroneous first line indent

### ISSUE THREAD

**Issue by ptooley** [getnikola/nikola#2927]
### Description:

When rendering from an ipython notebook, I am finding that the first line of all code blocks are indented by one extra space.

![2017-12-03-164614_1458x528_scrot](https://user-images.githubusercontent.com/32297355/33527480-9739cb76-d849-11e7-9c11-9ffe9faafe0e.png)

Example from http://acceleratedscience.co.uk/blog/adventofcode-day-3-spiral-memory/

The source ipynb can be downloaded and displays correctly (i.e no extra indented space) in recent versions of jupyter notebook

### Environment

Python Version: 3.5.4

Nikola Version: v7.8.8

Operating System: Gentoo Linux

**Comment by Kwpolska** [comment]
Seems to be an issue with our Jupyter-specific CSS.  I fixed this on `master` in commit 02510a81, but you can just change the offending lines in your local copy of `nikola_ipython.css` and rebuild.

**Comment by ptooley** [comment]
Wow, that was fast! Thanks :)
