### ISSUE TITLE
Dr. Web warns that: two files have virus "JS.DownLoader.426"

### ISSUE THREAD

**Issue by goldengrape** [getnikola/nikola#2935]
### Environment (if reporting a bug)

**Python Version:**
3.5

**Nikola Version:**
7.8.10

**Operating System:**
Mac OS 

### Description:

Dr. Web warns that: two files have virus "JS.DownLoader.426"

~/anaconda3/envs/blog/lib/python3.5/site-packages//nikola/plugins/misc/post_encryption.plugin/post_encryption.py

~/anaconda3/envs/blog/lib/python3.5/site-packages/nikola/plugins/misc/__pycache__/post_encryption.cpython-35.pyc

**Comment by Kwpolska** [comment]
This is a false-positive. This plugin is not in any way malware. [58 other antiviruses](https://www.virustotal.com/#/file/4c95527d4b636424e1453dd3792281ace59435ec3aee6a9192bd038ebbaf7de5/detection) don’t have any problems with it.  This file is harmless, it’s used to create encrypted posts. (It will be gone in v8 nevertheless.)
