### ISSUE TITLE
Orgmode no longer ships with htmlize

### ISSUE THREAD

**Issue by jwhendy** [getnikola/nikola#2937]
I have orgmode installed via git and just updated. I got a warning on exporting that I needed to install `htmlize`. In troubleshooting, I found out that they [recently removed it](https://github.com/hniksic/emacs-htmlize/issues/7#issuecomment-323286568) from shipping bundled with org.

I got the same error when I ran `nikola github_deploy`:
```
$ nikola github_deploy
Scanning posts........done!
.  render_posts:timeline_changes
Please install htmlize from https://github.com/hniksic/emacs-htmlize
```

I *had* installed it, which is when I realized you're using a separate `init.el`. I ended up adding these to make things work out.
```
;; where I have htmlize.el
(add-to-list 'load-path "~/.elisp/site-lisp/")
(require 'htmlize)
```

```
$ uname -a
Linux whammy 4.14.8-1-ARCH #1 SMP PREEMPT Wed Dec 20 21:27:44 UTC 2017 x86_64 GNU/Linux

$ python --version
Python 3.6.3

$ nikola --version
Nikola v7.8.10

M-x org-version
Org mode version 9.1.4 (release_9.1.4-248-gfdb2eb @ ~/.elisp/org/lisp/)
```

Thanks for taking a look.

**Comment by Kwpolska** [comment]
@punchagan can you take a look at it?

**Comment by jwhendy** [comment]
Sorry I forgot to come back, but could you let me do a bit more testing before investing time in this? It'd been so long since I used `nikola` (installed via an arch linux package), didn't recall that `orgmode` was a plugin, not included.

I was walking through reproducing this and in re-installing the `orgmode` plugin, I see that `init.el` now contains:

```
(require 'package)
(setq package-load-list '((htmlize t)))
(package-initialize)
```

So, it looks like you've actually addressed this and I was not up to date on the plugins.

Aside: maybe not a good idea, but what about a separate plugin package that could be kept up to date system wide and perhaps symlinked from individual site directories? Otherwise, when you ship a new plugin, it seems that one has to reinstall/update it in every working directory, correct?

**Comment by Kwpolska** [comment]
You could do user-wide installs: `nikola plugin --user -i orgmode`. Note that you will need to remove it from existing sites, and every site will be running that plugin.

An AUR package would be too much work and quite complicated, that’s not going to happen, sorry.

As for your fix: what if you remove orgmode from `~/.elisp/site-lisp/` and force a rebuild?

**Comment by jwhendy** [comment]
@Kwpolska I did not know about user-wide installs. That alleviates having to update for each repository, however I still need to update occasionally for issues like this, correct?

Totally understood on AUR packages.

To your last point, do you mean to remove `htmlize.el` from `~/.elisp/site-lisp`? I will try that. I am *sort of* thinking you didn't mean `orgmode`. I commented back so quickly as once I updated it looked like you're pulling `htmlize` via `elpa`, so you likely have taken care of what I brought up anyway.

**Comment by jwhendy** [comment]
It appears to work fine with either:

```
(add-to-list 'load-path "~/path/to/your/downloaded/htmlize.el")
(require 'htmlize)
```

or with your current `init.el`:
```
(require 'package)
(setq package-load-list '((htmlize t)))
(package-initialize)
```

I'm a happy camper now that I understand what was going on. Sorry about the confusion, and I'm happy to have everything working nicely again!
