### ISSUE TITLE
unable to write content in html

### ISSUE THREAD

**Issue by githubgnulinux** [getnikola/nikola#2938]
nikola new_post -f html
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/doit/doit_cmd.py", line 120, in run
    return command.parse_execute(args)
  File "/usr/lib/python2.7/dist-packages/doit/cmd_base.py", line 78, in parse_execute
    return self.execute(params, args)
  File "/usr/lib/python2.7/dist-packages/nikola/plugin_categories.py", line 102, in execute
    self._execute(options, args)
  File "/usr/lib/python2.7/dist-packages/nikola/plugins/command/new_post.py", line 262, in _execute
    self.site.config['post_pages'])
  File "/usr/lib/python2.7/dist-packages/nikola/plugins/command/new_post.py", line 65, in filter_post_pages
    type_name, compiler, type_name.upper()))
Exception: Can't find a way, using your configuration, to create a post in format html. You may want to tweak COMPILERS or POSTS in conf.py

The file 'conf.py' contains
COMPILERS = {
    "rest": ('.rst', '.txt'),
    "markdown": ('.md', '.mdown', '.markdown'),
    "textile": ('.textile',),
    "txt2tags": ('.t2t',),
    "bbcode": ('.bb',),
    "wiki": ('.wiki',),
    "ipynb": ('.ipynb',),
    "html": ('.html', '.htm'),
    # PHP files are rendered the usual way (i.e. with the full templates).
    # The resulting files have .php extensions, making it possible to run
    # them without reconfiguring your server to recognize them.
    "php": ('.php',),
    # Pandoc detects the input from the source filename
    # but is disabled by default as it would conflict
    # with many of the others.
    # "pandoc": ('.rst', '.md', '.txt'),
} 

There is no information what to do next.

**Comment by ralsina** [comment]
You probably don't have an entry in POSTS that says where html posts go.

Please post your POSTS option here and I will show you.

**Comment by ralsina** [comment]
In any case, it should be something like this:

```
POSTS = (
    ("posts/*.rst", "posts", "post.tmpl"),
    ("posts/*.md", "posts", "post.tmpl"),
    ("posts/*.txt", "posts", "post.tmpl"),
    ("posts/*.html", "posts", "post.tmpl"),
)
```

That line with "*.html" is probably the one you are missing.
