### ISSUE TITLE
Nikola web site inaccessible via proxy internet access

### ISSUE THREAD

**Issue by githubgnulinux** [getnikola/nikola#2946]
The nikola web site is inaccessible via anonymous internet proxy server:

One more step
Please complete the security check to access getnikola.com

Why do I have to complete a CAPTCHA?
Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.
What can I do to prevent this in the future?
If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.
If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.
Cloudflare Ray ID: 3db65416eafa7241 •  Performance & security by Cloudflare

**Comment by tritium21** [comment]
Are you sure the CAPTCHA request came from `104.28.21.58` or `104.28.20.58`?  This sounds like your proxy provider either requesting a CAPTCHA or your proxy provider being a bad actor.  getnikola.com runs nikola - a static html site.  It has no way to actually handle a CAPTCHA.

**Comment by ralsina** [comment]
Getnikola.com is served via cloudflare. In some cases if it suspects
malicious intent it will throw a captcha at you.

**Comment by Kwpolska** [comment]
@ralsina is right, and CloudFlare is a good thing to have on our website, so OP — please complain to them if you so desire.

**Comment by githubgnulinux** [comment]
> kwpolska:

Not everyone agrees that cloudflare is good. https://blog.torproject.org/trouble-cloudflare

**Comment by Kwpolska** [comment]
Same goes for Tor. In fact, far more people disapprove of Tor than of
CloudFlare.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by githubgnulinux** [comment]
Just tried to get nikola themes, but blocked due to cloudflare. Programmers, please consider this problem. Luckily, there is an archive file of themes that can be received via github repository.
