### ISSUE TITLE
Chronological (ascending) order

### ISSUE THREAD

**Issue by githubgnulinux** [getnikola/nikola#2947]
Please explain how to show posts in chronological order.

**Comment by Kwpolska** [comment]
Do you mean “oldest post on top”? Not officially supported (as it makes no sense for blogs: the top of the page always look the same, so your blog looks outdated).  You could use template hackery or post-lists to get it if you really want though.

(Newest-post-on-top is of course the default, and the only option for indexes.)

**Comment by githubgnulinux** [comment]
> You could use template hackery or post-lists to get it if you really want though.

Could you please show which part of the manual to edit templates?

What is "post-list"?

**Comment by Kwpolska** [comment]
`nikola theme -c index.tmpl` and then you can edit the template to do whatever you desire. In Jinja2 there’s the `posts|reverse` filter; `reversed(posts)` may or may not work for Mako (default).

Post lists are [these things](https://getnikola.com/handbook.html#post-list).  (Although again, we really don’t recommend working against basic user experience standards.)

**Comment by githubgnulinux** [comment]
Thanks for both options but,

"these things" hyperlink not accessible:

One more step
Please complete the security check to access getnikola.com
There was an issue communicating with the captcha provider. More information may be available below.

Enter confirmation code after solving challenge above

Why do I have to complete a CAPTCHA?
Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.
What can I do to prevent this in the future?
If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.
If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.
Cloudflare Ray ID: 3dc814620e8d6445
Performance & security by Cloudflare

**Comment by Kwpolska** [comment]
As mentioned in #2946, we will not drop CloudFlare. Please just enter the CAPTCHA or use a different provider.

**Comment by felixfontein** [comment]
You can always look at the site's source (or use it to build your own local copy) here: https://github.com/getnikola/nikola-site

**Comment by githubgnulinux** [comment]
OK.

You be interested to care that w3c accessibility guidance is that the cloudflare captcha is not helpful for text mode web browsers. Captcha difficult to enter when images are disabled

**Comment by felixfontein** [comment]
Please post CloudFlare related problems in #2946. Spreading them over so many different issues doesn't help.
