### ISSUE TITLE
Nikola supports the basic functionality of page resources already, let's add the extra bits

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2948]
For an explanation of Hugo's page resources, see https://regisphilibert.com/blog/2018/01/hugo-page-resources-and-how-to-use-them/

The missing bits are things like

```
{{ with .Resources.ByType "image" }}
    <div class="Image">
    {{ range . }}
        <img src="{{ .RelPermalink }}">
    {{ end }}
    </div>
{{ end }}
```

Which sounds pretty nice, to be honest. Also, not horribly hard to do as a shortcode.

**Comment by Kwpolska** [comment]
:-1: from me, because it looks (a) overly complicated (b) the thing is built for people who would by-foot implement galleries/listings/equivalent Nikola features.

**Comment by ralsina** [comment]
Could be done purely as a shortcode, and even out of repo. In plugins, even.

**Comment by ralsina** [comment]
Since I am not going to do it let's not do it.
