### ISSUE TITLE
warning locale guess

### ISSUE THREAD

**Issue by githubgnulinux** [getnikola/nikola#2950]
nikola new_post
 WARNING: Nikola: Could not guess locale for language en, using locale C

conf.py
...
# What is the default language?
DEFAULT_LANG = "en"
...

locale

**Comment by Kwpolska** [comment]
You need a *system* locale for English (read docs for your OS/distro of choice for details). We default to US English; if you want some other locale (eg. `en_GB`), you should change [the settings related to locales](https://github.com/getnikola/nikola/blob/master/nikola/conf.py.in#L168).

**Comment by githubgnulinux** [comment]
nikola serve
 WARNING: Nikola: Unexpected languages in LOCALES, ignoring them: B, e, G, F, -, ., U, T, 8, n, _
Traceback (most recent call last):
  File "/usr/bin/nikola", line 9, in <module>
    load_entry_point('Nikola==7.1.0', 'console_scripts', 'nikola')()
  File "/usr/lib/python2.7/dist-packages/nikola/__main__.py", line 118, in main
    site = Nikola(**config)
  File "/usr/lib/python2.7/dist-packages/nikola/nikola.py", line 491, in __init__
    self.config.get('LOCALES', {}), self.translations)
  File "/usr/lib/python2.7/dist-packages/nikola/nikola.py", line 1387, in sanitized_locales
    del locales[lang]
TypeError: 'unicode' object does not support item deletion

# While nikola can select a sensible locale for each language,
# sometimes explicit control can come handy.
# In this file we express locales in the string form that
# python's locales will accept in your OS, by example
# "en_US.utf8" in unix-like OS, "English_United States" in Windows.
# LOCALES = dict mapping language --> explicit locale for the languages
# in TRANSLATIONS. You can ommit one or more keys.
# LOCALE_FALLBACK = locale to use when an explicit locale is unavailable
# LOCALE_DEFAULT = locale to use for languages not mentioned in LOCALES; if
# not set the default Nikola mapping is used.
LOCALES = "en_GB.UTF-8"

**Comment by Kwpolska** [comment]
LOCALES = {"en": "en_GB.UTF-8"}
