### ISSUE TITLE
[boostrap4] poppers.js seems not included if use_cdn is false

### ISSUE THREAD

**Issue by farleylai** [getnikola/nikola#2954]
### Environment (if reporting a bug)

**Python Version:** 3.6

**Nikola Version:** 7.8.11

**Operating System:** Ubuntu 16.04

### Description:

I use a bootstrap 4 theme and add the dropdown menu item but it does not work as bootswatch shows.
The broswer inspection shows no poppers.js error.

> Error: Bootstrap dropdown require Popper.js (https://popper.js.org)

I checked the base.tmpl and found the poppers.min.js is included if use_cdn is true.
That could mean all-nocdn.js does not include poppers.js.
So the workaround is to set USE_CDN = True in conf.py.
I am not sure if this inconsistent behaviour is expected since it is the default.

**Comment by Kwpolska** [comment]
The first alphas uses `tether.js` and that was included in bundles. I fixed that and updated the theme for bootstrap’s recent 4.0.0 release.
