### ISSUE TITLE
Issue with teasers - thanks in advance

### ISSUE THREAD

**Issue by thestrawh8** [getnikola/nikola#2955]
### Environment (if reporting a bug)

**Python Version:3.6.4

**Nikola Version: 7.8.11

**Operating System:Ubuntu 16.04

### Description:

Hi, thank you very much making things easy. I am facing a small problem regarding INDEX_TEASERS = TRUE, I tried to figure but I couldn't understand why it is unable to apply teasers. I did grep -r -i "Teasers" in the output directory. I didn't get results. I am unable to figure out why it is happening can you please I did try to place a <--END TEASER--> tag manually in my posts/md files even then I couldn't see it working. can you please help. I shall attach all the possible requirements to debug this issue. 

I was using bootswatch theme. everything else works fine except the read more.

Thanks in advance.
![hierarchy](https://user-images.githubusercontent.com/20152870/35199860-610dc73e-ff2a-11e7-8c30-036a06ca43b1.png)
![indexpage](https://user-images.githubusercontent.com/20152870/35199861-614294dc-ff2a-11e7-97e6-0aa2da535320.png)
![index path](https://user-images.githubusercontent.com/20152870/35199862-6175ecb0-ff2a-11e7-9b46-522496668a4e.png)
![teasers](https://user-images.githubusercontent.com/20152870/35199863-61aa3240-ff2a-11e7-9b69-4fbc19fc98d5.png)

**Comment by Kwpolska** [comment]
<--END TEASER-->

This is not the correct tag. Did you try this:

    

(note word order, spaces, exclamation mark)

Also: Nikola won’t generate teasers automatically.  If fixing the spelling of the teaser tag doesn’t fix it, please also attach a sample post (.md) file.

**Comment by thestrawh8** [comment]
Thanks Kwpolska for responding very quickly and clarifying this for me. I thought it was auto generation so that is why I did raise an issue. Thanks again
