### ISSUE TITLE
Call to abs() in pagination_helper.tmpl yields UndefinedError

### ISSUE THREAD

**Issue by pschumm** [getnikola/nikola#2960]
Python 3.6.4
Nikola v7.8.11
OS X 10.13.3

The call to Python function `abs()` in

    {% if abs(i - current_page) <= surrounding or i == 0 or i == page_links|length - 1 %}

yields `jinja2.exceptions.UndefinedError`.  I believe the appropriate fix is to use the `abs` filter instead, e.g.:

    {% if (i - current_page)|abs <= surrounding or i == 0 or i == page_links|length - 1 %}

Note that this affects the following templates (at least):

    /data/themes/base-jinja/templates/pagination_helper.tmpl
    /data/themes/bootstrap3-jinja/templates/pagination_helper.tmpl

**Comment by Kwpolska** [comment]
Fixed on master, thanks for reporting.

PS. in the future, please report any non-standard settings you’re using, as this bug is reproducible only with `SHOW_INDEX_PAGE_NAVIGATION`.
