### ISSUE TITLE
permission error because of read-only assets

### ISSUE THREAD

**Issue by davidak** [getnikola/nikola#2962]
### Environment

**Python Version:** 3.6.4

**Nikola Version:** v7.8.11

**Operating System:** NixOS 17.09.2961.3d985c45905 (Hummingbird)

### Description:

The second build of the website fails, because the first created the assets as read-only files.

This is probably because the `/nix/store` is mounted read-only and the files are just copied.

Could you copy the files with right permissions?

```
[nix-shell:~/code/kaltefiste-website]$ nikola build && nikola serve --browser
Scanning posts........done!
.  render_galleries:output/DEFAULT_LANG/galleries
.  render_galleries:output/DEFAULT_LANG/galleries/index.html
.  render_galleries:output/DEFAULT_LANG/galleries/rss.xml
.  render_galleries:output/en/galleries/index.html
.  render_galleries:output/en/galleries/rss.xml
.  render_taxonomies:output/DEFAULT_LANG/archive.html
.  render_taxonomies:output/DEFAULT_LANG/categories/index.html
.  render_taxonomies:output/en/archive.html
.  render_taxonomies:output/en/categories/index.html
.  copy_assets:output/assets/fonts/glyphicons-halflings-regular.woff
########################################
TaskError - taskid:copy_assets:output/assets/fonts/glyphicons-halflings-regular.woff
PythonAction Error
Traceback (most recent call last):
  File "/nix/store/bglr5c2lkx2iq746b9020qf9csh6m4hl-doit-0.30.3/lib/python3.6/site-packages/doit/action.py", line 403, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/nix/store/rjgbhsjk2dqnanp9qap11v9wkpwx7sqx-python3.6-Nikola-7.8.11/lib/python3.6/site-packages/nikola/utils.py", line 804, in copy_file
    shutil.copy2(source, dest)
  File "/nix/store/z1avajv6hrjcx9nb07x9nd6cklb45w2r-python3-3.6.4/lib/python3.6/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/nix/store/z1avajv6hrjcx9nb07x9nd6cklb45w2r-python3-3.6.4/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'output/assets/fonts/glyphicons-halflings-regular.woff'
```

```
[nix-shell:~/code/kaltefiste-website]$ ll output/assets/fonts/
total 220
-r--r--r-- 1 davidak users  20127 Jan  1  1970 glyphicons-halflings-regular.eot
-r--r--r-- 1 davidak users 108738 Jan  1  1970 glyphicons-halflings-regular.svg
-r--r--r-- 1 davidak users  45404 Jan  1  1970 glyphicons-halflings-regular.ttf
-r--r--r-- 1 davidak users  23424 Jan  1  1970 glyphicons-halflings-regular.woff
-r--r--r-- 1 davidak users  18028 Jan  1  1970 glyphicons-halflings-regular.woff2
```

**Comment by Kwpolska** [comment]
We currently use copy2 which preserves metadata and permissions. Perhaps we
should change to just plain copy since permissions are irrelevant and so
are file change dates.

Any comments? (cc @ralsina)

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by ralsina** [comment]
Actually file dates are not irrelevant since webservers use them to control
caches.

**Comment by davidak** [comment]
So they might not stay in 1970 :D

**Comment by Kwpolska** [comment]
It turns out that just `copy` won’t fix it (it still copies permissions), we would need to use `copyfile` manually. Both 1970 dates and invalid permissions are caused by NixOS being crazy, not Nikola.  @davidak, perhaps you could try reconfiguring it first to behave more traditionally before we change behavior for everyone?

**Comment by ralsina** [comment]
I am -1 to not copying permissions and timestamps.

**Comment by ralsina** [comment]
Looks like I misremembered about webservers using file timestamps for handling the  if-modified-since header. Maybe they do, maybe they don't :)

So, let's think this through.

* What permissions do you expect the output to have?
* How do you expect to configure those permissions?
* Do you expect all files in the output to have the exact same permissions?
  * If no, how do you expect to configure that?

As of right now, the answers are:

* Nothing specific
* By setting the source's permissions
* No
   * By setting the permissions on the source files

And from that we may be able to work something out.

OTOH: regardless of making things readonly, having a file's timestamp set at 1970 is silly, why is that happening?

**Comment by felixfontein** [comment]
How about trying to change permissions to writeable before trying to write a file to disk? If someone wants to have read-only files, whatever, but if we copy permissions, we should try to handle that case halfway sane. OTOH, this quickly gets annoying if you have read-only directories as well...

@ralsina: the 1970 timestamps are pretty standard if you have a virtual filesystem (like `/proc`) and there is no sensible timing information you want to use (for `/proc` you can the system's boot time, but for other virtual filesystems that doesn't make any sense -- like when you don't want timestamps to change when you remount the thing or reboot your machine). A simple default is to use unixtime 0 in such cases, which results in January 1st 1970.

**Comment by felixfontein** [comment]
@davidak: you could use a simple passthrough fuse FS which presents the permissions (and file dates) differently. That's quite a hack, but effectively solves this problem without touching Nikola ;-) (see https://www.stavros.io/posts/python-fuse-filesystem/ for a Python example)

**Comment by davidak** [comment]
>having a file's timestamp set at 1970 is silly, why is that happening?

It's used to make the build reproducible. When the distribution builds the package and i build it again on my system it should have the same hash. So i can trust the distribution that it is really build from the source and not added some backdoors. You can also find problems with your build infrastructure when the resulting package changes. https://reproducible-builds.org/
