### ISSUE TITLE
Settings (per language) for Markdown extensions

### ISSUE THREAD

**Issue by saadatm** [getnikola/nikola#2970]
Some Markdown extensions allow the configuration of their output via options or settings (see, e.g., the settings for [SmartyPants](https://python-markdown.github.io/extensions/smarty/#usage) or [Footnotes](https://python-markdown.github.io/extensions/footnotes/#usage)).

Furthermore, in a multilingual website, users may want to override an extension's defaults for only some of the languages. As an example, I have a bilingual blog in English and Urdu, and when using SmartyPants, I would want to override the smart quote substitutions only for my Urdu posts, and keep using the default ones when writing in English.

So could it be possible to configure the settings for Markdown extensions on a per language basis?

**Comment by ralsina** [comment]
@saadatm if you want to test the proposed PR, I could use the help, since I am not really a markdown person.

**Comment by saadatm** [comment]
@ralsina Just tested the PR -- two languages, and each language having different options for Smarty Pants and Footnotes extensions -- and it's working. Thanks! 👍

**Comment by ralsina** [comment]
@saadatm neat, thanks for the test

**Comment by ralsina** [comment]
Fixed.

**Comment by saadatm** [comment]
I upgraded to v8.0.0b1, and  `MARKDOWN_EXTENSION_CONFIGS` does not seem to be working. I have created a [test Nikola site](https://github.com/saadatm/nikola-v8-test) that demonstrates the issue. Here are the relevant bits from conf.py:

```python
MARKDOWN_EXTENSIONS = [
    'markdown.extensions.abbr',
    'markdown.extensions.footnotes',
    'markdown.extensions.smarty',
]

MARKDOWN_EXTENSION_CONFIGS = {
    DEFAULT_LANG: {
        'markdown.extensions.footnotes': {
            'BACKLINK_TEXT': '[Back]'
        },
        'markdown.extensions.smarty': {
            'substitutions': {
                'left-single-quote': '&lsaquo;',
                'right-single-quote': '&rsaquo;',
                'left-double-quote': '&laquo;',
                'right-double-quote': '&raquo;'
            }
        }
    },
    'ur': {
        'markdown.extensions.footnotes': {
            'BACKLINK_TEXT': '[واپس]'
        },
        'markdown.extensions.smarty': {
            'substitutions': {
                'left-single-quote': '&rsquo;',
                'right-single-quote': '&lsquo;',
                'left-double-quote': '&rdquo;',
                'right-double-quote': '&ldquo;'
            }
        }
    }
}
```

When Nikola builds the site, none of these options get applied. Maybe I am missing something? (But it's strange because the same configuration worked in my earlier testing...)

**Comment by Kwpolska** [comment]
There was a glitch in the implementation. Sorry for not getting this into Beta 2; the real fix is just one line, so you can just patch it on your side: ad886d63.

**Comment by saadatm** [comment]
Got it working. Thanks!
