### ISSUE TITLE
ATOM_PATH

### ISSUE THREAD

**Issue by davidak** [getnikola/nikola#2971]
We have `RSS_PATH` but no `ATOM_PATH`.

I would like to have consistent URLs for RSS and ATOM Feeds.

Current:
RSS: https://davidak.de/rss.xml
ATOM: https://davidak.de/blog/index.atom

What i want:
RSS: https://davidak.de/rss.xml
ATOM: https://davidak.de/index.atom

(I'm not sure how important this is and if anyone uses ATOM Feeds nowadays)

**Comment by ralsina** [comment]
Probably not very important, but also probably easy to do :-)
