### ISSUE TITLE
graphviz plugin buggy output

### ISSUE THREAD

**Issue by vatula** [getnikola/nikola#2975]
### Environment (if reporting a bug)
http://ralsina.me/weblog/posts/lunchtime-nikola-feature-graphviz.html
and reproducible locally

**Python Version:**
3.6

**Nikola Version:**
v.7.8.11

**Operating System:**
alpine linux 3.7

### Description:
SVG is rendered with rudimentary text like 
"b'\nn "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n\n\n"
See http://ralsina.me/weblog/posts/lunchtime-nikola-feature-graphviz.html

**Comment by ralsina** [comment]
Well, it used to work in 2013. I'll take a look right now.

**Comment by ralsina** [comment]
The problem was that graphviz output was bytes and needed decoding. Should work fine now.
