### ISSUE TITLE
Malformed date/time string on new_post template

### ISSUE THREAD

**Issue by cinsk** [getnikola/nikola#2976]
### Environment (if reporting a bug)

**Python Version:**

        $ python --version
        Python 3.6.4

**Nikola Version:**

        $ nikola --version
        Nikola v7.8.11

**Operating System:**

        macOS High Sierra Version 10.13.3

### Description:
I use orgmode plugin to generate new post, (`nikola new_post -f orgmode`), and the template it generated has weird datetime string:

        .. date: 2018-03-06 10:27:55 UTC-08:00

It doesn't just orgmode plugin problem, rst backend has the same problem:

        .. date: 2018-03-06 10:28:07 UTC-08:00

It looks like `nikola/plugins/command/new_post.py` line 110 has the problem:

        106:     if iso8601:
        107:         tz_str = '{0:+03d}:{1:02d}'.format(offset_hrs, offset_min // 60)
        108:     else:
        109:         if offset:
        110:             tz_str = ' UTC{0:+03d}:{1:02d}'.format(offset_hrs, offset_min // 60)
        111:         else:
        112:             tz_str = ' UTC'

line 110 should be like:

        110:             tz_str = ' {0:+03d}:{1:02d}'.format(offset_hrs, offset_min // 60)

**Comment by Kwpolska** [comment]
Expected behavior, done to improve user experience. Many people would be confused about the meaning of the timezone string. (And yes, we know some Unix tools use this format with inverted +/- signs.) If you don’t like our generated date format, try `FORCE_ISO8601 = 1`. This will give you a more standard ISO8601 form.

**Comment by ralsina** [comment]
Just as a sidebar, if you use that without the UTC (for example, by manually adding the dates) it will work in the same way:

```
>>> from nikola.utils import to_datetime
>>> to_datetime('2018-03-06 10:27:55 UTC-08:00')
datetime.datetime(2018, 3, 6, 10, 27, 55, tzinfo=tzoffset(None, -28800))
>>> to_datetime('2018-03-06 10:27:55 -08:00')
datetime.datetime(2018, 3, 6, 10, 27, 55, tzinfo=tzoffset(None, -28800))
```
