### ISSUE TITLE
Add support for Schnack comments

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2979]
Since I just did Commento, let's try to do this one next:

https://github.com/schn4ck/schnack

**Comment by Kwpolska** [comment]
:-1: from me, nobody uses that. Let’s focus on more useful features.

**Comment by ralsina** [comment]
Commento took literally 3 minutes and is by far the easiest self-hosted comment solution. But I agree that schnack is niche.

**Comment by ralsina** [comment]
Ok, closing. Life is too short.
