### ISSUE TITLE
A "/" (single slash) in POSTS / PAGES second element confuses Nikola

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2982]
Something like

```
POSTS = [['posts/*txt', '/', 'post.tmpl']]
```

will attempt to write your pages in the actual root directory of your machine.

**Comment by Kwpolska** [comment]
I *think* the same happens with TRANSLATIONS.

**Comment by ralsina** [comment]
I will check that one too.

**Comment by ralsina** [comment]
I have a fix for POSTS / PAGES but TRANSLATIONS escapes me (the bug is there, I just can't find the fix yet).

**Comment by ralsina** [comment]
#2984 fixes it for POSTS / PAGES, so just TRANSLATIONS needs fixing.
