### ISSUE TITLE
No grouping using baguettebox.js

### ISSUE THREAD

**Issue by michaelb42** [getnikola/nikola#2992]
### Environment (if reporting a bug)

**Python Version:**
3.5.4

**Nikola Version:**
Old: 7.8.10
New: 8.0.0dev (master, last commit f99d4a66db8836f6f7d62bd63bdde29c2b4cdaf7)

**Operating System:**
gentoo GNU/Linux

### Description:

The lightbox used by nikola v7 e.g. in the auto-generated demo site provided grouping of images on posts or pages with multiple images or figures. The lightbox automagically provided nav-buttons so the reader could cycle through all images of the article.

This grouping feature does no longer work with current v8 and its new lightbox code.

#### Steps to reproduce:
v7 behaviour:
1. Generate a demo-site with v7
2. Simply duplicate the .. figure in posts/1.rst
3. Build and serve output - colorbox provides left and right buttons to cycle between the two images.

v8 behaviour:
1. Generate a demo-site with current v8
2. Duplicate the .. figure in posts/1.rst again
3. Build and serve output - baguettebox.js does not provide any controls to cycle between the two images, the user is required to click on each thumbnail-image to see the large version.

**Comment by ralsina** [comment]
Can you check if https://github.com/getnikola/nikola/pull/2993 works better for you?

It's a rather aggressive fix, so it could cause problems with other images in posts, but we'll see.

**Comment by michaelb42** [comment]
#2993 solves the problem, but yes, it is *very* aggressive.

**Comment by ralsina** [comment]
I will only do a lighbox for images that are links to images. I think that's more or less the behaviour we want :-)
