### ISSUE TITLE
Need clarification on the deps variable in ReSTExtensionTestCase

### ISSUE THREAD

**Issue by xuhdev** [getnikola/nikola#3002]
It seems like, `ReSTExtensionTestCase` has a variable `deps` which seems to be required to be set by plugin developers when they write test cases. This, however, does not seem like to be well documented. What does it do? Does it specify files that the test depends on? If so, how should we specify more than one such file?

**Comment by ralsina** [comment]
It's supposed to be a list of files.

In most cases it can just be None.
