### ISSUE TITLE
Recognize both TEASER_END and END_TEASER.

### ISSUE THREAD

**Issue by mforbes** [getnikola/nikola#3010]
I find it hard to remember that the teaser should be ended with `TEASER_END` rather than the imperative `END_TEASER`.  There is even an example in the mailing lists referring in error to the latter.  I propose that the TEASER_REGEXP be updated to accept both.  This was discussed briefly in [the newsgroup](https://groups.google.com/forum/#!topic/nikola-discuss/7_nIV_Buuzw).  I will provide a PR shortly.

**Comment by Kwpolska** [comment]
Resolved by #3011.
