### ISSUE TITLE
Dependency in snap missing to support blogger import

### ISSUE THREAD

**Issue by gusgit** [getnikola/nikola#3012]
Version:    nikola    7.8.8    252    ralsina

Hi,
I am trying to iport a blog from blogger. I am getting the following error:
```
$ nikola import_blogger ~/Downloads/blog-04-08-2018.xml 
[2018-04-08T09:20:51Z] ERROR: Nikola: In order to import Blogger dumps, you must install the "feedparser" Python package.
[2018-04-08T09:20:51Z] ERROR: Nikola: Exiting due to missing dependencies.
```
Can I use an external dependency, or does it need to be installed in the snap?

Thanks,
Gus

**Comment by ralsina** [comment]
It needs to be in the snap. I will take a look.

OTOH, if you at all can, please just install it the regular way, snaps are problematic in several ways once you go out of the testing phase.

**Comment by gusgit** [comment]
Hi Roberto,

Thanks, I've tried using virtualenv and pip and it all works fine.

I used the snap initially as it is convenient and simple to install, it also allows me to keep only one installation of nikola to share easily between multiple projects.

I hope you can get it to work, thanks for the good work!

Gus

**Comment by Kwpolska** [comment]
I have only one installation of Nikola. `~/virtualenvs/nikola` is used for all my development work and websites. (I use virtualenvwrapper, but that’s not mandatory.)

**Comment by gusgit** [comment]
I'll try that, thanks!

**Comment by Kwpolska** [comment]
@ralsina, perhaps we should add some notes about that to the getting started guide/blog posts/whatever?

**Comment by ralsina** [comment]
@Kwpolska sounds like it would be useful :-)

**Comment by Kwpolska** [comment]
@ralsina (by *we*, I meant *you*)

**Comment by ralsina** [comment]
Ok, on it.

**Comment by ralsina** [comment]
So, things have changed a lot in the snap ecosystem since I last looked.

I will need to do it on my work machine on monday.

**Comment by ralsina** [comment]
So, looks like today is monday. On it.

**Comment by ralsina** [comment]
The feedparser dependency was added in the stable channel snap today (version 8.0.4) so it should work, not that I expect the original reporter to have been waiting :-)
