### ISSUE TITLE
AMP outputs for Nikola

### ISSUE THREAD

**Issue by kayhayen** [getnikola/nikola#3013]
### Description:

I didn't find any reference for this in the mailing list archive, nor in the issue tracker.

it would be nice to add support: https://support.google.com/webmasters/answer/6340290 if not just for completeness sake, then for search engine ranking I suppose. I recall reading that Google prefers sites with this.

This is of course only a wish. Feel free to tell me I am uninformed and this is non-sense.

**Comment by Kwpolska** [comment]
We’ve already had #2136 about it. AMP does *not* make stuff any faster. It’s Google lock-in. It breaks link sharing (Google caching crap) and used to break scrolling in Safari on iOS. It also requires a ton of JavaScript.

If someone wants it, they could build a plugin for it. But definitely not going to happen in core.

https://www.theregister.co.uk/2017/05/19/open_source_insider_google_amp_bad_bad_bad/

**Comment by kayhayen** [comment]
Oh, sorry for being blind. I did search the issues, but skipped over the closed issue you are pointing out. Sorry for wasting your time.

And thanks for the good work on Nikola. I am auto-updating Nikola and not have had any issues with it forever now.
