### ISSUE TITLE
Multiline metadata not being processed.

### ISSUE THREAD

**Issue by mforbes** [getnikola/nikola#3014]
### Environment (if reporting a bug)

**Python Version:** 3.6.4
**Nikola Version:** Nikola v8.0.0.dev0
**Operating System:** Mac OS X

### Description:

I am trying to specify a multiline description using ReST in a page:

```rst
.. description: Aenean ornare velit lacus varius enim ullamcorper proin aliquam
	 facilisis ante sed etiam magna interdum congue. Lorem ipsum dolor amet nullam
	 sed etiam veroeros.
```

This is parsed appropriately by docutils.  For example, `rst2html5.py` converts this to:

```html
<!-- description: Aenean ornare velit lacus varius enim ullamcorper proin aliquam
facilisis ante sed etiam magna interdum congue. Lorem ipsum dolor amet nullam
sed etiam veroeros. -->
```

but Nikola only picks up the first line `Aenean ornare velit lacus varius enim ullamcorper proin aliquam` in the page metadata.  How can I specify a multiline description (line-breaks are not significant here - I just want all of the text inserted into the `description` metadata, though it would be nice to be able to include line breaks too occasionally, however, ~~this does not even work in RST~~.)

Update: RST does preserve the line-breaks in the multiline comments.  Note that the line breaks above exactly match the source.)

**Comment by mforbes** [comment]
I see that this processing is done in `metadata_extractors.py` which does not use docutils, hence the different behaviour.  This is still quite counter-intuitive and I do not see a way of including multiline descriptions.  Is it possible to maybe first convert the metadata to comments using docutils (or whatever engine is being applied) and then extract the metadata?

**Comment by mforbes** [comment]
I think I see the solution:

```python
# If enabled, extract metadata from docinfo fields in reST documents
USE_REST_DOCINFO_METADATA = True
# If enabled, hide docinfo fields in reST document output
HIDE_REST_DOCINFO = True
```

Then the [reST-docinfo](https://getnikola.com/handbook.html#rest-docinfo) option can be used which permits both explicit line-breaks (as per the ReST documentation) and multiline meta-data:

```rst
.. |br| raw:: html

   <br />

:description: Aenean ornare velit |br| lacus varius enim ullamcorper proin aliquam
	 facilisis ante sed etiam magna interdum congue. Lorem ipsum dolor amet nullam
	 sed etiam veroeros.
```

I think this satisfies all of my needs, so the only real issue is a warning in the handbook that the [reST-style-comments](https://getnikola.com/handbook.html#rest-style-comments) are not actually processed by docutils and that multi-line comments are not supported but that the [reST-docinfo](https://getnikola.com/handbook.html#rest-docinfo) technique can be used instead, (or possibly that the `FILE_METADATA_REGEXP` can be specified as needed - I will post back if I find a good regexp solution).

**Comment by Kwpolska** [comment]
Yes, this may need documenting. But multi-line metadata doesn’t seem all that useful to me.

**Comment by mforbes** [comment]
Slightly aside, but my use case was trying to fit Nikola into a custom theme which would organize standard data differently on different types of pages - i.e. in a post list, an image would come first, then the description, while in the actual page, the description would come first and then the image.  While it might ultimately be better control this positioning with CSS, for now I just wanted a quick and dirty way of reorganizing them in the templates.  The only easy way I could see to do this was to use metadata (i.e. an `image` tag and an extended `description` which I could then position as I wanted in the post lists and on the page).  This led to the desire for an extended `description`.

Am I correct in assuming that the "canonical" way of doing this would be to just include these things in the actual text and refer to them via selectors to do the positioning (I.e. in a post list, place the first paragraph below the image, while on a page, place it above.)?  I am not sure how easy this is to do without tweaking the DOM.  If there is another solution, I would appreciate a pointer.

**Comment by Kwpolska** [comment]
You should be able to put arbitrary HTML in meta tags, as long as you can fit it on one line. As for better solutions — perhaps do splitting, like we do with teasers?

**Comment by mforbes** [comment]
Splitting would have worked well if I could somehow get the teaser (easy) *and* then get the portion following the teaser.  I have no idea how to easily exclude the teaser given the current processing model without deeply hacking Nikola.

**Comment by Kwpolska** [comment]
Added one line about it multiline stuff to docs in 9e36774.
