### ISSUE TITLE
multiple atom feed files generated

### ISSUE THREAD

**Issue by davidak** [getnikola/nikola#3016]
### Environment (if reporting a bug)

**Python Version:** 3.6

**Nikola Version:** 7.8.11

**Operating System:** NixOS 18.03.131802.4b4bbce199d (Impala)

### Description:

Nikola generates many files for Atom feeds like `index.atom`, `index-2.atom` and `index-n.atom`. The RSS feed only generates one file.

Is that correct or a bug?

**Comment by felixfontein** [comment]
That's how Atom support worked in Nikola since forever. There's (at least for indexes and posts) one `.atom` file per `.html` file, having the same content in a different format. I have no idea whether that's correct usage of Atom, though...

**Comment by felixfontein** [comment]
Atom support as described here was first implemented in 0def2e0ada822ed20d0a9600f036ecf52774124f, if I understand it correctly. Maybe @da2x can comment on why it works this way with pagination? (@da2x: see also https://github.com/getnikola/nikola/pull/3015#issuecomment-379834650)

**Comment by felixfontein** [comment]
I.e. Atom feeds will be as RSS feeds?

**Comment by Kwpolska** [comment]
Yes, that would make more sense to me.

**Comment by felixfontein** [comment]
To me, too. I'm still curious why @da2x's initial implementation was like this. Maybe there's something about Atom feeds I don't understand...
