### ISSUE TITLE
Support for captioned and ordered images in galleries

### ISSUE THREAD

**Issue by jmcp** [getnikola/nikola#3017]
The gallery feature is very powerful, but is missing two features: the ability to caption individual images, and the ability to specify the order in which the images are displayed.

I have a patch available which resolves these two issues.

For ordering, create a file in your gallery directory called IDX. List the image filenames (one per line) in the order that you want them displayed in the gallery.

For captions, create a file in your gallery directory called captions. In that file, list the image filenames (one per line), whitespace, and then the text you want to use for the caption. You can specify that an image has *no* caption by using the string `::empty::`. Using a caption file also implicitly enables the gallery ordering feature.

**Comment by ralsina** [comment]
Sounds good. Could you open a PR?

**Comment by jmcp** [comment]
After review from Chris, I've re-implented the PR (#3018) so that the feature looks for a YAML-formatted 'metadata.yml' in the gallery directory, which contains

name:
caption:
order:

(only name is mandatory) for as many images as the user cares to provide information about. There is no need to use `::empty::` for an uncaptioned image.

**Comment by ralsina** [comment]
@jmcp @Kwpolska so, this is done?

**Comment by Kwpolska** [comment]
Yes, it is.

**Comment by ralsina** [comment]
Cool!
