### ISSUE TITLE
Feature request: option to strip left margin off converted Jupyter notebooks

### ISSUE THREAD

**Issue by gramster** [getnikola/nikola#3019]
When compiling a post from a Jupyter notebook, there is a gray left margin. For markdown cells its just a gray square while for code cells it has the cell number. For some themes this ends up using a lot of the page content width; you can see an example here:

https://www.grahamwheeler.com/posts/python-overview.html

It would be great to have an option to suppress that.

**Comment by Kwpolska** [comment]
To fix this in all pages, you can use custom CSS:
```css
div.prompt {
    display: none;
}
```

**Comment by gramster** [comment]
Thanks, I’ll do that, but it still seems like it would be good to be able to control this from the Nikola config.py.

**Comment by Kwpolska** [comment]
This would require maintaining custom templates for ipynb that would respect this option. Too much work, that CSS fix is enough.
