### ISSUE TITLE
section information ignored for files in subdirectories

### ISSUE THREAD

**Issue by tbm** [getnikola/nikola#3023]
### Environment (if reporting a bug)

**Python Version:** 3.5.3

**Nikola Version:** v7.8.14

**Operating System:** Debian

### Description:

Since sections in subdirectories are not automatically supported (#2486), I used metadata `section` on each file in my blog to define the section.

For `blog/foo/test.md` (`section: foo`) this works fine.  But for `blog/bar/baz/test.md` (`section: bar`) the section info seems to be ignored.  I get a `output/blog/foo/index.html` but no `output/blog/bar/index.html`.

**Comment by Kwpolska** [comment]
Sections are wonky sometimes, and they are slated for removal one day (#2833). Are you sure there is no `bar` directory anywhere?

**Comment by tbm** [comment]
The `bar` directory is there but no `index.html` even though `POSTS_SECTIONS = True`.

**Comment by tbm** [comment]
Ok, I read the bug you referenced. I'm a bit surprised because the manual says about categories: `Those are deprecated and replaced by sections`. Anyway, that's just a question of terminology. The proposal in the bug you referenced sounds good to me. I'm moving to nikola right now, I guess v8 is still far away so I should just make it work somehow for now?
