### ISSUE TITLE
Allow mapping metadata to different types

### ISSUE THREAD

**Issue by tbm** [getnikola/nikola#3025]
My pages define keywords using Yaml meta data, e.g.

```
keywords: [SheevaPlug, Marvell, Kirkwood, Debian, installer, ARM, GuruPlug]
```

A list seems to be the natural type to specify keywords and tags, but it seems nikola takes this as a string.

In fact, even if I do:

```
keywords:
  - Debian 
  - lenny 
  - installation
```

I end up with:

```
<meta name="keywords" content="['Debian', 'lenny', 'installation']">
```

**Comment by Kwpolska** [comment]
This works as intended. You pass in a list, and Nikola keeps it as that. Try this:

```mako
    <ul>
    % for k in post.meta('keywords'):
    <li>${k}</li>
    % endfor
    </ul>
```

```html
    <ul>
<li>SheevaPlug</li>
    <li>Marvell</li>
    <li>Kirkwood</li>
    <li>Debian</li>
    <li>installer</li>
    <li>ARM</li>
    <li>GuruPlug</li>
    </ul>
```

Since you’re just using the variable, you get its standard python `repr()`. To get your desired output, use `${', '.join(post.meta('keywords'))}` in Mako or `{{ post.meta('keywords')|join(', ') }}` in Jinja2.

**Comment by tbm** [comment]
Right, but what I was trying to say (sorry for not being clear) is that the standard template should do what you suggest.

Yeah, I know that HTML just wants a list of words separated by comma but the best way to represent that in Yaml is with a list.  So imho nikola should automatically do the join you suggest.

**Comment by tbm** [comment]
Is there any reason for NOT doing this in nikola itself?  Why would anyone want to pass a list to HTML?

**Comment by tbm** [comment]
Sorry for so many replies, but basically my argument is that the standard python repr() or a list doesn't make sense in HTML context and there it should always be the join() you mention.

**Comment by Kwpolska** [comment]
> Why would anyone want to pass a list to HTML?

To display it with bullet points, like I did in my response? We’re definitely not automatically joining lists.

Another thing to consider is that the template kinda assumes the default meta format, which only supports strings. This can be fixed, with a new feature.

This feature is called `METADATA_VALUE_MAPPING` — which makes stuff even more flexible than needed here. I have a patch ready, but it depends on #3028.

**Comment by felixfontein** [comment]
Would it maybe make sense to add a Mako/Jinja2 filter which keeps strings as is, and join lists? (If there isn't already.) And then use this filter in the default templates in such cases?
I don't know how complicated that is for Mako (I've only created Jinja2 filters so far), but that should solve this issue without preventing the list itself to be used.

**Comment by tbm** [comment]
Thanks for your comment @felixfontein. I haven't had the time to comment on @Kwpolska's recent comment. `METADATA_VALUE_MAPPING` is very elegant and can do a lot of stuff.  Nevertheless, in the HTML header, it's pretty clear that keywords and tags should be comma separated, not a list.  So my question was going to be why not do the join() there by default since that works with both lists and strings.  I think this is the same you're suggesting.

**Comment by Kwpolska** [comment]
It doesn’t work.
```pytb
>>> ', '.join('foo, bar, baz')
'f, o, o, ,,  , b, a, r, ,,  , b, a, z'
```

That said, a `smartjoin` filter that does The Right Thing™ is a reasonable idea too. I’ll implement that in a while.

**Comment by Kwpolska** [comment]
@tbm It won’t, it’s a new feature. Upgrading to `master` will probably be the best choice; otherwise, you can backport it manually (it’s just a few lines)
