### ISSUE TITLE
post-list shortcode doesn't work with Markdown

### ISSUE THREAD

**Issue by tbm** [getnikola/nikola#3027]
The manual says:

```
Using shortcode syntax (for other compilers):

{{% post-list stop=5 %}}{{% /post-list %}}
```

But when I put it in a Markdown file I get:

```
[2018-04-14T17:27:10Z] ERROR: Nikola: Unknown shortcode post-list (started at line 1, column 1)
```

In a `.rst` file it works (the `.. post-link` syntax. Maybe the shortcode doesn't work there either)

**Comment by Kwpolska** [comment]
Works for me. Did you do anything to disable the reST plugins?

**Comment by Kwpolska** [comment]
I can reproduce with `*.rst` and `*.txt` removed from POSTS and PAGES. Due to internal technical reasons, you can’t do that if you want to use certain shortcodes. I added a few warnings to the manual.

Feel free to reopen if you can reproduce after adding a `*.rst` entry to POSTS/PAGES.

**Comment by tbm** [comment]
You're right.  Adding`*.rst` to POSTS/PAGES makes it work.  Thanks.

**Comment by ralsina** [comment]
This is a known bug, and the fix is to make the shortcode independent from the reSt plugin.
