### ISSUE TITLE
[canterville] Inconsistent spacing between paragraphs

### ISSUE THREAD

**Issue by gramster** [getnikola/nikola#3029]
### Environment (if reporting a bug)

**Python Version:**

3.6

**Nikola Version:**

Nikola v7.8.10 w/Canterville theme

**Operating System:**

MacOS

### Description:

I would like a blank line between paragraphs in my posts, which are either markdown or Jupyter.

I find I get this if I open the individual post in a browser tab. I also get this if I just open the main page of my site, if the post was written in Jupyter. But if the post was written in markdown, then there is no space between paragraphs when opened from the main page.

Example: when reading a post from the top-level:

https://www.grahamwheeler.com/

![image](https://user-images.githubusercontent.com/2762632/38772523-9e010d32-3fed-11e8-817a-c6a7debe12c0.png)

and when reading that post on its own after clicking its title:

https://www.grahamwheeler.com/posts/blogagain.html

![image](https://user-images.githubusercontent.com/2762632/38772532-b3c2f748-3fed-11e8-9535-5de01358ea57.png)

Seems like a bug to me.

**Comment by Kwpolska** [comment]
This looks like explicit and desired behavior:

```css

.post-excerpt p {
    margin: 0; /* ! */
    font-size: 0.9em;
    line-height: 1.7em;
}
```

I suppose making excerpts smaller was a deliberate design choice.

PS. Issues with non-default themes are better off reported in getnikola/nikola-themes.

**Comment by ralsina** [comment]
Of coure it can also be overriden in custom.css
