### ISSUE TITLE
Allow config option for menu_alt (config to put something navigation upper right)

### ISSUE THREAD

**Issue by tbm** [getnikola/nikola#3030]
I'd like to put some social media links/icons on the upper right of the navigation bar.  I see that plugins can put `menu_alt` there.

Is there a reason I can't put content there using a config variable?

**Comment by Kwpolska** [comment]
Because nobody thought about this before.  Adding it as a new feature shouldn’t be hard.

**Comment by tbm** [comment]
This does exactly what I wanted, thanks @Kwpolska.
