### ISSUE TITLE
`active` label does not work for path handler navigation links

### ISSUE THREAD

**Issue by gwax** [getnikola/nikola#3031]
### Environment (if reporting a bug)

**Python Version:** 3.6.4

**Nikola Version:** 7.8.14

**Operating System:** OSX

### Description:

When using a path handler `link://slug/foo-bar-baz` as a navigation link the `active` label does not get set correctly under the base template.

The issue arises from the rel_link comparison at https://github.com/getnikola/nikola/blob/master/nikola/data/themes/base/templates/base_header.tmpl#L38

In this case, `permalink` is the final address but `suburl` is the untranslated path handler link.

As an ugly workaround, the check can be changed to `rel_link(permalink, url_replacer('/', suburl)) == '#'` but this only works if `STRIP_INDEXES = False` or `PRETTY_URLS = False`; otherwise permalink will have a trailing `/` but `url_replacer('/', suburl)` will not.

**Comment by Kwpolska** [comment]
Yeah, that’s a tricky problem.

```
P = /posts/welcome-to-nikola/
S = link://slug/welcome-to-nikola
```

We could try to run the replacer first, or use a special `is_active` function to check that also considers magic links and other stuff (and perhaps handle trailing slash issues more elegantly).

**Comment by gwax** [comment]
As I was thinking about it, it seems we might reasonably do two things:

1.  Make `url_replacer` more aware of `STRIP_INDEXES` and `PRETTY_URLS`
2.  Run url_replacer more often
    - possibly early in the chain (like when reading `NAVIGATION_LINKS`)

**Comment by Kwpolska** [comment]
(1) does not matter in this case, although it *should* be done to avoid issues with “regular” links (user types `/foo` in N_L and Nikola expects `/foo/`).  As for (2)… we could try doing that, although it’s a rather minor thing — it would be easier to avoid magic links in navbar.

**Comment by gwax** [comment]
Avoiding magic links in the navbar makes sense for a blog heavy use case but for a page heavy use case it becomes hugely valuable. For example, I have a "projects" page that I want directly linked from the navbar; I can construct the link as `/projects/` but, as I discovered recently, this breaks when I decide I want to change my link style; it's far nicer to be able to put `link://slug/projects` in my navigation links and know it will point to the right place.

**Comment by Kwpolska** [comment]
The problem in this case is you changing link styles. [Cool URIs don’t change](https://www.w3.org/Provider/Style/URI), and I can’t think of a better URL than `/projects/`.

**Comment by Kwpolska** [comment]
Closing as *won’t fix*.
