### ISSUE TITLE
How can I list all post in Tags and Categories page 

### ISSUE THREAD

**Issue by huhuang03** [getnikola/nikola#3033]
I want list all post in `http://127.0.0.1:8000/categories/`, similar to [this](https://groups.google.com/forum/#!topic/nikola-discuss/wvkJ-dcbVMA).

What's the ideas to do this?

**Comment by Kwpolska** [comment]
That’s not easily possible. You could use a [post-list](https://getnikola.com/handbook.html#post-list) and include it on the page via JS or server-side includes. You could also try to write a custom plugin to render the tags & categories page that does both, but that’s quite complicated and involved.

The reasons for this being impossible are listed in this thread: if `posts` were available everywhere, we’d always rebuild all files, and we don’t want to do that.

**Comment by Kwpolska** [comment]
I meant to do something as we do on themes.getnikola.com:

https://raw.githubusercontent.com/getnikola/nikola-themes/master/site/pages/sidemenu.rst 
https://github.com/getnikola/nikola-themes/blob/master/site/templates/sidemenu.tmpl 
https://github.com/getnikola/nikola-themes/blob/master/site/templates/sidemenu_list.tmpl 

this generates a simple [sidemenu.html](https://themes.getnikola.com/sidemenu.html) file, which — with the help of [pkgindex.js](https://themes.getnikola.com/assets/js/pkgindex.js) — appears [on every theme page, on the right](https://themes.getnikola.com/v8/base/).

You could do something similar — the JS would only be in `categories.tmpl` though.

or alternatively: https://en.wikipedia.org/wiki/Server_Side_Includes

**Comment by huhuang03** [comment]
After a try, I finished by follow your sidemenu demo. Thank you!
