### ISSUE TITLE
HTML validation errors with default bootstrap3 theme

### ISSUE THREAD

**Issue by tbm** [getnikola/nikola#3035]
I see the following validation errors from https://validator.w3.org with the default bootstrap3 theme.

On all pages:

```
Error: Element div is missing one or more of the following attributes: role.
From line 36, column 9; to line 36, column 83
>↩        <div class="collapse navbar-collapse" id="bs-navbar" aria-expanded="false">↩     
```

On all posts (blog):

```
Error: The itemprop attribute was specified, but the element is not a property of any item.
From line 106, column 44; to line 106, column 90
or vcard"><span class="byline-name fn" itemprop="author">↩     
```

**Comment by Kwpolska** [comment]
Validators are really not that important. What’s more important is working in browsers.

The latter error was already fixed in #2994. The former does not occur in `bootstrap4`. If you really want, you can add `role="menubar"` to the `div` in whatever template this is defined.
