### ISSUE TITLE
Rename DISABLE_INDEXES_PLUGIN_* settings

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#3039]
This sucks:

```py
DISABLE_INDEXES_PLUGIN_INDEX_AND_ATOM_FEED = False
DISABLE_INDEXES_PLUGIN_RSS_FEED = False
```

Better:

```py
# Disable indexes (/index.html) and main Atom feed (/index.atom)
DISABLE_INDEXES = False
# Disable main RSS feed (/rss.xml). See also: GENERATE_RSS (to disable all RSS feeds)
DISABLE_MAIN_RSS_FEED = False
```

**Comment by Knapstad** [comment]
Hi i tried to push a branch with a fix for this, but I got a 401 error message. I'm quite new to git so i'm not shure what i'm doing wrong

**Comment by Kwpolska** [comment]
@Knapstad: you can’t push branches to the main getnikola/nikola repository. Instead, you need to create a fork, push it there, and send a pull request. Here are some help articles:
https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/about-pull-requests/
https://help.github.com/articles/set-up-git/
