### ISSUE TITLE
Customizing main RSS path

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#3041]
So people can change `rss.xml` to anything they want (not only the subdirectory it’s in). Extension might be customizable also (`index.rss`, `feed.rss`)

**Comment by felixfontein** [comment]
That would result in two new options:
* one for defining the RSS extension (affects all RSS feeds);
* one for defining the stub for `RSS_PATH` (affects the indexes taxonomy only).

So the documentation for `RSS_PATH` would change to something like this:
``` .py
# output / TRANSLATION[lang] / RSS_PATH / RSS_PATH_BASE . RSS_EXTENSION
```
Any better suggestions for `RSS_PATH_BASE` or `RSS_EXTENSION`?

**Comment by felixfontein** [comment]
Similar changes for Atom feeds will be required; these should probably go into #3015.

**Comment by Kwpolska** [comment]
`RSS_FILENAME_BASE` perhaps?

**Comment by felixfontein** [comment]
It only applies to indexes RSS, though, and not to any other RSS feed.

**Comment by Kwpolska** [comment]
`MAIN_RSS_FILENAME_BASE`?

**Comment by felixfontein** [comment]
Since it is tightly coupled to `RSS_PATH`, why not `RSS_PATH_FILENAME_BASE`?

**Comment by Kwpolska** [comment]
That could work too.

**Comment by felixfontein** [comment]
It's not that elegant, but I guess more user-friendly since it doesn't deviate too much from `RSS_PATH`.

**Comment by felixfontein** [comment]
Actually, what I said wasn't correct: there are two more places where `rss.xml` is hardcoded. Namely, for sections and for galleries.

**Comment by felixfontein** [comment]
I'll switch to `RSS_FILENAME_BASE`, then.
