### ISSUE TITLE
Hackerthemes?

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#3049]
These look nice and could be a worthwhile addition: https://hackerthemes.com/new-bootstrap-themes/
Perhaps replace bootswatch_theme with `microtheme` that supports bootswatch and hackerthemes logic? (ht sometimes needs extra resources, which YAML config could help provide)

**Comment by ralsina** [comment]
Nice!

I can do this rather quick for v8

**Comment by ralsina** [comment]
Hmmm I have a "working version". The problem is taht to use them, at least the ones I saw you need to use extra classes. Let me put up a PR and then we can talk about it.

**Comment by Kwpolska** [comment]
@ralsina can we close this?

**Comment by ralsina** [comment]
Ah, sure!
