### ISSUE TITLE
Why no crumbs.tmpl in base templates?

### ISSUE THREAD

**Issue by tbm** [getnikola/nikola#3056]
v7 had a `crumbs.tmpl` in the base templates but this is no longer the case with v8.  Is there a good reason for this?

**Comment by Kwpolska** [comment]
The file `crumbs.tmpl` was renamed to `ui_helper.tmpl` and the breadcrumbs function was renamed to `breadcrumbs`.

**Comment by tbm** [comment]
So why do the jinja templates still have crumbs.tmpl?

```
./lib/python3.5/site-packages/nikola/data/themes/bootstrap4-jinja/templates/crumbs.tmpl
./lib/python3.5/site-packages/nikola/data/themes/base-jinja/templates/crumbs.tmpl
```

**Comment by Kwpolska** [comment]
Thanks for pointing it out, our scripts don’t remove templates while jinjifying (not worth adding IMO). Removed in 169c350a.
