### ISSUE TITLE
Do installs from GitHub master.zip files work?

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#3059]
I tried using https://github.com/getnikola/nikola/archive/master.zip to install Nikola on the VPS. I couldn’t get it to work properly, as the JS files had references to `../npm_assets` in it instead of the actual contents.

Is this some kind of bug? Do we need extra handling like we do for Windows?

**Comment by ralsina** [comment]
Does the tar.gz work?

**Comment by Kwpolska** [comment]
`zipfile` seems to lack support for symlinks: https://bugs.python.org/issue18595

someone else’s bug.  I think it’s not worth reporting to pip.

**Comment by ralsina** [comment]
It's good that some issues are not ours.
