### ISSUE TITLE
Is webassets really required?

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#3074]
We currently just use `webassets` as a glorified `cat`. We should make it also minify stuff, or get rid of it and do the concatenation ourselves.

**Comment by ralsina** [comment]
Since it also supports less/sass and other things, we could get rid of that part of our code.

OTOH I don't see how :-/

**Comment by felixfontein** [comment]
It would be nice to be able to be able to specify filters for specific files (like a CSS filter only for `output/assets/css/all.css`, so that the input CSS files aren't touched before being concatenated). Then everything webassets can do more than being a glorified `cat` could be done that way.

**Comment by arunikayadav42** [comment]
can i get started with this issue :)

**Comment by Kwpolska** [comment]
Sure, go ahead!

**Comment by arunikayadav42** [comment]
as an initial step can I please know how can I get started...I am newbie to open source :)

**Comment by Kwpolska** [comment]
Start with [GitHub help](https://help.github.com/) and our [Contribution guide](https://github.com/getnikola/nikola/blob/master/CONTRIBUTING.rst) and don’t hesitate to ask if you have any other questions.

**Comment by arunikayadav42** [comment]
Sure :)
