### ISSUE TITLE
korean snipplet already updated on transifex but not updated on nikola

### ISSUE THREAD

**Issue by icq4ever** [getnikola/nikola#3075]
some of korean sniplets are already updated on transflex, 2 years ago, but it's not updated to nikola.

 https://www.transifex.com/ralsina/nikola/viewstrings/#ko/messages/11425275

could you update this ?

**Comment by Kwpolska** [comment]
Which messages? Are you on the latest version of Nikola? The translations for Korean were last updated in v7.8.13 (March 20th).

https://github.com/getnikola/nikola/blob/master/translations/nikola.messages/ko.po https://github.com/getnikola/nikola/blob/master/nikola/data/themes/base/messages/messages_ko.py

**Comment by icq4ever** [comment]
oh. ok. I'll gonna check version. 
thanks.

**Comment by arturoc** [comment]
i'm using the latest nikola with:

```
pip --install --upgrade "nikola[extras]"
```

and still getting this. is there anyway to get a newer version?

**Comment by Kwpolska** [comment]
Okay, it turns out the Korean translations didn’t make it, probably due to an issue with backporting changes. However, this is already fixed in Nikola v8 (now at beta 1), so you can use `pip install -U 'nikola==8.0.0.b1'` — or just upgrade `messages_ko.py`
