### ISSUE TITLE
post-list vs post_list

### ISSUE THREAD

**Issue by tbm** [getnikola/nikola#3083]
Is it `post-list` or `post_list`?

With 8.0.0ebta1, this:
```
{{% post-list categories=phd %}}{{% /post-list %}}
```

 gives:

```
[2018-05-09T17:21:03Z] ERROR: Nikola: Unknown shortcode post-list (started at line 1, column 1)
```

This works:

```
{{% post_list categories=phd %}}{{% /post_list %}}
```

I don't know if this is a RST vs Markdown difference but the manual shows `post-list` even for the non-RST example.

**Comment by Kwpolska** [comment]
There might be a reason for using dashes in the reST thing, or there might not. But yes, supporting both ways would be nice if possible.
