### ISSUE TITLE
custom.css needs !important to override CSS with bootstrap4

### ISSUE THREAD

**Issue by tbm** [getnikola/nikola#3089]
This is with 8.0.0.beta1.

I'm by no means a CSS expert so maybe I'm doing something wrong.  With v7 I was easily able to override a number of things with a `files/assets/css/custom.css`.  But after upgrading to bootstrap4 and v8, when I updated my CSS the change would show up when I inspect it in the browser but it would be crossed out.  I have no idea how to find out what overrides it and this surprised me because I thought my local.css should override everything else.  In the end, I figured out that adding `!important` makes it work but that shouldn't be necessary imho.

Examples:

```
.bg-dark {
    background-color: #2C3E50!important;
}

li.nav-item>.active>a, li.nav-item>a:focus, li.nav-item>a:hover {
    color: #fff!important;
    background-color: #294867;
}

/* Make text easier to read on the dark background */
.navbar-nav .nav-link {
    color: #DDD!important;
}
```

**Comment by Kwpolska** [comment]
Any issues would be Bootstrap’s fault, not ours. `custom.css` is still the last in hierarchy. In [bootstrap4.css](https://getbootstrap.com/docs/4.1/dist/css/bootstrap.css), `.bg-dark` uses `!important`, so you need another `!important` to override that. Navbars seem to be using `.navbar-light .navbar-nav .nav-link` to refer to the link, which is apparently more important than `li.nav-item > .active`. You should be able to find this out by reading the CSS source, or seeing what CSS is used in the Inspector.

**Comment by Cutuchiqueno** [comment]
Spending 2 hours to understand this but accepting the argument that this is 'bootstraps' fault I still think that the documentation:

> CSS tweaking Using the default configuration, you can create a assets/css/custom.css file under files/ or in your theme and then it will be loaded from the <head> blocks of your site pages. Create it and put your CSS code there, for minimal disruption of the provided CSS files.

should at least mention this, not least because Bootstrap and Bootblog are the default Nikola themes.

**Comment by Kwpolska** [comment]
The documentation is accurate. You *don’t* need `!important` everywhere. There are, however, a few places, in which bootstrap4 itself uses an `!important` directive, so you need to add `!important` to override that. Nikola’s documentation is not the right place IMO for explaining how CSS works.
