### ISSUE TITLE
Should NAVIGATION_LINKS/NAVIGATION_ALT_LINKS allow a title?

### ISSUE THREAD

**Issue by tbm** [getnikola/nikola#3090]
I had social media link in my footer and I'm moving them to the new `NAVIGATION_ALT_LINKS`.  In the footer, I used a `title` on the `a href` to explain what the icon means:

```
<a href="https://github.com/tbm" title="Martin's GitHub"><i class="fab fa-github"></i></a>
```

afaik NAVIGATION_LINKS/NAVIGATION_ALT_LINKS doesn't allow to specify a `title`. While this might not be that useful for NAVIGATION_LINKS I think it would be quite useful for NAVIGATION_ALT_LINKS.  I wonder if it makes sense to add a 3rd (optional) element to the tuple for the title or is there a better way to handle this?

**Comment by Kwpolska** [comment]
Doing it in templates, as an optional thing, requires too much code and effort. You can easily modify your templates if you want titles for all entries though.
