### ISSUE TITLE
Default font in bootstrap4 too big?

### ISSUE THREAD

**Issue by tbm** [getnikola/nikola#3091]
This is a strange issue for me to report because I love big fonts, but when moving from v7 to v8 I noticed the font is much bigger. IMHO it's a bit too big.

v7: http://www.cyrius.com/contact/
v8: http://cyrius.netlify.com/contact/

What do you think?

**Comment by Kwpolska** [comment]
Sorry, but we don’t take complaints about Bootstrap’s design choices. They use the default font size of your browser, the default value of which is 16px.

I fix this on [chriswarrick.com](https://chriswarrick.com/) by setting `0.875rem` as the base font size (=14/16 rem = 14 px on default settings), but that also requires building bootstrap manually, which requires a ton of NodeJS garbage on the developer side, and might not be ideal for people who changed their browser settings.

**Comment by tbm** [comment]
Ok, I understand that. I tried to find out the other day what and how bootstrap is designed but when I went to their web site it was mostly about design elements (like the big box whose name I forgot) and not a complete theme.  i.e. it was more about building blocks to create your own theme, so I'm surprised the font size comes from them.  I guess I have to check bootstrap again.

**Comment by Kwpolska** [comment]
The `bootstrap4` theme design is 98% bootstrap, 1% reST css, 1% our modifications to both.

**Comment by Kwpolska** [comment]
Actually, it looks like all you need is [`html { font-size: 14px }`](http://getbootstrap.com/docs/4.1/content/typography/#responsive-typography) in custom.css.

**Comment by michaelb42** [comment]
Nope, that will not work. bootstrap uses derived and calculated values for everything. If you really want to change the size of the fonts for text, headings, etc. you have to either override them all in your own css or you simply change the base value in _variables.scss. And this is true not only for fonts but for colors, margins, padding, and so on. Theming bootstrap using css only means re-writing bootstrap with css.

**Comment by Kwpolska** [comment]
Bootstrap 4 uses rem font units, [relative to the value of the html tag](https://snook.ca/archives/html_and_css/font-size-with-rem) (default in most browsers = 16 px). Most values in Bootstrap use rem units. You can try it out yourself by going to [any article on chriswarrick.com](https://chriswarrick.com/blog/2016/02/10/deploying-python-web-apps-with-nginx-and-uwsgi-emperor/), opening Web Inspector, and modifying the font-size specified for `html` — and observe that everything looks fine after changing it.
