### ISSUE TITLE
bootstrap4: contains description twice in meta

### ISSUE THREAD

**Issue by tbm** [getnikola/nikola#3092]
validator.w3.org complains:

```
A document must not include more than one meta element with its name attribute set to the value description
```

and

```
Attribute itemprop not allowed on element meta at this point
```

bootstrap4/templates/base_helper.tmpl includes the description but bootstrap4/templates/post.tmp includes it again.  I'm not sure about the difference of `description` and `post.description()` but in my case the same gets included twice.

It seems bootstrap4 is the only theme that adds a description in post.tmpl so maybe this is just an oversight.

**Comment by Kwpolska** [comment]
I have no idea why I put the description in post.tmpl. Fixed, thanks for pointing this out.

**Comment by tbm** [comment]
Thanks.  FWIW I see no other validation issues with bootstrap4.
