### ISSUE TITLE
`default_config` produces Python-like unescaped output when sent to a file in Windows

### ISSUE THREAD

**Issue by sukiletxe** [getnikola/nikola#3094]
### Environment (if reporting a bug)

**Python Version:** 3.6.4

**Nikola Version:** 8.0.0b2

**Operating System:** Windows

### Description:

If I do:
`nikola default_config > conf2.txt`
I get a single line starting with:
`b'# -*- coding: utf-8 -*-\n\nimport time\n\n`

**Comment by Kwpolska** [comment]
It should work better now, although do note that, since we have some Unicode characters in our default config, one won’t be able to read the file with cmd.exe. (We recommend reading it on the web at https://getnikola.com/conf.html anyway.)

**Comment by sukiletxe** [comment]
Oh, no worries. I use it for diffs.
