### ISSUE TITLE
Changing multilingual behavior? 

### ISSUE THREAD

**Issue by MAlacAM** [getnikola/nikola#3101]
Hello, 
Thanks for nikola, I am liking it a lot, except: 
I am writing a multilingual blog (2 languages), and wanted to ask whether it would be at all possible to change the behavior so it would allow posts in exclusively one language. These shouldn't show up at all on the other language. For example `mysite.net/en` would show `post1, post2, post_only_en` and `mysite.net/tr` would show `post1(tr), post2(tr), post_only_tr`. Basically that would probably mean not having a default language? Is it doable?

**Comment by ralsina** [comment]
Check the SHOW_UNTRANSLATED_POSTS option, I think setting it to False does exactly what you want.

I am closing the issue, feel free to comment if that is not the case and I will reopen.

**Comment by MAlacAM** [comment]
Thank you! Exactly what I needed.
