### ISSUE TITLE
Missing "notebook" div in Jupyter Notebook HTML output.

### ISSUE THREAD

**Issue by KelSolaar** [getnikola/nikola#3102]
### Environment (if reporting a bug)

**Python Version:** 3.6

**Nikola Version:** Nikola v8.0.0b2

**Operating System:** macOS

### Description:

I'm porting our website to Nikola v8.x.x and I noticed that the Jupyter Notebook conversion does not produce the same HTML output compared to Nikola v7.x.x, most notable is the missing `div` with the `notebook` id that I was using to inject it into another page:

``` html
<div tabindex="-1" id="notebook" class="border-box-sizing">
```

Nikola v7.x.x:

![image](https://user-images.githubusercontent.com/99779/41200581-3b90d930-6cfb-11e8-8cbe-76de6bb44481.png)

Nikola v8.x.x:
![image](https://user-images.githubusercontent.com/99779/41200600-c34cba9c-6cfb-11e8-80f6-a142d864b489.png)

**Comment by Kwpolska** [comment]
Expected behavior — on an index page, more than one `#notebook` would appear. You can just grab `.entry-content` and will get the notebook.

**Comment by KelSolaar** [comment]
AFAIK there is (was in v7.x.x) only one `div` with the `notebook` id, e.g. https://github.com/colour-science/colour-science.org/blob/a467a6a9479abc03ed150997294a2b786f209f58/output/colour-science-for-python/index.html#L229

`.entry-content` content is a class here not an id, I won't be able to load it with [JQuery load](http://api.jquery.com/load/).

**Comment by Kwpolska** [comment]
The error with multiple divs would appear if *posts* on your blog (not pages) were notebooks. Blog indexes could then contain >1 ipynb posts.

And from jQuery.load docs, I can understand that `$("#foo").load("bar.html .entry-content");` is valid syntax as well. That said, you can change your `story.tmpl` template to add an id to the story container if you need that.

**Comment by KelSolaar** [comment]
`.entry-content` worked! That's great, thanks 👍
