### ISSUE TITLE
Relative assets paths break custom 404 page.

### ISSUE THREAD

**Issue by KelSolaar** [getnikola/nikola#3103]
### Environment (if reporting a bug)

**Python Version:** 3.6

**Nikola Version:** Nikola v8.0.0b2

**Operating System:** macOs

### Description:

This is maybe an edge case but as I came across it I thought I would report it. We have custom nginx served 404 page: http://colour-science.org/404/. It is generated as a regular page so that we have the navbar, footer, etc... and nginx simply redirects to it. Now what is happening is that any levels nested url will break rendering of the 404 page because the assets (CSS & co) are referenced relatively:

*Assets*
![image](https://user-images.githubusercontent.com/99779/41285328-e838da44-6e8f-11e8-865d-b322782c8918.png)

*Relative References*
![image](https://user-images.githubusercontent.com/99779/41285367-0339e87e-6e90-11e8-93bc-0f23bb616f2e.png)

Is there a way to build the pages with absolute urls to all the assets, e.g. could `URL_TYPE` also deal with assets?

Cheers,

Thomas

**Comment by ralsina** [comment]
AFAIK URL_TYPE *should* also work for assets.

**Comment by Kwpolska** [comment]
Set `.. url_type: full_path` in the metadata of your 404 page.

**Comment by ralsina** [comment]
@Kwpolska we support that? That's so cool! :-)

**Comment by sukiletxe** [comment]
Iirc that’s not documented.

**Comment by KelSolaar** [comment]
Yep!

**Comment by Kwpolska** [comment]
Added to docs in commit ff58f5e0.
