### ISSUE TITLE
Hide a tag/category from the main index

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#3105]
Use case:

* I tweet
* I want a copy of my tweets for archival purposes
* I don't want to have 30 new out-of-context tiny posts appear in my blog

So!

If it was possible to mark a tag or category as "hidden from the main index" and then use that tag/category in the posts generated by [continuous_import](https://plugins.getnikola.com/v7/continuous_import/) from my twitter feed, I would have what I want.

**Comment by felixfontein** [comment]
How about adding a new metadata variable for that instead (or having that possibility, too, next to hide via tag/category)?

**Comment by ralsina** [comment]
@felixfontein isn't that the private metadata?

**Comment by sukiletxe** [comment]
@ralsina I thought the same thing when reading @felixfontein's comment. Reading the description from the handbook and without reading the source code, I think that the private metadata would make the post disappear from *all* indexes (like if it was tagged `cat`, the tag wouldn't have it listed). I could be wrong, though.

**Comment by felixfontein** [comment]
Yes, that's I think the difference: private hides it from *all* indexes, while the new feature (however it will be implemented) should only hide it from the main index.

(If we want to hide it from (almost) all indexes, we could also make it a page ;-) )

**Comment by ralsina** [comment]
@felixfontein yes, but I want there to be an index, just not the main one :)

I am leaning towards a specific metadata field that hides posts from just the main index, anot not doing it based on tags/categories.

**Comment by ralsina** [comment]
Since I asked for it and I did not implement it, looks like this was not needed after all.

**Comment by mardy** [comment]
I'm actually looking for something like this (about the same use-case: webmention replies). How did you end up solving this?

I think I'll use the `private` tag, but if I could mark a category as belonging to microblogging, it would be cleaner.

This is also be related to #3408: while it is possible to do micro-blogging with Nikola, there is room for a specialized feature.

**Comment by ralsina** [comment]
@mardy I just gave up :-D

**Comment by mardy** [comment]
What if we added a couple of options to the conf file like `HIDE_POSTS_WITH_TAGS = []` and `HIDE_POSTS_WITH_CATEGORIES = []`, that one might use like this, for example:

    HIDE_POSTS_WITH_CATEGORIES = ["replies", "likes"]
    
This would hide all the posts having the "replies" or "likes" category from the `posts` variable, but still generate indexes for the "replies" and "likes" categories, where these posts would be indexed.

Do you think it's a task I could try to take on, or does it sound too hard to implement?

**Comment by JesperDramsch** [comment]
In case this ever happens, I'd be quite interested too.
