### ISSUE TITLE
Replace virtualenv + pip with pipenv in documentation

### ISSUE THREAD

**Issue by leingang** [getnikola/nikola#3107]
Right now the Getting Started documentation suggests the following sequence of commands to install Nikola:

```
$ virtualenv3 nikola
$ cd nikola
$ source bin/activate
$ pip install --upgrade pip setuptools wheel
$ pip install --upgrade "Nikola[extras]"
```

I use [`pipenv`](https://docs.pipenv.org/) now— it's supposedly python's officially recommended tool for managing virtual environments and packages.  So the above sequence can be shortened to

```
$ mkdir nikola
$ cd nikola
$ pipenv install "Nikola[extras]"
```

**Comment by Kwpolska** [comment]
Pipenv is:
* A garbage product that does too much magic and often fails at it
* Not officially recommended, that's a propaganda lie by KR; it's one of
the possibilities listed in the docs
* Maintained by a crazy person

As such, this request will not be granted.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by leingang** [comment]
Thanks, I appreciate your frankness.  So far it's worked for me, but if others haven't had the same experience it doesn't make any sense to recommend it.
