### ISSUE TITLE
Add ability to hide the "also available in..." block of a post

### ISSUE THREAD

**Issue by sukiletxe** [getnikola/nikola#3109]
### Environment (if reporting a bug)

**Python Version:**

**Nikola Version:**

**Operating System:**

### Description:

In [my blog](https://www.sukiletxe.eu) I have pages which simulate auto-generated ones (individual archives for two sections). It would be useful, in those pages, to not show the "Also available in..." block.

**Comment by Kwpolska** [comment]
Create a custom template that doesn’t display the unwanted information. You’ll probably want to make other modifications to these as well, the option doesn’t seem that useful to me.
