### ISSUE TITLE
pages compiled with .. template: option fail

### ISSUE THREAD

**Issue by ookimi** [getnikola/nikola#3114]
### Environment (if reporting a bug)

**Python Version:** 3.6

**Nikola Version:** 8.0.0b2

**Operating System:** Ubuntu 16.04

### Description: 

I am trying to use a custom template for some of site pages. According to the documentation, this is done with the template tag in the header of a ReST file. However, the pages compiled with this option in the header come out empty no matter what template is used.  This happens even if I simply specify the default base.tmpl template (that works perfectly on the same page), or copy its contents into my new template.

```
.. template: base.tmpl
```

In the generated page, the footer and header are preserved, but no content:

``` html
<div class="container" id="content" role="main">
<div class="body-content">
<!--Body content-->

 <!--End of body content-->
```
I tried this with Lanyon and Boostratp4 Mako themes.

**Comment by sukiletxe** [comment]
Can you give us more info on what you're trying to achieve? As base.tmpl doesn't call the post object, it is expected to render an empty post.
Also, are you putting the template file in templates/ ?

**Comment by ralsina** [comment]
Templates in the metadata work, I just checked it.

If you want an example of how the feature works, check this document:

https://getnikola.com/creating-a-custom-page.html

If you want to see it in action, just create the demo site:

```
nikola init --demo demosite
```

If you build it, you will see in the frontpage a link to "see a demo of a longer text".
That should be something like this: https://themes.getnikola.com/v8/bootblog4/demo/pages/dr-nikolas-vendetta/ (which I need to fix a little)

That is a page using this custom template: https://github.com/getnikola/nikola/blob/master/nikola/data/samplesite/templates/book.tmpl

And here you can see it in the page's metadata: https://raw.githubusercontent.com/getnikola/nikola/master/nikola/data/samplesite/pages/dr-nikolas-vendetta.rst

**Comment by ookimi** [comment]
Yes, it is in /templates - otherwise it complains that it can't find the template.

I'm trying to do a version of that base template with a different styling and an additional navbar, so I assumed that making a copy of the base.tmpl and modifying it is the way to go. 

Ok, so I see that base.tmpl is missing the actual content element. I am struggling to find what it is, though. [The list of template variables](https://getnikola.com/template-variables.html#global-variables) suggests that it's "post", correct? So it should be something like this: 

```html
<div class="container" id="content" role="main">
    <div class="body-content">
        <!--Body content-->
        ${template_hooks['page_header']()}
        <%block name="content">

        ${template_hooks['post']()}   <!-- missing part? --->

        </%block>
        <!--End of body content-->

        <footer id="footer">
            ${content_footer}
            ${template_hooks['page_footer']()}
        </footer>
    </div>
</div>
```

That doesn't work though, Nikola yields a KeyError for "post". My page is in /pages, not in /posts, but there doesn't seem to be any other value.

What should it be?

**Comment by ralsina** [comment]
If you want to replace your site's base.tmpl just put a copy in templates/
and modify it, that will change your base template for the whole site.

If you want a single page with a completely different layout from the rest
of the site you can use a custom template like in the examples I mentioned
and have that template not extend any others. That will be a lot of work,
but it can be done.

You would need to do all base.tmpl does and replace the content block with
one like the one in post.tmpl, for example.

**Comment by Kwpolska** [comment]
Template hooks are not template variables. To display the post text, you
need `${post.text()}`. To make it work properly, you should take the
content block from story.tmpl and insert it in your new template file.

-- 
Chris Warrick <https://chriswarrick.com/>
