### ISSUE TITLE
Math is not rendered at all

### ISSUE THREAD

**Issue by sebelk** [getnikola/nikola#3116]
### Environment

**Python Version:** python 3.6.5

**Nikola Version:**  v7.8.15

**Operating System:** Fedora 28

### Description: 

I've tried with no success math, for example:
~~~~
.. title: ejemplo
.. slug: ejemplo
.. date: 2018-07-09 22:56:25 UTC
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
.. has_math: true

.. math::

   \int \frac{dx}{1+ax}=\frac{1}{a}\ln(1+ax)+C


\[\int \frac{dx}{1+ax}=\frac{1}{a}\ln(1+ax)+C\]

$$f(x) = x^2 - 4$$


Euler’s formula: :math:`e^{ix} = \cos x + i\sin x`

$$P(A_i|B) = \frac{P(B|A_i) P(A_i)}{\sum_{k=1}^n P(B|A_k) P(A_k)}.... [1]$$

$$C^{n}_p=\binom{n}{p} = \frac{n!}{p!(n-p)!}$$


~~~~

None of these of lines are rendered, For example, the last one I expect to see, something like this:

![imagen](https://user-images.githubusercontent.com/4109256/42480710-34a5cc40-83b5-11e8-9396-17398cea22de.png)

Please could you help me? Am I doing something wrong?

Thanks in advance!

**Comment by felixfontein** [comment]
`.. has_math: true` only works in Nikola v8 (currently beta). You have to add a tag "mathjax" to your post for this to work in Nikola v7.

**Comment by sebelk** [comment]
Thanks @felixfontein ! I didn't know that you were talking about tags metafield. Now it works! However I will upgrade to version 8 asap.
