### ISSUE TITLE
nikola auto does not respect OUTPUT_FOLDER

### ISSUE THREAD

**Issue by mforbes** [getnikola/nikola#3119]
In Nikola v8.0.0b2 there is a hard-coded `'output/'` that should be `out_folder`:

[nikola/plugins/command/auto/__init__.py#L204](https://github.com/getnikola/nikola/blob/master/nikola/plugins/command/auto/__init__.py#L204)

This causes `nikola auto` to fail if `OUTPUT_FOLDER` is not `'output'`.

**Comment by ralsina** [comment]
You are correct, sir!

I'll do a quick fix later today.
