### ISSUE TITLE
Issues on Arch Linux (PKGBUILD and UnicodeDecodeError)

### ISSUE THREAD

**Issue by odysseusPolytropos** [getnikola/nikola#3121]
Hi folks!

I tried to install nikola (and nikola-git) on my up-to-date Arch Linux and ran into several problems:

### Environment

**Python Version:*3.6.6*

**Nikola Version:*7.8.15-1* and *8.0.0b1.r0.gc48c3861-1*

**Operating System:*Arch Linux*

### Description:
1. PKGBUILD does not seem to be valid, when trying to install it (with yaourt) it mocks about invalid characters '>=' and '=' in the optdepends section. A brief look into [the Arch wiki on PKGBUILD](https://wiki.archlinux.org/index.php/PKGBUILD#optdepends) suggests that there are no version restrictions allowed in optdepends, since it is a plain information format. Removing the >=[VERSION]-number suffixes did the trick for me. I'm not an expert on PKGBUILDs, but it looks to me like this should be fixed.

2. When trying to execute nikola, e.g.
`nikola init --demo nikolatest`
I get long stacktrace ending with
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 37: ordinal not in range(128)
Error loading mako template system plugin. (Uploading full error log does not work at the moment for some reasons, here is a [pastebin](https://pastebin.com/bbQ0G3Ce)).

I read this [blogpost on unix locales](https://chriswarrick.com/pl/blog/2017/06/18/unix-locales-vs-unicode/) but could not figure out what is wrong with my setup.
`[user@computer]$ locale`
> LANG=de_DE.utf8
LC_CTYPE="de_DE.utf8"
LC_NUMERIC="de_DE.utf8"
LC_TIME="de_DE.utf8"
LC_COLLATE="de_DE.utf8"
LC_MONETARY="de_DE.utf8"
LC_MESSAGES="de_DE.utf8"
LC_PAPER="de_DE.utf8"
LC_NAME="de_DE.utf8"
LC_ADDRESS="de_DE.utf8"
LC_TELEPHONE="de_DE.utf8"
LC_MEASUREMENT="de_DE.utf8"
LC_IDENTIFICATION="de_DE.utf8"
LC_ALL=

I also tried to set `LOCALE_DEFAULT = "en_US.UTF-8"` as well as `de_DE.UTF-8` in `/usr/lib/python3.6/site-packages/nikola/conf.py.in`, with no change in result.

At last I tried to install nikola in a virtualenv, which worked, therefore I suspect this is not really a locale-problem but some sort of packaging problem/incompatibility between expected and current version (at least in Arch Linux) of python packages.

If additional details about my system config or logs are desired, I'm willing to provide them of course.

Many regards
odysseus

**Comment by Kwpolska** [comment]
And now, onto the locale issue. Can you verify that `locale -a` shows the `de_DE.utf8` locale? What locales does it show?

What Python and Nikola versions was the virtualenv using?

(PS. `conf.py.in` is only a template for `nikola init`, we don’t use it at runtime.)

**Comment by Kwpolska** [comment]
Could you try enabling the `en_US.UTF-8` locale and see if it works then?

**Comment by odysseusPolytropos** [comment]
> Could you try enabling the en_US.UTF-8 locale and see if it works then?

Yes, after enabling `en_US.UTF-8` in /etc/locale.gen and regenerating locales with locale-gen `nikola init` suddenly works. I'm not too familiar with locales, I guessed from the obove mentioned blog post that only some UTF-8 config is required not `en_US.UTF-8` in particular.

It's also not too clear to me, why the virtualenv-version worked, since it is the same nikola version (7.8.15). Maybe one of the dependencies has another version, that requires `en_US.UTF-8` to be present?

**Comment by Kwpolska** [comment]
No, that isn’t it. Could you pastebin the full error log though? I really don’t know why it would fail like this.

**Comment by odysseusPolytropos** [comment]
The error log stays the same as the obove [pastebin](https://pastebin.com/bbQ0G3Ce), I also tried to set NIKOLA_DEBUG and NIKOLA_SHOW_TRACEBACKS to 1 with no change in error log. Nikola only fails on different plugins every time (looks like yapsy does not have a particular order, when loading them):

> `[2018-07-23T12:39:13Z] ERROR: yapsy: Unable to import plugin: /usr/lib/python3.6/site-packages/nikola/plugins/XYZ`

**Comment by Kwpolska** [comment]
I think falling back to the system xx_XX.UTF-8 locale would be a better idea, at least for non-configured sites.

**Comment by odysseusPolytropos** [comment]
I'm not sure if nikola is really the culprit here. I tried to install (the latest head) with the setup.py and it worked fine even without setting en_US.UTF-8 in my locale.gen. What

**Comment by Kwpolska** [comment]
Well, this could very well be a bug that was fixed in v8. If `nikola-git` works, then everything should be fine.

Let’s sum this up. Does Nikola work, without the en_US locale, if you install:

* `nikola` from AUR?
* `nikola-git` from AUR?
* `pip install nikola==7.8.15` in a virtualenv?
* `pip install nikola==8.0.0b2` in a virtualenv?

**Comment by Kwpolska** [comment]
I’ll have to try some debugging myself. One last question: what is your fstab/partition layout? Is there any chance they’re on differently configured partitions?

---

This is the issue you’re observing:

1. Nikola starts up fine and has a German UTF-8 locale.
2. Nikola goes through the locale setup, and switches to C, because you don’t have an English locale on your system.
3. Nikola then tries to import plugins (through yapsy), but somehow, ascii is used to read the files, not utf-8. (Why? LC_CTYPE tends to affect it, but have the old coding: utf-8 headers stopped working in py3?)
---

There are three fixes I can think of:

1. Don’t change the locale for site-less runs (eg. `nikola init`, but not `nikola build`)
2. Grab the locale list and pick a UTF-8 locale, although not when building
3. Switch to Babel and avoid all system locale issues (#2606)

**Comment by odysseusPolytropos** [comment]
> One last question: what is your fstab/partition layout? Is there any chance they’re on differently configured partitions?

My `/etc/fstab` is:

\# /dev/mapper/volgroup0-lv_root
UUID=[some_long_id]	/         	ext4      	rw,relatime,data=ordered	0 1

\# /dev/sda1
UUID=[some_long_id]	/boot     	ext2      	rw,relatime,block_validity,barrier,user_xattr,acl	0 2

\# /dev/mapper/volgroup0-lv_home
UUID=[some_long_id]	/home     	ext4      	rw,relatime,data=ordered	0 2

So, yes things are partly happening on different partitions, since /home is separated and I used the virtualenvironments in my home folder. I am not aware that there is a difference between the partitions configured (and they are on the same physical hard drive). Now I also tried the following
1. pip installation in an virtualenv in `/opt/nikola_test_venv` -> works
2. Directly cloning into `/opt/nikola.git` and executing `setup.py install` -> works
3. One of the PKGBUILDs in `/opt/nikola_pkgbuild` with `pkgbuild -si` -> does not work

Thanks for the explanation. What still confuses me here is that it seems to make a difference if I use `makepkg` with the PKGBUILD or install via `setup.py install`.

**Comment by odysseusPolytropos** [comment]
Just tested reinstalling `nikola-git` on my system and it just works. Thanks for investigating and fixing!
