### ISSUE TITLE
Headings are not rendered correctly from rst

### ISSUE THREAD

**Issue by d-s-e** [getnikola/nikola#3124]
### Environment:
**Python Version:** 3.6.6
**Nikola Version:** 8.0.0b2
**Operating System:** Arch Linux

### Description:
When I start a post with a heading (after all the meta tags), then this heading is ignored.
If I add some text before the heading - one non-whitespace character is enough - the heading is rendered in the output as it should be.

**Comment by ralsina** [comment]
In reSt a single unique heading at the beginning of a document is special and becomes the document title.

**Comment by Kwpolska** [comment]
We ignore that document title in Nikola, unless you explicitly enable that (`USE_REST_DOCINFO_METADATA`).

**Comment by Kwpolska** [comment]
I can think of a better way to handle this.
