### ISSUE TITLE
How do I insert special unicode characters like a non-breaking space into a rst file?

### ISSUE THREAD

**Issue by d-s-e** [getnikola/nikola#3125]
### Environment:
**Python Version:** 3.6.6
**Nikola Version:** 8.0.0b2
**Operating System:** Arch Linux

### Description:
Sometimes it is necessary to add non-breaking spaces to get a better test formatting, when the page is viewed on a small display. Inserting the chars as &nbsp; or \0xa0 is not working.
I tried to use a rst substition, but that's not working, too:

```rst
.. |nbsp| unicode:: 0xa0
   :trim:

foo |nbsp| bar
```

Is this even possible? Should it be done in completely different way?

**Comment by Kwpolska** [comment]
You should be able to type the character as a regular Unicode codepoint into the file (copied from [Wikipedia](https://en.wikipedia.org/wiki/Non-breaking_space) or otherwise).

**Comment by Kwpolska** [comment]
> Yes, that works, but then I don't see, if a space is non-breaking or a regular one, because it looks the same in the rst file.

That depends on editor config, for example, vim + vim-sensible displays nbsp as a grey + sign.

> I was hoping there is a better way.

I don’t think there is. As you might have noticed, reST is a rather specific format. (You can also use HTML or Markdown if you prefer.)

**Comment by d-s-e** [comment]
Ok. I'm using rst because it has some advantages over Markdown.
Thanks anyway!

**Comment by ralsina** [comment]
Hmmm I tried your very example and it does work:

```
.. |nbsp| unicode:: 0xa0
   :trim:

This is a |nbsp| here.
```

When using rst2html, this produces this:

```
<p>This is a&nbsp;here.</p>
```

However, when using nikola it produces this:

```
<p>This is a here.</p>
```

Which may seem bad, BUT ... that is indeed a unicode unbreakable space there :-)

**Comment by felixfontein** [comment]
I'm also using the ReST substitution, and so far it worked fine for me (at least, it did the last time I checked :D ). Actually, I just checked again. My `|nbsp|` in a post body resulted in a `&nbsp;` in the output.

(BTW: I'm using `.. include:: common.rst` at the top of most posts to include things like the `|nbsp|` definition. Is there a shortcut for automatically including something? Or a way to do some global definitions in `conf.py` or in a plugin?)

**Comment by ralsina** [comment]
@felixfontein It would be easy-ish to write a plugin to do it, I think. Example:

https://github.com/getnikola/plugins/blob/master/v7/sphinx_roles/sphinx_roles.py#L563

I have a vague memory of that being done at some point for a config option defining substitutions but I can't find it.

**Comment by d-s-e** [comment]
Ok, I tried it again with a sample text and it suddenly worked. After some try and error I found the problem in the emphasis:

Working: `This is a |nbsp| here.`
Not Working: `*This is a |nbsp| here.*`

So the problem is the combination of the substitution with an emphasized text.

**Comment by ralsina** [comment]
@d-s-e ok, that is not going to work because reSt doesn't support nested markup.

**Comment by d-s-e** [comment]
Oh, after reading the documentation for the third time I'm finally seeing this, too.
Sorry for the noise.

**Comment by ralsina** [comment]
@d-s-e no problem
