### ISSUE TITLE
Templating in charts - Feature

### ISSUE THREAD

**Issue by MortalCatalyst** [getnikola/nikola#3129]
Regarding the chart directive https://www.getnikola.com/handbook.html#chart

Can we use templates with the charts?

So data could be stored as csv or json and not manually written?

**Comment by ralsina** [comment]
This is **so** close to working with the shortcode :-)

If you put your data in a json file and put that in the "data" metadata field, you could turn this:

```
{{% chart Bar title='Browser usage evolution (in %)' %}}
        x_labels='["2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012"]'%}}
        'Firefox', [None, None, 0, 16.6, 25, 31]
        'Chrome',  [None, None, None, None, None, None]
        'IE',      [85.8, 84.6, 84.7, 74.5, 66, 58.6]
        'Others',  [14.2, 15.4, 15.3, 8.9, 9, 10.4]
{{% /chart %}}
```

Into something like this:

```
{{% chart Bar title='Browser usage evolution (in %)' %}}
        x_labels='["2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012"]'%}}
        % for k, v in post.data.items:
        '${k}', ${v}
        % endfor 
{{% /chart %}}
```

Or something similar, perhaps more complicated (not tried it yet)

OTOH, I think it makes a lot more sense to just have chart support a data_file option that lets you specify everything in a file. Would that be ok?

**Comment by MortalCatalyst** [comment]
Yes having all options in a chart data file sounds good. 

Especially using it like you have it.
% for k, v in post.data.items():
        '${k}', ${v}

Makes it easy to adapt to a data flow.
