### ISSUE TITLE
galleries at top level, with no index generated?

### ISSUE THREAD

**Issue by evetsso** [getnikola/nikola#3133]
### Environment (if reporting a bug)

**Python Version:** 3.6.6

**Nikola Version:** v8.0.0b2

**Operating System:**  Arch Linux x86-64

### Description:

I've got a site that I'm trying to replace with a static one generated by Nikola.

Since SEO has already been working with the old URLs, I'd really like it if the image galleries could be at the top level, as they were in the site I'm replacing.  e.g. I want the site to have:
* index.html (main page)
* posts/post1/index.html (it's acceptable in my case if posts go into a subdirectory)
* page1/index.html
* gallery1/index.html (i.e. *not* in a `galleries` subdirectory)

I can get most of the way there by defining the output folder for galleries to an empty string in conf.py, e.g.:
```py
GALLERY_FOLDERS = {"galleries": ""}
```
But building the site fails because Nikola wants to generate an index for all of the galleries, and this will collide with the main index page for the site:
```
ERROR: Two different tasks can't have a common target.'output/index.html' is a target for render_taxonomies:output/index.html and render_galleries:output/index.html.
```
Would it be reasonable for the galleries plugin to handle this case more gracefully?  e.g. by only yielding a task to generate that index page if a non-empty output folder was specified?  I'm attaching a diff that works for me - if it would be accepted, then I can format it into a PR.

[gallery-toplevel.diff.txt](https://github.com/getnikola/nikola/files/2268907/gallery-toplevel.diff.txt)

Thanks!  If anyone can offer a suggestion for a better way to solve this problem, I'd happily use that too.

**Comment by evetsso** [comment]
Ok actually the diff I attached doesn't quite work yet.  Will keep hacking.  But is the core idea behind it ok?

**Comment by evetsso** [comment]
[gallery-toplevel-v2.diff.txt](https://github.com/getnikola/nikola/files/2268958/gallery-toplevel-v2.diff.txt)

Seems to work.

**Comment by Kwpolska** [comment]
Looks reasonable. Could you submit this as a Pull Request via GitHub?
