### ISSUE TITLE
Nikola auto should redirect directories to add trailing slash

### ISSUE THREAD

**Issue by undertherain** [getnikola/nikola#3140]
since #1430 is closed, please let me create another one. 
also not sure if it is related to docs or to rendering being erroneous.

I'm using Nikola v8.0.0b3, python 3.6.5 on ubuntu 18.04

I'm trying to create a hierarchical navigation menu by creating an entry like this in conf.py
```
    (
        (
            ('/fruits/apple', 'Apple'),
            ('/fruits/orange', 'Orange'),
        ),
        'Fruits'
    )
```
the site looks fine from index page, the links look like `127.0.0.1:8000/fruits/apple`,
but when I navigate to that page and check navbar again, the links become like `127.0.0.1:8000/apple`, the first part mysteriously disappears.

if I crate links like  `('fruits/apple', 'Apple')`, then from the subpage it becoms `/fruits/fruits/apple` :-\

**Comment by Kwpolska** [comment]
Cannot reproduce. What theme are you using and how do you test it? The link is supposed to be `href="apple"` on that page, but it still works, since we use relative links for everything by default.

**Comment by undertherain** [comment]
on the subpage (/fruits/apple) the link is rendered as
`<a href="../apple" class="dropdown-item">Apple</a>`
here's how it looks:
![index](https://user-images.githubusercontent.com/1635907/44246606-fac69300-a219-11e8-9679-4189522205c2.png)
![apple](https://user-images.githubusercontent.com/1635907/44246611-fef2b080-a219-11e8-96cc-19e93d4aefb7.png)

**Comment by undertherain** [comment]
and here's the source:
https://github.com/crest-deep/crest-deep.github.io/tree/src

**Comment by undertherain** [comment]
just checked other themes - same problem with bootblog4 and base

**Comment by undertherain** [comment]
I see... from /fruits/apple "../apple" interprets last piece as a file name, not a folder... 
adding / to the end helps, so does `URL_TYPE = 'full_path'`
now not sure if it is a bug or a feature :)

**Comment by Kwpolska** [comment]
1. We recommend putting a forward slash / at the end of links in the navbar
2. Changing URL_TYPE should not be necessary
3. This appears to be a bug in nikola auto, it should redirect from /foo to
/foo/

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by Kwpolska** [comment]
I’m taking over, PR coming in 5 minutes.
