### ISSUE TITLE
Gallery baguettebox does not show image until scrolled in bootstrap4

### ISSUE THREAD

**Issue by undertherain** [getnikola/nikola#3141]
Environment: Python 3.6.6,  Nikola v8.0.0b2, Ubuntu 18.04.
Only happens with bootstrap4 theme, works fine with bootblog4 and base themes. 

When clicking a thumbnail in automatically generated gallery, the baguettebox JS kinda opens the image view (current page becomes dim, close  icon  ("X") in top right corner appears, but the image itself is not visible. If I scroll left or right, the image immediately appears, and then it scrolls to next image which is also visible. If I scroll back - the original image is visible as well. Checked with FireFox and Chromium.

**Comment by undertherain** [comment]
Just noticed it also works if I resize browser window before clicking first time.

**Comment by undertherain** [comment]
also checked Nikola v8.0.0b3 - same problem.

**Comment by undertherain** [comment]
this is what appears in console btw
``` [Show/hide message details.] TypeError: Argument 1 of Node.removeChild is not an object.[Learn More] all-nocdn.js:23:5128
Y/f.onload
http://127.0.0.1:8000/assets/js/all-nocdn.js:23:5128
```

**Comment by undertherain** [comment]
which becomes 
```
 [Show/hide message details.] TypeError: Argument 1 of Node.removeChild is not an object.[Learn More] 
baguetteBox.min.js:7:5128
Y/f.onload
https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js:7:5128
```
id I set use_cdn to False
is there a way to make Nikola to not minimize js files?

**Comment by undertherain** [comment]
It looks like the problem is coming from bootstrap4's base.tmpl
I've removed 
```
    <script>
    baguetteBox.run('div#content', {
        ignoreClass: 'islink',
        captions: function(element) {
            return element.getElementsByTagName('img')[0].alt;
    }});
    </script>
```
and added
```
        <script>
    baguetteBox.run('a.reference:not(.islink)', {
        captions: function(element) {
            return element.getElementsByTagName('img')[0].alt;
    }});
    baguetteBox.run('img:not(.islink)', {
        captions: function(element) {
            return element.alt;
    }});
    </script>
``` 
as in bootblog's base.tmpl
some blind guess - but is solved it for me

**Comment by Kwpolska** [comment]
Reproduced. This seems to be an issue with what #2992/#2993 did. Debugging this will require some work though.

**Comment by Kwpolska** [comment]
Turns out we were calling `baguetteBox.run` twice (once in `gallery.js` for just the gallery, and another time for `div#content`). PR #3152.
