### ISSUE TITLE
assets not properly copied

### ISSUE THREAD

**Issue by muellert** [getnikola/nikola#3144]
### Environment (if reporting a bug)

**Python Version:**
3.5.3
**Nikola Version:**
8.0.0b3 (but the problem also occurs with 7.8.15)
**Operating System:**

Debian/Stretch amd64

### Description:

I am trying to develop a new theme for my site. Inside the theme folder, I have an assets folder with stuff in it. Contrary to the documentation, only some parts of this folder are being copied to the output/assets folder, and especially, my images folder, which has the site logo, amongst other pieces, is _not_ being copied. As a result, all the images are missing.

To repeat, just do the following:

1. Create a site and then a new theme.
2. Inside the theme, have a folder 'assets' and place some images in it.
3. rm -fr output
4. nikola build
5. ls output/assets

**Comment by Kwpolska** [comment]
Did you remember to change `THEME` in `conf.py`? I can’t reproduce with this structure:

```
$ tree themes
themes
└── foobar
    ├── assets
    │   └── img
    │       └── bkg.png
    └── foobar.theme
```

**Comment by muellert** [comment]
While I had indeed forgotten to change the theme setting, I now did that and still got the same result:
$ grep THEME conf.py
THEME = "ontheme-bs3-grad-jinjia"
THEME_COLOR = '#5670d4'
$ rm -fr output && nikola build && tree themes/ontheme-bs3-grad-jinjia output/assets
...
themes/ontheme-bs3-grad-jinjia
├── assets
│   ├── css
│   │   ├── ontheme.css
│   │   ├── ontheme.css.map
│   │   └── ontheme.scss
│   ├── images
│   │   ├── debian-swirl-100.png
│   │   ├── django-logo-positive-small.png
│   │   ├── logo.png
│   │   ├── mbfish.gif
│   │   ├── ncc-member-logo.png
│   │   ├── plone-logo-256.png
│   │   ├── pyramid-positive-small.png
│   │   └── python.png
│   └── js
├── AUTHORS.txt
├── bundles
├── engine
├── ontheme-bs3-grad-jinjia.theme
├── parent
├── README.md
└── templates
    ├── base_helper.tmpl
    └── feeds_translations_helper.tmpl
output/assets
├── css
│   ├── baguetteBox.min.css
│   ├── bootblog.css
│   ├── bootstrap.min.css
│   ├── code.css
│   ├── html4css1.css
│   ├── ipython.min.css
│   ├── nikola_ipython.css
│   ├── nikola_rst.css
│   ├── rst_base.css
│   ├── rst.css
│   └── theme.css
├── js
│   ├── baguetteBox.min.js
│   ├── bootstrap.min.js
│   ├── fancydates.js
│   ├── fancydates.min.js
│   ├── gallery.js
│   ├── gallery.min.js
│   ├── html5.js
│   ├── html5shiv-printshiv.min.js
│   ├── jquery.min.js
│   ├── justified-layout.min.js
│   ├── moment-with-locales.min.js
│   ├── popper.min.js
│   └── tag_cloud_data.json
└── xml
    ├── atom.xsl
    └── rss.xsl

**Comment by Kwpolska** [comment]
It still looks as if your theme were not active. Could you paste your conf.py file?

**Comment by muellert** [comment]
With name of company removed...
$ grep -v '^#' conf.py|sed -e '/^ *$/d'
from __future__ import unicode_literals
import time
BLOG_AUTHOR = "XXXXXX"  # (translatable)
BLOG_TITLE = "IT Consulting & Services"  # (translatable)
SITE_URL = "http://localhost:8000/"
BLOG_EMAIL = "n.tesla@example.com"
BLOG_DESCRIPTION = "Powered by Nikola."  # (translatable)
DEFAULT_LANG = "en"
TRANSLATIONS = {
    DEFAULT_LANG: "en",
    "de": "./de",
    "zh_cn": "./zh_cn",
}
TRANSLATIONS_PATTERN = "{path}.{lang}.{ext}"
NAVIGATION_LINKS = {
    DEFAULT_LANG: (
        ("/en/archive/index.html", "Archive"),
        ("/en/categories/", "Tags"),
        ("/en/rss.xml", "RSS feed"),
    ),
    "de": (
        ("/de/archive/index.html", "Archiv"),
        ("/de/categories/", "Tags"),
        ("/de/rss.xml", "RSS-Feed"),
    ),
    "zh_cn": (
        ("/zh_cn/archive/index.html", "文章存档"),
        ("/zh_cn/categories/", "标签"),
        ("/zh_cn/rss.xml", "RSS 源"),
    ),
}
THEME = "ontheme-bs3-grad-jinjia"
THEME_COLOR = '#5670d4'
POSTS = (
    ("posts/*.rst", "posts", "post.tmpl"),
    ("posts/*.md", "posts", "post.tmpl"),
    ("posts/*.txt", "posts", "post.tmpl"),
    ("posts/*.html", "posts", "post.tmpl"),
)
PAGES = (
    ("pages/*.rst", "", "page.tmpl"),
    ("pages/*.md", "", "page.tmpl"),
    ("pages/*.txt", "", "page.tmpl"),
    ("pages/*.html", "", "page.tmpl"),
)
TIMEZONE = "Europe/Berlin"
FORCE_ISO8601 = True
COMPILERS = {
    "rest": ('.rst', '.txt'),
    "markdown": ('.md', '.mdown', '.markdown'),
    "textile": ('.textile',),
    "txt2tags": ('.t2t',),
    "bbcode": ('.bb',),
    "wiki": ('.wiki',),
    "ipynb": ('.ipynb',),
    "html": ('.html', '.htm'),
    # PHP files are rendered the usual way (i.e. with the full templates).
    # The resulting files have .php extensions, making it possible to run
    # them without reconfiguring your server to recognize them.
    "php": ('.php',),
    # Pandoc detects the input from the source filename
    # but is disabled by default as it would conflict
    # with many of the others.
    # "pandoc": ('.rst', '.md', '.txt'),
}
LOGO_URL = '/assets/images/logo.png'
WRITE_TAG_CLOUD = True
POSTS_SECTIONS = True
HIDDEN_TAGS = ['mathjax']
CATEGORY_ALLOW_HIERARCHIES = True
CATEGORY_OUTPUT_FLAT_HIERARCHY = False
CATEGORY_PAGES_ARE_INDEXES = False
HIDDEN_CATEGORIES = []
HIDDEN_AUTHORS = ['Guest']
FRONT_INDEX_HEADER = {
    DEFAULT_LANG: ''
}
ARCHIVE_PATH = "archive"
ARCHIVE_FILENAME = "index.html"
ARCHIVES_ARE_INDEXES = True
URL_TYPE = 'full_path'
USE_BASE_TAG = False
REDIRECTIONS = []
IMAGE_FOLDERS = {'images': 'images'}
INDEX_PATH = "blog"
INDEX_TEASERS = False
INDEX_READ_MORE_LINK = '<p class="more"><a href="{link}">{read_more}…</a></p>'
FEED_READ_MORE_LINK = '<p><a href="{link}">{read_more}…</a> ({min_remaining_read})</p>'
FEED_LINKS_APPEND_QUERY = False
LICENSE = ""
CONTENT_FOOTER = 'Contents &copy; {date}         <a href="mailto:{email}">{author}</a> - Powered by         <a href="https://getnikola.com" rel="nofollow">Nikola</a>         {license}'
CONTENT_FOOTER_FORMATS = {
    DEFAULT_LANG: (
        (),
        {
            "email": BLOG_EMAIL,
            "author": BLOG_AUTHOR,
            "date": time.gmtime().tm_year,
            "license": LICENSE
        }
    )
}
RSS_COPYRIGHT = 'Contents © {date} <a href="mailto:{email}">{author}</a> {license}'
RSS_COPYRIGHT_PLAIN = 'Contents © {date} {author} {license}'
RSS_COPYRIGHT_FORMATS = CONTENT_FOOTER_FORMATS
COMMENT_SYSTEM = ""
COMMENT_SYSTEM_ID = ""
PAGE_INDEX = True
INDEX_FILE = "index.html"
STRIP_INDEXES = True
PRETTY_URLS = True
MARKDOWN_EXTENSIONS = ['markdown.extensions.fenced_code', 'markdown.extensions.codehilite', 'markdown.extensions.extra']
SHOW_SOURCELINK = False
COPY_SOURCES = False
GENERATE_ATOM = True
UNSLUGIFY_TITLES = True
USE_BUNDLES = False
GLOBAL_CONTEXT = {}
GLOBAL_CONTEXT_FILLER = []

**Comment by ralsina** [comment]
Just a wild guess but the config says "jinjia" and maybe the theme is
called "jinja"?

**Comment by Kwpolska** [comment]
Closing due to no response and no reproduction in 14 days.
