### ISSUE TITLE
Responsive youtube embed

### ISSUE THREAD

**Issue by python-friends** [getnikola/nikola#3150]
I'm trying to set an embedded youtube link to 100% width in a .rst file. Is this possible?

I've tried:

```
.. youtube:: 3XsQCkF1SrE
   :align: center
   :width: 100%
```

**Comment by Kwpolska** [comment]
We just set width="whatever you type". Check if the `width` attribute of iframes can take a `100%` value, and perhaps check how other people achieved that 100% width?

**Comment by python-friends** [comment]
@Kwpolska Thanks for your reply!

I get this error:
```
System Message: ERROR/3 (<string>, line 5)

Error in "youtube" directive: invalid option value: (option: "width"; value: '"100%"') invalid literal for int() with base 10: '100%'.

.. youtube:: 3XsQCkF1SrE
   :align: center
   :width: "100%"
```
(I also tried "100%")

http://www.tagindex.net/html/frame/i_width.html tells me iframes can take %s as width.

**Comment by Kwpolska** [comment]
We declare the type of `width` and `height` to be integers, perhaps we should make them strings instead. Can you make a PR for this?

**Comment by python-friends** [comment]
Yes I can :) thanks for your help!
