### ISSUE TITLE
Nikola Simplified Chinese language pack correction test

### ISSUE THREAD

**Issue by dingpengyu** [getnikola/nikola#3155]
Hello, nikola community, I am a nikola user from China. I want to update the translation of nikola simplified Chinese. I mainly corrected the translation of Simplified Chinese, such as: Toggle navigation Translation — Chinese (China): Expand navigation bar, ID: 39
Also, I want to add, why do I not update the translation platform, and issue an issue on GitHub, because I am a blind person, I usually use a screen reader to operate the computer, transifex accessibility is not very friendly to the screen reader, based on The above reason has this GitHub ISSUE
thank
[zh_CN.zip](https://github.com/getnikola/nikola/files/2352397/zh_CN.zip)

**Comment by Kwpolska** [comment]
Thanks for contributing, and don’t worry, Transifex can be problematic for non-vision-impaired users as well.

There are two issues, could you please fix them?

1. "LANGUAGE" should be the translated name of the language (old translation was 简体中文, Google Translate says it was correct)
2. "Read in English" should be translated as "Read in Simplified Chinese"

You can just write the fixed translations here and I’ll integrate them.

**Comment by dingpengyu** [comment]
Hi Kwpolska Here is my revised Chinese translation:
msgid "More posts about %s"
msgstr "有关更多文章"

#. Here your translation should NOT say English but the name of your language
#. instead
msgid "LANGUAGE"
msgstr "语言:"

msgid "Tags"
msgstr "标签"

msgid "Categories"
msgstr "分类"

msgid "Tags and Categories"
msgstr "标签和分类"

msgid "Comments"
msgstr "评论"

msgid "Read more"
msgstr "阅读更多"

msgid "Posts about %s"
msgstr "关于文章 %s"

msgid "Next post"
msgstr "下一篇"

msgid "old posts, page %d"
msgstr "旧文章页 %d"

msgid "page %d"
msgstr "第 %d 页"

msgid "Source"
msgstr "资源"

#. Here your translation should NOT say English but the name of your language
#. instead
msgid "Read in English"
msgstr "阅读英文"

msgid "Posts for year %s"
msgstr "%s年文章"

msgid "Newer posts"
msgstr "较新的文章"

msgid "Previous post"
msgstr "上一篇文章"

msgid "Also available in:"
msgstr "也可用于："

msgid "Languages:"
msgstr "语言："

msgid "Original site"
msgstr "原文地址"

msgid "Older posts"
msgstr "以前的文章"

msgid "Archive"
msgstr "文章归档"

msgid "Publication date"
msgstr "发布日期"

msgid "Posted:"
msgstr "发表于："

msgid "Posts for {month_year}"
msgstr "{month_year}文章"

msgid "Posts for {month_day_year}"
msgstr "{month_day_year}文章"

msgid "Nothing found."
msgstr "没有找到。"

msgid "No posts found."
msgstr "没有找到文章"

msgid "RSS feed"
msgstr "RSS 源"

msgid "%d min remaining to read"
msgstr "剩余 %d 分钟去阅读"

msgid "Skip to main content"
msgstr "跳到主内容"

msgid "Subcategories:"
msgstr "子类别："

#. Used for active navigation links, for screen readers only
msgid "(active)"
msgstr "(活跃)"

#. Default content for a new post
msgid "Write your post here."
msgstr "在这里书写你的文章。"

#. Default content for a new page
msgid "Write your page here."
msgstr "在这里书写你的页面。"

msgid "Uncategorized"
msgstr "未分类"

#. Used for feeds of any format
msgid "Updates"
msgstr "更新"

msgid "Authors"
msgstr "作者"

msgid "Posts by %s"
msgstr "文章有%s发布"

msgid "Toggle navigation"
msgstr "展开导航栏"

msgid "Previous"
msgstr "以前"

msgid "Up"
msgstr "向上"

msgid "Next"
msgstr "项下"

msgid "Atom feed"
msgstr "Atom源"

#. {date} (updated {updated_date})
msgid "updated"
msgstr "更新"

**Comment by dingpengyu** [comment]
Hi Kwpolska This is my revised translation file.
[zh_CN.zip](https://github.com/getnikola/nikola/files/2352554/zh_CN.zip)

**Comment by dingpengyu** [comment]
This is the specific content:
msgid "More posts about %s"
msgstr "有关更多文章"

#. Here your translation should NOT say English but the name of your language
#. instead
msgid "LANGUAGE"
msgstr "语言:"

msgid "Tags"
msgstr "标签"

msgid "Categories"
msgstr "分类"

msgid "Tags and Categories"
msgstr "标签和分类"

msgid "Comments"
msgstr "评论"

msgid "Read more"
msgstr "阅读更多"

msgid "Posts about %s"
msgstr "关于文章 %s"

msgid "Next post"
msgstr "下一篇"

msgid "old posts, page %d"
msgstr "旧文章页 %d"

msgid "page %d"
msgstr "第 %d 页"

msgid "Source"
msgstr "资源"

#. Here your translation should NOT say English but the name of your language
#. instead
msgid "Read in English"
msgstr "阅读简体中文"

msgid "Posts for year %s"
msgstr "%s年文章"

msgid "Newer posts"
msgstr "较新的文章"

msgid "Previous post"
msgstr "上一篇文章"

msgid "Also available in:"
msgstr "也可用于："

msgid "Languages:"
msgstr "语言："

msgid "Original site"
msgstr "原文地址"

msgid "Older posts"
msgstr "以前的文章"

msgid "Archive"
msgstr "文章归档"

msgid "Publication date"
msgstr "发布日期"

msgid "Posted:"
msgstr "发表于："

msgid "Posts for {month_year}"
msgstr "{month_year}文章"

msgid "Posts for {month_day_year}"
msgstr "{month_day_year}文章"

msgid "Nothing found."
msgstr "没有找到。"

msgid "No posts found."
msgstr "没有找到文章"

msgid "RSS feed"
msgstr "RSS 源"

msgid "%d min remaining to read"
msgstr "剩余 %d 分钟去阅读"

msgid "Skip to main content"
msgstr "跳到主内容"

msgid "Subcategories:"
msgstr "子类别："

#. Used for active navigation links, for screen readers only
msgid "(active)"
msgstr "(活跃)"

#. Default content for a new post
msgid "Write your post here."
msgstr "在这里书写你的文章。"

#. Default content for a new page
msgid "Write your page here."
msgstr "在这里书写你的页面。"

msgid "Uncategorized"
msgstr "未分类"

#. Used for feeds of any format
msgid "Updates"
msgstr "更新"

msgid "Authors"
msgstr "作者"

msgid "Posts by %s"
msgstr "文章有%s发布"

msgid "Toggle navigation"
msgstr "展开导航栏"

msgid "Previous"
msgstr "以前"

msgid "Up"
msgstr "向上"

msgid "Next"
msgstr "项下"

msgid "Atom feed"
msgstr "Atom源"

#. {date} (updated {updated_date})
msgid "updated"
msgstr "更新"

**Comment by Kwpolska** [comment]
Thanks. I also changed `msgid "LANGUAGE"` to 简体中文.

**Comment by dingpengyu** [comment]
Fix two translation entries:
msgid "More posts about %s"
msgstr "更多关于文章 %s"
msgid "Next post"
msgstr "下一篇文章"
[zh_CN.zip](https://github.com/getnikola/nikola/files/2352590/zh_CN.zip)

**Comment by Kwpolska** [comment]
Done.
