### ISSUE TITLE
New date format (Babel) vs. GitLab container registry

### ISSUE THREAD

**Issue by kerstin** [getnikola/nikola#3165]
I don't think this is a bug per se, I'm more looking for someone to confirm that what I'm suspecting is likely the case (I've done lots of googling & consulting this repo already but I'm a newb where containering is concerned and my head is _swimming_ after hours of debugging after upgrading):

If my post dates get rendered literally on GitLab (i.e. as strings reading `d MMM YYYY`) but not locally, it's got to do with the container in the [Container Registry](https://gitlab.com/paddy-hack/nikola/container_registry) and my Nikola version not matching up, right? I.e. the last available container probably does not yet include the new date format?

I installed Nikola via `pip` today and changed the date format when the warning messages on the command line prompted me to. (When I change the date format back, Nikola doesn't want to render locally anymore.)

**Python Version:** 3.7.0
**Nikola Version:** v8.0.0
**Operating System:** MacOS 10.13.6

**Comment by Kwpolska** [comment]
Yes, this behavior is what would happen if you used the new date format with v7. It looks like a container for v8.0.0 has just been published, so you probably need to trigger a rebuild.

**Comment by kerstin** [comment]
Thanks a bunch, @Kwpolska!
