### ISSUE TITLE
Formatting of "Serving on" on console

### ISSUE THREAD

**Issue by kerstin** [getnikola/nikola#3166]
Because this is something I didn't immediately get yesterday and was wondering what was going on for a while: I think it would make sense to change the "Serving on" info in a way that on systems where URLs are clickable in the terminal, the full address (incl. port number) is displayed.

On MacOS, `127.0.0.0` already gets translated to a hoverable/clickable link, but as it was missing the port number, I only got the default "It works" message. I don't know for sure but am guessing terminals on other systems might need the protocol added to recognise URLs.

**Comment by kerstin** [comment]
(If this is something that sounds like an OK addition/change, I can submit a PR for it.)

**Comment by Kwpolska** [comment]
Both `serve` and `auto` have a `-b` option that opens your default browser, but displaying the URL makes some sense as well. Please create a PR.

**Comment by kerstin** [comment]
Hi there, any OS work usually has to wait until the weekend - so not working on this yet, but I haven't forgotten.

**Comment by Kwpolska** [comment]
A lot of time has passed, so I took this over.

**Comment by kerstin** [comment]
In my "OS time", only 2 days have passed, (; during which I had to take care of "IRL" stuff with higher priority, but great to hear! Looking forward to the fix.
