### ISSUE TITLE
Markdown>=3.0.0 compatibility

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#3173]
The Markdown library has had a new release. It’s backwards-incompatible with the old ones, and Nikola breaks hard when using it. (v8.0.1 will probably be released later today to make things work when installing.)

**Comment by ralsina** [comment]
It seems to be working with Markdown 3.0.1

**Comment by Kwpolska** [comment]
The test suite goes kaboom with a lot of warnings though.

**Comment by ralsina** [comment]
OK, reopening and will fix the suite

**Comment by ralsina** [comment]
Python 3.7 in general causes a TON of warnings, most of them in dependencies. Checking which ones we can handle and fix.

**Comment by ralsina** [comment]
Many fewer warnings with https://github.com/getnikola/nikola/pull/3175
