### ISSUE TITLE
Bootstrap.min.js syntax error

### ISSUE THREAD

**Issue by kayhayen** [getnikola/nikola#3176]
### Environment (if reporting a bug)

**Python Version:**

3.5 as of Debian stable

**Nikola Version:**

latest, the CI auto updates

**Operating System:**

Debian

### Description:

When I migrated my site from very old Nikola, I first encounted the issue, but was confused:

```
TaskError - taskid:copy_assets:output/assets/js/bootstrap.min.js
PythonAction Error
Traceback (most recent call last):
  File "/home/nuitka-buildslave/nikola-sandbox/lib/python3.5/site-packages/doit/action.py", line 424, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/nuitka-buildslave/nikola-sandbox/lib/python3.5/site-packages/nikola/utils.py", line 985, in unlessLink
    action(target)
  File "/home/nuitka-buildslave/nikola-sandbox/lib/python3.5/site-packages/nikola/filters.py", line 163, in yui_compressor
    return runinplace('{} --nomunge %1 -o %2'.format(yuicompressor), infile)
  File "/home/nuitka-buildslave/nikola-sandbox/lib/python3.5/site-packages/nikola/filters.py", line 136, in runinplace
    subprocess.check_call(command)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['yui-compressor', '--nomunge', 'output/assets/js/bootstrap.min.js', '-o', '/tmp/nikolarzuupywl/bootstrap.min.js']' returned non-zero exit status 1
```

I even switched to another plugin that should compress js files, but that tool also complained. So I switched to `closure_compiler` just to find it has the same error, although I think it was better at pointing out the syntax error.

Now I noticed my performance site which has been automatically updated for a long time when I run my ansible is getting the same error. In fact, the stack trace is from it.

I believe the included `bootstrap.min.js` may not be correct JavaScript.

For my main site, I opted to disable the compression, it's nice, but how useful can it be. However I think there might be an issue there. Can you confirm or deny my allegation?

Thanks,
Kay

**Comment by ralsina** [comment]
I ran that JS (which md5sum 67176c242e1bdc20603c878dee836df3) through a few syntax checkers I found by googling "javascript syntax checkers"

* http://esprima.org/demo/validate.html ✅ 

* https://www.jslint.com/ 🔺 

* jsvalidate.org so-so?

Seems to me that there is some differences of opinion about what is or is not valid JS, and since that file is used by a bazillion sites, it's probably more or less ok.

In any case, that file is already minimized so there is no point in doing it again.
