### ISSUE TITLE
Missing dependency PyYAML with Nikola-8.0.1 refresh installtion

### ISSUE THREAD

**Issue by monkeyxite** [getnikola/nikola#3177]
### Environment (if reporting a bug)

**Python Version:**
3.7.0
**Nikola Version:**
Nikola-8.0.1
**Operating System:**
Mac
### Description:

Refresh installation after pip, occur the dependency missing issue with PyYAML when creating new post. error message like this.

> 
> 
> Creating New Post
> -----------------
> 
> Title: Test Nicula
> Scanning posts..[2018-10-13T15:46:03Z] ERROR: Nikola: In order to use YAML metadata, you must install the "PyYAML" Python package.
> [2018-10-13T15:46:03Z] ERROR: Nikola: Exiting due to missing dependencies. 

After pip install PyYaml, all settled.

Suppose requirements.txt should be updated.

**Comment by Kwpolska** [comment]
Not really. `requirements.txt` contains the basic, mandatory requirements. Your site uses the YAML metadata format, as configured, so you also have to install PyYAML on your own. (Note this message was generated by Nikola on purpose.)

You can use `pip install 'Nikola[extras]'` to get Nikola
