### ISSUE TITLE
sitemap.xml includes not published posts

### ISSUE THREAD

**Issue by crohas** [getnikola/nikola#3180]
### Environment (if reporting a bug)

Python Version: 3.6.5

Nikola Version: 8.0.1

Operating System: Mac

### Description:
It seems Nikola's sitemap includes not published posts, 
but I don't want it to publish private posts.

Is this supposed to be this way?
Or is there a method that I avoid the result?

Thanks.

**Comment by crohas** [comment]
Sorry for making you confused, I should have told the status properly.
To be honest I do not understand the difference between `draft` and `private` well, but even I specified `private`, got the same result.

For now I'm specifying `draft` to the post(reST) like the following.

```
.. title: something
.. tags: React, JavaScript
.. date: 2099-12-31
.. slug: .
.. previewimage: /media/react.png
.. status: draft
```

And the values (might be relavant it) in `conf.py` are as below:

```
# FUTURE_IS_NOW = False
# DEPLOY_DRAFTS = True # even if I specified anything (also `False`), got same result.
# SCHEDULE_RULE = ''
# SCHEDULE_ALL = False
```

Also the other posts that specified the status as well is not displayed on index.html and also atom.xml.

You might think it weird to specify `.` to slug. Actually I'm not placing posts on just under `posts/`, but nesting directories on it.
It means the permalink getting the same with the directory path.

e.g. `/2018/post-title/index.rst` => `posts-prefix/2018/post-title/`

I just realized though, it seems that a private post specified a slug expressly on just under `posts/` does not appear in a sitemap.
Is this placement of posts unrecommended?

**Comment by ralsina** [comment]
Honestly, I don't think we ever considered using "." as a slug and I have no idea what it does :-)

**Comment by crohas** [comment]
I tried the way you said, and it worked. 
But I want to make a directory per post. (some posts require files relating itself in my case)

I'll give up if you decided don't deal with a rare case like this. it's not so hard to make a task to generate a sitemap by myself :)

But honestly I hope you fix it, because it looks an extraction method of sitemap.xml is different from the others. (e.g. index.html, atom.xml)

I know this may cause a problem, but I would be glad if you could consider it.

btw, '.' means current directory path, I think you know that though.
It seems Nikola makes a permalink using relative path from 'posts/' that the post puts and its slug.
e.g. `posts/spam/ham.rst` and the slug is `egg`, the permalink is `[posts-prefix]/spam/egg/`,
Specifying '.' makes a permalink the same with the directory path the post puts on, this is my own way.

Thanks.

**Comment by Kwpolska** [comment]
Use `index` as the slug — that is (a) supported and (b) apparently disables sitemap generation successfully.
