### ISSUE TITLE
Is 'published' unknown status?

### ISSUE THREAD

**Issue by crohas** [getnikola/nikola#3181]
### Environment (if reporting a bug)

Python Version: 3.6.5

Nikola Version: 8.0.1

Operating System: Mac

### Description:

Warning messages appear: `WARNING: Nikola: The post "posts/xxxx.rst" has the unknown status "published". Valid values are "published", "featured", "private" and "draft".`, when I specify `published` as the status.

I think `nikola/post.py#L285` should be `elif`, how do you think?
https://github.com/getnikola/nikola/blob/master/nikola/post.py#L283-L286

**Comment by Kwpolska** [comment]
Fixed, thanks. (Note that you don’t need to specify `status: published` at all; that’s why nobody caught this before)
