### ISSUE TITLE
Add a CNAME plugin

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#3182]
Looks moderately useful, and simple to do.

https://blog.minchin.ca/2018/10/cname-plugin-121-for-pelican-released.html

**Comment by Kwpolska** [comment]
`echo example.com > files/CNAME` is far easier and more discoverable than a plugin.

**Comment by tritium21** [comment]
Doesn't nikola already do this with the files that Chris already mentioned?  Is there something more than creating a static file that you want?

**Comment by ralsina** [comment]
I suspect there isn't but we **could** create the file automatically based
on us knowing the site's URL, I think.

**Comment by ralsina** [comment]
But yes, it's pretty silly.
