### ISSUE TITLE
Add an option to get post text only?

### ISSUE THREAD

**Issue by ChillarAnand** [getnikola/nikola#3187]
### Description: 

To calculate reading time for a blog post, we need to get word count in post and divide it by average WPM.

Nikola's `post.text` gives entire text+code. This leads to several inaccuracies because of several code blocks. If there is an option to retrieve only text without code blocks, reading time calculation will be accurate.

**Comment by ralsina** [comment]
What do you mean by code? The content of code blocks? I expect those are to be read too?

**Comment by ralsina** [comment]
If you want, you can get the HTML version of the text and remove the code
blocks using lxml ... in general I suspect all that will happen is that the
reading time will be skewed in the opposite direction.

**Comment by ChillarAnand** [comment]
Most likely it will.
