### ISSUE TITLE
Add option to use --cloak-email-addresses feature in rst2html

### ISSUE THREAD

**Issue by djmoch** [getnikola/nikola#3188]
### Description:

Per recommendation from ralsina in the IRC chatroom, I am requesting an additional option to use the `cloak-email-addresses` feature provided by rst2html.

**Comment by ralsina** [comment]
I think it would make more sense to support the option syntax from docutils' config file in nikola's conf.py instead (see http://docutils.sourceforge.net/docs/user/config.html#example)

In fact ... if you put that in a docutils.conf right next to conf.py ... it should work, I think?

**Comment by djmoch** [comment]
Confirmed. I honestly didn't think to check whether docutils was configurable this way. Nice!

**Comment by djmoch** [comment]
Actually, my quick (just running `rst2html` directly) doesn't bear out when actually running `nikola build`. For whatever reason, the `docutils.conf` isn't be honored.

**Comment by ralsina** [comment]
Ok then, I will make it happen.

**Comment by ralsina** [comment]
Not sure yet :-)

**Comment by djmoch** [comment]
I'm still not able to get this to work. The following `docutils.conf` doesn't yield any change in the output. Am I doing something wrong?

``` ini
[nikola]
cloak-email-addresses: yes
```

To get this to work with bare `rst2html`, the conf looks like this, which seems to suggest that collapsing the whole configuration into a single `[nikola]` section might be problematic:

``` ini
[html4css1 writer]
cloak-email-addresses: yes
```

**Comment by ralsina** [comment]
This works for me:

```
 $ cat docutils.conf                                                           
[nikola]
cloak-email-addresses = yes
$ rm cache/posts/foo.html 
$ cat posts/foo.rst
.. title: foo
.. slug: foo
.. date: 2018-12-11 15:18:19 UTC
.. tags:
.. category:
.. link:
.. description:
.. type: text

ralsina@kde.org
$ nikola build
Scanning posts........done!
.  render_posts:cache/posts/foo.html
$ cat cache/posts/foo.html 
<p><a class="reference external" href="mailto:ralsina&#37;&#52;&#48;kde&#46;org">ralsina<span>&#64;</span>kde<span>&#46;</span>org</a></p>
$ rm docutils.conf   
$ rm cache/posts/foo.html
$ nikola build
Scanning posts........done!
.  render_posts:cache/posts/foo.html
.  render_taxonomies:output/2018/index.html
.  render_taxonomies:output/authors/your-name/index.html
.  render_taxonomies:output/index.html
.  render_taxonomies:output/rss.xml
.  render_pages:output/posts/foo/index.html
.  render_taxonomies:output/authors/your-name.xml
.  sitemap:output/sitemap.xml
$ cat cache/posts/foo.html  
<p><a class="reference external" href="mailto:ralsina&#64;kde.org">ralsina&#64;kde.org</a></p>
```

**Comment by djmoch** [comment]
It sure looks like it’s working for you. Given the only difference between yours and mine is the use of an equals sign instead of a colon, that seems like something I should look into. 

It’ll try that out when I get back to my machine this evening (UTC-5).

**Comment by djmoch** [comment]
First off, it looks like the `docutils.conf` has been working all along, with caveats. It doesn't seem to me that anything has changed as a result of this bugfix. The behavior is the same in 8.0.1 as it is in 7d142c907b761db03eea160956635b94503b1a8b.

Second, your above comment led me a little further debugging this. It turns out that what lives in the cache is properly obscured as expected, but some of that gets lost when the cache gets built into the actual site date.

Here's an email address in my own home page as it exists in the cache
``` html
<a class="reference external" href="mailto:daniel&#37;&#52;&#48;danielmoch&#46;com">Email</a>
```
But in the actual site it looks like this:
``` html
<a class="reference external" href="mailto:daniel%40danielmoch.com">Email</a>
```
What do you make of that?

**Comment by ralsina** [comment]
On Wed, Dec 12, 2018 at 9:13 PM Daniel Moch <notifications@github.com>
wrote:

> First off, it looks like the docutils.conf has been working all along,
> with caveats. It doesn't seem to me that anything has changed as a result
> of this bugfix. The behavior is the same in 8.0.1 as it is in 7d142c9
> <https://github.com/getnikola/nikola/commit/7d142c907b761db03eea160956635b94503b1a8b>
> .
>
> Second, your above comment led me a little further debugging this. It
> turns out that what lives in the cache is properly obscured as expected,
> but some of that gets lost when the cache gets built into the actual site
> date.
>
> Here's an email address in my own home page as it exists in the cache
>
> <a class="reference external" href="mailto:daniel&#37;&#52;&#48;danielmoch&#46;com">Email</a>
>
> But in the actual site it looks like this:
>
> <a class="reference external" href="mailto:daniel%40danielmoch.com">Email</a>
>
> What do you make of that?
>
>
That is sort of ok, it's just changing encoding in a URL. But it's not all
cloaking does!

Cloaking can't really "hide" the email address in the link much, since it
has to be in an understandable format or it would not work. Cloaking is
also about hiding email addresses **in the visible text**.

So, here is the difference:

<p><a class="reference external" href="mailto:ralsina&
#37;&#52;&#48;kde&#46;org">ralsina<span>&#64;</span>kde<span>&#46;</span>org</a></p>

See all the span tags in the visible text? That's the actual cloaking :-)
It's not happening in your case because the text is just "Email"

The entities in the link? They don't do much, since they are all
recognizable email address links anyway, at least for anyone trying to
harvest email addresses.
