### ISSUE TITLE
Template shortcodes render an additional new line

### ISSUE THREAD

**Issue by matclab** [getnikola/nikola#3196]
### Environment (if reporting a bug)

**Python Version:**
Python 3.7.1

**Nikola Version:**
8.0.1

**Operating System:**
Arch linux in virtualenv

### Description:
Using the following `shortcodes/color.tmpl` template (with no space nor new line at the end, verified with `xxd`)
```
<tt class="color" style="color:${_args[0]};">${_args[0]}</tt>
```

in the following context
```
doit être rouge ({{% color #FF0000FF %}}) et
```

gives the following output
```
doit être rouge (<tt class="color" style="color:#FF0000FF;">#FF0000FF</tt> 
) et
```
Which renders an unwanted space before the closing parenthesis.

**Comment by Kwpolska** [comment]
Cannot reproduce on macOS with Python 3.7.1, both Markdown and reST compilers.

```
$ xxd shortcodes/color.tmpl
00000000: 3c74 7420 636c 6173 733d 2263 6f6c 6f72  <tt class="color
00000010: 2220 7374 796c 653d 2263 6f6c 6f72 3a24  " style="color:$
00000020: 7b5f 6172 6773 5b30 5d7d 3b22 3e24 7b5f  {_args[0]};">${_
00000030: 6172 6773 5b30 5d7d 3c2f 7474 3e         args[0]}</tt>
$ cat posts/foo.md
<!--
.. title: foo
.. slug: foo
.. date: 2019-01-01 19:07:34 UTC
.. tags:
.. category:
.. link:
.. description:
.. type: text
-->

Write your post here.
doit être rouge ({{% color #FF0000FF %}}) et
$ cat cache/posts/foo.html
<p>Write your post here.
doit être rouge (<tt class="color" style="color:#FF0000FF;">#FF0000FF</tt>) et</p>
```

**Comment by Kwpolska** [comment]
Cannot reproduce on Arch Linux in a freshly installed virtualenv either.

**Comment by matclab** [comment]
You're right. I'm  not sure that every editor add a supplementary end of line, and thus we shall probably not tweak the template content.
