### ISSUE TITLE
Capability of scanning symlinks in posts folder

### ISSUE THREAD

**Issue by carlosvin** [getnikola/nikola#3197]
I've found an useful use case you might want to support in Nikola. 

In my personal blog, sometimes I post fully working examples located in other external repositories. They normally have a `README.md` file pointing to the post in my blog. 

I think a better option would be to:
 - Write full post in README.md, example project repository.
 - Add external repository to my Nikola blog, for example in a folder named `externals`. 
```bash
cd externals
git submodule add  https://github.com/carlosvin/example-project.git
```
 - Create a symbolic link from `posts/post-for-my-example.md` to `externals/example-project/README.md`.
```bash
ln -s externals/example-project/README.md posts/post-for-my-example.md
```
 With this structure, I would expect Nikola to process `posts/post-for-my-example.md`, but since it is a symbolic link it seems to skip it.

**Comment by Kwpolska** [comment]
(Note that git submodules are not a good idea for anything. Right here, you’d need to manually remember to update the submodules.)

**Comment by carlosvin** [comment]
It think that update git submodules is better than remember all the posts you have in external projects and manually update them post by post.

**Comment by ralsina** [comment]
You could use a hard link instead (ln without -s)?

If it's not an acceptable solution for some reason, then yes, it's possible to change it so that nikola follows symlinks, I don't see a problem with that.

**Comment by carlosvin** [comment]
Yes, I think it is acceptable solution for the use case I described above (symlink to file), although for directories it won't work.
```
$ ln directory symlink-to-dir
hard link not allowed for directory
``` 
This is a more generic idea like "Why not following symlinks?", I understand it is not necessary feature and feel free to close it, I just wanted to share the idea.

**Comment by ralsina** [comment]
There is no reason not to follow them, really. It's just that figuring out where we are not doing it and fixing it everywhere is going to be a bit of a pain :-)

**Comment by ralsina** [comment]
Experiment: I created the demo site, then created a "parallel" site which is nothing except symlinks to the demo site.

It failed horribly (as expected) so I'll do a branch where I go fixing that. When the demo site builds, I will close this issue, pending future discoveries of broken things.

**Comment by ralsina** [comment]
Actually, once I realized all my symlinks were broken and I fixed them ... this works?
As you can see, there are almost no "real" files here:

![image](https://user-images.githubusercontent.com/1579/79134507-32396a00-7d84-11ea-83a9-6f93d97896e0.png)

And they are all links to some place else:

![image](https://user-images.githubusercontent.com/1579/79134556-49785780-7d84-11ea-861b-873e4cad6d88.png)

I suspect your error is because your symlink didn't really work, maybe? Or else, we fixed it inadvertently at some point.

And yet, this builds just fine. So, closing until someone points out a broken case.
