### ISSUE TITLE
Commento is broken.

### ISSUE THREAD

**Issue by ntkomata** [getnikola/nikola#3198]
**Nikola Version:**
8.0.1
Commento has updated their js file and the script in the comment helper template file is broken. 
And I noticed that even if I've changed the load script of commento, the script won't show up in the HTML! So I just put the script tag in the comment_form macro and now it works. 
Please fix this!

**Comment by Kwpolska** [comment]
It looks like it never worked correctly, which is kinda embarassing… Could you please test if it works with PR #3199?

**Comment by ralsina** [comment]
I am fairly sure I actually tested it at that point, but could be.

**Comment by habisain** [comment]
PR #3199 seems unlikely to work with at least the hosted version of Commento, but it's an easy fix.

     <script defer src="{{ comment_system_id }}/js/commento.min.js"></script>

Should be

     <script defer src="{{ comment_system_id }}/js/commento.js"></script>
