### ISSUE TITLE
Hi, where is the html file generated from list_post.tmpl

### ISSUE THREAD

**Issue by Henry-Jia** [getnikola/nikola#3205]
I want to show all my posts with the url: site_url/posts/.
I thought the list_post.tmpl will generate a html in posts fold, but i can't find it.
Meanwhile, i don't want to show all posts with the url: site_url/archive.
Please, help me!

**Comment by Kwpolska** [comment]
list_post.tmpl is the generic template used for various lists of posts. To get what you want, you can change your ARCHIVE_PATH to `posts` and optionally other archive-related settings.

**Comment by Henry-Jia** [comment]
Thank you very much, it works.
I love Nikola very much.

**Comment by Kwpolska** [comment]
PS. we prefer for usage questions to be sent to the nikola-discuss mailing list.

**Comment by Henry-Jia** [comment]
> PS. we prefer for usage questions to be sent to the nikola-discuss mailing list.

Ok, thank you.
