### ISSUE TITLE
Bootswatch Themes on Netlify

### ISSUE THREAD

**Issue by nemodicto** [getnikola/nikola#3209]
How to make Nikola's technique of subtheme using Bootswatch themes work with Netlify? 

Create subtheme:

```
nikola subtheme -s litera -p bootstrap4 -n bootstrap4-litera
```

Enable it in `conf.py`:

```
THEME = "bootstrap4-litera"
```

But upon deploy to netlify, using the `requirements.txt` and other files at [blog-template](https://github.com/getnikola/blog-template) repository seems to deploy with the parent theme.

**Comment by Kwpolska** [comment]
Was your new theme committed to the git repository? Did you get any errors from Netlify?

**Comment by nemodicto** [comment]
It was all correctly deployed, to gitlab. No errors. Except that it is the main theme, not the subtheme, that was being shown.

**Comment by Kwpolska** [comment]
Show the repo?

**Comment by nemodicto** [comment]
https://gitlab.com/nemodicto/dicto.xyz

**Comment by Kwpolska** [comment]
If the site in question is `https://dicto.xyz/`, then I can see that the theme is applied. If it isn’t, then I can’t think of anything that would prevent the theme from working.

**Comment by nemodicto** [comment]
In that case, I will check and get back to you. Sorry if I overlooked anything.

**Comment by ralsina** [comment]
I suppose this worked out :-)
