### ISSUE TITLE
Extend :doc: rst extension to handle page internal targets

### ISSUE THREAD

**Issue by CarstenGrohmann** [getnikola/nikola#3212]
Hi Nikola Developers,

what do you think about extending the current implementation of the `:doc:` rst extension to handle page internal locations also?

The current implementation does not support referencing internal like automatically generated references to (sub) titles. Thereby I suggest to enhance `:doc:` to allow hash marks (like HTML `<a href="#subtitle2"/>`) for separating page name and page internal target.

**Examples with the current implementation**
```
`"to sub title 2" <page.html#subtitle2>`_

`"my bash scripts" <projects.html#bash>`_
```

**Suggested enhancement for `:doc:`:**
```
:doc:`to sub title 2<page#subtitle2>`

:doc:`my bash scripts<projects#bash>`
```
**or better - extract the sub title also:**
```
:doc:`projects#bash`
```

Thank you,
Carsten

**Comment by Kwpolska** [comment]
It’s a neat idea, although the heading extraction (last example) won’t work, it’s impossible to get right. Would you like to create a PR?

**Comment by CarstenGrohmann** [comment]
I had hoped to get the change without writing a line myself. Be that as it may. I'll create a PR. 
Can you briefly answer my question from the 21st on IRC?

**Comment by Kwpolska** [comment]
```irc
06:48:50 <CarstenG> Hi,
06:48:50 <CarstenG> I use Nikola with rst pages and want to open only external links in own browser tab/window (<a target="_blank").
06:48:50 <CarstenG> I read the documentation but I don't found any related information.
06:48:50 <CarstenG> Is there an option to do this directly in Nikla? I only found a JavaScript based solution yet.
06:48:50 <CarstenG> Thanks
```

Nikola itself doesn’t do that, and I don’t think reST does either.

**Comment by ralsina** [comment]
I suppose it's possible to do some lxml postprocessing and have links to other sites have target blank?
