### ISSUE TITLE
Languages: please add interlingua

### ISSUE THREAD

**Issue by mardy** [getnikola/nikola#3214]
Hi there!
  I've translated nikola into interlingua (https://www.transifex.com/ralsina/nikola/language/ia/) but it's not clear to me how to proceed; I thought that Transifex would automatically generate a merge request, but it doesn't appear to be the case.
Should I download the translation file from transifex and manually create a merge request myself?

**Comment by Kwpolska** [comment]
Oh sorry, I forgot to commit and push. Done that now.
