### ISSUE TITLE
Isso comments don't work properly in multilingual sites

### ISSUE THREAD

**Issue by mardy** [getnikola/nikola#3215]
Isso uses the `#isso-thread` element as the key to load comments for a post. In the base-jinja template, Nikola is setting it to `post.permalink`:

comments_helper.tmpl:
```
{% macro comment_link(link, identifier) %}
    {% if comment_system_id %}
        <a href="{{ link }}#isso-thread">Comments</a>
    {% endif %}
{% endmacro %}
```

post_header.tmpl:
```
                <p class="commentline">{{ comments.comment_link(post.permalink(), post._base_path) }}
```

but in multilingual sites, the permalink also contains the language id, so if I enter a comment in the English version of the site, the comment won't be visible in the Italian version (and vice versa).

**Comment by Kwpolska** [comment]
I would consider that expected, desired, sensible behavior. People who read your post in language X expect comments in that language and might not even speak languages Y and Z, so these comments would be confusing to them.

**Comment by Kwpolska** [comment]
Feel free to change your site’s templates to your liking. We can’t change it, because that would mean comments potentially disappearing on users’ sites.

**Comment by mardy** [comment]
Fair enough. For those who find the same issue, here's the way I fixed it:

https://gitlab.com/mardy/mardy.it/commit/23841c860b38ffcf745386dd409337cc6e67f555
