### ISSUE TITLE
Incremental build seems not to be working

### ISSUE THREAD

**Issue by mardy** [getnikola/nikola#3216]
### Environment

**Python Version:**
Python 3.5.2

**Nikola Version:**
Nikola v8.0.1

**Operating System:**
Ubuntu 16.04

### Description:

If I run `nikola build` twice in a row, according to [this page](https://getnikola.com/features/fast.html) I would expect it to do nothing; and yet:
```
$ nikola build 2>&1 | wc -l
1910
```

It is less than a full rebuild:
```
$ nikola build -a 2>&1 | wc -l
4077
```
If I compare the actual output, it seems that the incremental rebuild doesn't do the `render_posts:cache/posts/...` tasks and the `render_taxonomies:output/...` for the `atom` and `xml` feeds.

Do I have some configuration or template in my site that makes Nikola misbehave? Are there some ways to debug this?

For the record, the source of my site is [here](https://gitlab.com/mardy/mardy.it).

**Comment by Kwpolska** [comment]
On my side, there seem to be some random rebuilds, but far less than 1910. (about 150 on first rebuild, 1 on second, 4 on third).

**Comment by ralsina** [comment]
Sigh, these are always tricky.

**Comment by mardy** [comment]
Is there some way to have Nikola dump a dependency graph, or anything else that could help in understanding where the issue is?

**Comment by Kwpolska** [comment]
`nikola dumpdb` can help (run multiple times, before and after building, compare outputs)

**Comment by ralsina** [comment]
Yes, basically the "solution" is:

* build
* dumpdb (save)
* build (see what spurious changes are there)
* dumpdb
* see *why* each spurious change happened
* track down why nikola thinks each thing needed rebuilding
* some of the rebuilds will be because of other expected rebuilds
* There will be one or more "root" spurious rebuilds
* see why those happened
* figure out whether it's a config problem or a stupid bug Roberto left there 3 years ago
* surely it's roberto's fault
* tell roberto

**Comment by ralsina** [comment]
Can't build it yet because of:

```
babel.core.UnknownLocaleError: unknown locale 'ia'
```

**Comment by mardy** [comment]
Right, I have a locally patched babel; but if you remove `ia` from `conf.py` and also
```
rm posts/2019/01/looking-forward-to-your-comments.ia.md posts/2018/04/what-you-dont-hear-about-ukraine.ia.html pages/about.ia.md
```
you should be able to build the site and I've verified that the problem is still there.

**Comment by ralsina** [comment]
And I think I know what it is.

<img width="1644" alt="screen shot 2019-02-05 at 12 53 51" src="https://user-images.githubusercontent.com/1579/52285516-3d556680-2945-11e9-9dde-1e7cdc32014b.png">

Templates in dependencies in jinja are not sorted.

**Comment by ralsina** [comment]
Grrr that is *a* thing but is not *the* thing.

**Comment by ralsina** [comment]
The guilty line is this:

```
deps_dict['global'] = self.GLOBAL_CONTEXT
```

which is ... extremely suprising.

**Comment by ralsina** [comment]
narrowed it down to self.GLOBAL_CONTEXT['momentjs_locales'] of all things

**Comment by ralsina** [comment]
And I got it :-)

This is an **obscure** bug dudes!

* Because interlingua is not supported in momentjs
* And momentjs_locales is a defaultdict
* Depending on "random things" sometimes that dict would have an extra element for interlingua
* So, "sometimes" this would trigger a corner case in our CustomEncoder for JSON

One-liner fix coming up.

**Comment by ralsina** [comment]
Ok, the fix is wrong. Sigh.

**Comment by mardy** [comment]
> BTW @mardy nice to see a fellow former-canonicaler around :-)

Yes, I noticed that your name was familiar! Then linked-in did the rest :-)

Note that this bug, as I wrote in [a previous comment](https://github.com/getnikola/nikola/issues/3216#issuecomment-460685025), this happens even if I completely remove interlingua. Though, maybe, it might still be referenced in some cached file, dunno.

**Comment by mardy** [comment]
> @mardy Could you check if the proposed branch fixes it for you?

It doesn't seem to fix it, no :-(

**Comment by ralsina** [comment]
@mardy grmbl, will look harder today

**Comment by ralsina** [comment]
@mardy I can't reproduce it anymore with that PR.

**Comment by mardy** [comment]
Mmm... I'll try again tonight, maybe I did something wrong in applying it.

**Comment by mardy** [comment]
No, @ralsina, it looks like it's not working here. I deleted the `.doit.db` file, and the `cache` and `__pycache__` directories, but nothing changes.
The `default()` function is called many times, but that line you added (`self.encode(dict(obj))`) is never called (I added a print statement right before it)

**Comment by ralsina** [comment]
@mardy I think you are testing old code, that is no longer there in the last version of the PR, see https://github.com/getnikola/nikola/pull/3218

**Comment by mardy** [comment]
Ah! Indeed, I was on the wrong commit. Now I've checked out e8916c85773d9fde2b23798fd9ea7ccfa970d984, but I still don't see an improvement:

    $ nikola build 2>&1 | wc -l
    1926

Can you tell me what is the expected output?

**Comment by mardy** [comment]
I also tried adding `ia: 'ia'` to the `MOMENTJS_LOCALES` dictionary, but it didn't help.

**Comment by mardy** [comment]
By the way, the latest `python-babel` from git supports the interlingua locale. You can follow the instruction from [here](https://github.com/python-babel/babel/blob/master/docs/installation.rst) (in the "Living on the edge" section) to install it in your virtualenv.

**Comment by Kwpolska** [comment]
With Python 3.7, macOS, the branch, and latest Babel, I cannot reproduce. An important thing to notice is that Python 3.5 has random dict ordering, so there might still be something there…

**Comment by Kwpolska** [comment]
Confirmed random rebuilds still happen with Python 3.5.

**Comment by mardy** [comment]
And I installed python3.5 in my home (I'm using Ubuntu 16.04), and I can confirm that there are no random rebuilds in 3.7. Thanks @ralsina for the fix, and @Kwpolska for the intuition of using 3.7! :-)
