### ISSUE TITLE
Isso support somewhat broken still

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#3219]
Building a site configured with isso support with bootstrap4 theme, I get this:

```
AttributeError: Namespace 'isso' has no member 'comment_link'
```

Not very important since almost noone uses Isso but I will take a look.

**Comment by gour** [comment]
> Not very important since almost noone uses Isso but I will take a look.

I was (am) using it, but now with Hugo due to problems with Asciidoctor [plugin](https://github.com/getnikola/plugins/issues/296)...

**Comment by Kwpolska** [comment]
Works for me.
