### ISSUE TITLE
CONTRIBUTING.rst refers to non-existing tests/README.rst

### ISSUE THREAD

**Issue by CarstenGrohmann** [getnikola/nikola#3221]
Hi Nikola developers,

the current version of `CONTRIBUTING.rst` refers to `tests/README.rst` for more details about testing Nikola, but the document does not exists.

Please add this document or replace it with some words about testing (e.g. run `py.test tests/`). 

Regards
Carsten

**Comment by Kwpolska** [comment]
That file was removed when `babel` was introduced, now no special instructions are necessary.
