### ISSUE TITLE
ERROR: Two different tasks can't have a common target.'output/2018/index.html' is a target for render_taxonomies:output/2018/index.html and render_pages:output/2018/index.html.

### ISSUE THREAD

**Issue by jean** [getnikola/nikola#3228]
### Environment

**Python Version:** 3.6.6

**Nikola Version:** 8.0.1

**Operating System:** WSL on Windows 10

### Description:

> ERROR: Two different tasks can't have a common target.'output/2018/index.html' is a target for render_taxonomies:output/2018/index.html and render_pages:output/2018/index.html.

This looks like a variation of #3022 --- the difference being that I have a subfolder ("`2018/`") of pages. 
If I move that subfolder out of the way, the error goes away.

**Comment by Kwpolska** [comment]
This is not a bug. A taxonomy, probably archives, is configured to generate `/2018/index.html`, and so is your page. Change your `ARCHIVE_PATH` or get rid of the page that generates `2018/index.html`.

**Comment by jean** [comment]
Ah OK, setting `ARCHIVE_PATH = "archive"` fixed this. It was at the default (`ARCHIVE_PATH = ""`), and so was generating `/2017/index.html` and `/2018/index.html`. 

Thanks!
