### ISSUE TITLE
Language links don't work when using Nikola's server

### ISSUE THREAD

**Issue by mardy** [getnikola/nikola#3229]
When running `nikola auto --browser`, the language links point to the real site and not to the right paths under `127.0.0.1`.
I've seen that this can be fixed with this change:
```
diff --git a/nikola/data/themes/bootstrap4-jinja/templates/base_helper.tmpl b/nikola/data/themes/bootstrap4-jinja/templates/base_helper.tmpl
index 20b9d54..3a463a5 100644
--- a/nikola/data/themes/bootstrap4-jinja/templates/base_helper.tmpl
+++ b/nikola/data/themes/bootstrap4-jinja/templates/base_helper.tmpl
@@ -167,7 +167,7 @@ lang="{{ lang }}">
 {% macro html_translations() %}
     {% for langname in translations|sort %}
         {% if langname != lang %}
-            <li class="nav-item"><a href="{{ abs_link(_link("root", None, langname)) }}" rel="alternate" hreflang="{{ langname }}" class="nav-link">{{ messages("LANGUAGE", langname) }}</a></li>
+            <li class="nav-item"><a href="{{ _link("root", None, langname) }}" rel="alternate" hreflang="{{ langname }}" class="nav-link">{{ messages("LANGUAGE", langname) }}</a></li>
         {% endif %}
     {% endfor %}
 {% endmacro %}
```
If you confirm that this change is correct, I can submit it for all themes' `base_helper` files.

**Comment by Kwpolska** [comment]
IMO this is expected behavior, they all take you to `SITE_URL`. (Same goes for the `/` link.)

**Comment by mardy** [comment]
Indeed, the / link should point to the local server too. Why would these link behave differently from the others? It just makes testing harder.

**Comment by mardy** [comment]
I found this: aa3f967ccf8bdc41104b3c66528e7b27fc609fdf

Still try to understand if this change would reopen those bugs.
