### ISSUE TITLE
[bootstrap4-jinja] [bootbase4-jinja] jinja themes should not load moment.js when DATE_FANCINESS = 0

### ISSUE THREAD

**Issue by keturn** [getnikola/nikola#3231]
### Environment

**Nikola Version:** 8.0.1

### Description:

While `base-jinja` correctly checks `date_fanciness` before loading `moment.js`, as seen in https://github.com/getnikola/nikola/blob/2414a5e53ad7c4188e330ff0276301a2500359d4/nikola/data/themes/base-jinja/templates/base_helper.tmpl#L69-L71
some other themes load this 319 kB JavaScript dependency regardless of the setting.

Offending themes include bootstap4-jinja and bootbase4-jinja, which each define their own `late_load_js`, e.g. https://github.com/getnikola/nikola/blob/2414a5e53ad7c4188e330ff0276301a2500359d4/nikola/data/themes/bootstrap4-jinja/templates/base_helper.tmpl#L64-L71

There may be others, I have not done an exhaustive search.

(There's probably a larger discussion to be had about whether it is _ever_ appropriate to load that 319 kB of javascript, given that the required locales seem to be known at compile-time, but that's for #3232.)

**Comment by Kwpolska** [comment]
This applies to bootstrap-based themes. Could you make a PR to replicate the correct behavior in `boot{strap,blog}4{,-jinja}`? (`-jinja` can be auto-generated with `scripts/jinjify.py`)

**Comment by keturn** [comment]
Yeah, I can do a PR for this one.

Should the themes be sharing any of this code between them, or should I make the change to each theme individually?

**Comment by Kwpolska** [comment]
Do it individually, attempting to make small stuff reusable at template level isn’t going to work.
