### ISSUE TITLE
lighter-weight fancy dates

### ISSUE THREAD

**Issue by keturn** [getnikola/nikola#3232]
"Fancy dates" are currently implemented using [moment.js](https://momentjs.com/), which is well-known for being a comprehensive and robust date-handling library. It's also well-known for being _enormous_ when shipped with all supported locales — 319 kB, probably the size of all the content on my Nikola site put together. :joy: 

Fortunately, as a static site, we only need a few bits of functionality from the wide world of date handling.

# prereq: parsing the date in JavaScript

To get a JavaScript [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) object, MDN recommends passing an integer timestamp (in milliseconds since the epoch), since that's the hardest for implementations to get wrong. However, using an ISO-8601 formatted string, as Nikola currently produces for `webiso` dates, should be fine too. We don't need any additional client-side dependencies for parsing or validating that format.

# Fanciness 1: using JS_DATE_FORMAT and local user time

Formatting a Date as a local time in _some_ sort of locale-appropriate way is available as [Date.toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString). But since, for fanciness purposes, we as the publisher want more control over the formatting, we have to look further.

`Date.toLocaleString` does support options, though the option syntax is more verbose than the strftime-style format used by Moment and less flexible, placing more trust in the browser's internationalization catalogue to do the right thing.

To be able to use strftime-style format strings, consider

- [luxon](https://moment.github.io/luxon/docs/manual/formatting.html#tolocalestring--strings-for-humans-) Luxon is by one of the maintainers of Moment, but relies on the browser's native Intl implementation instead of shipping its own locale files. 
- [date-fns](https://date-fns.org/v1.30.1/docs/format); [locales specified at build time](https://date-fns.org/v1.30.1/docs/I18n) 
- [dayjs](https://github.com/iamkun/dayjs/blob/dev/docs/en/API-reference.md#format-formatstringwithtokens-string) (non-English locales must be [specified at build time](https://github.com/iamkun/dayjs/blob/dev/docs/en/I18n.md))

Some of these libraries are similar in size to Moment, but are more friendly to loading just certain functions (i.e. formatting) without dragging in the whole thing.

# Fanciness 2: using a string like “2 days ago”

This level of fanciness does not yet enjoy native browser support, though see the [TC 39 Proposal for Intl.RelativeTimeFormat](https://github.com/tc39/proposal-intl-relative-time). Polyfill may be available.

- [luxon](https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-toRelative); internationalization depends on Intl.RelativeTimeFormat, will fall back to English.
- [date-fns](https://date-fns.org/v1.30.1/docs/distanceInWordsToNow)
- [dayjs RelativeTime plug-in](https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md#relativetime)
- [timeago](https://timeago.org/) 

# Other Considerations

- What's Nikola's browser support policy? Does it include any [browsers that don't support Internationalization](https://caniuse.com/#feat=internationalization)? Would it be okay if those browsers fall back to non-fancy dates?
- JavaScript build process. The extent to which we can deliver a smaller payload than Moment may depend on having a modern bundler; if Nikola's javascript dependencies are limited to "prebuilt things" (as mentioned in https://github.com/getnikola/nikola/pull/2965#issue-169454509 ), that'll rule out some of the alternatives.

Related: 
 - #2183 (which is currently titled "Unnecessary .js includes" but only cites moment.

**Comment by Kwpolska** [comment]
> * What's Nikola's browser support policy? Does it include any [browsers that don't support Internationalization](https://caniuse.com/#feat=internationalization)?

We currently don’t have any specific policy for browser support. Note that while Level 1 will probably be supported correctly, Level 2 won’t, as [RelativeTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat#Browser_compatibility) was added to Chrome (stable) in December 2018, and to Firefox in January 2019. It’s not supported by Safari.

A good rule-of-thumb that I would personally approve would be that a JS feature may be used, if it’s supported:
* by stable versions of Chrome, Firefox and Safari
* on desktop and mobile
* for at least 3 months

> Would it be okay if those browsers fall back to non-fancy dates?

As long as the number of affected users is small, sure.

> * JavaScript build process. The extent to which we can deliver a smaller payload than Moment may depend on having a modern bundler; if Nikola's javascript dependencies are limited to "prebuilt things" (as mentioned in [#2965 (comment)](https://github.com/getnikola/nikola/pull/2965#issue-169454509) ), that'll rule out some of the alternatives.

Nikola will *never* require Node to be installed for the core feature set. [The Node ecosystem is terrible](https://chriswarrick.com/blog/2019/02/15/modern-web-development-where-you-need-500-packages-to-build-bootstrap/), and external dependencies are always a pain to get working.

Another possible solution to minimize asset size would be to re-use the infrastructure previously used with Colorbox (copy only required locales to output, load only one i18n file on a page): https://github.com/getnikola/nikola/commit/f45bafbfefcc6c47387c057f28cfae18e86541f8 — cdnjs [supports that workflow](https://cdnjs.com/libraries/moment.js/) as well, even if we wouldn’t be able to use SRI for these files.

**Comment by xxyuk** [comment]
Day.Js is a nice alternative to me. It's supper small, only 2kb with locale and format.

⏰ Day.js 2KB immutable date library alternative to Moment.js with the same modern API

https://github.com/iamkun/dayjs

**Comment by tritium21** [comment]
> 
> 
> Day.Js is a nice alternative to me. It's supper small, only 2kb with locale and format.
> 
> ⏰ Day.js 2KB immutable date library alternative to Moment.js with the same modern API
> 
> https://github.com/iamkun/dayjs

Not sure if it's used by nikola, but it doesn't look like dayjs has timezone support

**Comment by ralsina** [comment]
Looks like relative dates are there except for Safari

https://caniuse.com/#feat=mdn-javascript_builtins_intl_relativetimeformat

Would that be acceptable @Kwpolska ?

**Comment by Kwpolska** [comment]
@ralsina 

1. Safari is kinda popular, and is the only available browser on iOS.
2. Safari is also a terrible browser to work with these days.
3. At the same time, the feature is very minor, so even if we fall back to a “regular” date, that shouldn’t be too much of an issue.
4. We could switch to the built-in browser support. For Safari, if we find a polyfill that does it well enough, we could use that.

I’m going to take a look at this, probably using luxon, because I don’t feel like messing with date parsing in JS by foot.
