### ISSUE TITLE
Improve experience of multilingual feed autodiscovery

### ISSUE THREAD

**Issue by friedelwolff** [getnikola/nikola#3248]
In my multilingual site I had the problem that my RSS reader (Liferea) uses the first RSS feed link when pointed to an HTML page. No choice between the different languages is presented like with the Firefox extension Awesome RSS.

A simple solution might be to make RSS_LINK translatable, but a principle that might improve the feed autodiscovery is to make the RSS feed of the page language the first link in the head tag. The assumption might be that somebody copying a URL for the current page into their feed reader might want the RSS feed corresponding to that language.

**Comment by ralsina** [comment]
RSS_LINK should really go away. It was meant for using a 3rd-party RSS service like feedburner, which is not a thing that exists anymore.

If you don't set RSS_LINK then it should behave the way you expect.

**Comment by friedelwolff** [comment]
Thank you for the response. Then I guess something else is wrong. I have two languages enabled, 'en' (DEFAULT_LANG), and 'af'. The RSS links are always in the order [af,en] in all HTML files regardless of the language of the page.

**Comment by ralsina** [comment]
Ok, that sounds like something that needs fixing then!

**Comment by ralsina** [comment]
Sadly the easy way to change this in the templates would be backwards-incompatible and would break 3rd party themes.

I am looking to see if there is a not-so-easy way :-(
