### ISSUE TITLE
Multiple authors for a post

### ISSUE THREAD

**Issue by certik** [getnikola/nikola#3252]
Currently one can specify a single author of a post using the `author` metadata field.

For post authored by multiple authors, there currently does not seem to be a way to specify that.

**Comment by ralsina** [comment]
Sorry about taking so long to acknowledge this issue, I have been busy.

This is a reasonable request, let's look into it a bit more:

* :+1: Metadata is arbitrary, you can add a "authors" field if you want
* :-1:  It's better if we standardize how that field would look 
* :-1: It's not supported in the default templates. Do you know of any site using multiple authors per post and like how it looks?
* :+1: There is support for multiple authors in docutils if we used document's metadata (no idea how well that works)

So, let's talk about it.

**Comment by certik** [comment]
I switched to Hugo, so here is an example of my blog post:

https://lfortran.org/blog/2019/04/why-we-created-lfortran/

You can see multiple people in the authors section, and here is how I did it:

https://gitlab.com/lfortran/web/www.lfortran.org/blob/66157184d69b01c57a576061e1c8b608c85539a5/content/blog/why-we-created-lfortran.md#L5

So perhaps Hugo thinks it's just one author, but I don't mind, as long as it looks good online.

**Comment by ralsina** [comment]
You could do exactly the same thing. Like copy & paste it :-)

Closing then.

**Comment by certik** [comment]
Perfect!

**Comment by fadelkon** [comment]
Hey, sorry to comment on a closed issue, but the current solution does not work for me.
In a shared blog, where there is more than one person writing, and sometimes or often, the entries are co-authored, then, the /authors special page is not useful. The simplest case:

Ann: how to code in fortran
Ben: using jupyter notebook
Ann & Ben: exploring LFrotran together

Then, I expect that in authors/ann and in authors/ben, there are 2 articles in each.
Is this something that I could change from a template?

**Comment by ralsina** [comment]
Metadata is arbitrary you could just have author1 / author2 / author3 and
so on and just fix the post template to support that

**Comment by fadelkon** [comment]
I understand this, but how can I do it so that I can have authors index page that for each author, the "shared posts" are recognized too?

If I used `author2`, then author index won't read it.

Similarly, if I populate `author: Ann & Ben` and interpret it from my template, the author index will show `Ann`, `Ben` and `Ann & Ben`. I don't want to create "combination authors" like that.

**Comment by ralsina** [comment]
Good point. Yes, you are right.

Sadly, the authors plugin is fairly convoluted. I don't promise anything
since I am mostly retired from open source, but I will try to take a look.

**Comment by Kwpolska** [comment]
I tried to solve this, and it’s a fairly easy fix (that can be backwards-compatible). See PR #3456 (please test and review).
