### ISSUE TITLE
add media.ccc.de integration to media directive

### ISSUE THREAD

**Issue by dvzrv** [getnikola/nikola#3253]
It would be very awesome to be able to include videos/ streams from https://media.ccc.de using the `.. media::` directive.
The service is run by the German hacker association [Chaos Computer Club (CCC)](https://ccc.de), which hosts annual events itself and lends streaming expertise to many external events via its [Video Operation Center (VOC)](https://c3voc.de).

The streaming service is a valuable source of information on many different topics and I think it would be an awesome addition!

If you have pointers on where I can add it, I might be able to do a pull request myself. I wouldn't call myself a Python expert though :-)

**Comment by Kwpolska** [comment]
The `media` directive offloads all work to the [micawber](https://github.com/coleifer/micawber) library. You can send a pull request to them.

I’ll close this since any changes made would be made in that library only, not Nikola itself.

**Comment by dvzrv** [comment]
Thanks! Sorry for the misunderstanding.
