### ISSUE TITLE
Org-Mode: Captions and HTML Attributes

### ISSUE THREAD

**Issue by ManosMagnus** [getnikola/nikola#3257]
Will be great if we can add captions at images and HTML attributes as it is described at [org-mode doc](https://orgmode.org/manual/Images-in-HTML-export.html)

**Comment by Kwpolska** [comment]
Please:

1. direct plugin issues to the [Plugins repo](https://github.com/getnikola/plugins)
2. describe the current behavior and desired behavior (including input, current output, desired output)
