### ISSUE TITLE
support for academicpages.github.io template

### ISSUE THREAD

**Issue by Evfro** [getnikola/nikola#3259]
Even though setting up and running a simple web site is very straightforward and easy with Nikola, transforming it into a fully-featured personal site such an academic web page is still quite labor-intensive. On the other hand, there exist some well-developed ready-to-use constructors, e.g., https://sourcethemes.com/academic/ that offer an almost instant solution with minimal tweaking required.

I believe that having something similar in Nikola would be one of the killer features, especially taking into account that the support for Jupyter Notebooks in other frameworks is still nothing like `nikola new_post -i` functionality. After making some research on possible solutions, I have stumbled upon the [AcademicPages](https://github.com/academicpages/academicpages.github.io) project, which basically provides the fully fledged scaffold for building a personal academic website with minimal coding. It would be really nice to include the template provided at https://academicpages.github.io/ into the Nikola's batteries and ensure seamless integration with Nikola's site deployment.

**Comment by ralsina** [comment]
The main problem doing this is maintenance.

I created a template with a similar idea for small event sites, and it did get used, but I did not maintain it properly (I think it's still working now, but not sure)

Nikola does support using arbitrary directories as templates internally (it's how "nikola init --demo" works) and I guess we could expose that to make this easier.

However ... I don't want to own any more pets :-)

So, I would be willing to work on the code to make this easier, but I will not own the site template, and volunteers are welcome.
