### ISSUE TITLE
option to disable self-links from post titles

### ISSUE THREAD

**Issue by Evfro** [getnikola/nikola#3260]
By default, all post titles are formatted with the self-link. For example, the demo post "Welcome to Nikola" has such title: clicking on it does nothing as the link simply points to the post itself. It doesn't seem reasonable neither from user experience nor from SEO perspective.

Currently, I use a workaround via `custom.css` file to disable the link and set the text color as follows:
```css
.entry-title a {
  pointer-events: none;
  cursor: default;
  color: #text_color
}
```

However, it doesn't feel future-proof and it would be great to have an option to control this via the configuration file, rather than altering theme style. Something like
```python
# Disable self-links in post titles
POST_TITLE_SELF_LINKS = False
```
which would treat titles as normal headers without hyperlinks and set appropriate color.

**Comment by ralsina** [comment]
Just change the template?

**Comment by Kwpolska** [comment]
Yeah, having an option for this doesn’t make much sense if (a) I doubt there is a lot of users who want it, (b) it’s trivial to remove the links from templates on your own.

**Comment by Evfro** [comment]
Thanks! I haven't thought about customizing templates. It certainly does the job (I used  `post_header.tmpl`) and I guess it is more reliable. However, isnt it an overkill for simply disabling the feature, which anyway seems to have no practical usecases?

I'm not insisting, as I'm not experienced in web development and have no idea of any simpler way to achieve this. If the proposed feature request would require unreasonable amount of work on internal parts of Nikola than I'm fine with closing this issue.

**Comment by Kwpolska** [comment]
You can right-click and copy the permalink. We don’t want to make this configurable, because (a) ~nobody would discover the option, (b) it would add extra complexity to templates.
