### ISSUE TITLE
NAVIGATION_ALT_LINKS does not keep element order

### ISSUE THREAD

**Issue by angelgcuartero** [getnikola/nikola#3261]
### Environment

**Python Version:**
Python 3.7.3

**Nikola Version:**
Nikola v8.0.2

**Operating System:**
macOS 10.13.6 (High Sierra)

### Description:
I was trying to configure NAVIGATION_ALT_LINKS and found that the element order was shown different almost everytime I saved conf.py. I had no problems with NAVIGATION_LINKS, so I created a new site for expermentation and found that default conf.py has this:

```python
NAVIGATION_LINKS = {
    DEFAULT_LANG: (
        ("/archive.html", "Archive"),
        ("/categories/", "Tags"),
        ("/rss.xml", "RSS feed"),
    ),
}

NAVIGATION_ALT_LINKS = {
    DEFAULT_LANG: {}
}
```
DEFAULT_LANG is created as a tuple in NAVIGATION_LINKS, so it keeps the element order and as a dictionary in NAVIGATION_ALT_LINKS. Dictionaries don't keep the element order. Maybe it's enough to change the code in line 91-93 in conf.py.in to 

```python
NAVIGATION_ALT_LINKS = {
    DEFAULT_LANG: ()
}
```
because it does not perform any variable substitution.

**Comment by Kwpolska** [comment]
Good catch. I made it into a tuple by default, in commit 6b41c11d8.
