### ISSUE TITLE
Support for peertube embed video

### ISSUE THREAD

**Issue by parisni** [getnikola/nikola#3263]
Hi

The `media` tag allows to embed a youtube video
```
.. media:: https://youtu.be/somehash
```
produces the html/css code to embed the video.

Peertube is a decentralized video platform. It allows embed videos (eg: https://video.ploud.fr/videos/embed/f14ffa07-4c6e-4cf6-acb9-4594943b95cd). as a decentralized platform it does not have a unique hostname (ie video.ploud.fr , peertube.cpy.re ...)

I have been able to embed the video by replacing the result of a youtube link within the built html code.

I wonder if nikola offer a way to deal with "any" video platform.

Thanks

**Comment by Kwpolska** [comment]
> I wonder if nikola offer a way to deal with "any" video platform.

We could use micawber’s capabilities to fetch URLs from https://noembed.com/ (we currently don’t), but all those PeerTube platforms would need to register themselves with noembed. On the other hand, you can just use an `<iframe>` in a raw HTML block and put any URL in there.
