### ISSUE TITLE
Make the contents of an empty post configurable

### ISSUE THREAD

**Issue by rixx** [getnikola/nikola#3267]
Currently, if you create a new post (or a new page), the content will be "Write your post here". This string is [static](https://github.com/getnikola/nikola/blob/5b202f3afe164bd0296760bb96fbb031652a86b1/nikola/plugins/command/new_post.py#L424) It would be helpful to be able to configure this string via the settings, to include a certain structure, or editing hints, etc.

**Comment by Kwpolska** [comment]
I’m not sure if this is worth implementing, but either way, you can always use `nikola new_post -i template.rst`. This will also make the template independent of the config file and less error-prone than typing it into `conf.py`.

**Comment by rixx** [comment]
All right, in that case I'll continue misusing `ADDITIONAL_METADATA`, I guess. Thank you for your consideration.
