### ISSUE TITLE
The procedure to configurate de Markdown should be more clear

### ISSUE THREAD

**Issue by wescley** [getnikola/nikola#3268]
Hi Nikola Team,

Good Evening,

I try to configurated Markdown in example web site using the Nikola's Handbook and i have difficut to do.
May be the procedures should be more clear.

Thanks

**Comment by Kwpolska** [comment]
What, do you think, is unclear? What could be improved? Nikola supports Markdown in freshly created sites, you just need to tell `nikola new_post` to use Markdown.

**Comment by wescley** [comment]
Hi Kwpolska,

Thanks for your response.
See in te page of my site example.
I try tu put some markdown and this don't render in the screen.

```
### Test Site

#### asdfg

```

Holds

**Comment by Kwpolska** [comment]
You haven’t posted any links to your website.

**Comment by Kwpolska** [comment]
You haven’t posted any links to your website. I added a few extra notes to the manual (commit 45d9b0e75), changes will appear on the website with the next release.
