### ISSUE TITLE
Plotly breaks KaTeX and RequireJS

### ISSUE THREAD

**Issue by fullpwemium** [getnikola/nikola#3270]
### Environment

**Python Version:**

3.7.3

**Nikola Version:**

8.0.2

**Operating System:**

macOS Mojave 10.14.5

### Description:

By adding 
```python
EXTRA_HEAD_DATA = "<script src='https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js'></script><script>requirejs.config({paths: { 'plotly': ['https://cdn.plot.ly/plotly-latest.min']},});if(!window.Plotly) {{require(['plotly'],function(plotly) {window.Plotly=plotly;});}}</script>"
```

It breaks KaTeX:

> [Error] ReferenceError: Can't find variable: renderMathInElement
> 	Global Code (my_post:509)
> [Error] ReferenceError: Can't find variable: baguetteBox
> 	Global Code (my_post:531)

and issues with RequireJS I think: 

> Error:` Mismatched anonymous define() module: function (){

To add, only a few of the Plotly figures (embedded into a jupyter notebook) actually appear, some disappear/reappear as I refresh

**Comment by Kwpolska** [comment]
We don’t provide support for third-party scripts. It looks like requireJS messes with module loading so much our regular scripts won’t load. You will need to find an alternative solution to use plotly.
