### ISSUE TITLE
Comments link in comments_helper_disqus.tmpl is not translatable

### ISSUE THREAD

**Issue by cpkio** [getnikola/nikola#3271]
Replace `>Comments</a>` to `>${messages("Comments")}</a>` to make «Comments» link translatable in `comments_helper_disqus.tmpl` and `comments_helper_isso.tmpl`, otherwise it will always be «Comments» no matter the language selected.

**Comment by Kwpolska** [comment]
Could you make a PR with this?

**Comment by Kwpolska** [comment]
Fixed in #3272.
