### ISSUE TITLE
Can't get a TOC in IPYNB

### ISSUE THREAD

**Issue by fullpwemium** [getnikola/nikola#3273]
Hello,

I can get a TOC in markdown using the documentation with no issue, however I can't do the same in IPYNB. I tried {{% contents %}}, but this doesn't work. 

Other rst shortcodes I tried in IPYNB: {{% media url="https://www.youtube.com/watch?v=Nck6BZga7TQ" %}}, which also didn't work.

Is there any way to do this? 

I would also be happy adding it to my post.tmpl, switched on by a metadata switch, but I can't figure this out either..

**Comment by Kwpolska** [comment]
The Jupyter compiler uses its own Markdown converter. It might not support Markdown extensions `contents` is not a Nikola shortcode, it’s a reST feature. It seems to have shortcode support enabled, though, so it seems that `media` should work, as long as it’s exposed to shortcode-based compilers.

**Comment by Kwpolska** [comment]
The documentation is slightly wrong, there should be no quotes around the URL. Other than that, the media shortcode works. I’ll update it.

As for the ToC part, there seems to be a Jupyter/nbconvert plugin available that does this: https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/toc2/README.html

**Comment by fullpwemium** [comment]
> The documentation is slightly wrong, there should be no quotes around the URL. Other than that, the media shortcode works. I’ll update it.
> 
> As for the ToC part, there seems to be a Jupyter/nbconvert plugin available that does this: https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/toc2/README.html

thank you - I've tried the Jupyter plugin but it isn't great, Ideally I want to put this in post.tmpl - is there any way to do this?

**Comment by Kwpolska** [comment]
It’s possible, but difficult. You would need to write a custom Python function that takes the HTML of the post and produces a ToC for it, and expose that function to templates.

**Comment by k-allika** [comment]
I wondering if this could be considered as an enhancement request. I primarily use ipynb files to write my blog posts and currently make TOCs manually. If Nikola could do it automatically, it would be brilliant.

**Comment by Kwpolska** [comment]
@k-allika You can try the Jupyter plugin linked in the previous discussion, or look for a different one. Nikola delegates ToCs to compilers. You could write a Nikola plugin that can generate a generic ToC, as suggested in the previous discussion, but a generic ToC would be unaware of some specific constructs that use `<h*>` but are not real headings. I don’t think this feature should be provided by Nikola, it should be an external plugin in the plugin repository, to which contributions are welcome.
