### ISSUE TITLE
Multiple questions regarding customizing the build system (nested shortcodes, directory tree mapping, assets)

### ISSUE THREAD

**Issue by Xeverous** [getnikola/nikola#3277]
First, before everything I would like to thank Nikola, because among [tons of other static site generators](https://www.staticgen.com/), **it's the only one** that has all of the following features which I need (maybe Hugo also has all of these but I prefer Python to Go):

- not limited to a blog
- custom subparsers (here named *shortcodes*) through plugins
- the possibilty for a custom data model (not as built-in as in [Statik](https://getstatik.com/) but I can do I through plugins)
- advanced build step customization

___

I have a plan for a relatively complex website and this raised few questions for me

1. If a page depends on some data (eg image), how should it be expressed in the page source? Just call a shortcode with that file and let it report the dependency to the generator?
1. Is there any convention for storing globally-accessible data? I might have a lot of binary (eg images) and non-binary data (eg some fixed text) that need to be accessed from multiple pages.
1. How should I handle nested shortcodes? AFAIK neither Markdown or reST parsers support them. I have a need for nested `div`s in final HTML, at worst instead of `{{% foo %}} {{% bar %}} ... {{% /bar %}} {{% /foo %}}` I can write `{{% foo %}} {{% bar %}} ... {{% end_foo %}} {{% end_bar %}}` and implement all these `foo`, `bar`, `end_foo` and `end_bar` as plugins but is this possible at all? I would need for my plugin to be able to store some state and a guuarantee that it will be called exactly in the order of shortcodes appearance (and not interleaved while doing other article or having some way to detect this - eg on file path)
1. How are the source files of non-blog pages mapped to the resulting output directory? Simply 1:1 (representing the same directory tree)? Can I use `PAGES` config value to implement 1:1 directory tree mapping?
1. This is a bit silly approach, but I have seen few frameworks/highlighters/generators which did not implement proper parsers (Chomsky Type-2 or Type-1) and instead based the entire Markdown/reST/other compiler on regular expressions (regular grammar == Type-3) which are incapable of parsing more complex grammars than Type-3. Asking this to prevent the issue that if I host some very complex and symbol-intensive code on my site (like regexes, C++ or Haskell), everything would break in syntax errors.
1. If I want to genete something like a sitemap or a hierarchical menu, which build step would be good to plug into? (I would need to run it either on source structure or almost-done output directory.)

**Comment by Kwpolska** [comment]
1\. and 2\.
For binary data, you would generally store it in `files/` or `images/` and just refer to it with an `<img>` or `<a>` or other tag in the output HTML. For that, you don’t need dependencies, the file will just independently copy itself when it changes. For text/JSON-ish data, you could use the *data files* system: https://getnikola.com/handbook.html#the-global-context-and-data-files

3\.
This is not supported. The shortcode system is generally meant for non-complex use-cases.

4\.
The directory trees are generally reproduced on output, adding the PAGES directory in front (it can be blank), and `PRETTY_URLS` can also change stuff.

5\.
The shortcode parser is unaware of the surrounding context.  If you had `{{%` in your actual blog post content, that would need to be escaped.

6\.
We generate a `sitemap.xml` file for search engines. If you want a user-readable sitemap, you might need to write a custom plugin to generate that file, based on data in the site object — it has a representation of all posts/pages there are on your site.

---

Could you describe the use-case for shortcodes you have in more detail? Maybe we could propose something different that would solve it in a better way.

**Comment by Xeverous** [comment]
1\. and 2.

Ok, so basically I can put all the binary assets in the `files` directory and use `files`-rooted paths everythere. Am I right?

4\.

Great, this solves all problems. I wanted exactly this (reproduced directory tree + some fixed paths from config).

5\.

Escaping is a natural solution to conflicts in complex grammars. I'm completely fine with this.

6\.

> based on data in the site object — it has a representation of all posts/pages there are on your site

Does this data hold just paths or the actual preamble contents (title, author etc) of each page?

___

> Could you describe the use-case for shortcodes you have in more detail? Maybe we could propose something different that would solve it in a better way.

I want to be able to implement multiple dynamic elements that may host child elements in the final HTML. For example:

- spoilers
- text block with different backgrounds
- highlighted code block

If I understand correctly, It would not be possible to have any nested structure without the support for nested shortcodes:

- a code block inside a spoiler block
- a different-background-color-text block-within another such block
- image inside a different-background-color-text block-within

My idea for a workaround was to just implement them separately (as 2 different shortcodes, without `data` parameter):

- `{{% spoiler %}}` that would emit `<div class="spoiler">` HTML
- `{{% end_spoiler %}}` that would emit `</div>` HTML

The only problem would be verifying that all shortcodes are closed and closed in proper order.
___

Also, thanks for the fast response.

**Comment by Kwpolska** [comment]
1\. and 2\.
With the default config, files in `files/` are copied to the main output directory (eg. `files/foo/bar.png` becomes `output/foo/bar.png`). Use `/foo/bar.png` to refer to it from HTML.

6\.
Full metadata is available in Post objects.

---
7\.
Consider writing reST or Markdown extensions instead of manually-paired shortcodes. Those will be a lot more flexible than shortcodes are, and allow for more markup possibilities than shortcodes. In fact, your `spoiler` example can be just done with a `.. class:: spoiler` in reST.

**Comment by Xeverous** [comment]
Ok, so I have all figured out except 7.

I get that markdown/reST extensions can be more powerful than custom shortcodes, but can they be nested?

**Comment by Kwpolska** [comment]
That depends on the specific implementation, check the docs for the
respective markup compilers (docutils, python-markdown)

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by Xeverous** [comment]
Ok, I will check and see what can be done. At worst, I will implement 2 custom shortcodes and another build blugin which will verify that all nested custom shortcodes are properly closed.
