### ISSUE TITLE
Avoiding copying unwanted built-in assets.

### ISSUE THREAD

**Issue by Xeverous** [getnikola/nikola#3282]
https://github.com/getnikola/nikola/issues/3279#issuecomment-518420117

Even though `css/code.css` is in ignored_assets, it is still copied to the output directory. `ignored_assets` field in the theme settings does not work against this file.

I don't think that manually specifying assets to ignore is a stable and future-proof solution. I would like to have control on what is done and when. "Nikola is a pile of plugins", the documentation says so I think it would be good to have every functionality replacable and no hardcoded behaviour other than the order of the build steps.

Right now there is no easy way to avoid some of built-in behaviours without disabling them altogether. Galleries, gists, indexing etc can be disabled if someone does not need them, removing the need for certain HTML templates. But copying assets is so fundamental that practically no website would want to disable it.

Poposed solutions:

- Fix the bug with `css/code.css` not being properly ignored. (I don't think this is a good long-term solution.)
- Split `copy_assets` plugin into 2 plugins: one that copies user assets and one that copies built-in assets which are required by other built-in plugins. This will also prevent name conflicts.
- Make the "base case" that no of built-in assets are copied and `conf.py` contains entries which files should be copied.

**Comment by ralsina** [comment]
There is no distinction between "built-in assets" and "your assets".

The copy_assets plugin copies the assets of the current "theme chain". If the "theme chain" is just your theme and it has no parent, then all the assets are your assets. If you have a parent theme then you **need** those other assets or your site is broken.

There is a bug, tho: it copies code.css even when it's not part of your theme because it has some special handling (it can be generated as response to a config option rather than as a file that is part of a theme)

**Comment by ralsina** [comment]
In fact, the problem is that copy_assets is *generating* code.css because of CODE_COLOR_SCHEME

Can you try setting "CODE_COLOR_SCHEME=None" in your conf.py and see if that helps?

**Comment by Xeverous** [comment]
> If the "theme chain" is just your theme and it has no parent, then all the assets are your assets. If you have a parent theme then you need those other assets or your site is broken.

Ok, that makes sense.

Once I get back home I will check these:

- Value and behavior of `CODE_COLOR_SCHEME` in `conf.py`
- Whether `ignored_assets` in my theme are actually needed. Now it has no parent so no additional assets should be copied (unless there is something in `conf.py` that tells to generate something).

**Comment by ralsina** [comment]
From a quick reading of copy_assets it should be just code.css

**Comment by Xeverous** [comment]
> Whether ignored_assets in my theme are actually needed. Now it has no parent so no additional assets should be copied (unless there is something in conf.py that tells to generate something).

You were right. No assets beyond `css/code.css` were copied.

> Value and behavior of CODE_COLOR_SCHEME in conf.py

Setting it to `None` caused `css/code.css` to not be copied.

___

So Nikola really does have "no files to copy by default", one just need to have parent-less theme and disable plugins + CODE_COLOR_SCHEME . The problem is gone, thanks.
