### ISSUE TITLE
Obtaining and using site information before compilation

### ISSUE THREAD

**Issue by Xeverous** [getnikola/nikola#3285]
I want to create few things:

1. An index page, which contains a tree view of all other pages. Something similar to sitemap.xml, but readable for users like any normal page.
1. Breadcrums on each page, allowing to easily see where you are and click some part of it to go upwards.
1. Next/previous buttons on each page to go forward/backward when reading tutorial pages.

The problem is that AFAIK site structure information (all posts/pages and their titles, etc) is gathered after all pages are scanned. I need this information inside templates. Is such thing available there?

Other issue is that in order to generate index page, all pages must be scanned. Creating index page adds another page, which appears after all pages have been scaned. So it will likely not be compiled. Is there any way here to avoid circular dependency?

**Comment by ralsina** [comment]
Each use case is different.

1. Use JS to load the actual sitemap. It's very trivial XML. Alternatively, convert it to JSON and load that instead. Alternatively: convert it to HTML and include it in the generated HTML serverside.

If you try to do this on render time, you will have to rebuild your site every time the sitemap changes. That is pretty much all the time.

2. This only makes sense for some specific templates and AFAIK it's perfectly possible to add it. For example, listings already does this. If you can give me specific examples I am happy to give it a shot. I ask for specific examples to avoid implementing it first on places where you don't care.

3. Add metadata to pages that have a specific prev/next relation and use it in their templates.

**Comment by Kwpolska** [comment]
For (1), you could make a plug-in that renders the HTML based on
site.timeline, outside of the page system. You could also look at the reST
post-list directive; it might not support a structure, but you could modify
the code to make it work this way. I wouldn't do it on the JS side myself.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by ralsina** [comment]
I sort of agree that you should do a plugin to render the HTML based on site.timeline, mostly because the real sitemap.xml is too full of uninteresting things to be useful.

BUT it also depends a little on what the site contains. If there are things in it not generated by Nikola via files/ or whatever, it could take a little more effort.

**Comment by ralsina** [comment]
I missed this bit:

> Other issue is that in order to generate index page, all pages must be scanned. Creating index page adds another page, which appears after all pages have been scaned. So it will likely not be compiled. Is there any way here to avoid circular dependency?

Oh yes, and that's why sitemap has been a pain in the ass in the past :-)

We have a "LateTask" plugin type for that, they run after all the site itself has been generated. It is a cheat, since if there was a plugin that depends on sitemap.xml and generated files that need to go in sitemap.xml it would not work, but in practical terms it works.

**Comment by Xeverous** [comment]
1\. Where can I find the documentation on site.timeline? https://nikola.readthedocs.io/en/latest/template-variables/#global-variables has no such thing. I would still prefer to have the data that scanning posts can provide. At worst it could be:

- scan pages
- my plugin that generates index pages based on site information
- scan pages (again)
- compile pages and continue

If there is no way to repeat scanning, I think I should just go with my own (non-plugin) script that will scan pages directory and create index pages for me. Then call nikola build. Then call my script again whenever I need to regenerate index.

2\.

> If you can give me specific examples I am happy to give it a shot.

Suppose such directory structure (of pages):

```
home
faq
about
tutorial1
  foo
    foo1
    foo2
  bar
    bar1
    bar2
tutorial2
  baz
    baz1
    quux
      quux1
      quux2
      quux3
```

Suppose we are on tutorial1/bar/bar1. Then the breadcrumb should be `home / tutorial1 / bar / bar1`. Each of words in the breadcrumb should be a link, so I will need title and url to each parent page.

The main problem is that the breadcrumb will be different for each page, so for each page I need a complete site structure information.

3\. Is there any way to obatin other page metadata while compiling current page? I could add metadata like next/prev but I would need to also obtain the paths, not just the titles. There might be many ways to reference related pages, but I would like to avoid code duplication and use only 1 property (eg title, relative path) and obtain all of others (full file path, title, url).

___

> We have a "LateTask" plugin type for that, they run after all the site itself has been generated.

I do not need to run anything aftert the site has been generated. Only after scanning, but before compilation.

**Comment by Xeverous** [comment]
2\. and 3. are relatively simple if Nikola can provide site structure information during compilation of each page.

1\. is more complex because it needs a site structure to generate a page ... which will inevitably add another page to the structure.

**Comment by Kwpolska** [comment]
1. site.timeline is not a global variable and is not accessible from
templates. It's a property of the site object, to which every plugin gets a
reference. site.timeline is a list of all Post objects found by the
scanner. There are also some more structures available you can find in
nikola.py and scan_posts.py. Consider reviewing the existing code and
possibilities of post_list first, before implementing something custom from
scratch.

3. Posts (not pages) already have chronological prev/next, and I believe we
also have a plug-in available that groups these by category. You could take
that code and make it add prev/next data for pages based on the directory.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by ralsina** [comment]
> 1. Where can I find the documentation on site.timeline?

When you write a plugin, you have a site object. site.timeline is a list of all posts and pages (all of which are Post objects) Keep in mind that Pages here doesn't mean "every HTML file Nikola generated" but just all the documents created from what the PAGES option in the configuration declares.

> 2. Suppose such directory structure (of pages):

So, those are pages? Cool. In that case, they are rendered by something like page.tmpl (which in most themes is the same as story.tmpl for historical reasons)

In those templates you have a post object, which is an instance of Post. That object has all the path information you may need.

There is an implementation of breadcrumbs in ui_helper.tmpl which takes a list of (link, text) crumbs.

You would need to parse the paths into crumbs, there is code for that in utils.get_crumbs() which you can expose to your templates if you want via GLOBAL_CONTEXT (I am fairly sure we have a different, better way to expose functions to templates but can't remember it)

One possible problem is that there is no guarantee that those paths are meaningful, but perhaps setting PAGE_INDEX = True will be enough.

**Comment by Xeverous** [comment]
> Posts (not pages) already have chronological prev/next, and I believe we
also have a plug-in available that groups these by category. You could take
that code and make it add prev/next data for pages based on the directory

My order of articles is not chronological. They may also be reordered in the future. Pages might be updated in the future. Generally, dates will be arbitrary and have very little to do with order.

> So, those are pages? Cool. In that case, they are rendered by something like page.tmpl

Yes, these are pages. But I use only my own HTML templates.

> [...] an instance of Post. That object has all the path information you may need.
>
> There is an implementation of breadcrumbs in ui_helper.tmpl which takes a list of (link, text) crumbs.

Yes, such template is very close to what I want. Having such template is not a problem, I'm more interested how to obtain `crumbs` in such template so that it knows for each page, what are its parent and sibling pages and what are their paths and titles. AFAIK templates only get the information about current page.

> When you write a plugin, you have a site object. site.timeline is a list of all posts and pages (all of which are Post objects).

This is good. Having site structure available for any plugin opens a lot of possibilities.

Is there any way to make that site object accessible in templates? Currently the only way I see this is writing a custom shortcode, but I do not really want to spam the same shortcodes at the top/bottom of every page - would prefer to make my template obtain site structure information without needing to modify any pages. Or some way to trigger my plugin with certain parameters while the template is compiled.

**Comment by Kwpolska** [comment]
> Is there any way to make that site object accessible in templates? 

No, it’s not possible, and never will be. If it was available, it would be easy to break the dependency list, because there would be no way to know if a rebuild is necessary or not, based on your use of the site object.  What, exactly, would you do with the access to your `site` object?

PS. please direct further general usage questions to the [nikola-discuss](https://groups.google.com/forum/#!forum/nikola-discuss) mailing list.

**Comment by Xeverous** [comment]
All really boils down to the simultaneous need of HTML generation and availability of the `site` object.

Everything seems easily solveable for me, If I can do one of these things:

A) **Somehow get access to `site` object inside templates.** Then, generating indexes/breadcrumbs/prev/next is very easy for every page.

B) **Somehow trigger my custom plugin from inside the template.** Plugins have site object, and they will know which page triggered them so again ... every page can get customized index/breadcrumb/prev/next.

**Comment by Kwpolska** [comment]
Start here: https://github.com/getnikola/plugins/blob/master/v8/category_prevnext/category_prevnext.py

You can use `next_post` and `prev_post` on pages as well. You will probably want the signal for post scanning, you can find its name in the docs or in the codebase. You can get the previous/next post eg. by specifying the slug in `post.meta`. You can place links to `next_post` and `prev_post` (see default `post.tmpl` for an example).

**Comment by Xeverous** [comment]
> What, exactly, would you do with the access to your site object?

- Generate index page(s). Like sitemap but viewable for end users. This needs to happen before index pages are compiled. This is problematic because I would need to scan, generate indexes, scan again, and then compile all pages (including index pages). This is of course a circular dependency so I don't think there is any working solution based on plugins. At worst, I could just write my own script (not a plugin) that traverses the repository, generates markdown/reST pages and after this trigger Nikola to build the site - Nikola would just see these "index pages" as if written by hand.

- Breadcrumbs need the access to (url, title) of every parent directory page, up to the home (the root directory). Templates know which site is currently being compiled, but they do not know about parent or sibling pages.

- prev/next buttons in certain pages - I would like to avoid any code duplication, preferably some shortcode like `{% next path="../bar/bar1" %}`. Then, the plugin could validate that the path is correct, and generate a HTML for a button containing link (next page url) with appropriate text (next page title).

**Comment by Kwpolska** [comment]
For index pages, take the `post-list` reST directive. If you want the index pages to display a hierarchy, you will need to modify the plugin to provide data to the template in a hierarchical format.

For the rest, make a signal handler plugin, that sets `next_post` and `prev_post` (as above). For the breadcrumbs, it would need to detect the directory structure, and place the breadcrumbs in a way accessible to the templates. It *should* work if you put a list of `(path, title)` tuples in `post.meta` (Strings will definitely work; other Python types should work now, since we support meta formats with more advanced types). Your `next` and `prev` posts would be put in the page metadata, eg. `.. prev: slug-of-other-post` (or the path, if you had duplicate slugs), and your plugin could just look it up in `site.whatever` and place the exact `Post` objects you found in `.{next,prev}_post`.

**Comment by Xeverous** [comment]
So basically I can realize both breadcrumbs and prev/next by doing, in order:

- Specify certain values for `prev` and `next` in page's metadata (eg slugs or paths).
- Signal handler plugin is triggered (on which singal should I register it? `scanned`?). It has access to the site object so it can verify that prev/next are correct and specify appropriate values for `prev_page` and `next_page` metadata fields of any given post. The plugin can also generate a breadcrumb and put it also in the page's metadata.
- Pages are rendered though templates. Templates make use of metadata fields.

Am I right on this?

**Comment by Kwpolska** [comment]
> It has access to the site object so it can verify that prev/next are correct

How would it “verify” it?

> and specify appropriate values for prev_page and next_page metadata fields of any given post.

`prev_post` and `next_post` are not metadata fields, they are attributes of the `Post` object. Now, I checked the source, and it looks like we only use the permalink to the prev/next post for dependency calculation, since we only use that in the default templates. Title changes of prev/next posts would not lead to automated rebuilds. You might want to put the title and URL in `post.metadata` yourself to overcome this, although IMO, adding the post title to the dependencies could be a worthwhile addition.

> Pages are rendered though templates. Templates make use of metadata fields.

Yes. (It would also make use of `post.next_post` and `post.prev_post` if you went that route.)

**Comment by Xeverous** [comment]
> How would it “verify” it?

Check that the given slug/path actually exists. And that it is unambiguous.

> (It would also make use of post.next_post and post.prev_post if you went that route.)

For breadcrumb, my plugin can write metadata field. But which way would you recommend for prev/next and post title? Should the plugin edit page's attributes of the post object OR should it add more metadata fields? I need this data in templates so metadata seems more natural choice for me.

**Comment by Kwpolska** [comment]
1. To be precise: you will need to find the Post object in `site.whatever` based on the provided information, and make sure you find exactly one.
2. Add metadata fields perhaps, even if we don’t make the dependency change that will work from the get-go.

**Comment by Xeverous** [comment]
Great. So "how to implement breadcrumbs and prev/next" is solved.

Now index pages ... I can not really force Nikola to generate any pages (source files like markdown or reST). But I have an idea... I can make a page that is just metadata + 1 shortcode and write a plugin for this shortcode. This way the page source actually exists (so it is scanned) and the plugin obtains any necessary information (site object, post object) to generate the content that will replace the shortcode. Then the page is passed to templates and I can do further work with generate text. Am I right?

**Comment by Kwpolska** [comment]
The index problem is already mostly solved by the `post-list` reST directive, as I have stated twice in this thread already.  Please take a look at it first and don’t reinvent wheels.

**Comment by Xeverous** [comment]
Post list plugin seems to do what I generally want, but how do I modify it? I don't think editing Nikola's sources is a good idea. I was thinking more about writing my own plugin, based on the code from post list.

**Comment by Kwpolska** [comment]
Yeah, you can copy the plugin, rename it, and modify it to suit your needs.
