### ISSUE TITLE
Shortcode plugin registration does not work for arbitrary functions

### ISSUE THREAD

**Issue by Xeverous** [getnikola/nikola#3286]
### Environment

**Python Version:** 3.7.3

**Nikola Version:** 8.0.2

**Operating System:** GNU/Linux 4.15.0-20-generic

### Description:

Shortcode plugin registration does not work for functions named differently than `handler`. I have wrote a dummy (incomplete) plugin but after registering, Nikola has different expectations from what has been actually registered.

```
Traceback (most recent call last):
  File "/home/xeverous/workspace/the_website/venv/bin/nikola", line 10, in <module>
    sys.exit(main())
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/nikola/__main__.py", line 166, in main
    _ = DN.run(oargs)
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/nikola/__main__.py", line 342, in run
    self.nikola.init_plugins()
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/nikola/nikola.py", line 1071, in init_plugins
    self._activate_plugins_of_category("ShortcodePlugin")
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/nikola/nikola.py", line 1222, in _activate_plugins_of_category
    plugin_info.plugin_object.set_site(self)
  File "/home/xeverous/workspace/the_website/website/plugins/generate_index.py", line 12, in set_site
    super(IndexGenerationShortcode, self).set_site(site)
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/nikola/plugin_categories.py", line 486, in set_site
    site.register_shortcode(self.name, self.handler)
AttributeError: 'IndexGenerationShortcode' object has no attribute 'handler'
```

Plugin source:

```python
from nikola.plugin_categories import ShortcodePlugin
from nikola.nikola import Nikola

class IndexGenerationShortcode(ShortcodePlugin):
    name = "generate_index"

    def set_site(self, site: Nikola):
        """Set the site."""
        super(IndexGenerationShortcode, self).set_site(site)
        site.register_shortcode("generate_index", self.generate_index)

    def generate_index(self, site, data=None, lang=None)
        pass
```

The fact that a function of certain name is expected is not mentioned anywhere in the documentation:

- https://nikola.readthedocs.io/en/latest/extending/#shortcodes
- https://getnikola.com/extending.html#shortcodes

It seems to me that the line `site.register_shortcode("generate_index", self.generate_index)` has no effect and that somewhere else the attribute `handler` is hardcoded, preventing working registration of anything named differently.

Documentation uses names `func` and `tag_rss_path` in examples.

**Comment by Kwpolska** [comment]
I updated the docs to reflect what’s happening.  See commit 4a8717721.

**Comment by Xeverous** [comment]
This is not a complete solution. The problem is that I did called `register_shortcode` but it seems to have no effect, still the `handler` attribute is expected.

Here is my `generate_index.plugin` file, with the code above you should be able to fully reproduce the issue:

```
[Core]
Name = generate_index
Module = generate_index

[Nikola]
PluginCategory = ShortcodePlugin

[Documentation]
Author = Xeverous
Version = 0.0
Website = https://xeverous.github.io
Description = Adds generate_index shortcode which outputs structure of all pages and their titles as a hierarchical list of links
```

**Comment by Xeverous** [comment]
Also, when rebuilding the site I'm getting this:

```
[2019-08-15T22:37:03Z] WARNING: Nikola: Shortcode name conflict: generate_index
[2019-08-15T22:37:03Z] INFO: auto: Rebuilding the site...
[2019-08-15T22:37:05Z] WARNING: Nikola: Shortcode name conflict: generate_index
```

I'm pretty sure that this name is not taken by any of built-in plugins. And warning appears twice - I think this might be the same issue as https://github.com/getnikola/plugins/issues/147

**Comment by Kwpolska** [comment]
Shortcode plugins have a set_site method, and it already registered
generate_index (the plugin name) as the handler method. You can rename the
method to handler, remove your custom call and it will just work. If you
want to register multiple shortcodes in one plugin, you can add more
register_shortcode calls to set_site, while keeping the
super().set_site(site) call.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by Xeverous** [comment]
I think you do not understand what I mean.

Why after such code:

```python
    def set_site(self, site: Nikola):
        """Set the site."""
        super(IndexGenerationShortcode, self).set_site(site)
        site.register_shortcode("generate_index", self.generate_index)
```

Nikola expects `handler`? I'm getting attribute error. Nikola wants `handler` but I wrote `register_shortcode("generate_index", self.generate_index)`, not `register_shortcode("generate_index", self.handler)`.

**Comment by Kwpolska** [comment]
Nikola automatically registers handler. Rename the method and delete your
set_site.

-- 
Chris Warrick <https://chriswarrick.com/>
