### ISSUE TITLE
Invalid "ERROR: Nikola: Two posts are trying to generate..." error

### ISSUE THREAD

**Issue by Xeverous** [getnikola/nikola#3287]
### Environment

**Python Version:** 3.7.3

**Nikola Version:** 8.0.2

**Operating System:** GNU/Linux 4.15.0-20-generic

### Description:

I have two posts in the root directory: `home.md` and `index.md`.

`home.md` has:

```
<!--
.. title: home
.. slug: index
.. date: 2019-08-05 22:09:52 UTC+02:00
.. tags:
.. category:
.. link:
.. description:
.. type: text
.. author: Xeverous
.. pretty_url: False
-->
```

`index.md` has:

```
<!--
.. title: index
.. slug: index
.. date: 2019-08-15 16:27:52 UTC+02:00
.. tags:
.. category:
.. link:
.. description: index of all pages on the website
.. type: text
.. author: Xeverous
-->
```

I have pretty urls enabled, but `home.md` explicitly disables them so that it can become the root `index.html` file on my webiste, being just the home page.

So the generated content process should be like this:

```
home.md => /index.html
index.html => /index/index.html
```

Nikola reports that there is some name conflict, while there should be none

```
[2019-08-15T22:48:54Z] ERROR: auto: [2019-08-15T22:48:54Z] WARNING: Nikola: Shortcode name conflict: generate_index
Scanning posts.[2019-08-15T22:48:54Z] ERROR: Nikola: Two posts are trying to generate index.html: pages/home.md and pages/index.md
[2019-08-15T22:48:54Z] ERROR: Nikola: Two posts are trying to generate index.md: pages/home.md and pages/index.md
done!
```

I have checked using different slugs and the output paths are correct. Only this case (`index.html` vs `index/index.html`) is trigerring an error, probably due some name clash in temporary files generated during the build.

**Comment by Kwpolska** [comment]
The index slug is special-cased and pretty URLs are always disabled for it.
You could work around this behavior by putting the file in
pages/index/index.md.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by Xeverous** [comment]
Works, thanks.

I haven't seen anywhere that `index` slug is special-treated and has always disabled pretty urls. If there is no documentation for it, it could be worthwhile to add such information.

**Comment by ralsina** [comment]
Agreed, added to docs.
