### ISSUE TITLE
Create the output directory if it does not exist

### ISSUE THREAD

**Issue by Xeverous** [getnikola/nikola#3288]
Cloned my website to new repository.

Attempted to build and got: `ValueError: No directory exists at '[...]/website/output'`. I think that Nikola should just create it if no such directory exists in the repository.

**Comment by Kwpolska** [comment]
Cannot reproduce with the demo site.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by Xeverous** [comment]
Ok, nevermind. I got this error simultaneously with another error (paths conflict from same-name pages), which caused the build to fail.

I can not reproduce it with my site and the demo site either.

**Comment by Kwpolska** [comment]
In the future, before reporting issues, please try to reproduce them with
the demo site, or with demo site + minimal required changes documented in
the issue.

-- 
Chris Warrick <https://chriswarrick.com/>
