### ISSUE TITLE
Dead link in the documentation of Extending Nikola - Singal Handlers

### ISSUE THREAD

**Issue by Xeverous** [getnikola/nikola#3290]
I searched for a more thorough specification of https://getnikola.com/extending.html#signalhandler-plugins  - I'm interested in exactly what argument each takes and what is the order of plugin invokations.

The linked section has a link titled "One example is the deploy_hooks plugin." but the result is 404.

**Comment by Kwpolska** [comment]
I noticed that and fixed it while I was fixing #3286, but I didn’t publish the changes to the site (this is usually done on release). (It should point to the `v7` directory now.)
