### ISSUE TITLE
extra_footer block in base.tmpl

### ISSUE THREAD

**Issue by tdimitrov** [getnikola/nikola#3291]
I'm building few custom pages for a Nikola powered site and I stumbled upon a minor issue. I wanted to override the footer of just one of the pages. As it is a single page CONTENT_FOOTER doesn't help, as it will update the content of all pages/posts.

My second idea was to add a small template override, similar to this one, but for the footer:

```
<%block name="extra_head">
    ${parent.extra_head()}
    <link rel="stylesheet" href="assets/bootstrap-social.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</%block>
```

I noticed that no such block exists in base.tmpl:

```
<div class="container" id="content" role="main">
    <div class="body-content">
        <!--Body content-->
        ${template_hooks['page_header']()}
        <%block name="content"></%block>
        <!--End of body content-->

        <footer id="footer">
            ${content_footer}
            ${template_hooks['page_footer']()}
        </footer>
    </div>
</div>
```

Do you think it's a good idea to add extra_footer block, which one can easily override for their needs?

Please check my PR, it's done for bootstrap4 theme.

**Comment by tdimitrov** [comment]
Link to the PR: https://github.com/getnikola/nikola/pull/3292

**Comment by Kwpolska** [comment]
#3292 was merged.
