### ISSUE TITLE
Headings are one level higher than in markdown source

### ISSUE THREAD

**Issue by Neurrone** [getnikola/nikola#3298]
# Environment

**Python Version:**

3.7.4

**Nikola Version:**

8.0.2

**Operating System:**

Windows 10 1903

### Description:

A heading such as "## introduction" is rendered as a level 3 heading, instead of a level 2 heading as I'd expect. 

Heading levels seem to be automatically increased by 1. I'd like this to either be fixed, or there to be some way of disabling this behaviour so that I can use the same source md file to generate standalone HTML source.

**Comment by Kwpolska** [comment]
Expected behavior; although it’s not in the manual, it can be found about in `conf.py`, the setting is `DEMOTE_HEADERS` and you can set it to 0 to achieve the effect you want.
