### ISSUE TITLE
Offer a way of disabling links to source files

### ISSUE THREAD

**Issue by Neurrone** [getnikola/nikola#3302]
I'm using the default theme. Posts have a link to the markdown source, which is always copied to the output directory. I couldn't find any way of disabling this behaviour.

**Comment by Kwpolska** [comment]
`SHOW_SOURCELINK = False`

https://github.com/getnikola/nikola/blob/master/nikola/conf.py.in#L1027-L1031

**Comment by Neurrone** [comment]
Really sorry I didn't find this in the conf file.

I suggest documenting this somewhere in the handbook if possible.
