### ISSUE TITLE
Update nikola Simplified Chinese

### ISSUE THREAD

**Issue by dingpengyu** [getnikola/nikola#3303]
### Environment

**Python Version:**
python3.7.4
**Nikola Version:**
nikola8.0.2
**Operating System:**
windows10-1903
### Description:

* zh_CN,Update the following entries:
LANGUAGE 翻译 - 中文（中国）: 语言, ID: 2
LANGUAGE Translation - Chinese (China): Language, ID: 2
Source 翻译 - 中文（中国）: 资源, ID: 12
Source Translation - Chinese (China): Resources, ID: 12
Read in English 翻译 - 中文（中国）: 阅读英文, ID: 13
Read in English Translation - Chinese (China): Read English, ID: 13
thanks

**Comment by Kwpolska** [comment]
The requested changes are not correct (see #3304):

* LANGUAGE should be translated as "Simplified Chinese", not "Language"
* Read in English should be translated as "Read in Simplified Chinese"
* 资源 means resource, not source code
* The last two are apparently "Lose your article here"
