### ISSUE TITLE
Table "border" attribute is hardcoded to 1 in RST output

### ISSUE THREAD

**Issue by serpent213** [getnikola/nikola#3305]
### Environment

**Python Version:**
3.74

**Nikola Version:**
8.0.2

**Operating System:**
MacOS 10.14.6

### Description:

The docutils HTML writer adds a ```border="1"``` attribute to the table element. That conflicts with any further CSS styling, for example the bootblog4 BootStrap design cannot be made to look right.

Docutils source:

https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docutils/writers/html4css1/__init__.py#l760

**Comment by Kwpolska** [comment]
We are using the `html5_polyglot` writer. The latest version from `master` doesn’t seem to have that `border=1` attribute. Can you double-check that it doesn’t happen on `master`?

**Comment by serpent213** [comment]
True, works fine on `master`!

Thank you!
