### ISSUE TITLE
Immediate crash on nikola auto

### ISSUE THREAD

**Issue by fgpietersz** [getnikola/nikola#3306]
Using Python 3.6.5, Nikola 8.0.2 on openSUSE Leap 15.1

Running `nikola auto` results in this:

```
Traceback (most recent call last):
  File "[path/to/virtualenv]/lib/python3.6/site-packages/doit/doit_cmd.py", line 177, in run
    return command.parse_execute(args)
  File "[path/to/virtualenv]/lib/python3.6/site-packages/doit/cmd_base.py", line 127, in parse_execute
    return self.execute(params, args)
  File "[path/to/virtualenv]/lib/python3.6/site-packages/nikola/plugin_categories.py", line 148, in execute
    return self._execute(options, args)
  File "[path/to/virtualenv]/lib/python3.6/site-packages/nikola/plugins/command/auto/__init__.py", line 118, in _execute
    self.rebuild_queue = asyncio.Queue()
  File "/usr/lib64/python3.6/asyncio/queues.py", line 42, in __init__
    self._loop = events.get_event_loop()
  File "/usr/lib64/python3.6/asyncio/events.py", line 694, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/lib64/python3.6/asyncio/events.py", line 602, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Dummy-1'.
```

**Comment by Kwpolska** [comment]
The thread name `Dummy-1` is unusual. I can’t reproduce on macOS Mojave and on Fedora 30, both running Python 3.7.  Are you sure there are no special threading arguments in use?

**Comment by fgpietersz** [comment]
No, nothing special on the command line. I have this with two sites, one of which I originally set up on Unubtu 18.04 and there is nothing changed in the conf file. The other is new. Both sites use the same virtualenv (obviously that was recreated because you cannot copy virtualenvs)

**Comment by fgpietersz** [comment]
That got me thinking, the only common factor was the virtualenv, so I deleted and recreated it and that fixed it.

I must have messed up somewhere. I do not know when or how, but its fixed. Before anyone asks, I did not copy it from the old machine running Ubuntu!

**Comment by Kwpolska** [comment]
Virtual environments are never meant to be copied between machines, not
even running the same OS, since they have very deep dependencies to the
system configuration. Your virtualenvs should be ephemeral so that you can
delete them at any time, without preparation.
-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by ralsina** [comment]
Or, if you just want things to run isolated and not bother
creating/deleting them, use fades!

https://pypi.org/project/fades/

**Comment by fgpietersz** [comment]
> Virtual environments are never meant to be copied between machines.

I think you misread my previous comment. I said that I did **not** copy the virtualenv. I excluded the virtualenvs directory when I copied my home directory over so I am sure about that.

I must have messed up the virtualenv some other way.

**Comment by fgpietersz** [comment]
The problem has come back. This time recreating the virtualenv did not help.

**Comment by Kwpolska** [comment]
Please try to run the following two programs using the same Python you use for Nikola and tell us the results.

```py
#!/usr/bin/env python3
import asyncio
rebuild_queue = asyncio.Queue()
print("OK Queue")
```

---

```py
#!/usr/bin/env python3
import asyncio

async def test():
    await asyncio.sleep(0.2)
    print("OK Run")

loop = asyncio.get_event_loop()
loop.run_until_complete(test())
```

**Comment by fgpietersz** [comment]
Both print the OK message.

**Comment by Kwpolska** [comment]
I cannot reproduce your issue using openSUSE 15.1 Leap (JeOS image).

```console
$ sudo zypper install python3-{pip,dbm,virtualenv}
$ python3 -m venv nvenv
$ cd nvenv
$ source bin/activate
$ pip install nikola watchdog aiohttp
$ nikola init -qd n
$ cd n
$ nikola auto
# no errors, curl works, editing a file in another tty rebuilds the site as expected
^C
$ deactivate
$ cd ../..
$ python3 -m virtualenv nvirtual
$ cd nvirtual
$ source bin/activate
$ pip install nikola watchdog aiohttp
$ nikola init -qd n
$ cd n
$ nikola auto
# no errors, curl works, editing a file in another tty rebuilds the site as expected

**Comment by fgpietersz** [comment]
I have investigated further, and found what makes the difference.

The original virtualenv had --system-site-packages (its what I usually do).

One without that works fine so I have a solution.

I do not know whether this is not a bug because it will not occur if the install instructions are followed exactly, or a bug because it may be due to a problem in the dependencies specified or similar.

**Comment by Kwpolska** [comment]
`--system-site-packages` is often buggy, and many people recommend against using that. You may want to report an issue to the virtualenv developers.
