### ISSUE TITLE
Travis CI: Invariant builds fail

### ISSUE THREAD

**Issue by okin** [getnikola/nikola#3310]
### Environment

Travis CI!

**Python Version:** 3.8

**Nikola Version:** master

**Operating System:** Ubuntu Xenial

### Description:

Builds in Travis CI fail because of diffs in the image files compared to what is in the zip for the Python 3.8 invariant builds.

[direct link to failed build](https://travis-ci.org/getnikola/nikola/jobs/600052580)

**Comment by Kwpolska** [comment]
Fixed.

**Comment by okin** [comment]
Thank you :)
