### ISSUE TITLE
reST file inclusion is a security hole

### ISSUE THREAD

**Issue by gwax** [getnikola/nikola#3311]
### Environment

**Python Version:** 3.7.3

**Nikola Version:** 8.0.2

**Operating System:** Any

### Description:

A number of reST directives allow for the inclusion of files in rendered output, namely [include](http://docutils.sourceforge.net/docs/ref/rst/directives.html#including-an-external-document-fragment), [raw](http://docutils.sourceforge.net/docs/ref/rst/directives.html#raw-data-pass-through), and [CSV Table](http://docutils.sourceforge.net/docs/ref/rst/directives.html#id4), which can potentially expose secret file contents.

Consider a site manage with CI for build and deploy:
* The site is managed by Person A who has permission to do whatever
* Deployment keys are kept in a repo root file named `secrets.json`
* The `master` branch is always built and deployed to `www.example.com`
* Any other branch is built and deployed to `${branchname}.ci-test.example.com`
* Person B is an author for the site with commit privileges but no permission to see the CI deploy keys
* Person B creates a post with the contents:

  ```rest
  Testing a leak
  ==============

  :slug: testing-a-leak
  :date: 2019-10-29 06:55:31+00:00
  :type: text

  Write your post here.

  .. include:: secrets.json
  ```

  and adds it to their branch `i-can-haz-yur-creds`
* Person B pushes their branch
* Person B goes to `i-can-haz-yur-creds.ci-test.example.com/blog/2019/10/29/testing-a-leak.html` and can see the credentials clear as day.

The solution according to docutils is to set [file_insertion_enabled](http://docutils.sourceforge.net/docs/user/config.html#file-insertion-enabled) to false (default is true).

**Comment by gwax** [comment]
More concretely, I am looking to use something like staticman to handle comments but don't want anyone extracting secrets by cleverly constructing a comment.

**Comment by felixfontein** [comment]
This clearly needs a possibility to configure this. I'm relying on this functionality for one of my blogs (allows to include some common ReST definitions everywhere), but in general this is a dangerous feature.

**Comment by Kwpolska** [comment]
There are also some other places where someone with access could potentially exfiltrate data, for example with `.. template:` or `.. listning::`. Making it possible to work around it would be a good idea.

But to implement comments, you should (a) not allow strangers to just build your site, because that way you will end up with spam, `<script>` and other nefarious stuff, (b) create a minimalistic compiler for your comments, that understands only basic syntax like `**bold**`, newlines, and URLs, that always filters out `<` and `>` as `&lt;` and `&gt;` and that does not interpret shortcodes, so that users can’t type bad stuff in comments.

**Comment by ralsina** [comment]
Nikola is not meant for processing 3rd party content.

Patches welcome to harden the obvious bits, but defaults can't change, and
I expect it's probably not possible to make it meaningfully secure in that
sense.

**Comment by gwax** [comment]
Whether or not Nikola is _meant_ for processing 3rd party content, it's really easy to run afoul of this if you were to combine [Staticman as suggested](https://getnikola.com/blog/really-static-comments-with-staticman.html) and the [static_comments plugin](https://plugins.getnikola.com/v8/static_comments/) with any CI/CD system.

The SPAM risk is smaller as most reasonable setups would route the comments through a PR and never hit public release but there is still a risk of leaks from test environments.

The default is unsafe and, while I understand keeping it as is for compatibility, I would encourage breaking compatibility where security risks are concerned. That can be a future discussion as long as an option exists.

**Comment by felixfontein** [comment]
There's another problem with the setup you describe in the issue: the configuration is executable, so if someone can create branches and these are automatically built, they can add code to the configuration which sends interesting files via email (can be prevented with networking lockdown) or copies them into the `posts` folder. And even if the config would contain no executable code, you can add/change plugins and themes embedded into the project. These are all executable code in the end. So ReST file inclusion is only a small part of the general problem :) (Though a very big part for static comments.)

**Comment by gwax** [comment]
Yes, there are a lot of potential holes. My intent had been to write my own static file processing code that would use my github user to post new PRs. Increasingly, that feels dangerous (PRs from the main repo have secret access in Travis). At this point, I expect that I'll want to use a robot account to fashion the PRs, which will should mitigate the remaining risks.

I don't know enough about the behavior of Staticman (or other systems) so I suspect locking down reST inclusion is still a useful feature.
