### ISSUE TITLE
Future posts in pages and post listings

### ISSUE THREAD

**Issue by spollard** [getnikola/nikola#3313]
I'm using Nikola to generate a website that keeps track of events. I want a page to be able to make a schedule of future events. It seems like allowing the Post List directive to have access to future posts would be the best way to implement this. One problem with this is that the Post List does not have access to the future posts, which would be necessary. 

Calling the future events drafts does not seem like a good method.

**Comment by spollard** [comment]
For now, I've simply added an 'all_posts' key to the global context that is a list of all posts. Then I can manipulate them in the template. 

https://github.com/spollard/nikola/commit/a97db5155a34df3f923b71f143773f3fc07f865c

This is not a great solution, but it does work. I was not able to alter the Post List directive such that it had access to future posts. Perhaps someone who is more familiar with the Post List directive could help out?

**Comment by Kwpolska** [comment]
Perhaps it would be okay for your site to set FUTURE_IS_NOW? If not, you
could modify the references in post-list from site.timeline to
site.all_posts. Although this probably won't happen in Nikola core.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by spollard** [comment]
FUTURE_IS_NOW=True doesn't work for my use because I don't want future events to show up on the main index page. 

Yeah, it's a niche (mis)use of Nikola that doesn't make sense to incorporate into the core unless a bunch of other people want it.  Feel free to close if there's little interest.

**Comment by Kwpolska** [comment]
Having it possible for future posts to be both visible and not does not sound like a good idea to support in the general case.  You can have a custom copy of the `post-list` plugin that refers to `all_posts` instead of `timeline` to get the behavior you want.
