### ISSUE TITLE
Unable to resolve file:// links

### ISSUE THREAD

**Issue by bashtage** [getnikola/nikola#3315]
### Environment

**Python Version:**
3.7.4
**Nikola Version:**
8.0.3
**Operating System:**
Windows or Linux

### Description:

After upgrading to 8.0.3 I am seeing warnings in my log like:

[2019-11-05T15:45:54Z] WARNING: Nikola: Cannot resolve path request for filename: pages/teaching/python/course.md
[2019-11-05T15:45:56Z] WARNING: Nikola: Cannot resolve path request for filename: pages/specimen.md
[2019-11-05T15:45:56Z] WARNING: Nikola: Cannot resolve path request for filename: pages/notebook-specimen.ipynb

In the file I have links like

```markdown

[Specimen](link://filename/pages/specimen.md)

[Notebook Specimen](link://filename/pages/notebook-specimen.ipynb)

```

I suspect this is a bug introduced by moving to Markdown 3.

**Comment by Kwpolska** [comment]
Cannot reproduce with your site (https://github.com/bashtage/kevinsheppard.com), Markdown==3.1.1, the links work correctly:

```html
<h3 id="website-related-content">Website-related content<a class="headerlink" href="#website-related-content" title="Permanent link">¶</a>
</h3>
<p><a href="../../specimen">Specimen</a></p>
<p><a href="../../notebook-specimen">Notebook Specimen</a></p>
```

Please check if this is still broken.

**Comment by bashtage** [comment]
I ran in a clean venv against master and can't reproduce. Thanks for looking into this.
