### ISSUE TITLE
Some of the themes do not build on a clean site generated with "nikola init"

### ISSUE THREAD

**Issue by laodzu** [getnikola/nikola#3321]
Given the problem building my site based on the zen theme in v8.0.3 ( #3319) I wrote a small shell script to test if the provided themes build out of the box on the small demo site generated with "nikola init -q".  Here are the results:

(nikola) dzu@krikkit:/tmp$ nikola-check-themes
[2019-11-26T09:02:38Z] INFO: init: Created empty site at clean-site.
Building for THEME = "blogtxt"                    ... ok
Building for THEME = "bnw"                        ... ok
Building for THEME = "bootblog"                   ... failed
Building for THEME = "bootblog-jinja"             ... ok
Building for THEME = "bootstrap"                  ... ok
Building for THEME = "bootstrap-jinja"            ... ok
Building for THEME = "bootstrap3"                 ... ok
Building for THEME = "bootstrap3-gradients"       ... ok
Building for THEME = "bootstrap3-gradients-jinja" ... ok
Building for THEME = "bootstrap3-jinja"           ... ok
Building for THEME = "cadair"                     ... ok
Building for THEME = "canterville"                ... ok
Building for THEME = "carpet"                     ... ok
Building for THEME = "detox"                      ... failed
Building for THEME = "foundation6"                ... ok
Building for THEME = "hack"                       ... failed
Building for THEME = "hemingway"                  ... failed
Building for THEME = "hpstr"                      ... ok
Building for THEME = "hybrid"                     ... failed
Building for THEME = "hyde"                       ... ok
Building for THEME = "jidn"                       ... failed
Building for THEME = "lanyon"                     ... failed
Building for THEME = "libretto"                   ... ok
Building for THEME = "lotabout"                   ... ok
Building for THEME = "material-theme"             ... ok
Building for THEME = "maupassant"                 ... ok
Building for THEME = "mdl"                        ... failed
Building for THEME = "monospace"                  ... ok
Building for THEME = "oldfashioned"               ... ok
Building for THEME = "planetoid"                  ... ok
Building for THEME = "readable"                   ... ok
Building for THEME = "reveal"                     ... failed
Building for THEME = "reveal-jinja"               ... ok
Building for THEME = "slidemenu"                  ... ok
Building for THEME = "srcco.de"                   ... ok
Building for THEME = "yesplease"                  ... ok
Building for THEME = "zen"                        ... failed
Building for THEME = "zen-forkawesome"            ... failed
Building for THEME = "zen-jinja"                  ... failed
12 attempts failed - not removing the temporary directory /tmp/nikola-check-theme-9zN

Some of those problems disappear with the code from #3320 but not all - 7 still remain.

Please note that I am not a Nikola developer, so maybe the script does not do a just evaluation, but manual cross-checks showed consistent results.

I'll attach the script to easily recreate the findings.

**Comment by Kwpolska** [comment]
Please (1) show your script (2) show full build logs with the failures (3) apply #3320 before building (4) provide a list of the 7 themes that fail with #3320.

**Comment by laodzu** [comment]
Hi Chris,

you are too fast for me - I'm still struggling to attach the script.  Isn't there an easy way to attach a file to this bug rather than pasting the script into markup?

**Comment by Kwpolska** [comment]
Just paste it here (wrap it in triple \`\`\`backticks\`\`\` on separate lines to make a code block).

**Comment by laodzu** [comment]
#!/bin/bash
    
    FAILS=0
    DIR=`mktemp -d /tmp/nikola-check-theme-XXX`
    cd $DIR
    nikola init -q clean-site
    cd clean-site
    for theme in `nikola theme -l | tail +3`
    do
        printf "Building for THEME = %-28s ... " \"$theme\"
        nikola theme -i $theme > /dev/null 2>&1
        sed -i 's/THEME = ".*"/THEME = "'$theme'"/' conf.py
        rm -rf cache
        if nikola build > build-log-$theme 2>&1
        then
    	echo "ok" >&2
        else
    	echo "failed" >&2
    	FAILS=$(( $FAILS + 1 ))
        fi
    done
    cd
    if [ $FAILS -gt 0 ]
    then
        echo "$FAILS attempts failed - not removing the temporary directory $DIR"
    else
        rm -r $DIR
    fi

**Comment by laodzu** [comment]
Pleas advise if you still want me to post all the build logs before and after applying #3320 - the script yields this as a side effect and maybe keeps the discussion here cleaner.

**Comment by Kwpolska** [comment]
No need for the logs, I can reproduce the failures.

With #3320 applied:

```
Building for THEME = "bootblog"                   ... failed
Building for THEME = "hybrid"                     ... failed
Building for THEME = "mdl"                        ... failed
Building for THEME = "reveal"                     ... failed
Building for THEME = "zen"                        ... failed
Building for THEME = "zen-forkawesome"            ... failed
Building for THEME = "zen-jinja"                  ... failed
```

The build script fails to account for `conf.py.sample`. I amended the code like this:

```bash
FAILS=0
nikola init -q clean-site
cd clean-site
cp conf.py baseconf.py
for theme in bootblog hybrid mdl reveal zen zen-forkawesome zen-jinja 
do
    printf "Building for THEME = %-28s ... " \"$theme\"
    nikola theme -i $theme > /dev/null 2>&1
    sed -i 's/THEME = ".*"/THEME = "'$theme'"/' baseconf.py
    cat baseconf.py themes/$theme/conf.py.sample > conf.py 2>&1
    rm -rf cache
    if nikola build > build-log-$theme 2>&1
    then
	echo "ok" >&2
    else
	echo "failed" >&2
	FAILS=$(( $FAILS + 1 ))
    fi
done
```

and got this as a result:

```
Building for THEME = "bootblog"                   ... ok
Building for THEME = "hybrid"                     ... ok
Building for THEME = "mdl"                        ... ok
Building for THEME = "reveal"                     ... ok
Building for THEME = "zen"                        ... ok
Building for THEME = "zen-forkawesome"            ... ok
Building for THEME = "zen-jinja"                  ... ok
```

**Comment by laodzu** [comment]
Ah, I knew I was missing some important info.  Thanks for showing me.  This is a corrected version taking this into account for all the themes that provide a conf.py.sample:

```bash
#!/bin/bash

FAILS=0
DIR=`mktemp -d /tmp/nikola-check-theme-XXX`
cd $DIR
nikola init -q clean-site
cd clean-site
cp conf.py baseconf.py
for theme in `nikola theme -l | tail +3`
do
    printf "Building for THEME = %-28s ... " \"$theme\"
    nikola theme -i $theme > install-log-$theme 2>&1
    # Some themes need further configuration
    if [ -r themes/$theme/conf.py.sample ]
    then
	cat baseconf.py themes/$theme/conf.py.sample > conf.py
    fi
    sed -i 's/THEME = ".*"/THEME = "'$theme'"/' conf.py
    rm -rf cache
    if nikola build > build-log-$theme 2>&1
    then
	echo "ok" >&2
    else
	echo "failed" >&2
	FAILS=$(( $FAILS + 1 ))
    fi
done
cd
if [ $FAILS -gt 0 ]
then
    echo "$FAILS attempts failed - not removing the temporary directory $DIR"
else
    rm -r $DIR
fi
```

With #3320 this only leaves "hyde" not working.  Excellent!

**Comment by Kwpolska** [comment]
Hyde works for me.  Please paste the build log.

**Comment by laodzu** [comment]
You are right, sorry.  This was due to an intermediate version of the script that did not correctly reset conf.py to baseconf.py. Now I also have all themes working.

**Comment by Kwpolska** [comment]
Great! JFYI, we build themes with the demo site when we update the themes site, but this wasn't done before v8.0.3, so #3319 was not caught.
