### ISSUE TITLE
Commento ServiceURL is incorrect for paid version

### ISSUE THREAD

**Issue by John-Drake** [getnikola/nikola#3324]
### Environment

**Python Version:** 3.7.3

**Nikola Version:** v8.0.3

**Operating System:** Windows 10

### Description:
For users who are paying for commento's service (e.g. using their own server instead of hosting it yourself), the concatenated URL appears to be incorrect.

For instance, if I set COMMENT_SYSTEM_ID = "https://cdn.commento.io" in the conf.py file, it will create HTML files with src="https://cdn.commento.io/js/commento.min.js".

The above won't properly load.

But if I edit the HTML file and remove the ".min" from the right... it will load. 

According to commento's installation guide, the proper script is:
<div id="commento"></div>
<script src="https://cdn.commento.io/js/commento.js"></script>

**Comment by John-Drake** [comment]
I noticed in #3198 that the same issue was reported (Back in February).  It seems like there was a commit (#733cd82), but I'm new to github and not sure if that ever was merged into the master branch or somehow reverted at a later date.

**Comment by Kwpolska** [comment]
The path was changed in `base-jinja` but not in `base`, and the `base-jinja` change was overwritten anyway.  I fixed this in commit 9f8e61567.
