### ISSUE TITLE
Make commento look decent for post's header

### ISSUE THREAD

**Issue by John-Drake** [getnikola/nikola#3325]
At the top of all posts, there is a header with [Title] --- [Date] --- [Comments] --- [Source]. For disquis, this looks quite decent as comments_helper_disqus.tmp creates a hyperlink below. 

'''
<%def name="comment_link(link, identifier)">
    %if comment_system_id:
    <a href="${link}#disqus_thread" data-disqus-identifier="${identifier}">${messages("Comments")}</a>
    %endif
</%def>
'''

But for comments_helper_commento.tmpl, nothing is created. This means the header looks like [Title] --- [Date] --- --- [Source] with two slashes between [Date] and [Source].

Either the hyperlink should be fixed or one of those slashes should be removed.

**Comment by Kwpolska** [comment]
Added a link, thanks for reporting.
