### ISSUE TITLE
Add support for default previewimage

### ISSUE THREAD

**Issue by rixx** [getnikola/nikola#3326]
The previewimage meta tag is used for Open Graph metadata, among other things. However, not all pages and blog posts will have their own image. It would be cool to be able to provide a generic **default image via the config**, without having to add it manually to all pages that don't feature one already.

(New pages and posts can be generated with the matching previewimage line, of course, but retrofitting all old files is a pain.)

**Comment by richieadler** [comment]
I concur with this need and I add that it would be desirable to have a default previewimage _per section_, if the site has sections. For instance a section can be a periodic column by some author and a photo of the author could be the default preview image.

**Comment by Kwpolska** [comment]
PRs for either or both the features are welcome. This could be generalized to per-category/site-wide default post metadata.

**Comment by ralsina** [comment]
Basic support for a single default image done in a PR.

![image](https://user-images.githubusercontent.com/1579/78455845-eb0df380-7676-11ea-83a9-3e28a834951a.png)
