### ISSUE TITLE
Produce a numbered toc

### ISSUE THREAD

**Issue by alinbxSorcerer** [getnikola/nikola#3328]
`.. contents::` could produce a toc but not numbered. 

try  the below directive in file header  

```
.. toctree::
   :numbered:
   :maxdepth: 2
```

but report error:

        Unknown directive type "toctree".

**Comment by Kwpolska** [comment]
The `toctree` directive is Sphinx-specific and does something different.  reST has automatic section numbering like this: https://docutils.sourceforge.io/docs/ref/rst/directives.html#automatic-section-numbering
