### ISSUE TITLE
Error in published date

### ISSUE THREAD

**Issue by cosmoscalibur** [getnikola/nikola#3337]
### Environment

**Python Version:**
3.6.8
**Nikola Version:**
8.0.3
**Operating System:**
Linux Mint 19.3
### Description:
Using in metadata `.. date: 2019-12-31 14:43:50-05:00`, the published date generated in HTML is 2020-12-31 14:43. Extracted from HTML: `<time class="published dt-published" datetime="2019-12-31T14:43:50-05:00" itemprop="datePublished" title="2020-12-31 14:43">2020-12-31 14:43</time>`.  

Example page with that error: https://www.cosmoscalibur.com/blog/usar-anaconda-python-en-git-bash/

**Comment by Kwpolska** [comment]
Explanation: https://www.youtube.com/watch?v=D3jxx8Yyw1c

It’s a one-liner fix (`YYYY` → `yyyy` in `DATE_FORMAT`).

**Comment by cosmoscalibur** [comment]
But this should be a default setup in DATE_FORMAT. In what case, do you need published date in YYYY-MM-dd format?

**Comment by felixfontein** [comment]
@cosmoscalibur the default will change to `yyyy-MM-dd` for the next released version, @Kwpolska changed it in f8b809e93645c9075660d741f55ce8f91da4abda. For now (until the next version is released), you either have to patch your installed version of Nikola, use the version from master branch, or adjust your site's config. I guess the old default has been wrong, but nobody ever noticed it (or reported it) until you did.
