### ISSUE TITLE
Nikola exposes posts in sitemap that are in the future

### ISSUE THREAD

**Issue by kayhayen** [getnikola/nikola#3339]
### Environment

**Python Version:**

3.7

**Nikola Version:**

Latest PyPI

**Operating System:**

Linux

### Description:

The Google search console just alerted me of 404 errors. There is a release announcement post, that I schedule a day in the future, when I generate the pages, so I got time to get the packaging sorted out until then. I think, in the past, the page became a draft and was uploaded. I might have remove the draft tag myself, assuming the date works the same.

http://nuitka.net/sitemap.xml
http://nuitka.net/sitemapindex.xml

However, it surely is a bug to expose the URL of a non-existing post. I have seen issues in the past that this has happened with pretty URLs and with actual drafts. Maybe the future date is different?

You can see my environment here: https://github.com/Nuitka/Nuitka-website but I strongly doubt that it's relevant. Also the issue of future post will be gone within the hour. I just wanted to mention this issue to you, I don't see much severity personally, as the URL contains no secrets.

Yours,
Kay

Yours,
Kay

**Comment by Kwpolska** [comment]
Sorry this took a month to look into. This was a very small oversight in an alternate code path that doesn’t get triggered with `PRETTY_URLS = True` (and our tests only did that one). I fixed that on master, and also added a test for this case.
