### ISSUE TITLE
Default installation does not load custom.css

### ISSUE THREAD

**Issue by euphi** [getnikola/nikola#3340]
I followed https://getnikola.com/handbook.html#customizing-your-site and created a custom.css in `files/assets/css`.

However, it is not loaded into default configuration (with no theme set or theme set to bootstrap4).

To be suree, I also check site info "sources" in chrome - other than stated in the handbook, the custom.css is not loaded.

**Comment by Kwpolska** [comment]
Cannot reproduce.

```
nikola init -qd n
cd n
mkdir -p files/assets/css
echo 'body { background: lightgreen !important; }' > files/assets/css/custom.css
nikola build
```

And when I open the page, the background *is* green.  Note that if you do *view source*, you won’t see the file, because we include it as part of our bundles (`all.css`, `all-nocdn.css`).

**Comment by euphi** [comment]
Ok.. It was not complete "default installation". I already added a line

```python
FILES_FOLDERS = {'files':'files'}
```

to my conf.py. Without these line, the custom.css is loaded into `all-nocdn.css`.

So, where do I need to place the custom.css in this case?

I changed FILES_FOLDER because I wanted to use it for extra downloadable files (pdf to print etc.). Is there another good way to seperate files like these in an extra directory?

**Comment by Kwpolska** [comment]
You need to make sure the file is *output* to `output/assets/css/custom.css`. This can be done by using a custom theme, or by placing it in a FILES_FOLDERS directory that outputs to ''. We recommend using the default FILES_FOLDERS setup. You can put your extra files in `files/files`, but you retain the ability to add custom files anywhere in the structure (and you might want to do that for stuff like `favicon.ico` or a custom `robots.txt`, for example). Or you can use a setup with multiple directories, like `{'root': '', 'files': 'files'}` or similar.

**Comment by nandoflorestan** [comment]
If anyone else finds this ticket and still needs help:

It might be your browser cache while you are developing your blog.  Hit F12 to go to developer tools, then go to Network and check "Disable cache".  Alternatively, empty the browser cache in its settings.

Look at the source code of your blog on the browser.  The default theme uses a single CSS file.  If you open output/assets/css/all-nocdn.css, scroll all the way down and see your custom CSS code there, then Nikola is doing its part, and you have a browser cache issue.
