### ISSUE TITLE
tests are being shipped as a module

### ISSUE THREAD

**Issue by dvzrv** [getnikola/nikola#3348]
### Environment

**Python Version:** 3.8.1

**Nikola Version:** 8.0.4

**Operating System:** Arch Linux

### Description:

During packaging of 8.0.4 I realized, that nikola somehow now ships its tests as a top-level module (e.g. `/usr/lib/python3.8/site-packages/tests`).

This already breaks the build during tests, as after

```
python setup.py build
```

the tests directory is also placed below `build/lib/` and the usual

```
pytest -v
```

fails on relative imports (because it picks up the tests from the `build` directory as well).

Currently I'm manually removing the `tests` directory, so there are no file conflicts with other packages (that also accidentally ship their tests as top-level modules).

It would be awesome, if the tests (as a module) could be removed again.

**Comment by dvzrv** [comment]
@Kwpolska ouf, so fast! :)
Thanks!

**Comment by Kwpolska** [comment]
Sorry for that, `find_packages` in setuptools is a bit picky, and we reorganized our tests package to have a subpackage. We asked for it to skip `tests`, and it did skip `tests/__init__.py`, but also decided it’s okay to install `tests/integration/__init__.py`.  Feel free to apply the one-line patch or delete `tests` from `site-packages` in the PKGBUILD.

```diff
-      packages=find_packages(exclude=('tests',)),
+      packages=find_packages(exclude=('tests', 'tests.*')),
```
