### ISSUE TITLE
Changes to EXIF_WHITELIST does not trigger gallery rebuild

### ISSUE THREAD

**Issue by o1knives** [getnikola/nikola#3357]
### Environment

**Python Version:**
3.8.1

**Nikola Version:**
8.0.4

**Operating System:**
Windows 10

### Description:
Changes to the `conf.py` variable `EXIF_WHITELIST` trigger a rebuild of all images in the `images` folder.  It does not, however, cause any rebuild of images in the `gallery` folder.  In order to change the EXIF data for galleries you must perform a full site rebuild.

**Comment by ralsina** [comment]
It seems to trigger a rebuild of the HTML files and RSS feeds of galleries but not of the images themselves.

![image](https://user-images.githubusercontent.com/1579/78379748-3a85ee00-75a9-11ea-8aae-aa76c6790933.png)
