### ISSUE TITLE
Ascii Error when building Nikola on 10.7.5

### ISSUE THREAD

**Issue by Djultypremierdunom** [getnikola/nikola#3379]
High, I'm new to the terminal language, therefor I'm totally lost since I've pushed a little too far my journey into it.

Here's the thing. I'm on mac 10.7.5, working on a site under Nikola, and trying to install Jekyll (... don't judge my naivety please), so I install and uninstall, upgrade and update a bunch of things I don't equally remember. Trying to install Python3, install GCC, updating a few bundles there, throwing away some TigerBrew or Macports here, sudopassing some troubles on brew doctor... In short, a happy mess in which I slowly drown, till :

julien:nikola julien$ nikola build Traceback (most recent call last): File "/usr/local/bin/nikola", line 11, in sys.exit(main()) File "/usr/local/lib/python2.7/site-packages/nikola/main.py", line 136, in main LOGGER.error('"{0}" cannot be parsed.\n{1}'.format(conf_filename, msg)) UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 72: ordinal not in range(128)

Can you help me please ? Thanks a lotlotlot

**Comment by Kwpolska** [comment]
Python 2 is not supported. Mac OS X 10.7 from 2011 might be difficult to get working with modern versions of Python or other software.

1. Remove your Python 2 copy of Nikola (with pip?)
2. Install Python 3.5 or newer [(MacPorts seems to have a 10.7 port for python3.8)](https://ports.macports.org/port/python38/summary).
3. Using that copy of Python 3, create a virtual environment and install Nikola in it (see [Getting started](https://getnikola.com/getting-started.html)).
4. If you still see Unicode errors, make sure `locale` shows UTF-8 locales, and change your shell configuration files if it does not.

**Comment by sukiletxe** [comment]
You need to use Python3 instead of the builtin Python. You may find these two guides by @Kwpolska useful:
[1]: <https://chriswarrick.com/blog/2017/07/03/setting-up-a-python-development-environment/>
[2]: <https://chriswarrick.com/blog/2017/06/18/unix-locales-vs-unicode/>

**Comment by ralsina** [comment]
I think the above answers cover everything, closing.
