### ISSUE TITLE
Beautifulsoup import error

### ISSUE THREAD

**Issue by SaiAle501** [getnikola/nikola#3396]
ImportError: cannot import name 'Beautifulsoup' from 'bs4' (C:\Users\saiki\AppData\Local\Programs\Python\Python37\lib\site-packages\bs4\__init__.py)

**Comment by Kwpolska** [comment]
Neither Nikola nor any standard Nikola dependencies use BeautifulSoup 4. What plugins are you using? Show full traceback.

**Comment by SaiAle501** [comment]
I did not get that can you please elaborate ?

**Comment by Kwpolska** [comment]
1. What extra plugins are you using?
2. Run Nikola with `NIKOLA_SHOW_TRACEBACKS=1 nikola build` and paste the full traceback here.

**Comment by ralsina** [comment]
Wherever that error is coming from, the problem is the lowercase s in "soup" should be uppercase.

**Comment by Kwpolska** [comment]
Closing due to no response.
