### ISSUE TITLE
Add a Github Action

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#3397]
Basically:

If we add a action.yml it's possible to publish a  "publish to github pages" action, and then users can just edit in GH, push a button and publish the site.

**Comment by Kwpolska** [comment]
Do you want to do it or can I take it? I have some [experience](https://github.com/Kwpolska/ansible-nginx-uwsgi/blob/master/.github/workflows/main.yml) with [evil Actions hackery](https://github.com/Kwpolska/ansible-nginx-uwsgi/tree/master/ci), so I could probably build something (more reasonable of course) for Nikola.

**Comment by ralsina** [comment]
I already started but I am doing a very basic one :-)

**Comment by ralsina** [comment]
Oh, well, didn't work and I have no idea why.

Feel free to take over the nikola-action repo :-)

**Comment by Kwpolska** [comment]
Done. Tutorial (based off the Travis CI tutorial): https://getnikola.com/blog/automating-nikola-rebuilds-with-github-actions.html
