### ISSUE TITLE
Markdown Parsing Error

### ISSUE THREAD

**Issue by pepoluan** [getnikola/nikola#3398]
### Environment

**Python Version:** 
```console
% python -V
Python 3.6.9 (7.3.1+dfsg-4~ppa1~ubuntu18.04, Apr 23 2020, 03:04:13)
[PyPy 7.3.1 with GCC 7.5.0]
```

**Nikola Version:**
```console
% nikola -V
Nikola v8.0.4
```

**Operating System:**
```console
% uname -a
Linux LAPTOP-PPO 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
% lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

### Description:

The following Markdown code:

```markdown
> Don't be so focused on **a procedure** (in this case, `pypy3 -m venv ...`) that you totally overlook
a different way to **achieve your goal*** (`sudo apt install virtual env` + `virtualenv -p ...`)
```

Gets rendered like this:

![image](https://user-images.githubusercontent.com/642259/80283647-65e0a080-8743-11ea-9ee0-bf70e13f2f11.png)

(Screenshoted from `nikola serve` on my laptop, but also what appeared on [my GitLab Pages](https://pepoluan.gitlab.io/posts/20200425/creating-pypy-virtualenvs-on-ubuntu/).)

While it should be rendered like this:

> Don't be so focused on **a procedure** (in this case, `pypy3 -m venv ...`) that you totally overlook
a different way to **achieve your goal*** (`sudo apt install virtual env` + `virtualenv -p ...`)

(The &lt;strong&gt; bled through instead of stopping at the second pair-of-asterisks; or rather, the second pair-of-asterisks triggered &lt;em&gt; instead of &lt;/strong&gt;)

**Comment by ralsina** [comment]
You have 3 * at the end of "achieve your goal" and should have 2.

**Comment by Kwpolska** [comment]
Also, this behavior is in `python-markdown`, not Nikola:

```
$ python -m markdown
> Don't be so focused on **a procedure** (in this case, `pypy3 -m venv ...`) that you totally overlook
a different way to **achieve your goal*** (`sudo apt install virtual env` + `virtualenv -p ...`)
<blockquote>
<p>Don't be so focused on <strong>a procedure*<em> (in this case, <code>pypy3 -m venv ...</code>) that you totally overlook
a different way to **achieve your goal</em></strong> (<code>sudo apt install virtual env</code> + <code>virtualenv -p ...</code>)</p>
</blockquote>
```

If you intend to have an asterisk after “achieve your goal”, escape it with a backslash. If you think `python-markdown` should behave differently, please report this bug to them.

**Comment by pepoluan** [comment]
Yeah, it was a wayward asterisk. My bad. I really should have double-checked the whole paragraph.

Sorry for the false error report.
