### ISSUE TITLE
Old site on new virtualenv, conf.py cannot be parsed

### ISSUE THREAD

**Issue by Djultypremierdunom** [getnikola/nikola#3402]
Hi,

I'm on mac 10.7.5, with python3 working in a virtual environment. 
I work on a website that has been build with an old version of Nikola. 
But since I have upgraded the whole bunch of things that blocked me (libxml, pyzmq, wheel, pillow...), The site could not build anymore and terminal returns me this :

```
(nikola_env) julien:nikola annebitran$ nikola build
[2020-04-29T16:01:31Z] ERROR: Nikola: "conf.py" cannot be parsed.
Traceback (most recent call last):
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/nikola/__main__.py", line 125, in main
    spec.loader.exec_module(conf)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "conf.py", line 133
    "Les Rémouleurs" : {
                     ^
SyntaxError: invalid syntax

The DEBUG returns me this :

--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/nikola/log.py", line 64, in format
    message = super().format(record)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Users/annebitran/nikola_env/bin/nikola", line 8, in <module>
    sys.exit(main())
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/nikola/__main__.py", line 114, in main
    LOGGER.debug("Website root: {0!r}", root)
Message: 'Website root: {0!r}'
```

Any help ? Thanks a lot !

**Comment by Kwpolska** [comment]
This is unlikely to be a Nikola bug (the debug thing is, but it’s something else). Can you run `python conf.py`?  If that gives you a SyntaxError, then your `conf.py` contains some invalid Python syntax, perhaps an unclosed quote/parenthesis on the previous line (we’d need to see a longer snippet to be able to tell).

**Comment by Djultypremierdunom** [comment]
(nikola_env) julien:nikola annebitran$ python conf.py
  File "conf.py", line 133
    "Les Rémouleurs" : {
                     ^
SyntaxError: invalid syntax

**Comment by Kwpolska** [comment]
Not a Nikola bug.  Please check your conf.py file around line 133 (± a few lines). You can also paste a longer snippet if you can’t see the issue.

**Comment by Djultypremierdunom** [comment]
In the conf.py, the pointed line (133) is: 
NAVIGATION_LINKS = {
    DEFAULT_LANG: (
        # ("/", "ACCUEIL"),
        "Les Rémouleurs" : {
        ("/compagnie/compagnie_presentation/", "LES REMOULEURS"),
        ("/compagnie/equipe", "L'équipe"),
        }
        ("/galleries/spectacles/DerniersGeants", "SPECTACLES"),
        ("/presse/presse", "PRESSE"),
        ("/agenda/", "AGENDA"),
        ("/atelier/atelier_residence_argenteuil", "L'ATELIER"),
        ("/sur_mesure/sur_mesure_presentation/", "SUR MESURE"),
        ("/contact/", "CONTACT"),
        ("/en", "ENGLISH")
    ),

Is there somenthing to cut or to add ?

**Comment by Djultypremierdunom** [comment]
So sorry to bother you with this nooby bug, but I can't see the error...

**Comment by Kwpolska** [comment]
You are using invalid syntax for the nested menu (it still has to be a tuple. You can fix it like this:

```py
NAVIGATION_LINKS = {
    DEFAULT_LANG: (
        # ("/", "ACCUEIL"),
        ((
            ("/compagnie/compagnie_presentation/", "LES REMOULEURS"),
            ("/compagnie/equipe", "L'équipe"),
        ), "Les Rémouleurs")
        ("/galleries/spectacles/DerniersGeants", "SPECTACLES"),
        ("/presse/presse", "PRESSE"),
        ("/agenda/", "AGENDA"),
        ("/atelier/atelier_residence_argenteuil", "L'ATELIER"),
        ("/sur_mesure/sur_mesure_presentation/", "SUR MESURE"),
        ("/contact/", "CONTACT"),
        ("/en", "ENGLISH")
    ),
}
```

**Comment by Djultypremierdunom** [comment]
Thank you so much ! However, it seems that the tuple is still not accepted by Nikola... I will rethink my navigation map.

**Comment by Kwpolska** [comment]
There was a small typo:

```py
NAVIGATION_LINKS = {
    DEFAULT_LANG: (
        # ("/", "ACCUEIL"),
        ((
            ("/compagnie/compagnie_presentation/", "LES REMOULEURS"),
            ("/compagnie/equipe", "L'équipe"),
        ), "Les Rémouleurs"),
        ("/galleries/spectacles/DerniersGeants", "SPECTACLES"),
        ("/presse/presse", "PRESSE"),
        ("/agenda/", "AGENDA"),
        ("/atelier/atelier_residence_argenteuil", "L'ATELIER"),
        ("/sur_mesure/sur_mesure_presentation/", "SUR MESURE"),
        ("/contact/", "CONTACT"),
        ("/en", "ENGLISH")
    ),
}
```
