### ISSUE TITLE
URL redirection using docker

### ISSUE THREAD

**Issue by xgaia** [getnikola/nikola#3407]
### Environment

**Python Version:** 3.7.7

**Nikola Version:** 8.0.4

**Operating System:** Docker nginx-alpine

### Description:
I use a docker nginx-alpine to deploy my nikola website to a specific port, and urls are not correctly redirected.

How to reproduce:

```bash
docker pull askomics/website
docker run --name website -d -p 8008:80 askomics/website
```

then, go to localhost:8008

putting the mouse on `News` show that the link is localhost;8008/news, but when I click on it, it redirect me to localhost/new/

How can I get the right redirection ?

**Comment by ralsina** [comment]
Usually that should work. What is your SITE_URL setting?

**Comment by Kwpolska** [comment]
Use links that end in slashes, i.e. `/news/`. All web servers will redirect links to folders like this, so to avoid the redirect, you must add the slash yourself.

[PS. Pipenv is a bad product and not recommended for Nikola.](https://chriswarrick.com/blog/2018/07/17/pipenv-promises-a-lot-delivers-very-little/)

**Comment by xgaia** [comment]
> Use links that end in slashes, i.e. `/news/`. All web servers will redirect links to folders like this, so to avoid the redirect, you must add the slash yourself.

I had end slashes 
```python
NAVIGATION_LINKS = {
    DEFAULT_LANG: (
        ("/news/", 'News'),
    ),
}

NAVIGATION_ALT_LINKS = {
    DEFAULT_LANG: (
        ("/about/", "About"),
    ),
}

```
It works on the main page, but if I go to a page (about), the navbar still show links without the end slashes

**Comment by xgaia** [comment]
It work when I set `PRETTY_URLS = True` Thanks for your help !

**Comment by Kwpolska** [comment]
When I tested your site, [PRETTY_URLS was enabled](https://github.com/askomics/website/blob/ca126bb1c1d92c84a20744158cb7a98160d9aedb/conf.py#L1014), but the slashes in NAVIGATION_LINKS were missing.

**Comment by xgaia** [comment]
Yes, I've tried several combinations. Work with PRETTY_URLS enabled and NAVIGATION_LINKS with end slashes
