### ISSUE TITLE
Add support for microblog-style posts without titles

### ISSUE THREAD

**Issue by devilgate** [getnikola/nikola#3408]
Like Dave Winer and others, I like to have some posts without titles. This is easy enough to implement with the templates. But there are a number of different conditions that can cause the title to be absent:

* Use of the `hidetitle` metadata
* Title is the "NO TITLE" placeholder
* Title is literally blank
* Post type: I'm using "micro" to indicate a microblog post.

As I say, I've got this working reasonably well _in my fork of one particular theme_. But my templates need to have various duplicated `if` conditions scattered through them, and anyone wanting similar functionality doesn't benefit. I would be good if there were a built-in feature by which templates could identify posts for which they should not render the title.

I propose adding a function to `Post.py`, such as `should_show_title()`. It would check the first three of the points above. For the fourth, I'm thinking of a new config item, something like `TYPES_WITHOUT_TITLES`, which would contain an optional list of of post types for which titles are not to be shown.

I plan to start work on this, but I'm open to suggestions for alternative approaches, corrections to my thinking, or what have you. I'm new to the Nikola codebase, so I'll be learning it as I go.

**Comment by Kwpolska** [comment]
What slugs do you use for your micro posts? How do you identify them if they don’t have a title?

**Comment by devilgate** [comment]
> What slugs do you use for your micro posts? How do you identify them if they don’t have a title?

That's a good question. I imported my site from WordPress, so most of them have the WP post ID number as the slug. Since starting to use Nikola, I haven't quite settled on what to use. I've tried using the date in ISO format (2020-05-06), but that obviously gets problematic if I post more than once in a day. And it duplicates information that's already in the URL path.

For some I have included a title, but using the `micro` post type, my template suppresses it. That's the easiest way, since `nikola new_post` needs a title.

I'd quite like it if there were a `nikola micro` option that didn't need a title, and that used something like the WordPress ID. But that's probably not worth the effort.

**Comment by ralsina** [comment]
Doing a command that does the same as new_post but doesn't ask for a title
is very easy.

You can make it a plugin, then anyone can use it.

**Comment by ralsina** [comment]
You can even inherit CommandNewPost :-)

**Comment by devilgate** [comment]
> Doing a command that does the same as new_post but doesn't ask for a title is very easy. You can make it a plugin, then anyone can use it.

I'll give that some thought. My "probably not worth the effort" thought was more about the idea of generating suitable slugs in the style of the WordPress ID number. It's something you could do, but it could easily get complex.

On the other hand, a simple file containing a number, read, updated, written back...

**Comment by ralsina** [comment]
On Wed, May 6, 2020 at 8:44 AM Martin McCallion <notifications@github.com>
wrote:

> Doing a command that does the same as new_post but doesn't ask for a title
> is very easy. You can make it a plugin, then anyone can use it.
>
> I'll give that some thought. My "probably not worth the effort" thought
> was more about the idea of generating suitable slugs in the style of the
> WordPress ID number. It's something you could do, but it could easily get
> complex.
>
> On the other hand, a simple file containing a number, read, updated,
> written back...
>

You can put that number in "state" (self.site.state in any plugin)  but if
that ever gets lost then things will get messed up.
If all you need is this to be reasonably unique, you can use something like
str(uuid.uuid4())[:8] ... the odds of collision are tiny.

**Comment by devilgate** [comment]
OK, I've got the code for the title display options working in my fork. I'd like to document it properly, but it's not obvious to me what the best place is to do that. Presumably [the ReadTheDocs page](https://nikola.readthedocs.io/en/latest/nikola/#module-nikola.post) will get updated eventually from the docstrings I've written, but that's kind of obscure.

I'd like to say to theme authors, "If you want to check whether a post's title should be shown, you can call `post.should_hide_title()`," for example. The [Theming Tutorial](https://getnikola.com/creating-a-theme.html) is a bit too specific to what it's doing to include that there, while the [Theming Reference](https://getnikola.com/theming.html) doesn't go to the level of detail of what methods are available.

In fact it seems like the only place where you can find what methods are available on a post _is_ the ReadTheDocs page (or the code, of course).

Am I missing something? Is there somewhere I can put documentation like that?

**Comment by ralsina** [comment]
Basically Post is undocumented outside the source code. We should probably
link to the automatically generated class documentation from the places
where it makes sense to call Post methods, like templated shortcuts or
theming guides.

**Comment by devilgate** [comment]
I was just looking at Dave Winer’s site, and I realised that he just uses the time for his slugs. Which is both obvious, and consistent with a date-based URL. So you’d end up with something like `/blog/2020/05/07/160835.html`

**Comment by ralsina** [comment]
The important code would be this:

https://github.com/getnikola/nikola/blob/e423974f03cf25e7ca602aa767e00f55c62c45fa/nikola/nikola.py#L1738

**Comment by devilgate** [comment]
Thanks, that seems to have sorted it.
