### ISSUE TITLE
documented minimal Python version is inconsistent

### ISSUE THREAD

**Issue by Xeverous** [getnikola/nikola#3413]
Note: this is a documentation-only issue

- On https://getnikola.com, there is *"Nikola is written in Python 3 (3.5+)."*.

- On https://getnikola.com/handbook.html, there is *"Nikola's static output and its input files will work as long as you can install Python 3.4 or newer"*.

**Comment by Kwpolska** [comment]
I updated the documentation and rebuilt the site, thanks.

**Comment by Xeverous** [comment]
Another small thing, this sentence on handbook looks incomplete:

> **pretty_url**
>
> Set to "False" to disable pretty URL for this page. Example:

**Comment by Kwpolska** [comment]
Thanks, I’ll remove the `Example:` bit. We used to have examples, but those aren’t super useful IMO, so let’s leave it like that.
