### ISSUE TITLE
Logging API for plugins

### ISSUE THREAD

**Issue by Xeverous** [getnikola/nikola#3414]
I have a need to issue some logs from my (custom) plugins. I think the need is self-explanatory. I have been looking for anything log-related on https://nikola.readthedocs.io/en/latest/nikola but:

- I haven't found any mention of logging on the docs. But I see that Nikola outputs some scanning, build and HTTP server logs.
- I am not able to find documentation of the base classes for plugins. There is no explicit documentation of `SignalHandler` type and `ShortcodePlugin`. Are they intended to be hidden? Is there nothing I can use in types derived from them?

**Comment by ralsina** [comment]
import nikola.log and either use `LOGGER` or call `get_logger("something")` and use your own.

**Comment by Kwpolska** [comment]
We should probably work on documenting those a bit more, although `SignalHandler`s are fully documented in the extending document: https://nikola.readthedocs.io/en/latest/extending/#signalhandler-plugins

**Comment by Xeverous** [comment]
> We should probably work on documenting those a bit more, although `SignalHandler`s are fully documented in the extending document

If there is nothing more to use in them then I think that the current documentation of signal handlers and shortcode plugins is fine.

I'm more surprised that the read the docs page has no explicit section that lists public plugin functions and the `nikola.log` is not present at all.

**Comment by Kwpolska** [comment]
I updated the Sphinx docs (cefb86f2c) and added some stuff to extending.rst (0a22dd5fd).

**Comment by Xeverous** [comment]
thanks
