### ISSUE TITLE
post object and/or more context information for Markdown and reST extensions

### ISSUE THREAD

**Issue by Xeverous** [getnikola/nikola#3415]
My use case: I'm implementing some Markdown/reST extensions and some of their options/parameters are paths and/or may depend on the Nikola configuration.

The documentation for reST plugins (https://getnikola.com/extending.html#restextension-plugins) mentions magic paths however:

- I can not access the `Post` instance from which the reST/Markdown extension is called, am I right?
- I don't see how can I report that my reST extension depends on any paths. In contrast, `ShortcodePlugin` has a documented handler that returns both the result and its dependencies. How could I do it for specific Markdown/reST extension invokation?
- There is `inject_dependency` in `BasePlugin` class, but since I can not access the `Post` object from the extension, I don't even know the path of the post being currently rendered. Is there any way to get it?

**Comment by ralsina** [comment]
You don't need to add dependencies to the post, you just need to add them to the task at hand.

To add a dependency, use `self.state.document.settings.record_dependencies.add` there is an example [here](https://github.com/getnikola/nikola/blob/master/nikola/plugins/compile/rest/post_list.py)

You can call that with paths or these pseudo paths (like `####MAGIC####CONFIG:OPTIONNAME` or `####MAGIC####TIMELINE`)

> I don't see how can I report that my reST extension depends on any paths.

Your extension doesn't, each specific instance of your extension running will depend on things, which you record using the above method.

**Comment by Xeverous** [comment]
Great, this is exactly what I need.

Can I obtain the path to the post source? Is `filename = self.state.document.settings._nikola_source_path` this thing? Looks like an implementation detail considering `_`.

I would like to be able to use 2 path types in my extensions:

- relative to the post being rendered
- relative to the root or some fixed directory in the repository

That's why I would need the path to the post/page source.

**Comment by ralsina** [comment]
We are passing the document path to the docutils machinery, surely it's in there somewhere.

Additionallly yes, looks like we put it in `_nikola_source_path` https://github.com/getnikola/nikola/blob/1477b4de9198f8dde88ba621af661b7e95d800fd/nikola/plugins/compile/rest/__init__.py#L380

**Comment by Xeverous** [comment]
Just tested and I'm getting `pages/test/rest_test.rst`. This will do.
