### ISSUE TITLE
Changing title colors

### ISSUE THREAD

**Issue by obundeturval** [getnikola/nikola#3416]
Hi,

Is it possible to change the title color in, let's say, the bootstrap4 theme? If so, how? 

Best regards,
Jan

**Comment by ralsina** [comment]
In all the themes using bootstrap you can use [bootswatch](https://bootswatch.com/) to change to different color schemes (See here for [nikola subtheme](https://getnikola.com/handbook.html#getting-extra-themes))

Other than that, you can create a `files/assets/css/custom.css` and usually any theme will apply it last, so you can tweak anything there.
