### ISSUE TITLE
..previewimage attribute not working

### ISSUE THREAD

**Issue by MattiooFR** [getnikola/nikola#3419]
### Environment

**Python Version:**
3.8.2

**Nikola Version:**
8.0.4

**Operating System:**
MacOS

### Description:
I'm trying to use the ..previewimage attribute but I can't manage to make it works, when I'm trying to share a link of my article the preview image I choose does not appear.

**Comment by Kwpolska** [comment]
How are you trying to use it? What theme are you using?

**Comment by MattiooFR** [comment]
I am using a custom theme with engine=jinja and parent=bootstrap4-jinja.

This is an example of meta data from one of my article where I tried to use
it.



When I'm trying to access directly the coding.png image in my deployed blog
the url works.

Le jeu. 18 juin 2020 à 22:12, Chris Warrick <notifications@github.com> a
écrit :

**Comment by Kwpolska** [comment]
Using the previewimage meta line and `bootstrap4-jinja`, the following line appears in the source:

```html
<meta property="og:image" content="https://example.com/images/coding.png">
```

This is the correct line according to OpenGraph, and Facebook claims to support it: https://developers.facebook.com/docs/sharing/webmasters/

If this line appears in your page, and the URL is correct, the website you’re trying to share to lacks support for this feature. If the URL is incorrect, check your SITE_URL. If it does not appear, your theme is missing the call to `helper.open_graph_metadata(post)` in post.tmpl.

**Comment by ralsina** [comment]
You can confirm it works by previewing your link in, for example, twitter,
here: https://cards-dev.twitter.com/validator

Just publish a page with preview information, and try the link there.

**Comment by ralsina** [comment]
Should look like this (but with whatever preview image you chose):

[image: image.png]

**Comment by MattiooFR** [comment]
Sorry for the delay, I just looked in the generated post html and I can see the ```<meta property="og:image" content="https://brainsorting.dev/images/coding.png">``` line. The URL works and display my image, but when I'm pasting the post url link : https://www.brainsorting.dev/posts/environment-variable-flask-heroku/ it does not show any preview image in the twitter validator, neither facebook.

**Comment by MattiooFR** [comment]
Ok that's weird, I just tried again and now twitter validator displays it properly. I'm gonna investigate more.
