### ISSUE TITLE
Nikola fails to compile ipynb files in Gitlab due to missing dependencies.

### ISSUE THREAD

**Issue by k-allika** [getnikola/nikola#3428]
### Environment

**Python Version:** 3.8.3

**Nikola Version:** 8.1.0

**Operating System:** Alpine 3.12

### Description: 
This is not a Nikola bug, but a bug with the Nikola docker image provided with the documentation at https://gitlab.com/pages/nikola

**Issue:** Nikola fails to compile ipynb files even after adding "pip3 install jupyter" per the documentation.

Pipeline error:
```
 $ nikola build
 Scanning posts.....[2020-06-23T18:13:47Z] ERROR: Nikola: In order to build this site (compile ipynb), you must install the "notebook>=4.0.0" Python package.
 [2020-06-23T18:13:47Z] ERROR: Nikola: Exiting due to missing dependencies.
 ERROR: Job failed: exit code 5
```

However, if I scroll up, it shows that the required version of notebook is already installed:
```
$ pip3 install jupyter
 Collecting jupyter
   Downloading https://files.pythonhosted.org/packages/83/df/0f5dd132200728a86190397e1ea87cd76244e42d39ec5e88efd25b2abd7e/jupyter-1.0.0-py2.py3-none-any.whl
 Requirement already satisfied: notebook in /usr/lib/python3.6/site-packages (from jupyter) (6.0.3)
```

**Solution**:
I created a new docker image with the following changes:  
- Upgraded base docker image from alpine 3.9 to alpine 3.12 and added required dependencies (py3-six, py3-requests) as 3.12 was slightly more bare than 3.9.
- Fixed dependency issues (zeromq-dev) in the original Nikola image that would throw errors while processing ipynb files even after adding "pip3 install jupyter" 
- Added built-in support to compile `ipynb` files (Jupyter notebooks).
- Upgrated to the latest version of Nikola 8.1.0.

More info at  
repo: https://gitlab.com/registryimage/nikola
image: registry.gitlab.com/registryimage/nikola

**To Do:** Please update the documentation at https://gitlab.com/pages/nikola either to include the image `registry.gitlab.com/registryimage/nikola` or fix the current image with the dependencies listed in my dockerfile at https://gitlab.com/registryimage/nikola

PS. I am new to git, not a great programmer and not very good with English but I am fascinated with them all. Please forgive me if I made any mistakes. I'll be thankful if you can point them out and help me learn.

**Comment by Kwpolska** [comment]
The GitLab pages/nikola repository is not managed by the Nikola team. We can’t help much with that repository. Please create an issue, or merge requests, in that repository, the people who maintain it are capable of doing this better.

Also, to make the install work, without adding jupyter to the line, I would recommend changing your Dockerfile to do this:

```dockerfile

ENV PIP_OPTS --no-cache-dir --disable-pip-version-check -U --upgrade-strategy eager

RUN …
    CFLAGS="$CFLAGS -L/lib"                             \
    pip3 install $PIP_OPTS pip setuptools wheel         \
    pip3 install $PIP_OPTS 'nikola[extras]'$_VERSION && \

```

Or even better, use a venv to avoid any sort of issues. (Those are still useful in a Docker environment.)
