### ISSUE TITLE
New language "Marathi" - completed translation+review in transifex

### ISSUE THREAD

**Issue by k-allika** [getnikola/nikola#3433]
Just wanted to inform that I completed translation of a new language **Marathi** in transifex (https://www.transifex.com/ralsina/nikola/).

Also completed translations of existing languages **Hindi**, **Telugu** and **Panjabi** (corrections/missing words and reviews).

**Comment by Kwpolska** [comment]
Thanks! I enabled the locale as of commit e676233f7.
