### ISSUE TITLE
THEME_COLOR doesn't seem to work

### ISSUE THREAD

**Issue by k-allika** [getnikola/nikola#3442]
### Environment

**Python Version:** 3.8.3

**Nikola Version:** 8.1.1

**Operating System:** Windows 10

### Description: Changing THEME_COLOR value does not make any changes to the output.

For example, I changed the theme colour as follows:
```
# Primary color of your theme. This will be used to customize your theme.
# Must be a HEX value.
THEME_COLOR = '#fa6511'
```
and changed navbar settings to bg-primary in base.tmpl
```
<nav class="navbar navbar-expand-md static-top mb-4 navbar-dark bg-primary>
```
I was expecting to see a change in navbar background but it still shows the default primary background.

**Comment by Kwpolska** [comment]
The description of `THEME_COLOR` is really bad. It affects the address bar in Chrome for Android, but not much else. While themes could use it for actual CSS, it’s not easy with CSS as-is (variables do exist, but `lighten()` doesn’t, for example).

I changed the description in commit 680fc3333.
