### ISSUE TITLE
Nikola strips away query strings with URL_TYPE='full_path'

### ISSUE THREAD

**Issue by radek-sprta** [getnikola/nikola#3448]
### Environment

**Python Version:3.8.2**

**Nikola Version:8.1.1**

**Operating System:Ubuntu 20.04.1 LTS**

### Description:

As title says, with `URL_TYPE='full_path'`, Nikola strips away query strings from links. Is that intentional?

#### Example:
The relevant line from the template:
`<script src="/assets/js/test.js?version={{ assets_version }}"></script>`

- Result with `URL_TYPE='rel_path'`:  
`<script src="assets/js/all.js?version=1597143702"></script>`
- Result with `URL_TYPE='full_path'`:  
`<script src=/assets/js/all.js></script>`
- Result with `URL_TYPE='absolute'`:  
`<script src="https://example.org/assets/js/all.js?version=1597143702"></script>`

**Comment by Kwpolska** [comment]
Fixed in #3449, please test.

**Comment by radek-sprta** [comment]
I've tested it and it looks good! Thanks.
