### ISSUE TITLE
reST doc directive: slugs with slashes in no longer work

### ISSUE THREAD

**Issue by infinity0** [getnikola/nikola#3450]
At some point in the previous few versions, slugs with slashes in no longer work - links pointing to them have their slashes removed before the link is resolved, leading to an error like `"swowndata" slug doesn't exist` for a slug called `sw/owndata`. I can't find this being mentioned in the release notes or the other issues here, so I assume this was done by accident, is a bug, and should be fixed.

**Comment by infinity0** [comment]
It's an issue with links - if you `nikola build` on a checkout of https://github.com/infinity0/droid-hacks you can hopefully reproduce it.

**Comment by Kwpolska** [comment]
Reproduced, bug was introduced in commit 22b29404241992816399c9ff4116ccb1572650e1.

**Comment by Kwpolska** [comment]
I created a PR with a fix, #3455.

**Comment by infinity0** [comment]
Thanks, that works nicely for me!
