### ISSUE TITLE
Native support for Utterances comment system

### ISSUE THREAD

**Issue by asmeurer** [getnikola/nikola#3453]
See https://utteranc.es/

Utterances gives you a script tag that you can add to your site, but it's not clear where that should go in the conf.py.

**Comment by Kwpolska** [comment]
Adding a new comment system requires changes to templates, namely `comments_helper.tmpl` and `comments_helper_NAMEOFSYSTEM.tmpl`. Looking at the page, it shouldn’t be hard to integrate this with Nikola. Would you be willing to take this?

**Comment by asmeurer** [comment]
What would be the best way to do it? Utterances has different configuration options than the other systems.

**Comment by Kwpolska** [comment]
You can use a GLOBAL_CONTEXT variable like isso does, or perhaps try to fit it in COMMENT_SYSTEM_ID.

**Comment by asmeurer** [comment]
`GLOBAL_CONTEXT` seems like it should work. However, there is one configuration option that is required (either `issue-term` or `issue-number`). If you don't specify it, it will show an error in the console log. Can we make it show an error on the Nikola build?

**Comment by Kwpolska** [comment]
You can’t output to Nikola logs from the console. The only (partial) solution I could think of is to add a big red warning box to the output if neither option is set.

**Comment by asmeurer** [comment]
I mean something like

```py
if COMMENT_SYSTEM == 'utterances':
    utterances_config = GLOBAL_CONTEXT.get('utterances_config', {})
    if not ('issue-term' in utterances_config or 'issue-number' in utterances_config):
        error("COMMENT_SYSTEM = 'utterances' must have either GLOBAL_CONTEXT['utterances_config']['issue-term'] or GLOBAL_CONTEXT['utterances_config']['issue-term'] defined")
```

I just don't know where that would go.

**Comment by Kwpolska** [comment]
We have a bunch of [config fixing and validation things in nikola.py](https://github.com/getnikola/nikola/blob/master/nikola/nikola.py#L731-L902).
