### ISSUE TITLE
Hyvor Talk comments system

### ISSUE THREAD

**Issue by k-allika** [getnikola/nikola#3454]
Request to add Hyvor Talk comments system. 

A few features that I liked about Hyvor, especially as compared to Disqus, are 
- no tracking even for free accounts
- no sign up required for commenting
- lightweight
- fully customisable
- doesn't sell user data

Website: https://talk.hyvor.com/
Code: https://talk.hyvor.com/docs/code

Thanks

**Comment by Kwpolska** [comment]
[This has been requested in January on the mailing list.](https://groups.google.com/forum/#!topic/nikola-discuss/Dyg6h2tBlqQ) It was denied for the following reasons:

* It’s a commercial product
* Very few users (the website says 1100+, but they have only [67 Twitter followers](https://wordpress.org/plugins/hyvor-talk/), and their WordPress plugin has [40+ users](https://wordpress.org/plugins/hyvor-talk/))

Adding a comment system is more work for us (we need to maintain it; if they change their JS snippet, we need to change code in Nikola), and I don’t think it’s worth it to give free advertising to a commercial product.

If you want a good comment system that matches requirements 1-5, I recommend self-hosted isso.
