### ISSUE TITLE
Incorrect src attribute for images in featured posts in bootblog4 theme

### ISSUE THREAD

**Issue by txels** [getnikola/nikola#3471]
### Environment

**Python Version:** 3.8.5

**Nikola Version:** 8.1.1

**Operating System:** Ubuntu 20.10

### Description:

It appears that Nikola 8.1.1 has introduced either a bug or a backwards-incompatible change that makes images in featured posts using the bootblog4 template render incorrecty.

My featured posts include these headings: 
```
.. status: featured
.. previewimage: /galleries/face-a-day-2020/20200817-me.png
```

My nikola site is rendered under a path: 
```python
# conf.py
SITE_URL = "https://carles.barrobes.com/drawing/"
# BASE_URL not set
```

- With nikola 8.0.4, this would generate a correct `src` attribute `galleries/face-a-day-2020/20200817-me.png`
- In nikola 8.1.1, this generates a relative path that doesn't work `drawing/galleries/face-a-day-2020/20200817-me.png` as it generates an invalid image URL of `https://carles.barrobes.com/drawing/drawing/galleries/face-a-day-2020/20200817-me.png` (duplicated `drawing` in the path).

The source of the issue seems to have been introduced here: https://github.com/getnikola/nikola/commit/e559cfda090edacbca0769395703fdbde50691cb

**Comment by Kwpolska** [comment]
The diff link doesn’t work, please link to the specific commit.

**Comment by txels** [comment]
Hmmm. Possibly this commit then https://github.com/getnikola/nikola/commit/e559cfda090edacbca0769395703fdbde50691cb

**Comment by Kwpolska** [comment]
I created PR #3475 with a fix, please test.
