### ISSUE TITLE
Link to jpg image file not working properly

### ISSUE THREAD

**Issue by rzbrk** [getnikola/nikola#3472]
### Environment

**Python Version:** Python 3.7.3

**Nikola Version:** Nikola v8.1.1

**Operating System:** Linux xxxxxxx 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux

**Web Browser:** Brave Browser 86.1.16.68

### Description:

When inserting a link to an image in a reST source file, e.g.

    `Link to image </image/image.jpg>`_

the link in the output html file is not working properly, meaning by clicking on the link in a web browser, the image is not displayed as expected. Actually, when clicking the link, nothing happens. The image can be opened by right-clicking on the link and selecting "open in new tab", hence the link to the jpg file is correct.

The link created in the html output file is of type ``reference external``:

    <a class="reference external" href="../../images/image.jpg">Link to image</a>

**Comment by Kwpolska** [comment]
I created PR #3474 with a fix, please test.
