### ISSUE TITLE
Migrate away from Travis CI

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#3473]
Travis CI is going to get rid of open-source projects (unless they ask for special treatment), and macOS builds will not be supported for free plans. The platform hasn’t been in good shape for some time. (Sources: [1](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom), [2](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), [3](https://www.theregister.com/2020/11/02/travis_ci_pricng/))

I propose to migrate to GitHub Actions, which is more flexible, and completely free and unlimited for open-source projects (that’s us!). We can migrate all builds (Linux, Windows, macOS) to the platform, and it’s integrated with the rest of GitHub. (We are using AppVeyor for Windows builds now, and while they are still nice to OSS projects, we can migrate it too for more consistency.)

If anyone has ideas for other CI providers with free open-source builds for these three platforms, or any objections, feel free to share. If anyone wants to contribute (parts of) Actions support, feel free to do that, PRs are always welcome.

Final deadline is December 31, 2020, when travis-ci.org will close down.

To do:

- [x] getnikola/nikola (done by @felixfontein in #3477)
- [x] getnikola/plugins (I’ll just copy the main repo one and modify it slightly)
- [x] getnikola/invariant-builds (perhaps we can upload it somewhere else than a git repo?)

**Comment by ralsina** [comment]
If everyone ends up stopping giving us free builds we can always self-host drone.io or something. Luckily I can afford that sort of thing again now :-)

**Comment by Kwpolska** [comment]
GitHub Actions can be self-hosted too, although that’s [not really desirable](https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories) for open-source projects where everyone can run code on the runner via a PR.

**Comment by felixfontein** [comment]
GitHub Actions sounds good. I guess keeping AppVeyor (as long as they support OSS) is fine too.

I have not that much experience with GH Actions yet, but I do have some. I can definitely try to help :)

**Comment by k-allika** [comment]
Please forgive me if I am naive, but would GitLab CI/CD be one of the solutions? I have been using free GitLab pages with Nikola for a few months now and had no issues. I also built a docker image for Nikola with built-in support for Jupyter notebook files here [https://gitlab.com/registryimage/nikola](https://gitlab.com/registryimage/nikola) (<- Please have a look)

Benefits to users:
1. It's simple. Users don't have to code or build nikola docker image for Nikola. All they have to do is include the .gitlab-ci.yml file in their repo and push it to GitLab. GitLab will access my Nikola image from above and build and deploy the site in the background.
2. It's small and quick. My Nikola image is stripped down to less than 60 MB, which is smaller than the smallest docker images mentioned in https://www.getnikola.com/getting-started.html which is about 230 MB. Smaller image loads faster, builds the site quicker and saves on your build minutes.

Is any of this relevant or useful to the issue?

**Comment by Kwpolska** [comment]
@k-allika  This isn’t relevant. This issue is about Travis CI being used to run Nikola’s test suite. So we don’t need those images, we need to install stuff on our own. GitHub Actions is great for CI, and you can use it to build a Nikola page with <https://github.com/getnikola/nikola-action>. If we wanted to use GitLab CI for this, we’d need to migrate all repos to GitLab, and we aren’t doing that (that would be very costly).

For building pages, our docs mention both the `nikola-action` for GitHub users, and https://gitlab.com/pages/nikola for GitLab. (It used to mention Travis too until last weekend, the post is still up on the Nikola blog.)

**Comment by k-allika** [comment]
@Kwpolska Thank you for taking time to explain this to me. I understand now.

**Comment by felixfontein** [comment]
@Kwpolska I think this is done now, right? (https://github.com/getnikola/nikola/commit/d0ef5b68d0667f635ecb2bc0d5b92e480b5e4b25, https://github.com/getnikola/plugins/pull/360, https://github.com/getnikola/invariant-builds/pull/1)

**Comment by Kwpolska** [comment]
Yes, it's done. Closing this.
