### ISSUE TITLE
Implement separate source file for teaser text

### ISSUE THREAD

**Issue by djmattyg007** [getnikola/nikola#3485]
Sometimes it may be desirable to have teaser text that doesn't exactly match the main content of the post. Right now, as far as I can tell there isn't a way to support this use case. So, I decided to try implementing it myself.

While I've had a tiny amount of success, I haven't been able to work around the issues that have cropped up with dependency management in the task handling system. The biggest problem I've found is `PageCompiler.compile` typically expects to attach dependencies directly to post objects itself, rather than passing them back to the post. This isn't compatible with having multiple compileable source files for the one post that can all contain unique content, and resolving it would unfortunately be a breaking change.

I'm therefore looking to start a discussion around what would be considered acceptable by the maintainers in terms of the magnitude of changes. Is this idea even likely to be accepted if I was to submit a PR? Is it okay to consider this the base of some cleanup and preparation for a new major version with breaking changes?

I'd appreciate any and all advice and recommendations. Thank you for producing such a fantastic tool.

**Comment by Kwpolska** [comment]
I would probably reject the idea of adding extra files support just to achieve this. You can handle this with some custom code in `GLOBAL_CONTEXT` to modify the posts’ HTML.

For example, look at [any post on my blog](https://chriswarrick.com/blog/2016/02/10/deploying-python-web-apps-with-nginx-and-uwsgi-emperor/) and note that the teaser is using larger text than everything else. But if you go to the index, you see the teasers only, and at standard size (that’s using the standard Nikola way to do this).

To get this done, you need to:

1. [Define a function that formats the post the way you want in conf.py](https://github.com/Kwpolska/chriswarrick.com/blob/b756d49979eeb99cd9ccb709303197b92bbb9a2e/conf.py#L649-L661) — you will probably want to `return ptext` unconditionally.
2. Add `"post_lead_format": post_lead_format` (names are customizable) to `GLOBAL_CONTEXT`.
3. Customize `post.tmpl` (edit it in your custom theme, or make a copy for customization with `nikola theme -c post.tmpl`), and replace the call to `post.text()` with `post_list_format(post)`.

If you also have posts where you want to display the teaser on the post page, you can solve it with copy-pasting the teaser above and below the marker, or control the behavior of `post_lead_format` with eg. `post.meta("hide_teaser")`.

**Comment by djmattyg007** [comment]
The solution you've proposed doesn't look like it would help with having actually different content for the teaser. I'm after the ability to have potentially totally different content for the teaser from what's in the actual post.

**Comment by Kwpolska** [comment]
It does, please test it out and pay attention to the change suggested in step 1.

**Comment by djmattyg007** [comment]
What it appears you're suggesting is for me to store the teaser in the main post file, and manually split it up myself rather than relying on core code (including the regex) to do so. That looks like it would work fine for pure templating purposes, but would still probably cause problems for things like RSS feed teasers and reading time calculations.

**Comment by Kwpolska** [comment]
Yes, those cases might not be fully solved. That said, if you want only the teasers in RSS, Nikola can do this; if you want the “real” body content, you’d need to patch the RSS rendering logic. Another partial alternative is to put teasers in post metadata — although this is certainly not user-friendly and not usable for teasers longer than a few sentences (although you could use YAML with multiline strings).

Those limitations aren’t convincing enough to make those big changes to Nikola, especially since there weren’t any requests like this for many years (so I doubt many people would make use of this feature). Also, the UX of splitting posts into multiple files (we support that for metadata, but default to 1-file posts) is fairly ugly. I’m closing as wontfix.

**Comment by djmattyg007** [comment]
Fair enough. Thanks for your consideration!
