### ISSUE TITLE
tables are not getting rendered despite adding 'tables' extension

### ISSUE THREAD

**Issue by jeanbourgain8** [getnikola/nikola#3487]
### Environment

**Python Version:**
Python 3.8.5
**Nikola Version:**
Nikola v8.1.1
**Operating System:**
Ubuntu 20.04.1
### Description:

It has been a while since I updated my website, yesterday I tried to create a post with a table included but I'm unable to understand why tables are not getting rendered in my posts, while they seem be doing fine in my markdown editor. I even checked by adding tables extension(markdown.extensions.tables) - considering the case of issue with python-markdown, but still I could see no change. Can you please look into & help me with this issue ?
Thanks.
*Details*
- [Blog Post](https://jeanbourgain8.github.io/posts/New%20Posts/Planning/Schedule/schedule-running-days/) : in which rendering is not happening. 
- Screenshot of my local editor 
![blog-post-check](https://user-images.githubusercontent.com/44467730/102579090-ca60cd80-4121-11eb-93b7-d2d6e9f7289d.png)

**Comment by Kwpolska** [comment]
It looks like the post was moved to https://jeanbourgain8.github.io/posts/Web%20Posts/Planning/Schedule/schedule-running-days/

This *is* a table. An unstyled one, but still a table. If you want a prettier one, you can give it `class="table"` — or some other style available in bootstrap4. (I don’t know how to do that with python-markdown; if you can’t do it on the `<table>`, you can wrap the table in a `<div class="table">` and it will work too.)

**Comment by jeanbourgain8** [comment]
Thanks Chris, for mentioning everything in detail, it's been helpful to me.
