### ISSUE TITLE
Ongoing Python 3.5 support?

### ISSUE THREAD

**Issue by matthew16550** [getnikola/nikola#3488]
Hi everyone, this is my first contribution to Nikola.

Python 3.5 reached [end of life](https://www.python.org/downloads/release/python-3510/) on September 5, 2020.

Is there any plan around Nikola dropping support for 3.5?

I ask because I'm working on a plugin to support [PlantUML](https://plantuml.com/) and it needs a few tweaks before the tests will pass on 3.5.  Also if the minimum version changes to 3.6 then f-strings could be used and they will make my code a bit nicer.

**Comment by Kwpolska** [comment]
Ubuntu 16.04 is still supported by Canonical, and it ships Python 3.5. All our dependencies support 3.5 (we haven’t had to make any special exceptions). There isn’t really need to drop it, and for Nikola, there isn’t any burden associated with that support (at least for now).

At the same time, this plugin is going to be contributed to the Plugins Index (getnikola/plugins). Nikola’s compatibility standards don’t apply there, and you can make a 3.6-only plugin if you want (just make sure to mention it in the README).
