### ISSUE TITLE
filters.typogrify might mess up the "og:description" part in the output HTML

### ISSUE THREAD

**Issue by GuDzpoz** [getnikola/nikola#3490]
## Environment

**Python Version:**
Python 3.8.6

**Nikola Version:**
Nikola v8.1.2

**Operating System:**
Manjaro Linux

### Reproduce:
```shell
nikola init --demo nikola
cd nikola
vim conf.py # enable filters.typogrify
nikola new_post # create posts/test.rst
vim posts/test.rst # edit the file
nikola build
```

#### The `posts/test.rst` file:
```rst
.. title: test
.. slug: test
.. date: 2020-12-29 14:51:16 UTC+08:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

A
B & C

```

#### The output HTML in `output/posts/test/index.html`:
```html
...

<meta property="og:description" content="A
B <span class="amp">&amp;</span> C&#8221;>

...
```
(Note that the quotation marks are mismatched.)

I was making a theme, so I looked at the `post_helper.tmpl` in the `base` theme:
```mako
%if post.description():
    <meta property="og:description" content="${post.description()[:200]|h}">
%else:
    <meta property="og:description" content="${post.text(strip_html=true)[:200]|h}">
%endif
```
But I have no idea whether it is a problem with the `base` theme or with nikola or with typogrify itself.

**Comment by Kwpolska** [comment]
That would be a `typogrify` issue, please report it there. We produce valid HTML — newlines are allowed inside attributes, but typogrify is failing to handle those properly.
