### ISSUE TITLE
dispatch PANDOC_OPTIONS base on input extensions

### ISSUE THREAD

**Issue by ickc** [getnikola/nikola#3492]
# Summary

Currently, `COMPILERS` only has a key `pandoc`, and `PANDOC_OPTIONS` is set for all the extensions specified there. The proposed feature simply suggests to have configurable dispatch logic to allow multiple extensions calling pandoc with a different set of `PANDOC_OPTIONS`.

# Example use case

My personal use for this would be to convert one of my site currently using `.md` and `.markdown` to mean a different target format. Both will be converted to HTML, but one of them is slideshow, another is normal "article"/post.

Another possible use case is, if one want to specify markdown extensions in pandoc, say `-t markdown+...-...`, then `COMPILERS['pandoc'] = ['.rst', '.md']` won't work with `PANDOC_OPTIONS = ['-t', 'markdown+...-...']` because that would be wrong input format for `.rst`.

# Suggested implementation

Probably the natural way is to promote

```py
PANDOC_OPTIONS: Union[list, Dict[str, list]]
```

where the keys are those in `COMPILERS['pandoc']`.

If it makes sense I can send a PR doing that. It seems that it only requires changes in <https://github.com/getnikola/nikola/blob/master/nikola/plugins/compile/pandoc.py#L52-L56>, is it true?

**Comment by Kwpolska** [comment]
Please implement this. No changes other than `pandoc.py` should be necessary.

**Comment by ickc** [comment]
There's one thing I don't understand and missed last time I looked:

```py
self.config_dependencies = [str(site.config['PANDOC_OPTIONS'])]
```

What's this `self.config_dependencies` doing here? Turning it into a string is strange here. Is it just for something like logging?

**Comment by Kwpolska** [comment]
`self.config_dependencies` is used to figure out if a post needs updating due to config changes. PANDOC_OPTIONS should be placed there — maybe doing it directly (without `str`) would work. It’s easy to test: if it doesn’t work, you’d (a) get an exception, (b) fail to get a rebuild when you change PANDOC_OPTIONS, (c) get a rebuild when you didn’t change anything (run `nikola build` twice+ in a row to test).

**Comment by ickc** [comment]
I'll leave that alone then as it is working well in the PR. (Good to know it is watching changes from conf.py though I find that sometimes changes in conf.py is not propagated when using `nikola auto`.)

**Comment by Kwpolska** [comment]
> changes in conf.py is not propagated when using nikola auto.

This could be a bug — please report it (we will need specific details about what you’re changing, in what cases does it work, and if it happens with `nikola build; $EDITOR conf.py; nikola build`)

**Comment by ickc** [comment]
I'll watch out for that in the future. Thanks.
