### ISSUE TITLE
logo not showing when LOGO_URL is svg and SHOW_BLOG_TITLE=False 

### ISSUE THREAD

**Issue by ickc** [getnikola/nikola#3493]
### Environment

**Python Version: 3.8.5**

**Nikola Version: 8.1.2**

**Operating System: macOS Catalina 10.15.7 19H15 x86_64**

### Description:

MWE:

```bash
nikola init --demo mysite
```

In `conf.py`, do the following minimum change:

```py
LOGO_URL = 'https://www.w3.org/Icons/SVG/Buttons/svg-w3c-blue.svg'
SHOW_BLOG_TITLE = False
```

Then you render the site and see that the logo is not there.

If you replace that with a png:

```py
LOGO_URL = 'https://upload.wikimedia.org/wikipedia/commons/6/63/Wikipedia-logo.png'
SHOW_BLOG_TITLE = False
```

The logo will show. So it is a bug only if the input logo is an svg.

**Comment by Kwpolska** [comment]
It’s a CSS issue. We don’t specify an image height, and if there is no text to set the container height, the `.svg` gets a size of 0.  I set `min-height: 25px;` to at least make it display, even if it isn’t going to be perfect. (It should be more, but if I did that, it would be likely to break existing blogs with smaller logos.) You should set the height of `#logo` to a value that looks good with your theme and logo.
