### ISSUE TITLE
Replacing husl by hsluv?

### ISSUE THREAD

**Issue by ickc** [getnikola/nikola#3495]
Nikola extras has husl. husl's home page <http://www.husl-colors.org/> is dead.

It seems that <https://www.hsluv.org/> and <https://github.com/hsluv/hsluv> is the currently active one. And its Python implementation is <https://github.com/hsluv/hsluv>.

**Comment by Kwpolska** [comment]
Changing the library to something else would mean there would be different colors, and that would be undesirable. However, on further inspection, hsluv is a new version of husl (it’s not clear from your post or their homepage). I compared the output of our colorization function with the two libraries and hsluv’s output is the same as husl’s (78% colors are identical, 20% changed one octet by 1 (# 123**4**56 vs 123**3**56 or 113**5**56), 2% changed two, a handful changed all three).

I created PR #3498 with the change.

**Comment by ickc** [comment]
Thanks for investigating this. I didn't know. I just use archive.org to see the history and found links pointing to the new repo. (And the Python library has the same license pointing to the same author.)

I think they did a poor job about their (dis)continuity.
