### ISSUE TITLE
Undesired Bullet List Behavior

### ISSUE THREAD

**Issue by nickvence** [getnikola/nikola#3496]
### Environment

**Python Version:** 3.8.5

**Nikola Version:** 8.1.2

**Operating System:** macOS 10.14.6

**Theme:** bootstrap4

### Description:
I get undesired behavior when I create a bulleted list in two formats.

First format, including a blank line before and after the bullet list items
```
Bullet lists:

 - This is item 1
 - This is item 2

```
Undesired behavior: list items have a (larger) font that doesn't match the rest of the text.

-----

Second format, no blank line above the list items:
```
My line above
 - This is item 1
 - This is item 2

```
Undesired behavior: **My line above** is rendered in bold.

I desire a uniform-font bulleted list with no auto-bold.

Thanks for your help,
Nicholas Vence

**Comment by Kwpolska** [comment]
Correct reST syntax:

```rst
My line above

- This is item 1
- This is item 2
```

The first example is interpreted as a blockquote (spaces in front of bullets), the second is considered a definition list (due to the space as well).
