### ISSUE TITLE
should html5lib be listed as dependency #730

### ISSUE THREAD

**Issue by suliuzh** [getnikola/nikola#3497]
Hi
I am wondering if html5lib should be listed in setup.py or requirements,txt?
As we can see, html5lib is used in nikola/filters.py as a must. But when I use "pip install nikola", it seems that html5lib will not be installed automatically. So should html5lib be listed as dependency?

![image](https://user-images.githubusercontent.com/27858725/103738069-5897e780-502e-11eb-8000-3496f81333d8.png)

**Comment by felixfontein** [comment]
It's only needed if you decide to use the filter. If you do not have it installed, it will work just fine.

**Comment by suliuzh** [comment]
thanks for your reply
but I think even this module is not hardcore dependency, maybe html5lib  should be introduceed as an extra dependnecy for the project. 
Maybe it can be listed in extra _requirements.txt_ in the sub-folders?

**Comment by Kwpolska** [comment]
Added to `requirements-extras.txt` (installed with `pip install 'Nikola[extras]'`).

**Comment by suliuzh** [comment]
Additional requirements for 

- jupyter_core

https://github.com/getnikola/nikola/blob/ed7da6ed9247573021c0403dea1cac5f187b88c3/nikola/plugins/compile/ipynb.py#L174

- polib
https://github.com/getnikola/nikola/blob/8cc31e0230a7209cc0bca558a9d085b2e179fe8c/scripts/import_po.py#L9

**Comment by NJUJisq** [comment]
MarkupSafe?
https://github.com/getnikola/nikola/blob/ed7da6ed9247573021c0403dea1cac5f187b88c3/nikola/plugins/template/mako.py#L37
