### ISSUE TITLE
unexpected pretty_url behavior

### ISSUE THREAD

**Issue by ickc** [getnikola/nikola#3503]
### Environment

**Python Version:** 3.8

**Nikola Version:** 8.1.2

**Operating System:** macOS

### Description:

In some situation, setting `PRETTY_URLS = True` in `conf.py` and `pretty_url: false` does not turn off `pretty_url` for that page, e.g. for a file `pages/404.md`.

Even more strangely, if I set `pretty_url: 'some random string'`, it would then turn off `pretty_url`.

I'm guessing it may be related to a multi-lingual setup.

MWE for `pages/404.md`:

```markdown
---
title: sajgfhadfg
pretty_url: false
# or
pretty_url: 'some random string'
url_type: full_path
---

sdfhasdjkgfhsdfalkjg
```

MWE for `conf.py` not available yet.

**Comment by Kwpolska** [comment]
We were expecting a string, since our default meta format is string-based. I fixed it to accept strings, ints and booleans. (PR #3504)

As for the behavior of an unusual string, that’s a side effect of the original implementation, I kept this behavior for backwards compatibility.
