### ISSUE TITLE
Docs over adding new comment systems 

### ISSUE THREAD

**Issue by Woile** [getnikola/nikola#3508]
Hello people, I'd like to ask support for new comment systems, which are free and pro-privacy. Recently disqus has become a bit controversial because of ads, etc.

- https://commentbox.io/
- remarkbox.com

I wouldn't mind trying to add them to the source code in nikola, but I couldn't find any docs on how to do it. I also took a quick glimpse into the code and didn't find them. If someone gives me a small guide, I can try attempt it myself 💪🏻 

Regards and thanks for this cool project :)

**Comment by Kwpolska** [comment]
In general, we are not accepting new comment systems for introduction into the Nikola core.  Only popular, reasonably-priced, high-quality, and unlikely-to-shut-down-in-a-year comment systems can be accepted — and both systems fail those criteria (30/20 Twitter followers respectively; both closed-source; Commentbox has apprently no spam protection and Remarkbox has weird UX).

If you want to add them to your own site, you can just add it to `comments_helper.tmpl` and create a `comments_helper_xxx.tmpl`, for example based on one of the existing systems. (`nikola theme -c comments_helper.tmpl` can help create a copy of the file to change it.)

**Comment by Woile** [comment]
Thanks!!

**Comment by Woile** [comment]
For future reference, Here's a rough implementation of commentbox:

https://github.com/Woile/woile.github.io/blob/e5eed460ff5498de6d627fd3f29901fe5318f31d/themes/willy-theme/templates/comments_helper_commentbox.tmpl

https://github.com/Woile/woile.github.io/blob/e5eed460ff5498de6d627fd3f29901fe5318f31d/themes/willy-theme/templates/comments_helper.tmpl
