### ISSUE TITLE
Nikola build not processing chart directive

### ISSUE THREAD

**Issue by varna9000** [getnikola/nikola#3523]
### Environment

**Python Version:**
Python 3.8.2

**Nikola Version:**
Nikola v8.1.3

**Operating System:**
Mac OS Big Sur 11.2.1 (20D74)

### Description:

Pygal is installed. I'm trying to use the charts directive from the documents example, but Nikola build is not rendering the chart. Instead it shows the code. The code is in .rst file.

**Comment by Kwpolska** [comment]
I cannot reproduce — the `charts` page in the demo site works correctly on my end. Try building that first; if that works but your file doesn’t, attach your `.rst` file.

**Comment by Kwpolska** [comment]
That’s not related. Please show your `.rst` file.

**Comment by varna9000** [comment]
Ok, I found the problem. I was just having the chart code in the file, but apparently it needs the metadata as well. Otherwise it doesn't generate the chart. It's basically the example from the docs I was having in the .rst file:


```
.. chart:: Bar
   :title: 'Browser usage evolution (in %)'
   :x_labels: ["2002", "2003", "2004", "2005", "2006", "2007"]

   'Firefox', [None, None, 0, 16.6, 25, 31]
   'Chrome',  [None, None, None, None, None, None]
   'IE',      [85.8, 84.6, 84.7, 74.5, 66, 58.6]
   'Others',  [14.2, 15.4, 15.3, 8.9, 9, 10.4]
```

**Comment by Kwpolska** [comment]
Yeah, you need post metadata in your posts, otherwise things may break.
