### ISSUE TITLE
[Question] Page as homepage, but keep site as blog

### ISSUE THREAD

**Issue by varna9000** [getnikola/nikola#3524]
Hi, I'm struggling to find a solution to this. I'm building a blog, but I want my homepage to be one of the pages, not the list of blog posts. If I follow the instructions [here](https://getnikola.com/creating-a-site-not-a-blog-with-nikola.html)  I can have a page show as a homepage (index) but I don't know how I can keep the posts on the website as well. If I leave in conflict.py:
```
POSTS = (
    ("posts/*.rst", "pages", "page.tmpl"),
    ("posts/*.md", "pages", "page.tmpl"),
    ("posts/*.txt", "pages", "page.tmpl"),
    ("posts/*.html", "pages", "page.tmpl"),

)
```

Then the blog posts are loading as homepage. Can you suggest a solution to this?

**Comment by varna9000** [comment]
Ok I have to reopen this, as building the website keeps routing the blog pages as homepage. I follow the examples exactly as mentioned in the link above but can't make a page set as homepage.

**Comment by Kwpolska** [comment]
What is your `INDEX_PATH` set to in `conf.py`?

**Comment by varna9000** [comment]
just as in the example - it's ``INDEX_PATH = "blog"``

Then I have:

```
POSTS = (
    ("posts/*.rst", "blog", "post.tmpl"),
    ("posts/*.md", "blog", "post.tmpl"),
    ("posts/*.txt", "blog", "post.tmpl"),
    ("posts/*.html", "blog", "post.tmpl"),
)
PAGES = (
    ("pages/*.rst", "pages", "page.tmpl"),
    ("pages/*.md", "pages", "page.tmpl"),
    ("pages/*.txt", "pages", "page.tmpl"),
    ("pages/*.html", "pages", "page.tmpl"),
)
```

and have created a page with ``nikola new_page`` containing :

```
.. title: index
.. slug: index
.. date: 2021-03-09 17:21:45 UTC+02:00


test page
```

**Comment by Kwpolska** [comment]
This setup isn't enough to put an index in the main directory. The index
page you're seeing is a stale file (removing the output folder will make it
not generate, nikola check -f will warn about it). To put an index.html
file in the site root, you need a PAGES entry with "' (empty string) as its
destination (second element in PAGES tuples).

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by varna9000** [comment]
Thank you! That works exactly as I expect!
