### ISSUE TITLE
HTML input converts & escapes certain valid HTML entities

### ISSUE THREAD

**Issue by Gumnos** [getnikola/nikola#3530]
### Environment

**Python Version:**  3.7.9

**Nikola Version:** 8.1.3

**Operating System:** FreeBSD 12.2-RELEASE-p4

### Description:

Certain valid HTML entities are getting the ampersand escaped; others get converted to Unicode characters rather than maintaining the underlying entity.

**To reproduce:**
    
    $ python3 -m venv demovenv
    $ . demoenv/bin/activate
    (demoenv) $ pip install -u pip
    (demoenv) $ pip install nikola
    (demoenv) $ nikola init demo # answer defaults to everything
    (demoenv) $ cd demo

Now with a working install, tweak `conf.py` to make HTML our preferred format:

    (demoenv) $ ed conf.py # move HTML to the top
    /^POSTS =/
    /html/m.
    /^PAGES =/
    /html/m.
    wq
    
Create a new post and call it "demo"

    (demoenv) $ nikola new_post # answer "demo" to the post name
    (demoenv) $ echo '&frac14; &frac13' >>  posts/demo.html
    (demoenv) $ nikola build
    (demoenv) $ grep frac output/posts/demo/index.html

### Expected behavior:

the output should be the same contents as the input, literally "`&frac14; &frac13;`".  If this is output (e.g. editing the `output/posts/demo/index.html` file to restore them), browsers correctly render the output as "`¼ ⅓`".

### Actual behavior:
    
The `grep` output shows that the `&frac14;` was converted to the Unicode character "¼" while the (legitimate) `&frac13;` entity had its ampersand escaped, making it `&amp;frac13;` in the output. When rendered in browsers, this correctly displays "`¼`" but improperly displays "`&frac13;`" (as one would expect with the underlying HTML).

### Preferred solution

If input is HTML, don't mess with entities, escaping nothing. Just pass them through.

**Comment by Gumnos** [comment]
grr, obviously that one line should read

    $ echo '&frac14; &frac13;' >>  posts/demo.html

(mis-transcribed it from my test session. the issue kinda requires that there to reproduce)

**Comment by Kwpolska** [comment]
Nikola passees all HTML it generates through `lxml` (which enables various forms of post-processing). `lxml` does not support round-tripping entities, or at least it doesn’t seem to, and I don’t really see the point in doing that (it’s 2021 and all browsers understand UTF-8 anyway). The lack of support for `&frac13;` seems to be an issue with lxml (or perhaps it needs some special switch to interpret it? — but Google doesn’t know anything about this), so it should probably be reported to the `lxml` project.
