### ISSUE TITLE
Drop legacy Python support

### ISSUE THREAD

**Issue by JeppeKlitgaard** [getnikola/nikola#3532]
Currently the documentation isn't entirely consistent as to which Python versions are supported, and there seems to be some legacy Python 2 code lying around in the codebase.

What is the the main developers' feelings about legacy support? Python 3.6 is due to stop getting security fixes at the end of 2021, so perhaps bumping the minimum supported Python version to 3.7 already would make sense? This would allow for more/nicer type hinting in the code, which I can see has already been started in the `log.py` code.

**Comment by Kwpolska** [comment]
Our current support policy is 3.5 or newer. Any Python 2 leftovers shouldn’t be major things that make the code worse.

Any changes to the support policy have to take the users into account. Our users have different relationships with Python — ranging from people for whom it’s just some dependency of Nikola, to contributors to [PyPy](https://github.com/pypy/pypy.org). And our users’ approach to Python versioning ranges from “whatever Ubuntu has in their repos” to “whatever was on CPython’s `master` branch at midnight”. We aim to support as many users and use-cases as possible, which means we need a broader range of versions. This means following Ubuntu LTS and Debian stable (and possibly looking at RHEL). Ubuntu 18.04 (old LTS) offers 3.6, 20.04 offers 3.8, Debian buster (stable) offers 3.7, RHEL seems to be at 3.6. There’s also PyPy, which is  This means that we won’t set the version to less than 3.6 for the time being, and we might stay with it even when CPython support for that version ends. We might get rid of 3.5 in the near future (when it becomes difficult to support, or if we get a PR that adds 3.6+ type annotations everywhere). But if there is no reason to upgrade to 3.6, I’d prefer to stay with 3.5.
