### ISSUE TITLE
Make pymdownx a first-class citizen?

### ISSUE THREAD

**Issue by JeppeKlitgaard** [getnikola/nikola#3538]
I wanted to include [pymdownx](https://facelessuser.github.io/pymdown-extensions/) in my Nikola site, but due to the way Pygments-handling is currently done with the `NikolaPygmentsHTML` class and its parent `BetterHtmlFormatter`, the code highlighting from `pymdownx.highlight` does not work well.

Given that `pymdownx` is actively maintained and adds a lot of very useful functionality (including the things like strike-through which is currently implemented by Nikola itself), I was wondering if it might be worthwhile to make `pymdownx` code highlighting compatible, and perhaps even transition to using it to provide extra Markdown functionality out-of-the-box?

`pymdownx` is also used in many `MkDocs` configurations, so I wouldn't expect it to fall out favour anytime soon.

**Comment by ralsina** [comment]
Usually the problem with different syntax highlighting mechanisms is just
that you need to hack the CSS, or you may need to create a plugin. In
principle we support any markdown extension you have installed, but if you
can provide a test case for what you are trying to do maybe I can take a
look (no promises, I am kinda retired :-) )

For example, I am using prismjs to reimplement docutils´ code directive
(and it looks awesome, if I may say so myself ;-)

[image: image.png]

**Comment by JeppeKlitgaard** [comment]
I think I got something that works now after a bit of CSS hacking, though it doesn't feel as elegant as I was hoping for 😄.

I'll close this now, but thank you so much for getting back to me!

**Comment by Kwpolska** [comment]
You could make a custom highlighter plugin for Markdown, based on `pymdownx.highlight` and `NikolaPygmentsHTML`.
