### ISSUE TITLE
Cactus comments

### ISSUE THREAD

**Issue by pieterdavid** [getnikola/nikola#3542]
From https://cactus.chat :
> Cactus Comments is a federated comment system for the web, based on the Matrix protocol.

It is a very new, but rather interesting comments system: each comments section is a [Matrix](https://matrix.org) room, which allows posting with an account on any Matrix homeserver, or as a guest user. Both the homeserver (several implementations exist, see [here](https://matrix.org/docs/projects/try-matrix-now)) and the Cactus Comments application service (which manages the creation and moderation of rooms) can also be [self-hosted](https://cactus.chat/docs/self-hosting/introduction/).

I have the integration working locally, so I am also submitting a PR.

**Comment by Kwpolska** [comment]
Hello, we are not accepting new comment systems for inclusion in Nikola, especially when the comment systems are brand new projects. Those systems end up being a maintenance burden for us when things change in their implementation, probably won’t have many users, and can randomly disappear.

**Comment by carlbordum** [comment]
For anyone who stumbles upon this in the future, @pieterdavid made a very nice project that can help you with this. You can check it out here: [docs](https://cactus.chat/docs/integrations/nikola/), [project](https://github.com/pieterdavid/nikola-cactus-comments), [MR](https://gitlab.com/cactus-comments/cactus.chat/-/merge_requests/4).

**Comment by Kwpolska** [comment]
(Also, if you have ideas about an alternative approach to allow comment systems to be installed from `plugins.getnikola.com` without needing to change core, we’ll happily discuss and take a PR for that — see #3544)
