### ISSUE TITLE
nikola build cli option to force FUTURE_IS_NOW

### ISSUE THREAD

**Issue by wohali** [getnikola/nikola#3558]
**Requested Feature:** For development purposes it can be useful to render and view future posts for testing purposes only. It'd be great to force that with a `nikola build` or `nikola auto` option, such as `--future=true`.

**Related Area:** General building

**Do you want to contribute this yourself as a pull request?**

- [X] Yes, I don’t have code ready yet (that’s okay!)
- [X] No (that’s okay too!)

I'm pretty sure I can code this, but won't if it's not desired as a feature.

**Does this feature affect backwards compatibility? If yes, in what way?** I can't see how...

**Rationale and full description:** For interactive development purposes, without having to manually change the date on posts for validation purposes -- this would be lovely.

**Comment by Kwpolska** [comment]
I don’t think we should make configuration options into command-line arguments, that would only increase complexity (especially considering the way in which arguments are added isn’t always ideal). This use-case can be handled with the `--conf` option and multiple config files.

**Comment by wohali** [comment]
@Kwpolska But `nikola auto` does not take a `--conf` argument:

```bash
$ nikola auto --conf conf-future.py"
ERROR: Error parsing Command: option --conf not recognized (parsing options: ['--conf', 'conf-future.py'])
$ nikola build --conf conf-future.py
ERROR: Error parsing Command: option --conf not recognized (parsing options: ['--conf', 'conf-future.py'])
```

What am I doing wrong? If these options aren't supported, can I change this request into one to add them?

**Comment by Kwpolska** [comment]
It requires an equals sign: `--conf=conf-future.py`

**Comment by wohali** [comment]
Got it, thanks. I didn't see `--conf` in the help output.

Guess I can close this, but I'd suggest updating the `-h` output to show the `--conf` option, it's not there for either `build` or `auto`.
