### ISSUE TITLE
Misaligned list of posts

### ISSUE THREAD

**Issue by padawanphysicist** [getnikola/nikola#3560]
# Environment

- Python Version:
Python 3.9.4

- Nikola Version:
Nikola v8.1.3

- Operating System:
Gentoo Linux

I've tried to build a blog using the demo contents,
```
nikola init --demo mypage/
```
and after creating another post,
```
nikola new_post
```
The recent posts are misaligned as in the attached screenshot. I've tried with other themes than the default without success.

Looking at the generated HTML only the first post is contained in the element which I suppose should wrap all the list (`<div id="content" class="container" role="main">`)

I'm not sure if this is the default behavior now, and I could get them aligned by hand adding a CSS file, but it feels like a hack. Can someone point a way to get it using templates?

![Screenshot_20210628_135301](https://user-images.githubusercontent.com/2635225/123674662-3bdbb000-d818-11eb-9a47-8ea3f24e2f07.png)

**Comment by Kwpolska** [comment]
I cannot reproduce. This is how it looks on my side:
![image](https://user-images.githubusercontent.com/327323/123678394-883de480-d846-11eb-93a2-56df0632dcd1.png)

Can you showthe output of `pip freeze` and attach a `.zip` of your site (`mypage`) folder?

**Comment by Kwpolska** [comment]
There aren’t almost any package versions in this `pip freeze` output. Perhaps you were working with some unusual version of lxml, docutils, or something else, that inserted an extra `</div>`.
