### ISSUE TITLE
Comments section rendered wrongly if title contains ampersands

### ISSUE THREAD

**Issue by devilgate** [getnikola/nikola#3561]
I've recently got the Isso commenting system working on my site, but there is a problem with the way the comments section is rendered in certain circumstances.

See this screenshot:
<img width="1054" alt="Screenshot 2021-07-13 at 18 03 21" src="https://user-images.githubusercontent.com/4842280/125495339-2720e3a1-25aa-40c5-99bb-12fe6e53413d.png">

The comment form should appear under the Previous/Next post buttons.

That's for a post called [Assignment in Eternity vols 1 & 2 by Robert A Heinlein (Books 2020, 12 & 13)](https://devilgate.org/blog/2020/06/13/assignment-in-eternity/), which you can see at that link. The ampersands in the title seem to be confusing something. Here's the relevant part of the generated HTML:

```html
<section class="comments hidden-print"><div data-title="Assignment in Eternity vols 1 <span class="amp">&amp;</span> 2 by Robert A Heinlein (Books 2020, 12 <span class="amp">&amp;</span> 13)&#8221; id=&#8221;isso-thread&#8221;></div>
        <script src="https://devilgate.org/isso/js/embed.min.js" data-isso="https://devilgate.org/isso/" data-isso-lang="en"></script></section>
```

As you can see, it has put an `&amp;` in the middle of the `data-title` attribute, as well as wrapping it in a `span`. Some of that combination is throwing everything else off.

Nikola v8.1.2 running on Ubuntu 20.04.2 LTS, but also on macOS Big Sur 11.4

**Comment by Kwpolska** [comment]
The `&amp;` is fine, but the `<span>` isn’t. The `<span>` comes from the `typogrify` filter. To fix this, you could disable `typogrify` or the specific `amp` filter of it, or somehow convince it not to mangle `data-title`.

**Comment by devilgate** [comment]
A bit of searching led me to a way to fix this using the `typogrify_custom` filter. The relevant part of my `conf.py` now looks like this:

```python
from nikola import filters
from nikola.filters import typogrify_custom
import typogrify.filters as typo
import functools
FILTERS = {
    # This setup uses the custom version of the Typogrify filter, selecting
    # which subfilters to run. We're not running the `amp` ome, which fixes a
    # problem where Typogrify was adding a span around ampersands, which broke
    # the Isso comments section.
    ".html": [functools.partial(typogrify_custom, typogrify_filters=[typo.widont, typo.smartypants, typo.caps, typo.initial_quotes]), filters.deduplicate_ids],
```

So I'm running all the Typogrify subfilters except `amp`. That's working for me now.

An alternative version, which worked briefly but then stopped for no reason I could see, was to use this formulation:

```python
 ".html": [functools.partial(typogrify_custom, ignore_tags=["section.comments"])],
```

which should have prevented the filter from running on the `<section>` with the `comments` class. As I say, it worked on one build, but then broke again. Possibly that was at the point where I upgraded Nikola to version 8.1.3, but I'm not sure.
