### ISSUE TITLE
`@` symbol in tpl eats content in element

### ISSUE THREAD

**Issue by kai-tub** [getnikola/nikola#3563]
### Environment

**Python Version:** 3.9.6
**Nikola Version:** 8.1.3
**Operating System:** Linux

### Description:

First of all, think you very much for creating such a cool tool!
It was very easy to set up and the documentation is very good. :pray: 

To my _issue_:
I am very new to anything web-related (first time taking a closer look at CSS, Jinja, etc.), so this might be a trivial issue where I am not understanding how the basics of jinja or static page generators work.
I am trying to create a custom theme and use that to learn a tiny bit about front-end development.

For me, the following behavior is unexpected and I am asking you for guidance:
If I have an HTML element in a `tpl` file:
```html
    <button @click="open = false"></button>
```
(I am trying to use [alpine.js](https://github.com/alpinejs/alpine/tree/v2.8.2))
After building the webpage, the `@click="open = false"` element is gone and replaced with `false`
So the entry looks like this:
```html
    <button false></button>'
```

To reproduce:
1. Init a new demo Nikola demo `nikola init --demo`
2. Add `<button @click="open = false"></button>'` after `articleBody text` div element
3. Build Nikola page
4. Go to post page
5. Inspect tiny button fragment that is created after the text
6. Notice that the `@click` part is missing

I've noticed this in my jinja tpl files but it seems to also happen in the default mako template file.
The code is garbage, but I should show the bug as a minimal example.

Like I said, this is the first time I am working with html/css/alpinejs so I am not sure if this is actually a Nikola issue, but I don't know where else to start asking.
If there is any way how I can assist you with the _debugging/reproducability_ please let me know :)

Thanks!

**Comment by Kwpolska** [comment]
This seems to be caused by lxml:

```
In [1]: import lxml.html

In [2]: b = lxml.html.fragment_fromstring('    <button @click="open = false"></button>')

In [3]: b.attrib
Out[3]: {'false': ''}
```

This attribute name might be valid HTML5, but not valid XML - and this is likely to be a problem for lxml. From alpinejs’ docs, it looks like you can use `<button x-on:click="foo = 'bar'"></button>`.

**Comment by kai-tub** [comment]
Wow :o 
Blazingly fast!
Yes, that solves the issue!
Thank you very much!
