### ISSUE TITLE
Page source,html page

### ISSUE THREAD

**Issue by Xristodoulos99** [getnikola/nikola#3577]
Hello, this is an issue on the website of the project.
When clicking on "Page source" it redirects you to the "index.src.html" page but it seems to be missing the css file or it can't access.

**Comment by Kwpolska** [comment]
That's expected behavior of the *Source* button - it shows you the raw source file. And for HTML files, browsers will render those as usual. But you can use the browser’s *View source* feature or whatever to take a closer look at the HTML source.
