### ISSUE TITLE
DependencyError - taskid:sitemap:./target/sitemapindex.xml

### ISSUE THREAD

**Issue by tangyiming** [getnikola/nikola#3578]
```bash
DependencyError - taskid:sitemap:./target/sitemapindex.xml
ERROR: Task 'sitemap:./target/sitemapindex.xml' saving success: Dependent file './target/sitemap.xml' does not exist
```

what does this mean and how to fix it? do i need to create a sitemap? can anybody tell me how to create a sitemap

**Comment by tangyiming** [comment]
start a new site

**Comment by Kwpolska** [comment]
(Not sure why you got the error, Nikola auto-generates `sitemap.xml` and `sitemapindex.xml` should have picked it up.)

**Comment by tangyiming** [comment]
> (Not sure why you got the error, Nikola auto-generates `sitemap.xml` and `sitemapindex.xml` should have picked it up.)
haha I don't know neither.
