### ISSUE TITLE
Unexpected behaviour of IMAGE_THUMBNAIL_SIZE because of bigger_panoramas

### ISSUE THREAD

**Issue by JesperDramsch** [getnikola/nikola#3586]
### Environment

**Python Version:** 3.9.1

**Nikola Version:** v8.1.2

**Operating System:** Windows 10

#### The Behaviour

The task `scale_images` does not properly scale images where the side-length is twice the size of the other side. 
(Basically 2*w > h or 2*h>w)

This behaviour is not documented anywhere I could find. 

It would be great to have that information in the `conf.py` for people to consider and possibly the documentation.

#### Considerations

Modern displays work with 16:9, which is a ratio of 1.777. Change that to 16:8 and an image is already considered a panorama, which seems a bit generous to me, especially with displays getting wider these days.

#### Cause

The `resize` function in the file `/nikola/image_processing.py` takes the argument `bigger_panoramas` and is default set to `True`. 

#### Solutions

A quick fix would be to document this behaviour as expected.

My preferred solution would be introducing a "BIGGER_PANORAMA_THUMBNAILS" keyword, giving the user a choice to use this setting. I personally would switch it off on my website.

**Comment by Kwpolska** [comment]
We could take a patch documenting it. I’m not sure if it’s worth it to make it configurable though, is the larger size really problematic?

**Comment by JesperDramsch** [comment]
I think so, ultra-wide displays are 21:9 and getting relatively common. Any images for that will not be handled correctly as they're well above 2x aspect ratio

I have images at 1920x800. With Thumbnail Size set to 400, it is resized to 1600x666 instead of 400x166, which would be expected.

I have now put the thumbnail-size to 115 to get small images, because most of my website has wide-screen enabled images and the page load time difference between a 450 wide and 1600 wide thumbnail is _significant_. Obviously that makes thumbnails absolutely unusable if I have images with a lower aspect ratio.

I understand that adding more keywords would be annoying. However, I'd argue if we quickfix this through "documenting the behaviour" the threshold should be higher (aspect ratio 3 maybe) and the difference should probably not be 4x of the thumbnail size the user specifies.

**Comment by ralsina** [comment]
I'd say we could just change the limit to images that are 3:1 or more

**Comment by JesperDramsch** [comment]
I'd be happy to try my hand on a PR.

Do I simply adjust the scaling script and document the behavior in [conf.py.in](https://github.com/getnikola/nikola/blob/master/nikola/conf.py.in)?

**Comment by Kwpolska** [comment]
Great! Those two changes should be enough.
