### ISSUE TITLE
Weird hyphenation issues when page is rendered in Canterville theme

### ISSUE THREAD

**Issue by gramster** [getnikola/nikola#3590]
Hi all

My blog had not been updated in some time but I recently posted a new article, and in the course of doing that updated my version of Nikola. The result now is very strange; I have word breaks being inserted that are indicated by little 'x' characters on a reversed background. If I inspect the underlying DOM I don't see anything obvious causing hyphens to display like this, although removing the 'hyphens: auto' from screen.css at least will stop the word breaking. Does anyone know what is causing this and how to get rid of it?

You can see this at http://www.grahamwheeler.com/posts/unit-tests-that-dont-suck/

I've also put a screen shot here.

![image](https://user-images.githubusercontent.com/2762632/147722534-198e2511-e588-4c41-8d48-cacc1d974b3d.png)

**Comment by gramster** [comment]
It looks like this is an issue with the Canterville theme; I'll reopen it there.

**Comment by ralsina** [comment]
Maybe the font has no hyphen character?
