### ISSUE TITLE
E-commerce web storefront options 

### ISSUE THREAD

**Issue by mgiaco** [getnikola/nikola#3595]
Hello,

What is the best way to add a simple web shop to a nikola site?
I need something for only a few products. I do not need any payment on the site only some reservation and or ordering via a bill (checkout).

Dose anyone a nikola website with a feature like that.

many thanks

**Comment by Kwpolska** [comment]
There is no e-commerce thing integrated in any way with Nikola, but I don't think any needs to be. You can just install any popular e-commerce thing and it will do.

**Comment by mgiaco** [comment]
Do you know any good one?

**Comment by loup-brun** [comment]
@mgiaco have a look at [Snipcart](https://snipcart.com/), you can add a cart to a webpage with proper markup.
