### ISSUE TITLE
POST_SECTIONS_ARE_INDEXES option?

### ISSUE THREAD

**Issue by loup-brun** [getnikola/nikola#3596]
### Environment

**Python Version:** Python 3.8.8

**Nikola Version:** Nikola v8.2.0

**Operating System:** macOS 10.13.6

### Description:
There is the mention of `POST_SECTIONS_ARE_INDEXES` in the documentation (see [Theming](https://getnikola.com/theming.html)) but apparently has no effect, a search in the codebase returns no occurrences. Can such option be replicated? I have a collection of `posts`, say `events/*.md` which I reference in `conf.py`:

```py

POSTS = (
    ("events/*.md", "events", "event.tmpl"),
    
    # ...
)
```

I want to automatically enable indexes for such sections, as Nikola currently just does default a directory listing of the section (“Index of /events”) with no templating/styling applied.

**Comment by Kwpolska** [comment]
This documentation seems outdated and is mentioning a feature removed in Nikola v8.0.0. This setup should be able to get what you want in recent versions;

```
CATEGORY_PATH = ""
CATEGORY_PREFIX = ""
CATEGORIES_INDEX_PATH = "categories.html"
CATEGORY_ALLOW_HIERARCHIES = True
CATEGORY_DESTPATH_AS_DEFAULT = True
CATEGORY_PAGES_ARE_INDEXES = True
```

**Comment by Kwpolska** [comment]
I removed the outdated docs mentions from `theming.rst` and `template-variables.rst`.
