### ISSUE TITLE
Output from build and deploy actions goes to stderr

### ISSUE THREAD

**Issue by agmlego** [getnikola/nikola#3605]
### Environment
Python 3.7.3
Nikola v8.2.0
Debian 10.11

### Description:
The output from `nikola build` and `nikola deploy` is sent to stderr instead of stdout, so the cronjob output fills my email with spurious alerts. It would be better from a sysadmin perspective to be able to do the conventional `nikola build > /dev/null` redirection and thus only get an email when there is actually a problem, instead of "Scanning posts........done!" _ad nauseum_.

**Comment by Kwpolska** [comment]
It is appropriate for processes to send status information and logs to stderr. To solve your crontab issues, just use `nikola build > /dev/null 2>&1`.
