### ISSUE TITLE
Add emphasize-lines directive to code blocks

### ISSUE THREAD

**Issue by fvicent** [getnikola/nikola#3607]
I suggest to add the `emphasize-lines` directive to code blocks, Sphinx-like. Emphasizing lines is an already supported feature in Pygments, so the implementation is trivial. I've already patched my local Nikola installation and it has been working fine. I can submit a PR with the proper tests if you are ok with this addition.

This is an example taken from the Sphinx docs of how it works:

```
.. code-block:: python
   :emphasize-lines: 3,5

   def some_function():
       interesting = False
       print('This line is highlighted.')
       print('This one is not...')
       print('...but this one is.')
```

Line ranges are also supported, such as:

```
   :emphasize-lines: 1-3,5-9,15
```

**Comment by ralsina** [comment]
If you want to open the PR that would be great!
