### ISSUE TITLE
Nikola fails to detect Jinja2

### ISSUE THREAD

**Issue by ChillarAnand** [getnikola/nikola#3622]
### Environment

**Python Version:**
3.8

**Nikola Version:**
8.2.2

**Operating System:**
MacOS

### Description:

Unable to use Jinja based themes as Nikola is not able to find Jinja.

<img width="947" alt="Screenshot 2022-05-07 at 19 37 41" src="https://user-images.githubusercontent.com/4463796/167337802-6784e46e-1182-4c61-b317-932c1f647d2e.png">

**Comment by ralsina** [comment]
Is it possible that nikola was installed in a virtualenv or something like that which doesn't have jinja2 installed?

**Comment by ChillarAnand** [comment]
Initially I thought the same but after quick verification, it doesn't seem to be the case.

<img width="1193" alt="Screenshot 2022-05-09 at 21 11 20" src="https://user-images.githubusercontent.com/4463796/167446674-9bd81f3f-531c-4819-af26-922729223aba.png">

**Comment by Kwpolska** [comment]
@ChillarAnand Does the same thing occur when you run `python -m nikola`? Can you `import jinja2` in the `python` REPL?

(Also, we recommend using virtual environments.)

**Comment by ChillarAnand** [comment]
As shown in the above screenshot, Jinja==2.1.1 got installed somehow. It is unsupported. Upgrading Jinja2 fixed the issue.

<img width="1137" alt="Screenshot 2022-05-14 at 06 42 56" src="https://user-images.githubusercontent.com/4463796/168405337-40013ea8-df20-4916-9234-22b13dccdee6.png">

Thanks, @Kwpolska, @ralsina
