### ISSUE TITLE
Unable to render Twitter Card preview

### ISSUE THREAD

**Issue by sebelk** [getnikola/nikola#3645]
### Environment

**Python Version:**

Python 3.10.6

**Nikola Version:**

Nikola v8.2.3

**Operating System:**

Fedora 36

### Description:

It's unable to render Card preview, this is the log from https://cards-dev.twitter.com/validator:

```
INFO:  Page fetched successfully
INFO:  17 metatags were found
INFO:  twitter:card = summary tag found
INFO:  Card loaded successfully
```
Thanks in advance

**Comment by ralsina** [comment]
Can you show me the head of the generated page?

**Comment by sebelk** [comment]
Thanks @ralsina for the fast response, shame on me, I was preprendig previewimage with `-- `  instead of `.. ` 
Sorry for the noise it was a pebkac 😄 .

**Comment by ralsina** [comment]
NP happens to everyone:)
