### ISSUE TITLE
ERROR: Two different tasks can't have a common target.'output/images2/illus_001.thumbnail.jpg'

### ISSUE THREAD

**Issue by g1ra** [getnikola/nikola#3654]
### Environment

**Python Version:**  python --version
Python 3.10.6

**Nikola Version:** Nikola v8.2.3

**Operating System:** linux

### Description:

(nikola) bob@lhost:~/nikola/gekis.dev$ nikola build
Scanning posts........done!
ERROR: Two different tasks can't have a common target.'output/images2/illus_001.thumbnail.jpg' is a target for scale_images:output/images2/illus_001.jpg and scale_images:output/images2/illus_001.thumbnail.jpg.

I'm trying to resurrect an old site written in nikola back in 2019 . 

I'm trying to find out what causes this but unable to find.

Please help how to find which are these two different tasks .

**Comment by g1ra** [comment]
I'm trying to find out what causes this but unable to find.

**Comment by Kwpolska** [comment]
It looks like you have a `illus_001.thumbnail.jpg` file in your images2 folder in your source tree. Files in image folders have a thumbnail automatically generated for them, and this auto-generated thumbnails conflicts with the thumbnail file you have in your source tree. Try removing `images2/illus_001.thumbnail.jpg` and see if it helps.

**Comment by g1ra** [comment]
Thanks ! indeed removed unused files : 
output/images/illus_001.thumbnail.jpg
output/images/illus_001.jpg
then problem solved !

**Comment by ralsina** [comment]
Rename one of those two files?
