### ISSUE TITLE
image alignment bug?

### ISSUE THREAD

**Issue by samuelstanton** [getnikola/nikola#3657]
### Environment

**Python Version:** 3.10.8

**Nikola Version:**. 8.2.3

**Operating System:** macOS 12.6.1

### Description:

I have a simple home page for my blog that looks like this:

```
.. title: Home  
.. slug: index
.. type: text

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

.. image:: /images/illus_001.jpg
  :width: 25%
  :align: center

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

I would expect the sample image to be centered as described here https://restructuredtext.documatt.com/element/image.html, however this is how the alignment looks when the site is built and served

![image](https://user-images.githubusercontent.com/22999782/210196492-7dd7fa87-4f35-4ca8-b56a-ba0c3dbbe933.png)

What gives?

**Comment by Kwpolska** [comment]
Docutils output changed in a recent version, and our CSS didn’t match it. It should be fixed on `master`.

**Comment by samuelstanton** [comment]
verified it works on `master`
