### ISSUE TITLE
CSS minify-filter does not work - cssminifier.com HTTP 404

### ISSUE THREAD

**Issue by 7wop** [getnikola/nikola#3658]
### Environment

**Python Version:**

`Python 3.10.6`

**Nikola Version:**

`Nikola v8.2.3` - Installed via pip in venv

**Operating System:**

`Ubuntu 22.04.1 LTS`

### Description:

I tried to use the filter to minify the CSS-file by adding `filters.cssminify` to my configuration file.

The `cssminifier.com` is redirecting to `https://www.toptal.com/developers/cssminifier`.

The error msg:

```
LOGGER.error("can't use cssminifier.com: HTTP status {}", response.status_code)
Message: "can't use cssminifier.com: HTTP status {}"                          
Arguments: (404,)    
```

**Comment by Kwpolska** [comment]
They changed the API URL for some reason, I fixed it.
