### ISSUE TITLE
Matplotlib plot processed into black box

### ISSUE THREAD

**Issue by LucyNowacki** [getnikola/nikola#3662]
Ubuntu 22.04
Python 3.10.8
matplotlib 3.5.0
nbconvert 7.2.7
nbformat 5.7.1

The problem is that the w final jupyter notebook blog (after final conversion to deployable format) generates black boxes from matplotlib plots. It started happening after updating python's packages.

**Comment by Kwpolska** [comment]
We’ll need more details. Which Nikola version? Which packages did you upgrade recently? Can you provide a .ipynb file that causes this problem?

**Comment by LucyNowacki** [comment]
Hi again
So my specification is:
Ubuntu 22.04.1 LTS
Python 3.10.8
Nikola 8.2.3

Please look at my blog and this link to .ipynb file under which you can see that plots are rendered as black boxes. On the bottom, I've attached all python packages after the update. 

[](https://lucynowacki.github.io/blog/robust-pca/)

**Comment by Kwpolska** [comment]
I was able to reproduce this issue by just running `jupyter nbconvert --to html robust-pca.ipynb`, which means it is not an issue with Nikola. Please report this bug to the [jupyter/nbconvert](https://github.com/jupyter/nbconvert) repository.

This issue occurs for me with `nbconvert==7.2.7`, but does not occur with `nbconvert==6.5.0`.

**Comment by LucyNowacki** [comment]
I downgraded to nbconvert==6.5.0 however; unfortunately, the issue still occurs.

**Comment by Kwpolska** [comment]
Did you rebuild all files by using `nikola build -a`?

**Comment by LucyNowacki** [comment]
Hi
I set u a new environment from conda, but installed all needed packages from Anaconda (they are usually older than from pip) and everything works perfectly :).
