### ISSUE TITLE
needed Jinja downgrade

### ISSUE THREAD

**Issue by LucyNowacki** [getnikola/nikola#3664]
### Environment

**Python Version:**

**Nikola Version:**

**Operating System:**

### Description:
To generate python code in jupyter for the blog it is necessary to downgrade jinja2  as follows

pip install Jinja2==3.0.3

probably it is necessary to change in Nikola package for this

from markupsafe import escape

**Comment by Kwpolska** [comment]
This issue contains zero details. Without any details, we cannot do anything with it. Please always include information about what goes wrong (errors) and anything that could help us debug.
