### ISSUE TITLE
google indexing always fails with redirect error 

### ISSUE THREAD

**Issue by RavikumarTulugu** [getnikola/nikola#3666]
Google indexing always complains "redirect error" when trying to index my website. i have a blog which is getting generated by nikola engine. i am following this procedure. I do a build with  "nikola build" and copy all the files and folders under "output" directory to my blog folder. Every thing works fine but google indexing always complains "redirect error". Please advise.

**Comment by Kwpolska** [comment]
1. Are there more details about the error?
2. What is the site? Where is it hosted?
3. Are you using any form of redirects (in your web server, via Nikola REDIRECTS)?

**Comment by RavikumarTulugu** [comment]
the site is https://peerdrive.net and the URL is https://peerdrive.net/blog/index.html
I have one redirect rule  which redirect http --> https

**Comment by Kwpolska** [comment]
Is there more information from Google about the error?

**Comment by RavikumarTulugu** [comment]
unfortunately no, i use google search console app and request indexing , i get a mail after few days that the 'indexing' failed.

**Comment by Kwpolska** [comment]
Are you sure? I’ve received some messages from Google Search Console, and they have a button to fix the issue, and you can find more information in the console.

Many Nikola websites index just fine. Without any details, we cannot help.

**Comment by RavikumarTulugu** [comment]
ok , let me dig more information and get back.
