### ISSUE TITLE
Several references to old removed option "bootswatch_theme"

### ISSUE THREAD

**Issue by ChrisJefferson** [getnikola/nikola#3680]
I spent a while trying to use "bootswatch_theme", as mentioned:

* https://themes.getnikola.com/v8/bootstrap4/
* https://docs.getnikola.com/en/latest/extending.html

* pages/extending.rst when I run `nikola init --demo`

However, it seems this option was removed, and replaced by `nikola subtheme`?

**Comment by Kwpolska** [comment]
Thanks for reporting this! I fixed all the mentions and redeployed the listed pages.
