### ISSUE TITLE
Add alternative Docker image to documentation

### ISSUE THREAD

**Issue by paddy-hack** [getnikola/nikola#3685]
I've been "maintaining" an [Alpine Linux](https://www.alpinelinux.org/)-based `nikola` Docker image for a while now (since 2016 :wink:) over at GitLab.com, see [`paddy-hack/nikola`](https://gitlab.com/paddy-hack/nikola).  Maintenance runs mostly on auto-pilot and checks for new releases on a weekly basis.  The image is [tested](https://gitlab.com/paddy-hack/nikola/-/blob/master/test.sh) using the demo site and only published when the test(s) pass.

BTW, this image is used by the [`nikola` GitLab Pages example](https://gitlab.com/pages/nikola). 

Seeing that the [Getting Started - Docker](https://getnikola.com/getting-started.html#installDocker) section mentions an image that has not been updated since mid August 2021 (and doesn't link to the Dockerfile used to build it) as well as an alternative that requires building the image yourself (rather than just pulling), I figured I'd mention mine in case you want to update the documentation.

**Comment by Kwpolska** [comment]
Thanks, I updated the docs to point to your image (and also improved some other stale things in the getting-started document along the way).

**Comment by paddy-hack** [comment]
Thanks for the quick follow-up.

**Comment by paddy-hack** [comment]
Thanks for the quick follow-up.
