### ISSUE TITLE
Discourse comments

### ISSUE THREAD

**Issue by Mte90** [getnikola/nikola#3689]
There is a discourse plugin for jekyll https://github.com/oblakeerickson/jekyll_discourse_comments/blob/master/discourse_comments.rb as we can see just print a javascript code with the url of the discourse thread.
So a nikola plugin should have just a parameter in the article and the plugin installed.

**Comment by Kwpolska** [comment]
(Moved from getnikola/plugins to getnikola/nikola, as comment systems cannot be plugins.)

**Comment by Mte90** [comment]
Note for myself to work on this:

* https://github.com/getnikola/nikola/blob/7f6ae4fbe8ac6178c2a706ae279f3c17ad3f40e8/nikola/data/themes/base/templates/comments_helper_disqus.tmpl a duplicate template file with the changes needed
* https://github.com/getnikola/nikola/blob/7f6ae4fbe8ac6178c2a706ae279f3c17ad3f40e8/nikola/nikola.py#L97 to add the new comment system 

My doubt is how to get in the template the new field that I have to add for the discourse thread link. The `comment_link_script` macro doesn't have the post object and the `comment_form` doesn't have the post object too.

**Comment by Kwpolska** [comment]
Looking at the Jekyll plugin and at [this Discourse forum thread](https://meta.discourse.org/t/embed-discourse-comments-on-another-website-via-javascript/31963), the `discourseEmbedUrl` is just the post URL, and the `comment_form` function gets the URL as a parameter. (`comment_link_script` is used on index pages, it is a script that shows the comment count in post headers — this is an optional feature.)

**Comment by Mte90** [comment]
You are right, a html snippet generate by the jekyll plugin:
```
<script type="text/javascript">
                            DiscourseEmbed = { discourseUrl: 'https://forum.linux.it/',
                            discourseEmbedUrl: 'https://www.ils.org/2023/05/10/mergeit-2023.html' };

                            (function() {
                                var d = document.createElement('script'); d.type = 'text/javascript'; d.async = true;
                                d.src = DiscourseEmbed.discourseUrl + 'javascripts/embed.js';
                                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(d);
                            })();
                        </script>
```
