### ISSUE TITLE
Change in paragraph spacing for reST files

### ISSUE THREAD

**Issue by friedelwolff** [getnikola/nikola#3704]
### Environment

**Python Version:**
3.8

**Nikola Version:**
Nikola==8.2.4

**Operating System:**
Linux

### Description:
A recent update causes undesirable layout for simple .rst files. In something like this:
```reST
Heading 1
---------
Paragraph 1

Paragraph 2

Heading 2
---------
Paragraph 3
```
There is no bottom margin on the p tag of Paragraph 2, due to this line:
https://github.com/getnikola/nikola/commit/c02d0fc85f2f93aac7b9d385d83674502fb93b25#diff-1db3a04ef500101f2ec02cdcac07f73dfc53f67f98ff8be77d2570bb530d67f6R77
Consequently there is a bigger margin below the h2 than above it.

That CSS file seems to be externally maintained, so I'm not sure what is the best to do here.

**Comment by Kwpolska** [comment]
Thanks for reporting, fixed in `master`. This CSS file comes from docutils, but we don’t mind modifying it if it does dumb stuff (and in recent versions, they started doing a lot of dumb stuff).
