### ISSUE TITLE
Add a custom sub-directory to a static website?

### ISSUE THREAD

**Issue by pritam-dey3** [getnikola/nikola#3711]
Hello, I am creating a static website with nikola, and I want to add a page that has its own css and javascript frameworks and its own assets folder. I want to just add this new page as a subdirectory. What is the easiest way I can add this subdirectory to the outputs folder so that `nikola build` automatically updates the files and folders inside this subdirectory?

**Comment by Kwpolska** [comment]
Anything in `files/` will be copied to `output/` directly, and you can have subdirectories in the `files/` directory.
