### ISSUE TITLE
.doit.db.dat file getting bigger and bigger.

### ISSUE THREAD

**Issue by partrita** [getnikola/nikola#3714]
I use github page to depoyments. buy my `.doit.db.dat` file is now 58 Mb. 
As you know, github allows under 50 Mb per file(except for Git LFS).
Is there anyway to reduce file size?

Thank you in advance.

**Comment by Kwpolska** [comment]
You shouldn’t commit `.doit.db.*` and `cache` to git, they are transient state.

If the file seems too large nevertheless, you can try removing it, it will be re-created and might end up being smaller

**Comment by partrita** [comment]
> You shouldn’t commit `.doit.db.*` and `cache` to git, they are transient state.
> 
> If the file seems too large nevertheless, you can try removing it, it will be re-created and might end up being smaller

Oh, I didn't know that. Thanks!
