### ISSUE TITLE
Nikola is not compatible with lxml 5.1.0

### ISSUE THREAD

**Issue by aknrdureegaesr** [getnikola/nikola#3732]
### Environment

**Python Version:**
3.9 (not relevant)

**Nikola Version:**
Git commit b96f05a2f8e6f5b60073ca1fb6b24f3e35094db8 (not very relevant)

**Operating System:**
Debian GNU Linux "Bullseye" (probably not relevant)

### Description:

When lxml increased their version from 4.9.4 to 5.1.0, our tests started to fail.

**Comment by Kwpolska** [comment]
This is a lxml regression: https://bugs.launchpad.net/lxml/+bug/2048920

This specific case should be simple to work around.
