### ISSUE TITLE
Nikola plugin comand does not work

### ISSUE THREAD

**Issue by msghens** [getnikola/nikola#3736]
### Environment

**Python Version:**
Python 3.8.10

**Nikola Version:**
Nikola v8.3.0

**Operating System:**
WSL

NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"

### Description:
When I enter the command:
*nikola plugin*

I get:

[2024-01-11 08:15:22] ERROR: Nikola: Unknown command plugin
[2024-01-11 08:15:22] INFO: Nikola: Did you mean "clean"?

**Comment by Kwpolska** [comment]
That’s a fairly awkward bug. You can manually apply the patch in cec44aeb445161096303f1abc2df9c0980ab14cb, or a new release might be out soon.
