### ISSUE TITLE
missing annotation_helper.tmpl

### ISSUE THREAD

**Issue by allenbrunson** [getnikola/nikola#3773]
### Environment

**Python Version:** 3.12.3

**Nikola Version:** 8.3.1

**Operating System:** macOS 14.4.1

### Description:

i have been using the bootstrap3 theme for my blog for a few years now, but a recent nikola update has broken it, due to the fact that annotation_helper.tmpl is missing. it appears that many of the built-in themes are suffering from this bug. bootstrap3-jinja is also broken, for example. i get an error like this when trying to build my site:

Scanning posts........done!
[2024-05-06 23:08:29] ERROR: Nikola: Error loading tasks. An unhandled exception occurred.
[2024-05-06 23:08:29] ERROR: Nikola: jinja2.exceptions.TemplateNotFound: annotation_helper.tmpl
[2024-05-06 23:08:29] WARNING: Nikola: To see more details, run Nikola in debug mode (set environment variable NIKOLA_DEBUG=1) or use NIKOLA_SHOW_TRACEBACKS=1

i was able to fix this by putting a blank file with name of the missing template into the theme's templates directory.

looking at other issues, it appears you guys are phasing out that annotation template file, and have therefore removed it from a lot of the themes. but apparently, you have not also removed all the code that references that template file.

so, i would suggest either re-adding that template file to the now-broken themes, or finish removing the code within nikola that references it.

**Comment by Kwpolska** [comment]
I re-added the files with dummy content.

**Comment by allenbrunson** [comment]
great! looks good to me.
