### ISSUE TITLE
CSS: Add `margin-bottom: 1rem` to `img` (default theme)

### ISSUE THREAD

**Issue by sjehuda** [getnikola/nikola#3777]
Please add `margin-bottom: 1rem` to `img` (default theme).

https://slixfeed.woodpeckersnest.space/posts/slixfeed-news-bot/#preview

Before:
![image](https://github.com/getnikola/nikola/assets/19249089/8468307b-dd9d-46bf-bd6c-58e76118135a)

After:
![image](https://github.com/getnikola/nikola/assets/19249089/d17d5845-c56a-46f4-bdaf-2312146f4012)

### Environment

**Python Version:**
3.12.3
**Nikola Version:**
8.3.1
**Operating System:**
Arch Linux

**Comment by Kwpolska** [comment]
This will break many more things than it will fix. Put your images in `<p>` or `<figure>`, or a `<div>` with the CSS you want.
