### ISSUE TITLE
Watchdog 5 rebuild loop

### ISSUE THREAD

**Issue by chris48s** [getnikola/nikola#3788]
### Environment

**Python Version:**

3.10

**Nikola Version:**

8.3.1

**Operating System:**

Ubuntu 22.04

### Description:

I tried upgrading my project from Watchdog 4 to [Watchdog 5](https://github.com/gorakhargosh/watchdog/blob/master/changelog.rst#500). Running `nikola auto` puts me into a loop of rebuilding the page and logging

```
[2024-09-01 16:45:29] ERROR: asyncio: Task exception was never retrieved
future: <Task finished name='Task-2935' coro=<CommandAuto.reload_page() done, defined at /home/chris/.cache/pypoetry/virtualenvs/blogmarks-P_QwLesb-py3.10/lib/python3.10/site-packages/nikola/plugins/command/auto/__init__.py:427> exception=ValueError('no path specified')>
Traceback (most recent call last):
  File "/home/chris/.cache/pypoetry/virtualenvs/blogmarks-P_QwLesb-py3.10/lib/python3.10/site-packages/nikola/plugins/command/auto/__init__.py", line 435, in reload_page
    p = os.path.relpath(event_path, os.path.abspath(self.site.config['OUTPUT_FOLDER'])).replace(os.sep, '/')
  File "/usr/lib/python3.10/posixpath.py", line 470, in relpath
    raise ValueError("no path specified")
ValueError: no path specified
```

over and over.

Reverting back to Watchdog 4 resolves this.

**Comment by Kwpolska** [comment]
This should be fixed on the main branch, could you try?

**Comment by chris48s** [comment]
Ah yes. Apologies if this is a duplicate. I did try searching the issue tracker for "watchdog" before raising this but couldn't see anything raised more recently than the release of watchdog 5 last week.
