### ISSUE TITLE
Post year is not compiled properly

### ISSUE THREAD

**Issue by aledeg** [getnikola/nikola#3807]
### Environment

**Python Version:** 3.13.1

**Nikola Version:** 8.3.1

**Operating System:** archlinux

### Description:
I've created a blog post today with the current date (**2024-12-31 11:01:05 UTC-05:00**) but it's displayed as **2025-12-31**.

The post itself is properly stored in the folder **2024/12**.

I am using the **lanyon** theme.

The weird thing is the output. Here is the content of my generated file:
```html
<p class="dateline"><a href="." rel="bookmark"><time class="post-date published dt-published" datetime="2024-12-31T11:01:05-05:00" itemprop="datePublished" title="2025-12-31">2025-12-31</time></a></p>
```
There is a mix-and-match between 2024 and 2025.

Is this bug related to nikola?

**Comment by Kwpolska** [comment]
This is probably an issue with your `DATE_FORMAT` setting. `YYYY` means “year in [ISO week](https://en.wikipedia.org/wiki/ISO_week_date)”, and that’s already 2025. Change your `DATE_FORMAT` to use `yyyy`.

**Comment by aledeg** [comment]
Good catch. That is the problem I had. Thank you
