### ISSUE TITLE
Importing from Wordpress: Some posts might already be Markdown

### ISSUE THREAD

**Issue by rassie** [getnikola/nikola#484]
It's possible to use Markdown (also Textile and AutoP) with Wordpress using the [TextControl plugin](http://plugins.trac.wordpress.org/wiki/TextControl). In that case, the export file contains:

    <wp:postmeta>
        <wp:meta_key>_tc_post_format</wp:meta_key>
        <wp:meta_value><![CDATA[markdown]]></wp:meta_value>
    </wp:postmeta>

Would be nice if the importer supported that.

**Comment by ralsina** [comment]
Sorry about taking two years to fix this :-)
