### ISSUE TITLE
Posts: Auto tagging, clouds, nicer links, related posts

### ISSUE THREAD

**Issue by rogerbinns** [getnikola/nikola#579]
These are all under the same umbrella for posts:

* For previous and next nav links at the bottom of the page say what the title of the prev/next article is

Do semantic analysis of posts

* Automatically tag them
* Show a tag cloud
* At the bottom of each post show related posts

**Comment by Kwpolska** [comment]
1. hover links to see titles
2. this is hard, let’s not bother — besides, we would have to make it an optional plugin that nobody would use
3. already doable on your own (we generate json files you can use)
4. requires rebuilds of all posts, the only way to do it would be to use tag cloud data and client-side JS for that
