### ISSUE TITLE
Meta - extract metadata from filecontent

### ISSUE THREAD

**Issue by areski** [getnikola/nikola#618]
As there is a plan for V6, I wonder if it will not be better that we review how we extra metadata from filecontent.

Both options are working now:
>> how-it-works.meta
How it works
how-it-works
.. date: 2012/03/30 23:00
.. tags: emerzia, how it works
.. link: http://www.emerzia.com
.. description: Emerzia is a reverse emergency notification system to broadcast messages via voice or SMS to large numbers or people in a short space of time.

2nd:
>> how-it-works.meta
.. title: How it works
.. slug: how-it-works
.. date: 2012/03/30 23:00
.. tags: emerzia, how it works
.. link: http://www.emerzia.com
.. description: Emerzia is a reverse emergency notification system to broadcast messages via voice or SMS to large numbers or people in a short space of time.

It seems that option 2nd is a better bet for future and keep some sane clarity for new users. 

It's sometime better to have less way of doing the same things...

**Comment by ralsina** [comment]
Actually, this is already done for a long time. I will open a different issue for what I want to do ;-)
