### ISSUE TITLE
Google Plus comments are not really working...

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#635]
I built a demo site to test them:

http://googleplus.ralsina.com.ar/posts/welcome-to-nikola.html

When I click to make a comment it pops a window, then it closes and nothing happens.

**Comment by ralsina** [comment]
@matclab I will take a look but if we can't find a way to make it work I guess I will just remove this.

**Comment by Kwpolska** [comment]
Google+ is dead, and so is their comment system. I’ve removed it in PR #2966.
