### ISSUE TITLE
Gallery window resize bug

### ISSUE THREAD

**Issue by max-arnold** [getnikola/nikola#687]
Just found some weird gallery behavior when browser window is resized. Steps to reproduce:

1. Open any gallery (like http://localhost:8000/galleries/my-gallery)
2. Resize browser window to make it smaller than gallery area (some images at the bottom should be hidden)
3. Resize browser window back to original size
4. Watch gallery images repeated multiple times (I also got high CPU usage on Firefox)

This is probably related to image placement logic implemented in javascript. Reproduced with Safari/Chrome/Firefox on OS X.

**Comment by ralsina** [comment]
Doesn't happen anymore, was never our bug, so, closing.
