### ISSUE TITLE
Wordpress import: does not create paragraphs properly

### ISSUE THREAD

**Issue by humitos** [getnikola/nikola#692]
After importing my old Worpress site (http://humitos.wordpress.com) I realized that wordpress creates just one big paragraph (`<p>`) for the whole content and adds `^M` between the paragraphs inside the big one. For example:

    <p>Hello, this is my blog post.^M

    This is another paragraph for Wordpress.com^M

    ... and this one is another one</p>

So, after the import, I had just one big paragraph, like this:

    <p>Hello, this is my blog post.

    This is another paragraph for Wordpress.com

    ... and this one is another one</p>

I did some change to fix that issue in my importation:

    diff --git a/nikola/plugins/command/import_wordpress.py b/nikola/plugins/command/import_wordpress.py
    index 1aded89..6468104 100644
    --- a/nikola/plugins/command/import_wordpress.py
    +++ b/nikola/plugins/command/import_wordpress.py
    @@ -332,7 +332,7 @@ class CommandImportWordpress(Command, ImportMixin):
         def transform_multiple_newlines(self, content):
             """Replaces multiple newlines with only two."""
             if self.squash_newlines:
    -            return re.sub(r'\n{3,}', r'\n\n', content)
    +            return re.sub(r'\n{3,}', r'</p>\n\n<p>', content)
             else:
                 return content

I'm posting this here because maybe it's useful.

**Comment by ralsina** [comment]
@humitos can you check if this still happens with current release? If it does I will fix it.

**Comment by ralsina** [comment]
No answer means no fix :-)

If anyone sees this, feel free to reopen or file a new issue.
