### ISSUE TITLE
progress bar output

### ISSUE THREAD

**Issue by schettino72** [getnikola/nikola#769]
Roberto first expressed the idea here: https://groups.google.com/d/msg/python-doit/MKTv4cnBlkI/GejSik7FjIEJ

I put together a trivial demo to demonstrate how this can be done using doit...
see: https://gist.github.com/schettino72/6730907

* You need to patch doit to pass all the tasks info to the reporter before start building the site. I will add this or whatever is needed by Nikola, so if you are playing with this feel free to add more calls to the "reporter" API.

* I used my own script for terminal manipulation. Of course any other library could be used. Its source is on https://bitbucket.org/schettino72/pyterm

You will need the file pyterm.py and sample_bar.py

Sorry no docs for this lib. If you look at sample_tutorial (6 lines of code) should be enough for you to get it. any questions, just ask...

**Comment by ralsina** [comment]
Giving up.
