### ISSUE TITLE
PDF Support.

### ISSUE THREAD

**Issue by Madawar** [getnikola/nikola#788]
It is possible to convert .rst files to PDF with rst2pdf, i have been able for a while to do it manually as described here http://www.codedcell.com/posts/best-way-to-setup-nikola-with-pdf-support.html. Would you mind adding support for PDF's?

**Comment by pwm1234** [comment]
I also would like to be able to convert my nikola blog to something printable. What I would like to have would be more a *nikola2sphinx* conversion. I could then tweak the converted content and reuse (and print) using a conventional sphinx approach. Please ignore this comment if it does not make sense from an implementation standpoint. I am just a happy user of both Nikola and Sphinx and am delighted with the sphinx plugin. I want to encourage more compatibility between the two.
Thanks!

**Comment by ralsina** [comment]
Since we as a project claim to support multiple markups, the only reasonable path is to go via HTML print CSS.

**Comment by ralsina** [comment]
Superseded by #1817

**Comment by Kwpolska** [comment]
So basically, you want visitors creating their own PDF via their browser’s *Print* function?

**Comment by ralsina** [comment]
Exactly.
