### ISSUE TITLE
Planetoid has leftover bits of Spanish

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#798]
Lines [188](https://github.com/getnikola/nikola/blob/092b4887c9e352c100a021025c975069d29706fc/nikola/plugins/command/planetoid/__init__.py#L188) and [195](https://github.com/getnikola/nikola/blob/092b4887c9e352c100a021025c975069d29706fc/nikola/plugins/command/planetoid/__init__.py#L195)

Shouldn’t we introduce new translation strings for those two?

**Comment by ralsina** [comment]
Planetoid is in plugins, and somewhat unmaintained, now.

**Comment by Kwpolska** [comment]
Was it *ever* maintained in the first place?

**Comment by ralsina** [comment]
@Kwpolska it was even used in production until recently.
