### ISSUE TITLE
Configurable logging handlers

### ISSUE THREAD

**Issue by DDevine** [getnikola/nikola#817]
I'd like to have more logging handlers such as email and XMPP.

The use case is for when Nikola is set up to automatically compile posts uploaded over FTP, or whatever - the user should be notified of compile errors and warnings - as they can't see the errors because they can't see stdout.

Adding a bunch of handlers is easy as far as the code goes (just register them with Logbook).

The configuration directive should probably be in the from of a dictionary with the name of the handler as the key and the arguments (username, password, ...) as the value.

```
LOGGING_HANDLERS = {
    "smtp" : ['username', 'password', 'host', 'warn'],
}
```

The above configures an email logging handler, and the handler should also take a logging level (debug, info, warn, error...)

There should also be new directory to dump the various logging handlers in rather than cramming utils.py full of handlers.

Comments?

**Comment by sjehuda** [comment]
Is it possible to send logs to XMPP via Nikola?

If not, I would like to suggest to add XMPP too and I am willing to offer help.

**Comment by Kwpolska** [comment]
@sjehuda The logging handlers feature was actually removed some time ago due to very low usage and benefit. If someone is running Nikola headless, they can set up their own thing to log to email or XMPP if they are still somehow using it.

**Comment by sjehuda** [comment]
Thank you for the information.

It is definitely good for us as we use both Email and XMPP for monitoring system activity.
