### ISSUE TITLE
Tornado doesn't redirect for directories

### ISSUE THREAD

**Issue by rogerbinns** [getnikola/nikola#834]
When using nikola auto, tornado doesn't redirect to trailing slash for directories.

For example if a request comes in for /galleries/example then it serves up the index.html directly.  It should redirect to /galleries/example/ (trailing slash).

Failing to do this breaks links within the page.  For example:

INFO:tornado.access:200 GET /galleries/2013%20Santa%20Cruz%20Day (127.0.0.1) 1.09ms

Note the 200 and not a redirect.  The the images fail to load because they don't have the gallery directory.

WARNING:tornado.access:404 GET /galleries/03.thumbnail.JPG (127.0.0.1) 0.55ms

**Comment by ralsina** [comment]
Closing because life's too short.
