### ISSUE TITLE
Include directive broken

### ISSUE THREAD

**Issue by v6sa** [getnikola/nikola#932]
Hi,

docutils says that include directive argument is the path to the file to be included, relative to the document containing the directive.

http://docutils.sourceforge.net/docs/ref/rst/directives.html#including-an-external-document-fragment

Currently include directives fail because nikola attempts to look up referenced files from the current working directory.

How to reproduce:

1. Create file foo.rst in posts/
2. Create bar.rst in posts/ and insert `.. include:: foo.rst`
3. Issue `nikola build`

**Comment by Kwpolska** [comment]
@ralsina any resolution on this one?  IMO just documenting our behavior should suffice; any changes will break tons of blogs…

On a side note: does docutils have any sort of “if nikola/if sphinx” facility?

**Comment by ralsina** [comment]
@Kwpolska I think documenting is enough, yes. I don't understand the question, tho.

**Comment by Kwpolska** [comment]
pseudocode:

```rest

.. if:: nikola

   Nikola-specific reST goes here, like the include directive with site-root-relative paths

.. if:: sphinx

   Sphinx-specific reST goes here, like the include directive with input-file-relative paths
```

(very unlikely to be a thing)

**Comment by ralsina** [comment]
Actually, sphinx has [such a thing](http://sphinx-doc.org/ext/ifconfig.html). I could add it to Nikola :-)
